### ISSUE TITLE
Allow trace logs to be fully disabled

### ISSUE THREAD

**Issue by tobdub-snce** [eclipse-paho/paho.mqtt.c#1000]
**Is your feature request related to a problem? Please describe.**
Currently the trace log level can not go higher than TRACE_MINIMUM. Even at TRACE_MINIMUM logs are generated for every message. It would be nice to be able to disable the logs to improve performance.

**Describe the solution you'd like**
Allow the trace log level to be set higher than TRACE_MINIMUM, e.g. only log errors.
It would be nice if only logging errors was the default setting and more logs could be enabled by opt in.

**Describe alternatives you've considered**
Change log level for logs generated for every message to TRACE_MEDIUM or lower.

**Comment by fpagliughi** [comment]
Aren't there already levels for ERROR and PROTOCOL?

**Comment by tobdub-snce** [comment]
The levels exist, but they can't be used for `trace_level` as far as I understand, see e.g. https://github.com/eclipse/paho.mqtt.c/blob/7c79e3073c241f39884553dec01a7a5c6d02eb4c/src/Log.c#L228

**Comment by icraggs** [comment]
Yes.   There are levels for ERROR and PROTOCOL.   See the use in the command line utilities such as paho_c_pub.  For instance:

paho_c_pub x --trace protocol --host mqtt.eclipse.org

Also, the stack trace and other details can be compiled out with the CMake PAHO_HIGH_PERFORMANCE option.

**Comment by tobdub-snce** [comment]
It seems `trace_level` can not be set higher than `TRACE_MINIMUM`?
```c
void Log_setTraceLevel(enum LOG_LEVELS level)
{
	if (level < TRACE_MINIMUM) /* the lowest we can go is TRACE_MINIMUM*/
		trace_settings.trace_level = level;
	trace_output_level = level;
}
```

Even with `trace_output_level` set to `LOG_ERROR` there is still a fair amount of overhead from the Mutex and the `vsnprintf` in the `Log` function.

**Comment by icraggs** [comment]
That's why you can build with PAHO_HIGH_PERFORMANCE if you want to.

**Comment by tobdub-snce** [comment]
Already using `PAHO_HIGH_PERFORMANCE`, but it doesn't seem to affect the logging?

**Comment by icraggs** [comment]
It does affect the logging - all the stack trace statemnents are removed.  I suppose the minimum could allowed could be ERROR.  There aren't many messages still written when the "high performance" option is used.

**Comment by tobdub-snce** [comment]
What I see in my trace seems to be mostly this call to `vsnprintf`: https://github.com/eclipse/paho.mqtt.c/blob/7c79e3073c241f39884553dec01a7a5c6d02eb4c/src/Log.c#L434
Even though the log is not output there is still some overhead caused by the logging call. I see around 5-8% CPU time spent on logging even though no log is visible. There are some logs for every received message even with `PAHO_HIGH_PERFORMANCE`.

**Comment by icraggs** [comment]
That would be the protocol tracing.

You could change the TRACE_MINIMUM to TRACE_ERROR in setTraceLevel, set the trace level to ERROR, and see what the consequences of that are.

**Comment by tobdub-snce** [comment]
I tried to set the default trace level to `LOG_ERROR` and removed the trace level restriction in `Log_setTraceLevel`. In my test case (just counting received messages) I can see the `Log` CPU time drop from 10% to 0%.
I didn't see any issues, but I'm not sure what the consequences of this change are since I haven't used the trace functionality.
Maybe one option could be to set the trace level to `LOG_ERROR` if `PAHO_HIGH_PERFORMANCE` is set?

**Comment by icraggs** [comment]
I'm just going to make that change for now.  Turning off the tracing just means that there will be less debugging information available if that were the only time a problem showed itself.  But that's rarely the case.

**Comment by tobdub-snce** [comment]
Should it be `<= LOG_ERROR`?
