### ISSUE TITLE
Persistence now calling free() on its context

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#1001]
It looks like the behavior of the persistence has now changed, and it is now taking ownership of its `context`?

It seem that these lines were added in a recent release:

https://github.com/eclipse/paho.mqtt.c/blob/7c79e3073c241f39884553dec01a7a5c6d02eb4c/src/MQTTPersistence.c#L147-L148

In the C++ and Rust clients, the context is pointing to a C++ or Rust object, respectively, which may or may not have been allocated by the system allocator, and likely wants to be deconstructed and not just freed.

So, now I am getting a segfault when an app exits that has user-defined persistence, which I _think_ is happening because the context memory is being free'd before the object is deconstructed by the app (segfault and potential double-free).

**Comment by icraggs** [comment]
It was a fix for https://github.com/eclipse/paho.mqtt.c/issues/809

**Comment by fpagliughi** [comment]
Hmm. Sorry I didn't notice this sooner. I'm just getting around to working with user-based persistence for the first time in a while.

OK. I see it. I'm thinking, though, that this was a breaking change for user persistence, and it kinda goes against the rest of the API in that a _context_ pointer supplied by the application is just an opaque value to the library - left to the app to manage.

Anyway, I think the update is trivial in order to keep the fix for #809, but restore the original behavior for user persistence: Only free the context if using the default persistence.

If I understand it, the persistence type is not stored by the lib, but it can figure it out by looking at _popen_?
If so, the context free should probably go inside the condition that immediately follows it:
```
if (c->persistence->popen == pstopen) {
    if (c->persistence->context)
        free(c->persistence->context);
    free(c->persistence);
}
```
I can at least test it to see if it fixes my segfault.

**Comment by fpagliughi** [comment]
Yes. That fixes my crash, and I assume that it doesn't break the fix for #809.

**Comment by icraggs** [comment]
The default persistence stuff wasn't written by me, so I don't remember what was done.  I'm thinking about what the correct approach is.

**Comment by fpagliughi** [comment]
Well I think it's fine and proper for the default file persistence to do whatever it likes (or needs to do) with the context. In that case, the library creates the context, "owns" the context, and thus the library can (and should) delete the context when it's done with it.

With user-defined persistence, however, the application supplies the context, and the application should be considered to "own" it, not the library. The library should not delete it.

As an example, for my C++ apps that have user-defined persistence, the persistence object (context) is actually pointing to an object declared on the stack in main()!  So no one should be trying to delete it at all.

But the main point here is that the update for #809 broke every Rust and C++ client that has user-defined persistence, with a hard segfault when the client is closed. So I probably can't release those liraries until this is resolved.

PR #1002 should fix it _and_ keep the fix in for #809.

**Comment by icraggs** [comment]
OK, sounds good.  Out of interest, are you using user defined persistence to provide an actual different persistence implementation?

I can add an interim 1.3.8 release to include just this fix and any others that seem essential or useful for the Rust/C++ clients.

**Comment by fpagliughi** [comment]
Yes.

On an Embedded Linux system where you need persistence, you often don't want to use the local file system because that will wear out the Flash chip rather quickly. But you do want to store the data out of the running client process. A good solution is to send the persistence data to a local, on-board, in-memory, key/value store.

My favorite for this is Redis. Most people think of it as a "big" cloud application, but it is really a small, efficient C program and works well on an embedded Linux board.

I even have a public drop-in Redis solution for the Rust client:
https://github.com/fpagliughi/mqtt.rust.redis

Users can add one line to their build file and one line to their Rust application and get Redis persistence.

The way the C lib sets up user persistence is awesome. The operations map directly to individual Redis commands, so the whole extension for the Redis is <100 lines of code.

**Comment by icraggs** [comment]
Cool.  I have a redis implementation written by a colleague of mine on my hard drive.  I could add it as a sample, although it might add to the maintenance workload :-)

**Comment by fpagliughi** [comment]
Yeah, I had contributed to a C++ Redis client a few years back when I first started using it with Paho, but I never tried to include it with the Paho library because it was a little messy for inclusion (download, build, link, etc).

With Rust the build process is so easy, so it seemed worth doing. _But_ even there, I made it as a totally separate, extra, library outside of Paho. I just mentioned it and put a link to it at the bottom of the Paho README.

Although I keep saying that one of these days, I'm going to blog about a bunch of this stuff...

**Comment by jumoog** [comment]
maybe its a good idea to start thinking about a "plugin" system?

**Comment by icraggs** [comment]
@jumoog I'm not sure what a plugin system would look like over and above what we have now.  

Apart from that, I don't really want to add any large amount of additional (non-core?) functionality like that unless someone a) pays me to (see Github sponsors) or b) contributes it as a PR, along with tests/doc leaving me little extra to do or c) becomes a committer willing to share the long-term maintenance and enhancement workload.  Or a combination of the 3 :-)

c) would be really useful anyway, for the longevity of the project.  I realize that maintenance of an existing code base is not the most exciting prospect (even for those who created it!) but someone has to do it for a project to continue.
