### ISSUE TITLE
How to connect CA signed server certificate

### ISSUE THREAD

**Issue by hfbuhun** [eclipse-paho/paho.mqtt.c#1006]
how to use paho.mqtt to connect like this

![2](https://user-images.githubusercontent.com/31332231/100582809-c6147200-3324-11eb-90d4-e1483354558e.jpg)
![1](https://user-images.githubusercontent.com/31332231/100582818-cad92600-3324-11eb-95d6-6267834c3796.jpg)
to connect mqtt server use tls. who can help me！Thanks

**Comment by jumoog** [comment]
the easiest way is to disable the check
`enableServerCertAuth = 0`

**Comment by luckstartc** [comment]
I tried it but it didn't work

		ssl_opts.verify = 0;
		ssl_opts.sslVersion = MQTT_SSL_VERSION_TLS_1_2;
		ssl_opts.enableServerCertAuth = 0;
		conn_opts.ssl = &ssl_opts;

**Comment by hfbuhun** [comment]
@jumoog 
I tried it but it didn't work

	ssl_opts.verify = 0;
	ssl_opts.sslVersion = MQTT_SSL_VERSION_TLS_1_2;
	ssl_opts.enableServerCertAuth = 0;
	conn_opts.ssl = &ssl_opts;

**Comment by jumoog** [comment]
What SSL error do you get?

**Comment by icraggs** [comment]
Might be easiest to include a trace at the PROTOCOL level, as described in the readme.  It looks like you also set the MQTT username and password.

**Comment by hfbuhun** [comment]
@icraggs @jumoog Thanks for your help! To use the MQTT.fx software we do not need a certificate to be able to connect to the MQTT server,I will paste the paho.mqtt.c error message tomorrow

**Comment by hfbuhun** [comment]
@jumoog @icraggs   This is the error message
![11](https://user-images.githubusercontent.com/31332231/100689408-61f2bc00-33bf-11eb-90e2-d18b6af3d078.jpg)
![22](https://user-images.githubusercontent.com/31332231/100689441-71720500-33bf-11eb-8769-5985286bf165.jpg)
![33](https://user-images.githubusercontent.com/31332231/100689452-759e2280-33bf-11eb-8ea4-62f683f912e3.jpg)
![44](https://user-images.githubusercontent.com/31332231/100689459-79ca4000-33bf-11eb-9cdc-2860203dde8e.jpg)

**Comment by hfbuhun** [comment]
Can connect correctly on UBUNTU
![正确1](https://user-images.githubusercontent.com/31332231/100729720-16aecc80-3404-11eb-92fc-c71bbd71e5dd.jpg)
![正确2](https://user-images.githubusercontent.com/31332231/100729727-1adaea00-3404-11eb-8135-a17936d00c1e.jpg)
but When i ported to arm.I get an error message
![错误1](https://user-images.githubusercontent.com/31332231/100729888-4f4ea600-3404-11eb-89db-7dc704e4b03b.jpg)
![错误2](https://user-images.githubusercontent.com/31332231/100729907-54abf080-3404-11eb-9103-03da01d4244b.jpg)
![错误3](https://user-images.githubusercontent.com/31332231/100729920-57a6e100-3404-11eb-949a-08cc10cf1dfe.jpg)

**Comment by hfbuhun** [comment]
@icraggs @jumoog I found my problem，When I compile OpenSSL, there is no linux-generic32 parameter，like this
./Configure linux-generic32 --cross-compile-prefix=xxxx
