### ISSUE TITLE
Async client blocks for a long time when the server closes the connection

### ISSUE THREAD

**Issue by martinboers** [eclipse-paho/paho.mqtt.c#1008]
I am using the Paho C++ client in an embedded application which has strict timing requirements - basically, the application cannot block for more than (say) 100ms before it causes problems.

I am trying to solve a problem where the Paho async client appears to block for a long time - up to 100 seconds or more - in some circumstances. I can reproduce this behaviour reliably. I have provided a full trace, with comments below.

I would welcome any advice that might lead to a solution.

**Environment**

OS: A custom Linux build for Phoenix Contact's AXC F 2152 controller.
Version: 2020.6.1

**The Scenario**

In this situation, our client is connecting to a remote MQTT server via SSL. The server appears to be quite strict about the topic and payload in messages that we publish, and it appears to immediately close the connection if it doesn't like what it sees.

The sequence of calls to the Paho async client is:

- Connect. This call is successful.
- Publish. This call is successful, but the server then appears to immediately close the connection.

**The Problem**

Before the Publish call, the Paho C client appears to be going through an "Async cycle" every 1 second (no problem).

After the Publish call, the Paho C client appears to go through a large number of cycles, about 1-3 ms apart. Each cycle includes the message "**Error from MQTTAsync_cycle() - removing socket**". Eventually, after a long time - in this case, 17 seconds - the closed connection is confirmed, and everything returns to normal. During these 17 seconds our client is blocked, which causes a problem for our application. This blocking behaviour can last anywhere from a few hundred milliseconds to over 100 seconds.

**Trace**

A full trace is linked [here](https://drive.google.com/file/d/1RuHLQMvEcyeDQ264Svrnq6-CBjffRuqS/view?usp=sharing) (I don't know why Github won't allow me to attach it).

Relevant timestamps are:

- Connect: `20201202 090530.782`
- Publish: `20201202 090600.281`
- Disconnect confirmed: `20201202 090617.642`

Our client is blocked between 090600 and 090617 (i.e. for 17 seconds).

**Additional information**

This behaviour does not appear with other MQTT servers that we have tested, including the Mosquitto test server, but that might just be because those servers haven't closed the connection in the same way as the one in this case.

I have performed the same procedure using the MQTT.fx client on Windows, on the same MQTT server. The "Broker connection lost" message appears consistently about 150 ms after publishing, which is the sort of behaviour we want to see with our client.

**Comment by icraggs** [comment]
You're using version 1.3.1.  A lot of things have changed in that time including in this area, over the intervening 16 months.  @fpagliughi is working on a new C++ client to use an updated C client.

**Comment by fpagliughi** [comment]
Yes, apologies on the delay getting a new C++ client out. A lot of fixes and new features are coming soon.

I've never seen anything more than a few seconds delay on closure (usually about 1sec), but I consider even that undesirable, and I think it is in the current C lib and can be fixed. There is already an open issue: #889

I'm not sure is this is related, but it would probably be helpful if we can boil it down to a simple C program that reproduces the behavior.

**Comment by icraggs** [comment]
@fpagliughi After looking at the trace, this is different to #889 and I'm pretty certain fixed a while back.

**Comment by martinboers** [comment]
Thanks for the replies.

At the moment our client dynamically links to the Paho libs that are included with the device firmware, so I'm restricted to the versions of the Paho libs that are bundled with the latest firmware. But I can ask for a specific minimum version to be included in the next firmware release, if necessary.

I will work on a minimal C program that demonstrates the behaviour.

**Comment by martinboers** [comment]
OK, on the device, I replaced version 1.3.1 of the library with version 1.3.7, and voila! The problem appears to be solved.

I will request an upgrade of the Paho libraries for the next device firmware release.

Thank you both for your excellent support of a great set of libraries.

**Comment by fpagliughi** [comment]
BTW, an updated C++ library is on the way. 

The existing C++ lib should work fine with the latest C library underneath it, though there is one known issue if you happen to use user-defined persistence (#1001), but if not, you should be good.

The new C++ lib will, of course, add support for all the new features in the C v1.3.7 as well.
