### ISSUE TITLE
OpenSSL Crash during MQTTClient_destroy

### ISSUE THREAD

**Issue by svermigo** [eclipse-paho/paho.mqtt.c#1014]
Looks like we have some issues during ERR_free_strings() in SSLSocket.c .. we are running openssl 1.0.2 .. do you think the issue is related to paho.mqtt.c or more to openssl? 

![image](https://user-images.githubusercontent.com/5464371/101488382-d1d4e980-395f-11eb-8237-8465bcfe2f0d.png)

**Comment by icraggs** [comment]
I don't know.  I've never seen this.  There are no parameters to ERR_free_strings() so unlikely it is called wrongly.  

If you have other parts of the application also using OpenSSL, then they could be clashing.  You can use the MQTTClient_global_init call to specify that this library does not initialize or close OpenSSL, but then the application (or another library) has to initialize and clean up OpenSSL.

**Comment by svermigo** [comment]
I believe I found the root cause: see PR https://github.com/eclipse/paho.mqtt.c/pull/1015

**Comment by icraggs** [comment]
Have you run enough tests to be sure that the solution in #1015 has made a difference?
