### ISSUE TITLE
httpsProxy depends on httpProxy

### ISSUE THREAD

**Issue by tiolan** [eclipse-paho/paho.mqtt.c#1021]
On the master branch I noticed that the value for aClient->http**s**Proxy (note the s) is only taken into account when aClient->httpProxy is set.
See:
https://github.com/eclipse/paho.mqtt.c/blob/7c79e3073c241f39884553dec01a7a5c6d02eb4c/src/MQTTProtocolOut.c#L240

~~~
if (aClient->httpProxy)
	p0 = aClient->httpsProxy;
else
	p0 = getenv("https_proxy");
~~~

However, in this commit, the logic was different:
https://github.com/eclipse/paho.mqtt.c/commit/6d80bd5538e26fe49592fff4cc2d0c76d6e00da9#diff-a0df8cc62c5e7e06af23ebe32beef7d14633e61e9734066f1e01b5218387de14R204
~~~
if (aClient->httpsProxy)
	p0 = aClient->httpsProxy;
else
	p0 = getenv("https_proxy");
~~~

I wonder whether this intended, as the logic for setting those via environment variables is different.

**Comment by icraggs** [comment]
It's a typo.
