### ISSUE TITLE
base64 encoding for basic auth proxy seems to be wrong

### ISSUE THREAD

**Issue by tiolan** [eclipse-paho/paho.mqtt.c#1022]
**Describe the bug**
The following setup:
paho C Mqtt lib with sample provided in MQTTClient_publish.c
Added the line 
~~~
conn_opts.httpProxy = "http://user:pass@localhost:3128/";
~~~
in order to connect to an http proxy, that has basic auth enabled.
Via such an http proxy, attempt to connect to a locally running broker (websockets).
Having squid3 as http proxy running locally, listening on port 3128.
Did:
~~~
export MQTT_C_CLIENT_TRACE=ON 
export MQTT_C_CLIENT_TRACE_LEVEL=PROTOCOL 
~~~

**To Reproduce**
Running MQTTClient_publish with above mentioned modification, produces:
~~~
20201213 160801.244 Setting http proxy to localhost:3128/
20201213 160801.244 Setting http proxy auth to dXNlcjpwYXM=
20201213 160801.244 WebSocket_proxy_connect: "CONNECT localhost:8080 HTTP/1.1
Host: localhost
Proxy-authorization: Basic dXNlcjpwYXM=
Failed to connect, return code -1
~~~
Wireshark of the CONNECT shows me, that the last character of the password was lost:
~~~
Hypertext Transfer Protocol
    CONNECT localhost:8080 HTTP/1.1\r\n
    Host: localhost\r\n
    Proxy-authorization: Basic dXNlcjpwYXM=\r\n
        Credentials: user:pas
    \r\n
    [Full request URI: localhost:8080]
    [HTTP request 1/1]
    [Response in frame: 6]

~~~
**Expected behavior**
According to several online base64 encoders, the base64 of "user:pass" should be "dXNlcjpwYXNz" instead of "dXNlcjpwYXM="
Using correct password, paho C Mqtt should be able to connect to broker via http proxy.
**Workaround**
Adding one single additional character to the password, generated the correct base64, http proxy accepts the CONNECT and connection to broker can be established.
~~~
conn_opts.httpProxy = "http://user:passX@localhost:3128/";
~~~
Wireshark for workaround:
~~~
Hypertext Transfer Protocol
    CONNECT localhost:8080 HTTP/1.1\r\n
    Host: localhost\r\n
    Proxy-authorization: Basic dXNlcjpwYXNz\r\n
        Credentials: user:pass
    \r\n
    [Full request URI: localhost:8080]
    [HTTP request 1/1]
    [Response in frame: 10]
~~~
**Sidenote**
When using another combination of a username and password, such as:
~~~
conn_opts.httpProxy = "http://myuser:mypass@localhost:3128/";
~~~
the produced base64 seems to have non-printable characters (see screenshot).
**Screenshots**
![image](https://user-images.githubusercontent.com/49237129/102016270-5361b880-3d60-11eb-8eff-32968fe84e3a.png)

**Environment (please complete the following information):**
 - OS: Linux Ubuntu-dev 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- git branch: master
- git hash: 7c79e3073c241f39884553dec01a7a5c6d02eb4c
(built from source)

**Additional context**
Assuming the last character of the password string is not taken into account when doing the base64 conversion.

**Comment by tiolan** [comment]
When removing this decrement, it also works without the workaround:
https://github.com/eclipse/paho.mqtt.c/blob/7c79e3073c241f39884553dec01a7a5c6d02eb4c/src/MQTTProtocolOut.c#L169

Did not check though, which implications this has.

**Comment by fpagliughi** [comment]
I agree. It seems to be making room for the NUL terminator by chopping off the final char of the password. If it needs the extra space for the NUL (which it appears to), then it should allocate an extra byte, right?
```
basic_auth = (b64_data_t *)malloc(basic_auth_in_len+1);
if (!basic_auth)
{
	rc = PAHO_MEMORY_ERROR;
	goto exit;
}
MQTTProtocol_specialChars((char*)basic_auth, source, &basic_auth_in_len);
```

And, for that matter, then does the output buffer require an extra byte for a NUL as well? It looke like `Base64_encodeLength()` is not taking into account the need for a terminating char, and if the encode function, `Base64_encode()` totally fills the buffer, then it does _not_ append a NUL.

I _think_ for this, the solution it to just say the output length is one more than actually needed:
```
basic_auth_out_len = Base64_encodeLength(basic_auth, basic_auth_in_len) + 1;
```

**Comment by icraggs** [comment]
Thanks.  You can try the above fix.

**Comment by fpagliughi** [comment]
I can add the fix later today. I'd like to get a local version of squid3 running to replicate the problem and see that this fixes it, but I'm rather new to using squid.

@tiolan can you share the squid3 configuration that you used to test this, and I will try to replicate and fix.

**Comment by tiolan** [comment]
@fpagliughi sure.
I started squid3 like this (it does not print anything in this config):
~~~
sudo squid3 -N -f /etc/squid/squid_myconf.conf
~~~
With etc/squid/squid_myconf.conf being (obviously there is a lot of useless stuff in, but I provide exactly what I used):
[squid_myconf.conf.txt](https://github.com/eclipse/paho.mqtt.c/files/5690348/squid_myconf.conf.txt)
Note: I had to rename the file-extension

**Comment by tiolan** [comment]
In case you need the mosquitto config:
~~~
mosquitto -c /etc/mosquitto/conf.d/websockets.conf 
~~~
with:
~~~
cat /etc/mosquitto/conf.d/websockets.conf  
listener 8080
protocol websockets

listener 1883
protocol mqtt

allow_anonymous true
~~~

**Comment by tiolan** [comment]
@icraggs I just compiled again with above mentioned fix and run the same setup with.
~~~
conn_opts.httpProxy = "http://user:pass@localhost:3128/";
~~~

It worked.

**Comment by fpagliughi** [comment]
Oh, hahaha. I read the comment, "You can try the above fix." to mean "Feel free to implement the fix you described above". Ha. I didn't see @icraggs had pushed a commit.

I tried it as well, and confirmed that the fix seems to fix it.
Thanks, @tiolan for the config files. Very helpful.

Reminder, if anyone else wants to try this, you need an auth file, like:
```
$ sudo htpasswd -c passwords user
New password:   <use "pass">
...
```
Then you can test with the latest *paho_c_pub:*
```
$ paho_c_pub --http-proxy http://user:pass@localhost:3128 -c ws://localhost:8080 -t hello -m "Hi there" 
...
=========================================================
20201214 132524.929 Connecting to serverURI localhost:8080 with MQTT version 4
20201214 132524.929 Setting http proxy to localhost:3128
20201214 132524.929 Setting http proxy auth to dXNlcjpwYXNz
20201214 132525.029 WebSocket_proxy_connect: "CONNECT localhost:8080 HTTP/1.1
Host: localhost
Proxy-authorization: Basic dXNlcjpwYXNz

"
20201214 132525.359 WebSocket connection upgraded
20201214 132525.359 3 paho-c-pub -> CONNECT version 4 clean: 1 (0)
20201214 132525.460 3 paho-c-pub <- CONNACK rc: 0
20201214 132525.460 3 paho-c-pub -> PUBLISH qos: 0 retained: 0 rc: 0 payload len(8): Hi there
20201214 132525.529 3 paho-c-pub -> DISCONNECT (0)
```
