### ISSUE TITLE
Memory ownership in MQTTAsync_updateConnectOptions callback

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#1024]
I'm trying to get a handle on the memory management in the `MQTTAsync_updateConnectOptions` callback.

If the application changes the data pointed to by the `MQTTAsync_connectData` struct, the library doesn't take ownership of the data (user name and password), but rather makes a copy of it.

Which means that the data must outlive the application's callback and be responsible for its management to be deallocated some time later. But that's a little vague from the application's perspective (knowing when the caller has copied the data), so it likely needs to be cached with the lifetime of the client.

Is that correct?

**Comment by icraggs** [comment]
Generally, the library copies the data for API calls so that the application can do what it likes with it.  See the username and password in the connect options for instance (on connect).

As far as I remember, the same approach was taken, or intended to be taken in this callback.

**Comment by fpagliughi** [comment]
It depends which way the call is going. An API call, where the application calls into the library and has control before and after the call, then it's great that the library copies the data. The app knows it can delete its local copy as soon as the call returns.

But in a callback, where the library calls into the application, it's more difficult for the app to manage the  memory. It loses control when it returns from the callback, needs to keep the memory alive after it returns, but is never quite sure when it's safe to delete it's copy (meaning the app has no way to know when the library has made the copy).

In this library, the similar callbacks are the persistence `get()` callback and the new `beforeWrite` and `afterRead` callbacks. With these, if the application needs new memory, it is required to use `MQTTAsync_malloc()` to allocate the new buffer(s) and then the library takes ownership and eventually deletes those buffers.

I'm not sure that I think this one needs to change, but maybe it should be more consistent with the other callbacks, rather than with the API calls.

But, as always, either way we go, we should explicitly document the callback as to what is required of it.

**Comment by icraggs** [comment]
Oh yeah.  I see.  We could change it for this upcoming release, I'm sure no-one is using it for real just yet.

**Comment by fpagliughi** [comment]
OK. I'm implementing this coverage in the C++ library. I'll implement assuming that this change will be made.

From what I have on my list, this is the last features I need to get in for the C++ release. I should have it done today, and then it's just test, test, test. (Until someone reminds me that I forgot something).

**Comment by icraggs** [comment]
I've made the change, if you'd like to check it out.  I think it's correct...

**Comment by fpagliughi** [comment]
Yeah, looks good and runs without leaks or double-free's, or anything like that.
I'll say this is good and close the issue.
