### ISSUE TITLE
Token not increased when using QOS0

### ISSUE THREAD

**Issue by tiolan** [eclipse-paho/paho.mqtt.c#1025]
**Describe the bug**
I am using the Async API with MQTTv5.
After the call to `MQTTAsync_sendMessage(client, &topic, &msg, &callOptions)` the structure `MQTTAsync_callOptions callOptions` allows to receive an `MQTTAsync_token`, which seems to essentially be the MQTT message ID.
Using this token, inside `callOptions.onSuccess5 = [](void* ctx, MQTTAsync_successData5* data){...}` I have a correlation between the call to `MQTTAsync_sendMessage` and the callback.

For QOS1 and QOS2, this works as expected.
For QOS0, the token always is equal to 0.

**Expected behavior**
I understand, the messageId in QOS0 is not defined, however I would expect the token to be uniquely set such that a correlation between call and callback can also be made with QOS0.

What is the intention of the token in QOS0 case, if also the messageID itself is offered in the struct (for publish only)?

**Environment:**
git hash 0582ec284811f868298513600d235eaf6ab74e7f
built from source

**Comment by icraggs** [comment]
The msgid field of the MQTTAsync_message structure is output only, to inform the application of the message id of incoming publish messages.

I had long discussions about the best approach to the response options token, before settling and agreeing on the use of the message id.  So yes, for QoS 0 messages the token is not set, and is always 0.

You still have both the callback and context addresses set in the response options which can be used for correlation as both are set and stored for each instance of calls to sendMessage().

The documentation should be improved for these fields though.

**Comment by tiolan** [comment]
@icraggs 
Thanks for the fast response.

Does this mean calling `MQTTAsync_waitForCompletion` on a task with QOS0 is not safe?
I wonder on which task I would wait, since all have the same token=0.

In my case the context field is already occupied with the this pointer - I am on C++.
So I was searching for an alternative to correlate call and callback.

Can you elaborate on what you mean with "callback addresses"?
What field are you referring to?
I do have `MQTTAsync_callOptions.onSuccess5` available in the call (pointing to the callback, always equal), but inside the callback only `MQTTAsync_successData5* data`

Thanks!
(Feel free to close, if it is expected behavior)
