### ISSUE TITLE
How to notify the program after automatic reconnection？

### ISSUE THREAD

**Issue by Davonter** [eclipse-paho/paho.mqtt.c#1028]
As title, I want to know when to reconnect successfully, so that I can do something after each successful reconnection.

Best regards!

**Comment by icraggs** [comment]
The connected callback.

https://eclipse.github.io/paho.mqtt.c/MQTTAsync/html/_m_q_t_t_async_8h.html#a18cc19740d9b00c629dc53a4420ecf1f

https://eclipse.github.io/paho.mqtt.c/MQTTAsync/html/_m_q_t_t_async_8h.html#a34bb8d321e9d368780b5c832c058f223

**Comment by Davonter** [comment]
> The connected callback.
> 
> https://eclipse.github.io/paho.mqtt.c/MQTTAsync/html/_m_q_t_t_async_8h.html#a18cc19740d9b00c629dc53a4420ecf1f
> 
> https://eclipse.github.io/paho.mqtt.c/MQTTAsync/html/_m_q_t_t_async_8h.html#a34bb8d321e9d368780b5c832c058f223

Thanks, it works.
