### ISSUE TITLE
asynch sll library ordinal 295 error

### ISSUE THREAD

**Issue by sanjukalki** [eclipse-paho/paho.mqtt.c#1029]
In a code to test asynch ssl communication with mosquito broker , getting an error of  "the ordinal 295 couldn't be located in dynamic link library " of paho-mqtt3as.dll .build in  visual studio 2013 windows .this lib added in properties->linker ->input ->additional Dependencies ,(lib location given in AdditionalLibraryDirectories ) , library from eclipse-paho-mqtt-c-win32-1.3.5 is used

**Comment by icraggs** [comment]
I've no idea what that means.  A quick search that I did suggests possibilities of missing or not found C++ redistributable, OpenSSL, mismatching build architectures (is your application built with 32 bit or 64 bit?) for instance.

**Comment by icraggs** [comment]
I think I've answered this question.
