### ISSUE TITLE
mqtt logic about Init and connect 

### ISSUE THREAD

**Issue by mandy-yan** [eclipse-paho/paho.mqtt.c#1037]
Hello, 
   below is a part of my code to use mqtt init and connect, I want to keep connect until success, so i want to ask 
   1. Am i right to use the this way to  implement my function?
   2. when i run the same code again(use the same client_id to login the broker, same user,same password),  The latter will squeeze the former down，and  the connlost function will be exec, so my program logic will Stuck in a loop(i don`t know whether you can understand)， But after a while, one of program will Segfault
   So, i want to ask, Am i somewhere use wrong to cause this error??, and everytime connlost function exec, the value `cause` is null, i also can`t understand why?
  Thanks to reply you

mqtt thread:
![image](https://user-images.githubusercontent.com/17793782/103858915-22bd3680-50f4-11eb-84c7-10734d770cba.png)

MQTT_InitAndConnect : 
![image](https://user-images.githubusercontent.com/17793782/103859034-5304d500-50f4-11eb-8d24-e47082f8964e.png)

connlost :
![image](https://user-images.githubusercontent.com/17793782/103859154-83e50a00-50f4-11eb-89bf-09d00db9b20e.png)

** Environment (please complete the following information):**
paho version:  v1.0.3

**Comment by icraggs** [comment]
1. You are using versiobn 1.0.3 which is almost six years old.  I suggest you use a newer version.

2. For multithreaded applications the MQTTAsync API is a better option.

3. You should only destroy the object when you've really finished with it - if things are still running or being cleaned up then it will cause problems.  I wouldn't advise using destroy just  because the connection failed.

**Comment by icraggs** [comment]
Also you should be aware that with MQTT you must use a different client id for each MQTT connection you want to make to the same broker.   If you don't, the previous connection with the same client id will be disconnected by the broker.

**Comment by icraggs** [comment]
There is no information in the cause field of connectionLost because I haven't found any useful information to put there yet.

In the connlost callback, you should really just call connect rather than starting another thread.

The MQTTAsync API also has automatic reconnection.
