### ISSUE TITLE
absolute path to libanl

### ISSUE THREAD

**Issue by sandro97git** [eclipse-paho/paho.mqtt.c#1038]
https://github.com/eclipse/paho.mqtt.c/blob/317fb008e1541838d1c29076d2bc5c3e4b6c4f53/src/CMakeLists.txt#L68

The line above leads to a fixed path in `eclipse-paho-mqtt-cConfig.cmake`. If the paho library is now built on a different machine than the project that's using it the library can't be found.

I suggest to replace the line with:
```cmake
SET(LIBS_SYSTEM "${LIBS_SYSTEM}" anl) 
```

**Comment by icraggs** [comment]
That change would reverse the change asked for by someone else to support building with libraries other than glibc, as the comment preceding it describes:

    # anl is only available with glibc so check if it is found before using
    # it or build will fail on uclibc or musl

and invalidate the 

    FIND_LIBRARY(LIB_ANL anl)

call.

**Comment by icraggs** [comment]
And I don't think I understand the description of your problem.

**Comment by sandro97git** [comment]
Let me try to explain a bit better. This is a part of the generated `eclipse-paho-mqtt-cConfig`:
```cmake
set_target_properties(eclipse-paho-mqtt-c::paho-mqtt3a PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "c;dl;pthread;rt /home/build/........../paho-mqtt-c/1.3.7-r0/recipe-sysroot/usr/lib/libanl.so"
)
```

As you can see the file contains an absolute path and because this file is generated during the build process which happens on a build server the path is not found on a developer machine.

If a developer on his machine links to `eclipse-paho-mqtt-c::paho-mqtt3a` cmake tries to find this path to libanl which does not exist on his machine. The paho cmake package is therefore not relocatable https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-relocatable-packages

I hope this helps.

**Comment by sandro97git** [comment]
Maybe another solution could be this:

```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 4137d38..191ae29 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -100,8 +100,8 @@ IF (PAHO_BUILD_SHARED)
     ADD_LIBRARY(paho-mqtt3c SHARED $<TARGET_OBJECTS:common_obj> MQTTClient.c)
     ADD_LIBRARY(paho-mqtt3a SHARED $<TARGET_OBJECTS:common_obj> MQTTAsync.c MQTTAsyncUtils.c)

-    TARGET_LINK_LIBRARIES(paho-mqtt3c ${LIBS_SYSTEM})
-    TARGET_LINK_LIBRARIES(paho-mqtt3a ${LIBS_SYSTEM})
+    TARGET_LINK_LIBRARIES(paho-mqtt3c PRIVATE ${LIBS_SYSTEM})
+    TARGET_LINK_LIBRARIES(paho-mqtt3a PRIVATE ${LIBS_SYSTEM})
     TARGET_LINK_LIBRARIES(MQTTVersion paho-mqtt3a paho-mqtt3c ${LIBS_SYSTEM})

     SET_TARGET_PROPERTIES(
@@ -149,8 +149,8 @@ IF (PAHO_BUILD_STATIC)
     ADD_LIBRARY(paho-mqtt3c-static STATIC $<TARGET_OBJECTS:common_obj_static> MQTTClient.c)
     ADD_LIBRARY(paho-mqtt3a-static STATIC $<TARGET_OBJECTS:common_obj_static> MQTTAsync.c MQTTAsyncUtils.c)

-    TARGET_LINK_LIBRARIES(paho-mqtt3c-static ${LIBS_SYSTEM})
-    TARGET_LINK_LIBRARIES(paho-mqtt3a-static ${LIBS_SYSTEM})
+    TARGET_LINK_LIBRARIES(paho-mqtt3c-static PRIVATE ${LIBS_SYSTEM})
+    TARGET_LINK_LIBRARIES(paho-mqtt3a-static PRIVATE ${LIBS_SYSTEM})
     IF (NOT WIN32)
         SET_TARGET_PROPERTIES(paho-mqtt3c-static PROPERTIES OUTPUT_NAME paho-mqtt3c)
         SET_TARGET_PROPERTIES(paho-mqtt3a-static PROPERTIES OUTPUT_NAME paho-mqtt3a)
@@ -232,7 +232,7 @@ IF (PAHO_WITH_SSL)
                     ${CMAKE_BINARY_DIR})
             TARGET_LINK_LIBRARIES(${TARGET}
                 PUBLIC
-                    OpenSSL::SSL OpenSSL::Crypto ${LIBS_SYSTEM})
+                    OpenSSL::SSL OpenSSL::Crypto PRIVATE ${LIBS_SYSTEM})
         ENDFOREACH()
         INSTALL(TARGETS paho-mqtt3cs paho-mqtt3as
             EXPORT eclipse-paho-mqtt-cTargets
```

Altough I'm not sure if it leads to problems if those libs are not part of the public link interface.
On my end this works fine.

**Comment by icraggs** [comment]
Ok, I re-read the CMake part where libanl is included and your original suggestion does look correct after all, so we could go with that.

**Comment by icraggs** [comment]
Merged into the develop branch.
