### ISSUE TITLE
CONNECT action intermittently takes 1s.

### ISSUE THREAD

**Issue by lstroe** [eclipse-paho/paho.mqtt.c#1039]
**Describe the bug**
CONNECT action intermittently takes 1s.

**To Reproduce**
1.	Write simple application that attempts to CONNECT to the Server.
2.	Run a script that calls the binary in a loop [e.g] 100 times.

Results
During this scenario ~15% of the time we get connected in one second period.

**Expected behavior**
Based on the logs bellow are we having the correct assumption that the “normal” behaviour is ? :
“Send thread” is starting and waits on the conditional variable until MQTTAsync_addCommand notifies it?
 
**Is this  expected ??**
In the “delayed” behaviour  we have noticed that MQTTAsync_addCommand runs after sendThread  checks for an empty command list but before sendThread starts waiting on the conditional variable.
sendThread will miss the notification and will only break from waiting after the timeout period(1s).? 

Good connection
--
|Time | Main thread  | sendThread
| --- | --- | ---|
0 | (0)> MQTTAsync_connect:2756 |  
0 | (1)> Thread_start:69 |  
0 | (1)< Thread_start:79 |  
0 | (1)> Thread_start:69 |  
0 |   | (0)> MQTTAsync_sendThread:1802
0 | (1)< Thread_start:79 |  
0.006 |   |<strong>(1)> Thread_wait_cond:411</strong>
0.006 |   |  
0.006 |   |  
0.006 |   |  
0.006 |  <strong>(1)> MQTTAsync_addCommand:1002 </strong>|  
0.006 | (2)> Thread_signal_cond:393 |  
0.006 | (2)< Thread_signal_cond:398 (0) |  
0.006 | <strong>(1)< MQTTAsync_addCommand:1036 (0) </strong>|  
0.006 | (0)< MQTTAsync_connect:3057 (0) |  
0.006 |   |<strong> (1)< Thread_wait_cond:426 (0)</strong>
0.006 |   | (1)> MQTTAsync_checkTimeouts:1748
0.006 |   | (1)< MQTTAsync_checkTimeouts:1796
0.006 |   | (1)> MQTTAsync_processCommand:1342
0.006 |   | (2)> MQTTProtocol_connect:114
0.006 |   | (3)> MQTTProtocol_addressPort:58
0.008 |   | (3)< MQTTProtocol_addressPort:90
0.008 |   | (3)> Socket_new:668
0.008 |   | (4)> Socket_addSocket:173
0.008 |   | (5)> Socket_setnonblocking:85
0.008 |   | (5)< Socket_setnonblocking:90 (0)
0.008 |   | (4)< Socket_addSocket:196 (0)

Delayed connection
--
|Time | Main thread  | sendThread
| --- | --- | ---|
0.000 | (0)> MQTTAsync_connect:2756 |  
-- | -- | --
0.000 | (1)> Thread_start:69 |  
0.000 | (1)< Thread_start:79 |  
0.000 | (1)> Thread_start:69 |  
0.000 |   | (0)> MQTTAsync_sendThread:1802
0.000 | (1)< Thread_start:79 |  
0.007 |<strong> (1)> MQTTAsync_addCommand:1002 </strong>|  
0.007 | (2)> Thread_signal_cond:393 |  
0.007 | (2)< Thread_signal_cond:398 (0) |  
0.007 | <strong>(1)< MQTTAsync_addCommand:1036 (0)</strong> |  
0.007 | (0)< MQTTAsync_connect:3057 (0) |  
0.007 |   |<strong> (1)> Thread_wait_cond:411</strong>
  |   |  
… |   |  
  |   |  
0.911 |   | <strong>(1)< Thread_wait_cond:426 (110)</strong>
0.911 |   | (1)> MQTTAsync_checkTimeouts:1748
0.911 |   | (1)< MQTTAsync_checkTimeouts:1796
0.911 |   | (1)> MQTTAsync_processCommand:1342
0.911 |   | (2)> MQTTProtocol_connect:114
0.911 |   | (3)> MQTTProtocol_addressPort:58
0.911 |   | (3)< MQTTProtocol_addressPort:90
0.911 |   | (3)> Socket_new:668
0.911 |   | (4)> Socket_addSocket:173
0.911 |   | (5)> Socket_setnonblocking:85
1.010 |   | (5)< Socket_setnonblocking:90 (0)
1.010 |   | (4)< Socket_addSocket:196 (0)

**Comment by icraggs** [comment]
So I think this will only happen when there is no existing client object because the background threads are not running yet and need to be started.

There is some work planned to allow separate library initialization/cleanup routines to be called explicitly which would avoid this.  Additionally the timeout value in the loop could be set to a lower value than 1s.
