### ISSUE TITLE
MQTTAsync interface, publish msg need extra handle for QoS 1 or 2?

### ISSUE THREAD

**Issue by kenxausten** [eclipse-paho/paho.mqtt.c#1042]
Describe the bug
If the msg's QoS is 1 or 2, does it need extra handle in following picture(in the function: MQTTAsync_processCommand if the command's type is publish)

BTW, the API of MQTTAsnc_sendMessage, how to get the specific msg is send successfully?

![image](https://user-images.githubusercontent.com/8687206/104575657-3cc9bc80-5692-11eb-9b36-65ae3be01bc9.png)

**Comment by icraggs** [comment]
That's in writeComplete which handles write completions.  QoS 1 and 2 success callbacks are called when the QoS 1 or 2 exchange is complete, which is when the PUBACK or PUBCOMP is received.  So the answer is no.  

A failing test or scenario is a better way to illustrate any problems.

The onSuccess callback will tell you when a message has been successfully sent.  The deliveryComplete callback will also be called for QoS 1 and 2 messages.

**Comment by icraggs** [comment]
I believe I've answered this question.
