### ISSUE TITLE
Async Client over Secure WebSocket (wss://) fails to connect properly

### ISSUE THREAD

**Issue by yulius-take2** [eclipse-paho/paho.mqtt.c#1047]
**Describe the bug**
While using the async client and connecting over SSL websockets, the call to `WebSocket_upgrade()` is not guaranteed to complete in a single call.  In async mode, multiple calls to `WebSocket_upgrade()` might be needed to finish receiving all the HTTP websocket upgrade header.  The current code in `MQTTAsyncUtils.c` will call WebSocket_upgrade() once and assume the upgrade completed before changing the state to `WAIT_FOR_CONNACK`.  The fix is to check `m->c->net.websocket` equal 1 before changing state to `WAIT_FOR_CONNACK`.

For reference here is the section of code with the bug:
https://github.com/eclipse/paho.mqtt.c/blob/v1.3.8/src/MQTTAsyncUtils.c#L2815-L2825

This is the section of the code in websocket that successfully upgrades:
https://github.com/eclipse/paho.mqtt.c/blob/v1.3.8/src/WebSocket.c#L1409-L1411

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1. Setup a MQTT server that accepts WSS (we used VerneMQ)
2. Enable logging in paho client
3. Connect using paho async client
4. You will get a log that say "Bad MQTT packet, type  4" and you will not be able to connect.  If you look at the payload data you will see it's the websocket preamble.

**Expected behavior**
You should be able to connect using async client over wss://

**Screenshots**
N/A

** Environment (please complete the following information):**
 - OS: Windows 10 - Version 2004 (OS Build 19041.685)
 - Version: Using Paho 1.3.7 but problem also exists in Paho 1.3.8

**Additional context**
This is the example of the fix.
https://github.com/yulius-take2/paho.mqtt.c/commit/f4e755aaed094aefd804b20b3a3d948f833a21c8

**Comment by icraggs** [comment]
Thanks.

**Comment by qm3ster** [comment]
It's not too late to rename this issue :v
