### ISSUE TITLE
How to connect AWS?

### ISSUE THREAD

**Issue by JorgeVBZ** [eclipse-paho/paho.mqtt.c#1049]
Hi friends,

I'm trying to connect to AWS IoT Core but I don't know how to use the PAHO MQTT library to do it. I think that I'm not calling some functions or in the correct order. I attach the code below.
Someone can help me? I appreciate so much any help...

Thanks in advance,

Regards!

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "MQTTClient.h"

#define ADDRESS     "****************-ats.iot.eu-west-3.amazonaws.com:8883"
#define CLIENTID    "ExampleClientPub"
#define TOPIC       "admin"
#define PAYLOAD     "Hello World!"
#define QOS         1
#define TIMEOUT     10000L

struct Options
{
        char server_auth_connection[100];
        char** haconnections;           /**< connection to system under test. */
        int hacount;
        char* client_key_file;
        char* client_key_pass;
        char* server_key_file;
        char* client_private_key_file;
        int verbose;
        int test_no;
        int websockets;
} options =
{
        "****************-ats.iot.eu-west-3.amazonaws.com:8883",
        NULL,
        0,
        "./Certificates/ef9cfb6049-private.pem.key",
        "",
        "./Certificates/root.pem",
        "./Certificates/ef9cfb6049-private.pem.key",
        0,
        0,
        0,
};

int main(int argc, char* argv[])
{
    MQTTClient client;
    MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
    MQTTClient_willOptions wopts = MQTTClient_willOptions_initializer;
    MQTTClient_SSLOptions sslopts = MQTTClient_SSLOptions_initializer;
    MQTTClient_message pubmsg = MQTTClient_message_initializer;
    MQTTClient_deliveryToken token;
    int rc;
    MQTTClient_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);
    conn_opts.keepAliveInterval = 20;
    conn_opts.cleansession = 1;

    if (options.haconnections != NULL)
    {
        conn_opts.serverURIs = options.haconnections;
        conn_opts.serverURIcount = options.hacount;
    }

    printf("Hasta aqui\n");

    //rc = MQTTClient_connect(client, &conn_opts);
    //printf("Connect should fail\n");

    conn_opts.ssl = &sslopts;

    if (options.server_key_file != NULL)

        conn_opts.ssl->trustStore = options.server_key_file; /*file of certificates trusted by client*/

    if (options.client_key_file != NULL){

        conn_opts.ssl->keyStore = options.client_key_file;//clave publica
    }

    if (options.client_private_key_file){

        conn_opts.ssl->privateKey = options.client_private_key_file;//clave privada
    }

    if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to connect, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }

    pubmsg.payload = PAYLOAD;
    pubmsg.payloadlen = strlen(PAYLOAD);
    pubmsg.qos = QOS;
    pubmsg.retained = 0;
    MQTTClient_publishMessage(client, TOPIC, &pubmsg, &token);
    printf("Waiting for up to %d seconds for publication of %s\n"
            "on topic %s for client with ClientID: %s\n",
            (int)(TIMEOUT/1000), PAYLOAD, TOPIC, CLIENTID);
    rc = MQTTClient_waitForCompletion(client, token, TIMEOUT);
    printf("Message with delivery token %d delivered\n", token);
    MQTTClient_disconnect(client, 10000);
    MQTTClient_destroy(&client);
    return rc;
}

**Comment by icraggs** [comment]
I think you might get a better response if you asked in an AWS support forum.  I don't use AWS myself but some others have, such as in #615

AWS has a C SDK, have you tried using that or transposing the settings from that?  If you describe the result you get that might be easier to answer.

**Comment by JorgeVBZ** [comment]
Hi @icraggs,

First of all thanks for the quick response.

There is no SDK for C language, it is for C++, that is why I use notepad to program my files.
I think that I am not using correctly the PAHO library. I read on file paho.mqtt.c/test/test3.c and copy the example on line 640 (Test2a: Mutual SSL Authentication - Certificates in place on client and server - single threaded). I think that this example is which I need, but I am not sure.
On that example, I am not sure what certificate goes on each opts.ssl field (trustStore, privateKeyPassword, privateKey)...
I read #615 but I don't understand how finally @janscahtz solve his problem. 
My problem is using PAHO library to connect to a site that requires certificates. AWS provides me root.pem file, file.crt, public.pem and private.pem. My doubt is how to assing each one to the opts.ssl and how to call the functions in the correct order in order to connect succesfully.

Thanks in advance,

Regards!

**Comment by fpagliughi** [comment]
Here are some parameters I used with the Rust client to connect to AWS (remembering it just wraps this C lib):

```
[some connect_options]
mqtt_version = 4  (version 3.1.1)
uri = "ssl://...-ats.iot.us-east-2.amazonaws.com:8883"
client_id = "arn:aws:iot:us-east-2:...:client/basicPubSub"

[ssl_options]
trust_store = "root-CA.crt"
key_store = "awsthing1.cert.pem"
private_key = "awsthing1.private.key"
private_key_password = ""
enable_server_cert_auth = false
verify = true
```

The certificates and Client ID were generated with the AWS on-line or CLI tools. 

Hopefully this helps. There's also a relatively new way to connect using ALPN, but I haven't tried that yet.

Keep in mind, though, that the AWS broker is not 100% MQTT compliant, and it may not like something in your connect options/packet. When that happens, it immediately disconnect from you. The library reports that as a vague connection error, but if you look at the logs you can tell whether the certificates were rejected or the connect packet.

**Comment by icraggs** [comment]
And you might find it useful to experiment with one of the samples paho_c_sub / paho_c_pub as they allow you to set these parameters from the command line.

**Comment by JorgeVBZ** [comment]
Hi @icraggs,
I tried to connect with **paho_cs_pub** program from `paho.mqtt.c/build/output/samples` like below:

./paho_cs_pub -t admin -c *************-ats.iot.eu-west-3.amazonaws.com:8883 -m mensajePrueba --cafile /home/jvillacastin/workspace/MQTTClient/Certificates/root.pem --capath /home/jvillacastin/workspace/MQTTClient/Certificates/ --cert /home/jvillacastin/workspace/MQTTClient/Certificates/ef9cfb6049-certificate.pem.crt --key /home/jvillacastin/workspace/MQTTClient/Certificates/ef9cfb6049-private.pem.key

but I got this failure: `Connect failed return code: Failure`

@fpagliughi do you see some wrong on my command? I think that the certs and the keys are in the right place.

Additionally, if I test with this command  `openssl s_client -connect **********-ats.iot.eu-west-3.amazonaws.com:8883 -cert ef9cfb6049-certificate.pem.crt -key ef9cfb6049-private.pem.key`, I receive Verify return code 0 (ok), so I guess that the files are fine.

I test also another graphic MQTT Client on windows called MQTT.fx and it works and publish messages on AWS MQTT Client, so the files and the conection don't fail. It must be something with my PAHO configuration. 

Thanks in advance for your help,

Regards!

**Comment by icraggs** [comment]
You should take a trace to give more information about the errors.  With the command line utilities you can use the option --trace protocol

You can attach the trace output as files, rather than pasting the output.

**Comment by icraggs** [comment]
In the absence of more information, I'm closing this.

**Comment by phantom-j** [comment]
Hi @JorgeVBZ 
Is it working?
I am trying to do same thing ,connecting to aws using paho mqtt c library.
It will be helpful to know the mandatory steps

**Comment by phantom-j** [comment]
This configuration worked for me and i can receive messages also

	conn_opts.ssl = &ssl_opts;
    conn_opts.ssl->enableServerCertAuth = 1;
    conn_opts.ssl->struct_version = 3;
    conn_opts.ssl->CApath = "./*******-certificate.pem.crt";
    conn_opts.ssl->trustStore = "./AmazonRootCA1.pem";
    conn_opts.ssl->keyStore = "./*******-certificate.pem.crt";
    conn_opts.ssl->privateKey = "./*********-private.pem.key";
    conn_opts.ssl->sslVersion = MQTT_SSL_VERSION_TLS_1_2;
