### ISSUE TITLE
Error when trying to compile with emscripten

### ISSUE THREAD

**Issue by lucasvanmol** [eclipse-paho/paho.mqtt.c#1052]
Hi, I'm trying to compile the library with emscripten using the command:
`emcmake cmake -GNinja -DPAHO_BUILD_SHARED=FALSE -DPAHO_BUILD_STATIC=TRUE ~/paho.mqtt.c` which runs fine.
But after, running `ninja package` I get the following error:

```
FAILED: src/CMakeFiles/common_obj_static.dir/SHA1.c.o 
/home/username/emsdk/upstream/emscripten/emcc -DPAHO_MQTT_STATIC=1  -fPIC -MD -MT src/CMakeFiles/common_obj_static.dir/SHA1.c.o -MF src/CMakeFiles/common_obj_static.dir/SHA1.c.o.d -o src/CMakeFiles/common_obj_static.dir/SHA1.c.o   -c '/home/username/paho.mqtt.c/src/SHA1.c'
/home/username/paho.mqtt.c/src/SHA1.c:109:10: error: implicit declaration of function 'be32toh' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                w[i] = be32toh(w[i]);
                       ^
/home/username/paho.mqtt.c/src/SHA1.c:156:15: error: implicit declaration of function 'htobe32' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ctx->w[14] = htobe32((uint32_t)(total >> 32));
                     ^
2 errors generated.
```

I believe that this means that the line `#include <endian.h>` in SHA1.c isn't properly defining the functions be32toh() and htobe32(). Is there any way to fix this?

**Comment by icraggs** [comment]
It depends on the platform (OS) that you're building on.  In SHA1.c you see definitions for Linux, Cygwin, FreeBSD, NetBSD, Apple and Windows.  If it isn't one of them you might have to find equivalents.

**Comment by lucasvanmol** [comment]
This is on Linux, so shouldn't the line [`#  include <endian.h>`](https://github.com/eclipse/paho.mqtt.c/blob/317fb008e1541838d1c29076d2bc5c3e4b6c4f53/src/SHA1.c#L57 ) define the functions properly?

**Comment by lucasvanmol** [comment]
Well its a fresh VM, running ldd --version gives `ldd (Ubuntu GLIBC 2.31-0ubuntu9.1) 2.31`

**Comment by icraggs** [comment]
The CI tests run on three different versions of Ubuntu, as you can see here: https://travis-ci.org/github/eclipse/paho.mqtt.c/builds/755400003

The doc for emscripten says it's a complete toolchain and has its own version of libc, at least on quick skim.  Could be those differences to the base Ubuntu.  

SHA1.c may well not try to include endian.h with emscripten due to none of those macros being defined.  I also found this:

http://dosbox-x.com/doxygen/html/byteorder_8h_source.html

which has the comment that emscripten does not include endian.h.  Whether that's in fact true, I don't know.

**Comment by lucasvanmol** [comment]
I think it has something to do that indeed; if I try to manually add `#include <endian.h>` at the top of SHA1.c it seems to work, although I get a different error.

```
[6/26] Linking C executable test/thread.js
FAILED: test/thread.js 
: && /home/username/emsdk/upstream/emscripten/emcc    test/CMakeFiles/thread.dir/thread.c.o test/CMakeFiles/thread.dir/__/src/Thread.c.o  -o test/thread.js  -lc  -lpthread && :
error: undefined symbol: sem_getvalue (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _sem_getvalue may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
```

**Comment by icraggs** [comment]
Well you need to find out where or whether sem_getvalue is declared.  It's also used in Thread.c in the src directory which presumably compiled otherwise you wouldn't have got this far.

**Comment by icraggs** [comment]
I'm assuming this is now resolved.
