### ISSUE TITLE
The program crashed on the MQTTS connection

### ISSUE THREAD

**Issue by Krehizi** [eclipse-paho/paho.mqtt.c#1053]
**Describe the bug**
The program crashed on the MQTTS connection , everything is fine with MQTT , the following is the specific log . thanks.

**Explain**
I don't have the **OPENSSL Directory**,i'm running on an embedded system,i don't know if it affected.
![捕111111222获](https://user-images.githubusercontent.com/27603839/105620200-30cdbf80-5e35-11eb-8644-4678ae2dea3a.PNG)

**Log**
[log.txt](https://github.com/eclipse/paho.mqtt.c/files/5861508/log.txt)

**follow-up**
I found that this function caused the program to crash ,does it come from the OpenSSL library :
![11111111捕获](https://user-images.githubusercontent.com/27603839/105623117-266dee80-5e52-11eb-8729-6a134b6e6ba8.PNG)

**Comment by jumoog** [comment]
maybe you can run it with `valgrind`? And attach that log?

**Comment by icraggs** [comment]
Please try to attach log files rather than pasting the log contents. It makes the issues easier to read. Thank you.

**Comment by Krehizi** [comment]
> maybe you can run it with `valgrind`? And attach that log?

@jumoog I tried to run valgrind, but it doesn't work on an embedded system，is the OpenSSL Directory mandatory and what is it for ?

**Comment by Krehizi** [comment]
> Please try to attach log files rather than pasting the log contents. It makes the issues easier to read. Thank you.

@icraggs I have already modified,is the OpenSSL Directory mandatory and what is it for ?

**Comment by icraggs** [comment]
The call you have highlighted is an OpenSSL call, so the problem is likely within OpenSSL.  

The OpenSSL directory you have highlighted is the OpenSSL installation directory where OpenSSL thinks it is installed.  If it doesn't exist, then something is wrong with your OS or OpenSSL installation.

**Comment by Krehizi** [comment]
> The call you have highlighted is an OpenSSL call, so the problem is likely within OpenSSL.
> 
> The OpenSSL directory you have highlighted is the OpenSSL installation directory where OpenSSL thinks it is installed. If it doesn't exist, then something is wrong with your OS or OpenSSL installation.
I found the problem.My application was compiled with the OpenSSL library and the MQTT library, so if I removed OpenSSL it would not crash.

**Comment by Krehizi** [comment]
> The call you have highlighted is an OpenSSL call, so the problem is likely within OpenSSL.
> 
> The OpenSSL directory you have highlighted is the OpenSSL installation directory where OpenSSL thinks it is installed. If it doesn't exist, then something is wrong with your OS or OpenSSL installation.

I found the problem.My application was compiled with the OpenSSL library and the MQTT library, so if I removed OpenSSL it would not crash.
The crash may have been caused by repeated references to the OpenSSL library.
