### ISSUE TITLE
Install paho command line utility 

### ISSUE THREAD

**Issue by satyamtpatel** [eclipse-paho/paho.mqtt.c#1055]
Can you please provide steps to install command line paho mqtt client utility in both 
x86 and arm?

**Comment by icraggs** [comment]
Both the make and CMake install commands install the command line utilities as well as the libraries, I believe.

**Comment by icraggs** [comment]
I'm assuming that that helped.

**Comment by satyamtpatel** [comment]
Yes. Thanks.

Satyam Patel
Director of Technology Development
850-345-6798 (M) • 850-877-1104 (O) spatel@kyrasolutions.com<mailto:spatel@kyrasolutions.com> • kyrasolutions.com<http://www.kyrasolutions.com/> • Tallahassee, FL
[cid:image001.jpg@01D6F88F.0C095BC0]<http://www.kyrasolutions.com/>
