### ISSUE TITLE
How to reduce the number of else if in paho mqtt callback function with c？

### ISSUE THREAD

**Issue by Claire413** [eclipse-paho/paho.mqtt.c#1056]
I am using the PAHO mqtt asynchronous function to subscribe to topics, but I found a problem. When I receive and parse topics in the callback function messageArrived, I need to write a lot of else if to judge whether it is the corresponding topic. If so, I subscribe to many topics, then the topics written after else if will be implemented relatively slowly because they need to be compared one by one. And because topicname is char type, so I can't use switch... Case..., what's your good idea?

`rc = MQTTAsync_setCallbacks(MqttClient, (VOID*)MqttClient, connlost, messageArrived, 
deliveryComplete);
...
INT32 messageArrived(VOID *context, CHAR *topicName, INT32 topicLen, MQTTAsync_message *message)
{
    if (strcmp(topicName, TOPIC1) == 0)
    {
     //do something
    }
    else if (strcmp(topicName, TOPIC2) == 0)
    {
     //do something
    }
    ...
    // many 'else if'
    ...
    else if (strcmp(topicName, TOPICn) == 0)
    {
     //do something
    }
}`
I have ask in [https://stackoverflow.com/questions/65881563/how-to-reduce-the-number-of-else-if-in-paho-mqtt-callback-function-with-c](url)

**Comment by icraggs** [comment]
This is really a C question.  

I don't think that switch/case would be very much faster than if/else.  Unless you are having thousands of topics, I don't think these checks are going to have a big effect.  If you did really have thousands of topics, then you could use the C library bsearch() function.

**Comment by Claire413** [comment]
thanks.
