### ISSUE TITLE
What's MQTTCLIENT_FAILURE mean? how to solve it ?

### ISSUE THREAD

**Issue by henzycuong1** [eclipse-paho/paho.mqtt.c#1060]
Hi there,

What's MQTTCLIENT_FAILURE mean? how to solve it ?

I have the error when I used "MQTTClient_connect" function.
I tried creating a new MQTTClient by MQTTClient_create after deleting my MQTTClient by MQTTClient_destory. But I still receive MQTTCLIENT_FAILURE when connecting.
Where am I wrong ?

** I'm sorry about my english **

**Comment by icraggs** [comment]
You can try taking a trace as described in the readme and attaching the log as a file.  It may help.

**Comment by henzycuong1** [comment]
> You can try taking a trace as described in the readme and attaching the log as a file. It may help.

Thank you, sir. I have fixed the problem.
