### ISSUE TITLE
MQTTClient (synchronous api) fails for wss:// connection

### ISSUE THREAD

**Issue by stronnag** [eclipse-paho/paho.mqtt.c#1061]
## Description

wss:// connections fail with the synchronous API. Connection to the same broker using tcp://, ssl:// or ws:// will suceed.

## To Reproduce

Use the sample `paho_cs_sub` application with a broker offering wss://, for example:

```
paho_cs_sub -c wss://broker.emqx.io:8084 -t dskhfs/weowpeop/asasasa/zxzx --trace protocol
```

The trace terminates with:

```
Trace : 4, 20210131 083251.305 SSL state connect:SSLv3/TLS read server session ticket:TLS_AES_256_GCM_SHA384
Trace : 4, 20210131 083251.305 SSL connect:SSL negotiation finished successfully
Trace : 4, 20210131 083251.305 WebSocket upgrade read not complete 0
Trace : 4, 20210131 083251.305 3 paho-cs-sub -> CONNECT version 3 clean: 1 (0)
Trace : 4, 20210131 083251.305 3 paho-cs-sub <- PUBACK msgid: 21584
Trace : 5, 20210131 083251.305 Bad MQTT packet, type 2
Trace : 4, 20210131 083251.305 SSL alert write:warning:close notify
Connect failed return code: Failure
```

Modifying the `MQTTClient_subscribe.c` to support SSL and user provided end-points results in 
```
Message with token value 21584 delivery confirmed
Message with token value 21584 delivery confirmed
Failed to connect, return code -1
```
i.e.  the same two unexpected `21584 delivery confirmed` messages.

## Expected behavior

wss:// should complete successfully.

## Log files ##

`paho_cs_sub -c wss://broker.emqx.io:8084 --trace protocol` attached.
[wss-sync-fail.txt](https://github.com/eclipse/paho.mqtt.c/files/5899401/wss-sync-fail.txt)

## Environment ##
 - OS: Debian (testing) and Arch Linux
 - Version: Paho Synchronous Client 1.3.8. Other relevant versions in the attached log file.

## Additional context ##
wss:// connections to the same endpoint succeed using the Paho Golang API.
Perhaps related to #1047 ?

**Comment by tchaloupka** [comment]
I can confirm that it's related to #1047.
Tried similar fix here: https://github.com/eclipse/paho.mqtt.c/blob/64a5ff3c3b71fe019353aeacaebc66a3cf4f3461/src/MQTTClient.c#L977

And client has connected successfully.
