### ISSUE TITLE
Is PINGRESP receipt expected to be notified via MQTTAsync_messageArrived() callback?

### ISSUE THREAD

**Issue by robpottify** [eclipse-paho/paho.mqtt.c#1063]
We have the Paho C client running and connecting to AWS IoT Core MQTT Broker.
We believe we are seeing keepalive responses raised via the MQTTAsync_messageArrived() callback into our application code, but I thought that Paho internally handles the keepalive PINGREQ and PINGRESP flow. 

The MQTTAsync_messageArrived() callback appears to be called for PINGRESP with an empty topic, so we are using the len(topic) to identify that this is a PINGRESP rather than a legit data message, and therefore skipping it.

Is it expected that the Paho C client exposes PINGRESP messages? I haven't observed that behaviour on the python client.

**Comment by icraggs** [comment]
It's not intended that the messageArrived callback is called for a PINGRESP, nor do I ever remember seeing it happen.  A client library trace, as suggested in the readme (at the protocol level first) might shed some light.

**Comment by icraggs** [comment]
I'm going to close this.  If you do have more information, you can reopen it.

**Comment by siyanggao** [comment]
notice the MQTTAsync_messageArrived return value,the message will deliver again at the same time as keepalive if return 0
