### ISSUE TITLE
publish message slowlly

### ISSUE THREAD

**Issue by dfqhappy** [eclipse-paho/paho.mqtt.c#1069]
Hi friend,
I use paho.mqtt.c (MQTTAsync) send message on high frequency，Dozens of messages per second。It works well on win10 systems,but when it works on some systems such as win7, the message published very slowlly, Within 10 messages per second. I used QOS0.

my test method:
when it publish message, i use paho client to SubScribe the message. The server address is 127.0.0.1, so the mqtt server is the same pc. 

i do not know why,can you give me some ....

int CPahoMQTTClient::Connect(const char* pClientID, StMqttConn mqttConn)
{
	int nRet = 0;
	m_stMqttConn = mqttConn;
	m_strClientID = pClientID;
	m_nKeepAliveInterval = CDagConfig::GetInstance()->GetConfig().mqttServerInterval;
	string strAddr = "tcp://";
	strAddr += mqttConn.ipv4 + ":" + mqttConn.port;
	LOG_DEBUG("mqtt connect address=%s", strAddr.c_str());
	m_connOpts = MQTTAsync_connectOptions_initializer;
	MQTTAsync_create(&m_ClientAsync, strAddr.c_str(), m_strClientID.c_str(), MQTTCLIENT_PERSISTENCE_NONE, NULL);
	MQTTAsync_setCallbacks(m_ClientAsync, (void*)this, _OnConnLost, _OnMsgArrvd, NULL);
	MQTTAsync_setConnected(m_ClientAsync, (void*)this, _OnConnected);
	
	m_connOpts.keepAliveInterval = m_nKeepAliveInterval;
	m_connOpts.password = mqttConn.password.c_str();
	m_connOpts.username = mqttConn.userName.c_str();
	m_connOpts.onSuccess = _OnSuccess;
	m_connOpts.onFailure = _OnFailure;
	m_connOpts.context = this;
	m_connOpts.cleansession = 0;
	m_connOpts.connectTimeout = 2;

	m_connOpts.automaticReconnect = 1;
	m_connOpts.retryInterval = 0;
	m_connOpts.maxRetryInterval = 10;
	m_connOpts.minRetryInterval = 2;

	if ((nRet = MQTTAsync_connect(m_ClientAsync, &m_connOpts)) != MQTTASYNC_SUCCESS)
	{
		LOG_DEBUG("Failed to connect, code=%d", nRet);
		return err_Connect;
	}
	return err_Success;
}

int CPahoMQTTClient::Publish(const char* pTopic, const char* pMessage)
{
	if (!IsConnected())
	{
		LOG_ERROR("mqtt not connected");
		return err_Connect;
	}
	if (pTopic == NULL || NULL==pMessage)
	{
		LOG_ERROR("param invalid");
		return err_ParamInvalid;
	}
	int rc=0;
	MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
	string strMessage = pMessage;
	string strUTF8Message = GBToUTF8(strMessage);
	pubmsg.payload = (char*)strUTF8Message.c_str();
	pubmsg.payloadlen = strUTF8Message.length();
	pubmsg.qos = MQTT_QOS;//0
	pubmsg.retained = 0;

	MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
	opts.onSuccess = _OnSend;

	opts.onFailure = _OnSendFailure;
	opts.context = this;
	string strTopic = pTopic;
	string strUTF8Topic = GBToUTF8(strTopic);
	
	if ((rc = MQTTAsync_sendMessage(m_ClientAsync, strUTF8Topic.c_str(), &pubmsg, &opts)) != MQTTASYNC_SUCCESS)
	{
		LOG_ERROR("Failed to send sendMessage, code=%d", rc);
		return err_Publish;
	}
	return err_Success;
}

**Comment by icraggs** [comment]
I don't see by what means you are deciding to publish the next message.  The Win7 systems might be slower, or have slower network connections?

**Comment by icraggs** [comment]
In the absence of further information, I'm closing this.
