### ISSUE TITLE
websocket based mqtt is dead slow for 4K bytes data

### ISSUE THREAD

**Issue by RamakrishnanOSS** [eclipse-paho/paho.mqtt.c#1071]
Greetings,

Websocket based mqtt is dead slow for 4Kbytes data but TCP based is faster.

I could only send & receive 2.5messages / second whereas with TCP I could send 1252 messages / second.

This happens only for websocket & 4K combination. for Others as expected ws is faster. Any clue?

**To Reproduce**
1. Use ws://localhost -> protocol instead of tcp://locahost
2. send 4K bytes of data

I do not have any special settings.

**Expected behavior**
ws:// based transfer should exceed the count of tcp://

**Environment**
 - OS:  Ubuntu
 - Version 20.04LTS
 - MQTT version 1.38 compiled with -HIGH_PERFORMANCE=true

**Comment by icraggs** [comment]
I wouldn't expect websockets to be faster than straight TCP at any time as there is extra translation to/from websocket frames.  I would expect it to be slower.

A trace, as described in the readme (at min level), of a 4k case and another for comparison might help.

**Comment by icraggs** [comment]
No response to request for more info.
