### ISSUE TITLE
The name of the source zip and tar.gz don't include the projects name

### ISSUE THREAD

**Issue by d4ddi0** [eclipse-paho/paho.mqtt.c#1072]
The compiled packages nicely tell you who they are, e.g. eclipse-paho-c-1.3.8-win64.zip.

But the source package is rather lamely named "v1.3.8.tar.gz", or "v1.3.8.zip".
It would be grand for finding them later, or deciding whether to eventually delete them if they also followed the "eclipse-paho-c-1.3.8.tar.gz" format.

**Comment by icraggs** [comment]
I don't think I have control over those names as Github generates the files from the tag.  Changing the tag name convention seems like the wrong approach.

**Comment by d4ddi0** [comment]
The download link does some magic filename fix when downloaded using a web browser. So its only cli downloaders such as wget that actually get the weird name. After posting this, I found https://stackoverflow.com/a/41692847/1419731 It is possible to name the download anything you want. The suffix determines the format.
