### ISSUE TITLE
Cannot connect to HiveMQ broker - MQTTCLIENT_FAILURE   -1

### ISSUE THREAD

**Issue by minaee** [eclipse-paho/paho.mqtt.c#1075]
I created a hiveMQ cluster in the HiveMq cloud and created a username and password.

From Paho C library I created MQTTClient_connectOptions and put my username and password as parameters:

```
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "MQTTClient.h"

#define ADDRESS     "tcp://myURL:8883"  // broker address
#define CLIENTID    "myclientID"
#define TOPIC  "testtopic"
#define USERNAME "myUsername"
#define PASSWORD "myPassword" 

int main(int argc, char* argv[])
{
    /* MQTT Client initialization */ 
    MQTTClient client;
    MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
    MQTTClient_message pubmsg = MQTTClient_message_initializer;
    MQTTClient_deliveryToken token;

    int rc; //status code received from broker
    rc = MQTTClient_create(&client, ADDRESS, CLIENTID,
                            MQTTCLIENT_PERSISTENCE_NONE, NULL);
    printf("Client create reason code: %d\n", rc);
    conn_opts.keepAliveInterval = 20;
    conn_opts.cleansession = 1;
    conn_opts.username = USERNAME;
    conn_opts.password = PASSWORD;
    

    MQTTClient_setCallbacks(client, NULL, connlost, msgarrvd, delivered);

    // checks whether the connection is successful or not
    if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to connect, return code %d\n", rc);
        exit(-1);
    }

    MQTTClient_message msg = MQTTClient_message_initializer;
    msg.payload = "hi"
    msg.payloadlen = strlen(msg.payload);
    msg.qos = 2;    
    msg.retained = 0; 

    /*
        sending data
    */
    rc = MQTTClient_publishMessage(client, topic, &msg, token);

    // Disconnect
    int timeout = 100;  // ms
    MQTTClient_disconnect(client, timeout);
    MQTTClient_destroy(&client);

    return rc;
}
```
the `MQTTClient_connect` cannot connect to the broker and return -1:

> Failed to connect, return code -1

I tried connecting with MQTT CLI, it was successful, I published and subscribed to a topic and transferred a msg. this is how I connect to broker with MQTT CLI:

> con -h xxxxxx...xxxx.env-1.hivemq.cloud -p 8883 -s -u myUsername -pw myPassword

I don't use TLS~SSL in the CLI connection but it works, So my authentication in C code is wrong.

How to correctly connect with simple authentication with the Paho C library?

**Comment by icraggs** [comment]
A trace (at the normal level), as described in the readme, might show more about what's going on.

**Comment by minaee** [comment]
> A trace (at the normal level), as described in the readme, might show more about what's going on.

Thank you for reminding me. I added `MQTTClient_setCallbacks` as following:

```
void trace_callback(enum MQTTCLIENT_TRACE_LEVELS level, char* message)
{
	printf("%s(): Trace : %d, %s\n", __func__ ,level, message);
}

int main(int argc, char* argv[])
{
    ...
    MQTTClient_setCallbacks(client, NULL, connlost, msgarrvd, delivered);
    MQTTClient_setTraceCallback(trace_callback);
    MQTTClient_setTraceLevel(MQTTCLIENT_TRACE_PROTOCOL 	);

    if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to connect, return code %d\n", rc);
        exit(-1);
    }

    return rc;
}
```

here is the output:

> Client create reason code: 0
> trace_callback(): Trace : 4, 20210310 134505.848 3 Publisher -> CONNECT version 4 clean: 1 (0)
> trace_callback(): Trace : 5, 20210310 134505.848 waitfor unexpectedly is NULL for client Publisher, packet_type 2, timeout 29686
> trace_callback(): Trace : 4, 20210310 134505.848 3 Publisher -> CONNECT version 3 clean: 1 (-22)
> trace_callback(): Trace : 5, 20210310 134505.848 waitfor unexpectedly is NULL for client Publisher, packet_type 2, timeout 29493
> Failed to connect, return code -1

**Comment by icraggs** [comment]
That trace doesn't indicate a username/password problem.

I changed the broker hostname to broker.hivemq.com in the MQTTClient_publish sample, and that worked fine.

I used the command line sample 

paho_cs_pub x --connection broker.hivemq.com --trace protocol

which also worked fine.  

8883 is usually the TLS port, 1883 the non TLS port.  You should check that you're using the correct one for your configuration.

**Comment by jumoog** [comment]
if you use TLS you have to use ssl:// as URI

**Comment by minaee** [comment]
> if you use TLS you have to use ssl:// as URI
@icraggs 

HiveMQ did not provided me with public key/private key for using TLS. there was just URL and port (8883) which is for TLS.

By the way, when I use "ssl://...." as URI and set the port 1883 instead of 8883, the "MQTTCLIENT_TRACE_ERROR" returns these messages:

> Client create reason code: -14
> Failed to connect, return code -1

code -14 is:  MQTTCLIENT_BAD_PROTOCOL   -14
and code -16 is: MQTTCLIENT_WRONG_MQTT_VERSION   -16

it shows that 'tcp' should be used intead of 'ssl'. but what is wrong with the MQTT version?

**Comment by icraggs** [comment]
The comment for -14 on create says:

  * protocol prefix in serverURI should be tcp://, ssl://, ws:// or wss://
  * The TLS enabled prefixes (ssl, wss) are only valid if the TLS version of the library is linked with.

You need to link with the paho-mqtt3cs library (note the final s) to use SSL/TLS.

**Comment by minaee** [comment]
yes, I added `client.tls_set` and the client could finally connect to the broker.
sorry I forgot to close the issue here.
