### ISSUE TITLE
When restoring messages from persistence on startup, it seems 2 connections are made

### ISSUE THREAD

**Issue by svanharmelen** [eclipse-paho/paho.mqtt.c#1080]
**Describe the bug**
It looks like 2 connections are made with the same client ID when we start our application with `restoreMessages` and persisted messages on disk. The problem is that both these connection use the same client ID and AWS IoT Core doesn't allow that. So as soon as the second connection is made, the first connection is forcefully disconnected preventing the republishing of old messages to succeed.

I think there could be 2 solutions. One (probably the preferred one) solution is to make sure only one connection is used. The other option could be to give the connection that is used to republished persisted messages a custom client ID.

**To Reproduce**
Again, this is difficult. We use the default file based persistence in combination with an AWS IoT Core endpoint.

**Expected behavior**
Preferably use only one connection instead of two.

** Environment (please complete the following information):**
 - OS: Linux
 - Version v1.3.8

**Comment by icraggs** [comment]
TCP connections are only created in the connect operation.  Restoring messages is done during create.  

To get two TCP connections I think you have to be calling connect twice, perhaps before the first one has completed.

**Comment by svanharmelen** [comment]
Restoring messages in this context means reading the persisted messages from disk/database and putting them in the queue right? Or are they then also directly send to the MQTT broker (so is a `connect` called during the `create` operation in this case)?

**Comment by svanharmelen** [comment]
Following the code, it indeed looks like during `create` persisted messages are "only" read and put onto the queue. So `connect` is not called from here... Yet I'm very sure I only call `connect` once myself.

**Comment by svanharmelen** [comment]
I'll have another look and will gather some logs as well. But meanwhile, issue #1079 is hurting us much more. So if you have any ideas or pointers about that one that would be great!

**Comment by icraggs** [comment]
Connect is not called implicitly during restore.  It's only called explicitly through the API.

**Comment by svanharmelen** [comment]
I implemented a custom persistence store and don't see the issue anymore. It didn't happen too often so maybe it's pops up again in the future, but I'll close this one for now 👍🏻
