### ISSUE TITLE
Old security issue not fixed

### ISSUE THREAD

**Issue by tardyp** [eclipse-paho/paho.mqtt.c#1084]
Hello,
While looking for public security issue for this library I found that there is no CVE assigned to it and actually no CPE (product identifier).

We can still find some evidence that there has been at least one security report, which was later disclosed.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=543626
https://bugzillaattachments.eclipsecontent.org/bugs/attachment.cgi?id=277237

While studying the security report, and the actual code in the mainline, I dont find any evidence that the issue is actually fixed.

There report actually describe two issues. Awaiting some more feedback before creating specific bugs.

**Comment by icraggs** [comment]
Thanks for pointing this out.  I thought I'd fixed the packet data handling previously but evidently not.  I've added a fix now.

The second part is not actually achievable in practise.
