### ISSUE TITLE
Calling MQTTAsync_connect after the "connection lost callback" doesn't reconnect the client

### ISSUE THREAD

**Issue by satyamtpatel** [eclipse-paho/paho.mqtt.c#1088]
**Describe the bug**
After broker connection is lost, connection lost callback is not able to connect it again. I am using your sample MQTTASync_subscribe example to test it but it is not working. I am using version 1.3.2 version of MQTT Client. I am attaching image in the below content.

![image](https://user-images.githubusercontent.com/33553292/112224721-15e3b580-8c02-11eb-98e7-e6663a8054e9.png)

**Comment by jumoog** [comment]
maybe related to #955.. try the newest version.

**Comment by icraggs** [comment]
That output appears to show a successful reconnection.

**Comment by satyamtpatel** [comment]
I was expecting it to call onConnect callback method to perform subscription task.

**Comment by icraggs** [comment]
Ah, your description just talks about reconnection.  

You need to set the connected callback with the MQTTAsync_setConnected function.  And it's a good idea to use the latest version, as @jumoog suggested.
