### ISSUE TITLE
Can paho-mqtt-c read certificate from memory?

### ISSUE THREAD

**Issue by linxingyang** [eclipse-paho/paho.mqtt.c#1091]
HI.
I'm using cert for mqtt client to connect mqtt server safely, but struggle with how to save the cert files(ca.crt, client.key, client.crt) safely, i can not modify or encrypt those files, so i want paho-mqtt-c lib can load thoes files from memory  instead of files, but i don't find such methods, and i did find OpenSSL support load cert files from memory.
need i do it myself, add a method to pass memory to paho then openssl load it ?
or there's another way?

linxy.

**Comment by jumoog** [comment]
paho-mqtt-c expects the certificates to be available as a file.

**Comment by linxingyang** [comment]
Thank you.
What a pity.

linxy.
