### ISSUE TITLE
crosscompile for ARM -> undefined reference to "" Error

### ISSUE THREAD

**Issue by una801** [eclipse-paho/paho.mqtt.c#1093]
I want to connect to ARM Board with aws IoT Core It is being crosscompiled. As a result, a linking error occurs while running make through the library path, such as openssl (crosscompiled).

The following errors are displayed:
```
[ 51%] Linking C executable paho_c_pub
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'SSLeay_version'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'CRYPTO_THREADID_set_numeric'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'ERR_get_error'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'ERR_print_errors_cb'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'ERR_load_crypto_strings'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'OPENSSL_add_all_algorithms_noconf'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'CRYPTO_num_locks'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'CRYPTO_THREADID_set_callback'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'CRYPTO_set_locking_callback'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'ERR_free_strings'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'EVP_cleanup'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'ERR_clear_error'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'BIO_f_base64'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'BIO_new'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'BIO_s_mem'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'BIO_push'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'BIO_set_flags'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'BIO_write'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'BIO_ctrl'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'BIO_read'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'BIO_free_all'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'RAND_bytes'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'SHA1_Init'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'SHA1_Update'
../libpaho-mqtt3as.so.1.3.8: error: undefined reference to 'SHA1_Final'
collect2: error: ld returned 1 exit status
```

openssl version is 1.02h( ARM board's version)
I'm trying to compile like these command
`$ cmake .. -DOPENSSL_LIB_SEARCH_PATH=/home/youna/tm2sdk/sysroots/armv7a-vfp-neon-oe-linux-gnueabi -DPAHO_WITH_SSL=TRUE -DOPENSSL_INCLUDE_DIR=/home/youna/tm2sdk/sysroots/armv7a-vfp-neon-oe-linux-gnueabi/usr/include/openssl -DOPENSSL_LIB=/home/youna/tm2sdk/sysroots/armv7a-vfp-neon-oe-linux-gnueabi/usr/lib/libssl.so -DOPENSSLCRYPTO_LIB=/home/youna/tm2sdk/sysroots/armv7a-vfp-neon-oe-linux-gnueabi/usr/lib/libcrypt.so -DOPENSSL_ROOT_DIR=/home/youna/tm2sdk/sysroots/armv7a-vfp-neon-oe-linux-gnueabi -DPAHO_BUILD_SAMPLES=TRUE -DBUILD_SHARED_LIBS=ON
`
i succeed to cmake , but when i try to make , error appears like above message.

How can I do this ??

OS : Ubuntu 20.04 LTS

**Comment by icraggs** [comment]
These are link errors for the OpenSSL libraries.  Perhaps your linux build type (endian, processor etc) doesn't match that of the OpenSSL libraries.  The file command will display those attributes.

Apart from that I don't know - cross compiling is something I generally don't do.

**Comment by una801** [comment]
So it's not a problem with openssl 1.0.2 version? When cross-compiling with openssl1.1 it is more confusing because the build is good (same path setting and compilation method).

Is there a command that needs to be added in addition to the route setting when link error occurs?

**Comment by jumoog** [comment]
You have both Versions installed on your System?

**Comment by una801** [comment]
Yes, version 1.0.2 of openssl is included in device sdk. Would it be a problem if it was downloaded in duplicate?

**Comment by icraggs** [comment]
Only a problem if the build was trying to pick up the wrong build of openssl.  That could result in the output you show.

**Comment by icraggs** [comment]
I think this question has been answered.
