### ISSUE TITLE
Pending tokens, inflight messages and buffered messages

### ISSUE THREAD

**Issue by martinboers** [eclipse-paho/paho.mqtt.c#1094]
I would like to understand more about the relationship between "pending tokens", "inflight messages" and "buffered messages".

I notice that a recent issue (#1092) includes similar questions, but unfortunately that has not answered my questions, nor has an examination of the source code (I got confused quite quickly).

I have noticed the following behaviour on a simple asynchronous client that is publishing messages using a quality of service value of 1:

- When the connection between client and server is good, the list of pending delivery tokens returned by `MQTTAsync_getPendingTokens()` is usually empty, but may occassionally contain a few tokens for a brief period.
- When there are network problems, the list of delivery tokens returned by `MQTTAsync_getPendingTokens()` can get quite large. I have an example where this list gets to 1500 entries during a brief network outage.
- When the brief network outage is over, the list of delivery tokens returned by `MQTTAsync_getPendingTokens()` shrinks until it is (usually) empty again.

This is all fine. It is great that published messages are automatically buffered by the client during brief network outages, and delivered when the network is restored.

I tried running the same test with the `maxinflight` field in the `MQTTAsync_connectOptions` strucure set to 10. This seemed to make no difference to the result - the list of pending tokens returned by `MQTTAsync_getPendingTokens()` increased way above 10 during brief network outages. I have looked at the source code, but I cannot tell if this behaviour is expected. In this case, I do not understand why the `maxinflight` value had no effect on the number of tokens in the "pending token" list. Should it?

I thought that perhaps the `maxBufferedMessages` field in the `MQTTAsync_createOptions` structure was playing a part, but I am calling `MQTTAsync_create()`, not `MQTTAsync_createWithOptions()`, so I think that there will be no "buffered messages" in this case. And anyway, during the brief network outage the client still thinks it is connected (`MQTTAsync_isConnected() == true` for the entire period of the brief network outage), and this "buffer" (the one affected by the `maxBufferedMessages` field) only comes into play when the client thinks it is not connected ... right?

Thanks a million for any advice.

**Comment by svanharmelen** [comment]
To my knowledge (but would be nice if @icraggs can confirm this), `maxBufferedMessages` is used to set the maximum number of messages that is allowed to be queued. Being queued here means to be put on an in memory queue waiting to be processed. Looking at the code I got the impression that when using `MQTTAsync_create()` it doesn't set a max buffer size and will always allow new messages on the queue (not sure though).

`maxInflight` on the other hand is (when using QoS 1 or 2) used to limit the number of publish requests that are send to the MQTT server, but not acknowledged yet. So when your network connection drops, it will not be able to send new publish requests but it will still be able to queue new messages to be processed when the connection is restored again.

Hope this helps a little...

**Comment by icraggs** [comment]
getPendingTokens() returns the number of queued messages *plus* those inflight.

Max inflight governs the maximum number of simultaneous QoS 1 and 2 outbound publishes allowed.  That is, those that are in the process of being transmitted over the TCP connection.  This number could typically be 10 or 20.  

Max buffered controls the number of messages on the queue - which is where they are stored before being sent over TCP/IP.  If the inflight "window" is full, the messages will be queued until there is a space in that window (caused by a QoS 1 or 2 exchange completing).

**Comment by martinboers** [comment]
Great, this is excellent information. If I understand correctly:

- Messages do not immediately become "in flight" as soon as they are published - they first pass through a local (client-side) buffer. This helps to explain the behaviour I am seeing.
- The local buffer is the same buffer that is used to store messages that are published when the client is not connected (if enabled by the `sendWhileDisconnected` field in the `MQTTAsync_createOptions` structure).
- The size of the local buffer is controlled by `maxBufferedMessages` field in the `MQTTAsync_createOptions` structure.
- If `MQTTAsync_create()` is used instead of `MQTTAsync_createWithOptions()`, then messages will not be stored in the buffer while the client is disconnected, and there is no maximum buffer size.

I guess I was thrown by the "while not connected" part of [the comment](https://github.com/eclipse/paho.mqtt.c/blob/64a5ff3c3b71fe019353aeacaebc66a3cf4f3461/src/MQTTAsync.h#L949) attached to the `maxBufferedMessages` field - but this does not refer to the result of the `MQTTAsync_isConnected` function, it refers to whether or not messages are actually able to be transmitted via TCP.

So, I can limit the number of messages in the buffer, _even while the client thinks it is still connected_, by using the `MQTTAsync_createWithOptions()` with `maxBufferedMessages` set to the maximum buffer size.

Thank you both for your fast and very helpful replies.

**Comment by icraggs** [comment]
My fast reply was partly an accident of timing!

I also just realized in my reply to #1092 that the max combined number of QoS 1 and 2 messages that can be queued is 64k because they are assigned MQTT packet ids which are limited to that number.   The number of QoS 0 messages that can be queued is only limited by maxBufferedMessages (minus any QoS 1 and 2 messages that are also queued) because QoS 0 messages do not have packet ids.
