### ISSUE TITLE
MQTTAsync_publish_Time.c and multithreads

### ISSUE THREAD

**Issue by ghost** [eclipse-paho/paho.mqtt.c#1098]
Hi, 
i have a test setup where i have on localhost my mosquitto broker and a client mqtt-spy to connect to it and view the publishing done by this example and also to publish on topics which this example i made to subscribed to.
I placed this example in its own thread with little modifications. Now i have some strange behavior. I made this example switchable. So i can send the time intentionally. I use the mqtt-spy to make that happen by publishing to the right topic. Starting to send the time works, even if a open more threads.
But as soon as i send the stop event it stops but after some time i get new messages without forcing that.
Those messages are rubbish and i can not send any start or stop event to this example anymore correctly they are all rubbish. Just for giving a hint my keepalive is 10 and i send every secound.
[mqtt.txt](https://github.com/eclipse/paho.mqtt.c/files/6442970/mqtt.txt)

**Comment by icraggs** [comment]
You'll need to provide more information as requested in the issue template.  A client library trace or test program, version of the library, OS, connection type (TCP, TLS, WebSockets), those sorts of things.

**Comment by ghost** [comment]
Hi Ian,
i am using the paho c library the newest one downloaded recently. I use VS and my OS is windows 10. I am not using TLS and my broker is on the same system as my application. I use the MQTTAsync_publish_Time.c example provided by the library with little modifications mainly printf and a feature to swicht on/off the publishing of the time. I placed it in its own thread because later i would like to open several clients to mqtt broker each in its own thread. I use an opensource mqtt client programm named mqtt-spy to communicate and have a visual feedback what is going on.

Maybe its better to give you a rough overview. 
My system should be able to publish info to the broker coming from dozen of devices whom are many of different device typs. One single device should have its own server running in its own thread which should forward all incoming messages to te broker. It is not posible to open several clients with the same clientID so each thread was its own clientID. Up to that point i could achive that, but when a send stop request it stop yes but as shown in my appendings the message receive buffer is somehow corrupted later one. I see that because there are printf. The message biffer would be freeed MQTTAsync_free() is this thread safe? Does library use one single message buffer for all opened clientIDs. Is there any multithreading aproaches in those examples.

Thanks in advance Ian

**Comment by icraggs** [comment]
"but when a send stop request it stop"  - a stop request to what?  What stops?

"The message biffer would be freeed MQTTAsync_free() is this thread safe?" Yes.  

"Does library use one single message buffer for all opened clientIDs." - no.

A client library trace (as described in the readme) could shed some more light.

**Comment by icraggs** [comment]
No more information, so closing.
