### ISSUE TITLE
Where can I set  successful reconnect callback?

### ISSUE THREAD

**Issue by forstef** [eclipse-paho/paho.mqtt.c#1101]
https://github.com/eclipse/paho.mqtt.c/issues/282#issuecomment-308788816

Found: MQTTAsync_setConnected()

But could I get the actual retry events when reconnecting even it is failed?

**Comment by icraggs** [comment]
No.  Well you can see them in the trace at the protocol level, which you can see in the trace callback if you want.

**Comment by icraggs** [comment]
I think I've answered this question.
