### ISSUE TITLE
When I unplug the server network cable, the client waited 80 seconds before receiving the "connection lost". 

### ISSUE THREAD

**Issue by WKD-007** [eclipse-paho/paho.mqtt.c#1102]
version: paho.mqtt.c-1.2.1
When I unplug the server network cable, the client waited 80 seconds before receiving the "connection lost". 
Then I found it stuck for 60 second in the “shutdown(socket, SHUT_WR)” statement of the “Socket_close_only” function.
![image](https://user-images.githubusercontent.com/52060078/118106423-2d743900-b410-11eb-9b88-7a207b1cab0b.png)
Then I made the following changes and it worked.
![image](https://user-images.githubusercontent.com/52060078/118106808-99ef3800-b410-11eb-9ea3-76671d49c8b7.png)

**Comment by icraggs** [comment]
I'm guessing that means it's skipped all the time which doesn't seem like a good idea.

You're using version 1.2.1 - the latest version is 1.3.8.  You don't say what platform you're using.

Also, the time needed to detect a lost connection is affected by the keepalive time.  What are you using?

What amount of activity did you have on the socket when you pulled out the cable?

**Comment by WKD-007** [comment]
Thanks for your comments.

It does not call "shutdown(socket, SHUT_WR)" only when the socket is not writable.

I tried the latest version yesterday and had the same problem.

When using other platforms, this will not happen, maybe it is the difference of kernel version or hardware, the platform I use is arm platform,
![image](https://user-images.githubusercontent.com/52060078/118210591-36f7b280-b49d-11eb-87d8-5c78898ce776.png)

**Comment by icraggs** [comment]
I thought it might not be a "mainstream" platform - ARM.  I also note that Linux kernel 3.10 reached end of life in 2017.   

A client library trace could still be useful, as outlined in the readme.  Also, the return code from the shutdown call.  I don't think shutdown should block.

**Comment by icraggs** [comment]
Closing in the absence of further information.
