### ISSUE TITLE
How can I let mqtt broker generate MQTT PROPERTY CODE ASSIGNED CLIENT IDENTIFIER?

### ISSUE THREAD

**Issue by forstef** [eclipse-paho/paho.mqtt.c#1103]
Accordding to mqtt version 5:

A Server MAY allow a Client to supply a ClientID that has a length of zero bytes, however if it does so the Server MUST treat this as a special case and assign a unique ClientID to that Client [MQTT-3.1.3-6]. It MUST then process the CONNECT packet as if the Client had provided that unique ClientID, and MUST return the Assigned Client Identifier in the CONNACK packet [MQTT-3.1.3-7].

So how could I do this in this library?

**Comment by icraggs** [comment]
Isn't it self explanatory?

Use a zero length client id - "".  Extract the assigned client id from the MQTT 5 properties.

**Comment by icraggs** [comment]
The MQTT 5.0 properties returned in the onSuccess callback from the connect, I should say.   I think this question has been answered now.
