### ISSUE TITLE
MQTTClient_subscribeMany

### ISSUE THREAD

**Issue by gao1293181874** [eclipse-paho/paho.mqtt.c#1105]
For the function shown in the title, check whether there is an upper limit for the number of subscriptions. After a simple test, 1000 subscriptions succeed and 2000 subscriptions fail, the return value is -22. This error code is not found in the document.

**Comment by icraggs** [comment]
-22 is an interrupted socket write.  There isn't an upper limit of subscriptions imposed by MQTT except insofar as the packet size is not exceeded, or any limit imposed by the broker receiving the request.  I would expect a practical use case to use less than 10 subscriptions, not 1000 or 2000.

A trace, as suggested in the issue template, could show more.

**Comment by icraggs** [comment]
I think this has been answered.
