### ISSUE TITLE
A segment faultoccurred after calling MQTTAsync_SendMessage

### ISSUE THREAD

**Issue by hyl1416134510** [eclipse-paho/paho.mqtt.c#1106]
HI,
A segment error occurred when I called mqttasync_sendMessage after compiling paho.mqtt.c using the cross-compiler tool
This is my cross-compiled version of GCC
arm-linux-gcc -v
Using built-in specs.
COLLECT_GCC=arm-linux-gcc
COLLECT_LTO_WRAPPER=/home/hyl/arm_linux_4.8/bin/../libexec/gcc/arm-nuvoton-linux-uclibceabi/4.8.4/lto-wrapper
Target: arm-nuvoton-linux-uclibceabi
Configured with: ../configure --prefix=/usr/local/arm_linux_4.8 --target=arm-nuvoton-linux-uclibceabi --enable-static --disable-__cxa_atexit --with-gnu-ld --disable-libssp --disable-multilib --enable-target-optspace --disable-libsanitizer --enable-tls --disable-libmudflap --enable-threads --without-isl --without-cloog --with-float=soft --disable-decimal-float --with-abi=aapcs-linux --with-cpu=arm926ej-s --with-float=soft --with-mode=arm --enable-languages=c,c++ --enable-poison-system-directories --enable-shared --disable-libgomp --with-sysroot=/usr/local/arm_linux_4.8 --with-build-time-tools=/usr/local/arm_linux_4.8/arm-nuvoton-linux-uclibceabi/bin --enable-shared
Thread model: posix
gcc version 4.8.4 (GCC) 

My test code:
#include "mqtt/MQTTAsync.h"
#include <string>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <pthread.h>

MQTTAsync m_client;
std::string m_addr = "ssl://192.168.1.151:8883";
std::string m_client_Id = "mqttx_071cc2c1111";
std::string m_user_name = "unilumin-cli";
std::string m_pass = "Unilumin123*";
int m_keep_alive_interval = 20;
int m_clean_sesson = 1;
int m_n_usessl = 1;

void onConnectFailure(void* context, MQTTAsync_failureData* response)
{
     printf("Connect failed, rc %d\n", response ? response->code : 0);
	 //CMqtt::GetInstance()->ConnectToSrv();
	 //CMqtt::GetInstance()->ConnectToSrv();
}

void onConnect(void* context, MQTTAsync_successData* response)
{
	MQTTAsync client = (MQTTAsync)context;
	int rc;
	printf("success\n");
    MQTTAsync_message pubmsg2 = MQTTAsync_message_initializer;
    pubmsg2.payload = (void*)"pStr";
    pubmsg2.payloadlen = 4;
    pubmsg2.qos = 0;
    pubmsg2.retained = 0;
	printf("send\n");
    if ((rc = MQTTAsync_sendMessage(client, "smartPole/gataway-nuvoton/notify/hb/server/rtdata", &pubmsg2, NULL)) != MQTTASYNC_SUCCESS)
    {
          printf("Failed to start sendMessage, return code %d", rc);
          //exit(EXIT_FAILURE);
          return ;
    }
	printf("CMqtt::send\n");
}
int msgarrvd(void *context, char *topicName, int topicLen, MQTTAsync_message *message)
{

}

void connlost(void *context, char *cause)
{

}

bool CreateClient()
{
	int rc = 0;
	if((rc = MQTTAsync_create(&m_client, m_addr.c_str(), m_client_Id.c_str(),MQTTCLIENT_PERSISTENCE_DEFAULT, NULL))!= MQTTASYNC_SUCCESS) 
	{
		printf("mqtt client create failer %s:%s errorcode %d",m_addr.c_str(), m_client_Id.c_str(),rc);
		return false;
	}
	MQTTAsync_setCallbacks(m_client, NULL, connlost, msgarrvd, NULL);
	return true;
}
bool ConnectToSrv()
{

	MQTTAsync_SSLOptions ssl_opts = MQTTAsync_SSLOptions_initializer;
	ssl_opts.enableServerCertAuth = false;
		
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
    conn_opts.keepAliveInterval = m_keep_alive_interval;
    conn_opts.cleansession = m_clean_sesson;
	
	conn_opts.username = m_user_name.c_str();
	conn_opts.password = m_pass.c_str();
	conn_opts.serverURIcount = 0;
	conn_opts.serverURIs = NULL;

	if(0 != m_n_usessl)
	{
		conn_opts.ssl = &ssl_opts;
	}
	
	
	conn_opts.onSuccess = onConnect;
    conn_opts.onFailure = onConnectFailure;
    conn_opts.context = m_client;	

	//m_client = pClient;
	
	int rc;
	if ((rc = MQTTAsync_connect(m_client, &conn_opts)) != MQTTASYNC_SUCCESS)
    {
		printf("mqtt client connect failer code %d", rc);
       return false;
    }
	printf("connecting...\n");
	return true;
}
int main()
{
	printf("123\n");
	CreateClient();
	ConnectToSrv();
	while(1);
}

Run the phenomenon:
# ./mqttTest
123
connecting...
success
send
CMqtt::send
Segmentation fault

My guess is if there is something wrong with sending the function callback asynchronously

Looking forward to your reply,   thk

**Comment by hyl1416134510** [comment]
about my environment:
paho.mqtt.c version :  1.3.8
system: Linux (none) 4.4.115

**Comment by icraggs** [comment]
I tried your test program and it worked for me, without any segfault.  

You should take a client library trace or a gdb backtrace which might give some more information.

**Comment by hyl1416134510** [comment]
Thank you for your reply, when I changed the 4th parameter of MQTTAsync_create from "MQTTCLIENT_PERSISTENCE_DEFAULT" to "MQTTCLIENT_PERSISTENCE_NONE", the program ran normally. I read the explanation about this parameter, it may be related to my file system, my root file The system is "yaffs2", I don't know if it is the reason why "MQTTCLIENT_PERSISTENCE_DEFAULT" does not support this file system

**Comment by icraggs** [comment]
Perhaps the default file storage location is not writable?

**Comment by hyl1416134510** [comment]
Which path is the default file storage location？

**Comment by icraggs** [comment]
The current working directory, if you don't set it (as noted in the documentation for create).

**Comment by hyl1416134510** [comment]
The current working directory is  writable

**Comment by icraggs** [comment]
So I suggest again a client library trace (as described in the readme) and/or a gdb backtrace.

**Comment by icraggs** [comment]
Closing as no more information was provided.
