### ISSUE TITLE
"Failed to connect, return code -15" when trying to use MQTT protocol version 5

### ISSUE THREAD

**Issue by hbuggi** [eclipse-paho/paho.mqtt.c#1111]
**Description:**

I am trying to use MQTT protocol version 5 when connecting to HIveMQ CE broker. But I am getting the following response

"Failed to connect, return code -15"

If I do not set the protocol version the program works fine. 

**To Reproduce:**

This is the program.

#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "MQTTClient.h"

#define ADDRESS     "tcp://localhost:1883"
#define CLIENTID    "ExampleClientPub"
#define TOPIC       "MQTT Examples"
#define PAYLOAD     "Hello World!"
#define QOS         1
#define TIMEOUT     10000L

int main(int argc, char* argv[])
{
    MQTTClient client;
    MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
    MQTTClient_message pubmsg = MQTTClient_message_initializer;
    MQTTClient_deliveryToken token;
    int rc;

    MQTTClient_create(&client, ADDRESS, CLIENTID,
    MQTTCLIENT_PERSISTENCE_NONE, NULL);
    conn_opts.keepAliveInterval = 20;
    conn_opts.cleansession = 1;
    conn_opts.username = "myusername";
    conn_opts.password = "mypassword";
    conn_opts.MQTTVersion = 5;

    if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to connect, return code %d\n", rc);
        exit(-1);
    }
    pubmsg.payload = PAYLOAD;
    pubmsg.payloadlen = strlen(PAYLOAD);
    pubmsg.qos = QOS;
    pubmsg.retained = 0;
    MQTTClient_publishMessage(client, TOPIC, &pubmsg, &token);
    printf("Waiting for up to %d seconds for publication of %s\n"
            "on topic %s for client with ClientID: %s\n",
            (int)(TIMEOUT/1000), PAYLOAD, TOPIC, CLIENTID);
    rc = MQTTClient_waitForCompletion(client, token, TIMEOUT);
    printf("Message with delivery token %d delivered\n", token);
    MQTTClient_disconnect(client, 10000);
    MQTTClient_destroy(&client);
    return rc;
}

I am compiling on Ubuntu 18.04.4 LTS with the following commands 

gcc -L c_client c_client.c -l paho-mqtt3c

./a.out

**Expected:**

Expecting the program to publish the message "Hello World!" to the topic "MQTT Examples" using MQTT protocol version 5.

**Comment by Pascal-Fremaux** [comment]
MQTTClient.h
 /**
  * Return code: option not applicable to the requested version of MQTT
  */
 #define MQTTCLIENT_BAD_MQTT_OPTION -15

May be your pb come from you declare  MQTT Version=5  (MQTTv5) but you use a MQTTv3.1.1 initializer (should use MQTTClient_connectOptions_initializer5)

Also, may be wrong, but your topic name do not respect the topic naming rules (space)

https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/

And globally your settings are not in-lined with a MQTTv5 config (cleansession is for MQTTv3.1/V3.1.1, no idea what does a MQTTv5 config with it, same for username/password)

**Comment by hbuggi** [comment]
@Pascal-Fremaux thanks for your response and help. You were right and the program was not working because of the clean session flag - "conn_opts.cleansession = 1;"

I commented out this line and also changed the "MQTTClient_connectOptions_initializer" to "MQTTClient_connectOptions_initializer5" and the program is now working and client is able to connect to broker using MQTT protocol version 5.

**Comment by icraggs** [comment]
Thanks for your comment, @Pascal-Fremaux
