### ISSUE TITLE
Buid fails on CentOS7

### ISSUE THREAD

**Issue by swertz** [eclipse-paho/paho.mqtt.c#1113]
**Describe the bug**

I was trying to build paho.mqtt.c as a dependency of paho.mqtt.cpp, but on CentOS7 it fails at the linking stage:
```
Linking C shared library libpaho-mqtt3as.so
/bin/ld: cannot find -lOpenSSL::SSL
/bin/ld: cannot find -lOpenSSL::Crypto
```

**To Reproduce**

```
git clone https://github.com/eclipse/paho.mqtt.c.git
cd paho.mqtt.c
git checkout v1.3.9
cmake -Bbuild -H. -DPAHO_ENABLE_TESTING=OFF -DPAHO_BUILD_STATIC=ON \
    -DPAHO_WITH_SSL=ON -DPAHO_HIGH_PERFORMANCE=ON
sudo cmake --build build/ --target install
```

**Environment (please complete the following information):**

 - OS: Linus CentOS
 - Version 7
 - cmake version 2.8.12.2

`openssl-devel` version `1.0.2k` is installed, and I see the following libraries:
```
$ ls -1 /usr/lib64/*ssl*
/usr/lib64/libevent_openssl-2.0.so.5
/usr/lib64/libevent_openssl-2.0.so.5.1.9
/usr/lib64/libssl3.so
/usr/lib64/libssl.so
/usr/lib64/libssl.so.0.9.8e
/usr/lib64/libssl.so.10
/usr/lib64/libssl.so.1.0.2k
/usr/lib64/libssl.so.1.1
/usr/lib64/libssl.so.1.1.1g
/usr/lib64/libssl.so.6
/usr/lib64/libxmlsec1-openssl.so
/usr/lib64/libxmlsec1-openssl.so.1
/usr/lib64/libxmlsec1-openssl.so.1.2.20
```

**Comment by swertz** [comment]
I suspect this is due to the cmake version being too old - maybe it's necessary to update the requirement in CMakeLists.txt?

In any case, I realize CentOS 7 is quite old and that expecting support for it can be much to ask... I have resorted to build paho.mqtt.c in a CentOS 8 container, which works fine.

**Comment by icraggs** [comment]
Well I don't know.  You could try a newer version of CMake on CentOS 7 to see if that is actually the problem.  You've got multiple versions of OpenSSL installed there - 0.9.8e, 1.0.2k and 1.1.1g so maybe it's confused?  I'm not an expert on CMake builds by any means, so I'm speculating here.
