### ISSUE TITLE
Port To Parallax Propeller P2

### ISSUE THREAD

**Issue by PythonLinks** [eclipse-paho/paho.mqtt.c#1119]
**Is your feature request related to a problem? Please describe.**
I want to connect to a P2 device using MQTT, but it does not run there (yet).

**Describe the solution you'd like**
An executable, I could easily install. 

**Describe alternatives you've considered**
 From the P2 use a serial line to talk to some device that does run MQTT.

**Additional context**
I use MQTT.  I like MQTT.  I taught classes in MQTT.  I spoke at conferences on MQTT.  I am almost tempted to port it, it is only 8,000 lines of C.    But I have other things that are more important to me.  Sigh.

**Comment by fpagliughi** [comment]
This library is for memory-managed operating systems like Linux, Windows, and Mac. It doesn't work with bare-metal microcontrollers. So this is not the proper library to even consider for a P2.

**Comment by icraggs** [comment]
Thanks @fpagliughi I was going to ask what type of hardware this was.  The embedded library is the suitable one, then https://github.com/eclipse/paho.mqtt.embedded-c/ which I haven't looked at in a while but I mean to get back to.

**Comment by PythonLinks** [comment]
I think we will be using this solution. 
https://github.com/martin-ger/esp_mqtt
The P2, does not yet run Tcp/IP, so they use the ESP32 chip, in a separate board.  And talk to it with a serial line.  So just run MQTT on that chip, and all is well.  
I am not sure if there is any relationship between that solution and your software.

**Comment by icraggs** [comment]
Ok great.  I'll close this.
