### ISSUE TITLE
shutdown mqtt server, connect lost,  After 20 minutes, maybe longer, start mqtt server , connect fail.

### ISSUE THREAD

**Issue by xiekai-aiai** [eclipse-paho/paho.mqtt.c#1121]
**Describe the bug**
shutdown mqtt server, connect lost,  After 20 minutes, maybe longer, start mqtt server , connect fail.

attachment “program.zip“ is my demo.
attachment "log.zip " is track log.
[program.zip](https://github.com/eclipse/paho.mqtt.c/files/6762304/program.zip)
[log.zip](https://github.com/eclipse/paho.mqtt.c/files/6762310/log.zip)

when i start my program, everything goes well。 but when i shut down mqtt server(mosquitto-2.0.9) for 20 minutes, it maybe longer. then restart mqtt server,   the connection always fails。

mqtt server(mosquitto-2.0.9) print log:
1625467028: New connection from 127.0.0.1:41276 on port 1883.
1625467028: Client <unknown> closed its connection.
1625467028: New connection from 127.0.0.1:41278 on port 1883.
1625467028: Client <unknown> closed its connection.
.....

**Comment by icraggs** [comment]
I tried it, stopped the broker for > 30 mins and your program worked for me.

**Comment by xiekai-aiai** [comment]
> I tried it, stopped the broker for > 30 mins and your program worked for me.

thank you for your reply.   But I encountered this problem, the log can reflect this.  when i start mqtt server, the last side of the log still shows the connection failure

**Comment by icraggs** [comment]
What happens if you stop the server and restart it quickly?

**Comment by icraggs** [comment]
Closing in the absence of more information.  I also note that you are using version 1.3.0 of library - the latest version is 1.3.9.
