### ISSUE TITLE
MQTTAsync_connect() returns MQTTASYNC_SUCCESS even if the broker address is a fake one

### ISSUE THREAD

**Issue by KuanL1u** [eclipse-paho/paho.mqtt.c#1122]
Hi paho MQTT developers,

It seems the `MQTTAsync_connect()` will return MQTTASYNC_SUCCESS even if the broker address is a fake one. Is this expected?

reproduction code:
````
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "MQTTAsync.h"
#define ADDRESS     "aFakeBroker.org:1883" // a fake broker address
#define CLIENTID    "ExampleClientPub"
#define TOPIC       "MQTT Examples"
#define PAYLOAD     "Hello World!"
#define QOS         1
#define TIMEOUT     10000L

int main(int argc, char* argv[])
{
        MQTTAsync client;
        MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
        MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
        MQTTAsync_token token;
        int rc;
        MQTTAsync_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);
        MQTTAsync_setCallbacks(client, NULL, connlost, NULL, NULL);
        conn_opts.keepAliveInterval = 20;
        conn_opts.cleansession = 1;
        conn_opts.onSuccess = onConnect;
        conn_opts.onFailure = onConnectFailure;
        conn_opts.context = client;

        rc = MQTTAsync_connect(client, &conn_opts);
        printf("Return code %d\n", rc);
        
        return 0;
}
````

**Comment by icraggs** [comment]
That's because in the async API, calling an operation only starts it.  The asynchronous result on completion is returned in the onSuccess or onFailure callback.

**Comment by KuanL1u** [comment]
> That's because in the async API, calling an operation only starts it. The asynchronous result on completion is returned in the onSuccess or onFailure callback.

Thank you very much for your reply! One quick followup question: is that okay to use MQTTAsync_isConnected() function to check the connect status instead of using  onSuccess or onFailure callback?

**Comment by icraggs** [comment]
You could do that but it wouldn't be very efficient, and you wouldn't get the error information passed back into the callback.

**Comment by icraggs** [comment]
I think this has been answered.
