### ISSUE TITLE
Program blocked when there are a large number of persistence files

### ISSUE THREAD

**Issue by stuqqq** [eclipse-paho/paho.mqtt.c#1126]
I have been running the program for nearly 20 minutes and it is still blocked.I think it's just too many persistent files, close to 30,000.Other than controlling the number of persistent files, is there a good solution to this problem？
[log2.txt](https://github.com/eclipse/paho.mqtt.c/files/6744998/log2.txt)

_Originally posted by @stuqqq in https://github.com/eclipse/paho.mqtt.c/issues/1116#issuecomment-871866389_

**Comment by icraggs** [comment]
It's not going to help to open another issue for the same problem - that just causes more work for me.   I'm going to copy this response into the original issue and close this one as a duplicate.

Controlling the persistence files is probably the best option.  How did you get 30,000?  I improved the startup time a few releases back, but the highest performance wasn't the aim for this library, and I'm unlikely to improve it more unless there is an actual bug.

From your trace, I see you are using Linux kernel 3.2, which is from 2012.  If you are using a low powered machine, Raspberry Pi style or similar, then the performance will be lower.
