### ISSUE TITLE
Build Eclipse Paho for Windows

### ISSUE THREAD

**Issue by Rasmita-Ardu** [eclipse-paho/paho.mqtt.c#1130]
I am trying to build paho.mqtt.c for windows platform. I am naive in cmake compilation. Kindly help me out.

Steps I followed :
1. Downloaded the source code from : [https://github.com/eclipse/paho.mqtt.c.git]
2. Extracted the contents and navigated to the paho.mqtt.c-master folder.
3. Ran the following cmd in cmd :: `cmake -G "MSYS Makefiles" -DPAHO_BUILD_SAMPLES=TRUE -DCMAKE_TOOLCHAIN_FILE=/cmake/toolchain.win64.cmake ~paho.mqtt.c-master`
4. After successful generation of build files , I ran :: `cmake --build . --config Release`
I received the following error :
![image](https://user-images.githubusercontent.com/34830728/126470718-0b1bc441-c98f-47a0-9376-d31a8f3a4747.png)
Can anyone guide me on this ?
Thanks !

**Comment by icraggs** [comment]
What version of Windows are you using?  I wouldn't use the toolchain file - that's for cross-compiling as far as I know.  You can see how the build is done for the CI tests in appveyor.yml, and the results of builds here: https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c/history

**Comment by jumoog** [comment]
not sure what you did but i tried and 
`C:\msys64\mingw64\x86_64-w64-mingw32\include\wincrypt.h`
has `CRYPT_STRING_NOCRLF`

**Comment by icraggs** [comment]
I note that the MS doc says that for this option "Windows Server 2003 and Windows XP:  This value is not supported."  Which is why I asked about the windows version.  I assume this has been answered.

**Comment by Rasmita-Ardu** [comment]
@icraggs 
I am using Windows 10.0.18363

**Comment by icraggs** [comment]
So I suggest you look at the AppVeyor builds (link above) and see what the difference is to your build.  It depends what compiler you're using for instance.  I always use Microsoft compilers for building on Windows.

If you are using MinGW (it would have been helpful to state that) then it may depend on the version of that compiler/build environment you have.
