### ISSUE TITLE
MQTTAsync_successData (MQTTAsync_failureData) in MQTTAsync_send onSuccess (onFailure) callback no longer contains pointer to published message

### ISSUE THREAD

**Issue by wnts** [eclipse-paho/paho.mqtt.c#1133]
**Describe the bug**
Previously, we used version `1.3.1` of the paho-c asynchronous MQTT library.
We had implemented our `onSuccess` and `onFailure` callbacks that are passed to `MQTTAsync_send` in the `MQTTAsync_responseOptions` parameter to log the original message payload passed to `MQTTAsync_send` in those callback functions.

Recently, we are looking to upgrade to version `1.3.9`, but we have found that the behavior in the `onSuccess` and `onFailure` callbacks has changed. The `MQTTAsync_successData response` passed into those callbacks no longer has the original published message available in `response->alt.pub.message.payload`, which is a `NULL` pointer instead

**To Reproduce**
1. Take https://github.com/eclipse/paho.mqtt.c/blob/v1.3.9/src/samples/MQTTAsync_publish.c and modify the `onSend` function to read as follows, so that it prints `response->alt.pub.message.payload`: 
```
void onSend(void* context, MQTTAsync_successData* response)
{
    MQTTAsync client = (MQTTAsync)context;
    MQTTAsync_disconnectOptions opts = MQTTAsync_disconnectOptions_initializer;
    int rc;

    printf("Message with token value %d delivery confirmed\n", response->token);
    if(response->alt.pub.message.payload == NULL)
    {
        printf("response->alt.pub.message.payload == NULL\n");
    }
    else
    {
        printf("payload: %s\n", (char*)response->alt.pub.message.payload);
    }
    opts.onSuccess = onDisconnect;
    opts.onFailure = onDisconnectFailure;
    opts.context = client;
    if ((rc = MQTTAsync_disconnect(client, &opts)) != MQTTASYNC_SUCCESS)
    {
        printf("Failed to start disconnect, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }
}
```
2. Compile and run, which shows the following output (when linked against version `1.3.9`):
```
Waiting for publication of Hello World!
on topic MQTT Examples for client with ClientID: ExampleClientPub
Successful connection
Message with token value 1 delivery confirmed
response->alt.pub.message.payload == NULL
Successful disconnection
```

Also see the corresponding run with trace output enabled: [paho_publish_callback_nullptr.log](https://github.com/eclipse/paho.mqtt.c/files/6900414/paho_publish_callback_nullptr.log)

**Expected behavior**
In the `onSuccess(void *context, MQTTAsync_successDATA* response)` and `onFailure(void *context, MQTTAsync_successDATA* response)` callbacks passed to `MQTTAsync_send`, `response->alt.pub.message.payload != NULL`, but instead contains a pointer to the original payload passed to `MQTTAsync_send`.

This expected behavior was the behavior seen in version `1.3.1`

**Environment**
 - OS: `CentOS7.1804`
 - Version `1.3.9`

**Comment by icraggs** [comment]
Thanks.  It appears this is true, and is likely a consequence of fixing other issues.   Are you expecting a pointer to the original memory area, or one to an allocated copy?

**Comment by maikebing** [comment]
I think this should be the original memory area to facilitate the freeing of memory.  If it is allocated memory.

**Comment by maikebing** [comment]
OnSendFailure should do the same

**Comment by stuqqq** [comment]
I had the same problem.

**Comment by icraggs** [comment]
The functionality in 1.3.1 was to return an allocated copy, so that's what I've done. You can free the payload memory after calling publish/send, you don't need to wait until the success/failure callbacks.
