### ISSUE TITLE
multiple "undefined reference to" errors while using the libary

### ISSUE THREAD

**Issue by BloodyHellcat** [eclipse-paho/paho.mqtt.c#1134]
**Describe the bug**
I've installed the MQTT Libary on my Compute Module 4 like the manual and wanted to use it, so I tried to test one of the example scripts provided.

Following the way to reproduce and my errors, but first some information about the HW:
Everything happens on the Compute Module 4, but developing is done over Netbeans on a windows machine which copies all files to the CM4 and then remotely starts everything.

**To Reproduce**
1. git clone, obviously.
2. cd in the directory
3. make
4. sudo make install
5. removed the git repo locally since everything is now installed in the /usr/local/bin, lib, include or share folders.
6. then I started the Netbeans project, selected the CM4 as a Remote project.
7. I've added the "MQTTAsync_subscribe" file provided in the sample folder
8. tried to compile the whole thing and then the following errors below been thrown out in the console

**Output console**
The XXX are just censors of personal information

Copying project files to /home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXXX at pi@XXX.XXX.XXX.XXX
Building project files list...
Checking directory structure...
Checking previously uploaded files...
Checking links...
Uploading changed files:
	Zipping 12 changed files...
	Uploading zip to pi@XXX.XXX.XXX.XXX...
	Unzipping changed files...
Checking exec permissions...
Uploading changed files finished successfully.

cd '/home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient'
/usr/bin/make -f Makefile CONF=Debug
"/usr/bin/make" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
make[1]: Entering directory '/home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXXXX/MQTTClient'
"/usr/bin/make"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-Linux/mqttclient
make[2]: Entering directory '/home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient'
mkdir -p build/Debug/GNU-Linux
rm -f "build/Debug/GNU-Linux/MQTTAsync_subscribe.o.d"
gcc    -c -g -MMD -MP -MF "build/Debug/GNU-Linux/MQTTAsync_subscribe.o.d" -o build/Debug/GNU-Linux/MQTTAsync_subscribe.o MQTTAsync_subscribe.c
mkdir -p dist/Debug/GNU-Linux
gcc     -o dist/Debug/GNU-Linux/mqttclient build/Debug/GNU-Linux/MQTTAsync_subscribe.o 
/usr/bin/ld: build/Debug/GNU-Linux/MQTTAsync_subscribe.o: in function `connlost':
/home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient/MQTTAsync_subscribe.c:56: undefined reference to `MQTTAsync_connect'
/usr/bin/ld: build/Debug/GNU-Linux/MQTTAsync_subscribe.o: in function `msgarrvd':
/home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient/MQTTAsync_subscribe.c:69: undefined reference to `MQTTAsync_freeMessage'
/usr/bin/ld: /home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient/MQTTAsync_subscribe.c:70: undefined reference to `MQTTAsync_free'
/usr/bin/ld: build/Debug/GNU-Linux/MQTTAsync_subscribe.o: in function `onConnect':
/home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient/MQTTAsync_subscribe.c:119: undefined reference to `MQTTAsync_subscribe'
/usr/bin/ld: build/Debug/GNU-Linux/MQTTAsync_subscribe.o: in function `main':
/home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient/MQTTAsync_subscribe.c:135: undefined reference to `MQTTAsync_create'
/usr/bin/ld: /home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient/MQTTAsync_subscribe.c:143: undefined reference to `MQTTAsync_setCallbacks'
/usr/bin/ld: /home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient/MQTTAsync_subscribe.c:155: undefined reference to `MQTTAsync_connect'
/usr/bin/ld: /home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient/MQTTAsync_subscribe.c:179: undefined reference to `MQTTAsync_disconnect'
/usr/bin/ld: /home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient/MQTTAsync_subscribe.c:195: undefined reference to `MQTTAsync_destroy'
collect2: error: ld returned 1 exit status
make[2]: *** [nbproject/Makefile-Debug.mk:63: dist/Debug/GNU-Linux/mqttclient] Error 1
make[2]: Leaving directory '/home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient'
make[1]: *** [nbproject/Makefile-Debug.mk:59: .build-conf] Error 2
make[1]: Leaving directory '/home/pi/.netbeans/remote/XXX.XXX.XXX.XXX/XXX/MQTTClient'
make: *** [nbproject/Makefile-impl.mk:40: .build-impl] Error 2

BUILD FAILED (exit value 2, total time: 671ms)

Does someone know what I'm missing out or doing wrong?

Thanks in advance for any help

**Comment by icraggs** [comment]
I don't know anything about NetBeans.  But I don't see any mention of the Paho shared library in those commands.

**Comment by BloodyHellcat** [comment]
I don't think that Netbeans is the problem, since the compilation is done on the CM4, not in Netbeans.

The photo library has been installed in the /usr/local/bin/directory.

And I tested it with if the library would be missing. Then the IDE has thrown the error that the included file is missing. So I guess the library is included.

But as you say, why is there no reference to the paho library and why are those functions not found?

What am I missing out?

Especially since this is the sample code and I haven't changed anything.

**Comment by icraggs** [comment]
As the linking is the problem not the compiling, it's nothing to do with the code, it's the build.  As you succeeded building locally you could compare the two.  When I build for the Pi, I always do it locally, not remotely.

I see you building the library for the host (local) platform, but not for the remote.  Unless they are exactly the same, which I doubt, otherwise why do it remotely, you'll need to build the library for the Pi too.

**Comment by BloodyHellcat** [comment]
I'm not 100% sure if I get everything right, but if the linking is the problem, why does it recognise all files?

Till now I have just compiled it on the Remote (Pi) not locally, so I haven't successfully built it locally.

I've just tried it with the installation of Cygwin in Windows.
And I changed the library path from the installation on the Pi to locally in the same folder as the main .c file, so I can test it with the same circumstances on my local machine and the remote.

Sadly the I get the same error.

Following the console from local compilation in Netbeans with Cygwin support:

cd 'C:\LocalNetBeansRemotes\MQTTClient'
C:\cygwin64\bin\make.exe -f Makefile CONF=Debug_Local clean
"/usr/bin/make" -f nbproject/Makefile-Debug_Local.mk QMAKE= SUBPROJECTS= .clean-conf
make[1]: Entering directory '/cygdrive/c/LocalNetBeansRemotes/MQTTClient'
rm -f -r build/Debug_Local
make[1]: Leaving directory '/cygdrive/c/LocalNetBeansRemotes/MQTTClient'

CLEAN SUCCESSFUL (total time: 582ms)
cd 'C:\LocalNetBeansRemotes\MQTTClient'
C:\cygwin64\bin\make.exe -f Makefile CONF=Debug_Local
"/usr/bin/make" -f nbproject/Makefile-Debug_Local.mk QMAKE= SUBPROJECTS= .build-conf
make[1]: Entering directory '/cygdrive/c/LocalNetBeansRemotes/MQTTClient'
"/usr/bin/make"  -f nbproject/Makefile-Debug_Local.mk dist/Debug_Local/Cygwin-Windows/mqttclient.exe
make[2]: Entering directory '/cygdrive/c/LocalNetBeansRemotes/MQTTClient'
mkdir -p build/Debug_Local/Cygwin-Windows
rm -f "build/Debug_Local/Cygwin-Windows/MQTTAsync_subscribe.o.d"
gcc    -c -g -MMD -MP -MF "build/Debug_Local/Cygwin-Windows/MQTTAsync_subscribe.o.d" -o build/Debug_Local/Cygwin-Windows/MQTTAsync_subscribe.o MQTTAsync_subscribe.c
mkdir -p dist/Debug_Local/Cygwin-Windows
gcc     -o dist/Debug_Local/Cygwin-Windows/mqttclient build/Debug_Local/Cygwin-Windows/MQTTAsync_subscribe.o 
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: build/Debug_Local/Cygwin-Windows/MQTTAsync_subscribe.o: in function `connlost':
/cygdrive/c/LocalNetBeansRemotes/MQTTClient/MQTTAsync_subscribe.c:56: undefined reference to `MQTTAsync_connect'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: build/Debug_Local/Cygwin-Windows/MQTTAsync_subscribe.o: in function `msgarrvd':
/cygdrive/c/LocalNetBeansRemotes/MQTTClient/MQTTAsync_subscribe.c:69: undefined reference to `MQTTAsync_freeMessage'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: /cygdrive/c/LocalNetBeansRemotes/MQTTClient/MQTTAsync_subscribe.c:70: undefined reference to `MQTTAsync_free'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: build/Debug_Local/Cygwin-Windows/MQTTAsync_subscribe.o: in function `onConnect':
/cygdrive/c/LocalNetBeansRemotes/MQTTClient/MQTTAsync_subscribe.c:119: undefined reference to `MQTTAsync_subscribe'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: build/Debug_Local/Cygwin-Windows/MQTTAsync_subscribe.o: in function `main':
/cygdrive/c/LocalNetBeansRemotes/MQTTClient/MQTTAsync_subscribe.c:135: undefined reference to `MQTTAsync_create'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: /cygdrive/c/LocalNetBeansRemotes/MQTTClient/MQTTAsync_subscribe.c:143: undefined reference to `MQTTAsync_setCallbacks'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: /cygdrive/c/LocalNetBeansRemotes/MQTTClient/MQTTAsync_subscribe.c:155: undefined reference to `MQTTAsync_connect'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: /cygdrive/c/LocalNetBeansRemotes/MQTTClient/MQTTAsync_subscribe.c:179: undefined reference to `MQTTAsync_disconnect'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: /cygdrive/c/LocalNetBeansRemotes/MQTTClient/MQTTAsync_subscribe.c:195: undefined reference to `MQTTAsync_destroy'
collect2: error: ld returned 1 exit status
make[2]: *** [nbproject/Makefile-Debug_Local.mk:63: dist/Debug_Local/Cygwin-Windows/mqttclient.exe] Error 1
make[2]: Leaving directory '/cygdrive/c/LocalNetBeansRemotes/MQTTClient'
make[1]: *** [nbproject/Makefile-Debug_Local.mk:59: .build-conf] Error 2
make[1]: Leaving directory '/cygdrive/c/LocalNetBeansRemotes/MQTTClient'
make: *** [nbproject/Makefile-impl.mk:40: .build-impl] Error 2

BUILD FAILED (exit value 2, total time: 1s)

Thank you very much for your fast replies.

**Comment by BloodyHellcat** [comment]
I somehow can compile it if I add "-lpaho-mqtt3as" at the end of the gcc command:
gcc MQTTAsync_subscribe.c -lpaho-mqtt3as

Don't ask me why, but I can compile it.

Gota go test now if it really works.

**Comment by icraggs** [comment]
That's the option to link to the library, so it's no suprise that wil fix the link errors.

**Comment by BloodyHellcat** [comment]
Well, I didn't know that :x

I just knew of the linking options in NetBeans....but they didn't solve the problem.

Well, lesson learned.
