### ISSUE TITLE
Connect onSuccess is no longer called while using automaticReconnect if the first connect attempt was a failure

### ISSUE THREAD

**Issue by ashish-250** [eclipse-paho/paho.mqtt.c#1135]
Hi 
We have noticed that as the fix for #972, you have added the following commit: [link](https://github.com/eclipse/paho.mqtt.c/commit/9e4d95b86df0d3b86ffc8092f32b7d666cd19bca), the library is now nulling out the callback function pointers after first connect request-resposne cycle. 
With this change, if the someone is using the automaticReconnect while calling MQTTAsync_connect and end with with a failure during the first attempt, paho calls onFailure once and gets rid of the function pointers although it still keeps on retrying to connect. As a result, even if any one of the next attempts is successful, the onSuccess callback function is never called and our client code never knows if we have a connection or not.
We are currently using 1.3.1 and tried to ugprade to 1.3.9 which led us to identify this issue. 

The reproduction steps are easy: 
1. Keep the server down
2. Call MQTTAsync_connect with options set for automaticReconnect and wait for failure of one attempt. 
3. Now bring the server up
4. You will notice that onFailure was called once after the very first attempt failure and once server came up, paho will get a connection but onSuccess was never called 

We are not sure if this change was intentional or if there is any other way to get  a notification of a successful connection. It is always better to get notified of every response including those of failed attempts from the connect attempt for logging purposes or any other custom logic someone wants to add in there code like number of failed responses before exiting the program.
We would like to see the earlier behavior back. Please provide your thoughts on this.

**Comment by icraggs** [comment]
That's correct.  onSuccess or onFailure should only be called once for each command (and not both).  The connected() callback will be called on every re-connection.

**Comment by ashish-250** [comment]
How do we configure the function pointer for the connected callback? I can only see two function pointer configurations in MQTTAsync_connectOptions: onSuccess and onFailure.

Our configurations are as follows, can u tell me how do we get a callback on successful connection?
1. Here is how we are configuring the connect options(with automaticReconnect) before passing it to MQTTAsync_connect: 

> 	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	conn_opts.automaticReconnect = 1;               //    We are using automaticReconnect
	conn_opts.minRetryInterval = 1;
	conn_opts.maxRetryInterval = 5;
	conn_opts.cleansession = cleanSession;
	conn_opts.connectTimeout = 5;
	conn_opts.onSuccess = connectionSucceedCallback;
	conn_opts.onFailure = connectionFailedCallback;
	conn_opts.context = this;

If the server is down at the first attempt and connnectionFailedCallback is invoked once, now later server came up and connection got successful but connectionSucceedCallback is never invoked. 
Is there any additional that we need to set to get a connected callback?

**Comment by icraggs** [comment]
MQTTAsync_setConnected()

**Comment by ashish-250** [comment]
Thanks @icraggs. MQTTAsync_setConnected() works for us.

**Comment by icraggs** [comment]
Great
