### ISSUE TITLE
Publish the message using QOS2, and the connection is automatically disconnected after a period of time

### ISSUE THREAD

**Issue by wlysky** [eclipse-paho/paho.mqtt.c#1136]
[root@root:~]# ./MQTTClient_publish_async 2
-----------qos=2--------
---------upload total bytes=9604800-------upload rate = 26.321669 Mbps------------
---------upload total bytes=19209600-------upload rate = 34.704288 Mbps------------
---------upload total bytes=28814400-------upload rate = 39.509321 Mbps------------
---------upload total bytes=38419200-------upload rate = 42.415194 Mbps------------
---------upload total bytes=48024000-------upload rate = 44.382007 Mbps------------
---------upload total bytes=57628800-------upload rate = 45.732592 Mbps------------
---------upload total bytes=67233600-------upload rate = 46.763750 Mbps------------
---------upload total bytes=76838400-------upload rate = 47.604014 Mbps------------
---------upload total bytes=86443200-------upload rate = 48.280379 Mbps------------
---------upload total bytes=96048000-------upload rate = 48.819920 Mbps------------
---------upload total bytes=105652800-------upload rate = 49.263796 Mbps------------
---------upload total bytes=115257600-------upload rate = 49.669686 Mbps------------
---------upload total bytes=124862400-------upload rate = 50.009262 Mbps------------
---------upload total bytes=134467200-------upload rate = 50.545007 Mbps------------

Connection lost
     cause: (null)
Failed to publish message, return code -3-----Disconnected

**Comment by icraggs** [comment]
I'm afraid that's nowhere near enough information to say anything about what's going on.  Take a look at the issue template and answer some more of the sections in there.  

I would suggest looking at the server log to see if there is any explanation there.

**Comment by wlysky** [comment]
When I run "MQTTClient_publish_async.c" example, set "maxInflightMessages = 32 and qos = 2", the length of each published data is 100,000 bytes. The MQTTClient connectionLost callback is triggered after running for a while, MQTTClient_publishMessage return -3. and if i set "maxInflightMessages = 1 or qos = 1", this problem no longer occurs.

**Comment by icraggs** [comment]
Maybe there is a limit of maxinflightmessages on the server?  There could be something else the server doesn't like.  Some servers limit throughput, which the maxinflightmessages setting would increase as you increase it.  You need to look at the server diagnostics to get some idea.

**Comment by wlysky** [comment]
Okay, thanks. I'll check the log again

**Comment by icraggs** [comment]
I think this is covered in #1141 and #1140

**Comment by wlysky** [comment]
If I slow down the release rate and this problem doesn't happen any more, can you give me some advice on how to fix it without slowing down the rate?
