### ISSUE TITLE
MQTTProperties_free with null pointer reference

### ISSUE THREAD

**Issue by wsxjbupt** [eclipse-paho/paho.mqtt.c#1137]
![image](https://user-images.githubusercontent.com/55175963/127736748-7a549e5b-1235-4971-b9b6-ad8228205c65.png)
When the broker process exits and there is a buffer message in the client messageQueue, a null pointer reference appears when the client handle resource is released.

**Comment by wsxjbupt** [comment]
I will be grateful for solving this problem.

**Comment by icraggs** [comment]
You'll need to provide more information to allow anyone to provide meaningful help.  See the issue template for suggestions.

**Comment by wsxjbupt** [comment]
> You'll need to provide more information to allow anyone to provide meaningful help. See the issue template for suggestions.


My scenario is to implement the client based on paho.mqtt.c, and mosquitt as the broker server.

When a large number of messages are sent, there will be cached messages in the client queue.

If the mosquitto process exits, it will trigger the MQTTClient_disconnect_internal function in the MQTTClient_publish5 function.

**Comment by wsxjbupt** [comment]
> You'll need to provide more information to allow anyone to provide meaningful help. See the issue template for suggestions.


Before calling MQTTClient_publish5, it is found that there may be wild pointer references by printing the properties.count value of each message.
![image](https://user-images.githubusercontent.com/55175963/128955924-f9fd793f-5263-4f3d-ace9-16cd175132e5.png)

Finally trigger coredump in the MQTTProperties_free function

The wrong count value may be the cause of the coredump trigger
![image](https://user-images.githubusercontent.com/55175963/128956154-f4a1b51d-c99f-4899-9039-b64a7b93c133.png)

**Comment by wsxjbupt** [comment]
> You'll need to provide more information to allow anyone to provide meaningful help. See the issue template for suggestions.

Client handle init with MQTTClient_create function.

**Comment by icraggs** [comment]
How about a client library trace, as suggested in the issue template?  What environment(s) are you using?  Are you using MQTT 5.0?   If so, are you using/expecting any properties on the publish message?   Do you have an example program to illustrate your scenario?

If you supply a trace, attach it as a file, don't paste the output - pasting a lot of information makes the issue hard to read.

**Comment by icraggs** [comment]
Closing as no response to questions.
