### ISSUE TITLE
Unable to connect more then 64 clients from my application

### ISSUE THREAD

**Issue by cvmohan68** [eclipse-paho/paho.mqtt.c#1138]
I am using latest version of PahoClient  library from MFC application. We are unable to create more then 64 clients from an application. Is there any limit enforced in Paho client library and is there any configuration to tune this parameter to connect more then 64 clients

**Comment by icraggs** [comment]
There is no limit of number of clients but different OSes apply different limits to the number of sockets available to the select API.  On Linux this limit is 1024 sockets.  From https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-select:

_Four macros are defined in the header file Winsock2.h for manipulating and checking the descriptor sets. The variable FD_SETSIZE determines the maximum number of descriptors in a set. (The default value of FD_SETSIZE is 64, which can be modified by defining FD_SETSIZE to another value before including Winsock2.h.) Internally, socket handles in an fd_set structure are not represented as bit flags as in Berkeley Unix. Their data representation is opaque. Use of these macros will maintain software portability between different socket environments._

**Comment by cvmohan68** [comment]
Thanks for your reply. Able to create more then 64 clients in a single process after assigning new value to FD_SETSIZE in Paho MQTT library.
