### ISSUE TITLE
Can we subscribe to a wildcard topic but unsubscribe a specific one from the wildcard?

### ISSUE THREAD

**Issue by KuanL1u** [eclipse-paho/paho.mqtt.c#1142]
**Describe the bug**
If I use MQTTAsync_subscribe() to subscribe to a wildcard topic and use MQTTAsync_unsubscribe() unsubscribe a specific one from the wildcard, I will still receive the messages from the unsubscribed topic.

**To Reproduce**
1. use MQTTAsync_subscribe() to subscribe to "myhouse/+/temperature"
2. use MQTTAsync_sendMessage() to send messages to "myhouse/livingroom/temperature" and "myhouse/bedroom/temperature"
3. verify that we received messages from "myhouse/livingroom/temperature" and "myhouse/bedroom/temperature"
4. use MQTTAsync_unsubscribe() to unscribe from "myhouse/bedroom/temperature"
5. use MQTTAsync_sendMessage() to send other messages to "myhouse/livingroom/temperature" and "myhouse/bedroom/temperature"
6. we can still receive messages from "myhouse/bedroom/temperature"

**Expected behavior**
Is the behavior above expected? Why does it behave like that?

**Comment by jumoog** [comment]
You can only unsubscribe from topics you subscribed before.

**Comment by KuanL1u** [comment]
> why you unsubscribe from `myhouse/bedroom/temperature` not `myhouse/+/temperature` ?

Thanks for your response!

It is just an example. I wonder if this use case is valid.

To be more specific, `myhouse/+/temperature` will contain all the temperature info of all rooms in `myhouse`. It may contain
```
myhouse/livingroom/temperature
myhouse/bedroom/temperature
myhouse/diningroom/temperature
myhouse/kitchen/temperature
...
```

In this case, I would like to receive all the temperature info in `myhouse/+/temperature` except `myhouse/bedroom/temperature`

**Comment by KuanL1u** [comment]
> You can only unsubscribe from topics you subscribed before.

Got it! Thanks for the answer.

**Comment by jumoog** [comment]
> 
> 
> > You can only unsubscribe from topics you subscribed before.
> 
> Got it! Thanks for the answer.

Or do you filter on the Client side.

**Comment by icraggs** [comment]
This has been answered - it's an MQTT question.  Thanks @jumoog !
