### ISSUE TITLE
Whether the mqtt Win32 library can be used on WinXP System ？

### ISSUE THREAD

**Issue by stuqqq** [eclipse-paho/paho.mqtt.c#1147]
Whether the mqtt Win32 library can be used on WinXP System ？
What should I do ？

**Comment by jumoog** [comment]
Yes but you have to compile it yourself.

**Comment by stuqqq** [comment]
I tried using cmake3.15.7 and mingw4.9.3-32 compile this project ; But when i using ming32-make to make this project , I encountered the flowing problem.

![1629092590855_BFDF5BF9-50C3-4bb5-BCEE-71F299891001](https://user-images.githubusercontent.com/28746880/129516671-13fd6867-0147-4ff1-84d6-5a5f023b0a06.png)
![1629092641551_ECDA26C8-0237-4bb9-B19A-164CDE103C0C](https://user-images.githubusercontent.com/28746880/129516680-bcd5608f-ee82-4c61-82b1-a46d6bd33584.png)
![1629092724465_89B912A0-A3A3-44b0-98D9-ABFD6F86774B](https://user-images.githubusercontent.com/28746880/129516689-396eaf71-209f-4f0b-b8e7-696d315a3334.png)

**Comment by jumoog** [comment]
looks like your `wincrypt.h` doesn't have `CRYPT_STRING_NOCRLF`

**Comment by icraggs** [comment]
The MS docs https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptbinarytostringa say that that option is not supported on Windows Server 2003 and Windows XP.  You could try just deleting that option and see if the rest of the build works.

That is, change the line to:

     if ( CryptBinaryToStringA( in, in_len, CRYPT_STRING_BASE64, out, &dw_out_len ) )
                ret = (b64_size_t)dw_out_len;

It's only going to affect WebSocket connections for one thing.  I'd be interested to know if the build works after that.

**Comment by icraggs** [comment]
I think this question has been answered.
