### ISSUE TITLE
Connection lost during message publish

### ISSUE THREAD

**Issue by robinbansal08** [eclipse-paho/paho.mqtt.c#1150]
I have client which publishes large messages(of payload of 200KBs with QOS:1) at every 20 seconds.
Everything works fine for few hours but after that suddenly the client goes into re-connection with connection_lost issue during message publish event. The error code is -11 (MQTTASYNC_OPERATION_INCOMPLETE). 

I am running these clients over low end embedded processors, so it requires around 400-700 ms to publish 200KBs of payload. The network is stable as all clients are connected over LAN via Ethernet cable.

Is there a timeout period for publishing and receiving the acknowledgement of the message for async mqtt client, after which the client goes into connection lost sequence ? I tested with QOS-0 also, in that also I am facing the similar issue.

Please find the attached trace output here.

[logMQTT_1.txt](https://github.com/eclipse/paho.mqtt.c/files/7066027/logMQTT_1.txt)
[logMQTT_2.txt](https://github.com/eclipse/paho.mqtt.c/files/7066028/logMQTT_2.txt)

**Comment by icraggs** [comment]
Hello.  I think this is the same problem as https://github.com/eclipse/paho.mqtt.c/pull/1131 is intended to fix.  I haven't tried the fix  out yet, but if you do, please let me know because that would be useful information.  Thanks.

**Comment by robinbansal08** [comment]
Thanks a lot for your reply. I have tested with #1131  intended fix, but still I am still facing the same error -11 (MQTTASYNC_OPERATION_INCOMPLETE).

**Comment by icraggs** [comment]
Well your trace certainly looks like the problem it's intended to fix.  If this were your problem then then having the messages incoming to your client at QoS 0 rather than QoS 1 should make it disappear (to try that out, you can subscribe at QoS 0).

**Comment by icraggs** [comment]
I've merged #1131 into the develop branch along with a couple of other changes.   I've added a test (test8 / test_no 6) which tests this scenario, which your trace shows is exactly this one.  If you still get a problem with these changes, then please provide a trace with them in place.  Thanks.
