### ISSUE TITLE
subscribe will fail if set cleansession = true

### ISSUE THREAD

**Issue by adgiczone** [eclipse-paho/paho.mqtt.c#1151]
**Describe the bug**
if cleansession set true and call MQTTClient_subscribe  in connect lost callback function, it will cause connect lost again 

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1.  connect with cleansession = 1 and subscribe more than five topics
2.  turn off wired connect, try to reconnect in connect lost callback func
3.  turn on wired connect, re subscribe topics after reconnect in connect lost callback func and it success. 
4.  subscribe another topic, it will subscribe fail and throw -1, then mqtt connect lost again.
5.  topic resubscribed in callback func can't receive message. 
6. all of this steps use synchronous client application

**Expected behavior**
resubscribe success and won't  connect lost

**Log files**
Please try to attach log files rather than pasting the log contents. It makes the issues easier to read.
[log.log](https://github.com/eclipse/paho.mqtt.c/files/7097575/log.log)
reconnect success and subscribe first occurred in line 9014 and then subscribe throw -1 and connect lost at line 9702. It seems to be because Thread_wait_sem returns 11 
** Environment (please complete the following information):**
 - OS: Ubuntu18.04
 - Version 3.9.0

I look forward to hearing from you

**Comment by icraggs** [comment]
You can't call MQTTClient_subscribe in the connectionLost callback, only MQTTClient_connect().  If you want to make other calls in callbacks you'd have to use the MQTTAsync API.

**Comment by adgiczone** [comment]
Thank you. Now I use MQTTClient Api in a multi-threaded application, and I use MQTTClient_setcallback func to receive msg and check lost. Did I need to change all  MQTTClient to MQTTAsync. Or if I'm not using other calls in the callback function, there's no necessary to change to MqttAsyn.
I look forward to hearing from you

**Comment by icraggs** [comment]
If you aren't using any MQTTClient calls in any callback apart from MQTTClient_connect in the connectionLost callback, then that is fine.

**Comment by icraggs** [comment]
Question answered.
