### ISSUE TITLE
MQTTClient_connect does not finish

### ISSUE THREAD

**Issue by samg0ku** [eclipse-paho/paho.mqtt.c#1161]
**Describe the bug**
When i shutdown the server and try to connect to it the function call to MQTTClient_connect does not return, causing my system to get stuck.
Once I enable the trace logs to the maximum level the function return a not success state but does not get stuck anymore.

**Environment (please complete the following information):** 
 - OS: Linux
 - Version 1.3.9
 
The trace logs when the function is able to return are attached
[logs.txt](https://github.com/eclipse/paho.mqtt.c/files/7364550/logs.txt)

**Comment by icraggs** [comment]
Please don't paste the logs into the issues, it makes them hard to read.  Attach them as files.  The issue template requests this.

Also, what version of the library are you using, and what platform?  You cut that information out of the trace you pasted.

**Comment by samg0ku** [comment]
sorry, edited the text to remove the logs and attached it as a file.

I am using version 1.3.9 on an embedded Linux system linux-armv4

**Comment by icraggs** [comment]
It's a bit difficult to tell without a trace.

You could try the samples paho_cs_sub/paho_cs_pub to see if they behave the same way as your application.

You could try strace to get system call output to see if that shows up any differences.

**Comment by icraggs** [comment]
No more information forthcoming.
