### ISSUE TITLE
Possible data race detected using helgrind with a provided sample - MQTTAsync_publish

### ISSUE THREAD

**Issue by BinduRao2018** [eclipse-paho/paho.mqtt.c#1169]
**Describe the bug**
Possible data race detected. Based on the documentation - https://www.eclipse.org/paho/files/mqttdoc/MQTTAsync/html/async.html, MQTTAsync APIs are thread-safe. However, I see a Possible data race using helgrind.

**To Reproduce**
- Build the sample MQTTAsync_publish provided in paho.mqtt.c repo
- Execute the example with helgrind 
   i.e using the command:
valgrind --tool=helgrind ./MQTTAsync_publish

**Expected behaviour**
No data race condition 

[**Log](url) files**
[helgrind_mqttasyc_pub.txt](https://github.com/eclipse/paho.mqtt.c/files/7462193/helgrind_mqttasyc_pub.txt)

** Environment (please complete the following information):**
 - OS:  - Ubuntu 20.04

**Comment by icraggs** [comment]
What version of the client library are you using?

**Comment by BinduRao2018** [comment]
using 1.3.9

**Comment by icraggs** [comment]
I used the drd tool rather than helgrind as it seems to have more reliable output for me.  I fixed the issues reported in the library.  The sample code still reports a minor potential issue with the "finished" flag which doesn't have any effect on the running of the sample.

**Comment by BinduRao2018** [comment]
Thanks for the update. When would v1.4.0 be available for use?

**Comment by BinduRao2018** [comment]
We notice a deadlock when trying to publish (MQTTAsync_sendMessage()) when processing messages from msgarrvd(). Is there any limitation? We use MQTT as a bridge where publishing is done from one thread while processing the msgarrvd from the callback.

**Comment by jumoog** [comment]
Maybe we should always run some long-term tests. Many companies use the software in their production environment. I could donate a virtual server. In case of a crash, I could also create an issue via the Github API. I always do long-term tests before a new release for production.

**Comment by icraggs** [comment]
Limitations in callbacks: don't wait, or cause any significant delay.  You can make some other API calls, but no blocking (such as waitForCompletion or anything like that).

If you have thousands of messages in flight, MQTT has a limit of 64k.  Probably not this, and I think it should be handled, but could perhaps be an issue.
