### ISSUE TITLE
getaddrinfo occasionally returns -3 and it fails to reconnect if connection goes UP

### ISSUE THREAD

**Issue by raoufriahi** [eclipse-paho/paho.mqtt.c#1192]
The Socket_new function calls getaddrinfo which occasionally returns -3 means the IP address is invalid 
So the incorrect IP error code -3 is not managed in the **MQTTProtocol_connect** function (it only managed -1 and 0), which causes after the MQTT session management problem 

I propose this patch to solve this problem.
With this fix, socket_new returns 0 on success and -1 on failure and avoids returning -3

![socket_patch](https://user-images.githubusercontent.com/65498891/149787685-55ce4401-4ec0-4d50-a33e-0974ce6482ae.png)

**Comment by Pascal-Fremaux** [comment]
In fact, Paho should not use magical numbers but only use the defined constant values

**Comment by icraggs** [comment]
I wondered what the -3 return code was - I couldn't seem to find it in the doc for getaddrinfo.

**Comment by icraggs** [comment]
Ah maybe I'm confusing it with another issue.  Not sure.
