### ISSUE TITLE
"Socket error Network is unreachable in connect" on DNS64/NAT64 environment

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#12]
migrated from Bugzilla [#483646](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483646)
status UNCONFIRMED severity _normal_ in component _MQTT-C_ for _1.2_
Reported in version _1.1_ on platform _PC_
Assigned to: Ian Craggs

On 2015-12-04 05:02:45 -0500, Kazuma MISHIMAGI wrote:

> Actually we are facing this issue on Mac OS X, iOS and Android.
> 
> We are testing mqtt connectivity on local IPv6 Wi-Fi network using Internet Sharing feature of Mac OS X.
> 
> Then the program cause "Socket error Network is unreachable in connect".
> 
> 20151204 164838.603 (25825280)    (3)> Socket_new:601
> 20151204 164838.603 New socket 29 for xxx.xxx.com, port 8883
> 20151204 164838.603 (25825280)     (4)> Socket_addSocket:162
> 20151204 164838.603 Allocating 16 bytes in heap at file  ...
> 20151204 164839.472 Allocating 32 bytes in heap at file ...
> 20151204 164839.472 (25825280)      (5)> Socket_setnonblocking:72
> 20151204 164839.472 (25825280)      (5)< Socket_setnonblocking:77 (0)
> 20151204 164839.472 (25825280)     (4)< Socket_addSocket:175 (0)
> 20151204 164839.472 (25825280)     (4)> Socket_error:94
> 20151204 164839.472 Socket error Network is unreachable in connect for socket 29
> 20151204 164839.472 (25825280)     (4)< Socket_error:103 (51)
> 20151204 164839.472 (25825280)    (3)< Socket_new:688 (51)
> 
> I found that one of the problem is 
> uninitialized property of `struct sockaddr_in6`.
> 
> `sockaddr_in6` has more properties than `sockaddr_in`  
> and some properties (such as scope_id) seem to be uninitialized.
> Then the network will be unreachable.
> 
> In addition, this client tries only one `addrinfo` to connect 
> and prefers ipv4 is the problem too.
> If both ipv4 and ipv6 addresses are provided and v4-one is unreachable,
> v6-one seems to be never used and the client would just fail to connect.

**Comment by JuergenKosel** [comment]
Hello,

could you please check, if the proposed fix for bug 484496 also fixes this issue for the MAC?

Greetings
  Juergen

**Comment by icraggs** [comment]
I've fixed these issues in the develop branch.
