### ISSUE TITLE
Memory leak in Socket_new()

### ISSUE THREAD

**Issue by guilhermeferreira** [eclipse-paho/paho.mqtt.c#121]
There is a memory leak on Socket_new(). The leak happens due the lost of a reference to result pointer, returned from getaddrinfo(3). The freeaddrinfo(3) requires a pointer to the first result's element. However, this reference is lost when replaced by res.

There is a patch attached.
[Fix-memory-leak-on-Socket_new.patch.txt](https://github.com/eclipse/paho.mqtt.c/files/228259/Fix-memory-leak-on-Socket_new.patch.txt)

**Comment by icraggs** [comment]
Thanks very much.  I've merged the pull request.
