### ISSUE TITLE
MQTT- C Client not cleaning Open SSL Properly, causing crashes

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#13]
migrated from Bugzilla [#480363](https://bugs.eclipse.org/bugs/show_bug.cgi?id=480363)
status ASSIGNED severity _major_ in component _MQTT-C_ for _1.2_
Reported in version _1.2_ on platform _PC_
Assigned to: Ian Craggs

On 2015-10-21 20:38:14 -0400, Angelo Ribeiro wrote:

> I'm using: paho-mqtt3cs. 
> 
> We've identified that on SSLSocket.c we are not cleaning CRYPTO_set_locking_callback. 
> 
> So, if another client (Paho or other client that uses SSL), tries to use OpenSSL, it will crash. 
> 
> Basically, when Paho calls SSLSocket_terminate() we should add the code to reset the locking_callback. 
> 
> Suggested code: 
> void SSLSocket_terminate()
> {
>   FUNC_ENTRY;
>         CRYPTO_set_locking_callback(NULL);
>   free(sslLocks);
>         sslLocks = NULL; 
>   FUNC_EXIT;
> }
> 
> Let me know if you have problem reproducing this error. 
> 
> Thanks, 
> 
> Angelo Ribeiro.

On 2015-10-26 17:50:54 -0400, Eclipse Genie wrote:

> GitHub Pull Request 3 created by [aribeironovaes]
> https://github.com/eclipse/paho.mqtt.c/pull/3

On 2015-11-10 11:42:45 -0500, Ian Craggs wrote:

> Thanks.  I'll get this in asap.

**Comment by icraggs** [comment]
Fix added to develop branch.
