### ISSUE TITLE
name prefixes in global namespace?

### ISSUE THREAD

**Issue by sayegh** [eclipse-paho/paho.mqtt.c#132]
We have compiled paho.mqtt.c into a static library, and had a linker clash regarding (duplicate symbol)

ListElement\* ListFind(List\* aList, void\* content);

with another library, which is not uncommon given the general naming and the C function declaration. Same might be true for other global C functions. 
It might be useful to refactor utility functions to be named paho_\* or similar.

**Comment by icraggs** [comment]
In the provided build for the library on Linux and Windows, only the public functions are exposed, (see #define DLLExport in MQTTClient.h and MQTTAsync.h) which avoids name clashes.  

I will consider making the suggested naming changes, but not immediately, as we are in the middle of a release cycle.

**Comment by sayegh** [comment]
You're right, we had no issues when we used the dynamic libs, only with static linking.
Thanks for considering, and thanks for the lib which saved us quite some work. No need for immediate action, we're able to refactor of course.

**Comment by ralight** [comment]
It sounds to me like the bug here is around visibility of symbols in static builds of the library. It might be worth your while searching around that topic rather than refactoring the code.

There are some solutions here (that I've not tried):

http://stackoverflow.com/questions/2222162/how-to-apply-gcc-fvisibility-option-to-symbols-in-static-libraries

**Comment by sayegh** [comment]
Thanks for the pointer. Solution 1 proposes to extract all .o files from an archive and link with these (in our case an executable, not a shared object). So there'd be still a linker clash. I haven't tried the -Wl, thing, since it already says that it won't work on OSX. 

I think the Paho C client is a nice and lightweight lib to connect to MQTT brokers, so IMHO its code should be as robust as possible for different usage contexts. Unfortunately there's no easy solution for plain C code to a) omit piggypacking own utility implementations (like linked lists) and b) prevent symbol clashes. 

Just my 2 cents, and thanks for all your help!
