### ISSUE TITLE
SSL in protocol://host:port gives me no such name DNS in wireshark

### ISSUE THREAD

**Issue by sanket28** [eclipse-paho/paho.mqtt.c#133]
Hello,

I'm trying to use TLS with this library and it isn't working at all. Here's the code snippet:

```
    MQTTClient mqttClient;
    MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
    MQTTClient_SSLOptions sslOptions = MQTTClient_SSLOptions_initializer;
    sslOptions.trustStore = "/etc/ssl/certs/ca-certificates.crt";

    int rc, ch;

    MQTTClient_create(&mqttClient, "ssl://brokerAddress:8905", "test", MQTTCLIENT_PERSISTENCE_NONE, NULL);
    conn_opts.keepAliveInterval = 20;
    conn_opts.cleansession = 1;
    conn_opts.username = "username";
    conn_opts.password = "password";
    conn_opts.ssl = &sslOptions;

    MQTTClient_setCallbacks(mqttClient, NULL, NULL, msgarrvd, NULL);

    if ((rc = MQTTClient_connect(mqttClient, &conn_opts)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to connect, return code %d\n Error: %s\n", rc, strerror(errno));
        exit(-1);
    }
```

I am running this on an Ubuntu machine. I have used your Java client and it works fine with TLS. In wireshark I see DNS packets with "no such name". Could anyone please tell me what I'm missing here?

Thanks!

**Comment by icraggs** [comment]
This answer indicates that the "no such name" in your DNS packet is nothing to do with your program not working:

https://ask.wireshark.org/questions/43998/debug-dns-failure-no-such-namemalformed-packet

If you can get a trace of your connect attempt, by setting the environment variable

MQTT_C_CLIENT_TRACE=<ON or filename>

then that might shed more light on it.

**Comment by icraggs** [comment]
I'm going to close this issue for now.  Please reopen and attach a trace if you think there is still a problem.
