### ISSUE TITLE
Socket leak in Socket_new()?

### ISSUE THREAD

**Issue by obiltschnig** [eclipse-paho/paho.mqtt.c#135]
In an application we're implementing automatic reconnect if the connection to the broker fails (e.g., the mobile network may not yet be available when the application starts). If MQTTClient_connect() fails, we're trying to call it again after some time. However, there seems to be a leaked socket if the connect() call in Socket_new() fails, as it does in our case. 

Looking at the implementation of Socket_new():
1. a new socket is created with a call to socket()
2. some socket options are set
3. the socket is added to the internal list with Socket_addSocket()
4. connect() is called

Now if connect() fails, the unconnected socket stays in the internal list.
Shouldn't it be removed from that list with a call to Socket_close() in case connect() fails?
Or are we supposed to call MQTTClient_disconnect() (or any other method) in case MQTTClient_connect() fails?

**Comment by icraggs** [comment]
Thanks.  I'll look into this in the next week or so.

**Comment by icraggs** [comment]
I've merged a fix to this.  Thanks to all.
