### ISSUE TITLE
Probably shouldn't free openssl global resources

### ISSUE THREAD

**Issue by ralight** [eclipse-paho/paho.mqtt.c#136]
ERR_free_strings() as used around SSLSocket.c#L450 frees global resources that might be used in a different part of the application. Just because we loaded the strings doesn't mean we own them. I've had complaints before about libmosquitto doing this.

https://github.com/eclipse/paho.mqtt.c/blob/develop/src/SSLSocket.c#L450

**Comment by icraggs** [comment]
I'm happy to remove it.  Probably needs a comment to show it is a deliberate decision, before someone else opens an issue to free them :-)

**Comment by ralight** [comment]
It's a tricky one, someone else will complain about it not being valgrind clean...

It's also not as critical as it could be - this doesn't deinitialise the openssl library which is what libmosquitto was doing.

I'll leave it to you to decide what the best action is, but thought you should know about it.

**Comment by tucic** [comment]
Is it better to have separate functions for initialization and
deinitialization, than relying on number of clients currently running?

Best regards,
Milan

**Comment by loigu** [comment]
Well, it's not only about the errors but about any openssl resources - if someone (like me) is using openssl in different parts of application then not being able to control who and now initializes/deinitializes openssl can wreak havoc.
I had to patch paho mqtt to be able to use it and made pull request for it, see:
https://github.com/eclipse/paho.mqtt.c/pull/189

I think this way it is backward compatible :)

**Comment by icraggs** [comment]
Will be in 1.2 - the option to initialize/cleanup OpenSSL by the application.
