### ISSUE TITLE
Should 64 bit libs be able to link with 32 bit applications, and vice versa?

### ISSUE THREAD

**Issue by icraggs** [eclipse-paho/paho.mqtt.c#138]
Reference:

https://github.com/eclipse/paho.mqtt.c/pull/130

I'm not sure whether this is important, or not.

**Comment by ralight** [comment]
Is it even possible to do this?

**Comment by JuergenKosel** [comment]
Hello,
this is not possible!
You need to link 32 bit application against 32 bit libraries and objects and 64 bit application against 64 bit libraries.
This is also the reason why drivers for Windows and kernel modules for Linux must match the bit width of the operating system core.

Therefore the library needs to be build in the desired bit width format.

**Comment by icraggs** [comment]
So then I don't understand the proposal in #130 .  I thought that was the purpose of it.

**Comment by icraggs** [comment]
Ok, seems like we're all agreed.  I'll close this issue.
