### ISSUE TITLE
ListFreeNoContent Error on Raspberry pi 3.

### ISSUE THREAD

**Issue by chaunm** [eclipse-paho/paho.mqtt.c#139]
I'm using Paho for my raspberry pi 3 client application. 
I'm using MQTTClient_subscribeMany to subscribe to 2 channels on the broker and I got error with the function ListFreeNoContent(topics); (line 1263 in MQTTClient.c) 

Further debugging showed that the error may be related to myfree() function in heap.c (mqtt src).

The same code working fine with ubuntu. Is there any difference between ubuntu and raspberry pi jessie?

**Comment by icraggs** [comment]
The client library should work the same way on both, but there are differences: notably you are probably running Ubuntu on an Intel architecture machine, while the Raspberry Pi is ARM.  A trace of the problem, taken by setting the environment variable:

export MQTT_C_CLIENT_TRACE=<ON or filename> 

might help me understand what is going on.

**Comment by chaunm** [comment]
[debug.txt](https://github.com/eclipse/paho.mqtt.c/files/294812/debug.txt)
Hello Ian,
Here is the error.
The first connection has been successfully subscribed, the error occurred with the second one. 

20160602 103036.871 (1995931648) (0)> MQTTClient_subscribe:1317
20160602 103036.871 Allocating 32 bytes in heap at file src/LinkedList.c line 56 ptr 0x466900

Somehow, raspberry pi couldn't allocate memory for new List.

Please see the file for more detail.

Hope you can understanding more.

**Comment by chaunm** [comment]
Finally I have solved the problem. The problem was relate to using strdup() to create a topic name. 
I have to used malloc and memcpy instead up strdup().

**Comment by icraggs** [comment]
Ok.  Thanks for letting me know.
