### ISSUE TITLE
Why is it requested to squash commits into a single or few commits?

### ISSUE THREAD

**Issue by JuergenKosel** [eclipse-paho/paho.mqtt.c#140]
Many git based projects, especially Linux kernel development, recommend to provide changes as a set of small commits ( see section "SEPARATE CHANGES" of https://www.kernel.org/pub/software/scm/git/docs/gitworkflows.html ).
This allows them to get useful results from git-bisect in case of regression-bugs.

In opposite to this project requests:
"8. If you have a lot of commits for the change, squash them into a single / few commits."
( see https://github.com/eclipse/paho.mqtt.c/blob/develop/CONTRIBUTING.md#30 )

What is the reason for this requirement?

**Comment by icraggs** [comment]
I think that particular suggestion was written by @ralight - I'll check with him.

**Comment by ralight** [comment]
Not guilty :) That was @jpwsutton. I imagine this is a not very clearly worded request to reduce unnecessary commit clutter like can be seen in https://github.com/eclipse/paho.mqtt.python/pull/63/commits rather than wanting to produce huge single commits.

**Comment by jpwsutton** [comment]
Hi, that's right, I'll try and re-word it to make it a bit clearer, the goal is to make sure that the repository history is easier to read and as @ralight said, to avoid clutter. Obviously it's a bit of a balancing act though, so I don't think we'd expect every PR to be squashed to 1 commit.

**Comment by icraggs** [comment]
James, do you have a wording you are happy with now?

**Comment by jpwsutton** [comment]
How about this:

"If you have many commits for the change that you have made, squash the commits into logical units of work. A logical unit of work could be a consistent set of patches that would be reviewed together. This will help reduce unnecessary noise in the repository history and make it easier to find changes."

I took a little bit of inspiration from Docker's guidelines here: https://github.com/docker/docker/blob/master/CONTRIBUTING.md

**Comment by icraggs** [comment]
That sounds good to me.  I should follow this advice myself too.
