### ISSUE TITLE
Adding the ability to pass custom malloc()/free() functions to Heap.h

### ISSUE THREAD

**Issue by hhellyer** [eclipse-paho/paho.mqtt.c#142]
Our project has been using a modified version of Paho to allow us to pass in our own memory allocation functions so we can track memory usage. We would like to merge this functionality back, firstly because it seems like a useful general feature to have when embedding Paho that other projects might want to use and secondly because we have now open sourced our project on Git Hub and merging would allow us to use Paho directly as a git submodule rather than having to sync up our own fork.

Currently our implementation just passes in pointers to suitable allocation functions via an extra exported call in Heap.h and those are used in place of the default malloc/free functions. The (possibly unavoidable) limitation of this method is that the allocation functions can only be set before any other Paho functions are called to avoid freeing a block with a function that doesn’t match the one that allocated it originally.

I’ve put our implementation on a branch on my fork of Paho here:

https://github.com/hhellyer/paho.mqtt.c/tree/custom_allocator

but it’s really just an example, I’d like to make it more suitable for general consumption based on any feedback I can get and the raise a pull request. (I can easily make changes to our code if the interface changes - it’s the functionality I’m hoping to merge not our particular implementation.)

**Comment by JuergenKosel** [comment]
Hello,

if you use glibc, there are already hooks to trace memory allocation, see:
http://www.gnu.org/savannah-checkouts/gnu/libc/manual/html_node/Allocation-Debugging.html
The usage of mtrace() is much faster, than the usage of valgind.
But valgrind gives you additional information on not initialized memory usage and sometimes for stack issues.

**Comment by hhellyer** [comment]
In our specific case we weren't just interested in tracing memory allocation for debug - we wanted to be able to track it in production builds across Linux, Windows, AIX etc. We were embedding Paho inside a JVMTI agent and wanted to use the standard JVMTI memory allocation routine as we could see how much memory JVMTI had allocated in any diagnostics. I don't want to focus too much on that in this discussion since it's just one data point. There's some better discussions around why you might want to use standard allocators here:

http://stackoverflow.com/questions/826569/compelling-examples-of-custom-c-allocators

That discussion is about C++ allocators since custom allocators are a feature of C++ but I think the general arguments still apply. For someone embedding Paho using the same memory allocation as the rest of their application may be quite useful. (Also since someone might want to use Paho from C++ they might want to be able to pass a allocation functions that use the same mechanisms as any custom allocators they were using.)

**Comment by icraggs** [comment]
It will take me a week or two to look at this as I'm dealing with the Paho 1.2 release at the moment, and just about to go on vacation.

**Comment by icraggs** [comment]
If you still would like to add this, I suggest creating a PR.
