### ISSUE TITLE
SSL flag in command is not set properly if using `serverURI` in client

### ISSUE THREAD

**Issue by prateekbansal** [eclipse-paho/paho.mqtt.c#144]
If we are not passing in multiple `serverURIs`, but just passing a single `serverURI` using `client`, the ssl option on client is not set and so ssl seems to be broken.

Specifically, the processing on the serverURI at line src/MQTTAsync.c:1005-1013 should happen outside of `if` check:

```
if (command->command.details.conn.serverURIcount > 0) { ...
```

**Comment by rpendleton** [comment]
Correct me if I'm wrong, but it looks like it's still being set if you use `MQTTAsync_create`. Look at lines 450-456 of master:

``` c
#if defined(OPENSSL)
    else if (strncmp(URI_SSL, serverURI, strlen(URI_SSL)) == 0)
    {
        serverURI += strlen(URI_SSL);
        m->ssl = 1;
    }
#endif
```

I have SSL working fine in one of my projects and I'm using a single server with `MQTTAsync_create`. There was one bug I encountered though, which was that the `CMakeLists.txt` file is missing the compiler flag that actually enables SSL. So everything would compile fine, but it would try resolving the hostname with `ssl://` in it. My pull request (#149) fixes that.

**Comment by prateekbansal** [comment]
@rpendleton the code seems to have changed since my last pull request (around a couple of weeks back) which had that issue. Possibly the issue got resolved because I don't see that code anymore.

**Comment by icraggs** [comment]
The SSL tests are working in both Travis and AppVeyor, so I think it's all good.  Closing.
