### ISSUE TITLE
Add pre-shared key (PSK) support

### ISSUE THREAD

**Issue by icraggs** [eclipse-paho/paho.mqtt.c#146]

**Comment by ralight** [comment]
You can run `grep -r TLS_PSK lib/*` on the mosquitto source to find how it's done there.

It's basically just defining a callback and configuring it with `SSL_CTX_set_psk_client_callback()`.

**Comment by icraggs** [comment]
Thanks Roger, I was thinking of asking :-)

**Comment by tenderitaf** [comment]
Hello, as a reference for the others 

You may want to integrate paho with a JSSE lib from google called conscrypt that implements PSK.

https://github.com/google/conscrypt

Usage example from their integration test suite ;

https://github.com/google/conscrypt/blob/f0e05d561147458e3a10b4806e24d0752dfd5d4b/openjdk-integ-tests/src/test/java/libcore/javax/net/ssl/SSLSocketTest.java

Regards

**Comment by icraggs** [comment]
Done in #573
