### ISSUE TITLE
VersionInfo.h file not built/found

### ISSUE THREAD

**Issue by ThomasMeschke** [eclipse-paho/paho.mqtt.c#151]
After git cloning the repo I used msbuild to build paho like described on the page, but it breaks telling me it cannot find "VersionInfo.h", which is indeed not in the src folder. 
I suggest it should be built from the VersionInfo.h.in file? 

[build_log.txt](https://github.com/eclipse/paho.mqtt.c/files/327701/build_log.txt)

**Comment by ThomasMeschke** [comment]
Okay, finally I got it to build. 
After installing and configuring Ant, it works. 
I just don't like the fact that neither the Readme nor the website says anything about the need of ant to be able to run msbuild, with ant doing nothing else than replacing string placeholder for version and timestamp...

**Comment by ralight** [comment]
VersionInfo.h should have been automatically created when you ran cmake, ant is not a requirement.

**Comment by D-r-P-3-p-p-3-r** [comment]
The "Building from source" section (https://eclipse.org/paho/clients/c/) does not mention anything about cmake or am I missing something?

**Comment by raaj5671** [comment]
How about in Windows Microsoft Visual Studio 2015?
