### ISSUE TITLE
Disconnect by broker due to too late send pingreq

### ISSUE THREAD

**Issue by JuergenKosel** [eclipse-paho/paho.mqtt.c#156]
Hello,

In my application the keepAliveInterval is set to 20, as in the tests.
Occasionally the broker drops the connection to my application on Windows 10. The log of the mosquitto broker indicate, that the connection is lost due to time out.

The pingreq are usually send after approx 25 seconds. But sometimes they are send after 33 seconds.
And in this cases the broker drops the connection.
(I have not seen such disconnects with Windows 7.)

Question: Is the setting of 20 seconds for keepAliveInterval below the recommended value, or is this a bug?

Greetings
  Juergen

**Comment by icraggs** [comment]
I think this is probably a bug.  Can you get a trace of the occurrence?

Normally I tend to use 60 seconds as a keepalive interval in applications unless some other behaviour is needed.  It's major effect is altering the time that the client takes to recognize a closed socket connection to the broker.

**Comment by JuergenKosel** [comment]
Hello,
as the attached log file indicates, the library believes, that it has send the last ping request 24 seconds before the connection is closed by the broker:
[pingpong.txt](https://github.com/eclipse/paho.mqtt.c/files/373518/pingpong.txt)

But in the wireshark trace I could see, that this ping request was send 29 seconds before the TCP FIN message.
So it seems, that the TCP naggle algorithm is part of this problem!

Greetings
  Juergen

**Comment by icraggs** [comment]
Some people set TCP_NODELAY on the socket for an MQTT connection, but I have thought this was unnecessary and possibly inefficient.  We could turn it on by default, or it could be a connect option.

**Comment by ralight** [comment]
For keepalive=20, sending a PINGREQ at 24 seconds after the last outgoing message seems a bit late to me anyway, never mind nagle.

**Comment by icraggs** [comment]
There's a loop which checks keepalive processing every 5 seconds, for all client objects.  That interval can be reduced.

**Comment by ralight** [comment]
Ah, that makes sense then. Perhaps it would be worth having a keepalive dependent interval if you don't want to make it too small by default. Maybe something like min(5, keepalive/10) would do.

**Comment by icraggs** [comment]
Yes I was thinking the same thing.  As it happens that loop will still start in-session retry processing too, which is a left over from 3.1 (or was it 3.0?), which was another reason for the interval not being less than 5 seconds.  I think a small amount of refactoring is in order.

**Comment by icraggs** [comment]
In 1.2
