### ISSUE TITLE
SSL Connection Failing

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#16]
migrated from Bugzilla [#479376](https://bugs.eclipse.org/bugs/show_bug.cgi?id=479376)
status UNCONFIRMED severity _major_ in component _MQTT-C_ for _1.2_
Reported in version _future_ on platform _PC_
Assigned to: Ian Craggs

On 2015-10-08 21:04:55 -0400, Angelo Ribeiro wrote:

> I am using MQTT-C (paho) library paho-mqtt3cs and SSL Connection was failing on method: MQTTProtocol_connect file: MQTTProtocolOut.c. 
> 
> If you take a look on line 105 It calls: SSLSocket_setSocketForSSL(&aClient->net, aClient->sslopts), but it tests if It is != 1 as if 1 would be an error. 
> 
> But if you take a look into the implementation of SSLSocket_setSocketForSSL (File SSLSocket.c) this method returns 1 in case of success. 
> 
> So, it was not sending CONNECT because of that.
> 
> If you change the code to:  
> SSLSocket_setSocketForSSL(&aClient->net, aClient->sslopts) == 1
> It will work corretly. 
> 
> Let me know if you want me to do a PULL request or if you have any questions. 
> 
> Thanks, 
> 
> Angelo Ribeiro.

**Comment by icraggs** [comment]
Thanks.  Added fix to develop branch.
