### ISSUE TITLE
NULL-pointer access in SSLSocket_setSocketForSSL()

### ISSUE THREAD

**Issue by JuergenKosel** [eclipse-paho/paho.mqtt.c#160]
Hello,

if the user has provided only sslopts.keyStore = "<some public key chain file>" and there is no
private key provided, a segmentation fault occurs in SSLSocket_setSocketForSSL():

```
if (net->ctx != NULL || (rc = SSLSocket_createContext(net, opts)) == 1)
{
    int i;
    SSL_CTX_set_info_callback(net->ctx, SSL_CTX_info_callback);
```

Because rc is 1 but net-ctx == NULL.
I Believe, that such bad certificate files should be reported to the user without a crash.

Greetings
  Juergen

**Comment by JuergenKosel** [comment]
Hello,

I have just seen, that this could be a duplicate of issue #155 . For me this has happened for Windows
but in #155, the crash occured on a Linux.

Greetings
  Juergen

**Comment by kguilbert** [comment]
I ran into this too, with an incorrect `sslopts.privateKeyPassword`. I commented on @JuergenKosel's PR by noting that perhaps in SSLSocket_createContext(), if the SSL_CTX_use_PrivateKey_file() call fails, the return code `rc` should be set so it bubbles up to the caller, which should then know not to use `net->ctx`.

**Comment by icraggs** [comment]
I've added a fix to the develop branch.  Thanks.

**Comment by penglsh** [comment]
Hello, JuergenKosel
I see the issue has been closed a loong time, but it still confuses me. The lastest code in the function `SSLSocket_createContext` will still return 1 though `net->ctx` is NULL. The segmentation fault will still occur in `SSLSocket_setSocketForSSL()` like you metioned above. What do you think about the above question?  I would appreciate hearing from you. Thanks.
