### ISSUE TITLE
osx tsl 1.2 support

### ISSUE THREAD

**Issue by yupengfei** [eclipse-paho/paho.mqtt.c#162]
Is the binary library of osx support tsl 1.2 or I have to compile myself?https://projects.eclipse.org/projects/technology.paho/downloads

**Comment by icraggs** [comment]
It depends on the version of OpenSSL installed on the system, which the library will make use of.  TLS 1.2 support has been in OpenSSL since version 1.0.1.

**Comment by ralight** [comment]
As an addendum, it's worth pointing out that the only versions of openssl that do not support TLS 1.2 are no longer supported.
