### ISSUE TITLE
Feature Request: Client-Id with more than 23 characters

### ISSUE THREAD

**Issue by JuergenKosel** [eclipse-paho/paho.mqtt.c#163]
Hello,
as stated in
http://www.hivemq.com/blog/supporting-mqtt-client-identifiers-23-characters
it is possible to use client ids with more than 23 characters.
I am note sure about the MQTT broker of IBM Bluemix cloud:
They require a client id which is generated from organization-id, device-type-id and device-id. So you may easily need to use a client-id, with more than 23 characters.

Therefore could could make sense to support larger client-ids in paho.mqtt.c

Greetings
  Juergen

**Comment by icraggs** [comment]
Hi.  The library does support client ids > 23 characters, but the documentation still has the comment about the 23 character limit.  I'll fix the doc.

**Comment by icraggs** [comment]
Doc updated
