### ISSUE TITLE
Test is incorrect when checking connection error

### ISSUE THREAD

**Issue by ela34** [eclipse-paho/paho.mqtt.c#164]
In 

> SSLSocket.c

 in function 

> int SSLSocket_connect(SSL\* ssl, int sock) 

I think this test:

> **if (error == SSL_ERROR_WANT_READ || error == SSL_ERROR_WANT_WRITE)**

should be:

> **if (!(error == SSL_ERROR_WANT_READ || error == SSL_ERROR_WANT_WRITE))**

**Comment by icraggs** [comment]
Hi.

I think the test is correct.  WANT_READ and WANT_WRITE indicate that the call did not complete, so we return INTERRUPTED, so that the operation is tried again.

**Comment by ela34** [comment]
I got this problem running sample code "MQTTAsync_publish.c" on windows using OpenSSL.
Without this change the connection was never made, now it works like a charm.
May be it's the contract of this function to return INTERRUPTED when it get WANT_READ or WANT_WRITE from the SSL layer, but it is not the way the caller interprets it (look at "MQTTProtocol_connect" which do not handle correctly this error code). WANT_READ or WANT_WRITE is not an error it just means that you have to call again read or write to let the SSL layer process its state machine.
I hope my explanation will be helpful.

**Comment by icraggs** [comment]
Hi, 

I think your explanation is the same as mine above.  
1. If the error code is WANT_READ or WANT_WRITE, SSLSocket_connect returns TCPSOCKET_INTERRUPTED (-22)
2. Oh I think I see the problem.  In MQTTProtocol_connect, connect_state should be set to 2, and TCPSOCKET_INTERRUPTED returned.

Lines 109/110 in MQTTProtocolOut.c should be 

if (rc == TCPSOCKET_INTERRUPTED)
    aClient->connect_state = 2; /\* SSL connect called - wait for completion */

instead of 

if (rc == -1)
    aClient->connect_state = 2; /\* SSL connect called - wait for completion _/_/

There are other cases of doing this check such as line 2718 in MQTTAsync.c:

if (rc == TCPSOCKET_INTERRUPTED)
{
    rc = MQTTCLIENT_SUCCESS; /\* the connect is still in progress */
    m->c->connect_state = 2;
}

**Comment by ela34** [comment]
Yes, this is the correct fix. Thanks for your help.

**Comment by davemcincork** [comment]
This change addresses the problem for me too. Connection over SSL not possible without it (on Linux builds of library - Windows builds not affected). I can't see a pull request to get this into master?

**Comment by icraggs** [comment]
Merged into the develop branch.

**Comment by MadhukarKandhula** [comment]
Hi,

I am new to mqtt,
I am getting below error, when I enabled SSL option,
=========================================================
19700101 053000.000 (3119138624)  (1)> Socket_outInitialize:131
19700101 053000.000 (3119138624)   (2)> SocketBuffer_initialize:94
19700101 053000.000 (3119138624)   (2)< SocketBuffer_initialize:98
19700101 053000.000 (3119138624)  (1)< Socket_outInitialize:144
19700101 053000.000 (3119138624)  (1)> SSLSocket_initialize:443
19700101 053000.000 (3119138624)   (2)> SSL_create_mutex:343
19700101 053000.000 (3119138624)   (2)< SSL_create_mutex:349 (0)
19700101 053000.000 (3119138624)   (2)> SSL_create_mutex:343
19700101 053000.000 (3119138624)   (2)< SSL_create_mutex:349 (0)
19700101 053000.000 (3119138624)   (2)> SSL_create_mutex:343
19700101 053000.000 (3119138624)   (2)< SSL_create_mutex:349 (0)
19700101 053000.000 (3119138624)   (2)> SSL_create_mutex:343
19700101 053000.000 (3119138624)   (2)< SSL_create_mutex:349 (0)
19700101 053000.000 (3119138624)   (2)> SSL_create_mutex:343
19700101 053000.000 (3119138624)   (2)< SSL_create_mutex:349 (0)
19700101 053000.000 (3119138624)   (2)> SSL_create_mutex:343
19700101 053000.000 (3119138624)   (2)< SSL_create_mutex:349 (0)
19700101 053000.000 (3119138624)   (2)> SSL_create_mutex:343
19700101 053000.000 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.941 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.941 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.942 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.942 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.942 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.942 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.942 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.942 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.942 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.942 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.942 (3119138624)   (2)> SSL_create_mutex:343
20190415 161551.942 (3119138624)   (2)< SSL_create_mutex:349 (0)
20190415 161551.942 (3119138624)  (1)< SSLSocket_initialize:487 (1)
20190415 161551.942 (3119138624)  (1)> MQTTStrncpy:851
20190415 161551.942 (3119138624)  (1)< MQTTStrncpy:861
20190415 161551.942 (3119138624)  (1)> MQTTStrncpy:851
20190415 161551.942 (3119138624)  (1)< MQTTStrncpy:861
20190415 161551.942 (3119138624)  (1)> MQTTPersistence_create:52
20190415 161551.942 (3119138624)  (1)< MQTTPersistence_create:98 (0)
20190415 161551.942 (3119138624)  (1)> MQTTPersistence_initialize:113
20190415 161551.942 (3119138624)  (1)< MQTTPersistence_initialize:121 (0)
20190415 161551.942 (3119138624)  (1)> MQTTAsync_restoreCommands:936
20190415 161551.942 0 commands restored for client myclient
20190415 161551.942 (3119138624)  (1)< MQTTAsync_restoreCommands:974 (0)
20190415 161551.942 (3119138624)  (1)> MQTTPersistence_restoreMessageQueue:714
20190415 161551.942 0 queued messages restored for client myclient
20190415 161551.942 (3119138624)  (1)< MQTTPersistence_restoreMessageQueue:753 (0)
20190415 161551.942 (3119138624) (0)< MQTTAsync_createWithOptions:593 (0)
20190415 161551.942 (3119138624) (0)> MQTTAsync_setConnected:2540
20190415 161551.942 (3119138624) (0)< MQTTAsync_setConnected:2552 (0)
20190415 161551.942 (3119138624) (0)> MQTTAsync_setCallbacks:2426
20190415 161551.942 (3119138624) (0)< MQTTAsync_setCallbacks:2440 (0)

Connecting...
20190415 161551.942 (3119138624) (0)> MQTTAsync_connect:2738
20190415 161551.942 (3119138624)  (1)> UTF8_validateString:157
20190415 161551.942 (3119138624)   (2)> UTF8_validate:131
20190415 161551.942 (3119138624)   (2)< UTF8_validate:143 (1)
20190415 161551.942 (3119138624)  (1)< UTF8_validateString:159 (1)
20190415 161551.942 (3119138624)  (1)> Thread_start:69
20190415 161551.942 (3119138624)  (1)< Thread_start:79
20190415 161551.942 (3119138624)  (1)> Thread_start:69
20190415 161551.942 (3119138624)  (1)< Thread_start:79
20190415 161551.942 (3119138624)  (1)> MQTTStrncpy:851
20190415 161551.943 (3119138624)  (1)< MQTTStrncpy:861
20190415 161551.943 (3119138624)  (1)> MQTTStrncpy:851
20190415 161551.943 (3119138624)  (1)< MQTTStrncpy:861
20190415 161551.943 (3119138624)  (1)> MQTTAsync_addCommand:984
20190415 161551.943 (3119138624)   (2)> Thread_signal_cond:395
20190415 161551.943 (3119138624)   (2)< Thread_signal_cond:400 (0)
20190415 161551.943 (3119138624)  (1)< MQTTAsync_addCommand:1018 (0)
20190415 161551.943 (3119138624) (0)< MQTTAsync_connect:3039 (0)
Waiting for the connection...
20190415 161551.943 (3092694784) (0)> MQTTAsync_sendThread:1784
20190415 161551.943 (3092694784)  (1)> MQTTAsync_processCommand:1324
20190415 161551.943 Connecting to serverURI myuri with MQTT version 4
20190415 161551.943 (3084302080) (0)> MQTTAsync_receiveThread:2064
20190415 161551.943 (3092694784)   (2)> MQTTProtocol_connect:114
20190415 161551.943 (3092694784)    (3)> MQTTProtocol_addressPort:58
20190415 161551.943 (3092694784)    (3)< MQTTProtocol_addressPort:90
20190415 161551.943 (3092694784)    (3)> Socket_new:668
20190415 161551.943 New socket 3 for uri, port number
20190415 161551.943 (3092694784)     (4)> Socket_addSocket:173
20190415 161551.943 (3092694784)      (5)> Socket_setnonblocking:85
20190415 161551.943 (3092694784)      (5)< Socket_setnonblocking:90 (0)
20190415 161552.073 (3092694784)     (4)< Socket_addSocket:196 (0)
20190415 161552.073 Connect pending
20190415 161552.073 (3092694784)    (3)< Socket_new:785 (115)
20190415 161552.073 (3092694784)   (2)< MQTTProtocol_connect:156 (115)
20190415 161552.073 (3092694784)   (2)> MQTTProperties_free:366
20190415 161552.073 (3092694784)   (2)< MQTTProperties_free:389
20190415 161552.073 (3092694784)  (1)< MQTTAsync_processCommand:1660 (1)
20190415 161552.073 (3092694784)  (1)> Thread_wait_cond:413
20190415 161552.073 (3084302080)  (1)> MQTTAsync_cycle:3662
20190415 161552.073 (3084302080)   (2)> Socket_getReadySocket:237
20190415 161552.073 (3084302080)    (3)> Socket_continueWrites:928
20190415 161552.073 (3084302080)    (3)< Socket_continueWrites:952 (0)
20190415 161552.073 (3084302080)    (3)> isReady:213
20190415 161552.073 (3084302080)    (3)< isReady:218 (1)
20190415 161552.073 (3084302080)   (2)< Socket_getReadySocket:309 (3)
20190415 161552.073 m->c->connect_state = 1
20190415 161552.073 (3084302080)   (2)> MQTTAsync_connecting:3513
20190415 161552.073 (3084302080)    (3)> MQTTProtocol_addressPort:58
20190415 161552.073 (3084302080)    (3)< MQTTProtocol_addressPort:90
20190415 161552.073 (3084302080)    (3)> SSLSocket_setSocketForSSL:647
20190415 161552.075 (3084302080)     (4)> SSLSocket_createContext:521
20190415 161552.075 (3084302080)     (4)< SSLSocket_createContext:637 (1)



20190415 161552.076 (3084302080)     (4)> MQTTStrncpy:851
20190415 161552.076 the src string is truncated
20190415 161552.076 (3084302080)     (4)< MQTTStrncpy:861
20190415 161552.076 (3084302080)    (3)< SSLSocket_setSocketForSSL:686 (1)
20190415 161552.076 (3084302080)    (3)> SSLSocket_connect:697
20190415 161552.076 SSL handshake started write:unknown:unknown
20190415 161552.076 SSL state connect:before/connect initialization:(NONE)
20190415 161552.076 sent 771 256 buflen 5
20190415 161552.076 sent 771 22 buflen 379
20190415 161552.076 SSL state connect:SSLv2/v3 write client hello A:(NONE)
20190415 161552.076 SSL connect:SSLv2/v3 read server hello A
20190415 161552.076 (3084302080)     (4)> SSLSocket_error:97
20190415 161552.076 SSLSocket error WANT_READ/WANT_WRITE
20190415 161552.076 (3084302080)     (4)< SSLSocket_error:117 (2)
20190415 161552.076 (3084302080)    (3)< SSLSocket_connect:754 (-22)
20190415 161552.076 (3084302080)   (2)< MQTTAsync_connecting:3652 (0)
20190415 161552.076 m->c->connect_state = 2
20190415 161552.076 CONNECT sent, *rc is 0
20190415 161552.076 (3084302080)   (2)> MQTTAsync_retry:3495
20190415 161552.076 (3084302080)    (3)> MQTTProtocol_keepalive:608
20190415 161552.076 (3084302080)    (3)< MQTTProtocol_keepalive:644
20190415 161552.077 (3084302080)    (3)> MQTTProtocol_retry:730
20190415 161552.077 (3084302080)    (3)< MQTTProtocol_retry:749
20190415 161552.077 (3084302080)   (2)< MQTTAsync_retry:3505
20190415 161552.077 (3084302080)  (1)< MQTTAsync_cycle:3818 (0)
20190415 161552.077 (3084302080)  (1)> MQTTAsync_cycle:3662
20190415 161552.077 (3084302080)   (2)> Socket_getReadySocket:237
20190415 161552.077 (3084302080)    (3)> Socket_continueWrites:928
20190415 161552.077 (3084302080)    (3)< Socket_continueWrites:952 (0)
20190415 161552.077 (3084302080)    (3)> isReady:213
20190415 161552.077 (3084302080)    (3)< isReady:218 (1)
20190415 161552.077 (3084302080)   (2)< Socket_getReadySocket:309 (3)
20190415 161552.077 m->c->connect_state = 2
20190415 161552.077 (3084302080)   (2)> MQTTAsync_connecting:3513
20190415 161552.077 (3084302080)    (3)> SSLSocket_connect:697
20190415 161552.077 (3084302080)     (4)> SSLSocket_error:97
20190415 161552.077 SSLSocket error (5) in SSL_connect for socket 3 rc 0 errno 0 Success

20190415 161552.077 (3084302080)     (4)< SSLSocket_error:117 (-3)
20190415 161552.077 (3084302080)    (3)< SSLSocket_connect:754 (-3)
20190415 161552.077 (3084302080)    (3)> nextOrClose:1667
20190415 161552.077 (3084302080)     (4)> MQTTAsync_checkConn:467
20190415 161552.561 (3084302080)     (4)< MQTTAsync_checkConn:470 (0)
20190415 161552.561 (3084302080)     (4)> MQTTAsync_closeSession:2587
20190415 161552.561 (3084302080)      (5)> MQTTAsync_closeOnly:2559
20190415 161552.561 (3084302080)       (6)> MQTTProtocol_checkPendingWrites:1138
20190415 161552.561 (3084302080)       (6)< MQTTProtocol_checkPendingWrites:1155
20190415 161552.561 (3084302080)       (6)> WebSocket_close:397
20190415 161552.561 (3084302080)       (6)< WebSocket_close:450
20190415 161552.561 (3084302080)       (6)> SSLSocket_close:871
20190415 161552.561 (3084302080)        (7)> SSLSocket_destroyContext:858
20190415 161552.561 (3084302080)        (7)< SSLSocket_destroyContext:862
20190415 161552.561 (3084302080)       (6)< SSLSocket_close:883 (-1)
20190415 161552.561 (3084302080)       (6)> Socket_close:613
20190415 161552.561 (3084302080)        (7)> Socket_close_only:587
20190415 161552.561 (3084302080)        (7)< Socket_close_only:601 (0)
20190415 161552.561 (3084302080)        (7)> Socket_abortWrite:895
20190415 161552.561 (3084302080)        (7)< Socket_abortWrite:913 (0)
20190415 161552.561 (3084302080)        (7)> SocketBuffer_cleanup:136
20190415 161552.561 (3084302080)        (7)< SocketBuffer_cleanup:148
20190415 161552.561 Removed socket 3
20190415 161552.561 (3084302080)       (6)< Socket_close:640
20190415 161552.561 (3084302080)      (5)< MQTTAsync_closeOnly:2581
20190415 161552.561 (3084302080)      (5)> MQTTAsync_cleanSession:2616
20190415 161552.561 (3084302080)       (6)> MQTTPersistence_clear:160
20190415 161552.561 (3084302080)       (6)< MQTTPersistence_clear:164 (0)
20190415 161552.561 (3084302080)       (6)> MQTTProtocol_emptyMessageList:812
20190415 161552.561 (3084302080)       (6)< MQTTProtocol_emptyMessageList:821
20190415 161552.561 (3084302080)       (6)> MQTTProtocol_emptyMessageList:812
20190415 161552.561 (3084302080)       (6)< MQTTProtocol_emptyMessageList:821
20190415 161552.561 (3084302080)       (6)> MQTTAsync_emptyMessageQueue:1820
20190415 161552.561 (3084302080)       (6)< MQTTAsync_emptyMessageQueue:1834
20190415 161552.561 (3084302080)       (6)> MQTTAsync_removeResponsesAndCommands:1844
20190415 161552.561 0 responses removed for client myclient
20190415 161552.561 0 commands removed for client myclient
20190415 161552.561 (3084302080)       (6)< MQTTAsync_removeResponsesAndCommands:1929
20190415 161552.561 (3084302080)      (5)< MQTTAsync_cleanSession:2632 (0)
20190415 161552.561 (3084302080)     (4)< MQTTAsync_closeSession:2594
20190415 161552.561 Calling connect failure for client emyclient87e
20190415 161552.561 (3084302080)    (3)< nextOrClose:1720
20190415 161552.561 (3084302080)   (2)< MQTTAsync_connecting:3652 (-3)
20190415 161552.561 m->c->connect_state = 0
20190415 161552.561 CONNECT sent, *rc is -3
20190415 161552.561 (3084302080)   (2)> MQTTAsync_retry:3495
20190415 161552.561 (3084302080)    (3)> MQTTProtocol_retry:730
20190415 161552.561 (3084302080)    (3)< MQTTProtocol_retry:749
20190415 161552.561 (3084302080)   (2)< MQTTAsync_retry:3505
20190415 161552.561 (3084302080)  (1)< MQTTAsync_cycle:3818 (-3)
20190415 161552.561 Could not find client corresponding to socket 3
20190415 161552.561 (3084302080)  (1)> MQTTAsync_cycle:3662
20190415 161552.561 (3084302080)   (2)> Socket_getReadySocket:237
20190415 161552.561 (3084302080)   (2)< Socket_getReadySocket:309 (0)
20190415 161552.561 (3084302080)   (2)> MQTTAsync_sleep:420
terminate called after throwing an instance of 'mqtt::exception'
  what():  MQTT error [-1]: TCP/TLS connect failure
Aborted (core dumped)

could please tell me where is the issue.
I am using paho.mqtt.c(v1.3.0) (libpaho-mqtt3as.so.1)library
I am using ubuntu 16.04 platform.

**Comment by MadhuKandula** [comment]
Hi,

I am getting this issue with async client.
I am using ubuntu 16.04 and paho.mqtt.c(v1.3.0) libpaho-mqtt3as
