### ISSUE TITLE
Is websockets support in the works?

### ISSUE THREAD

**Issue by uvzubovs** [eclipse-paho/paho.mqtt.c#166]
It is so hard to go through firewalls without HTTP :( Please add websockets support.

**Comment by icraggs** [comment]
I'll put it onto the list.  It was easy to add websockets support in Python, but it's a bit harder in C, without using external libraries :-)

**Comment by nicodeceulaer** [comment]
hi, I'm also looking for a C/C++ MQTT client library that supports websocket.
are there any known-to-work combinations of paho and other libraries that get met this feature combination?

**Comment by rallengrc** [comment]
icraggs, so if one was to go about adding websockets support using C based libwebsockets would be a problem?

**Comment by gsilva2016** [comment]
You can publish MQTT messages over websockets using the C Paho client libs. You need to configure your broker to support. Both Mosquitto and HiveMQ brokers already support.

Is this request for something different?

**Comment by nicodeceulaer** [comment]
On this page websocket support is marked as not present?
https://eclipse.org/paho/clients/c/
Is that info page out of date?

**Comment by gsilva2016** [comment]
No but configure your broker for both mqtt and websockets. After, you can publish to it using mqtt as usual and the subscribers on the websocket port will get the publishes.

**Comment by uvzubovs** [comment]
In order for the subscriber to get the messages over the websocket, it must connect to the broker over the websocket, and that is what seems to be not supported in the Paho C client, unless the documentation page is incorrect.

**Comment by gsilva2016** [comment]
True, depending  on the subscriber though you can easily do without paho c. I usually use through a browser with js. Qt has has good support as well.

**Comment by zenonasz** [comment]
Hi, 

Any news on this?

Looking for a paho c client that supports mqtt over websockets.

Moderators has misunderstand the point of the issue here. We looking for websockets support in the C C++ clients so we can use it on either iOS (Objective C) or embedded platforms (arduino or esp8266 sdk).

Whats the status on this, any future support?

Javascript already provide this, will it be hard to port it on C as well?

Can we at least have some guidelines on this? how can it be achieved? whats the flow currently used in the javascript how can websockets subscribe to a topic on a mqtt over ws?

**Comment by icraggs** [comment]
Mosquitto uses libwebsockets so this is an option for this client.  However Roger Light has suggested that a smaller package aimed specifically at our needs would be good.  I have started to think about implementing websockets support myself without using libwebsockets, it's a matter of finding the time.  

In the meantime if a contribution were made using libwebsockets then I would be happy to look at it.

**Comment by eduard739** [comment]
is there any planing in the near future to add web socket support to c?
(for now i am using python paho python embedded in c++)

**Comment by windbender** [comment]
I too will pile on the need for websocket support.  Archaic network admins the world around are basically forcing us to tunnel everything on HTTPS. So be it.

Here's another lib which might help (distinct from libwebsockets )
https://github.com/tatsuhiro-t/wslay

**Comment by NoamMoshe** [comment]
Hi,
Any news on this?

**Comment by attawit** [comment]
Please update .. for C. pls Let me know if this Client Class with websocket available, I port our development to another OS, it seem to be blocked. After checking websocket shall be most reliable solution. Thanks

**Comment by icraggs** [comment]
Ok... I think I should look into how easy (or not) it will be to use libwebsockets...

**Comment by attawit** [comment]
Thanks you,

**Comment by knmr** [comment]
Hi,
Any news on this?

**Comment by Joryzoetendaal** [comment]
Hi, Is there any news for websockets support? Thanks!

**Comment by G2020sudo** [comment]
I'm curuios if anyone is willing to share their use case for needing to pub and sub to a websocket via paho c client?

**Comment by eduard739** [comment]
using mqtt client to interact with web server that send events for example: user enter live video page on the web, then the web send live video event via mqtt WS to let the client know to start streaming

**Comment by knmr** [comment]
@gabe2004 hardware in unknown networks. Firewalls cause less problems with WS and WSS

**Comment by icraggs** [comment]
So the news is, that I haven't started yet.  The two options I am considering are 1) use libwebsockets 2) write the web socket protocol from scratch.  I've already implemented websockets support in Python, so I know what's involved, but obviously writing it in C is much more time consuming than in Python.  If anyone has any other suggestions, let us know.

**Comment by uvzubovs** [comment]
@gabe2004 : It is so hard to go through firewalls without HTTP. iOS apps use Paho C client. When an iOS user is connected to the Internet using Wi-Fi at work, oftentimes corporate firewall blocks non-HTTP traffic. Does this make sense?

**Comment by icraggs** [comment]
We have a contribution for web socket support (thanks to Keith) - it's going through legal checks now.

**Comment by knmr** [comment]
Very good news! Thank you Keith and Ian.

**Comment by Joryzoetendaal** [comment]
Good to hear, can't wait! Thanks!

**Comment by icraggs** [comment]
Keith's PR has been approved.  I'll look to merge it soon.

**Comment by icraggs** [comment]
I've merged the PR into the develop branch.  Existing tests are working.  I want to add some websocket specific tests too.

**Comment by JuergenKosel** [comment]
Hello,

even with the comments of merge request #415 it is still unclear for me, how to pass through a firewall with http-proxy.
I guess that `./paho_cs_sub my/topic --host ws://test.mosquitto.org --port 8080` specifies the address of the broker.

But how is the address of the http-proxy specified?

Or is the web-socket implementation just a preparation step?

Greetings
Juergen
