### ISSUE TITLE
Binary LWT message

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#167]
Why does the C library only allow for a text LWT message payload, through a `const char*` message instead of a `const void*` payload and corresponding payload length? Does the MQTT standard prevent you from using a binary LWT payload?

**Comment by guilhermeferreira** [comment]
According to the MQTT v3.1 protocol specification [http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html] the Will Message "is UTF-8 encoded [character string] in the CONNECT message [...] The message must therefore only consist of 7-bit ASCII characters."

But, to me, the MQTT v3.1.1 Protocol [http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/mqtt-v3.1.1.html], section 3.1.3.3, is not very clear : "The Will Message defines the Application Message that is to be published to the Will Topic [...] This field consists of a two byte length followed by the payload for the Will Message expressed as a sequence of zero or more bytes. The length gives the number of bytes in the data that follows and does not include the 2 bytes taken up by the length itself."

If the v3.1.1 description says the same thing as the v3.1, then its correct to define it as `const char*`. However, if the v3.1.1 allows arbitrary bytes, then I guess it should be `const unsigned char*`, right?

Anyone with a deeper understand of the protocol could clarify this?

**Comment by guilhermeferreira** [comment]
There is another issue open for the same problem, #34.

**Comment by icraggs** [comment]
I'll add the ability to send binary LWT payloads, as well as passwords (PR #159).   "Zero or more bytes" means that any data should be able to be sent.

**Comment by icraggs** [comment]
Update added to the develop branch, for release in June.

**Comment by icraggs** [comment]
I think this issue is fixed - closing.
