### ISSUE TITLE
Segmentation fault or hi CPU load

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#17]
migrated from Bugzilla [#478734](https://bugs.eclipse.org/bugs/show_bug.cgi?id=478734)
status ASSIGNED severity _normal_ in component _MQTT-C_ for _1.2_
Reported in version _1.1_ on platform _PC_
Assigned to: Ian Craggs

On 2015-09-30 11:02:47 -0400, Gianluca Costa wrote:

> Environment:
> OS: Ubuntu 14.04.3 LTS
> CPU: x86 64bit
> Version: paho-1.0.3 (application is linked with libpaho-mqtt3c.so)
> 
> The application that generate the issue is:
> # include <stdio.h>
> # include "MQTTClient.h"
> 
> int main()
> {
>     int rc;
> 
> ```
> MQTTClient client = NULL;
> MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
> 
> conn_opts.keepAliveInterval = 20;
> conn_opts.cleansession = 1;
> 
> while (1) {
>     printf("Create...\n");
>     rc = MQTTClient_create(&client, "192.168.1.123", "Menego", MQTTCLIENT_PERSISTENCE_NONE, NULL);
>     if (rc == MQTTCLIENT_SUCCESS) {
>         printf("Try...\n");
>         if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS) {
>             printf("Fault\n");
>             MQTTClient_destroy(&client);
>             client = NULL;
>         }
>         else
>             break;
>     }
>     else {
>         printf("End");
>         break;
>     }
> }
> 
> return 0;
> ```
> 
> }
> 
> The main part of the test is that the connection fails, therefore the MQTTClient_destroy is called and after that it is called MQTTClient_create.
> 
> Using valgrind I have these errors:
> ==3973== Invalid read of size 4
> ==3973==    at 0x54B8414: pthread_mutex_lock (pthread_mutex_lock.c:66)
> ==3973==    by 0x570937B: ??? (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
> ==3973==    by 0x570B388: SSL_COMP_get_compression_methods (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
> ==3973==    by 0x5710708: SSL_library_init (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
> ==3973==    by 0x4E46DCB: SSLSocket_initialize (SSLSocket.c:400)
> ==3973==    by 0x4E3F6AE: MQTTClient_create (MQTTClient.c:272)
> ==3973==    by 0x40095F: main (main.c:17)
> ==3973==  Address 0x5f7c6c4 is 660 bytes inside a block of size 1,656 free'd
> ==3973==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==3973==    by 0x4E3B373: myfree (Heap.c:242)
> ==3973==    by 0x4E46EC4: SSLSocket_terminate (SSLSocket.c:445)
> ==3973==    by 0x4E3CC66: MQTTClient_terminate (MQTTClient.c:332)
> ==3973==    by 0x4E3CDE3: MQTTClient_destroy (MQTTClient.c:399)
> ==3973==    by 0x4009CA: main (main.c:23)
> 
> Where line 17 is on MQTTClient_create, and line 23 is on MQTTClient_destroy

On 2015-09-30 11:31:06 -0400, Ian Craggs wrote:

> Hi.  
> 
> That program doesn't show any errors when I run it under valgrind linked against libpaho-mqtt3c.so.  However, the valgrind output shows OpenSSL calls which won't be made unless you link with libpaho-mqtt3cs.so.  It did show the errors then, which I will look into.
> 
> But also, why are you destroying the client object at that point, rather than trying to reconnect, after a delay for instance?  You don't need to recreate the client object to be able to reconnect.  Is this just to demonstrate the problem?
> 
> If you want to try to connect to a number of possible MQTT host/port combinations in sequence if one doesn't work, then you can also use the serverURIs connect option, which would also avoid having to destroy and recreate the client object.

On 2015-10-01 04:16:14 -0400, Gianluca Costa wrote:

> Hi,
> yes the issue comes using libpaho-mqtt3cs.so (I forgot the 's'... I'm sorry).
> Yes, the code demonstrates the problem, but thanks for the very helpful suggestion about try to reconnect without destroying the client object.

**Comment by icraggs** [comment]
I'm going to close this issue, as I've not heard anything since 2015.
