### ISSUE TITLE
timeout on MQTTClient_waitfor() in MQTTClient.C

### ISSUE THREAD

**Issue by AcoemDlu** [eclipse-paho/paho.mqtt.c#173]
Paho C MQTT APIs compiled with VisualStudio 2015 
I want to send message to IoT Hub.
I have a timeout on Thread_wait_sem() in MQTTClient_waitfor()
I use this configuration in paho_cs_pub.c:
url: TestAcoemIotHub.azure-devices.net:1883

"DeviceAcoem"
, "\n"
, 100
, 0
, 0
, "xxx.azure-devices.net/DeviceAcoem"
, "SharedAccessSignature sr=xxx.azure-devices.net%2fdevices%2fDeviceAcoem&sig=3DO9XHIa0igyCYdYp%2bTd2VwPkROxiRvEAIQK3X9Uqg4%3d&se=1501234285"
, "xxx.azure-devices.net"
, "1883"
, 1

Thanks for your reply

**Comment by icraggs** [comment]
If you can take a trace as explained in the readme:  set the environment variable MQTT_C_CLIENT_TRACE=ON and capture the output.

**Comment by icraggs** [comment]
I'm going to close this issue.  If you need more information then you can add a comment here or reopen.
