### ISSUE TITLE
Connection lost, segmentation fault

### ISSUE THREAD

**Issue by viko58** [eclipse-paho/paho.mqtt.c#176]
I'm using MQTTAsync  of this example in https://github.com/eclipse/paho.mqtt.c/blob/master/src/samples/MQTTAsync_subscribe.c,  all seems good, I can subscribe/publish but when I disconnect my Interface, I get a segmentation fault, I'm trying to find the issue, and it seems that issue is on "connlost" function callback when client try to reconnect: 
if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS) {
  printf("Failed to start connect, return code %d\n", rc);
   finished = 1;
} 
Thanks for your reply

**Comment by icraggs** [comment]
Thanks, I've added a fix.
