### ISSUE TITLE
Paho MQTT for mbedTLS

### ISSUE THREAD

**Issue by ela34** [eclipse-paho/paho.mqtt.c#177]
Hello,
Is there any work in progress for having Paho using mbedTLS?

**Comment by icraggs** [comment]
Hi.  The Paho embedded C client is the one that was written for use in the mbed environment.  We were constrained at one point by the GPL licensing of the TLS library which is when I wrote this description:

http://modelbasedtesting.co.uk/?p=181

Now we could have more direct support.  But the place to look is https://github.com/eclipse/paho.mqtt.embedded-c

**Comment by PravallikaKG** [comment]
Hi icraggs,

The code in the paho.mqtt.embedded.c doesnot have tls functionality.  Is my understanding is right?

Could you please help me where can i get code for paho mqtt embedded c client using mbedtls(light weight tls library) library?

Thanks In Advance
