### ISSUE TITLE
Deadlock when MQTT broker connection is lost

### ISSUE THREAD

**Issue by joepschroen** [eclipse-paho/paho.mqtt.c#182]
I noticed that the MQTTA library does not detect a broken connection and will cause a deadlock in the application integrating the library. It does not call the connection loss callback and keeps printing:
"PINGRESP not received in keepalive interval for client ExampleclientPub on socket 17, disconnecting".
When I enable debugging (MINIMUM level) it works correctly! 
Cross-compiling using the openWRT toolchain for a MIPS processor.

**Comment by icraggs** [comment]
If you can get a trace, that could help.  Setting environment variable:

MQTT_C_CLIENT_TRACE=ON

Thanks

**Comment by icraggs** [comment]
I've added a fix for issue #190 to the develop branch, which I think is this same issue.  Thanks.
