### ISSUE TITLE
Superfluous pthread dependency in CMake generated Visual Studio projects

### ISSUE THREAD

**Issue by tbeu** [eclipse-paho/paho.mqtt.c#184]
The CMake generated Visual Studio projects for paho-mqtt3a and paho-mqtt3c have an explicit linker dependency to pthread.lib though it is not required at at all. Since pthread.lib is not a system library on Windows the linker is very likely to fail. Removing this pthread.lib from the dependencies simply works.

**Comment by tbeu** [comment]
#134 proposed the proper fix for it.

**Comment by guilhermeferreira** [comment]
Hello @tbeu, the #141 replaces the #134. It's basically the same code. I don't remember why I closed and opened another request.

**Comment by tbeu** [comment]
Already addressed and fixed by #141. Closed as duplicate.
