### ISSUE TITLE
pthread_mutex_lock_full error on repeat calls to MQTTClient_create

### ISSUE THREAD

**Issue by deadprogram** [eclipse-paho/paho.mqtt.c#185]
I have some code that creates a worker thread that periodically creates a new `MQTTClient` and calls `MQTTClient_create()`. Consistently on the third call to `MQTTClient_create()` I receive the following fatal error:

```
=========================================================
                   Trace Output
Product name: Paho Synchronous MQTT C Client Library
Version: ##MQTTCLIENT_VERSION_TAG##
Build level: ##MQTTCLIENT_BUILD_TAG##
OpenSSL version: OpenSSL 1.0.1m 19 Mar 2015
OpenSSL flags: compiler: i586-poky-linux-gcc  -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -mstackrealign -fno-omit-frame-pointer --sysroot=/export/users/neck/iotdk_3.5_dev/workdir/build_edison/tmp/sysroots/edison -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN     -DTERMIO  -O2 -pipe -g -feliminate-unused-debug-types -Wall -Wa,--noexecstack -DHAVE_CRYPTODEV -DUSE_CRYPTODEV_DIGESTS -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_B
OpenSSL build timestamp: built on: Mon Jun  6 13:08:57 2016
OpenSSL platform: platform: debian-i386-i586
OpenSSL directory: OPENSSLDIR: "/usr/lib/ssl"
/proc/version: Linux version 3.10.98-poky-edison+ (neck@flax) (gcc version 4.9.1 (GCC) ) #1 SMP PREEMPT Mon Jun 6 14:32:08 PDT 2016

=========================================================
Testl: ../nptl/pthread_mutex_lock.c:351: __pthread_mutex_lock_full: Assertion `(-(e)) != 3 || !robust' failed.
```

I am using the "classic" / synchronous with SSL lib.

Thanks for any help, this is a big blocker for us right now.

**Comment by icraggs** [comment]
I'll note that on Linux 3 == ERSCH, no such process.  So maybe something has died or been interrupted.

Do you have the full stack trace?  A fuller client trace? Are you deleting the previous object before creating the new one?  Is the sequence of calls to create this quite simple?

**Comment by deadprogram** [comment]
It was basically doing the same as this https://github.com/eclipse/paho.mqtt.c/blob/master/src/samples/MQTTClient_publish.c#L31-L59 but inside a loop. And yes, I was deleting the previous object.

I've changed my implementation to use a single MQTTClient repeatedly, instead of creating a new one, using it, and then destroying it. This certainly seems like a better implementation pattern anyhow.

**Comment by icraggs** [comment]
I tried the scenario you describe with the latest develop branch, and it worked for me - multiple iterations and QoSs.  So I'll close this for now.
