### ISSUE TITLE
MQTTAsync does not respect FD_SETSIZE

### ISSUE THREAD

**Issue by CallumAttryde** [eclipse-paho/paho.mqtt.c#186]
When developing an application using the MQTTAsync interface, we noticed a crash when rapidly creating topics, stemming from a read to a junk location at Socket.c:164

At Socket.c:240, a 'select' call with first argument s.maxfdp1 is made. As per the 'select' manual (and header file), providing a negative or value above FD_SETSIZE inclusive causes undefined behaviour. We noticed that Sockets.maxfdp1 does not boundary check against FD_SETSIZE, so adding sockets very quickly runs above this number and eventually into bad memory. For our purposes as a quick fix, adding a check at Socket_addSocket protected against this problem, though this is not by any means a recommended fix

```
int Socket_addSocket(int newSd)
{
        int rc = 0;

        FUNC_ENTRY;
        if (s.maxfdp1 >= FD_SETSIZE) {
                rc = SOCKET_ERROR;
        }
        else if (ListFindItem(s.clientsds, &newSd, intcompare) == NULL) /* make sure we don't add the same socket twice */
        {
                int* pnewSd = (int*)malloc(sizeof(newSd));
                *pnewSd = newSd;
                ListAppend(s.clientsds, pnewSd, sizeof(newSd));
                FD_SET(newSd, &(s.rset_saved));
                s.maxfdp1 = max(s.maxfdp1, newSd + 1);
                rc = Socket_setnonblocking(newSd);
        }
        else
                Log(LOG_ERROR, -1, "addSocket: socket %d already in the list", newSd);

        FUNC_EXIT_RC(rc);
        return rc;
}
```

**Comment by icraggs** [comment]
I've added a fix to return an error on connect if FD_SETSIZE is exceeded - in the develop branch.
