### ISSUE TITLE
Non-standard network functions

### ISSUE THREAD

**Issue by thprice** [eclipse-paho/paho.mqtt.c#187]
In my project, the standard Linux network communication functions cannot be used (such as connect, recv etc.). Would you accept, and apply, a patch that offers a project to "overload" the corresponding functions?

If so, there are several mechanisms to achieve this. Which one would you prefer?

Callbacks: An obvious options as it has been applied in other projects in the same situation.
pos: well understood pattern, straightforward implementation, same library concurrently supports both types of network functions
neg: slight negative performance impact for "standard" (all existing) projects

Build option: optionally compile support for alternate (project-supplied) network functions
pos: no performance impact
neg: code duplication, code harder to read and understand, requires special library build, conflict with standard build on same system

Defines in header file: a project can provide a header file "overloading" the network functions and build a special version
pos: clean code, no performance impact
neg: requires special library build, conflict with standard build on same system, harder to document

Any other option you can think about?

Regards,
Thierry

**Comment by thprice** [comment]
Only belatedly found out about paho-embedded which seems to support what I'm looking for.

**Comment by icraggs** [comment]
Thanks!  I was going to ask whether you'd seen the embedded client - it doesn't have all the features of this client, but is meant to be very portable.
