### ISSUE TITLE
Makefile for openwrt systems

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#19]
migrated from Bugzilla [#477704](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477704)
status UNCONFIRMED severity _blocker_ in component _MQTT-C_ for _1.2_
Reported in version _unspecified_ on platform _Other_
Assigned to: Ian Craggs

On 2015-09-17 08:35:20 -0400, prem singhania wrote:

> I am trying to use eclipse paho's C client library in an openwrt system(its a cloudgate to be precise). In order to use the library in that environment I need a makefile that installs the package on the go, but the current makefile(one that comes with the package) doesnot have the link from where the openwrt environment can download the package. So if you can please tell me what needs to be added to the makefile so that it works or even better if you could send me different makefile.
> 
> Thanks in advance.

**Comment by icraggs** [comment]
I'm not quite sure how to answer this one.  I'm going to close for now.

**Comment by bacnh85** [comment]
I made a OpenWrt makefile to build [paho.mqtt.c lib](https://github.com/ngohaibac/openwrt-extra-packages/blob/master/paho.mqtt.c/Makefile) to work in OpenWrt package system. Output is: libpaho.mqtt.c_1.3.0-1_ramips_24kec.ipk for my chipset MTK7688.

This makefile has been tested under board# [EK-AI7688H](http://www.acsip.com.tw/index.php?action=products-detail&fid1=21&fid2=&fid3=&id=81)

**Comment by lakshminarayanagurram** [comment]
Hai can you give me the make file to compile paho.mqtt.c lib for openWRT so that i can compile it for my OpenWrt firmware in raspberryPi
