### ISSUE TITLE
Connect failure not properly detected -> catched in endless loop

### ISSUE THREAD

**Issue by JuergenKosel** [eclipse-paho/paho.mqtt.c#190]
In a test for certificate handling, I have configured a mosquitto broker so that it expects,
that my MQTTAsync based client provides a SSL certificate for authentication.
But in this test, the client does not provide the certificate. Therefore it is expected
that the connection could not be successfully established.
But the provided on-connect-failure callback function is not called.
Instead the paho.mqtt.c function Socket_getReadySocket() does not detect, that the socket is already
gone. And the library is catched in an endless loop, waiting for the not existing socket, as shown in the attached log file.

[syslog-no-call-of-connect-failure-endlessloop.txt](https://github.com/eclipse/paho.mqtt.c/files/591461/syslog-no-call-of-connect-failure-endlessloop.txt)

**Comment by JuergenKosel** [comment]
Hello,

after applying the attached patch, it looks like  m->c->connect_state = 0 while the endless loop is entered:

[issue-190-log.txt](https://github.com/eclipse/paho.mqtt.c/files/591847/issue-190-log.txt)

[commit-21cf7ba.txt](https://github.com/eclipse/paho.mqtt.c/files/591848/commit-21cf7ba.txt)

**Comment by icraggs** [comment]
Hi.  I added a new test test2d, in test5.c to show this problem, but whatever I've tried, it's all worked.  The Mosquitto configuration used is test/tls-testing/mosquitto.conf.  Can you change test2d plus the mosquitto configuration if necessary to exhibit this problem?  Changing this area of the code can result in regressions if we're not careful, as the above test results show.

Thanks.

**Comment by JuergenKosel** [comment]
I will try.
But the trouble with this issue is, that it does not happens always - only sometimes.
As commit 45409c0063f34d864666ece0724c0cf8b0c698fc indicated, there is/was some race condition.

**Comment by icraggs** [comment]
Thanks. If we can't reproduce it, then I'll look at your traces more closely.  It's important that we don't break existing behaviour, which the PR does.

**Comment by icraggs** [comment]
Fix added to develop

**Comment by icraggs** [comment]
Will be in 1.2.

**Comment by gittripley** [comment]
Does aadd424 has all fix for this race condition? I am using version aadd424, but it appears that it still have race condition.

I am running a test to stop mqtt broker and start mqtt broker every 10 second. After running this test for an hour or two hours, a call back of on_failure is not received.

**Comment by JGrossholtz** [comment]
I can confirm the same issue as flyhorseli with version 1.3.0. Sometimes the onFailure handler is not called.

**Comment by icraggs** [comment]
@JGrossholtz please use the open issue #496, and try to get a trace.  Thanks.
