### ISSUE TITLE
Build on Win fails

### ISSUE THREAD

**Issue by fmikulu** [eclipse-paho/paho.mqtt.c#193]
Let me suggest some improvements regarding build/install on Win.
There is problem with linking Lin specific pthread an missing ARCHIVE destination for *.lib installation. See attached patch with suggested changes
[0001-Fixed-build-and-installation-for-Win.zip](https://github.com/eclipse/paho.mqtt.c/files/614289/0001-Fixed-build-and-installation-for-Win.zip)

**Comment by tbeu** [comment]
See also #141.

**Comment by icraggs** [comment]
#141 is merged and Windows CMake builds are now working on AppVeyor.  Thanks
