### ISSUE TITLE
Support CMake configure for apps using paho 

### ISSUE THREAD

**Issue by fmikulu** [eclipse-paho/paho.mqtt.c#194]
You can find attached patch and a simple **Findpaho.cmake** finder, resp. **pahoConfig.cmake.in**
The finder can be saved somewhere in a project referencing paho library, e.g:

_referencing-app/cmake/modules/FindPaho.cmake_

And apply commands in its CMakeLists.txt:

**set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/Modules/")
FIND_PACKAGE(paho REQUIRED)
IF (PAHO_FOUND)
    MESSAGE(STATUS "Paho found: " ${PAHO_ROOT_DIR} )
ELSE()
    MESSAGE("Paho cannot be found")
ENDIF()**

Another way is to incorporate **pahoConfig.cmake.in** to paho source root and call there from CMakeLists.txt:

**configure_file(${CMAKE_CURRENT_SOURCE_DIR}/${PROJECT_NAME}Config.cmake.in  {PROJECT_BINARY_DIR}/${PROJECT_NAME}Config.cmake @ONLY)**

**Comment by fmikulu** [comment]
And the attachment ;-)
[modules.zip](https://github.com/eclipse/paho.mqtt.c/files/614294/modules.zip)

**Comment by icraggs** [comment]
Fix added from PR #636.
