### ISSUE TITLE
Automatic reconnect does not work properly after connection is lost

### ISSUE THREAD

**Issue by 0xartem** [eclipse-paho/paho.mqtt.c#196]
I'm trying to implement reconnect feature for my MQTT project. I encountered that reconnect does not call MQTTAsync_connected callback after connection is lost and set up again. It seems that MQTTAsync_receiveThread goes to endless cycle on Socket_getReadySocket function. To test reconnect feature I turn on and turn off Internet connection manually. It's interesting that if I set breakpoint on MQTTAsync_connectionLost callback, turn on the network during the break, and then run the application again - I receive MQTTAsync_connected callback.
I'm running it on Windows 8.1 x64 system.

**Comment by 0xartem** [comment]
Maybe it's the same problem as mentioned in #182

**Comment by icraggs** [comment]
If it's possible to get a trace, that could help. Setting environment variable:

MQTT_C_CLIENT_TRACE=ON

Thanks

**Comment by icraggs** [comment]
Added a fix to the develop branch under issue #190.  If you find that doesn't fix the issue, or have more information, feel free to reopen.  Thanks,
