### ISSUE TITLE
will structure memory leaks

### ISSUE THREAD

**Issue by nnnntosh** [eclipse-paho/paho.mqtt.c#197]
There is a memory leak on MQTTClient_connect(). 
Memory leak always occurs when Will Option is enabled.
I think that `m->c->msg` and `m->c->will->topic` are not released with the following code.

```c
exit:
	if (m->c->will)
	{
		free(m->c->will);
		m->c->will = NULL;
	}
```

[diff.patch.txt](https://github.com/eclipse/paho.mqtt.c/files/641478/diff.patch.txt)

**Comment by icraggs** [comment]
Thanks.  I've fixed this now in the develop branch.
