### ISSUE TITLE
No documentation for auto reconnect ?

### ISSUE THREAD

**Issue by ghost** [eclipse-paho/paho.mqtt.c#198]
There is no documentation available for automatic reconnect flag, and it doesn't behave as expected in a multi threaded environment

**Comment by BeLearner** [comment]
I found it won't autoreconnect,see #206

**Comment by SeadexWP** [comment]
@BeLearner:
It's still not documented, neither is MQTTAsync_setConnected which is very important in that context IMHO.

**Comment by icraggs** [comment]
I've updated the online async client documentation, which includes the auto reconnect calls.

http://www.eclipse.org/paho/files/mqttdoc/MQTTAsync/html/index.html

I guess I should add a new page describing the auto reconnect behaviour all together.

**Comment by icraggs** [comment]
I've added some new sections in the MQTTAsync documentation for auto reconnect and publish while disconnected.
