### ISSUE TITLE
socket error on client unknown disconnecting on CentOS 7

### ISSUE THREAD

**Issue by liorko87** [eclipse-paho/paho.mqtt.c#199]
I'm using CentOS with MQTT C client. When I ran my app I'm receiving the error : `Failed to connect, return code -1`. 
When I'm looking at mosquitto I'm see this output :

```
1482228512: New connection from 127.0.0.1 on port 1883.
1482228512: New connection from 127.0.0.1 on port 1883.
1482228512: New connection from 127.0.0.1 on port 1883.
1482228512: Socket error on client <unknown>, disconnecting.
1482228512: Socket error on client <unknown>, disconnecting.
1482228512: Socket error on client <unknown>, disconnecting.
```

Why the connection is lost?

**Comment by icraggs** [comment]
Please attach a trace of the client by setting environment variable:

MQTT_C_CLIENT_TRACE=ON

and collecting stdout, if this is still a problem for you, and reopen the issue.  Thanks.

**Comment by liorko87** [comment]
The problem was that I used machines names and not IP addresses.

**Comment by mhlg** [comment]
> The problem was that I used machines names and not IP addresses.
I have the same issue can you show how you solved it?

**Comment by icraggs** [comment]
@mhlg By machine names, do you mean TCP host names?  Because host names, or IP addresses will work.  "localhost" or "127.0.0.1" for instance.  Host names, as long as they can be resolved by your DNS.  Easy to check with ping.

**Comment by mhlg** [comment]
@icraggs  Hi I really do not understand what @liorko87 is referring to..
but I have the same mosquitto output 

```
1482228512: New connection from 192.168.10.73 on port 1883.
1482228512: Socket error on client <unknown>, disconnecting. 
```

MQTTNetworkConnect returns OK but as soon as MQTTConnect is called and the packet is sent by sendPacket the "Socket error on client <unknown>, disconnecting" error happens.
sendPacket which internally calls c->ipstack->mqttwrite returns the number of bytes sent and is successfull.

my mqttwrite implementation
```
int MQTTNetOS_write(Network* n, unsigned char* buffer, int len, int timeout_ms)
{
	struct timeval timeout;
	fd_set fdset;
	int rc = -1;
	int readySock = 0;

	FD_ZERO(&fdset);
	FD_SET(n->my_socket, &fdset);

	timeout.tv_sec = 0;
	timeout.tv_usec = timeout_ms;
	readySock = select(n->my_socket + 1, NULL, &fdset, NULL, &timeout);
	if(readySock == 1){
		rc = send(n->my_socket, (char*)buffer, len, 0);
	}


	return rc;
}
```

I assume something inside the MQTTPacket_connectData is not set correctly but I'm not sure what.


My development env is composed of my laptop where mosquitto is running using 
```mosquitto -v```
and an external development board with ETH connectivity where the MQTT client code is running.
