### ISSUE TITLE
[feature] Automatic reconnect and Offline Buffering

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#2]
migrated from Bugzilla [#486951](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486951)
status ASSIGNED severity _normal_ in component _MQTT-C_ for _1.2_
Reported in version _1.2_ on platform _PC_
Assigned to: Ian Craggs

On 2016-02-01 11:39:36 -0500, Ian Craggs wrote:

> Similar to 486843 for Java

On 2016-02-01 11:40:04 -0500, Ian Craggs wrote:

> This one is mine :-)

**Comment by icraggs** [comment]
This is done for the async client.  Not currently planned for the synchronous client.

**Comment by rashed043** [comment]
Is there any news for reconnect for synchronous client? Could please give us any information regarding this? thanks

**Comment by icraggs** [comment]
It's not in plan for the synchronous client at the moment.
