### ISSUE TITLE
Application getting segfault and signal 134 when i send mqtt messages to cloud 5 times per second continously.

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#20]
migrated from Bugzilla [#475697](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475697)
status UNCONFIRMED severity _major_ in component _MQTT-C_ for _1.2_
Reported in version _unspecified_ on platform _Other_
Assigned to: Ian Craggs

On 2015-08-24 06:11:17 -0400, Siva Subrahmanyam Nallamalli wrote:

> We have some mqtt related issues we need to take care of. After some number of mqtt messages are sent to the cloud, the app gets a segment violation (signal 139). The app restarts, but this is still an issue.
> 
> If you run  gdb ./ble_app_xxaa_s120_xxaa.out <core file name> and run bt, you should be able to see the back trace. It segfaults at SSLSocket_continueWrite().

On 2015-08-24 06:16:51 -0400, Siva Subrahmanyam Nallamalli wrote:

> Also sometimes we get signal 134 - this may be stack corruption.
> 
> This is happening when mqtt traffic to the cloud was heavy.

On 2015-08-24 06:52:41 -0400, Ian Craggs wrote:

> Do you have a core file?  Even if you do, on its own, this is unlikely to help much.  I will need more details of your application -- a test program which reproduces the problem, or a trace of the problem.  To get a trace, set the environment variables:
> 
> MQTT_C_CLIENT_TRACE to ON (which will write to stdout), or a filename
> MQTT_C_CLIENT_TRACE_MAX_LINES to the maximum number of lines to add to the trace file, to make sure the event is captured.
> 
> Thanks.

On 2015-08-24 07:28:10 -0400, Siva Subrahmanyam Nallamalli wrote:

> yes i had core file. I will come up a complete trace as we are linking this with our propietary application

On 2015-08-25 07:56:04 -0400, Siva Subrahmanyam Nallamalli wrote:

> This is the backtrace with gdb using core file.
> 
> clf@arm:~$ gdb ./ble__app_xxaa.out_crash jcore_0.keep 
> GNU gdb (Ubuntu 7.7-0ubuntu3.1) 7.7
> Copyright (C) 2014 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "arm-linux-gnueabihf".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> http://www.gnu.org/software/gdb/bugs/.
> Find the GDB manual and other documentation resources online at:
> http://www.gnu.org/software/gdb/documentation/.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from ./ble_cloudleaf_app_xxaa_s120_xxaa.out_crash...done.
> 
> warning: core file may not match specified executable file.
> [New LWP 1233]
> [New LWP 1235]
> [New LWP 1230]
> [New LWP 1232]
> [New LWP 1237]
> [New LWP 1236]
> [New LWP 1238]
> [New LWP 1239]
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
> Core was generated by `/home/clf/ble_cloudleaf_app_xxaa_s120_xxaa.out'.
> Program terminated with signal SIGSEGV, Segmentation fault.
> # 0  0x00000180 in ?? ()
> 
> (gdb) bt
> # 0  0x00000180 in ?? ()
> # 1  0xb6ed1f84 in SSLSocket_continueWrite (pw=0xb5c2753c) at src/SSLSocket.c:807
> # 2  0xb6ed0e28 in Socket_continueWrite (socket=socket@entry=4) at src/Socket.c:720
> # 3  0xb6ed0f7c in Socket_continueWrites (pwset=pwset@entry=0xb5bfec60) at src/Socket.c:781
> # 4  0xb6ed1124 in Socket_getReadySocket (more_work=more_work@entry=0, tp=tp@entry=0xb5bfed24) at src/Socket.c:246
> # 5  0xb6ecb42a in MQTTAsync_cycle (sock=sock@entry=0xb5bfedc0, timeout=timeout@entry=1000, rc=rc@entry=0xb5bfedbc) at src/MQTTAsync.c:2584
> # 6  0xb6ecb79a in MQTTAsync_receiveThread (n=<optimized out>) at src/MQTTAsync.c:1477
> # 7  0xb6f71fbc in start_thread (arg=0xb5bff430) at pthread_create.c:314
> # 8  0xb6d5eb3c in ?? () at ../ports/sysdeps/unix/sysv/linux/arm/nptl/../clone.S:92 from /lib/arm-linux-gnueabihf/libc.so.6
> 
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)

On 2015-08-25 09:09:52 -0400, Ian Craggs wrote:

> So I determine from the stack trace that you are using the asynchronous client with an SSL connection.  I'm going to need some more information to go on.  Are you able to get an MQTT client trace, as outlined above?
> 
> Does this situation occur after a predictable number of messages, or variable?  Are there any error messages or more information on the server when this happens?  
> 
> What QoS are you using?  What does your MQTT application look like - like any of the SSL Async tests in test/test5.c?  If you were to write a test to reproduce the problem, what would it look like?
> 
> And, what version of the client library are you using?
> 
> Thanks

On 2015-09-07 07:58:19 -0400, Siva Subrahmanyam Nallamalli wrote:

> So I determine from the stack trace that you are using the asynchronous client with an SSL connection.  I'm going to need some more information to go on.  Are you able to get an MQTT client trace, as outlined above?
> 
> It is very intermittent issue. I didnt got the clients trace still it was not reproduced with MQTT client trace enable.
> 
> Does this situation occur after a predictable number of messages, or variable?  Are there any error messages or more information on the server when this happens?  
> This Happens when No of MQTT client publish messages/sec(traffic) to cloud increases drastically.There are no error messages.  
> 
> What QoS are you using?  What does your MQTT application look like - like any of the SSL Async tests in test/test5.c?  If you were to write a test to reproduce the problem, what would it look like?
> QoS set 1.
> We are also trying to reproduce with standalone application, that generates mqtt messages to the cloud. i.e in while(1) send mqtt publish messages.
> we had written a separate thread to enque mqtt messages & dequeue it and process. Finally calling MQTTAsync_sendMessage function.
> 
> And, what version of the client library are you using?
> latest version i.e 1.0.3.

**Comment by icraggs** [comment]
Closing this issue as I didn't get a response to my last question.

**Comment by choka85** [comment]
Hey guys..

I ran into same issue mentioned here. This issue occurs after SSL_write() in SSLSocket_putdatas() fails, paho adds failed write to the "writes" list which should be written later through SSLSocket_continueWrite() function. If paho client gets disconnected before SSLSocket_continueWrite()  finishes its job, SSLSocket_close() will free same SSL structure (net->ssl) which is added in"writes" list SSLSocket_putdatas. When paho reconnects and tries to finish write from "writes" list in SSLSocket_continueWrite(), crash usually occurs in SSL_write(pw->ssl,...) bcs passed argument "pw->ssl" is actually freed SSL structure pointer from SSLSocket_close() which is freed when disconnection occurred. So, now pw->ssl structure fields now contain some random values which cause app to crash mostly with SIGSEGV while dereferencing ((int*)pw->ssl)[2].. sometimes also with SIGBUS, SIGILL or memory leak occurs and app freezes at some point... depends on new random values in pw->ssl...

I simply added SocketBuffer_writeComplete(net->socket) in SSLSocket_close() which fixed this issue.. Not sure if that's best possible solution though but removing that unfinished write from a list prevented app to crash for me at least....
Also, I haven't mentioned that we are using QoS1..

Best Regards,
Goran

**Comment by icraggs** [comment]
I'll reopen as a result of Goran's comment.

**Comment by icraggs** [comment]
Added 

SocketBuffer_writeComplete(socket);

to SocketBuffer_cleanup() which is called by Socket_close();

**Comment by icraggs** [comment]
Fix added to the develop branch.
