### ISSUE TITLE
CMake build doesn't seem to pass -DOPENSSL compilation flag

### ISSUE THREAD

**Issue by prateekbansal** [eclipse-paho/paho.mqtt.c#201]
Issue: Running cmake .. `-DPAHO_WITH_SSL=true` doesn't pass `-DOPENSSL` flag. Possible fix is:

```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 1faaa92..17740f2 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -73,6 +73,8 @@ IF (PAHO_WITH_SSL)
     SET(OPENSSL_LIB_SEARCH_PATH "" CACHE PATH "Directory containing OpenSSL libraries")
     SET(OPENSSL_INC_SEARCH_PATH "" CACHE PATH "Directory containing OpenSSL includes")
     SET(OPENSSL_LIBRARIES ssl crypto)
+    SET(CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -DOPENSSL")
+
     LINK_DIRECTORIES(
         ${OPENSSL_LIB_SEARCH_PATH}
         )
```

**Comment by gsilva2016** [comment]
This was already addressed in the pull request https://github.com/eclipse/paho.mqtt.c/pull/195 
I also posted a comment asking why this change has propagated to dev/master branches.

**Comment by rpendleton** [comment]
It's also addressed in my #149, which hasn't been merged yet. I'm not sure why not though, since it's been working for me perfectly fine.

**Comment by fmikulu** [comment]
Better fix is to add props just to targets with SSL. If set as a compile flag it force other targets to link SSL as well. I recommend to fix it in this way:
         paho-mqtt3cs paho-mqtt3as PROPERTIES
         VERSION ${CLIENT_VERSION}
         SOVERSION ${PAHO_VERSION_MAJOR})
         COMPILE_FLAGS -DOPENSSL)
     INSTALL(TARGETS paho-mqtt3cs
         RUNTIME DESTINATION bin
         ARCHIVE DESTINATION lib

**Comment by icraggs** [comment]
This is now fixed.  TLS builds and tests using CMake are working in both Travis and AppVeyor
