### ISSUE TITLE
Using MQTTClient_publish_async.c inside a thread 

### ISSUE THREAD

**Issue by kushal4** [eclipse-paho/paho.mqtt.c#203]
WHen using the above file inside a thread it publishes twice to the broker and after that it exits out of the infinite loop within which the publish is done at a certain timeout

**Comment by kushal4** [comment]
the 3rd time when it is about to publish the message the thread prints the last debug message which i put in the file MqttPacket.c in the function MQTTPacket_send_publish() what i am anticipating that the queue may be full with the buffer is it the case or is it related to any other issue

**Comment by icraggs** [comment]
It's hard to say without more information.  You could take a trace as outlined in the README: set the environment variable

MQTT_C_CLIENT_TRACE=ON

and capture the output.

**Comment by icraggs** [comment]
If you get more information, then feel free to reopen.  Thanks.
