### ISSUE TITLE
pub0sub1_nb.c  does not receive published message

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#21]
migrated from Bugzilla [#476397](https://bugs.eclipse.org/bugs/show_bug.cgi?id=476397)
status UNCONFIRMED severity _critical_ in component _MQTT-C_ for _1.2_
Reported in version _unspecified_ on platform _PC_
Assigned to: Ian Craggs

On 2015-09-02 03:31:11 -0400, philippe smadja wrote:

> pub0sub1.c and pub0sub1_nb.c do not work (receive message)
> qos0pub.c    published properly (I gor the message with java client.
> Environement:   windows 7.
> NOTE. I updated transport.c for Windows: call to WSAStartup() to initialize socket library
> Any idea.?
> Thanks
> Philippe

**Comment by icraggs** [comment]
Moved to correct repository.
