### ISSUE TITLE
SSL/TLS does not work on Windows

### ISSUE THREAD

**Issue by paulorb** [eclipse-paho/paho.mqtt.c#211]
SSL/TLS does not work at all, not able to create secure connection, the wireshark does not show any SSL traffic. The unit tests on test5.cpp fails. Obs: I am using the lastest OpenSSL version.

**Comment by paulorb** [comment]
I am trying to connect to iot.eclipse.org port 8883

This is the PEM file used
[test.zip](https://github.com/eclipse/paho.mqtt.c/files/699469/test.zip)


This is part of the code


```
MQTTAsync_SSLOptions sslopts = MQTTAsync_SSLOptions_initializer;
		sslopts.trustStore = "C:/test.pem";
		sslopts.enableServerCertAuth = 0;
		conn_opts.ssl = &sslopts;


		conn_opts.keepAliveInterval = MQTTApiManager::GetKeepAlive();
		conn_opts.cleansession = 1;
		conn_opts.onSuccess = onConnect;
		conn_opts.onFailure = onConnectFailure;
		conn_opts.context = mqtt_client_inst;
		conn_opts.connectTimeout = GetTimeout() / 1000;
		if ((rc = MQTTAsync_connect(mqtt_client_inst, &conn_opts)) != MQTTASYNC_SUCCESS)
		{
			*pnStatus = MQTT_ERROR_CONNECTING_BROKER;
			return rc;
		}
```

**Comment by paulorb** [comment]
On SSLSocket.c there is a function called SSLSocket_connect, I am receiving errors, in case of error this function calls SSLSocketError to identify the error. The error I receive is 2 and 5 which are:
SSL_ERROR_WANT_READ and SSL_ERROR_SYSCALL

On the wireshark I cannot see any SSL handshake like Client Hello Server Hello Cipher negotiation.

I really dont know what is going on. I will try mosquitto api to see if I get some different results.

**Comment by chaituy2002** [comment]
Hi..

i tried mosquitto library for TLS-PSK based authentication in my project as
Paho dont have support for it..

it worked fine for me.

Thanks & Regards,
Chaitanya.

**Comment by ghost** [comment]
Try prefixing the adresse with : "ssl://".
Like so : ssl://iot.eclipse.org:8883.

**Comment by icraggs** [comment]
Make sure you are linking against the TLS enabled libraries, whose names end with "s".

AppVeyor TLS WIndows tests are working - you could look at the test programs for examples.

You can get trace out of the protocol and TLS exchanges by setting the environment variables:

MQTT_C_CLIENT_TRACE=<ON or filename)
MQTT_CLIENT_TRACE_LEVEL=PROTOCOL
