### ISSUE TITLE
Void pointer arithmetic issue

### ISSUE THREAD

**Issue by Jarkre** [eclipse-paho/paho.mqtt.c#217]
Socket_continueWrite() function seems to do pointer arithmetic for void pointer which AFAIK is not allowed without casting. The IAR Embedded Workbench compiler shows an error "expression must be a pointer to a complete object type".

However, the GCC compiler compiled the code without an error message.

 		{ /* if previously written length is in the middle of the buffer we are currently looking at, 
 				add some of the buffer */ 
 			size_t offset = pw->bytes - curbuflen; 
 			iovecs1[++curbuf].iov_len = pw->iovecs[i].iov_len - (ULONG)offset; 
 			iovecs1[curbuf].iov_base = pw->iovecs[i].iov_base + offset;  <- Void pointer arithmetic
 			break; 
 		} 

After this casting also the IAR Embedded Workbench compiled the code without an error or warning.

 		{ /* if previously written length is in the middle of the buffer we are currently looking at, 
 				add some of the buffer */ 
 			size_t offset = pw->bytes - curbuflen; 
 			iovecs1[++curbuf].iov_len = pw->iovecs[i].iov_len - (ULONG)offset; 
 			iovecs1[curbuf].iov_base = (char *)pw->iovecs[i].iov_base + offset;
 			break; 
 		}

**Comment by icraggs** [comment]
Looks right, thanks.  Added to develop branch.
