### ISSUE TITLE
automatic reconnect is broken

### ISSUE THREAD

**Issue by SeadexWP** [eclipse-paho/paho.mqtt.c#218]
I connect my MQTTAsync client to a Mosquitto broker instance (automaticReconnect is activated). Everything works fine, I can communicated with the broker. Now I shut down my Mosquitto. My client gets notified about that via the MQTTAsync_connectionLost interface correctly. Then after a short while I restart Mosquitto.
I can see in the paho trace that reconnect tries **should** occur:
20170126 111219.903 Automatically attempting to reconnect
This happens periodically. It will never reconnect tough.
When checking with Wireshark I can see that there is never ever any network traffic to the Mosquitto port. No connection attempt, no ping, no nothing...
Operating system: Windows 10

**Comment by SeadexWP** [comment]
I found the reason:
If the connection timeout is too long (in my case 30s), the connect never times out, because the start value for the timeout gets (falsely) rest all the time.
Thus the socket never gets shut down, thus no new connection attempt, thus no reconnect...
If I take a short timeout (e.g. 1s). The timeout check works and so does the reconnect.

**Comment by SeadexWP** [comment]
This patch worked for me:

```
---
 src/MQTTAsync.c | 11 ++++++++++-
 1 file changed, 10 insertions(+), 1 deletion(-)

diff --git a/src/MQTTAsync.c b/src/MQTTAsync.c
index f475c27..c11648d 100755
--- a/src/MQTTAsync.c
+++ b/src/MQTTAsync.c
@@ -804,7 +804,16 @@ int MQTTAsync_addCommand(MQTTAsync_queuedCommand* command, int command_size)
 	
 	FUNC_ENTRY;
 	MQTTAsync_lock_mutex(mqttcommand_mutex);
-	command->command.start_time = MQTTAsync_start_clock();
+
+	// >>> Wolfgang Petroschka >>>
+	// Don't set start_time if it is a connect command which is already busy connecting. Else we might
+	// never reach our connect timeout!!!
+	if( ( command->command.type != CONNECT ) || ( ( command->command.type == CONNECT ) && ( command->client->c->connect_state == 0 ) ) )
+	{
+		command->command.start_time = MQTTAsync_start_clock();
+	}
+	// <<< Wolfgang Petroschka <<<
+
 	if (command->command.type == CONNECT || 
 		(command->command.type == DISCONNECT && command->command.details.dis.internal))
 	{
-- 
```

**Comment by icraggs** [comment]
I've added a fix to the develop branch which should fix this issue.  Thanks.

**Comment by yupengfei** [comment]
@icraggs It works on windows, but failed on MacOS 10.12.4.
