### ISSUE TITLE
CMake build on Windows (Visual Studio) fails

### ISSUE THREAD

**Issue by herrfrei** [eclipse-paho/paho.mqtt.c#223]
The build fails due to two errors:

1. The BUILD_TIMESTAMP assignment in the master CMakeLists.txt dows not work on Windows. I would suggest to replace the 'date'-call with the CMake command STRING(TIMESTAMP BUILD_TIMESTAMP UTC).
2. Linking against pthread is not needed (and not possible, of course).

Also, the library files for linking against the DLLs are missed from the packages. I add a diff file for my changes.

[pah.mqtt-c-win-visualc.diff.txt](https://github.com/eclipse/paho.mqtt.c/files/763932/pah.mqtt-c-win-visualc.diff.txt)

**Comment by guilhermeferreira** [comment]
Hello @herrfrei, did you use the current develop branch? The pull request #141 should have fixed those issues. And it has already been merged into develop branch.

**Comment by herrfrei** [comment]
Hello @guilhermeferreira, I used the master branch. I'll try the develop branch later to see if the issues are gone. Right now I have one suggestion: Replace 

IF(WIN32)
    EXECUTE_PROCESS(COMMAND "cmd" " /C date /T" OUTPUT_VARIABLE BUILD_TIMESTAMP)
ELSE()
    EXECUTE_PROCESS(COMMAND date -u OUTPUT_VARIABLE BUILD_TIMESTAMP)
ENDIF()
STRING(STRIP ${BUILD_TIMESTAMP} BUILD_TIMESTAMP)

with 

STRING(TIMESTAMP BUILD_TIMESTAMP UTC)

**Comment by guilhermeferreira** [comment]
Hello @herrfrei, this change seems good. If it works on any platform and with the CMake version required by the project, you can request a pull.

**Comment by herrfrei** [comment]
Hello @guilhermeferreira, the mod should work on every platform (supported since CMake 3.0, requested version by paho). I found another thing to patch: in src/CMakeLists.txt in the INSTALL() macro calls the "RUNTIME DESTINATION" ist not set. On Windows this is used to determine the destination path for DLLs. I'll add this also.

**Comment by icraggs** [comment]
This is resolved in the develop branch.  Thanks.
