### ISSUE TITLE
MQTTClient_connect does not respect MQTT protocol error codes

### ISSUE THREAD

**Issue by ndanzi** [eclipse-paho/paho.mqtt.c#224]
Hi all,

I created a MQTTClient using an existing endpoint address with a broker instance listening on that address. I put  wrong username but the return code of the MQTTClient_connect method is MQTTCLIENT_FAILURE (-1) instead of 4 as reported in the documentation of the method. With the right username I was able to connect to the broker. I had the same behavior also with wrong password. 

I expected that the MQTT protocol error codes were supported by that method as reported in the documentation. But in case of error the MQTTClient_connect always returns -1. Is there a way to get those error codes from MQTTClient_Connect or from another method?

EDIT:
I found this behavior only with a remote IoTHub broker. Mosquitto and apollo brokers handles those codes correctly. Is this a server-side issue?

**Comment by icraggs** [comment]
Hi.  The client library returns the error code that is sent by the server.  The server isn't absolutely required to send back error codes, as the downside is to give more information to a malicious application.  The server may not send back a connack at all, but just close the connection, in which case the client library will return -1.  The packet trace can be switched on with the following environment variables:

MQTT_C_CLIENT_TRACE=ON
MQTT_C_CLIENT_TRACE_LEVEL=PROTOCOL

which should show the connack error code returned, if it is, like this:

20170213 170713.792 3 stdin-publisher-async -> CONNECT cleansession: 1 (0)
20170213 170713.911 3 stdin-publisher-async <- CONNACK rc: 0
