### ISSUE TITLE
Websockets and porting the lib to esp8266 sdk 

### ISSUE THREAD

**Issue by zenonasz** [eclipse-paho/paho.mqtt.c#228]
Not an issue, more like a question for the upcoming releases.

1) supportin websockets like yor paho.js (with pubsub).
2) porting the lib to esp8266 nonos sdk. 

If there plans of supporting websockets, i will try to port the lib to esp8266 nonos sdk. Of course, it will be handy if you can point me the possibilities since you know the dependencies of lib.

P.S there is already a ported lib for arduino which supports mqtt over websockets but is for the amazon aws. https://github.com/odelot/aws-mqtt-websockets

Regards,
Zenon.

**Comment by icraggs** [comment]
I do have websocket plans, but not sure how long it would take - depends how much of that I write myself, or rely on an external library like libwebsockets.

If the nonos sdk API is Linux like, using OpenSSL for TLS then this Paho library might be  a good starting point.  If the APIs are unlike Linux, then the Paho embedded C client is probably a better bet.  

I'm going to close this issue as there is another to track websockets.   I'm happy to answer further questions if you have any.
