### ISSUE TITLE
segfault in MQTTProtocol_keepalive

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#23]
migrated from Bugzilla [#470858](https://bugs.eclipse.org/bugs/show_bug.cgi?id=470858)
status UNCONFIRMED severity _normal_ in component _MQTT-C_ for _1.2_
Reported in version _1.0_ on platform _PC_
Assigned to: Ian Craggs

On 2015-06-24 03:49:16 -0400, Ruslan Filipenko wrote:

> MQTTClient.c: while destroying the last mqtt client (MQTTClient_destroy) MQTTClient_terminate is called. MQTTClient_terminate calls ListFree(bstate->clients) which causes bstate->clients to become an invalid pointer. But a thread function MQTTClient_run may still be running calling MQTTProtocol_keepalive function. 
> 
> The line 
> 
> Clients\* client =   (Clients*)(current->content);
> 
> results in segfault as bstate->clients is no longer a valid pointer.
> 
> I've ended with the following fix:
> 
> --- a/src/LinkedList.c
> +++ b/src/LinkedList.c
> @@ -399,6 +399,12 @@ void ListFreeNoContent(List\* aList)
>   _/
>  ListElement_ ListNextElement(List\* aList, ListElement*\* pos)
>  {
> -    if (!aList || !aList->count)
> -    {
> -        *pos = 0;
> -        return 0;
> -    }
>   +
>   return _pos = (_pos == NULL) ? aList->first : (*pos)->next;
>   }
> 
> diff --git a/src/MQTTClient.c b/src/MQTTClient.c
> index 0511d58..7d7cd39 100644
> --- a/src/MQTTClient.c
> +++ b/src/MQTTClient.c
> @@ -325,6 +325,7 @@ void MQTTClient_terminate(void)
>   if (initialized)
>   {
>       ListFree(bstate->clients);
> -               bstate = &ClientState;
>     ListFree(handles);
>     handles = NULL;
>     Socket_outTerminate();

On 2015-08-11 11:08:32 -0400, Ian Craggs wrote:

> The first call in MQTTClient_terminate() is to call MQTTClient_stop() whose job it is to stop the background thread.   The intention is that the background thread is stopped before cleaning up the client list, so this situation would not occur. 
> 
> Can you get a trace of the event (environment variable MQTT_C_CLIENT_TRACE=filename)?

On 2015-08-13 11:54:06 -0400, Ian Craggs wrote:

> Or do you have a test program which reproduces the problem?

**Comment by icraggs** [comment]
The background thread should be stopped before the list is freed.  If it's still a problem, making sure the background thread is ended properly would be my preferred fix.
