### ISSUE TITLE
How can I publish a message from the msgarrvd function?

### ISSUE THREAD

**Issue by CheyenneForbes** [eclipse-paho/paho.mqtt.c#242]
I tried this but it doesnt work:
```
int rc;
MQTTAsync client = (MQTTAsync)context;

MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
pubmsg.payload = "PAYLOAD";
pubmsg.payloadlen = strlen("PAYLOAD");
pubmsg.qos = QOS;
pubmsg.retained = 0;
deliveredtoken = 0;

if ((rc = MQTTAsync_sendMessage(client, "TOPIC", &pubmsg, NULL)) != MQTTASYNC_SUCCESS)
{
	printf("Failed to start sendMessage, return code %d\n", rc);
}
```

**Comment by icraggs** [comment]
testt4.c shows how to accomplish this in several places, such as this:

int test1_messageArrived(void* context, char* topicName, int topicLen, MQTTAsync_message* message)
{
	MQTTAsync c = (MQTTAsync)context;
	static int message_count = 0;
	int rc;

	MyLog(LOGA_DEBUG, "In messageArrived callback %p", c);

	if (++message_count == 1)
	{
		MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
		MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
		pubmsg.payload = "a much longer message that we can shorten to the extent that we need to payload up to 11";
		pubmsg.payloadlen = 11;
		pubmsg.qos = 2;
		pubmsg.retained = 0;
		rc = MQTTAsync_sendMessage(c, test_topic, &pubmsg, &opts);
	}
	else
	{
		MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;

		opts.onSuccess = test1_onUnsubscribe;
		opts.context = c;
		rc = MQTTAsync_unsubscribe(c, test_topic, &opts);
		assert("Unsubscribe successful", rc == MQTTASYNC_SUCCESS, "rc was %d", rc);
	}

	MQTTAsync_freeMessage(&message);
	MQTTAsync_free(topicName);

	return 1;
}

**Comment by icraggs** [comment]
It is run in every Travis and AppVeyor build.

**Comment by CheyenneForbes** [comment]
Thank you, I got it working, the problem was that the second parameter (context) for `MQTTAsync_setCallbacks` was set to NULL, I thought the context that was passed to `msgarrvd` was the on that was set with `MQTTAsync_connect`
