### ISSUE TITLE
Memory leaks with SocketBuffer_interrupted().

### ISSUE THREAD

**Issue by nnnntosh** [eclipse-paho/paho.mqtt.c#244]
Hi all,
I found a memory leak on SSL connection When SSL_ERROR_WANT_READ returns many times.
Also, I think that plain socket connection have the same problem.
There is a problem with SocketBuffer_interrupted(), and entry is accumulated in the queues linked list is the cause of the leaks.
In SocketBuffer_interrupted(), socket value is not set with else statements, entry is not hit by ListFindItem() at next time. And unused memory accumulates in the queue.

I think that adding the code as below will solve the problem.

```c
int SSLSocket_getch(SSL* ssl, int socket, char* c)
{
	int rc = SOCKET_ERROR;

	FUNC_ENTRY;
	if (ListFindItem(queues, &socket, socketcompare))
		queue = (socket_queue*)(queues->current->content);
	else /* new saved queue */
	{
		queue = def_queue;

		/* Additional code */
		queue->socket = socket;

		ListAppend(queues, def_queue, sizeof(socket_queue)+def_queue->buflen);
		SocketBuffer_newDefQ();
	}
	.......
```

**Comment by icraggs** [comment]
Isn't the socket field set in SocketBuffer_queueChar?

	else if (def_queue->socket == 0)
	{
		def_queue->socket = socket;
		def_queue->index = 0;
		def_queue->datalen = 0;
	}

How did you find the memory leak?  Do you have some gdb or valgrind output?

Can you get some trace of when it happens?  Setting environment variables:

MQTT_C_CLIENT_TRACE=ON
MQTT_C_CLIENT_TRACE_LEVEL=PROTOCOL will show TLS + MQTT calls only.

**Comment by nnnntosh** [comment]
Thank you for your reply despite your busy schedule.

I noticed that the memory was increasing when I was stress testing My Application.
The trigger for this problem is to run a large number of publish and subscribe at about the same time.
I inspected it. Add logs where memory leaks are likely to occur.

Please look at the log below.
[paho.mqtt.zip](https://github.com/eclipse/paho.mqtt.c/files/912579/paho.mqtt.zip)

Searching logs from top to bottom with "DEBUG" shows that queue entries increase.

```
20170411 164141.703 SSLSocket error WANT_READ/WANT_WRITE
20170411 164141.703 DEBUG SocketBuffer_interrupted socket=1652, queues->count = 7, queues->size = 975
20170411 164141.703 DEBUG SocketBuffer_interrupted ListFindItem() == false
20170411 164141.703 DEBUG     socket_queue[0]->socket == 0
20170411 164141.703 DEBUG     socket_queue[1]->socket == 0
20170411 164141.703 DEBUG     socket_queue[2]->socket == 0
20170411 164141.703 DEBUG     socket_queue[3]->socket == 0
20170411 164141.703 DEBUG     socket_queue[4]->socket == 0
20170411 164141.703 DEBUG     socket_queue[5]->socket == 0
20170411 164141.703 DEBUG     socket_queue[6]->socket == 0
```

This log has a slight change in the source code and outputs it.

```diff
--- a/src/SocketBuffer.c
+++ b/src/SocketBuffer.c
@@ -224,10 +224,26 @@ void SocketBuffer_interrupted(int socket, size_t actual_len)
        socket_queue* queue = NULL;

        FUNC_ENTRY;
+
+       Log(TRACE_PROTOCOL, -1, "DEBUG SocketBuffer_interrupted socket=%d, queues->count = %d, queues->size = %d", socket, queues->count, queues->size);
+
        if (ListFindItem(queues, &socket, socketcompare))
+       {
+               Log(TRACE_PROTOCOL, -1, "DEBUG SocketBuffer_interrupted ListFindItem() == true");
+
                queue = (socket_queue*)(queues->current->content);
+       }
        else /* new saved queue */
        {
+               Log(TRACE_PROTOCOL, -1, "DEBUG SocketBuffer_interrupted ListFindItem() == false");
+               ListElement* le = NULL;
+               int qcnt = 0;
+               while (ListNextElement(queues, &le))
+               {
+                       socket_queue* sq = (socket_queue*)(le->content);
+                       Log(TRACE_PROTOCOL, -1, "DEBUG     socket_queue[%d]->socket == %d", qcnt++, sq->socket);
+               }
+
                queue = def_queue;
                ListAppend(queues, def_queue, sizeof(socket_queue)+def_queue->buflen);
                SocketBuffer_newDefQ();

```

Also, the log of SSLSocket_error() changes the log level.
```diff
--- a/src/SSLSocket.c
+++ b/src/SSLSocket.c
@@ -68,14 +68,14 @@ int SSLSocket_error(char* aString, SSL* ssl, int sock, int rc)
         error = ERR_get_error();
     if (error == SSL_ERROR_WANT_READ || error == SSL_ERROR_WANT_WRITE)
     {
-               Log(TRACE_MIN, -1, "SSLSocket error WANT_READ/WANT_WRITE");
+               Log(TRACE_PROTOCOL, -1, "SSLSocket error WANT_READ/WANT_WRITE");
     }
     else
     {
         static char buf[120];

         if (strcmp(aString, "shutdown") != 0)
-               Log(TRACE_MIN, -1, "SSLSocket error %s(%d) in %s for socket %d rc %d errno %d %s\n", buf, error, aString, sock, rc, errno, strerror(errno));
+               Log(TRACE_PROTOCOL, -1, "SSLSocket error %s(%d) in %s for socket %d rc %d errno %d %s\n", buf, error, aString, sock, rc, errno, strerror(errno));
          ERR_print_errors_fp(stderr);
                if (error == SSL_ERROR_SSL || error == SSL_ERROR_SYSCALL)
                        error = SSL_FATAL;
```
I don't think that adding "queue-> socket = socket;" is the best fix, but memory does not increase.

Environment data
--------------------
```
 Runtime Environment: Windows10 x64
 MQTT.Paho library version: v1.1.0
```

**Comment by icraggs** [comment]
I've had a look at your debug output and couldn't understand how it got to that position.  I've tried a few tests, both with SSL and without, albeit on Linux, and everything worked as expected.

Could you get a fuller trace of just one cycle using

MQTT_C_CLIENT_TRACE_LEVEL=MINIMUM (the default anyway)?

The question is, when do the socket values in the queues get set to 0?

socket_queue[0]->socket == 0

They should hold the value of the socket.  Only one socket is showing up in your debug output when SocketBuffer_interrupted() is called.

**Comment by nnnntosh** [comment]
I tried it with a plain socket and it worked correctly.
Therefore, memory leak seems to occur only when SSL_ERROR_WANT_READ is returned by SSLSocket_getch().

The contents of the load test are as follows.
· Receive 1000 topics data per second by SUBSCRIBE.
· Send 1000 topics data per second by PUBLISH.

> Could you get a fuller trace of just one cycle using
> MQTT_C_CLIENT_TRACE_LEVEL=MINIMUM (the default anyway)?

I got a log at MINIMUM level.
[paho.mqtt.log.zip](https://github.com/eclipse/paho.mqtt.c/files/961213/paho.mqtt.log.zip)

However, I attached only the first log. Because there are too many logs.
So it may not be helpful.
Also, processing is delayed due to the influence of log output. It is a log when there is no memory leak.
(SSLSocket Error when handshaking is not related to Memory Leak.)

> socket_queue[0]->socket == 0
> They should hold the value of the socket. Only one socket is showing up in your debug output when SocketBuffer_interrupted() is called.

I looked at the value of "def_queue->socket" in SocketBuffer_interrupted(), but it is always zero.
I think that "def_queue-> socket" has been zero all the time and that socket value will never be stored.

**Comment by icraggs** [comment]
Unfortunately the log when there is no memory leak is not so useful.  But I can see what's happening.  If the SocketBuffer_interrupted call is made with no previous queueChar call, then the socket member of the queue structure will not have been set.  This is extremely unlikely to happen except in the SSL case it appears.  Your proposed fix is the shortest, and what I will add for now.

**Comment by icraggs** [comment]
I've added the fix to the develop branch.  Thanks for your help.

**Comment by nnnntosh** [comment]
Thank you for fixing the code.
I am pleased that I can contribute to your project.
