### ISSUE TITLE
Is msgarrvd executed in a new thread or I need to open a new thread in every call to msgarrvd if I want to run some code which will block (GMainLoop)

### ISSUE THREAD

**Issue by CheyenneForbes** [eclipse-paho/paho.mqtt.c#247]

**Comment by icraggs** [comment]
It's not intended that you use blocking requests in any of the callbacks.  It might be ok, but it could cause unintended side effects, including freezing the client library until the calback is returned from.  There is a thread used for callbacks, but it is not a separate thread per callback.  

I had in mind that any request that could take a long time would be started in the callback, and itself signal its completion my making another callback.

**Comment by icraggs** [comment]
Closing for now.
