### ISSUE TITLE
Check client use from multiple threads

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#25]
migrated from Bugzilla [#441950](https://bugs.eclipse.org/bugs/show_bug.cgi?id=441950)
status ASSIGNED severity _normal_ in component _MQTT-C_ for _1.1_
Reported in version _1.1_ on platform _PC_
Assigned to: Ian Craggs

On 2014-08-18 05:29:04 -0400, Ian Craggs wrote:

> A new test should be created which checks the use of both C client libraries (multi-threaded mode for the sync library) from multiple client threads.
> 
> I expect the locking to work correctly.  What I suspect may be a problem is the starting of the background thread(s).  Only one instance of each should be started.  This depends on the variables storing the thread state being shared.
> 
> Needs to be checked on all operating systems (Linux, Windows, Mac), as it may be OS dependent.

On 2015-02-09 06:19:15 -0500, Ian Craggs wrote:

> Adding helpwanted flag

On 2015-08-13 11:50:41 -0400, Ian Craggs wrote:

> I've created test2 which test multiple thread access to the same client object for MQTTClient.
> 
> Remaining tests:
> - multiple thread access to multiple client objects for MQTTClient
> - the same two tests for MQTTAsync

**Comment by icraggs** [comment]
This has been done.
