### ISSUE TITLE
[Suggestion] Report specific error when SSL/TLS not supported

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#251]
It might be helpful to report an error when the user requests an SSL/TLS connection using a version of the library that does not support SSL. Perhaps, in the `MQTTAsync_connect()` function, add a #else to the OPENSSL check to see if the user is asking for an SSL connection?

```
#if defined(OPENSSL)
    // ... normal stuff here
#else
    if (options->struct_version != 0 && options->ssl)
    {
        rc = MQTTASYNC_SSL_NOT_SUPPORTED;
        goto exit;
    }
#endif

**Comment by icraggs** [comment]
Yes, it would be helpful :-)  I had been thinking the same thing myself recently.

**Comment by fpagliughi** [comment]
I created a fix for this the other day, but my editor scrambled all the line ends in the file. I'll try again today and submit a PR.

**Comment by icraggs** [comment]
Fix merged into develop.  Thanks Frank.
