### ISSUE TITLE
The issue of MQTTClient_create

### ISSUE THREAD

**Issue by guobaoteacher** [eclipse-paho/paho.mqtt.c#256]
Hi, all
    I create more than one client in my program using MQTTClient_create. But when I use MQTTClient_connect to connect the server, only one client connect successfully. How can I create more than one client in one program. Thank you.

**Comment by icraggs** [comment]
Did you use a different client id for each client object?  With MQTT, only one instance of a client with the same id can connect simultaneously.

**Comment by icraggs** [comment]
I think that was likely your problem.
