### ISSUE TITLE
Static libs with ssl don't work

### ISSUE THREAD

**Issue by Bubu** [eclipse-paho/paho.mqtt.c#257]
#149 fixed the missing OPENSSL define in cmake. Apparenly this is not enough for the static libraries.

They build fine, but are note compiled with OPENSSL=1 such that they are missing all SSL symbols.

This can be checked with: 
`$ nm ./src/CMakeFiles/paho-mqtt3as-static.dir/SSLSocket.c.o` which return nothing (no symbols inside this object file.)

If you check `$ nm ./src/CMakeFiles/paho-mqtt3as.dir/SSLSocket.c.o` this returns all expected symbols.

I don't understand why SSLSocket.c.o is built twice at all? common_ssl_obj is only added once as a library.

Using:
`cmake . -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_STATIC=TRUE`
cmake version 3.7.2
paho current master

**Comment by icraggs** [comment]
I think this is resolved with the merging of #259
