### ISSUE TITLE
Don't send messages back to publisher

### ISSUE THREAD

**Issue by iceberg1369** [eclipse-paho/paho.mqtt.c#258]
Hello there,
I used same MQTTAsync client to  both subscribe and publish to a single topic. whenever I publish a message I get it back in my subscribe callbacks. so How can I disable receiving my own published messages?

**Comment by miketran78727** [comment]
MQTT is designed to work that way, publisher and receiver.  So, if your application subscribes to the same topic, the callback will be called.

**Comment by iceberg1369** [comment]
@miketran78727  thanks

**Comment by icraggs** [comment]
A note to say that that MQTT version 5, which should be published this year, will have the option for subscriptions to omit sending to the publisher.
