### ISSUE TITLE
Building static libraries with Visual Studio, x64

### ISSUE THREAD

**Issue by dontsovcmc** [eclipse-paho/paho.mqtt.c#261]
Aim: Build static libraries with Visual Studio, x64 (paho-mqtt3c)
Please add to manual, or make project files to do this.

1. In current repository I can't do this. Linking error :(.
The first error: Can't find Version.h file.
I try to change vcproj settings to static manully, compile to lib file. But can't link this lib correctly.

2. In v1.1.0.tar.gz I done static library correctly.

What I do:
a. make my oun script.bat
```
rmdir /s /q
Debug
mkdir Debug
cd Debug
call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
cmake -G "Visual Studio 12 2013" -DPAHO_WITH_SSL=FALSE -DPAHO_BUILD_DOCUMENTATION=FALSE -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.win64.cmake -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SAMPLES=FALSE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=TRUE ..
```
b. open Debug/paho.sln and change in paho-mqtt3c:
- Configuration Type: Static library (.lib)
- C++/Code Generation/Runtime library - Multy-threaded Debug (/MTd)

and compile paho-mqtt3c.

**Comment by icraggs** [comment]
The VersionInfo.h problem has been fixed in the develop branch.  The rest of the static linking updates will be taken care of in #792
