### ISSUE TITLE
Static library doesn't work (visual studio)

### ISSUE THREAD

**Issue by dontsovcmc** [eclipse-paho/paho.mqtt.c#263]
lib version 1.0.0, but this error now also present
windows x64

Open Paho C MQTT APIs.sln
1. Try to build solution: VersionInfo.h not found.
ooookey, run cbuild.bat to create VersionInfo.h, copy it to "src" folder.
2. Build solution, run test1 - OK
3. Change to /MTd projects: paho-mqtt3c, paho-mqtt3a, test1
4. Build static paho-mqtt3c, paho-mqtt3a, test1
5. Run test1 - failed!
Reason in code:
MQTTClient_connect returns -1
817: MQTTClient.c   m->c->connect_state == 0 is TRUE  :(
98: MQTTProtocolOut.c rc = Socket_new(addr, port, &(aClient->net.socket)); return 6 
670: Socket.c rc = connect(*sock, (struct sockaddr*)&address, sizeof(address)); return -1

**Comment by icraggs** [comment]
I've not looked at building statically, it's been added by contributions and was not something I had originally intended to support  If it can work without too much refactoring then I guess that's ok.

For Windows, some initialization of the module is done in DllMain (creating Mutexes), which I'm guessing will not be called for a static library unless some other arrangement is made.  You could try calling that function or similar code directly.

**Comment by dontsovcmc** [comment]
Static library on Ubuntu works..

**Comment by icraggs** [comment]
Initialization on Windows and Linux is different.   Windows initialization relies on DLL callbacks as it stands.  You could call the initialization function explicity in your application:

DLLMain(NULL, DLL_PROCESS_ATTACH, NULL)

or similar.

**Comment by jodogne** [comment]
Hello, I confirm that explicitly calling `DllMain()` does the trick, but you'll need to declare the function as `extern`, as it is not exposed by the Paho headers. For instance:

``` c++
#include <MQTTClient.h>    // or <MQTTAsync.h>

#if defined(_WIN32)
extern BOOL APIENTRY DllMain(HANDLE hModule,
                             DWORD  ul_reason_for_call,
                             LPVOID lpReserved);
#endif

int main()
{
#if defined(_WIN32)
    DllMain(NULL, DLL_PROCESS_ATTACH, NULL);
#endif

  // ...
}
```

@icraggs May I suggest you to move the initialization code for mutexes and semaphore that is contained in `DllMain()`, into the `MQTTClient_global_init()` and `MQTTAsync_global_init()` functions?

**Comment by dontsovcmc** [comment]
I don't understand this 'hack' with calling DllMain.. There is a fact, that something in code doesn't work when you compile library as static. I think, that is a bug.

**Comment by raffienficiaud** [comment]
This is a bug: ``DLLMain`` is called by the operating system when a dll is attached or detached from a process or from a thread. Those events are used to create/delete global objects or thread local objects. I've seen it used only by COM.

In case we use a static linking of paho/mqtt, there is no ``DLLMain``. I would suggest then to expose 2 functions for initializing and releasing the global objects, exactly as ``DLLMain`` is doing, but with an explicit manner. ``DLLMain`` can just branch to those 2 functions directly.

What do you think?

[DLLMain doc](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682583(v=vs.85).aspx)

**Comment by dontsovcmc** [comment]
I think, there is no problem to call init & release functions for compatible. 

I usually see in libraries the same code like this:
```
//  Libiqxmlrpc - an object-oriented XML-RPC solution.
//  Copyright (C) 2011 Anton Dedov

#ifndef _libiqxmlrpc_api_export_
#define _libiqxmlrpc_api_export_

#include "sysinc.h"

#if defined(WIN32) || defined(__MINGW32__)
#ifdef DYNAMIC_LIB
  #define LIBIQXMLRPC_DLL
#endif
#endif // WIN32 || __MINGW32__

#ifdef LIBIQXMLRPC_DLL
  #if defined(LIBIQXMLRPC_COMPILATION) && defined(DLL_EXPORT)
    #define LIBIQXMLRPC_API __declspec(dllexport)
  #elif !defined(LIBIQXMLRPC_COMPILATION)
    #define LIBIQXMLRPC_API __declspec(dllimport)
  #else
    #define LIBIQXMLRPC_API
  #endif // LIBIQXMLRPC_COMPILATION && DLL_EXPORT
#elif defined(__GNUC__) && __GNUC__ > 3
  #define LIBIQXMLRPC_API __attribute__((visibility("default")))
#else
  #define LIBIQXMLRPC_API
#endif // LIBIQXMLRPC_DLL

#endif

```

**Comment by raffienficiaud** [comment]
I created the #341 to address this issue. Let me know if those changes are valid.

**Comment by icraggs** [comment]
Static linking works on Windows - you need to call a MQTTClient_global_init() or MQTTAsync_global_init() function first to initialize the library.  This is done implicitly when used as a shared library.
