### ISSUE TITLE
How to null terminate payloads 

### ISSUE THREAD

**Issue by pbn4** [eclipse-paho/paho.mqtt.c#264]
Hello,

Is there a way for MQTTClient_message->payload to become a null terminated string?  What I showed below is just a conception visualization not an actual idea for the improvement. 

```
void Protocol_processPublication(Publish* publish, Clients* client)
{
	qEntry* qe = NULL;
	MQTTClient_message* mm = NULL;

	FUNC_ENTRY;
	qe = malloc(sizeof(qEntry));
	mm = malloc(sizeof(MQTTClient_message));

	qe->msg = mm;

	qe->topicName = publish->topic;
	qe->topicLen = publish->topiclen;
	publish->topic = NULL;

	/* If the message is QoS 2, then we have already stored the incoming payload
	 * in an allocated buffer, so we don't need to copy again.
	 */
	if (publish->header.bits.qos == 2)
		mm->payload = publish->payload;
	else
	{

#if !defined(NULL_TERMINATED_PAYLOAD)
                mm->payload = malloc(publish->payloadlen);
#else 
                mm->payload = malloc(publish->payloadlen + 1);
#endif
		memcpy(mm->payload, publish->payload, publish->payloadlen);
#if defined(NULL_TERMINATED_PAYLOAD)
                mm->payload[publish->payloadlen] = '\0
#endif
	}
	mm->payloadlen = publish->payloadlen;
#if defined(NULL_TERMINATED_PAYLOAD)
	mm->payloadlen += 1;
#endif
	mm->qos = publish->header.bits.qos;
	mm->retained = publish->header.bits.retain;
	if (publish->header.bits.qos == 2)
		mm->dup = 0;  /* ensure that a QoS2 message is not passed to the application with dup = 1 */
	else
		mm->dup = publish->header.bits.dup;
	mm->msgid = publish->msgId;

	ListAppend(client->messageQueue, qe, sizeof(qe) + sizeof(mm) + mm->payloadlen + strlen(qe->topicName)+1);
#if !defined(NO_PERSISTENCE)
	if (client->persistence)
		MQTTPersistence_persistQueueEntry(client, (MQTTPersistence_qEntry*)qe);
#endif
	FUNC_EXIT;
}
```

If messages are json strings it helps some parsers expecting a null terminated string. There is no workaround for this except for duplicating the message and null terminating it in 2nd buffer. 

What do you think about this?

**Comment by pbn4** [comment]
I don't know if this is a client problem or what, but when I used `mosquitopp` to implement a simple client I was receiving null-terminated messages sent using  `mosquitto_pub`. When I switched to paho I receive a non  null-terminated message using the same `mosquitto_pub` client for sending messages. I don't have a clue what is the reason for this.

**Comment by icraggs** [comment]
With the Paho client, the returned payload is exactly what was received over MQTT, hence identical to what was sent.  If the publisher sent a null terminated payload, that's what you will get.  And vice versa.

**Comment by icraggs** [comment]
It sounds to me like the mosquittopp library *might* null terminate the received payload for you.  I'm going to close this issue.
