### ISSUE TITLE
Disable message arrived callback

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#267]
It doesn't appear possible to disable the "message arrived" callback after it has been set. 

The `MQTTAsync_setCallbacks` checks if that particular callback parameter is NULL and fails if it is. The function allows the other two callbacks, `connectionLost` and `deliveryComplete` to be set back to NULL. 

It appears that access to the pointer is checked for a NULL value throughout the rest of MQTTAsync.c, so it should be safe to set the value back to NULL and thus disable user callbacks for message arrived.

The restricting code is the "|| ma == NULL" at around line 1959 in MQTTAsync.c:
```
int MQTTAsync_setCallbacks(MQTTAsync handle, void* context,
                                         MQTTAsync_connectionLost* cl,
                                         MQTTAsync_messageArrived* ma,
                                         MQTTAsync_deliveryComplete* dc)
{
    ...
    if (m == NULL || ma == NULL || m->c->connect_state != 0)
        rc = MQTTASYNC_FAILURE;
    else
    ...
```

**Comment by icraggs** [comment]
I didn't think it was a good idea not to have a message arrived callback.  What does the library do if a message arrives, but no callback is set?

**Comment by fpagliughi** [comment]
Throw it away?  Hmmm. I see what you're saying.

I'm trying to put a synchronous reader (subscriber) capability into the C++ library. So _after_ connecting and subscribing you could do this:
```
cli.connect();
cli.subscribe(topics);

cli.start_consuming();
while (true) {
    message_ptr msg = cli.consume_message();  // Read next message from thread-safe queue
    if (!msg) break;
    cout << msg->get_topic() << ": " << msg->get_payload_str() << endl;
}
cli.stop_consuming();
```
The `start_consuming()` constructs a thread-safe queue and and calls `setCallbacks` to start the callbacks feeding messages into it.

So what should the `stop_consuming()` do? I thought to disable the callbacks and delete the queue, but we're still subscribed and messages may still be arriving. What should we do, since the user/app has decided it doesn't want them any more?

**Comment by icraggs** [comment]
What happens to messages after the subscribe and before start_consuming() ?  Are they added to the delivery queue?  The same behaviour should occur after stop_consuming() and before unsubscribe() in my opinion.

**Comment by fpagliughi** [comment]
Ah, yeah. That's a race. I suppose the recommended behavior should be that the start/stop consuming should be outside the subscribe envelope:
```
cli.connect();

cli.start_consuming();
cli.subscribe(topics);

// read messages

cli.unsubscribe(topics);
cli.stop_consuming();

cli.disconnect();
```

I thought to let the consumer calls take a topic list - `start_consuming(topics)` and `stop_consuming(topics)` to hide the details from the app, but I didn't want to imply that the queue was tied to just those topics. If the app sent a separate subscribe(), those topics would end up on the queue, too.

**Comment by fpagliughi** [comment]
Oh, but back to my original point...

I was trying to figure out thread safety for manipulating the queue. I don't want a callback when I'm doing that. I can work around the C lib, by giving an empty lambda function to the library for the callback, but I think I'd rather see that flexibility in the C library. If I can turn something on, why can't I turn it off? If messages got lost, that would be my fault. I think I could live with that.

**Comment by icraggs** [comment]
I think that the problem is that MQTT itself doesn't have these semantics, unlike JMS.  You subscribe to start receiving messages and unsubscribe to stop receiving them. 

If you know ahead of time that the subscribe is going to be used for the synchronous reader, then you could stack the subscription request(s), and actually execute them in the start_consuming() call.

**Comment by icraggs** [comment]
Frank, can I close this issue, or is there something more to discuss?

**Comment by fpagliughi** [comment]
Yes, I worked around it.
