### ISSUE TITLE
Not all QoS 2 messages completing.

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#269]
Hey!. Sorry I don't have more info on this problem yet, but I figured I'd start this issue and feed into it as I learn more. It might also be related to #266.

I wrote a little performance test/sample app for the C++ client to time how long it takes to publish a bunch of messages. It sets up a callback, sends N messages, and then waits for N callbacks. Something like:
```
for (int i=0; i<N; ++i)
    client.publish(topic, payload, payloadlen, qos, retained);
wait_for_N_callbacks();
```
The app lets me change the number of messages (N), the payload length, and the qos value.

I typically set N to a few thousand. It works fine for qos=0 & qos=1, but if I use qos=2, then I usually only get a few hundred callbacks (~ 180-300) and then things just stop.

This could well be in the C++ client, but at that layer, there isn't much difference between QOS values. 

Is there a test case in C that covers this?  Should I try to code something up in pure C to recreate this?

Oh, and I'm testing on Linux - Mint 17 (Ubuntu 14.04)  with Mosquitto running over localhost.

**Comment by icraggs** [comment]
There are tests for multiple clients but not specifically many multiple parallel publishes.  You could try taking a trace by setting the MQTT_C_CLIENT_TRACE=ON environment variable.  A snippet of trace in the segment where things are slowing down might be sufficient.

**Comment by icraggs** [comment]
Frank, this works for me once I set the Mosquitto configuration for max_inflight_messages to greater than the amount of simultaneous publishes you are issuing (that's more than is actually needed).  The default is 20, according to the Mosquitto doc.  If the setting is too low, then I get the Mosquitto log message:

1493806125: Outgoing messages are being dropped for client async_test.

and not all the messages are received.

**Comment by fpagliughi** [comment]
Confirmed. I see the same error in the mosquitto log. And the problem goes away if I up the number of inflight messages.

Thanks, Ian.. You can close the issue.
