### ISSUE TITLE
Don't use "typedef struct" or "typedef union"

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#27]
migrated from Bugzilla [#470624](https://bugs.eclipse.org/bugs/show_bug.cgi?id=470624)
status ASSIGNED severity _minor_ in component _MQTT-C_ for _1.2_
Reported in version _unspecified_ on platform _All_
Assigned to: Ian Craggs

On 2015-06-19 14:16:46 -0400, Jerry Hicks wrote:

> There are good reasons to not ever combine the keywords 'typedef struct' and 'typedef union'.
> 
> Foremost is the unnecessary global name space pollution that such usage imposes when structs and unions already enjoy their own name-spaces.
> 
> Please consider separating the declarations of the structs into a separate header and place the typedefs into a separate and optional header if you must.

On 2015-08-10 09:56:38 -0400, Ian Craggs wrote:

> This is not a discussion I was previously aware of.  I see that pros and cons have been fairly well discussed here:
> 
> http://stackoverflow.com/questions/252780/why-should-we-typedef-a-struct-so-often-in-c
> 
> The arguments make sense.  I don't mind changing the approach when I have the time (or accepting a contribution), as long as existing application programs do not need to change.

On 2015-08-11 10:35:42 -0400, Ian Craggs wrote:

> Changing title to be more meaningful

**Comment by icraggs** [comment]
I also read this:

http://stackoverflow.com/questions/10243149/why-is-typedef-struct-foo-foo-considered-harmful

where there are pros and cons described both ways.

**Comment by ralight** [comment]
I've done some reading around this as well and fwiw my view is that if it's a public struct then I would avoid using a typedef but for opaque structs it makes sense.

Having said that, I'm also a big fan of not breaking backwards compatibility unless really necessary.

**Comment by icraggs** [comment]
If you use C++, you don't have to use the struct keyword.  I know that this isn't C++, but I was trying to get to a similar position, which would still probably be my preference.  I don't want to break backward compatibility - we'd have to go to a 2.0 release for that.  

We could have a #define which omitted the typedefs, for those who really want to.   The default would be to operate as we do today.

**Comment by icraggs** [comment]
I'll consider this for future client implementations, or new versions, but not for now.  Thanks.
