### ISSUE TITLE
Connection error with IoT Hub

### ISSUE THREAD

**Issue by ndanzi** [eclipse-paho/paho.mqtt.c#270]
Hi all,
I'm running your develop (commit [`359a9f4`](https://github.com/eclipse/paho.mqtt.c/commit/359a9f4a7339e3d4015ac6223762983c2546b675)) and I am able to connect to several brokers, except IoT Hub. Switching to your Release 1.1.0, the connection to IoT Hub is established correctly. I am running your Test3 with my IoT Hub credential data

Thanks
Nicolo'

**Comment by icraggs** [comment]
Hi.  There's nothing for me to go on unless you provide more information, like a trace.

**Comment by icraggs** [comment]
Please reopen with a trace if this is still a problem for you.  Thanks.
