### ISSUE TITLE
Packet State when a client is closed

### ISSUE THREAD

**Issue by kushal4** [eclipse-paho/paho.mqtt.c#272]
Suppose i am publishing messages to/from a client with Qos=2,the The last message sent from the broker is suppose PUBREL to client but before sending the PUBCOMP packet to broker (or creating that packet in cleint),that client gets closed somehow.In that case,if the publish is done from broker,then do i have to start from the PUBLISH packet itself from the broker or the last PUBREL packet can be sent again?

**Comment by icraggs** [comment]
It would be better to ask general MQTT questions like this on the Paho mailing list or the MQTT Google group.  If the client has connected with cleansession=false, then when the client reconnects, the broker will resend the last PUBREL packet, and the exchange will complete, and the message delivered.

**Comment by kushal4** [comment]
Actually this question is a followup to my previous 1000 connection part where i am trying to close the connection  from the broker when a certain time period has elapsed and store the last succesful state with ehich the packet has been sent through that connection so i thought about asking it here

**Comment by kushal4** [comment]
I am using my own broker where the communication works perfectly when i am opening 800 connections on my test bench but after that this wierd behaviour starts to occur

**Comment by icraggs** [comment]
So I think I've answered your question then haven't I?  Have you read the MQTT 3.1.1 specification on this topic?  Have you compared the behaviour of your broker with Mosquitto?

**Comment by kushal4** [comment]
yes its  answered  for  now  :) yes  i  have compared  it with  the  mosquitto  broker  by  running it side  by  side
