### ISSUE TITLE
/usr/local/include is not created if not existing

### ISSUE THREAD

**Issue by destroyedlolo** [eclipse-paho/paho.mqtt.c#275]
Hello,

It's not really a bug but it's annoying : on linux,
`make install`
doesn't create /usr/local/include if it doesn't exist, trashing the installation of *.h files.

Best regards,

Laurent

**Comment by icraggs** [comment]
If we do that, then we should do it for bin and lib dirs too?

**Comment by destroyedlolo** [comment]
Probably (I duno, bin and lib where already here :) ).

**Comment by chrvadala** [comment]
same problem
