### ISSUE TITLE
 retransmission of PUBLISH packets from paho client for Qos=1 or Qos=2

### ISSUE THREAD

**Issue by kushal4** [eclipse-paho/paho.mqtt.c#279]
Hi,
I dont know whether this feature is a default feature or not,that is why i posted here as an issue.The thing is suppose paho client sends PUBLISH packets for Qos=1 or Qos=2 ,and the broker doesnt recieve that packet for some reason.In this case,is there any provision in paho,where the same data packet can be retransmitted to the broker?
Thanks,
Kushal

**Comment by icraggs** [comment]
The client will retransmit packets on re-establishment of the connection, if the clean session connect option is set to false, as per the MQTT 3.1.1 specification.

**Comment by kushal4** [comment]
ok :) thnks   so,in this case suppose there is a half open connection  ,Do  I have to  close  the connection from  the  broker  side and  the  restablished  of  the  connection  to  be  done  after   that?

**Comment by kushal4** [comment]
Suppose,the client sends PUBLISH packet with say qos=1 and the broker never sends PUBACK to that client,in that case what should be the behaviour so that the same PUBLISH packet with the same data is retransmitted from the client .Do i have to close the connection and reconnect again or is there any other scenario for that ?
