### ISSUE TITLE
Auto-reconnect does not call the onSuccess callback

### ISSUE THREAD

**Issue by jjjwallylabs** [eclipse-paho/paho.mqtt.c#282]
Auto reconnect does not call the connect onSuccess call back because of the following statement:

https://github.com/eclipse/paho.mqtt.c/blob/master/src/MQTTAsync.c#L1780

It's convenient to have the subscribe logic in the onSuccess callback but after the connect callback is called once the pointer to the call back is cleared out.  This isn't helpful for clean sessions.  Rather than having to write code to detected when a reconnect happens what  consequences would removing this line have?  I have commented it out and auto reconnect now calls the callback each time a reconnect happens.

**Comment by jjjwallylabs** [comment]
Let me know if this is the intended functionality or if I am missing something. Since this is a requirement for us I can submit a pull request to add the functionality of resubscribing after auto-reconnecting for a clean session.

**Comment by kushal4** [comment]
Could you please explain your  scenario a bit more clearly?

**Comment by jjjwallylabs** [comment]
Basically after the first successful connection the pointer to the onSuccess callback is cleared out.

https://github.com/eclipse/paho.mqtt.c/blob/master/src/MQTTAsync.c#L1780

It is explicitly set here:

https://github.com/eclipse/paho.mqtt.c/blob/master/src/MQTTAsync.c#L2211

by the 

```int MQTTAsync_connect(MQTTAsync handle, const MQTTAsync_connectOptions* options)```

call. When an auto reconnect occurs this call is not made, so the onSucess callback is not reset to the original connection options. The command to connect is queued up but the original connection options are not set here:

https://github.com/eclipse/paho.mqtt.c/blob/master/src/MQTTAsync.c#L1430

**Comment by kushal4** [comment]
Actually during the reconnect, you have to pass the all the option by yourself on the code itself. I guess thats how basic reconnect is implemented here.So if you can pass on some places about the occurrence of your phenomenon that would be easy to understand

**Comment by jjjwallylabs** [comment]
Sorry, I'm not following what you are saying.  Do you mean to say that if I detect a disconnect that I should reinitialize the client handle with the connection options before auto-reconnect begins?

**Comment by kushal4** [comment]
yes  thats what i am saying  when  you  auto reconnect  you  have to reinitialise again

**Comment by jjjwallylabs** [comment]
Okay thanks, I will add this to my code.

**Comment by kushal4** [comment]
okay  do  tell me  if  it works  for  u

**Comment by icraggs** [comment]
Sorry I missed this question.  Successful auto reconnect calls the connected callback, not the onSuccess callback.  The onSuccess callback is only made in response to a command, like connect or subscribe, and then onSuccess or onFailure will be called only once.

**Comment by jjjwallylabs** [comment]
got it, thanks for the info!
