### ISSUE TITLE
Not check negative number when call MQTTClient_waitfor

### ISSUE THREAD

**Issue by dontsovcmc** [eclipse-paho/paho.mqtt.c#287]
I got infinity waiting of WaitForSingleObject.

millisecsTimeout - MQTTClient_elapsed(start) = -156 = 0xffffff64

```
DWORD WINAPI WaitForSingleObject(
  _In_ HANDLE hHandle,
  _In_ DWORD  dwMilliseconds
); 
```
([MSDN](https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms687032(v=vs.85).aspx)) 

See call stack:
![long_wait](https://user-images.githubusercontent.com/6192152/27230649-9b4c1f32-52b8-11e7-818c-42329dcac352.png)

**Comment by icraggs** [comment]
A client trace would give us more to go on, if it's readily reproducible.  (Environment variable MQTT_C_CLIENT_TRACE=ON).

**Comment by icraggs** [comment]
I assume this falls into the category of it doesn't happen very often... or can occur more if you reduce the connect timeout to a small value.  I've added a fix to the develop branch.

**Comment by dontsovcmc** [comment]
Great! Thanks a lot!
