### ISSUE TITLE
Unsub/Sub after connected

### ISSUE THREAD

**Issue by msaiducar** [eclipse-paho/paho.mqtt.c#288]
Hi,

In my application, I create async connection to broker, and subscribe simple topic. When I publish message to this topic, everything works fine in application. At some point, I unsubscribe existing topic and subscribe new topics (includes wildcard), whenever I publish message, in callback method, topicName and message set null. Is it not possible to unsubscribe/subscribe without disconnect? 

Best Regards,
-Said.

**Comment by icraggs** [comment]
This should work fine.  I would check your subscriptions to the new topics to check that they are connect.

**Comment by icraggs** [comment]
I'm going to close this issue pending a response.  You can reopen if you want to pursue further.
