### ISSUE TITLE
MQTTAsync_connect .onFailure callback MQTTAsync_failureData* is NULL

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#29]
migrated from Bugzilla [#472250](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472250)
status ASSIGNED severity _normal_ in component _MQTT-C_ for _1.2_
Reported in version _future_ on platform _Macintosh_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[file_472250.txt](https://bugs.eclipse.org/bugs//attachment.cgi?id=255073)_ (ID 255073)

On 2015-07-09 03:38:08 -0400, Andres Vahter wrote:

> Created attachment 255073
> testcase
> 
> Using develop branch from: https://github.com/eclipse/paho.mqtt.c.
> 
> If MQTT broker is not running and connect attempt is made we get success here:
> 
> if ((rc = MQTTAsync_sendMessage(client, TOPIC, &pubmsg, &opts)) != MQTTASYNC_SUCCESS)
> {
>     printf("Failed to start sendMessage, return code %d\n", rc);
>     exit(-1);
> }
> 
> .. and then callback with response NULL is called:
> 
> void onConnectFailure(void\* context, MQTTAsync_failureData\* response)
> {
>   if (response == NULL) {
>       printf("Connect response is NULL\n");
>   }
>   printf("Connect failed, rc %d\n", response ? response->code : 0);
>   finished = 1;
> }
> 
> The problem is that application does not get any information why it is unable to connect, because MQTTAsync_sendMessage returns 0 (success) and inside callback we have NULL pointer, so we do not get more information from there either.

On 2015-08-11 06:13:22 -0400, Ian Craggs wrote:

> When I was writing the library I just returned the data from the connack in the failure response code.  When there was no connack, the failure data response was not filled in.  I could add response codes for each connect failure so that each different occurrence did have some information with it.

On 2015-08-11 06:54:58 -0400, Andres Vahter wrote:

> (In reply to Ian Craggs from comment # 1)
> 
> > When I was writing the library I just returned the data from the connack in
> > the failure response code.  When there was no connack, the failure data
> > response was not filled in.  I could add response codes for each connect
> > failure so that each different occurrence did have some information with it.
> 
> That would be reasonable.

**Comment by icraggs** [comment]
Fix added to develop branch.
