### ISSUE TITLE
can't send message after received message

### ISSUE THREAD

**Issue by gutouyu** [eclipse-paho/paho.mqtt.c#293]
I want to send message when I receive every message. And I want to do it sync, so I compile the github source code and use the sync library with head file `MQTTClient.h`  Then I use setCallbacks like this `    MQTTClient_setCallbacks(client, NULL, callback.connectionLost, callback.msgArrived, callback.delivered);` and in msgArrived callback I just simplely send a message when I receive every message , but I can only get it done with the first message I received. Plz help me with this, thx.
```c++
int msgArrived(void *context, char *topicName, int topicLen, MQTTClient_message *message)
{
    int i;
    char* buffer = (char *)malloc(message->payloadlen * sizeof(char));
    char* payloadptr = (char*)message->payload;
    printf("[Receive] : ");
    for(i=0; i<message->payloadlen; i++)
    {
        putchar(*payloadptr++);
    }
    putchar('\n');

    MQTTClient_freeMessage(&message);
    MQTTClient_free(topicName);
    free(buffer);buffer = NULL;

    char* ret; int retLen;
    ret = "client return msg";
    retLen = strlen(ret);
    int result = TSMExecuter_publish(option.serverTopic, ret, retLen);
    return 1;
}
int TSMExecuter_publish(char *topic, char *msg, int msgLen)
{
    deliveryToken = 0;
    printf("begin to publish msg\n");
    int ret;
    long timeout = 10000;
    MQTTClient_token token;
    MQTTClient_message pubmsg = MQTTClient_message_initializer;
    pubmsg.payload = msg;
    pubmsg.payloadlen = msgLen;
    pubmsg.qos = 2;
    pubmsg.retained = 0;
    MQTTClient_publishMessage(client, topic, &pubmsg, &token);
//    ret = MQTTClient_waitForCompletion(client, token, timeout);
    printf("Message delivered with token %d\n", token);
//    if(ret != MQTTCLIENT_SUCCESS) {printf("Error in publish\n");return ERR_PUBLISH_MSG;}
    while(deliveryToken != token);
    printf("publish msg end and success\n");
    return SUCCESS;
}
```

**Comment by icraggs** [comment]
You can't do this with the synchronous client MQTTClient, you can with the asynchronous one, MQTTAsync.  The only MQTT API call that can be made in a callback in MQTTClient is to reconnect in the connectionLost callback.

"Synchronous" refers to the blocking nature of the calls with the MQTTClient API.  The subscribe call, for instance, waits until the acknowledgement is received from the server before continuing.  This means there will be some small delay, but makes it easier to write the application program.

The asynchronous API equivalent subscribe call will just cause the request to be queued internally in the library, leaving the application program to continue quickly.  To determine whether and when the subscribe call succeeded, onSuccess or onFailure callbacks are made to the application.  The application should return from callbacks quickly - if a long running task is started, it's termination too should be tracked by callbacks.  This enables an event-driven application to be created.

**Comment by gutouyu** [comment]
Thank you very much. I have changed to the MQTTAsync and stuff. Problem solved. I thought it's ok to call other MQTT API in all the callbacks, cause don't see warning in the doc earlier, so sad ...

I see plenty of tokes used in source code samples such as MQTTClient_deliveryToken. Only know one token value for one message, but what it is used for? I have trouble in understanding it, could you please help me to understand the token mechanism ?   It would be helpful with some examples. thanks

> The only MQTT API call that can be made in a callback in MQTTClient is to reconnect in the connectionLost callback.
