### ISSUE TITLE
confusion regarding  usage of  minRetryInterval and maxRetryInterval on connect

### ISSUE THREAD

**Issue by kushal4** [eclipse-paho/paho.mqtt.c#297]
Hi,
I have used connectTimeout with a large  value of 400 sec for testing  purpose.I have  given  minRetryInterval as 200 sec and  maxRetryInterval as 300sec.But  the reconnect  occurs  in a very   little  time  less  than  these values.So,whats  the  signficance  of using minRetryInterval and  maxRetryInterval .If  possible  please  show  a  small  example  with it  :)

**Comment by kushal4** [comment]
Is there any maximum  limit  upto  which  the  connect timeout  can  be  set? I think even  if  i remove  minRetryInterval  and  maxInterval  value  from the code,the reconnect  occurs  at very  little  time  much  lesser  than  400 sec

**Comment by icraggs** [comment]
"But the reconnect occurs in a very little time less than these values".  I'm not sure I understand what you mean by this.  Can you give me an actual example time interval that the reconnect occurs in?

**Comment by kushal4** [comment]
having  set the  above  values  as mentioned  above.I  see  reconnect  occurring  at  around   10-15 seconds .I  have  retried  it 2-3 times  with the same  config  getting  the  same  result

**Comment by icraggs** [comment]
The connect timeout should have no effect on the retry interval.  There is no particular maximum, but as the intent is to force the connect attempt to fail if there is no response from TCP or the MQTT server, having a long one would seem to be pointless.

**Comment by kushal4** [comment]
but if   i set  minretryinterval  at  60  should  it retry around  at that time only?

**Comment by kushal4** [comment]
Actually i am  confused  about  retryInterval  ,minretryInterval ,maxretryInterval.When should  it  used ? It  will  be  really  nice  if  you  present some  examples  here  :)

**Comment by icraggs** [comment]
retryInterval is a hold over from MQTT 3.1, when it was recommended that MQTT publish requests where QoS >1 that were not responded to were retried after some interval.  The requirement to do this was removed in MQTT 3.1.1.  From my experience, retries usually only made bad situations worse by increasing the load on already overloaded systems.

minRetryInterval and maxRetryInterval apply to automatic reconnect and are the lower and upper limits of the that reconnect interval, doubling on each failed attempt.  I see that the documentation is lacking in this regard, I will update it.
