### ISSUE TITLE
MQTTPacket_send has a parameter and a function called "free"

### ISSUE THREAD

**Issue by GiveMeMoreMtDew** [eclipse-paho/paho.mqtt.c#298]
The MQTTPacket_send function has an input parameter called "free" and calls the C API function free().  If NO_HEAP_TRACKING is not defined, then the free function is defined as myfree in Heap.h and the compiler does not catch the duplicate meanings.  I suggest that you rename the input parameter (ex. freeData) and pass freeData into the 2 functions that currently accept free.

**Comment by icraggs** [comment]
Good suggestion.  Thanks.
