### ISSUE TITLE
Extra Thread_wait_cond

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#3]
migrated from Bugzilla [#486805](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486805)
status UNCONFIRMED severity _critical_ in component _MQTT-C_ for _1.2_
Reported in version _1.1_ on platform _PC_
Assigned to: Ian Craggs

On 2016-01-29 06:10:28 -0500, Kazuma MISHIMAGI wrote:

> "Thread_wait_cond" in MQTTAsync.c L1275 seems to be extra. 
> (v1.0.3)
> 
> This line seems to make extra waiting time to send next command.
> Sending commands one after another has 1 second waiting time between each commands.
> 
> This line is added in commit e3e40d1 .
> 
> Is this designed behaviour?

On 2016-02-01 10:36:02 -0500, Ian Craggs wrote:

> When a command is sent, the condition variable should be signalled to release the wait_cond and thus the send thread.  This signalling is done in addCommand, at
> 
>   rc = Thread_signal_cond(send_cond);
> 
> So, do you think this is not working, or there should be a signal somewhere else?  Can you get a trace?
> 
> To get a trace, use the following environment variables:
> 
> MQTT_C_CLIENT_TRACE=ON or filename
> MQTT_C_CLIENT_TRACE_MAX_LINES to control the nubmer of lines in the trace file.

**Comment by icraggs** [comment]
As I've been adding the function for offline buffering, I realized exactly what this issue is referring to.   There is indeed an extra Thread_wait_cond - after I added the error checking, I forgot to remove the original line.  I will be fixing this issue.

**Comment by icraggs** [comment]
Fixed in develop.
