### ISSUE TITLE
Fallback from 3.1.1 to 3.1 not always working

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#30]
migrated from Bugzilla [#447113](https://bugs.eclipse.org/bugs/show_bug.cgi?id=447113)
status ASSIGNED severity _major_ in component _MQTT-C_ for _1.1_
Reported in version _1.0_ on platform _PC_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[trace_combined.txt](https://bugs.eclipse.org/bugs//attachment.cgi?id=247861)_ (ID 247861)

On 2014-10-14 10:30:29 -0400, Nicolas Schneider wrote:

> Created attachment 247861
> Trace showing a working and a not working fallback
> 
> Tested using the asynchronous library v1.0.2 and mosquitto v1.2 running on localhost.
> 
> Trace file, which includes two traces â one when the fallback worked, one when it did not â is attached.
> 
> It seems like the socket, which is used during the fallback, gets closed because of an error during the previous handshake sometimes.

On 2014-10-14 10:38:35 -0400, Nicolas Schneider wrote:

> Also, the onFailure callback for the connect command is not invoked.

On 2015-08-10 09:18:13 -0400, Ian Craggs wrote:

> Nicolas,
> 
> I realize it's a long time since this was raised, but I did start to look at it last week.  My simple test program has not reproduced the problem so far, but from the traces it looks like that setting 
> 
> *rc = 0;
> 
> to initialize the return code in MQTTAsync_cycle should fix it.  Does the problem still happen with the latest code?  Are you able to test a fix?
> 
> Thanks

**Comment by icraggs** [comment]
Fixed by the same fix for #190.  Now in the develop branch.
