### ISSUE TITLE
Automatic reconnect "masks" connection timeouts

### ISSUE THREAD

**Issue by GiveMeMoreMtDew** [eclipse-paho/paho.mqtt.c#301]
When automaticReconnect is 1, and minRetryInterval is less than connectionTimeout, automatic reconnect logic is preventing MQTTAsync_checkTimeouts from detecting connection timeouts.

I also believe that this is contributing to issue #297.

Line 1362 of MQTTAsync.c

else if (m->c->connect_state != 0 && MQTTAsync_elapsed(m->connect.start_time) > (m->connectTimeout * 1000))

command.start_time is used in MQTTAsync_checkTimeouts to determine if a connection has timed out.

Line 1419  of MQTTAsync.c which is also in MQTTAsync_checkTimeouts:

if (m->reconnectNow || MQTTAsync_elapsed(m->lastConnectionFailedTime) > (m->currentInterval * 1000))

A connect command is reinserted into the linked list if the time since the last connection failure exceeds currentInterval.  currentInterval is initialized to minRetryInterval in MQTTAsync_startConnectRetry.  If line 1419 is true, then the connect command is reinserted into the linked list using MQTTAsync_addCommand.

Line 838 in MQTTAsync.c, MQTTAsync_addCommand.

command->command.start_time = MQTTAsync_start_clock();

The command.start_time is set to the current time.

What happens when minRetryInterval is less than connectionTimeout?  MQTTAsync_elapsed(m->connect.start_time) > (m->connectTimeout * 1000) on line 1362 will always be false since the reconnect logic is resetting command.start_time before MQTTAsync_elapsed(m->connect.start_time)
exceeds connectTimeout.  Connection timeouts are not detected.  Is this by design?

If this is a bug, then the suggested solution is to redefine MQTTAsync_addCommand.

static int MQTTAsync_addCommand(MQTTAsync_queuedCommand* command, int command_size, int updateStartTime )
{
	// ... code removed for clarity ...
	if (updateStartTime)
		command->command.start_time = MQTTAsync_start_clock();		
	// ... code removed for clarity ...
}

Prevent MQTTAsync_addCommand from updating command.start_time on lines 921 & 1430...

MQTTAsync_addCommand(conn, sizeof(m->connect), 0);

On all other calls, allow MQTTAsync_addCommand  to update the start time...

MQTTAsync_addCommand(conn, sizeof(m->connect), 1);

**Comment by icraggs** [comment]
The retry interval should start at the time of the last connect failure.  I will try it out soon.

**Comment by icraggs** [comment]
What is the external behaviour that is not as you expected?  I changed test3 in test9.c to have minRetryInterval less than the connectTimeout, and the test still worked.

The connection timeout is a time limit on the completion of an individual connect attempt, to fix situations where the TCP or MQTT connect takes a long time.  Automatic reconnect means that in the event of an individual connect failure, a connect will be automatically retried at some point in the future.  No notification is given to the application until a reconnect attempt succeeds.

I don't think that minRetryInterval being less than connectTimeout will cause any different behaviour from the inverse.

**Comment by GiveMeMoreMtDew** [comment]
Upgrading to version 1.2.0 fixed the problem.

Thanks,
Scott

**Comment by icraggs** [comment]
Great.  Fixed in 1.2.
