### ISSUE TITLE
controlling  the interval  at  which  ping  is sent to  the  broker  from  paho  client

### ISSUE THREAD

**Issue by kushal4** [eclipse-paho/paho.mqtt.c#302]
Hi,
Can i  manually set  any interval  for  the PINREQ packets  to  be sent  at  that  time  from  paho  itself?
Thanks,
Kushal

**Comment by icraggs** [comment]
This is controlled by the keepalive interval.  If no other packets are sent to the server within this interval, then a ping will be sent.  This is described by the MQTT specification.

**Comment by kushal4** [comment]
actually  i want  to  send  the PINGREQ packet with  my own  timeinterval   within  the  keepalive  interval  itself.Is it  possible  with  the paho api  :)?

**Comment by kushal4** [comment]
what i mean  is  suppose  i set  keepalive interval as  60 sec ,i want to  define  the  time interval  at  which  PINGREQ  would  be sent  to the  broker with say 20 sec.Is there  any api  as  such  of  doing this  thing  in  paho?

**Comment by icraggs** [comment]
No.  Setting the keepalive interval is the method of controlling the ping frequencies.

**Comment by icraggs** [comment]
Why do you think you need the ping interval to be different or unconnected to, the keep alive interval?

**Comment by kushal4** [comment]
i thought i would control the  time  at  which the  ping would  be  sent in  other  words suppose  keepalive  interval is60 sec  i  would start  ping  at 20 sec interval

**Comment by icraggs** [comment]
In that case why wouldn't you set the keepalive interval to 20 seconds?

**Comment by kushal4** [comment]
actually i thought that ping is  fired at a random  time sometimes i see it is fired quickly ,so had  that  idea  about it

**Comment by icraggs** [comment]
No, the ping is not sent at random, but at predefined times.  This explanation should give you some idea:

https://github.com/eclipse/paho.mqtt.embedded-c/issues/99

**Comment by kushal4** [comment]
ok got it  thanks  :)
