### ISSUE TITLE
reopen Tests failed in Ubuntu

### ISSUE THREAD

**Issue by klif** [eclipse-paho/paho.mqtt.c#303]
Hi, 

I have similar problems with tests (#273).

Mosquitto started with your config...
 ```
$ ps ax | grep mosq
14764 pts/18   S      0:01 mosquitto -c test/tls-testing/mosquitto.conf
```
**Running the tests**
```
python ../test/mqttsas2.py &
ctest -VV
```

```
$ ps ax | grep mqtt
14965 pts/18   S      0:00 python ../test/mqttsas2.py
```
In result:
```
 88% tests passed, 6 tests failed out of 48

Total Test time (real) = 149.67 sec

The following tests FAILED:
	 10 - test3-2as-mutual-ssl-auth-single-thread (Failed)
	 11 - test3-2am-mutual-ssl-auth-multi-thread (Failed)
	 14 - test3-3as-broker-auth-server-cert-in-client-store-single-thread (Failed)
	 15 - test3-3am-broker-auth-server-cert-in-client-store-multi-thread (Failed)
	 28 - test5-2a-multual-ssl-auth-certificates-in-place (Failed)
	 32 - test5-3a-server-auth-server-cert-in-client-store (Failed)
Errors while running CTest
```

WBR

p.s.: last commit I tested was 
commit e8d34da24ad807f5e698b327d67591fd4b4bfa7e
Merge: 082f582 35a7bd6
Author: Ian Craggs <icraggs@users.noreply.github.com>
Date:   Fri Jun 30 15:59:07 2017 +0100

    Merge pull request #292 from orpiske/develop
    
    Bumps RPM version to 1.2.0 for release packaging

Maybe I need check develop branch ...

**Comment by klif** [comment]
You can tell me that errors related to my configuration (without ssl)

```
/**
 * Return code: Attempting SSL connection using non-SSL version of library
 */
#define MQTTASYNC_SSL_NOT_SUPPORTED -13
```
And I also thought so but I configured cmake with ssl support

```
$ cmake -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_SAMPLES=TRUE ~/work/yashkov/paho.mqtt.c
-- CMake version: 3.5.1
-- CMake system name: Linux
-- Timestamp is 2017-07-17T20:19:04Z
-- OpenSSL hints: 
-- OpenSSL headers found at /usr/include
-- OpenSSL library found at /usr/lib/x86_64-linux-gnu/libssl.so
-- OpenSSL Crypto library found at /usr/lib/x86_64-linux-gnu/libcrypto.so
-- OpenSSL hints: 
-- OpenSSL headers found at /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/build.paho
```
and didn`t see any errors nor during cmake nor during make

**Comment by icraggs** [comment]
The master branch is the same as develop, that won't make any difference.

What, if any, messages did Mosquitto produce?  Including the initial ones as a result of using the supplied config.

What are the exact  does taking a client trace say?  It will have OpenSSL messages too.

**Comment by klif** [comment]
Mosquito:
```
$ mosquitto -c test/tls-testing/mosquitto.conf &
[1] 19859
1500363638: mosquitto version 1.4.8 (build date Tue, 23 May 2017 22:14:40 +0100) starting
1500363638: Config loaded from test/tls-testing/mosquitto.conf.
1500363638: Opening ipv4 listen socket on port 1883.
1500363638: Opening ipv6 listen socket on port 1883.
1500363638: Opening ipv4 listen socket on port 18883.
1500363638: Opening ipv6 listen socket on port 18883.
1500363638: Opening ipv4 listen socket on port 18884.
1500363638: Opening ipv6 listen socket on port 18884.
1500363638: Opening ipv4 listen socket on port 18885.
1500363638: Opening ipv6 listen socket on port 18885.
1500363638: Opening ipv4 listen socket on port 18886.
1500363638: Opening ipv6 listen socket on port 18886.
1500363638: Opening ipv4 listen socket on port 18887.
1500363638: Opening ipv6 listen socket on port 18887.
```
```
$ python ../test/mqttsas2.py &
[2] 20086
Listening on port 1884, broker on port 1883
```
ctest -VV 2>&1 | tee test.out

attached test.out.txt (renamed to fit github filter)

[test.out.txt](https://github.com/eclipse/paho.mqtt.c/files/1155052/test.out.txt)

**Comment by icraggs** [comment]
The OpenSSL messages say that they can't find the certificate files.

The CERTDIR CMake variable contains the location of them, and is set by default to

SET(CERTDIR $ENV{TRAVIS_BUILD_DIR}/test/ssl)

So one solution would be to set the TRAVIS_BUILD_DIR environment variable.

This is all in the CMakeLists file in the test directory.

**Comment by icraggs** [comment]
I've updated the travis-env-vars script in the develop branch which will set the environment variables appropriately for running the tests from the main repo directory.
