### ISSUE TITLE
paho program  crashed  when  multiple instances of  1000  clients are run  from different  processes  in  ubuntu

### ISSUE THREAD

**Issue by kushal4** [eclipse-paho/paho.mqtt.c#304]
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffee7fc700 (LWP 3970)]
0x00007ffff4c8b3fb in MQTTAsync_cycle () from /usr/local/lib/libpaho-mqtt3a.so
 when  3 instances of 1000 clients  are  run

**Comment by kushal4** [comment]
(gdb) bt
Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0x8: 
#0  0x00007ffff448a3fb in MQTTAsync_cycle ()
   from /usr/local/lib/libpaho-mqtt3a.so
Cannot access memory at address 0x8

**Comment by kushal4** [comment]
this occurs  when  all  clients are sending  PUBLISH packet  simultaneously  from the different instances

**Comment by icraggs** [comment]
Which version of the code are you using? (That information is crucial).

Also you'll need to provide the backtrace information and ideally a client trace leading up to the problem.

**Comment by kushal4** [comment]
i am  using the version  1.1.0  i am taking  the  log  trace and  putting  it  here  shortly

**Comment by kushal4** [comment]
Actually the scenario  occured  inbetween  all clients  getting connected  and sending  the  PUBLISH  packet,i cant  reproduce the  exact  scenario  right  now   but  if   i do  i  will  post  the  trace    here
