### ISSUE TITLE
REQUEST: Please export Log_setTraceCallback

### ISSUE THREAD

**Issue by GiveMeMoreMtDew** [eclipse-paho/paho.mqtt.c#305]
... unless there is a technical reason for not doing so.

**Comment by icraggs** [comment]
That's what MQTTAsync_setTraceCallback is for.  In fact, that's all it does.

void MQTTAsync_setTraceCallback(MQTTAsync_traceCallback* callback)
{
        Log_setTraceCallback((Log_traceCallback*)callback);
}

**Comment by GiveMeMoreMtDew** [comment]
My bad.  Thanks for pointing that out.
