### ISSUE TITLE
 the OPENSSL seems not work

### ISSUE THREAD

**Issue by frankygu** [eclipse-paho/paho.mqtt.c#311]
Hi @icraggs 
I use the newest code to compile and use the command to enable SSL function like this :
cmake -DPAHO_WITH_SSL=TRUE 

but from my test result :the code under #if defined(OPENSSL) is not included in those libraries.
Could you help me to see it. Thx

**Comment by icraggs** [comment]
You can look at the build scripts for Travis and AppVeyor: travis-build.sh and appveyor.yml for examples.  The automatic builds on both those systems use exactly that for build and testing including SSL on Linux, MacOS and Windows, whichever you are using.

**Comment by icraggs** [comment]
As no further comment I'm going to close this issue.
