### ISSUE TITLE
OS layer to increase portability

### ISSUE THREAD

**Issue by icraggs** [eclipse-paho/paho.mqtt.c#312]
PR #295 contains a discussion on portability and the suggestion to create an OS layer.   I'm opening this issue so the discussion can continue in one place.

**Comment by orpiske** [comment]
I'd like to provide a +1 for providing a OS layer. In particular, I believe that it may also help to leverage code reuse for future updates and new features. It may also simplify testing individual bits of the code (ie.: let's say, implement a test for common data structures, I/O layer, etc), which can help protect/find/etc from underlying OS bugs, and make the test code simpler.

**Comment by icraggs** [comment]
This isn't going to happen unless a contribution is made.  In any case I think the lower layer modules already do some of this.
