### ISSUE TITLE
initiation of  new connection from paho when  the broker closes the connection 

### ISSUE THREAD

**Issue by kushal4** [eclipse-paho/paho.mqtt.c#313]
Hi,
I am closing the connection from the broker end when i am seeing any abnormal  behaviour from any   client  machine like network failure  for instance.So after i close  that connection,suppose the network comes back online  and its sending CONNECT on the same socket from the client  how  would  the broker know that  this is a  new connection and open a new socket?

**Comment by icraggs** [comment]
It can't be the same socket, that will have been closed at both ends.

**Comment by icraggs** [comment]
There is a test broker written in Python in the https://github.com/eclipse/paho.mqtt.testing repository. This may help to show you how this situation works.

**Comment by kushal4** [comment]
ok thanks  looking  at it now :)

**Comment by icraggs** [comment]
Either the socket connection will break, and then both client and server will become aware of the socket errors, possibly after some time.  Or the socket connection will still be working, in which case the conversation can continue.

It is an error for a server to receive a second MQTT connect packet on the same socket.  The server should close the connection and destroy the socket in this case.

**Comment by kushal4** [comment]
got the working now  thanks :)
