### ISSUE TITLE
Submission to the Fedora Linux distribution

### ISSUE THREAD

**Issue by icraggs** [eclipse-paho/paho.mqtt.c#315]
@icraggs, based on our conversation, I am requesting the Eclipse Paho C project inclusion in the Fedora distribution. I would, kindly, request to leave this PR open until the project is officially included in Fedora, because they may request additional changes on packaging.

**Comment by icraggs** [comment]
Fedora inclusion request link: https://bugzilla.redhat.com/show_bug.cgi?id=1476458

**Comment by orpiske** [comment]
Thanks @icraggs. Working on this ticket might actually be better than on the PR. I will update the request inclusion ticket with a link to this issue.

**Comment by icraggs** [comment]
Hello everyone,

I just wanted to let everyone aware that Eclipse Paho C is now available on official Fedora repositories. The packages are available for Fedora 26 and 27.

It can be installed via dnf: dnf install -y paho-c.

If you have any packaging problems, just open a ticket on Fedora's bugzilla and I will be happy to assist you.

Regards
-- 
Otavio R. Piske
Messaging Quality Assurance Engineer

**Comment by icraggs** [comment]
I think I'll close this issue as it now seems complete.  Thanks Otavio!
