### ISSUE TITLE
valgrind memory leak detection with SSL enabled

### ISSUE THREAD

**Issue by michaelschollerer** [eclipse-paho/paho.mqtt.c#316]
Valgrind reports definitely and indirectly lost memory blocks examing a SSL connect and disconnect of my application using server and client authentication. I would like to understand if it is a "real" leakage or a misuse of the paho API. 

I have attached the valgrind and mqtt_c_client_trace logs.

[mqtt_c_client_valgrind.txt](https://github.com/eclipse/paho.mqtt.c/files/1199720/mqtt_c_client_valgrind.txt)
[mqtt_c_client_trace.txt](https://github.com/eclipse/paho.mqtt.c/files/1199721/mqtt_c_client_trace.txt)

**Comment by icraggs** [comment]
An online search found that these two calls which are not yet in SSLSocket_terminate (in SSLSocket.c) may clean these up: 

CRYPTO_cleanup_all_ex_data();
ERR_remove_state(0);

If you build the client yourself, you could try that out and let me know if that works for you, otherwise I'll try it myself sometime soon.

Thanks.

**Comment by michaelschollerer** [comment]
Unfortunately this only decreased the still reachable blocks. I've had a look at MqttAsync and MqttProtocolOut, but the clean up procedure looks proper from my point of view.

I've noticed that the "leak" is not increasing over time or doing multiple connect/disconnects. Seems like the clean up is missing some objects.

 If I can provide you any further details, please let me know.

**Comment by icraggs** [comment]
This might be a useful reference: https://stackoverflow.com/questions/29845527/how-to-properly-uninitialize-openssl/29927669#29927669

**Comment by icraggs** [comment]
I tried this with the latest develop branch (1.3.9+) and got no leaks using the paho_c_pub sample.  Attached is the output.

[log.txt](https://github.com/eclipse/paho.mqtt.c/files/7643251/log.txt)

**Comment by icraggs** [comment]
I think this is fixed as per the last comment.
