### ISSUE TITLE
Too many tries with invalid URI in MQTTAsync_connect leads OS connection stuck

### ISSUE THREAD

**Issue by hackerick4** [eclipse-paho/paho.mqtt.c#319]
```
int MQ::connectToMQ() {
        int rc;
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	MQTTAsync_disconnectOptions disc_opts = MQTTAsync_disconnectOptions_initializer;
	rc = MQTTAsync_create(&client, "" , CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);
	MQTTAsync_setCallbacks(client, NULL, connlost, msgarrvd, NULL);
	conn_opts.keepAliveInterval = 20;
	conn_opts.onSuccess = onConnect;
	conn_opts.onFailure = onConnectFailure;
	conn_opts.cleansession = 1;
	conn_opts.context = client;
        if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS) {
	   //	cout << "Failed to start connect, return code : " << rc << endl;
	}
	return rc;
}
```

issue 1 : Why "MQTTAsync_create" function returned success even I try to input empty connection URL ?

issue 2 : Why "MQTTAsync_connect" also returned success here? 

issue 3 : After I tried MQTTAsync_connect with empty URI many times(over 60,000) would lead OS connection stuck. Every external connections would fail. For example, I cannot ssh to MSSQL and even cannot surf internet until I close MQ Client program. 
I want to ask that MQTTAsync_connect free the socket when URI is invalid. Why did I get this result? and how can I avoid them ?

BTW, My OS is Windows 7 32bit.

**Comment by icraggs** [comment]
I'm afraid this issue is in the wrong place again - should be https://github.com/eclipse/paho.mqtt.cpp

**Comment by hackerick4** [comment]
Thanks, I have moved this issue there.

**Comment by fpagliughi** [comment]
Hey @icraggs, I had asked that this be posted here. The application code appears to be C++, but is is using the C Async library directly. There is nothing in the code snippet from the Paho C++ library.

**Comment by mf1564662361** [comment]
hello，@hackerick4   I had met same issue with you, but my OS is android , I tried on several phones，   but only one android 6.0 device works, and i want to know if you had solved this problem？

**Comment by icraggs** [comment]
You could run one cycle of connecting with a zero length URI with the trace on, and let's see what that tells us?   See the Runtime Tracing section of the Readme for how.

**Comment by mf1564662361** [comment]
@icraggs  Thanks for your answers， I have tried an empty URI  , but also returned connect success code , Here are my Trace log:
<font size=1>=========================================================
                   Trace Output
Product name: Paho Asynchronous MQTT C Client Library
Version: @CLIENT_VERSION@
Build level: @BUILD_TIMESTAMP@
/proc/version: Linux version 3.10.74-gf692d1f (android@localhost) (gcc version 4.7.3 20121205 (prerelease) (crosstool-NG linaro-1.13.1-4.7-2012.12-20121214 - Linaro GCC 2012.12) ) #2 SMP PREEMPT Mon Dec 7 04:26:59 CST 2015

=========================================================
19700101 080000.000 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb70ae958

19700101 080000.000 (3069557740)  (1)> Socket_outInitialize:128
19700101 080000.000 (3069557740)   (2)> SocketBuffer_initialize:94
19700101 080000.000 Allocating 32 bytes in heap at file jni/src/SocketBuffer.c line 81 ptr 0xb72d35d8

19700101 080000.000 Allocating 1008 bytes in heap at file jni/src/SocketBuffer.c line 83 ptr 0xb723b268

19700101 080000.000 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb7251b50

19700101 080000.000 (3069557740)   (2)< SocketBuffer_initialize:98
19700101 080000.000 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb7104d70

19700101 080000.000 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb71da7f0

19700101 080000.000 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb723b688

19700101 080000.000 (3069557740)  (1)< Socket_outInitialize:141
19700101 080000.000 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb723b6f8

19700101 080000.000 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb723b768

19700101 080000.000 Allocating 208 bytes in heap at file jni/src/MQTTAsync.c line 489 ptr 0xb72cb038

19700101 080000.000 Allocating 16 bytes in heap at file jni/src/MQTTProtocolClient.c line 766 ptr 0xb72cb160

19700101 080000.000 (3069557740)  (1)> MQTTStrncpy:743
19700101 080000.000 (3069557740)  (1)< MQTTStrncpy:753
19700101 080000.000 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb72cb1c0

19700101 080000.000 Allocating 16 bytes in heap at file jni/src/LinkedList.c line 95 ptr 0xb723b7d8

20170912 165749.982 Allocating 96 bytes in heap at file jni/src/MQTTAsync.c line 505 ptr 0xb72d4b08

20170912 165749.982 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb72d4bb8

20170912 165749.982 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb72d4c40

20170912 165749.982 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb7206ee0

20170912 165749.982 Allocating 32 bytes in heap at file jni/src/MQTTProtocolClient.c line 766 ptr 0xb7206f58

20170912 165749.982 (3069557740)  (1)> MQTTStrncpy:743
20170912 165749.982 (3069557740)  (1)< MQTTStrncpy:753
20170912 165749.982 (3069557740)  (1)> MQTTPersistence_create:51
20170912 165749.982 (3069557740)  (1)< MQTTPersistence_create:97 (0)
20170912 165749.982 (3069557740)  (1)> MQTTPersistence_initialize:112
20170912 165749.982 (3069557740)  (1)< MQTTPersistence_initialize:120 (0)
20170912 165749.982 (3069557740)  (1)> MQTTAsync_restoreCommands:807
20170912 165749.982 0 commands restored for client GID_m@@@SA9
20170912 165749.982 (3069557740)  (1)< MQTTAsync_restoreCommands:841 (0)
20170912 165749.982 (3069557740)  (1)> MQTTPersistence_restoreMessageQueue:616
20170912 165749.982 0 queued messages restored for client GID_m@@@SA9
20170912 165749.982 (3069557740)  (1)< MQTTPersistence_restoreMessageQueue:651 (0)
20170912 165749.982 Allocating 16 bytes in heap at file jni/src/LinkedList.c line 95 ptr 0xb7206fe0

20170912 165749.982 (3069557740) (0)< MQTTAsync_createWithOptions:536 (0)
20170912 165749.982 (3069557740) (0)> MQTTAsync_setCallbacks:1983
20170912 165749.983 (3069557740) (0)< MQTTAsync_setCallbacks:1997 (0)
20170912 165749.983 (3069557740) (0)> MQTTAsync_setConnected:2007
20170912 165749.983 (3069557740) (0)< MQTTAsync_setConnected:2019 (0)
20170912 165749.983 (3069557740) (0)> MQTTAsync_connect:2197
20170912 165749.983 (3069557740)  (1)> UTF8_validateString:159
20170912 165749.983 (3069557740)   (2)> UTF8_validate:133
20170912 165749.983 (3069557740)    (3)> UTF8_char_validate:83
20170912 165749.983 (3069557740)    (3)< UTF8_char_validate:117
20170912 165749.983 (3069557740)    (3)> UTF8_char_validate:83
20170912 165749.983 (3069557740)    (3)< UTF8_char_validate:117
20170912 165749.983 (3069557740)    (3)> UTF8_char_validate:83
20170912 165749.983 (3069557740)    (3)< UTF8_char_validate:117
20170912 165749.983 (3069557740)    (3)> UTF8_char_validate:83
20170912 165749.983 (3069557740)    (3)< UTF8_char_validate:117
20170912 165749.983 (3069557740)    (3)> UTF8_char_validate:83
20170912 165749.983 (3069557740)    (3)< UTF8_char_validate:117
20170912 165749.983 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.265 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.265 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.267 (3069557740)  (1)> UTF8_validateString:159
20170912 165758.267 (3069557740)   (2)> UTF8_validate:133
20170912 165758.267 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.267 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.267 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.267 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.267 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.267 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.267 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.267 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.267 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.267 (3069557740)    (3)< UTF8_char_validate:117

20170912 165758.268 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.268 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.268 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.268 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.268 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.268 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.268 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.268 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.268 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.268 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.268 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.268 (3069557740)    (3)> UTF8_char_validate:83


20170912 165758.270 (3069557740)    (3)> UTF8_char_validate:83
20170912 165758.270 (3069557740)    (3)< UTF8_char_validate:117
20170912 165758.270 (3069557740)   (2)< UTF8_validate:145 (1)
20170912 165758.270 (3069557740)  (1)< UTF8_validateString:161 (1)
20170912 165758.271 (3069557740)  (1)> Thread_start:67
20170912 165758.271 (3069557740)  (1)< Thread_start:77
20170912 165758.271 (3069557740)  (1)> Thread_start:67
20170912 165758.271 (3069557740)  (1)< Thread_start:77
20170912 165758.271 Allocating 64 bytes in heap at file jni/src/MQTTAsync.c line 2379 ptr 0xb73e5418

20170912 165758.271 (3074309432) (0)> MQTTAsync_receiveThread:1719
20170912 165758.271 (3074309432)  (1)> MQTTAsync_cycle:2890
20170912 165758.271 (3074309432)   (2)> Socket_getReadySocket:234
20170912 165758.271 (3074309432)   (2)< Socket_getReadySocket:300 (0)
20170912 165758.271 (3074309432)   (2)> MQTTAsync_sleep:391
20170912 165758.271 (3069557740)  (1)> MQTTAsync_addCommand:851
20170912 165758.271 Allocating 16 bytes in heap at file jni/src/LinkedList.c line 110 ptr 0xb74090b0

20170912 165758.271 (3069557740)  (1)< MQTTAsync_addCommand:886 (0)
20170912 165758.271 (3069557740) (0)< MQTTAsync_connect:2393 (0)
20170912 165758.271 (3074314704) (0)> MQTTAsync_sendThread:1480
20170912 165758.271 (3074314704)  (1)> MQTTAsync_processCommand:1113
20170912 165758.271 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb73e0c00

20170912 165758.271 Freeing 32 bytes in heap at file jni/src/LinkedList.c line 392, heap use now 1888 bytes

20170912 165758.271 Freeing 16 bytes in heap at file jni/src/LinkedList.c line 224, heap use now 1856 bytes

20170912 165758.271 Connecting to serverURI  with MQTT version 4
20170912 165758.274 (3074314704)   (2)> MQTTProtocol_connect:105
20170912 165758.274 (3074314704)    (3)> MQTTProtocol_addressPort:55
20170912 165758.274 (3074314704)    (3)< MQTTProtocol_addressPort:83
20170912 165758.274 (3074314704)    (3)> Socket_new:620
20170912 165758.274 (3074309432)   (2)< MQTTAsync_sleep:397
20170912 165758.274 getaddrinfo failed for addr  with rc 7
20170912 165758.274  is not a valid IP address
20170912 165758.274 (3074314704)    (3)< Socket_new:713 (7)
20170912 165758.274 (3074314704)   (2)< MQTTProtocol_connect:140 (7)
20170912 165758.274 (3074314704)   (2)> MQTTAsync_disconnect1:2404
20170912 165758.274 (3074314704)   (2)< MQTTAsync_disconnect1:2434 (-3)
20170912 165758.274 (3074314704)   (2)> MQTTAsync_checkConn:438
20170912 165758.274 (3074314704)   (2)< MQTTAsync_checkConn:441 (1)
20170912 165758.274 Connect failed, more to try
20170912 165758.274 (3074314704)   (2)> MQTTAsync_addCommand:851
20170912 165758.274 Allocating 16 bytes in heap at file jni/src/LinkedList.c line 110 ptr 0xb73edcd0

20170912 165758.274 (3074314704)   (2)< MQTTAsync_addCommand:886 (0)
20170912 165758.274 (3074314704)  (1)< MQTTAsync_processCommand:1350 (1)
20170912 165758.274 (3074314704)  (1)> MQTTAsync_processCommand:1113
20170912 165758.274 Allocating 32 bytes in heap at file jni/src/LinkedList.c line 58 ptr 0xb73e1190

20170912 165838.335 Freeing 32 bytes in heap at file jni/src/LinkedList.c line 392, heap use now 1888 bytes

20170912 165838.335 Freeing 16 bytes in heap at file jni/src/LinkedList.c line 224, heap use now 1856 bytes

20170912 165838.335 Connecting to serverURI  with MQTT version 3
20170912 165838.335 (3074314704)   (2)> MQTTProtocol_connect:105
20170912 165838.335 (3074314704)    (3)> MQTTProtocol_addressPort:55
20170912 165838.335 (3074314704)    (3)< MQTTProtocol_addressPort:83
20170912 165838.335 (3074314704)    (3)> Socket_new:620
20170912 165838.335 getaddrinfo failed for addr  with rc 7
20170912 165838.335  is not a valid IP address
20170912 165838.335 (3074314704)    (3)< Socket_new:713 (7)
20170912 165838.335 (3074314704)   (2)< MQTTProtocol_connect:140 (7)
20170912 165838.335 (3074314704)   (2)> MQTTAsync_disconnect1:2404
20170912 165838.335 (3074314704)   (2)< MQTTAsync_disconnect1:2434 (-3)
20170912 165838.335 (3074314704)   (2)> MQTTAsync_checkConn:438
20170912 165838.335 (3074314704)   (2)< MQTTAsync_checkConn:441 (0)
20170912 165838.335 Calling command failure for client GID@@@SMA
20170912 165838.335 Freeing 64 bytes in heap at file jni/src/MQTTAsync.c line 1049, heap use now 1840 bytes

20170912 165838.335 (3074314704)  (1)< MQTTAsync_processCommand:1350 (1)
20170912 165838.335 (3074314704)  (1)> Thread_wait_cond:368
20170912 165838.335 (3074309432)   (2)> MQTTAsync_retry:2772
20170912 165918.388 (3074309432)    (3)> MQTTProtocol_keepalive:519
20170912 165918.388 (3074309432)    (3)< MQTTProtocol_keepalive:552
20170912 165918.388 (3074309432)    (3)> MQTTProtocol_retry:636
20170912 165918.388 (3074309432)    (3)< MQTTProtocol_retry:655
20170912 165918.388 (3074309432)   (2)< MQTTAsync_retry:2782
20170912 165918.388 (3074309432)  (1)< MQTTAsync_cycle:3001 (-1)
20170912 165918.388 (3074309432)  (1)> MQTTAsync_cycle:2890
20170912 165918.388 (3074309432)   (2)> Socket_getReadySocket:234
20170912 165918.388 (3074309432)   (2)< Socket_getReadySocket:300 (0)
20170912 165918.388 (3074309432)   (2)> MQTTAsync_sleep:391
</font>

**Comment by mf1564662361** [comment]
And Here are logs of fail devices
===============================
`20170912 165523.895 (3074458496)    (3)> isReady:210
20170912 165523.895 (3074458496)    (3)< isReady:215 (1)
20170912 165523.895 (3074458496)   (2)< Socket_getReadySocket:300 (92)
20170912 165523.895 (3074458496)   (2)> MQTTAsync_retry:2772
20170912 165523.895 (3074458496)    (3)> MQTTProtocol_retry:636
20170912 165523.895 (3074458496)    (3)< MQTTProtocol_retry:655
20170912 165523.897 (3074458496)   (2)< MQTTAsync_retry:2782
20170912 165523.897 (3074458496)  (1)< MQTTAsync_cycle:3001 (-1)
20170912 165523.897 Could not find client corresponding to socket 92
20170912 165523.897 (3074458496)  (1)> MQTTAsync_cycle:2890
20170912 165523.897 (3074458496)   (2)> Socket_getReadySocket:234
20170912 165523.897 (3074458496)    (3)> isReady:210
20170912 165523.897 (3074458496)    (3)< isReady:215 (1)
20170912 165523.897 (3074458496)   (2)< Socket_getReadySocket:300 (93)
20170912 165523.897 (3074458496)   (2)> MQTTAsync_retry:2772
20170912 165523.897 (3074458496)    (3)> MQTTProtocol_retry:636
20170912 165523.897 (3074458496)    (3)< MQTTProtocol_retry:655
20170912 165523.897 (3074458496)   (2)< MQTTAsync_retry:2782
20170912 165523.897 (3074458496)  (1)< MQTTAsync_cycle:3001 (-1)
20170912 165523.897 Could not find client corresponding to socket 93
20170912 165523.897 (3074458496)  (1)> MQTTAsync_cycle:2890`

**Comment by hackerick4** [comment]
@mf1564662361 Hi, I am still in the trouble. Only I can do is that stop or restart the service after too many attempt connection.

**Comment by mf1564662361** [comment]
@icraggs  @hackerick4  I have solved my issue（connect valid URI with a lot of tries and finally calls connect fail in most phones).  I recomplied source code  to SHARED lib and set 
‘LOCAL_ARM_MODE := arm’  in Android.mk file.  Now, all devices can works. I dont't know exactly reason ，maybe  incompatibility between compilers . It's too wired 😂😂   I think maybe you could reduce 'conn_opts.maxRetryInterval,  conn_opts.automaticReconnect, connect time out  ' options to avoid connection stuck.

**Comment by hackerick4** [comment]
@mf1564662361  Thanks your information. I'm a C++ developer but I will keep your suggestion in my mind and post my solution once I solve it.

**Comment by hackerick4** [comment]
Maybe I found the root cause. 
After I used TCPView from Microsoft, I found the MQ Client socket was closed at the SYN_SENT status. I guess that closing SYN_SENT socket is not really disable it but OS would handle the life cycle by self. Maybe the closed SYN_SENT socket is too many that they occupied all the usable  ports in OS.

**Comment by icraggs** [comment]
I assume that the original point of this issue is that the create call should validate the connect URI to a certain extent?   A zero length URI should be thrown out.  If you expect the call to work, use a valid URI.

The Android trace looks pretty much as expected.  I haven't used the C client on Android - the Java client is usually used for that.

**Comment by mf1564662361** [comment]
yes，It‘s more easy to use Java client ，but  jar  is  more likely to be decompiled.It's necessary to protect our  datas and source code by using so file.

**Comment by icraggs** [comment]
I'm going to close this issue.  I think it's got too wandering and confused.  I think the original problem was due to not waiting for callbacks from the connect with the result of the connect call.
