### ISSUE TITLE
fetch sock_fd for a particular client in paho

### ISSUE THREAD

**Issue by kushal4** [eclipse-paho/paho.mqtt.c#320]
Is their any api for paho where i can fetch sock fd of a particular client.If there is not could  you  please point  out a workaround in order to fetch  the socket fd of that particular client?

**Comment by icraggs** [comment]
No, there is no such API.  The risk of supplying that facility is that the application could close the socket or some other operation which invalidates its state, thus causing the library to error, and then causing a problem which we have to debug.
