### ISSUE TITLE
Cannot unsubscribe without disconnecting

### ISSUE THREAD

**Issue by vardit1988** [eclipse-paho/paho.mqtt.c#321]
Unsubscribing from a subject without disconnecting doesn't work for me.
I was trying to find some examples but could only find ones that unsubscribe and then disconnect.

I'm using the "asynchronous with SSL" library. 
I count the number of received messages and would like to unsubscribe from a topic when I reach a certain number of messages.
This is how my code looks: 

    int main()
    {
        MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	    char* address = "tcp://localhost:1883";
	
        MQTTAsync_create(&mqtt_client, address, MODULE_SHORT_NAME, 				   
                             MQTTCLIENT_PERSISTENCE_NONE, NULL);

        conn_opts.keepAliveInterval = 20;
        conn_opts.cleansession = 0;	
	
        MQTTAsync_setCallbacks(mqtt_client, mqtt_client, NULL, mqttMessageArrived, NULL);

	    conn_opts.MQTTVersion = 3;
        conn_opts.struct_version = 0;
	    conn_opts.context = mqtt_client;
	
	    if ((rc = MQTTAsync_connect(mqtt_client, &conn_opts)) != MQTTASYNC_SUCCESS)
         {
            printf("ERROR");
         }
        else
        {
             printf("MQTT Connected\n");
        }
    }

    int mqttMessageArrived(void* context, char* topic, int topic_len, MQTTAsync_message* message)
    {				
        if (received_messages > MAX_MQTT_MSG)
        {		
            MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
            opts.context = mqtt_client;
		
            int rc;
		
		if ((rc = MQTTAsync_unsubscribe(mqtt_client, topic, &opts)) != MQTTASYNC_SUCCESS)
		{
			printf("Failed to unsubscribe, return code %d\n", rc);
		}
               else
               {
                       printf("Unsubscribe was successful\n");
               }
       }

        printf("Message is: %.*s\n", (int)message->payloadlen, (char*)message->payload);			
        printf("Topic is: %s \n", topic);
        received_messages++;
	
        MQTTAsync_freeMessage(&message);
        MQTTAsync_free(topic);

        return 1;
    }

The output I get is this: 

MQTT Connected
Topic is: test/sample1
Message is: Hello from client1 msg No 0
Topic is: test/sample1
Message is: Hello from client1 msg No 1
Topic is: test/sample1
Unsubscribe was successful
Message is: Hello from client1 msg No 2
Topic is: test/sample1
Unsubscribe was successful
Message is: Hello from client1 msg No 3
Topic is: test/sample1
Unsubscribe was successful
Message is: Hello from client1 msg No 4
Topic is: test/sample1
Unsubscribe was successful

As if the unsubscribe didn't really work, even though the return value of the function is MQTTASYNC_SUCCESS

Has anyone encountered this issue? Can you please help?
Thanks!

**Comment by icraggs** [comment]
The return from MQTTAsync_unsubscribe just means that the request to unsubscribe has been successful, it does not mean that the actual operation has been so.  To work that out, you have to use and wait for the success/fail callbacks.  

Even if the unsubscribe was successful, it could take some time during which more messages are correctly received.  It depends on the frequency of the publishes received and the time taken for the unsubscribe to complete on the server.

**Comment by vardit1988** [comment]
Thank you for the answer.
Any idea how long should the unsubscription take? Is there any way to control this time?

I tried publishing 10 messages, with 3 seconds delay between the messages, and even though the subscriber side unsubscribes after receiving 3 messages, it receive all the messages, as if the unsubscription never really occured. 
I am using Moqsuitto broker and according to the log, the unsubscription request was received and was successful.

This is a part of my publisher code:

    static MQTTAsync mqtt_client;

    int main()
    {
        const char* topic_to_publish = "test/sample1";
        for (int i= 0; i< 10; i++)
        {							
            usleep(3000000L);						 
            mqttMessagePublish(topic_to_publish, QOS2, 0, 0, i, );					

            MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
            MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
            int rc;
	
            opts.onSuccess = NULL;
            opts.onFailure = NULL;
            opts.context = mqtt_client;
           
            char message[20];
            sprintf((char *)message, "Message number #%d", i);

            pubmsg.msgid = i;
            pubmsg.dup = 0;
            pubmsg.payload = message ;
            pubmsg.payloadlen = strlen(message);
            pubmsg.qos = 2;

            if ((rc = MQTTAsync_sendMessage(mqtt_client, topic, &pubmsg, &opts)) != MQTTASYNC_SUCCESS)
            {
                 printf("ERROR!\n");
            }
        }
    }

Thanks again!

**Comment by vardit1988** [comment]
After looking more into it, I see I never receive UNSUBACK. 
Now trying to figure out why.. I'll update when I have insights.

**Comment by icraggs** [comment]
The unsubscribe should work quickly unless there is an undue hold up on the server.  You can get a trace of MQTT packets sent and received by setting the environment variables:

MQTT_C_CLIENT_TRACE=ON
MQTT_C_CLIENT_TRACE_LEVEL=PROTOCOL

This should show how long the unsubscribe takes.

**Comment by icraggs** [comment]
Closing this issue in the absence of further questions.
