### ISSUE TITLE
Suppress SSL error dumping

### ISSUE THREAD

**Issue by CallumAttryde** [eclipse-paho/paho.mqtt.c#326]
It would be nice to have a macro which hides the call to ERR_print_errors_fp() in SSLSocket.c. I found that although this was useful for development debugging, in practice/production I did not want stderr to be polluted uncontrollably. An option to disable this at build time (rather than maintaining divergent patches masking functionality) would be much appreciated

**Comment by icraggs** [comment]
I didn't write this aspect of the code, and didn't realise we were writing these to stderr.  We shouldn't be doing that - it should be going to the log output destination or not at all.  I'll look into it.

**Comment by tbeu** [comment]
I also need a fix for this issue.

Can we add a new struct member `ssl_error_cb` of type `int (*cb) (const char *str, size_t len, void *u)` to the `MQTTClient_SSLOptions`, increment the `struct_version` to 3 and pass this callback function to `SSLSocket_error` to be called with `ERR_print_errors_cb`?

Remaining questions are
* What is the default behaviour if `ssl_error_cb` is `NULL`? Call `ERR_print_errors_fp` or do nothing?
* Should we also support the userdata pointer that can be passed to `ERR_print_errors_cb`? Should be straight forward by providing another application-specific context member to `MQTTClient_SSLOptions`.
* PR welcome?

**Comment by icraggs** [comment]
I was planning to just remove the call to ERR_print_errors_fp().   But adding the callback setting is a good idea.  If there is no callback, then nothing should be printed or called.  And we should add the userdata options at the same time.

A PR would be very welcome.  I hope to cut the next release in the next week or two so it'll have to be soon otherwise I'll add it myself :-)

**Comment by tbeu** [comment]
Thanks for the fast reply. Yes, I will send this PR early enough for v1.3.0.

**Comment by tbeu** [comment]
Checking the context of `SSLSocket_error`, it does not seem trivial to pass ssl error callback and context to functions `SSLSocket_getch` or `SSLSocket_continueWrite`. Would be a rather invasive change then.
