### ISSUE TITLE
Return Code to string

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#33]
migrated from Bugzilla [#460856](https://bugs.eclipse.org/bugs/show_bug.cgi?id=460856)
status ASSIGNED severity _enhancement_ in component _MQTT-C_ for _1.1_
Reported in version _1.0_ on platform _PC_
Assigned to: Ian Craggs

On 2015-02-25 15:23:39 -0500, Pierre-Luc Lacroix wrote:

> It would be nice if there would be a helper function that would convert a return code to a human readable string.
> 
> For example, here's a partial implementation:
> <code>
> const char *
> MQTTClient_returnCodeToString (int returnCode)
> {
>     static const char _mqttClient_returnCodeSuccess    []  = "MQTTCLIENT_SUCCESS";
>     static const char _mqttClient_returnCodeFailure    []  = "MQTTCLIENT_FAILURE";
>     static const char _mqttClient_returnCodeUnknown    []  = "MQTTCLIENT_UNKNOWN";
> 
> ```
> switch (returnCode) {
> case MQTTCLIENT_SUCCESS:
>     return _mqttClient_returnCodeSuccess;
> case MQTTCLIENT_FAILURE:
>     return _mqttClient_returnCodeFailure;
> default:
>     return _mqttClient_returnCodeUnknown;
> }
> ```
> 
> }
> </code>
> 
> This code sample complies with http://www.eclipse.org/legal/CoO.php

On 2015-04-24 03:29:41 -0400, Ian Craggs wrote:

> Yes, it would be nice.  Thanks.

**Comment by icraggs** [comment]
A contribution has added this feature.  Thanks!
