### ISSUE TITLE
Paho Mqtt Async apis consuming 100% cpu.

### ISSUE THREAD

**Issue by PravallikaKG** [eclipse-paho/paho.mqtt.c#330]
[mytest_app1.txt](https://github.com/eclipse/paho.mqtt.c/files/1292368/mytest_app1.txt)
[mytest_app2.txt](https://github.com/eclipse/paho.mqtt.c/files/1292369/mytest_app2.txt)

 I am using paho mqtt c async library in my project. ( 'https://github.com/eclipse/paho.mqtt.c' project, I am referring to ). In my application i subscribed to topic and will be processing the incoming messages on the topic, Since my project is embedded project, it should continuously process the incoming messages.

I have implemented mqtt client functionality in one of the thread. Problem is my application is consuming 100% cpu, whenever my mqtt thread is running.

I have attached the some similar kind of sample code in the mail whose design is same like my application. could you please help where i am doing wrong? Since i added two sample applications, in this case whenever both are running then together consumes 100% cpu? 

In some post i read that **keepAliveInterval** should be assigned with some value, then the cpu usage will reduce. But it is not happening.

Please help me how to overcome this problem?

**Comment by icraggs** [comment]
Have you tracked how often messages are being sent and received?  If it as fast as possible, that will probably consume 100% of CPU, especially if you are running the broker on the same machine as well.

It's not a good idea to sleep in a callback (message arrived).  You're not meant to hang around in them.

**Comment by PravallikaKG** [comment]
Thank you very much ICRAGGS for fast reply. Request you to please help me in resolving this issue.

My server is in another Machine.

I will brief you bit clear about my work. I am working on embedded project, wherein there is one parent device and multiple end devices. All the end devices can be controlled by user from mobile through parent device using mqtt communication. Also at the same time user receives the heartbeat state of end devices through parent device using mqtt channel. 
My Program is part of Parent device which is responsible for:
a) processing requests from user and send back the response. (SUBTOPIC, PUBTOPIC)
b) sends the heart beat of end devices to user every 5 seconds.(PUBTOPIC2)

According to point a, the communication is not so frequent, it happens only when user triggers an action.

[CodeReference.txt](https://github.com/eclipse/paho.mqtt.c/files/1294795/CodeReference.txt)

Please refer to the above code(which is same as my program) and ignore the files which are attached in previous post. 

**I also tried by commenting the MQTTAsync_sendMessage calls at all places i.e., i am not publishing data to topics(PUBTOPIC, PUBTOPIC2) also i commented the subscription part, but still the program is consuming 100%.  
Will the connection consumes the 100% cpu even though without publish and subscribe? Am i missing any parameters to set in my code which might be the reason for this issue?**

**Comment by icraggs** [comment]
One way of understanding what is happening would be to take a trace.  This is described in the debug section of the readme.

If you use the environment variable:

MQTT_C_CLIENT_TRACE=ON

this will display all trace information.  If you add

MQTT_C_CLIENT_TRACE_LEVEL=PROTOCOL

this will show the MQTT packets being sent and received, which might be what you need.  Also, if your server is Mosquitto, then it presumably logs the packets sent and received, which will be continuous if the 100% CPU is due to message traffic.

**Comment by PravallikaKG** [comment]
Thank you icraggs. I will check this and get back to you.

**Comment by PravallikaKG** [comment]
There are no packets transfer between client and server i see in the logs, so looks like this might be not the reason for 100% cpu.

**But i have done one change in the code past. Initially when i am using this library it is not working to me, i mean publish and subscribe not working, then what i did is i enabled the trace macro to see the logs. When i enabled, i saw the following are only logs printing continuously**:

20170922 161114.045 Error 22 waiting for condition variable
20170922 161114.045 Error 22 waiting for condition variable
20170922 161114.045 Error 22 waiting for condition variable
20170922 161114.045 Error 22 waiting for condition variable
20170922 161114.046 Error 22 waiting for condition variable
20170922 161114.046 Error 22 waiting for condition variable
20170922 161114.046 Error 22 waiting for condition variable
20170922 161114.046 Error 22 waiting for condition variable
20170922 161114.046 Error 22 waiting for condition variable
20170922 161114.046 Error 22 waiting for condition variable
20170922 161114.046 Error 22 waiting for condition variable
20170922 161114.046 Error 22 waiting for condition variable
20170922 161114.047 Error 22 waiting for condition variable
20170922 161114.047 Error 22 waiting for condition variable
20170922 161114.047 Error 22 waiting for condition variable
20170922 161114.047 Error 22 waiting for condition variable


So i did work around on it by commenting piece of code in reference to someone suggestion in the google. Following is the part of code in MQTTAsync.c of MQTTAsync_sendThread method is commented:

**#if !defined(WIN32) && !defined(WIN64)
		if ((rc = Thread_wait_cond(send_cond, 1)) != 0 && rc != ETIMEDOUT)
			Log(LOG_ERROR, -1, "Error %d waiting for condition variable", rc);
#else
		if ((rc = Thread_wait_sem(send_sem, 1000)) != 0 && rc != ETIMEDOUT)
			Log(LOG_ERROR, -1, "Error %d waiting for semaphore", rc);
#endif**


After this change i am able to publish and subscribe successfully.


Is this code required? Why i am getting the error continuously if this code is not commented? My code change in the code is reason for 100% cpu?

**Comment by icraggs** [comment]
We need to figure out why you were getting "Error 22 waiting for condition variable".  If you change the library code, you can't expect me to figure out what's happening, when you don't tell me that you've changed it either.  And your change could quite likely be the reason you are getting 100% CPU usage.

You should reverse that change, and take a trace which shows the situation which leads up to the "Error 22 waiting for condition variable".    You must have no changes in the library code, and tell me which version you are using.  Then I might be able to understand what is happening.

Have you tried a basic scenario, just publish perhaps, to see if you can get that working?  What operating system and hardware are you using?

**Comment by PravallikaKG** [comment]
Sorry Ian, i have not remembered about this code change. This i have done very long back in reference to someone suggestion in one forum. Now i verified all the changes with the freshly downloaded code. Only this code change and few changes in makefile(cc varaibale and dynamic libraries generation changes) there is a difference. I am using latest paho code 1.2.0. My embedded device operating system is 'Linux version 2.6.36', cpu is MIPS 7620. In my embedded device most of the libraries are stripped out to make the ubuntu image lighter.

I have identified the problem, i.e.,reason for "Error 22 waiting for condition variable". Problem is with the underlying lpthread library. I have written a small program which has call to ''pthread_cond_timedwait' api. wherein also i am getting the similar error, shown below the log:

'The value specified by abstime, cond or mutex is invalid.:EINVAL(22)'.

Looks like there is some incompatability with the underlying pthread library. 
If i execute the same program in my ubuntu PC, i am not facing this 22 or any error.   

Is there any alternate way wherein we can call, instead of 'pthread_cond_timedwait' method to resolve issue in MQTTAsync.c of MQTTAsync_sendThread method?

**Comment by fpagliughi** [comment]
It might be better to figure out WHY your system is returning this error, so that if there is an issue with the library, it can be fixed. In particular, find out what EXACTLY are the values of the `timespec` fields that are being sent to `pthread_cond_timedwait`. If that looks OK, then here are a few other things to investigate:
https://stackoverflow.com/questions/11319063/pthread-cond-timedwait-root-causes-of-einval

**Comment by PravallikaKG** [comment]
Thank you fpagliughi. I will check on this and update you.

**Comment by icraggs** [comment]
I'm going to close this for now.  Thanks,
