### ISSUE TITLE
Build is breaking on systems without C++ compiler

### ISSUE THREAD

**Issue by yegorich** [eclipse-paho/paho.mqtt.c#331]
test/CMakeLists.txt doesn't state it is a C-only project. So making this chanage fixes the issue:

diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index 5c88c44..3aca80f 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -1,4 +1,4 @@
-PROJECT(mqtt-tests)
+PROJECT(mqtt-tests C)

 IF (WIN32)
   SET(MQTT_TEST_BROKER "tcp://mqtt.iotree.co.uk:1883" CACHE STRING "Hostname of a test MQTT broker to use")

It would be also great if you could add an option to disable test building.

**Comment by icraggs** [comment]
Thanks.  I guess I don't have any systems without a C++ compiler :-)

**Comment by yegorich** [comment]
I'm using [Buildroot](https://buildroot.org/) and you can create pretty small toolchains having very minimal functionality to keep root file system as small as possible.
