### ISSUE TITLE
License choice?

### ISSUE THREAD

**Issue by pombredanne** [eclipse-paho/paho.mqtt.c#336]
When I see these notices in the code:
```
This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 ```
... does this mean BOTH license terms and conditions apply? or that I can select one license or the other?
The `and` does not make this very clear.
Thanks for the clarification!

**Comment by icraggs** [comment]
I knew this informally before, but the FAQ says that you can choose which license terms apply.

https://eclipse.org/legal/eplfaq.php#DUALLIC

**Comment by pombredanne** [comment]
@icraggs Thank you!  
@waynebeaton FYI, It could be great to beef this up: this is a case where `xxx AND yyy` really means `xxx OR yyy` hence my confusion and question. The FAQ clears this up, but IMHO it would be best to have a clearer statement that this is a choice.
