### ISSUE TITLE
Conflict between Paho and FFMPEG

### ISSUE THREAD

**Issue by AdamMiltonBarker** [eclipse-paho/paho.mqtt.c#337]
Hi guys. How do you get message-> payload to a json object? Have been able to get this into a string but not convert to json.

**Comment by AdamMiltonBarker** [comment]
Sorted it.

**Comment by AdamMiltonBarker** [comment]
Actually not able to sort this, it works sometimes and crashes others, are there any examples of extracting this payload and accessing the elements. 

This is what I have tried so far, sometimes it works fine, other times it crashes:

```
int msgarrvd(void *context, char *topicName, int topicLen, MQTTAsync_message *message)
{
	int i;
	const char* payloadptr;

	payloadptr = (const char*)message->payload;
	std::cout << payloadptr;
	std::vector<std::string> v = explode("/", topicName);
	std::string s(payloadptr);
	std::cout << s;
	json data = json::parse(s+'\n');
	std::cout << data["Command"];

	if (v[4]=="Commands") {

	}
	 
	MQTTAsync_freeMessage(&message);
	MQTTAsync_free(topicName);
	return 1;
}
```

https://github.com/nlohmann/json/issues/752

**Comment by AdamMiltonBarker** [comment]
Have worked out somewhere along the way, in Paho only, characters are being added to the message such as et.c is somehow being added to the end of message->payload

**Comment by AdamMiltonBarker** [comment]
:O It is coming from the output of FFMPEG I disabled it and it works everytime, no idea how that is possible.  Do you know of a reason why FFMPEG output would be mixing with message->payload, this is what is crashing it.

**Comment by AdamMiltonBarker** [comment]
:O It is coming from the output of FFMPEG I disabled it and it works everytime, no idea how that is possible. Do you know of a reason why FFMPEG output would be mixing with message->payload, this is what is crashing it.

I have removed the output of FFMPEG but it is still crashing, there is some sort of conflict between paho and FFMPEG, FFMPEG is activated in a pipe in this program.

If I disable this, the error does not happen:

`pPipe = _popen(" ffmpeg -loglevel quiet -loop 1 -f image2pipe -i - -framerate 25 -vcodec mpeg4 -f mpegts -codec:v mpeg1video -s 640x480 -b:v 1000k -bf 0 http://127.0.0.1:XXXX", "wb");`

UPDATE: No it has just happened with it disabled, this is getting annoying lol

**Comment by AdamMiltonBarker** [comment]
These are values that are making crash:

`{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}"Capture"{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}X#�╖º3êêêê─╧ûF�{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}X#�╖º3êêêê─╧ûF�`

`{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}etOut.êêêêc�å(��{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}etOut.êêêêc�å(��`

Data is correctly going through the broker, these characters are only being received in Paho C, I use Paho  JS for one client and it does not receive this, and the broker is receiving and storing data correctly, any ideas what can be causing this please guys?

**Comment by icraggs** [comment]
The payload member of MQTTAsync_message points to binary data, which is not a null-terminated C string.  The length of the data is in payloadlen.

**Comment by AdamMiltonBarker** [comment]
Thanks for the reply, this was really annoying me but it wasnt issue with either libraries, it was me lol. Solved with:

```
int msgarrvd(void *context, char *topicName, int topicLen, MQTTAsync_message *message)
{
	int i;
	char* payloadptr;

	payloadptr = (char*)message->payload;
	std::cout << payloadptr;
	std::string s = "";
	for (i = 0; i<message->payloadlen; i++)
	{
		s = s + *payloadptr++;
	}
	s = s + '\n';

	std::vector<std::string> v = explode("/", topicName);
	std::cout << s;
	json data = json::parse(s);
	std::cout << data["Command"];

	if (v[4]=="Commands") {

	}
	 
	MQTTAsync_freeMessage(&message);
	MQTTAsync_free(topicName);
	return 1;
}
```
