### ISSUE TITLE
Failover protocal cannot work 

### ISSUE THREAD

**Issue by hackerick4** [eclipse-paho/paho.mqtt.c#338]
`MQTTAsync_create(&client, "Failover:(tcp://192.168.122.168:1883)", CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);`

The above code is my sample that cannot link to broker 192.168.122.168. 

`MQTTAsync_create(&client, tcp://192.168.122.168:1883", CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);`

That's can work. Is there any mistake I did ?

**Comment by icraggs** [comment]
I'm not sure how you're expecting failover to work, but the way it's intended to work is by use of the serverURIs member of the connectOptions structure:

http://www.eclipse.org/paho/files/mqttdoc/MQTTAsync/html/struct_m_q_t_t_async__connect_options.html#aba22d81c407fb2ba590dba476240d3e9

**Comment by icraggs** [comment]
I'm going to close this issue as there has been no follow up.
