### ISSUE TITLE
MQTTAsync.c persistance bug

### ISSUE THREAD

**Issue by mbutaru** [eclipse-paho/paho.mqtt.c#339]
Hi,

I just noticed the MQTTAsync client crashes here:
file MQTTAsync.c line 1782 (`NO_PERSISTENCE` not defined)
`if (rc)`
`{`
`ListRemove(m->c->messageQueue, qe);`
`#if !defined(NO_PERSISTENCE)`
		`if (m->c->persistence)`
			`MQTTPersistence_unpersistQueueEntry(m->c, (MQTTPersistence_qEntry*)qe);`
`#endif`
`}`

It seems that the object called 'qe' gets deallocated then used in the persistence block.

Thanks,
Mihai

**Comment by icraggs** [comment]
Thanks, I will fix it soon.
