### ISSUE TITLE
Paho last will & testament doesn't support binary payloads

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#34]
migrated from Bugzilla [#461411](https://bugs.eclipse.org/bugs/show_bug.cgi?id=461411)
status ASSIGNED severity _normal_ in component _MQTT-C_ for _1.1_
Reported in version _1.1_ on platform _Other_
Assigned to: Ian Craggs

On 2015-03-04 11:02:43 -0500, Michael Smosna wrote:

> When publishing a message using MQTTAsync_sendMessage(), the third parameter of type MQTTAsync_message contains fields for specifying the payload (as void *) and payloadlen (as int) which allows a binary payload to be sent.
> 
> When creating a session, there is the option of specifying a last will and testament.  When populating the MQTTAsync_willOptions struct, only a 'const char *message' parameter is available for specifying the payload.  Since there is no message length parameter, I assumed that 'message' could only be a text string.  I tested this by first setting message to the string 'LOST_CONNECTION'.  I non-gracefully disconnected from the central broker (in this case I'm using mosquitto) and shortly after received 15 bytes as the LW&T message.  I then set 'message' to {0x30,0x31,0x32,0x33,0x34,0x0,0x35,0x36,0x0} and repeated the same test.  The LW&T message came through with 5 bytes.
> 
> Our use case involves publishing binary payloads to topics and is also needed for the LW&T message.  Is it possible to expand the MQTTAsync_willOptions structure to include a message length parameter and allow for binary payloads?

On 2015-04-20 11:51:57 -0400, Ian Craggs wrote:

> Hi.  Yes, it is possible.  A new version of the willOptions structure will be needed.  (I updated the component for this bug because this is not about the embedded client).

**Comment by icraggs** [comment]
Update added to the develop branch, for release in June.
