### ISSUE TITLE
Shared library calls exit

### ISSUE THREAD

**Issue by orpiske** [eclipse-paho/paho.mqtt.c#342]
This is related to the work I am doing for #315. One of the reviewers pointed that the libraries might be calling exit. 

The snippet from the package build warning is provided below:

> paho-c.x86_64: W: shared-lib-calls-exit /usr/lib64/libpaho-mqtt3a.so.1.2.0 exit@GLIBC_2.2.5
> paho-c.x86_64: W: shared-lib-calls-exit /usr/lib64/libpaho-mqtt3as.so.1.2.0 exit@GLIBC_2.2.5
> paho-c.x86_64: W: shared-lib-calls-exit /usr/lib64/libpaho-mqtt3c.so.1.2.0 exit@GLIBC_2.2.5
> paho-c.x86_64: W: shared-lib-calls-exit /usr/lib64/libpaho-mqtt3cs.so.1.2.0 exit@GLIBC_2.2.5
> shared-lib-calls-exit:
> This library package calls exit() or _exit(), probably in a non-fork()
> context. Doing so from a library is strongly discouraged - when a library
> function calls exit(), it prevents the calling program from handling the
> error, reporting it to the user, closing files properly, and cleaning up any
> state that the program has. It is preferred for the library to return an
> actual error code and let the calling program decide how to handle the
> situation.

**Comment by icraggs** [comment]
It was in some old code, left over from testing.

**Comment by orpiske** [comment]
Thanks @icraggs!
