### ISSUE TITLE
Create man pages for Paho MQTT C binaries/API

### ISSUE THREAD

**Issue by orpiske** [eclipse-paho/paho.mqtt.c#346]
One of the suggestions that were received during submission for inclusion in Fedora (tracked on #315) was to generate the man pages for the binaries. While reviewing the documentation code, I noticed that we also don't automatically generate the man pages for the API as well. 

Therefore, I am opening this issue/enhancement request to track that and provide a proposed patch for future review.

**Comment by icraggs** [comment]
Are there best practices or advice that could be followed about the content?

**Comment by orpiske** [comment]
As far as I know, there are no written guidelines about it. 

However, out of curiosity, I did a brief research to see if I could find some pointers. One text (that came as a reference from [here](https://stackoverflow.com/questions/779975/best-practices-to-put-into-a-man-page)) pointed to [this](http://www.schweikhardt.net/man_page_howto.html) article, which seems to give some insights on the subject of man page writing.

In a much wider sense, though, I like some of the documentation insights from Carolyn Stransky's talk [Humanizing Your Documentation](https://www.youtube.com/watch?v=FvPXMUuUCS4) can provide some interesting ideas for the content as well.

That said, I think it might be enough to give a glance of the CLI tools provided. IMHO, documenting the API might be a bit overkill if it's not automated, since the documentation is already available online.

**Comment by icraggs** [comment]
I've added man pages for the main utilities in doc/man/man1.  I haven't done anything about installing them yet.  I've also updated the Doxygen config files so that man pages for the API are generated.  I haven't finished updating the Doxygen doc details yet.

**Comment by orpiske** [comment]
@icraggs thanks! I will make sure the man pages are added on the next version of the package.

**Comment by icraggs** [comment]
You don't need me to add them to the Makefile or CMake build?

**Comment by orpiske** [comment]
Oh, you can add them to the CMake build. When packaging, I will ensure that they get installed on the right location on Fedora/CentOS. This may be distribution-specific, so, I think we are fine with the defaults you set.

**Comment by icraggs** [comment]
I've added them to the Makefile first for now.  They get installed to the standard man locations.  I'll look into the the CMake config next at some point.
