### ISSUE TITLE
Use system-wide crypto policies

### ISSUE THREAD

**Issue by orpiske** [eclipse-paho/paho.mqtt.c#347]
This is another suggestion raised for the submission to Fedora (tracked on #315). One of the packaging policies calls for packages to allow a [system-wide crypto policy](https://fedoraproject.org/wiki/Packaging:CryptoPolicies).

I opened this ticket/enhancement request in order to discuss this enhancement/request.

**Comment by icraggs** [comment]
I tried using PROFILE=SYSTEM as the default, but that resulted in errors on my Mac.  So I took the other option of removing the default call to set_cipher_list entirely.

**Comment by icraggs** [comment]
Assuming this is good, I'm going to close it.

**Comment by orpiske** [comment]
Thanks for taking a look at this, @icraggs!
