### ISSUE TITLE
Macro redefinition (socket.h) in windows10x64

### ISSUE THREAD

**Issue by dontsovcmc** [eclipse-paho/paho.mqtt.c#348]
I found the bug. 
No problem with functions and open non blocking connection.

The problem in incorrect defines in socket.h:
```
2>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\errno.h(43): warning C4005: 'EINTR' : macro redefinition
2>          d:\code\paho.mqtt.c_fork\paho.mqtt.c\src\Socket.h(31) : see previous definition of 'EINTR'
2>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\errno.h(50): warning C4005: 'EAGAIN' : macro redefinition
2>          d:\code\paho.mqtt.c_fork\paho.mqtt.c\src\Socket.h(29) : see previous definition of 'EAGAIN'
2>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\errno.h(100): warning C4005: 'ECONNRESET' : macro redefinition
2>          d:\code\paho.mqtt.c_fork\paho.mqtt.c\src\Socket.h(39) : see previous definition of 'ECONNRESET'
2>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\errno.h(104): warning C4005: 'EINPROGRESS' : macro redefinition
2>          d:\code\paho.mqtt.c_fork\paho.mqtt.c\src\Socket.h(33) : see previous definition of 'EINPROGRESS'
2>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\errno.h(118): warning C4005: 'ENOTCONN' : macro redefinition
2>          d:\code\paho.mqtt.c_fork\paho.mqtt.c\src\Socket.h(37) : see previous definition of 'ENOTCONN'
2>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\errno.h(130): warning C4005: 'ETIMEDOUT' : macro redefinition
2>          d:\code\paho.mqtt.c_fork\paho.mqtt.c\src\Socket.h(41) : see previous definition of 'ETIMEDOUT'
2>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\errno.h(132): warning C4005: 'EWOULDBLOCK' : macro redefinition
2>          d:\code\paho.mqtt.c_fork\paho.mqtt.c\src\Socket.h(35) : see previous definition of 'EWOULDBLOCK'
```
"who read warnings..." :(

"socket.h" included firstly, after it VisualStudio includes "errno.h" and redefines your constants :(

link: https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms737828(v=vs.85).aspx

**Comment by icraggs** [comment]
These definitions were originally included because errno.h did not exist on Windows, so defined some of my own to try to minimize #ifdef sections in the main code.  Are these errors because errno.h is defined in later versions of Windows/Visual Studio?

**Comment by dontsovcmc** [comment]
I have rather old Visual Studio 2013.
Look at my errno.h file:
[errno.h.txt](https://github.com/eclipse/paho.mqtt.c/files/1430402/errno.h.txt)
it's the same in Win10, Win7

As I see in https://stackoverflow.com/questions/42777424/visual-studio-2017-errors-on-standard-headers and https://msdn.microsoft.com/en-us/library/5814770t.aspx (click 'other versions') there is no  errno.h file in VS2017.

**Comment by icraggs** [comment]
The AppVeyor builds such as https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c/build/1.2.118 work without changes, using Visual Studio 14.  I'm not sure what version of Windows is being used.

**Comment by dontsovcmc** [comment]
Another reason maybe different order of include paths? 
I can't compile mqtt with -G "NMake Makefiles" on my PC: https://github.com/eclipse/paho.mqtt.c/issues/353

**Comment by dontsovcmc** [comment]
I compiled mqtt with NMake correctly. Maybe this problem only if VS selected. I think we can close it. Somebody found solution if needed.

**Comment by dontsovcmc** [comment]
The previous info about NMake isn't correctly, sorry. There are same errors with NMake.
So, I create pull request for VS less than 2015. https://github.com/eclipse/paho.mqtt.c/pull/359

**Comment by icraggs** [comment]
So... the changes to Socket.c in a PR that caused the build to fail on older versions of Visual Studio have been reversed - see #367.  The build should now work for you as I've merged those changes in.

I'll consider adding new AppVeyor builds using different versions of Visual Studio.

**Comment by icraggs** [comment]
I think that this is resolved.  I've opened an issue for adding an AppVeyor build #389 for an older version of Visual Studio.
