### ISSUE TITLE
Connection timeout issue

### ISSUE THREAD

**Issue by botsutoshi** [eclipse-paho/paho.mqtt.c#358]
I'm working on several platforms (Linux, Win...) and I found the behavior while debugging with Windows 10.
Paho version is 1.2 with vs120.

So, I'm checking my application execution flow during a connection to a not existing broker.
The broker is locally defined (RSMB by IBM, address 127.0.0.1):

- if available, Paho client correctly connects
- otherwise, application hangs

While debugging I found this working configuration:

1. `MQTTClient_connectURI(...)` started
2. `start` variable set to current timestamp
3. first call to `MQTTClient_connectURIVersion(...)`
4. second call to `MQTTClient_connectURIVersion(...)` due to 3) error
<no more control>

Within the `MQTTClient_connectURIVersion` there is a time elapsed calculation (`MQTTClient_elapsed` function calls).
`MQTTClient_waitfor(...)` with timeout parameter set to `millisecsTimeout - MQTTClient_elapsed(start)` calls `Thread_wait_sem(sem, timeout)` that calls `WaitForSingleObject(sem, timeout)`.

**OK, probably here we have the issue.**

After point 3) execution, `millisecondsTimeout - MQTTClient_elapsed(start)` produces a negative number.
This result applied to `WaitForSingleObject(...)` API causes an almost infinite waiting effect.

Probably it's enougt to check for positive numbers within the `Thread_wait_sem(...)` implementation.
I temporarly solved in this way:

```
int Thread_wait_sem(sem_type sem, int timeout)
{
  /* sem_timedwait is the obvious call to use, but seemed not to work on the Viper,
   * so I've used trywait in a loop instead. Ian Craggs 23/7/2010
   */
  int rc = -1;

  if (timeout >= 0)
  {
#if !defined(WIN32) && !defined(WIN64) && !defined(OSX)
#define USE_TRYWAIT
#if defined(USE_TRYWAIT)
    int i = 0;
    int interval = 10000; /* 10000 microseconds: 10 milliseconds */
    int count = (1000 * timeout) / interval; /* how many intervals in timeout period */
#else
    struct timespec ts;
#endif
#endif

    FUNC_ENTRY;
#if defined(WIN32) || defined(WIN64)
    rc = WaitForSingleObject(sem, timeout);
#elif defined(OSX)
    rc = (int)dispatch_semaphore_wait(sem, dispatch_time(DISPATCH_TIME_NOW, (int64_t)timeout * 1000000L));
#elif defined(USE_TRYWAIT)
    while (++i < count && (rc = sem_trywait(sem)) != 0)
    {
      if (rc == -1 && ((rc = errno) != EAGAIN))
      {
        rc = 0;
        break;
      }
      usleep(interval); /* microseconds - .1 of a second */
    }
#else
    if (clock_gettime(CLOCK_REALTIME, &ts) != -1)
    {
      ts.tv_sec += timeout;
      rc = sem_timedwait(sem, &ts);
    }
#endif
  }

  FUNC_EXIT_RC(rc);
  return rc;
}
```

**Comment by icraggs** [comment]
Ok, thanks.  I'll look into it.

**Comment by botsutoshi** [comment]
In addition, I found my workaround causes other problems related to synchronizations (I haven't spent time in other investigations, sorry).

What it seems to work properly is normalizing the timeout parameter value, if negative:
```
int Thread_wait_sem(sem_type sem, int timeout)
{
/* sem_timedwait is the obvious call to use, but seemed not to work on the Viper,
 * so I've used trywait in a loop instead. Ian Craggs 23/7/2010
 */
	int rc = -1;

  timeout = timeout < 0 ? -(timeout) : timeout;

#if !defined(WIN32) && !defined(WIN64) && !defined(OSX)
#define USE_TRYWAIT
#if defined(USE_TRYWAIT)
	int i = 0;
	int interval = 10000; /* 10000 microseconds: 10 milliseconds */
	int count = (1000 * timeout) / interval; /* how many intervals in timeout period */
#else
	struct timespec ts;
#endif
#endif

	FUNC_ENTRY;
	#if defined(WIN32) || defined(WIN64)
		rc = WaitForSingleObject(sem, timeout);
  #elif defined(OSX)
		rc = (int)dispatch_semaphore_wait(sem, dispatch_time(DISPATCH_TIME_NOW, (int64_t)timeout*1000000L));
	#elif defined(USE_TRYWAIT)
		while (++i < count && (rc = sem_trywait(sem)) != 0)
		{
			if (rc == -1 && ((rc = errno) != EAGAIN))
			{
				rc = 0;
				break;
			}
			usleep(interval); /* microseconds - .1 of a second */
		}
	#else
		if (clock_gettime(CLOCK_REALTIME, &ts) != -1)
		{
			ts.tv_sec += timeout;
			rc = sem_timedwait(sem, &ts);
		}
	#endif

 	FUNC_EXIT_RC(rc);
 	return rc;
}
```

I know this implementation doesn't honor the connection timeout (in general for a couple of seconds), but it works better than previous solution.

**Comment by ubyyj** [comment]
I encountered the same issue on Windows, and propose a fix here  https://github.com/eclipse/paho.mqtt.c/pull/380/commits/b3e2930a04fdeb7c567721caa4c845044de4b77c

**Comment by fwinkelbauer** [comment]
I can reproduce this issue on my Windows machine as well using either v1.1 or v1.2:

If no mqtt broker is online, a call to `connect()` will block indefinitely only if the "message received" callback for the MQTTClient is set. A timeout will occur if this callback is set to `NULL`.

Blocking connect (using code parts found [here](https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/subasync.html)):

```c
MQTTClient_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);
conn_opts.keepAliveInterval = 20;
conn_opts.connectTimeout = 3; // does not change anything
conn_opts.cleansession = 1;

MQTTClient_setCallbacks(client, NULL, connlost, msgarrvd, delivered);
MQTTClient_connect(client, &conn_opts);
```

**None**-blocking call:

```c
MQTTClient_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);
conn_opts.keepAliveInterval = 20;
conn_opts.connectTimeout = 3; // works as expected
conn_opts.cleansession = 1;

// setting msgarrvd to NULL
MQTTClient_setCallbacks(client, NULL, connlost, NULL, delivered);
MQTTClient_connect(client, &conn_opts);
```

**Comment by icraggs** [comment]
I've merged #380 into the develop branch, which may help - I didn't meet the issue in my test so far.

**Comment by fwinkelbauer** [comment]
Just dropping by to confirm that this code change fixes the blocking problems in my application. Thanks!

**Comment by icraggs** [comment]
Great, thanks!
