### ISSUE TITLE
Cppcheck static code analyzer complains on Paho MQTT-C...

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#36]
migrated from Bugzilla [#462753](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462753)
status UNCONFIRMED severity _normal_ in component _MQTT-C_ for _1.1_
Reported in version _1.0_ on platform _All_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[patchset_v1.tar.bz2](https://bugs.eclipse.org/bugs//attachment.cgi?id=251803)_ (ID 251803)

On 2015-03-21 06:26:04 -0400, Lionel Debroux wrote:

> Created attachment 251803
> Patches fixing several cppcheck complaints and performing several other janitorial changes
> 
> Recently, I ran cppcheck on the code base of another project which embeds Paho MQTT-C (an outdated copy thereof, but that's another story), and it found several low-impact things to rightfully complain about. Analyzing HEAD upstream version finds the same issues.
> 
> So here are a couple patches:
> - the first one fixes the complaints of highest severity, and makes several nearby changes while at it (one of them related to bug # 444229: checking the return value of malloc);
> - the second one uses angle brackets for including system headers, as is usually recommended, and for consistency with most other files in the MQTT-C code base. Noticed when using cppcheck --check-config.
> 
> Note that cppcheck also produces dozens of lower-level notes, such as dead assignments, variables whose scopes can be reduced, etc.
> 
> That's clearly a tiny contribution, but integrating (some of) these changes will avoid someone else having to reinvent them later :)

**Comment by icraggs** [comment]
Changes made.  Thanks.
