### ISSUE TITLE
log mqtt paho trace  in a custom file 

### ISSUE THREAD

**Issue by kushal4** [eclipse-paho/paho.mqtt.c#361]
Hi,
I am setting environment variables in order to see the paho mqtt packet trace on the command line itself.
But now,i want to log these packet traces in a custom file for later references.Is there any api calls or facility given in paho  in order to do this ?
Thanks,
Kushal

**Comment by icraggs** [comment]
The environment variable MQTT_C_CLIENT_TRACE takes a value of ON (which writes to stdout) or a filename, to write to a file.  You can also redirect stdout to a file, of course.

**Comment by kushal4** [comment]
ok thanks :)
