### ISSUE TITLE
Subscribe after connect

### ISSUE THREAD

**Issue by croja** [eclipse-paho/paho.mqtt.c#363]
I use async API of paho.mqtt.c library in my application. 

I want to know when client is connected to perform my subscriptions, so I specify callback in connect options. In this callback I call MQTTAsync_subscribe() on desired topics. 
However, this cause to deadlock. MQTTAsync_receiveThread execute my callback with locked mutex, and MQTTAsync_subscribe() tries to lock the same mutex again.

I tried to convert this:
`(*(m->connect.onSuccess))(m->connect.context, &data);`
to this:
`MQTTAsync_unlock_mutex(mqttasync_mutex);`
`(*(m->connect.onSuccess))(m->connect.context, &data);`
`MQTTAsync_lock_mutex(mqttasync_mutex);`

and deadlock dissapeared.

Are there any reasons why user callbacks must be called under lock? Maybe it is wrong to perform subscriptions from user callbacks (without starting new thread)? How to act in this case?

Thank you

**Comment by icraggs** [comment]
The MQTTAsync_subscribe.c sample does exactly this scenario.  How is yours different?

**Comment by croja** [comment]
Thank you for response. Now I saw difference and realize that I was wrong: it was not MQTTAsync_subscribe(), but MQTTAsync_isConnected().
If I add this call to MQTTAsync_subscribe.c sample it deadlocks too.

My wrapper function (that invokes MQTTAsync_subscribe()) may be called not only from "successful-connection" callback, so I hoped I can check if client is connected.

**Comment by icraggs** [comment]
Ok.  So the problem is "calling MQTTAsync_isConnected() in the callback causes deadlock"?

I'm not sure I expected isConnected() to be called in a callback, as the callback generally indicates the state of the connection - isConnected() or connectionLost(), for example.
