### ISSUE TITLE
Can't build code with C++, missing underscores in MQTTAsync.h

### ISSUE THREAD

**Issue by gkiryaziev** [eclipse-paho/paho.mqtt.c#368]
hi, VS2015 can't build my C++ code, and I found missing underscores here

https://github.com/eclipse/paho.mqtt.c/blob/master/src/MQTTAsync.h#L95

have to be 

`#if defined(_WIN32) || defined(_WIN64)`

and I think MQTTClient.h have this problem too

https://github.com/eclipse/paho.mqtt.c/blob/master/src/MQTTClient.h#L112

VC2015 don't recognize Windows

**Comment by icraggs** [comment]
This code has been building in various versions of Visual Studio for 10 years or more, without those definitions being changed.  I don't think it's the source of your problems.

How are you building the code?  Are you using CMake to generate the Visual Studio project?

**Comment by icraggs** [comment]
I've just built the code unchanged with Visual Studio 2015, using the cbuild.bat script (using CMake).

**Comment by gkiryaziev** [comment]
Hi, I am using CMake for C and C++ libraries and then successfully build them in VS2015 x64, I have no problem with libraries building, I have a problem then when I use the C++ library in my project, because I have to include MQTTAsync.h in the project and then VS2015 does not detect Windows.

here you can see how VS2015 selects `else` section without underscores

![2017-11-18_153207](https://user-images.githubusercontent.com/8873218/32980813-2c691a60-cc76-11e7-86ce-f30d3ff8c614.png)

![2017-11-18_153234](https://user-images.githubusercontent.com/8873218/32980848-a65ffd84-cc76-11e7-9668-64be8f1e7fe0.png)

and finally with underscores my code was built successfully

**Comment by icraggs** [comment]
The CMake build includes test programs and sample applications too.  I'm not sure what you mean by the C++ library - is that the separate Paho C++ client library?

You could just add the WIN32 definition, if it isn't defined already.

**Comment by gkiryaziev** [comment]
I am using [MQTT C++ Client for Posix and Windows](https://www.eclipse.org/paho/clients/cpp/) and it requires the [Paho MQTT C client library](https://www.eclipse.org/paho/clients/c).

Yes, I can add the `WIN32` or `WIN64` definition, before `#include` in my code, like this:

`#ifndef WIN64`
`#define WIN64`
`#endif`

`#include <iostream>`
`#include "mqtt\client.h"`

apparently this is the fastest trick. Thank you.

**Comment by fpagliughi** [comment]
If there’s a problem building the Paho C++ library, please raise an issue on the C++ Github page as well, in case I might be able to fix it there.
https://github.com/eclipse/paho.mqtt.cpp/issues

**Comment by gkiryaziev** [comment]
No, it is not a problem of C++ client, problem is in `MQTTAsync.h` file which is part of C library and used in the project as dependency because MQTT C++ Client requires the Paho MQTT C client library. The problem I described above, VS2015 does not find `#define WIN32` or `WIN64` without underscores, like `_WIN32`, `_WIN64`, and the quickest way to solve the problem is to specify `#define WIN32` or `WIN64` in your code. Thanks.

**Comment by Strob0t** [comment]
THIS!
@icraggs you schould to point out that problem in an FAQ or anything if someone had such a problem. I had the same problem with the missing underscore before the `_WIN32` and it cost me a lot of time to find out the error for that damn much copiler errors.

**Comment by fpagliughi** [comment]
Agreed. But stay nice.

I don't know if or when Microsoft changed things, but it seems that now we want/need the underscore. The docs for VS2015, 2017, and 20199 don't event list WIN32 as a supported macro, without the underscore:
https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019

The Rust client doesn't build for Windows unless we manually define WIN32:
https://github.com/eclipse/paho.mqtt.rust/pull/54

So  it's probably worth changing this now. I'll throw up a PR shortly.

**Comment by icraggs** [comment]
So I'm not sure why the CMake/AppVeyor builds have never stopped working then.  I don't see an explicit definition of WIN32, although I could have overlooked it.

**Comment by fpagliughi** [comment]
My understanding is that _WIN32 is defined by the compiler itself whereas WIN32 may (or may not) be defined by the build system. And that things were different in the past. 

So these days it appears to be safer to use _WIN32 and _WIN64.
