### ISSUE TITLE
not working on openwrt

### ISSUE THREAD

**Issue by appkisstronics** [eclipse-paho/paho.mqtt.c#369]
compiled the src code with toolchain OpenWrt-SDK-15.05.1-ar7-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.

I have made simple application and paho mqtt c src included in my application. I have compiled and tested the same on x86 Linux. and armhf Linux. 
But, Same is not working on openwrt ( 15.05.0 ) on ar7 based target.  
Any known issues then please do let me know.

**Comment by icraggs** [comment]
It is always more helpful to say how the application is not working, rather than just "it's not working".

In this case, you may need to add the REVERSED compiler definition to change the ordering of bitfields in the MQTT header, due to the architecture of that particular target.

**Comment by appkisstronics** [comment]
Okay, I will check it. 
Here what I have observed is..
In Socket.c file there is method  Socket_new.
When I call the MQTTClient_connect wth options. everything goes well but, Socket_new Method returns -1.
sin_family  is AF_INET
when it reaches to **connect()** api with in Socket_new method it return -1. 
I have tested connect api with same parameters in other code and is working fine. 

Please help me how to do this REVERSED bitfields in header if possible.

**Comment by icraggs** [comment]
REVERSED is a compile definition: add -DREVERSED to your gcc command.

It doesn't sound like this is your problem.  To help diagnose, take a trace by setting the environment variable MQTT_C_CLIENT_TRACE=ON

**Comment by appkisstronics** [comment]
sorry for my late reply!!!
-DREVERSED option working. 
Its not a bug. Its my mistake that I missed this compiler option for my target architecure.
