### ISSUE TITLE
Create pahopub and pahosub from stdinpub and stdoutsub

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#37]
migrated from Bugzilla [#442034](https://bugs.eclipse.org/bugs/show_bug.cgi?id=442034)
status NEW severity _normal_ in component _MQTT-C_ for _1.1_
Reported in version _v0.5_ on platform _PC_
Assigned to: Ian Craggs

On 2014-08-19 06:10:11 -0400, Ian Craggs wrote:

> The sample programs stdinpub and stdoutsub are actually very useful.
> 
> They should be renamed to pahopub and pahosub and SSL enabled.  Then they should be part of the Makefile as utility programs which get installed along with the libraries.

On 2014-08-28 10:59:33 -0400, Ian Craggs wrote:

> Assigning to Rong.

On 2015-01-16 06:45:38 -0500, Ian Craggs wrote:

> Taking back.

On 2015-02-09 06:15:09 -0500, Ian Craggs wrote:

> Adding helpwanted flag

On 2015-02-09 06:16:06 -0500, Ian Craggs wrote:

> Also resetting to NEW

On 2015-02-15 09:07:15 -0500, Bernard Opic wrote:

> Do you simply target [SAMPLE_FILES_C = stdinpub stdoutsub pubsync pubasync subasync], or also [SAMPLE_FILES_A = stdoutsuba MQTTAsync_subscribe MQTTAsync_publish]?

On 2015-03-02 08:53:48 -0500, Ian Craggs wrote:

> It would be nice to have both sets, synchronous and asynchronous. :-)

**Comment by icraggs** [comment]
They probably should be called paho_c_sub and paho_c_pub.  And maybe paho_ca_pub and paho_ca_sub for asynchronous.  People using them as utilities won't care about the variants, but for test purposes, all are useful.

**Comment by icraggs** [comment]
Names changed in develop.
