### ISSUE TITLE
Sending of PINREQ after DISCONNECT

### ISSUE THREAD

**Issue by kushal4** [eclipse-paho/paho.mqtt.c#371]
Is it valid that after DISCONNECT packet is sent from paho ,PINGREQ may be sent from the client ?Am just confused in this part.
Thanks

**Comment by icraggs** [comment]
PINGREQ should not be sent after DISCONNECT.  The connection should be terminated after DISCONNECT is sent.

**Comment by kushal4** [comment]
ok thanks :)
