### ISSUE TITLE
failed to connect, return code -1

### ISSUE THREAD

**Issue by helo-ch** [eclipse-paho/paho.mqtt.c#375]
Hi,

I am trying to use the MQTT protocol with the paho.mqtt.c library. My goal was to subscribe to a topic from a computer while the MQTT server is running on another computer. The two computers are on the same network and I can ping one from the other, but when I run my subscriber code I get a `failed to connect, return code -1` error. The address I'm trying to connect to is `"tcp://[IP adress of the computer on which the MQTT server is running]:1883"`

Not sure what this error is about, any help would be appreciated.

**Comment by icraggs** [comment]
Well, you haven't given enough information to determine what is happening.  "Can you run the server and the client on the same machine and get a successful connection?" is one question you could ask.

Taking a trace by setting the environment variable MQTT_C_CLIENT_TRACE=ON might help, but it could also be much simpler than that.

**Comment by helo-ch** [comment]
Sorry, I was in a hurry, but I actually don't know what more information I could add. I know it is possible to run the server and the client on the same machine because this is what I have been doing so far, now what I am trying to do is to run them on different machines.

The MQTT broker is RabbitMQ, with the MQTT plugin enabled.

**Comment by icraggs** [comment]
If that's the case you'll first need to ensure that the machine running the server hasn't got a firewall blocking port incoming connections on 1883.

**Comment by icraggs** [comment]
I'm going to close this for now.  If you have new information, you can reopen.
