### ISSUE TITLE
Return code -8 when connect to broker using version v1.2

### ISSUE THREAD

**Issue by abbarace** [eclipse-paho/paho.mqtt.c#376]
Use makefile to compile v1.2 source in linux system.
And i try paho_c_sub sample code to test async connection, but always return -8 when do async connection.
But when i change struct_version to 4(default is 5), i fix this problem.
I don't know why?

**Comment by icraggs** [comment]
I just tried it and it works for me (on a Mac).  Is an older version of the paho shared library installed on your system?

**Comment by abbarace** [comment]
Thanks for your reply. I will check it out！

**Comment by abbarace** [comment]
Hi icraggs,
Just as you say,  It link to older version lib to cause this fault. Thank you very march to resolve my problem!
