### ISSUE TITLE
sleep() in fast path (publish) when QoS>0 (MQTTClient)

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#38]
migrated from Bugzilla [#460853](https://bugs.eclipse.org/bugs/show_bug.cgi?id=460853)
status UNCONFIRMED severity _normal_ in component _MQTT-C_ for _1.1_
Reported in version _1.0_ on platform _PC_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[0001-Smaller-sleep-in-MQTTClient_yield.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=251109)_ (ID 251109)
- _[0002-Faster-publish-when-QoS-0.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=251110)_ (ID 251110)

On 2015-02-25 14:32:31 -0500, Pierre-Luc Lacroix wrote:

> Sample code:
> <code>
> MQTTClient_publishMessage(client, "topic", &pubmsg, &token);
> MQTTClient_waitForCompletion(client, token, 10000L);
> </code>
> 
> The code will be limited to sending ~10 messages/second when using QoS>0 because of a 100ms sleep in the MQTTClient_yield() function.
> 
> I have a simple (naive) fix that pushes the theoretical maximum sending rate to 100k messages/second. I could implement a better fix but I figured this was a good first step.
> 
> Here's my implementation of the fix on my git fork:
> https://github.com/pl89/paho.mqtt.c/commit/SHA: b16df7337c364e90b34edbd6d6ea9a67393bd74a
> https://github.com/pl89/paho.mqtt.c/commit/SHA: ee29fb8584c17d50abad711ce4bceef1d0907d4a

On 2015-02-25 15:05:29 -0500, Pierre-Luc Lacroix wrote:

> Created attachment 251109
> Lower the sleep() length in MQTTClient_yield() method.
> 
> Attaching patches to bug.
> 
> This contribution complies with http://www.eclipse.org/legal/CoO.php

On 2015-02-25 15:07:18 -0500, Pierre-Luc Lacroix wrote:

> Created attachment 251110
> Fix compile warning, further improve fast path by using modified version of MQTTClient_yield().
> 
> This contribution complies with http://www.eclipse.org/legal/CoO.php

**Comment by icraggs** [comment]
I'll add a change to help this under issue #156.  Thanks
