### ISSUE TITLE
question about msgid

### ISSUE THREAD

**Issue by helo-ch** [eclipse-paho/paho.mqtt.c#387]
I'm sorry if this question has been answered already, either in the doc or on here, but I couldn't find any answer : is a message's msgid supposed to be the same when it is received than when it is sent? I tried without setting msgid when sending my message, it was 0 for both the sent and the received messages, and when I tried setting msgid to a value of my choice when sending the message, it was still 0 on the receiving end. I would have thought it was supposed to be the same value on both sending and receiving side, but maybe this is normal behaviour? Or maybe msgid is not supposed to be set manually?

**Comment by icraggs** [comment]
The message id is set by the library, you can't set it yourself.  The message id is used in one direction only, one connection between client and server.   If you subscribe to that topic and get that message back, it will have a different message id.  

Also, QoS 0 does not use message ids, only QoS 1 and 2.

**Comment by helo-ch** [comment]
Oh okay, thanks for the quick answer! I was sending messages in QoS0, hence the msgid = 0 I guess.
