### ISSUE TITLE
Disabling StackTracing

### ISSUE THREAD

**Issue by croja** [eclipse-paho/paho.mqtt.c#391]
I build pahomqtt with following commands:

> 
> cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$PREFIX
> make install

Which option can I specify to enable NOSTACKTRACE? (my threads spend most of time waiting on mutex defined in StackTrace.c)

**Comment by icraggs** [comment]
You can put required compile definitions into the CMakeLists file in the same way as other examples:

ADD_DEFINITIONS(-DOSX)

**Comment by croja** [comment]
Thank you
