### ISSUE TITLE
paho.mqtt.c MQTTAsync_connect, MQTTAsync_disconnect, MQTTClient_connect, MQTTClient_disconnect functions block some other threads

### ISSUE THREAD

**Issue by mozcelikors** [eclipse-paho/paho.mqtt.c#392]
Hello there,

We are developing an Eclipse-based embedded project within Eclipse KUKSA. 

I have an issue which is extensively described here: [Callback threads in paho.mqtt.c blocking another thread (Pthread)
](https://stackoverflow.com/questions/47823805/callback-threads-in-paho-mqtt-c-blocking-another-thread-pthread)

I have a static thread with highest priority for low-level GPIO operations, yet this thread is completely blocked somehow when I either call ``MQTTAsync_connect``, ``MQTTAsync_disconnect`` or ``MQTTClient_connect``, ``MQTTClient_disconnect`` functions in other threads dedicated to publishing and subscription. (The weird thing is, we have over 40 threads issuing other communication protocols, sensors and so on, but this only happens when I specifically use the aforementioned functions. Furthermore, even if these functions are called in the main thread, still causes this blockage.)

From wiringPi library, this thread is completely blocked:
```
static void *softPwmThread (void *arg)
{
  int pin, mark, space ;
  struct sched_param param ;

  param.sched_priority = sched_get_priority_max (SCHED_RR) ;
  pthread_setschedparam (pthread_self (), SCHED_RR, &param) ;

  pin = *((int *)arg) ;
  free (arg) ;

  pin    = newPin ;
  newPin = -1 ;

  piHiPri (90) ;  //Adjusts priority - 99max - 1min

  for (;;)
  {
    mark  = marks [pin] ;
    space = range [pin] - mark ;

    if (mark != 0)
      digitalWrite (pin, HIGH) ;
    delayMicroseconds (mark * 100) ;

    if (space != 0)
      digitalWrite (pin, LOW) ;
    delayMicroseconds (space * 100) ;
  }

  return NULL ;
}
```

I really wonder if the developers of paho.mqtt.c have an idea about why this might happen. If so, I would really appreciate some pointers.

Thanks in advance.

**Comment by icraggs** [comment]
The MQTTAsync dis/connect calls should not block at all.  However, the MQTTClient calls will block, in the case of connect, waiting for the CONNACK packet from the MQTT server.  If you want an entirely non-blocking solution, then you should only use the MQTTAsync calls.

Using both MQTTAsync and MQTTClient libraries in one application is not something I have done, or thought that might be done, so I've not tested for any interactions between them.  I see that there is one mutex on Linux with the same name (socket_mutex) but if they are in different shared libraries I don't know if this is a problem or not.  Easily tested by changing the name of one of them, along with its store.

I didn't see any mention of the use of MQTTClient in the stackoverflow question.  I probably haven't understood fully the behaviour you are seeing yet.

It might help to take a trace of the events, by setting the MQTT_C_CLIENT_TRACE environment variable to ON or a filename.

**Comment by mozcelikors** [comment]
Hello,

Thanks for your fast reply. I should clarify the problem.

I've tried both MQTTClient and MQTTAsync versions, and tried calling those examples either from the main function and from a thread. (Along with the only PWM handler thread that I described above) Regardless of the solution being blocking or non-blocking, it affects the aforementioned thread operation. 

I've discovered that when either the waiting is handled within callback (Async) or either it being completely blocking (Client) does not affect this situation. **I suspect some call within MQTTAsync_connect or MQTTAsync_disconnect functions (also the MQTTClient versions have the same behavior) are doing something that might affect other threads, causing them to starve (even if they are the highest priority).**

Regarding,

> I see that there is one mutex on Linux with the same name (socket_mutex) but if they are in different shared libraries I don't know if this is a problem or not.

I think you assumed I am using both MQTTClient and MQTTAsync versions, but I've tried either examples, not both of them at the same time.

If you don't have any idea still about this issue, whether or not MQTT calls might affect other threads or not, I can hopefully provide you a specific trace some time soon.

Thanks.

**Comment by icraggs** [comment]
I'd like to ensure that you know that the callback functions in the async client are meant to be short-lived.  It's fine to call make other non-blocking API calls within them, but during the execution of that callback some other async library functions will be blocked, so any blocking call should be made elsewhere.

There arey two possibilities for blocking that I can think of in the async call:

1) malloc is overridden by mymalloc() in Heap.c, and blocks on heap_mutex.  If you are building the library yourself, you can turn off the malloc/free tracking with the NO_HEAP_TRACKING compiler switch.

2) MQTTAsync_addCommand blocks on socket_mutex.

If you only need very simple MQTT client functionality, perhaps the embedded C/C++ library could be an option?  Is this on an embedded device or similar?

**Comment by mozcelikors** [comment]
Hello, sorry it took a bit to answer. But I wanted to get the valgrind trace.
I seriously believe that MQTT library causes problems, I did two tests:

**(1)** - with mqtt publisher and subscriber running
**(2)** - without mqtt publisher and subscriber running

In (2)nd case, no SIGILL, everything is fine.

In (1)st one,

```
**Creating Thread MQTT Publisher**
**Creating Thread MQTT Subscriber**
disInstr(arm): unhandled instruction: 0xF1010200
                 cond=15(0xF) 27:20=16(0x10) 4:4=0 3:0=0(0x0)
==4008== valgrind: Unrecognised instruction at address 0x48426f4.
==4008==    at 0x48426F4: ??? (in /usr/lib/arm-linux-gnueabihf/libarmmem.so)
==4008== Your program just tried to execute an instruction that Valgrind
==4008== did not recognise.  There are two possible reasons for this.
==4008== 1. Your program has a bug and erroneously jumped to a non-code
==4008==    location.  If you are running Memcheck and you just saw a
==4008==    warning about a bad jump, it's probably your program's fault.
==4008== 2. The instruction is legitimate but Valgrind doesn't handle it,
==4008==    i.e. it's Valgrind's fault.  If you think this is the case or
==4008==    you are not sure, please let us know and we'll try to fix it.
==4008== Either way, Valgrind will now raise a SIGILL signal which will
==4008== probably kill your program.
==4008== 
==4008== Process terminating with default action of signal 4 (SIGILL)
==4008==  Illegal opcode at address 0x48426F4
==4008==    at 0x48426F4: ??? (in /usr/lib/arm-linux-gnueabihf/libarmmem.so)
**Creating Thread MQTT Subscriber**
==4008== Thread 6:
==4008== Use of uninitialised value of size 4
==4008==    at 0x5493934: free_mem (in /lib/arm-linux-gnueabihf/libc-2.19.so)
==4008==    by 0x54933C3: __libc_freeres (in /lib/arm-linux-gnueabihf/libc-2.19.so)
==4008==    by 0x4024633: _vgnU_freeres (vg_preloaded.c:61)
==4008==    by 0x487D503: __pthread_enable_asynccancel (cancellation.c:31)
==4008==    by 0xFFFFFFFF: ???
```

I will be posting when I figure out more. If you know something about this, please let us know.
Thanks.

**Comment by icraggs** [comment]
If no further information, I'm going to close.
