### ISSUE TITLE
Is there a sample program that can communicate with the server?How to compile /src/samples?

### ISSUE THREAD

**Issue by zmsoft** [eclipse-paho/paho.mqtt.c#396]
Hi 
I am currently studying MQTT,so I want to run the demo to see how it works.
I see the src/samples in the directory structure that looks like a client program.
My OS is ubuntu 14.04, cmake 3.8.2,gcc 4.8.4
Many thanks.

**Comment by dontsovcmc** [comment]
see tests folder. there are a lot of integration tests.

**Comment by icraggs** [comment]
The readme contains build instructions for using make.  Alternatively, you can use plain "make" which builds both tests and samples.  The Travis build executes the tests, and includes the Mosquitto configuration needed to do so.  It's all there with a little investigation.
