### ISSUE TITLE
openssl1.1.0f

### ISSUE THREAD

**Issue by ZhouBox** [eclipse-paho/paho.mqtt.c#397]
when I use openssl 1.1.0f lib in wondiws on VS2015，error！
>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(62): error C2143: 语法错误: 缺少“)”(在“*”的前面)
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(62): error C2143: 语法错误: 缺少“{”(在“*”的前面)
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(62): error C2059: 语法错误:“)”
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(392): error C2143: 语法错误: 缺少“)”(在“*”的前面)
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(392): error C2143: 语法错误: 缺少“{”(在“*”的前面)
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(392): error C2059: 语法错误:“)”
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(393): error C2054: 在“id”之后应输入“(”
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(415): error C2065: “CRYPTO_LOCK”: 未声明的标识符
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(440): warning C4013: “SSL_library_init”未定义；假设外部返回 int
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(443): warning C4013: “ERR_load_crypto_strings”未定义；假设外部返回 int
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(444): warning C4013: “SSL_load_error_strings”未定义；假设外部返回 int
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(450): warning C4013: “OpenSSL_add_all_algorithms”未定义；假设外部返回 int
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(452): warning C4013: “CRYPTO_num_locks”未定义；假设外部返回 int
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(469): warning C4013: “CRYPTO_THREADID_set_callback”未定义；假设外部返回 int
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(469): error C2065: “SSLThread_id”: 未声明的标识符
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(473): warning C4013: “CRYPTO_set_locking_callback”未定义；假设外部返回 int
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(490): warning C4013: “EVP_cleanup”未定义；假设外部返回 int
1>d:\newlib\paho.mqtt.c-1.2.0\src\sslsocket.c(491): warning C4013: “ERR_free_strings”未定义；假设外部返回 int
1>  MQTTAsync.c
1>d:\newlib\paho.mqtt.c-1.2.0\src\mqttasync.c(3187): warning C4013: “SSLeay_version”未定义；假设外部返回 int
1>d:\newlib\paho.mqtt.c-1.2.0\src\mqttasync.c(3187): error C2065: “SSLEAY_VERSION”: 未声明的标识符
1>d:\newlib\paho.mqtt.c-1.2.0\src\mqttasync.c(3187): warning C4047: “=”:“const char *”与“int”的间接级别不同
1>d:\newlib\paho.mqtt.c-1.2.0\src\mqttasync.c(3190): error C2065: “SSLEAY_CFLAGS”: 未声明的标识符
1>d:\newlib\paho.mqtt.c-1.2.0\src\mqttasync.c(3190): warning C4047: “=”:“const char *”与“int”的间接级别不同
1>d:\newlib\paho.mqtt.c-1.2.0\src\mqttasync.c(3193): error C2065: “SSLEAY_BUILT_ON”: 未声明的标识符
1>d:\newlib\paho.mqtt.c-1.2.0\src\mqttasync.c(3193): warning C4047: “=”:“const char *”与“int”的间接级别不同
1>d:\newlib\paho.mqtt.c-1.2.0\src\mqttasync.c(3196): error C2065: “SSLEAY_PLATFORM”: 未声明的标识符
1>d:\newlib\paho.mqtt.c-1.2.0\src\mqttasync.c(3196): warning C4047: “=”:“const char *”与“int”的间接级别不同
1>d:\newlib\paho.mqtt.c-1.2.0\src\mqttasync.c(3199): error C2065: “SSLEAY_DIR”: 未声明的标识符
1>d:\newlib\paho.mqtt.c-1.2.0\src\mqttasync.c(3199): warning C4047: “=”:“const char *”与“int”的间接级别不同

**Comment by icraggs** [comment]
OpenSSL version 1.0 and 1.1 have different link requirements.  I don't remember right now, but I it looks like the Windows library was built with 1.0.

**Comment by icraggs** [comment]
Closing for now.
