### ISSUE TITLE
Separate callback contexts

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#399]
It would be slightly more convenient if each callback function could have its own context. This would allow some of the other languages using the C library to map separate lambdas/closures to each callback. 

It could be done by adding separate callback registration functions, like:
```
MQTTAsync_setConnectionLostCallback(MQTTAsync handle, void* context, MQTTAsync_connectionLost* cl);

MQTTAsync_setMessageArrivedCallback(MQTTAsync handle, void* context, MQTTAsync_messageArrived* ma);

MQTTAsync_setDeliveryCompleteCallback(MQTTAsync handle, void* context, MQTTAsync_deliveryComplete* dc);
```

The existing API wouldn't need to be broken, since the `MQTTAsync_setCallbacks` could just call each of these with the same context value.

**Comment by icraggs** [comment]
Yep.

**Comment by icraggs** [comment]
Fix merged.  Thanks!
