### ISSUE TITLE
Possible segmentation fault in application callback function caused by not properly initialized argument

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#4]
migrated from Bugzilla [#486548](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486548)
status UNCONFIRMED severity _normal_ in component _MQTT-C_ for _1.2_
Reported in version _1.2_ on platform _PC_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[commit-e1d8e2d](https://bugs.eclipse.org/bugs//attachment.cgi?id=259382)_ (ID 259382)

On 2016-01-26 07:15:05 -0500, Juergen Kosel wrote:

> The functions MQTTAsync_removeResponsesAndCommands() and
> MQTTAsync_removeResponsesAndCommands() do not initialize the pointer data.message.
> So if a on command failure callback tries to use this given pointer,
> it has no chance to see that there is no valid message. And then it triggers a
> segmentation fault exception.

On 2016-01-26 07:16:37 -0500, Juergen Kosel wrote:

> Created attachment 259382
> Git commit which fixes this problem
> 
> Initialize the message to null pointer
> 
> To prevent segmentation fault in application, the message pointer needs
> to be initialized.

**Comment by icraggs** [comment]
Fix added to the develop branch.
