### ISSUE TITLE
LinkedList.c Crash issue on iOS

### ISSUE THREAD

**Issue by KonamiWu** [eclipse-paho/paho.mqtt.c#402]
I am using MQTTAsync with SSL static library for iOS by cross compiling.

I use auto reconnect on my connection.

I have no idea with following crash report:

Crashed: Thread
0  MyApp                       0x100e48668 ListFindItem (LinkedList.c:157)
1  MyApp                       0x100e487f0 ListUnlink (LinkedList.c:205)
2  MyApp                       0x100e487f0 ListUnlink (LinkedList.c:205)
3  MyApp                       0x100e48ad4 ListRemoveItem (LinkedList.c:346)
4  MyApp                       0x100e412f4 Socket_close (Socket.c:581)
5  MyApp                       0x100e36a78 MQTTAsync_closeOnly (MQTTAsync.c:2049)
6  MyApp                       0x100e3688c MQTTAsync_closeSession (MQTTAsync.c:2067)
7  MyApp                       0x100e36cf0 nextOrClose (MQTTAsync.c:1396)
8  MyApp                       0x100e36338 MQTTAsync_checkTimeouts (MQTTAsync.c:1440)
9  MyApp                       0x100e32cbc MQTTAsync_sendThread (MQTTAsync.c:1496)
10 libsystem_pthread.dylib        0x180fd42b4 _pthread_body + 308
11 libsystem_pthread.dylib        0x180fd4180 _pthread_body + 310
12 libsystem_pthread.dylib        0x180fd2b74 thread_start + 4

Is it attributable to the errors in cross compile?

**Comment by icraggs** [comment]
What errors did you get in the cross compile?  I built the library for iOS a couple of years back and it worked at that point.  That stack trace looks like its happening on a socket failure, or close.

**Comment by KonamiWu** [comment]
it won't happen every time....
it may  happen when connecting(by auto reconnecting) and disconnecting too quickly

**Comment by icraggs** [comment]
Getting a client trace if you can (see the debug info in the readme) could help narrow this down.

**Comment by icraggs** [comment]
Some updates have been made since this report which may help.  I'll need a trace to go further.

**Comment by KonamiWu** [comment]
I don't have any trace any more sorry....

we have changed to use CocoaMQTT for the project

thanks

Ian Craggs <notifications@github.com> 於 2018年8月2日 週四 下午11:05寫道：

**Comment by icraggs** [comment]
Thank you.  That's probably a good idea as iOS is not the main focus of this project (Linux, Windows and MacOS are).  For iOS you may also want to check out https://github.com/novastone-media/MQTT-Client-Framework and other work by @ckrey.
