### ISSUE TITLE
Reconnection issue when network is disabled.

### ISSUE THREAD

**Issue by bcmacri** [eclipse-paho/paho.mqtt.c#409]
Greetings,

While testing we ran into a reconnection issue on Windows using the C library version 1.2.0 (Paho 1.3).  If the network card is disabled when an initial connection is tried then the client will not try to reconnect if a host name is specified instead of an IP address.  I realize this is very specific but I wanted to at least put it out there.

While looking through the code I found when I specify a hostname verses an IP address there is a slight different code path to do the DSN lookup.  Since it can't successfully complete that, it errors out with the connect_state set to 0.  If an IP address is specified the connection still can't be made but the connect_state gets set to 1.  This makes a big difference because the logic in MQTTAsync_checkTimeouts looks at the connect_state to determine if the connection should be retried.  If it is 0 then the connection is not retried.

I don't know if this expected behavior but I would think the connection should be retried no matter if a hostname or IP address is specified.  I did not convert one of the samples to show this behavior and if that would be helpful I will try to do that.

Thank you for your time,
Ben

**Comment by icraggs** [comment]
Can you take a client trace (see the 'runtime tracing' section of the readme for how) of this situation?  Thanks

**Comment by bcmacri** [comment]
Thank you for taking a look.  I'm not sure what trace level you wanted so I ran these with TRACE_MAXIMUM.  The Host_Name.txt file is using the host name while IP_Address.txt is using the IP address.  Both are pointing to HiveMQ.  In both I started the app with the network connection disabled.  About a minute after starting I enabled the network connection.  About a minute after that I shut it down.  In the IP Address test the connection did get established so I sent a publish through.  Other than that I tried to keep it the same as much as possible. 

If there is anything else I can help you with or if you want me to run these tests with a different tracing level just let me know.

Thank you for your time.
Ben

[Host_Name.txt](https://github.com/eclipse/paho.mqtt.c/files/1741695/Host_Name.txt)
[IP_Address.txt](https://github.com/eclipse/paho.mqtt.c/files/1741696/IP_Address.txt)

**Comment by dawagner** [comment]
I encountered the same problem: automatic connection retry works with an IP address, not with a domain name.

**Comment by icraggs** [comment]
These questions are going through my mind.  If you can answer any of them that would be helpful.

1. The trace shows the DNS lookup for the hostname failing, as it would do with the network disabled.  Does the retry also fail if the DNS lookup works, but the server is not available for another reason?

2. Does the failure occur for a 'manual' retry, using the connectionLost callback, in the same way, or is it only automatic reconnect?

3. Does the failure still occur with the latest code on the master branch?  A number of changes have been made which might affect this behaviour.

4. Does the failure occur on platforms other than Windows?

I'll be trying to answer these questions myself.

**Comment by dawagner** [comment]
1. It seems to only occur when DNS resolution fails **the first time**. The following scenarion works, though:
    - Add "foobar" in /etc/hosts
    - Run the client and point it to "foobar:1883"
    - Connection fails because the broker isn't running; the client tries to reconnect periodically
    - Remove "foobar" from /etc/hosts
    - Start the broker
    - The client is still trying to reconnect but can't
    - Add "foobar" to /etc/hosts again
    - The client successfully connects to the broker

    If you skip the first step, then the client doesn't retry to connect.

2. Don't know

3. Don't know; I may try that later

4. I forgot to mention that I'm running into this issue on Linux

**Comment by dawagner** [comment]
@icraggs : I still encounter this issue with the develop branch (specifically, d27a7c589986dab1589497178ef80a5f17ee3f5e).

**Comment by icraggs** [comment]
@dawagner On Windows?  Scratch that question, I just saw your Linux comment.

**Comment by icraggs** [comment]
I've added a fix to the develop branch, which seems to do the job for me.

**Comment by dawagner** [comment]
It works for me too :) thanks.

**Comment by icraggs** [comment]
That was quick!
