### ISSUE TITLE
Paho failing to build

### ISSUE THREAD

**Issue by danibez** [eclipse-paho/paho.mqtt.c#416]
When I clone the repository and run make it returns me the following error. The test code is for sure missing. I searched for it in some previous commits but couldn't find it.

`make: *** No rule to make target 'src/../test/test_issue373.c', needed by 'build/output/test/test_issue373'.  Stop.`

**Comment by icraggs** [comment]
Hmm, I didn't mean to add that to the Makefile.  I've removed it now.  The CMake build is probably the best one to use now - it's the one that's used on Travis, and the output pretty good.

**Comment by icraggs** [comment]
This should be fixed now.
