### ISSUE TITLE
MQTTV5 packet support

### ISSUE THREAD

**Issue by icraggs** [eclipse-paho/paho.mqtt.c#417]
First stage of MQTT 5 support outlined in #308: 

Stages:
1) MQTTV5 packets, which include properties.  This should allow existing tests to work in V5 mode to a V5 broker, I think.

2) Specific V5 enhancements
- new behaviour for clean start + session expiry
- disconnect sent from server
- nack handling and reporting
- the ability to set and read properties
- subscription options
- automatic use of topic aliases?
- use of subscription identifiers
- setting, reading and adhering to new session parameters such as max inflight 
- auth packet exchanges

**Comment by ashchurko** [comment]
Hello Ian!

How about testing your client's MQTT 5.0 implementation against [3rd party broker](http://flespi.com/mqtt-broker#mqtt-checklist)?

**Comment by icraggs** [comment]
@ashchurko thanks for the invitation.  The tests should run against any broker when they're done.

**Comment by ashchurko** [comment]
Yes, we successfully run the tests over the broker. But as you will implement more features and need broker for this you may just use it. At that moment of time it is the sole one public broker supporting MQTT 5.0 protocol.

**Comment by icraggs** [comment]
Do you know that I wrote a Python MQTT 5.0 broker last year in the Paho test material?  That's what we use for the CI testing for the Java and C clients.  It's pretty public :-)

https://github.com/eclipse/paho.mqtt.testing

**Comment by ashchurko** [comment]
))) yes, of course. But it kind of testing staff and behaves accordingly. And not all the features)) You still need to test client with huge load, long running, handling of various types of disconnects, including network problems, test against different implementations of servers, because they may behave even differently (protocol is still quite flexible, for example the order of retained messages can be before or after SUBACK), etc etc

I do not push, I mean - here we have it, I know for developing client you need server, better multiple servers to test, so just let you know about this possibility. Nothing more))

**Comment by icraggs** [comment]
The MQTTV5 packet support is now done.

**Comment by AtosNicoS** [comment]
Is there any documentation about the V5 API written yet? I'd like to check how MQTT5 is realized, so we can prepare better for the new version and its options.

**Comment by icraggs** [comment]
@AtosNicoS I wrote a blog post a little while back

http://modelbasedtesting.co.uk/2018/04/30/the-new-mqtt-v5-api-for-the-eclipse-paho-c-client/

The examples are in the test programs, test15, test45, test10 and test11.  

I'll update the Doxygen doc soon.  Perhaps I should write another post?  I aim to update the samples soon as well.

**Comment by icraggs** [comment]
1) Yes 
2) Properties have ids (one byte) not names - the names are an enum.  User properties, of which you can have more than one, have both a name and a value.  All others are predefined ids and types. http://docs.oasis-open.org/mqtt/mqtt/v5.0/cs01/mqtt-v5.0-cs01.html#_Toc502667250
3) User properties are UTF-8 strings for both name and value.  Yes, but :-)
4) Max size for strings is 64k (2-byte length field)
