### ISSUE TITLE
error while compiling MQTT source code

### ISSUE THREAD

**Issue by bhagyashree-dhotre** [eclipse-paho/paho.mqtt.c#419]
hello,
I am using paho c library for MQTT protocol.
I am using Ubuntu operating system. I followed the following for building library.
https://www.eclipse.org/paho/clients/c/

when i am going to compile the source code of MQTT code then it gives an error like undefined reference to MQTT_client create.
below i attached screen shots of the command prompt, 
![capture10](https://user-images.githubusercontent.com/36404687/36711471-752508fa-1b7b-11e8-912b-3925ff5d243e.PNG)

**Comment by icraggs** [comment]
You need to include the library in your gcc command.  You can see examples in the Makefile, when you run it, and in the CMake configuration files.  Here is a line from running the makefile on OS/X:

cc -o build/output/samples/paho_cs_pub src/samples/paho_cs_pub.c -lpaho-mqtt3c  -I src -lpthread -L build/output -DOSX

You'll see the -lpaho-mqtt3c option which tells it the library to link with.

**Comment by icraggs** [comment]
I'll assume this has answered your question.
