### ISSUE TITLE
TLS Hostname Verification

### ISSUE THREAD

**Issue by lebandhe** [eclipse-paho/paho.mqtt.c#420]
Hi all,

we are using the latest PAHO Release Library and found out, that the Client does not Check the CN of the Server Certificate. 

According to the Openssl Wiki it is the responsibility of the Software using Openssl:

_OpenSSL 1.1.0 provides built-in functionality for hostname checking and validation. Viktor Dukhovni provided the implementation in January, 2015. Its been available in Master since that time. The code is beginning to see widespread testing as the release of OpenSSL 1.1.0 approaches.

One common mistake made by users of OpenSSL is to assume that OpenSSL will validate the hostname in the server's certificate. Versions prior to 1.0.2 did not perform hostname validation. Version 1.0.2 and up contain support for hostname validation, but they still require the user to call a few functions to set it up.

A man page on hostname validation has been available since 1.0.2. Also see the X509_check_host()._

Does Paho do this check or is this a bug?

**Comment by icraggs** [comment]
Hello.  The original implementer of TLS support, who is very experienced in security and the use of TLS, was (and still is) of the opinion that this check did not buy anything over validating the certificate chain.

As it seems to be common practice I can add it in.  I'll look into using the OpenSSL 1.1.0 functions or implementing it separately.

**Comment by lebandhe** [comment]
Our assumption is, that if someone could get hold on a valid Certificate from another Server (with a valid chain), he could play man in the middle. That way, certificate chain validation would not be sufficient.

Using the OpenSSL Functions seem to do the job.

**Comment by icraggs** [comment]
Having started to try out the X509_check_host function, it seems to exist in OpenSSL 1.0.2 as well.  So using that function seems like a viable option.  It might be that some workaround for OpenSSL 0.9.8 is needed, I'm not sure.

**Comment by icraggs** [comment]
I've a added a fix, and a test to the develop branch.  Just figuring out how to get all the Travis tests working, as the Ubuntu image has an older version of OpenSSL which doesn't support these calls.
