### ISSUE TITLE
port with 8080 caused -3 failure, does the code support websocket?

### ISSUE THREAD

**Issue by xiaodongliang** [eclipse-paho/paho.mqtt.c#421]
Hi,

I am using Intel Up2 Grove board. It works well with the MQTT native (port 1883). However, MQTTAsync_sendMessage always fail with -3 when trying with MQTT over websocket (say 8080, 8000). I have tested with test.mosquitto.org:8080, or the MQTT localhost. 

It does not tell more useful info with MQTTAsync_setCallbacks.

I am not sure if this is something paho.mqtt.c does not support at all, or something Intel board does not support, or the specific port on the board is not enabled? Googling a lot, no result.

Thank you!

**Comment by icraggs** [comment]
No it doesn't yet.  See #166

**Comment by icraggs** [comment]
We can track this in issue #166
