### ISSUE TITLE
can not publish message to cloud

### ISSUE THREAD

**Issue by bhagyashree-dhotre** [eclipse-paho/paho.mqtt.c#422]
hello,
 I am using Eclipse paho.mqtt.c library.
In the samples code,  I am using code paho_cs_pub.c to publish the message to artik cloud.
 and ARTIK cloud which acts as a MQTT broker requires encrypted channel so i generated respected certificates.
where i putting every parameter in the command line argument. like user name and password, url, port number. but gives me the following error. failed to connect.. please help me out what i am missing
![capture 34](https://user-images.githubusercontent.com/36404687/36833603-ffcd1034-1d55-11e8-80ee-6e3e52de12cd.PNG)

**Comment by icraggs** [comment]
You will undoubtedly need to use a TLS connection, which that sample doesn't have support for yet.  It's on my to-do list.

**Comment by icraggs** [comment]
Continuing the conversation in #423
