### ISSUE TITLE
do we need to provide generated certificate in the source code

### ISSUE THREAD

**Issue by bhagyashree-dhotre** [eclipse-paho/paho.mqtt.c#423]
hello
ARTIK CLOUD MQTT broker requires the encrypted ssl/tls connection.
I am using paho_cs_pub.c in github source/samples to publish the message to ARTIK cloud.
so how to provide ssl/tls connection to broker and how will be set usrename and password in the source code.
where do we need to provide the path of the certiifcates.

here is the link of the paho library which i have included in my ubuntu operating system
https://github.com/eclipse/paho.mqtt.c

and what will be sequence of command line arguments in the command prompt? while we provide the input to code as follows

./a.out /v1.1/messages/6d4fa8beef56421f9dcfc7f2932bccc5 --verbose --qos 0 --host api.artik.cloud --port 8883 --clientid stdin_publisher --username "6d4fa8beef56421f9dcfc7f2932bccc5" --password "ee6cd7ef814141868bd5c6a6318d8f63" 100 \n
this what i provide in command prompt to connect broker.
is it correct??

![capture 34](https://user-images.githubusercontent.com/36404687/36843160-0f5ad0b8-1d74-11e8-9777-ff158d2817f4.PNG)

**Comment by icraggs** [comment]
I'd appreciate it if you didn't open another issue for what is essentially a continuation of the question in issue #422.   You could have continued the conversation there.  

As I think I said in the other issue, that sample does not yet support TLS.  I will put it on the to do list.  There are plenty of examples of using TLS in the tests.
