### ISSUE TITLE
On network links with more than small amounts (<10ms) latency paho is limited by the maxInflightMessages list.

### ISSUE THREAD

**Issue by ArcolaJasper** [eclipse-paho/paho.mqtt.c#424]
On a 3g connection with ~100ms latency when the maxInflightMessages list is full MQTTClient_publish blocks until an ack is received, which limits the messages/sec you can send to ~10 or so.

Changing the 10 here:

https://github.com/eclipse/paho.mqtt.c/blob/8276dcd2172b8f96582243a8c29f1fe88c390002/src/MQTTClient.c#L1061

 to a much larger value, e.g. 500 fixes it and gets us ~2000 messages/sec.

**Comment by icraggs** [comment]
Yes, that limitation was put in a long time ago when the people I was working with were quite nervous about having lots of in flight messages.  I could add an option/API to the client so this value can be increased if desired.

**Comment by ArcolaJasper** [comment]
We have a separate queue that holds sent messages as well as the messages ids. If we lose connection to the broker we try to reconnect and re-send messages that we havn't got an ack for.

I don't know what brokers do (or what the spec says to do) if they have received messages and not yet sent an ack and a client disconnects.

In  our case we don't really have a choice tho - we need the performance.

An option to set the queue size would be very helpful.

**Comment by icraggs** [comment]
If you connect non-cleansession, then the client and broker will both resend unacked QoS 1 and 2 messages automatically on reconnect.

**Comment by icraggs** [comment]
I should observe that the async client MQTTAsync, has no such limit.  You can allow as many inflight messages as you wish, using the callbacks to monitor the number of outstanding completions.
