### ISSUE TITLE
Async wait for subscribe causes endless lock

### ISSUE THREAD

**Issue by Thalhammer** [eclipse-paho/paho.mqtt.c#425]
While implementing a small wrapper around MQTTAsync I get a hang using the following code:
```cpp
MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
if (MQTTAsync_subscribe(impl->client, topic.c_str(), qos, &opts) != MQTTASYNC_SUCCESS)
	throw std::runtime_error("Failed to subscribe");
MQTTAsync_waitForCompletion(impl->client, opts.token, -1);
```
The code hangs inside the call to MQTTAsync_waitForCompletion.
When looking at the communication using Wireshark I can see that the subscribe is never sent to the server. If I comment out the wait the packet is sent fine.
Note that I only observed this behavior on subscribing, with send and unsubscribe similar code seems to work just fine.

//EDIT
Immediately after opening this issue I noticed that subscribe is the only call done from a mqtt callback.
Maybe this is a reason why it does not send?

// EDIT2
Looking at the source code of this client, I noticed that those callbacks are called inside the receiving thread. So it makes absolute sense for this to fail to work. So please consider this issue closed.

**Comment by icraggs** [comment]
I think you've answered your own question.  You can issue any non-blocking call within a callback, such as MQTTAsync_subscribe, but not a blocking one such as waitForCompletion.  In fact, waitForCompletion is the only blocking call in the API.
