### ISSUE TITLE
conan support

### ISSUE THREAD

**Issue by danimtb** [eclipse-paho/paho.mqtt.c#426]
Hi!

Following suggestions in the[ conan wishlist](https://github.com/conan-io/wishlist/issues/13) we have recently started packaging paho with [conan](https://www.conan.io/).

I have setup a [conan-community/conan-paho-c](https://github.com/conan-community/conan-paho-c) project with the needed files to package the lirbary as well as the CI jobs for multi-platfom building.

We have created a wide range of packages for different platforms and supported library options such as SSL (with OpenSSL dependency) and async support. Check the table:

![paho-c_table](https://user-images.githubusercontent.com/10808592/37099038-b5a48cca-221f-11e8-9171-6a31b2ae5aaa.png)

We are at the point of including this package in [conan-center](https://bintray.com/conan/conan-center), a central repository with curated and maintained conan packages for the opensource c++ community and we would like to know if you would be willing to enable support for conan to the paho.mqtt.c library (Directly in this repository or using a separate one).

We would also like to have [paho.mqtt.cpp](https://github.com/eclipse/paho.mqtt.cpp) once the paho.mqtt.c dependency package is ready in conan-center. 😄

**Comment by icraggs** [comment]
Hello!  Yes, absolutely.  I think the support files could go in this repo, unless they were huge, or couldn't be licensed under the EPL/EDL.

**Comment by danimtb** [comment]
Hi @icraggs! Thank you so much for your quick response.

Currently the repo [conan-paho-c](https://github.com/conan-community/conan-paho-c) is licensed under MIT but don't worry if that is a stopper. We used that license as it is the same one Conan has, so we can transfer the needed files under your license.

Also notice that in order to generate conan packages of your librry automatically, the setup will require setting up some CI jobs under Travis/Appveyor as every package has the needed binaries for each configuration. Some library authors would like to generate packages only if there is a new release/tag. Otherwise, this process would have to be done manually, but this is up to you.

Would it be fine if I make a PR to this repo with the needed files? Would you like to setup those CI jobs?

Please ask me whatever doubt you have and I'll be happy to help with the setup 😄 Thanks!

**Comment by icraggs** [comment]
Please do start by making a PR.  To pass the IP checks that Eclipse place on the PR, you will have to agree to Eclipse EPL/EDL licensing - that would make the process much easier.

**Comment by icraggs** [comment]
https://github.com/conan-io/conan-center-index/issues/1395

**Comment by icraggs** [comment]
I've created a PR for version 1.3.4 https://github.com/conan-io/conan-center-index/pull/1862

Probably take me a while to get it all right, but let's see.

**Comment by icraggs** [comment]
A fix has been added for the contribution of Paho 1.3.4 to conan-center. https://github.com/conan-io/conan-center-index/pull/1888
