### ISSUE TITLE
Publish message won't be resent after reconnect even when clean session flag set to false 

### ISSUE THREAD

**Issue by ss-zhou** [eclipse-paho/paho.mqtt.c#429]
[mqtt_clean_session_bug.zip](https://github.com/eclipse/paho.mqtt.c/files/1824842/mqtt_clean_session_bug.zip)
The clean session flag doesn't work after the first time of connection Lost. 
In the wireshark capture there is a Publish Message with value '81' at Frame No.278 that couldn't be sent due to network interrupt. After 14 seconds at Frame No.287 the Publisher sent a Connect Command with clean session flag false. Here is expected after reconnect the Publish Message with value '81' be resent, but the first Publish Message after reconnect at the Frame No.293 shows vaule '105'. So the Publish Message with value '81' was lost in this case.  In the next round of network interrupt at Frame No.306, the Publish Message was resent after reconnect, so here the clean session flag works as expected. And as the wireshark capture shown, all the network interrupt after the first interrupt works the clean session flag correctly.

**Comment by icraggs** [comment]
Did the connect before the connection lost also have clean session = false?  The session state is cleared both at connect and disconnect when clean session = true, so even if you then reconnect with clean session false, there is no session state to continue with.

This is not a particularly satisfactory state of affairs, but one that is resolved in MQTT 5.0 (under development).

If you still think there is a bug, could you take an MQTT client trace, by setting the environment variables MQTT_C_CLIENT_TRACE=ON as outlined in the readme file.  Thanks.

**Comment by ss-zhou** [comment]
The connection before has clean session = true because that is a initial connection. But thanks for the information.
