### ISSUE TITLE
Username and password not copied as other connect options are

### ISSUE THREAD

**Issue by icraggs** [eclipse-paho/paho.mqtt.c#431]
Discovered here https://github.com/ibm-watson-iot/iot-cpp/issues/31

**Comment by dawagner** [comment]
Looks a lot like https://github.com/eclipse/paho.mqtt.cpp/issues/145, is that right?

**Comment by icraggs** [comment]
@dawagner it does look strikingly similar!  The proof would be in the testing...

**Comment by dawagner** [comment]
Successfully tested using paho.mqtt.cpp compiled against d27a7c589986dab1589497178ef80a5f17ee3f5e.

**Comment by icraggs** [comment]
@dawagner Thank you for testing it :-)

**Comment by fpagliughi** [comment]
Awesome! 
I was literally  just looking at this right now.
