### ISSUE TITLE
WSAGetLastError() should be called earlier

### ISSUE THREAD

**Issue by ghost** [eclipse-paho/paho.mqtt.c#432]
In Socket_error function, WSAGetLastError() should be called before FUNC_ENTRY macro. On my windows 7 virtual machine(and very few physical machine), I print WSAGetLastError() before and after FUNC_ENTRY macro, first call return 10035(right error number), later call return 0(wrong error number,  reset by  FUNC_ENTRY macro). Error number 0 cause the logic which can handle 10035 skipped and connection failed. If I move WSAGetLastError() before FUNC_ENTRY macro, everything is OK.
According to msdn, WSAGetLastError() should be called immediately after sockets operation failed.

**Comment by icraggs** [comment]
Thanks.  Seems right - I would probably remove the FUNC_ENTRY/EXIT macros from this function entirely.
