### ISSUE TITLE
Publishing a message within the "connected" callback of an automatic reconnect using clean session false

### ISSUE THREAD

**Issue by dawagner** [eclipse-paho/paho.mqtt.c#436]
This is more a question than a bug report.

I'm trying to implement the following behaviour:
1. Connect with clean_session=true
2. Upon success, disconnect and connect again with clean_session=false, with automatic reconnection and with max_buffered_messages > 0.
3. At that point, upon any connection success, subscribe to some topics and publish a message to a topic (I will refer to this message later as the "hello" message).
4. Once the connection mentioned in 2 is successful, start sending periodical messages

If I shutdown the network (e.g. by unplugging my ethernet cable) after some periodical messages have been sent, paho will eventually start refusing to send messages, which is expected. However, when I bring the network back, the connection success callback will be called and sending the "hello" message will fail with the error code `-12`, meaning that we are disconnected... which is contradictory to the fact that we're the "connection success" callback.

I believe the real cause is that the "max buffered message" queue is full and thus, my "hello" message can't be queued yet. Is it a known bad practice to send an MQTT command from within a callback? Is there an alternative, apart from implementing a custom retry logic?

**Comment by dawagner** [comment]
oops, sorry for the confusion regarding the meaning of `-12`.

That's right, I'm talking about the `connected()` callback. It seems that I should indeed have a custom handling of the "hello" message.

**Comment by icraggs** [comment]
Personally I would try to avoid hitting MAX_BUFFERED_MESSAGES by having the buffer big enough, or maybe implement your own buffering completely.

Can I close this issue now?
