### ISSUE TITLE
When mqtt broker is down, sometimes, callback is not received.

### ISSUE THREAD

**Issue by gittripley** [eclipse-paho/paho.mqtt.c#437]
I am running an automation test to stop and start mqtt broker every 10 seconds. After running for a few minutes, a connection failure callback is not received. Later I searched in google and found several people had already reported. In the issue 190, it is said it has been fixed in version 1.2. I saw a commit aadd424 that has been merged and the issue is closed.

Then I upgrade my paho.mqtt.c library version using the commit aadd424. It looks like the failure callback is received when mqtt broker is down. However, after I ran this test for hours, the connection failure callback is not received.

If commit aadd424 includes all the fix, there might be another hole that could cause the race condition.

https://github.com/eclipse/paho.mqtt.c/issues/190 described the fix and mentioned the commit aadd424

**Comment by icraggs** [comment]
What keep alive interval are you using?  What platform (OS)?  I presume from the references to the commits that you are using the MQTTAsync library.

When you don't receive the failure callback, can the application continue?  Are you attempting to publish any messages during this test?

**Comment by gittripley** [comment]
I stop mqtt broker for 1 second and start mqtt broker for about 8.5 second, then repeat stop and start.

When mqtt broker is down, connection_lost is called. Then the application schedule a thread to call connection right away. Later the on_failure is received, the application will schedule a thread to sleep several tens or hundred milli-second before calling connection again. 99% of time, the application keep trying until the on_success is received. However, some times (although very low possibility), the first on_failure call back is never received. It is stuck there forever even after mqtt broker is up. It appears that MQTTAsync_client thinks the call back has been made. Every time, if the expected callback is not received, it happens on the one first on_failure after connection_lost, where the application don't sleep but schedule a thread to call connection right away. It is a problem if the application calls the connection right after a connection_lost callback?

I am running the application on linux. Yes, MQTTAsync is used actually. 

I think the application can continue, but I will double check it. I don't have any message publication going on. Basically, the application starts and connect to mqtt broker. That's it. Then I started my test.

**Comment by gittripley** [comment]
Later, I read https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.1.0/com.ibm.mq.doc/tt60390_.htm.
It is said that there is only one callback instance running at a time. Now I am wondering, what if before the connection_lost callback is finished, the other thread start to call connect, will it reject it right away?

I saw the code MQTTAsync_connect(), it checks `if (sendThread_state !=STARTING && sendThread_state != RUNNING)` and `if (receiveThread_state != STARTING != receiveThread_state != RUNNING)` then it will schedule a thread. 

What if the MQTTAsync_connect() is called and the while loop in MQTTAsync_sendThread() is completed, i.e. the sendThread_state is still RUNNING (between line 1562 and 1563), in this case there is no thread for  callback.

**Comment by icraggs** [comment]
The keepalive interval is used to detect socket failures.  If the keepalive interval is longer than the interval you use between stopping/restarting the broker, maybe you won't get a connection lost callback every time.  The key question is, what happens when you try to send a message?  Do you get a connection lost callback which enables you to reconnect?  

If you get stuck in the situation where a reconnect won't work then that's a problem.  In that case the best approach might be to take a trace - the readme explains how.

**Comment by gittripley** [comment]
First, in the test so far, I always received connection lost callback. The problem is that if I schedule a task to connect in the connection lost callback right away, I won't receive the connection failure callback. But if I schedule a task to connect in the connection lost callback after 60 ms sleep, after trying a few hours, I always receive the connection failure callback.

It is actually reconnect problem.

**Comment by icraggs** [comment]
Ok, so can you take a trace as explained in the README under Runtime Tracing?  And what OS are you using?

**Comment by gittripley** [comment]
I will get the trace.

**Comment by gittripley** [comment]
I set up export 
```
export MQTT_C_CLIENT_TRACE=ON
export MQTT_C_CLIENT_TRACE_LEVEL=MAXIMUM
```
Then I start to run our application. I only got the following message

=========================================================
                   Trace Output
Product name: Paho Asynchronous MQTT C Client Library
Version: 1.1.0
Build level: 2018-03-28T22:52:13Z
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
OpenSSL flags: compiler: /usr/local/gcc-linaro-6.1.1-2016.08-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -I. -I.. -I../include  -DOPENSSL_THREADS  -DOPENSSL_NO_HEARTBEATS
OpenSSL build timestamp: built on: reproducible build, date unspecified
OpenSSL platform: platform: os/compiler
OpenSSL directory: OPENSSLDIR: "/home/ubuntu/foghorn-edgestack/native/scripts/build-third-party-libs/openssl-1.0.2j-arm-none-linux-gnueabihf"
/proc/version: Linux version 4.4.34-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #930 SMP Wed Nov 23 15:20:41 GMT 2016

=========================================================


Other message are our own debug message.

By the way, I am running the app in the docker container. So basically, I set up environment variable in the docker compose yml file and then go inside the container to run the application.

**Comment by icraggs** [comment]
Would need some trace to understand what is going on.
