### ISSUE TITLE
Is error or warning log

### ISSUE THREAD

**Issue by suniltop** [eclipse-paho/paho.mqtt.c#439]
Hi,

When i trying to send a message (size  about 1MB) then i get a log from console. 
If i trying to send a message size about 25KB, there is no log.

In addition this issue similar #373 maybe

=========== Start of stack trace for thread 1944159248 ==========
=========== End of stack trace for thread 1944159248 ==========

=========== Start of stack trace for thread 1915745296 ==========
Socket_getReadySocket (238)
   at MQTTClient_cycle (1720)
   at MQTTClient_run (558)
=========== End of stack trace for thread 1915745296 ==========

=========== Start of stack trace for thread 1960936464 ==========
Socket_putdatas (503)
   at MQTTPacket_sends (230)
   at MQTTPacket_send_publish (695)
   at MQTTProtocol_startPublishComm (132)
   at MQTTProtocol_startPublish (155)
   at MQTTClient_publish (1586)
   at MQTTClient_publishMessage (1674)
=========== End of stack trace for thread 1960936464 ==========

**Comment by icraggs** [comment]
You could try using the latest code in the master branch to see if it fixes your problem.

**Comment by suniltop** [comment]
I have tried master branch already.

Also this log appears only on my embedded device (RK3288 SOC). Works great with VM Ubuntu 16.04 on X86

Any Suggentions ?

**Comment by icraggs** [comment]
It seems that I've left a diagnostic StackTrace_printStack(stdout) statement in Socket.c (at line 537 in the current master branch).  This will only be called if the socket write isn't complete, which ties in with your experience of it only happening when the packet size is large.  There is another occurrence at line 507, but that is for a situation that 'should never happen' so I think it's not that one.

If you are building from source, you could try removing the StackTrace_printStack(stdout); and see if it solves your problem.
