### ISSUE TITLE
Create Linux packages for Debian and Red Hat

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#44]
migrated from Bugzilla [#405837](https://bugs.eclipse.org/bugs/show_bug.cgi?id=405837)
status NEW severity _normal_ in component _MQTT-C_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Ian Craggs

On 2013-04-16 18:59:38 -0400, Andy Piper wrote:

> Tracking bug to note that we should make .deb and .rpm packages for our Linux builds.

On 2013-04-16 19:09:18 -0400, Andy Piper wrote:

> Depends on versioning tickets.

On 2015-02-09 06:19:46 -0500, Ian Craggs wrote:

> Adding helpwanted flag

**Comment by icraggs** [comment]
Two contributions, one each for deb and rpm packages have been made.
