### ISSUE TITLE
Discard-oldest offline buffering policy

### ISSUE THREAD

**Issue by kbogucki** [eclipse-paho/paho.mqtt.c#441]
In the current paho implementation, MQTTASYNC_MAX_BUFFERED_MESSAGES error is returned in case of max buffered messages limit is reached.
Is there any way to setup paho offline buffering policy as discard-oldest, to discard the oldest queued message when a new one arrives?
It would be useful on memory constrained devices.

Thank you in advance for any suggestions.

**Comment by icraggs** [comment]
I agree that it would be a good policy.

**Comment by icraggs** [comment]
Added a deleteOldestMessages switch to create options.
