### ISSUE TITLE
Segmentation Fault while disconnected and Persistence enabled

### ISSUE THREAD

**Issue by cp26** [eclipse-paho/paho.mqtt.c#442]
My project is sending a JSON message 1/second.  Everything works as expected unless sendwhiledisconnected is enabled and the system remains disconnected for a few hours at which point the memory usage grows and then there is a segmentation fault.  I am attaching my strace which was running up until the seg fault.  This is my first time posting on github so please let me know what other information I need to provide. 

[mqtt_trace4918_3.zip](https://github.com/eclipse/paho.mqtt.c/files/1895434/mqtt_trace4918_3.zip)

**Comment by icraggs** [comment]
It looks like from your trace that there is 17M allocated at the end.  How big is the system you are running on?

**Comment by cp26** [comment]
Not all that big.  See attached.

![capture](https://user-images.githubusercontent.com/38256744/38581806-79396f66-3cd3-11e8-9a43-9da9889a2ad2.PNG)

Thank you.

**Comment by icraggs** [comment]
If you are doing this again, you could see whether there are any errors by setting the environment variables:

MQTT_C_CLIENT_TRACE=ON
MQTT_C_CLIENT_TRACE_LEVEL=ERROR

I'm thinking there might be a memory allocation error, given the size of the system.  Do you think it would be wise to limit the number of messages stored, perhaps by setting the maximum buffered messages lower?   What are you expecting to happen under these circumstances?

**Comment by cp26** [comment]
I ran the trace again with the mentioned trace level above and did not have any errors.  

The buffer max size is reached within around the first 10 minutes.  The program continues to run once the buffer is reached but memory used in the process continues to grow and eventually results in the seg fault a few hours later.   This only happens with persistence enabled. 

I am expecting the buffer to reach the max size allowed and then discard additional messages.  Is that an accurate expectation of how persistence functions?

**Comment by icraggs** [comment]
When the max number of buffered messages is reached, then you should get the MQTTASYNC_MAX_BUFFERED_MESSAGES return code when you invoke sendMessage(), and the send() is refused.

Is that what you are seeing?

**Comment by cp26** [comment]
I am seeing the -12 code for the MQTTASYNC_MAX_BUFFERED_MESSAGES  error.  At that point it should not store any more messages to the buffer?

**Comment by icraggs** [comment]
There is also now the option to delete oldest messages rather than newest (in upcoming 1.3.5 release).
