### ISSUE TITLE
Possible bug on setting CAPath

### ISSUE THREAD

**Issue by HED-rhodson** [eclipse-paho/paho.mqtt.c#446]
It appears that CAPath variable in MQTTClient_SSLOptions and MQTTAsync_SSLOptions is not getting copied correctly in the MQTTAsync_connect and MQTTClient_connectURI functions

The code:
if (m->c->sslopts->CApath)
	m->c->sslopts->CApath = MQTTStrdup(options->ssl->CApath);

Probably should be:
if (options->ssl->CApath)
        m->c->sslopts->CApath = MQTTStrdup(options->ssl->CApath);

**Comment by icraggs** [comment]
You are correct!  Thanks.
