### ISSUE TITLE
linker problem 

### ISSUE THREAD

**Issue by sw-tt-chandershekharsuthar** [eclipse-paho/paho.mqtt.c#448]
I'm try to publish my data via MQTT in C and I'm use the sample code of ( Paho MQTT C Client Library link [http://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/pubsync.html]) but I'm getting some error like

--------------------------------------------------------------
D:\work\CB\TEST_RUNNING\hello\main.c|21|undefined reference to `MQTTClient_create'|
D:\work\CB\TEST_RUNNING\hello\main.c|26|undefined reference to `MQTTClient_connect'|
D:\work\CB\TEST_RUNNING\hello\main.c|35|undefined reference to `MQTTClient_publishMessage'|
D:\work\CB\TEST_RUNNING\hello\main.c|39|undefined reference to `MQTTClient_waitForCompletion'|
D:\work\CB\TEST_RUNNING\hello\main.c|41|undefined reference to `MQTTClient_disconnect'|
D:\work\CB\TEST_RUNNING\hello\main.c|42|undefined reference to `MQTTClient_destroy'|
||error: ld returned 1 exit status|
||=== Build failed: 7 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|
------------------------------------------------------------

help me how to remove it and get my resutls

**Comment by icraggs** [comment]
If you look at the Makefile, it shows how to compile and build applications on Linux/Mac.  You need to link with the appropriate library libpaho-mqtt3c.so with the gcc option -lpaho-mqtt3c

**Comment by sw-tt-chandershekharsuthar** [comment]
I'm getting the SOCKET_ERROR tell me how to remove it

**Comment by icraggs** [comment]
I presume that you've got past this problem now, so we could close this issue and just use the other one?

**Comment by sw-tt-chandershekharsuthar** [comment]
last one is solved that linker error but now its like that .....
Eclipse Paho C\src\Socket.c|676|undefined reference to `getaddrinfo'|
Eclipse Paho C\src\Socket.c|708|undefined reference to `freeaddrinfo'

**Comment by sw-tt-chandershekharsuthar** [comment]
Thanks Ian its over now I got my solutions

**Comment by minaee** [comment]
I compiled that code with address of the library.
in my case:
`gcc -L/home/shahriar/MQTT/eclipse.paho.mqtt.c/build/output test.c -lpaho-mqtt3c`
`/home/shahriar/MQTT/eclipse.paho.mqtt.c/build/output` is the address of where I have built the library
