### ISSUE TITLE
versionInfo error

### ISSUE THREAD

**Issue by sw-tt-chandershekharsuthar** [eclipse-paho/paho.mqtt.c#455]
I'm publishing my data with mqtt for that I'm using Eclipse paho mqtt C code in Eclipse IDE but its give me that error...................
make -j4 all 
mkdir -p build/output/samples
sed -e "s/@CLIENT_VERSION@/1.2.1/g" -e "s/@BUILD_TIMESTAMP@//g" src/VersionInfo.h.in > build/VersionInfo.h
The syntax of the command is incorrect.
mkdir -p build/output/test
make: [makefile:188: mkdir] Error 1 (ignored)
The system cannot find the path specified.
make: *** [makefile:211: build/VersionInfo.h] Error 1
make: *** Waiting for unfinished jobs....
The syntax of the command is incorrect.
make: [makefile:189: mkdir] Error 1 (ignored)
echo OSTYPE is Windows_NT
OSTYPE is Windows_NT

15:37:09 Build Finished (took 155ms)
...................................................

how to remove it

**Comment by icraggs** [comment]
I'm going to assume this is now answered.
