### ISSUE TITLE
OPENSSL_Applink Error for secure connections in dlls

### ISSUE THREAD

**Issue by x1tan** [eclipse-paho/paho.mqtt.c#457]
Hello,

I'm trying to create a secure connection with the help of OpenSSL within an dll.

If I try to specify the digital certificate which the client should I trust I receive an runtime error "OPENSSL_Applink".

```
MQTTAsync_SSLOptions sslopts = MQTTAsync_SSLOptions_initializer;
sslopts.trustStore="my.org.crt";
```

It seems that you can only call AppLink functions from other processes but not other dlls (source: comments on [this ](https://stackoverflow.com/a/24075424) post).

Any ideas how to solve this problem? 

I thought about calling the functions to read and parse the certificate manually and supply paho with the parsed certificate and not the path to the file. But this is currently not intended as far as I can see.

Thanks a lot!

**Comment by paulorb** [comment]
What is the relation between the issue and the system variable "OPENSSL_CONF"? I have the same issue at my side

**Comment by jumoog** [comment]
i had problems in the past with "OPENSSL_CONF"

**Comment by icraggs** [comment]
What is the exact runtime message you get relating to "OPENSSL_Applink"?

**Comment by x1tan** [comment]
> OPENSSL_Uplink(00007FF8C7D603D8,08): no OPENSSL_Applink

While trying to establish the connection.

**Comment by x1tan** [comment]
Since my DLL is a plugin for an third-party application I am sadly not able to include the applink.c file.

**Comment by icraggs** [comment]
Hmm.  Tricky.  I don't know of an answer to that one.

**Comment by JuergenKosel** [comment]
Hello,

the applink must be included only once. And only for Windows with MSVC. (I do not believe that this is necessary for mingw-gcc.)
Therefore it must be included into the main program and not one of the 5 libraries which are linked against openssl library.
@x1tan if it is really not possible to add applink.c into the source list of your main application, then you could still add applink.c into the source list of your DLL. This wouldn't break thinks for anybody else, who uses paho.mqtt.c library.

**Comment by tbeu** [comment]
> If it is really not possible to add applink.c into the source list of your main application, then you could still add applink.c into the source list of your DLL.

From what I read (and also experienced) OpenSSL assumes the AppLink in the calling application and not in any called DLL. This looks like a design error of OpenSSL and will not not work out then.

See #521 for a proper fix be replacing ERR_print_errors_fp with ERR_print_errors_cb.
