### ISSUE TITLE
Seg fault occurs when DNS fails to resolve Address

### ISSUE THREAD

**Issue by HED-rhodson** [eclipse-paho/paho.mqtt.c#459]
Our platform has an issue, that is being resolved, which exposed a potential defect in the V1.2.1 Asynch Library. When our DNS doesn't restore after a Internet disconnection, the MQTT library will generate a seg fault if the address is returned as not a valid IP address.

getaddrinfo failed for addr mybackofficeip.com with rc -2
mybackofficeip.com s not a valid IP address
SIGSEGV

**Comment by HED-rhodson** [comment]
Incidentally if I test the address with getaddrinfo before I call the MQTTAsync_connect function, the seg fault never happens.

**Comment by icraggs** [comment]
Is it possible to get  a client library trace or gdb backtrace?

**Comment by HED-rhodson** [comment]
I eventually resolved the issue - ultimately my own code was responsible for the seg fault- I failed to protect against the MQTTAsync_failureData response pointer returning NULL - in the onFail callback.

**Comment by icraggs** [comment]
Thanks for letting me know.  Perhaps I should always return a failure structure so that this doesn't happen to anyone else.  It looks like there are only 3 cases.

**Comment by HED-rhodson** [comment]
It might help out a future developers. I was simply logging the response reason for informative purposes.

**Comment by icraggs** [comment]
Thanks - I've put in a change to this effect.
