### ISSUE TITLE
Add C client sample code

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#46]
migrated from Bugzilla [#402253](https://bugs.eclipse.org/bugs/show_bug.cgi?id=402253)
status ASSIGNED severity _normal_ in component _MQTT-C_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Ian Craggs

On 2013-03-03 18:01:12 -0500, Ian Craggs wrote:

> In the src/samples directory

On 2013-03-03 18:02:38 -0500, Ian Craggs wrote:

> Sample code added.

On 2013-03-04 10:02:27 -0500, Andy Piper wrote:

> **\* Bug 401722 has been marked as a duplicate of this bug. ***

On 2013-03-04 10:38:03 -0500, Andy Piper wrote:

> So we now have
> 
> MQTTAsync_publish.c
> MQTTAsync_subscribe.c
> pubasync.c
> pubsync.c
> stdinpub.c
> stdoutsub.c
> stdoutsuba.c
> subasync.c
> 
> There appear to be duplicates here (pubasync and MQTTAsync_publish?) etc.
> 
> There are strings defining the swtest.hursley.ibm.com broker as the test broker.
> 
> Need to replace localhost with m2m.eclipse.org to match Java samples.
> 
> In addition, the Makefile SAMPLES build rules do not match up with these filenames so setting BUILD_SAMPLES=TRUE does not cause the samples to be built.

On 2013-03-04 11:00:35 -0500, Ian Craggs wrote:

> pubasync and MQTTAsync_publish are not duplicates.  One uses the MQTTClient API, the other uses the MQTTAsync API, corresponding to the samples in the html documentation.

On 2013-03-04 11:02:21 -0500, Andy Piper wrote:

> (In reply to comment # 4)
> 
> > pubasync and MQTTAsync_publish are not duplicates.  One uses the MQTTClient
> > API, the other uses the MQTTAsync API, corresponding to the samples in the
> > html documentation.
> 
> Apologies I'd taken a very hasty look! was surprised that there were 8 rather than the 4 accounted for in the makefile :-)

On 2013-03-04 11:30:07 -0500, Andy Piper wrote:

> Committed the OS X build change to the Makefile, but the samples chunk will need updating in line with this.

On 2013-03-04 18:01:12 -0500, Ian Craggs wrote:

> I added some samples that I had written a long time ago, which I think are actually useful as utilities as well.  There is another to come as well: stdinpuba.c.  But I haven't written it yet!
> 
> Where to document, is the next question.

On 2013-03-04 18:08:12 -0500, Andy Piper wrote:

> (In reply to comment # 7)
> 
> > I added some samples that I had written a long time ago, which I think are
> > actually useful as utilities as well.  There is another to come as well:
> > stdinpuba.c.  But I haven't written it yet!
> > 
> > Where to document, is the next question.
> 
> I think a brief summary of the samples in README.md is appropriate?
> 
> If a deep dive is needed it could go in a tentative doc/Samples.txt

On 2013-04-15 08:35:06 -0400, Andy Piper wrote:

> Assigning to MQTT-C since this is C client specific.

On 2014-08-28 10:58:49 -0400, Ian Craggs wrote:

> Assigning to Rong.

On 2015-01-16 06:44:51 -0500, Ian Craggs wrote:

> Taking back.

**Comment by icraggs** [comment]
Old, and most issues resolved or being so.
