### ISSUE TITLE
Unable to Connect to Azure IOT using Paho MQTT for C!!

### ISSUE THREAD

**Issue by Pavan2358** [eclipse-paho/paho.mqtt.c#461]
Hi,
I am trying to connect to azure iot using Paho MQTT C(https://github.com/eclipse/paho.mqtt.c), as I believe that SSL establishment is required to connect successfully to the azure cloud, I have used "**ssl://hostname:8883**" in the address section of the code**, I am getting segmentation fault while connecting.**
I am able to compile and run it successfully but not connect!!:(
**Code for publishing the data using the topic is attached**
Note:
**1) I have used username and password, which I was able to get by refering to 
https://docs.microsoft.com/en-in/azure/iot-hub/iot-hub-mqtt-support document 
**2) I am able to connect to Azure cloud using Paho MQTT for PYTHON SUCCESSFULLY using the same parameters and SSL is installed in my PC**
3) I am using sample codes to connect to the cloud**
Please help :(....I just want to connect to the cloud, if I have to add something please tell what is required and how to use it.
**4) I have tried with other sample programs as well but its giving the similar error/ connect failed rc is  -1**
5) **If I have to use test programs, please guide on how to run it with modified changes**
Please help :(
[MQTTAsync_publish.txt](https://github.com/eclipse/paho.mqtt.c/files/2036114/MQTTAsync_publish.txt)

**Comment by icraggs** [comment]
Have you tried setting the port to 8883 in the ADDRESS parameter?  The default is 1883.

**Comment by Pavan2358** [comment]
Hi @icraggs 

**I have used **8883** port in the code, I have missed in the text file while copying from the source code**
**It would be really helpful if you can attach/give the MQTTAsync_publish code(or any publish sample code) which has modified changes to work for SSL connection**. You can give "XXXX" if you dont want the variables such as device id, end point not to be revealed, **but please provide a code. I have been trying this for a long time,** just want to connect to the azure cloud!!
Or please provide steps as to what has to be added,
Please help:(

**Comment by icraggs** [comment]
There are many examples of connecting with SSL/TLS in the test program directory, along with a mosquitto configuration file in test/tls-testing.  

test3.c - MQTTClient
test5.c - MQTTAsync

The commands to run these tests are in the test/CMakeLists.txt file.

**Comment by Pavan2358** [comment]
Hi @icraggs 

I tried test3.c as suggested by you, but even after giving right parameters test cases are failing.
**I understand each test case is for different scenario, but I have confusion as to which test case has to be run and what parameters have to be changed to connect to azure IOT successfully**
I am running the executable "test3" after doing "make and make install" as follows:
**./test3 --test_no <testcase no> --connection ssl://Ironman.azure-devices.net:8883**
**Also please find the screenshots of the test cases executed and also the code that I am runnig**
**Note:** 1) When I am running **test no 5(test2c)** the test case is passing, but rc = MQTTClient_connect(c, &opts); **is giving RC value as -1** 

2) When I am running **test no 6(test3a_s,test2a-m)** I am getting following error and test case is failing

**140652352521984:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1230:
140652352521984:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1230:
Assertion failed, file src/../test/test3.c, line 946, description: Good rc from connect
rc was -120180525 131053.506 failed: test test3a_s. 2 tests run, 1 failures.**

**Please let me know which test case has to be run to connect to azure iot and publish a message and also the parameters that I have to update if required.
![screenshot from 2018-05-25 13-32-42](https://user-images.githubusercontent.com/37648135/40532834-66bfa5a8-601e-11e8-9aae-0cab571a9078.png)

**The Code:**

[test3c.txt](https://github.com/eclipse/paho.mqtt.c/files/2038914/test3c.txt)


**
**It would be better if you send code that is running successfully with instructions on how to change according to the azure iot hub that I have created, as I am working on it for a long time and yet to crack it!!**
If 
Please help:(
Hi @JuergenKosel 
I have done the same...you can check the code I have attached, but still no luck in connecting:(

**Comment by Pavan2358** [comment]
Hi @icraggs @JuergenKosel and others

Please help for the below issue, I am to connect to azure iot(return code I am getting as 0) but cannot publish message, what wrong am I doing, I am using test3.c and checking with test no 8(test3b),
which test no should I used if I want to connect to azure iot with SAS token

**Comment by Pavan2358** [comment]
Hi @ArcolaJasper @JuergenKosel  @icraggs  and others

**That is the test name which you have seen, I am able to connect to azure IOT with test3.c and test no 8(test3b) after looking at the return code as success, but I cannot seem to publish it,
I have doubts on which test I should run, so that I can run successfully?
If I am using username and password as authentication parameters, is trust certificate required?
if needed how to get it and change it in the test functions?
Please answer it someone, I am desperately in need of this solution to connect to Azure IOT**
Please :(
**I have attached a file that connects but does not publish for test3b in test3c.c**
[test3.txt](https://github.com/eclipse/paho.mqtt.c/files/2045393/test3.txt)

**Comment by JuergenKosel** [comment]
Hello,

the Azure broker closes the connection, if the published message does not match the Azure internal format.
So this problem has nothing to do with the used mqtt library.

**Comment by icraggs** [comment]
@JuergenKosel Thanks for the response.

**Comment by icraggs** [comment]
Thanks for letting us know.  I'll close this issue for now.

**Comment by vikilabs** [comment]
I had the same issue, I was not able to connect to azure cloud with paho_c_pub. The -p option is not giving any effect. The port is preset to 1883. 
I did a workaround by modifying the default port to 8883 in paho_c_pub.c. I thank @icraggs for suggesting the default port hint.

**Comment by IanMercer** [comment]
I was able to get Azure working eventually by doing all of the following:

1. The server address must start with `ssl://` and must end with `:8883`
    `ssl://<your-hub-name>.azure-devices.net:8883`

2. The user name must look like:
    `<your-hub-name>.azure-devices.net/<your-device-name>/?api-version=2018-06-30`

3. The password must be a shared access signature in this form (including `SharedAccessSignature` at the start of the password:
    `SharedAccessSignature sr=<your-hub-name>.azure-devices.net%2Fdevices%2F<your-device-name>&sig=<sig>%3D&se=<timestamp>`

And then the messages _must use Azure's very limited topic format_ or the connection will be closed immediately after you send it.
    `devices/<device_id>/messages/events/`
