### ISSUE TITLE
About the Paho MQTT C Client reconnect setting question

### ISSUE THREAD

**Issue by toBeGeekNo1** [eclipse-paho/paho.mqtt.c#475]
Hello, I have a question about how to set the reconnect model into the Paho MQTT C Client library? I know  the Paho Asynchronous MQTT C Client Library have the automaticReconnect attribute to control reconnect model。Is there hava a attribute into the Paho MQTT C Client library  like the automaticReconnect into the Paho Asynchronous MQTT C Client Library? please give me a reply, thanks

**Comment by icraggs** [comment]
Hello.  No, there is no equivalent in the MQTTClient API.  You have to call Connect in the connectionLost callback.  

I'll take this as a request to add automatic reconnect to the MQTTClient API.

**Comment by icraggs** [comment]
I'm not going to add this any time soon to the synchronous library.
