### ISSUE TITLE
not getting .exe file of test3 and test5 

### ISSUE THREAD

**Issue by sw-tt-chandershekharsuthar** [eclipse-paho/paho.mqtt.c#480]
Hello Sir I'm in visual studio 2017with windows 7 OS. I build this project with Cmake and get only output file (.exe) for test(1,2,4,6,8,9) but there are something is missing and I'm not able to get the .exe for test3 and test5 and getting error like........................

1>------ Build started: Project: paho-mqtt3cs, Configuration: Debug|Win32 ------
  Clients.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\clients.h(30): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  Log.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\sslsocket.h(29): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  MQTTClient.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\clients.h(30): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  MQTTPacket.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\sslsocket.h(29): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  MQTTPacketOut.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\sslsocket.h(29): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  MQTTPersistence.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\clients.h(30): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  MQTTProtocolClient.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\sslsocket.h(29): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  MQTTProtocolOut.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\sslsocket.h(29): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  Socket.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\socketbuffer.h(28): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  SocketBuffer.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\socketbuffer.h(28): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  SSLSocket.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\socketbuffer.h(28): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  StackTrace.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\src\clients.h(30): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
  Generating Code...
2>------ Build started: Project: test3, Configuration: Debug|Win32 ------
  test3.c
d:\work\msvs17\allnew\paho.mqtt.c-master\pahomaster\test\test3.c(29): fatal error C1083: Cannot open include file: 'openssl/applink.c': No such file or directory
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ========== 

I include the openssl files and link with my project too but don't know what is the problem

**Comment by icraggs** [comment]
Hi.  The build can't find your OpenSSL installation.  If you look in src/CMakeLists.txt you'll see that the default location on windows is:

IF (WIN32)
      SET(OPENSSL_SEARCH_PATH "C:/OpenSSL-Win64")
ENDIF ()

So the easiest approach is to ensure your OpenSSL installation is in that directory.

**Comment by icraggs** [comment]
I'm assuming this response is adequate.
