### ISSUE TITLE
How can I know my message have sent successfully?

### ISSUE THREAD

**Issue by toBeGeekNo1** [eclipse-paho/paho.mqtt.c#481]
hello, how can I know my message have sent successfully? I saw some demo, It seems that they use the MQTTClient_deliveryToken type variable  token pass to  the MQTTClient_publishMessage() ，method，and then compare the token whether or not  is 0,  I'm not sure about it can work, please give me an sure answer，thank you

**Comment by icraggs** [comment]
It depends which QoS you are using.  

With QoS 0, there is no ack, so if the MQTTClient_publishMessage() call completes successfully, the packet has been written to TCP, and there is no other feedback.  If you want to be sure that message has arrived, you will have to rely on a response from the receiving application (another MQTT publish).

With QoS 1 and 2, a delivery token is returned from the publish call.  The completion of the publish can be determined by:

1) Setting the deliveryComplete callback.  When the callback function is called, you're done.

2) Calling getPendingDeliveryTokens and checking if the token you are interested in is in the returned list

3) Calling waitForCompletion().  This blocks until the publish is complete.

**Comment by icraggs** [comment]
I'm assuming this is answered.
