### ISSUE TITLE
"make install" is broken on OS X (Darwin)

### ISSUE THREAD

**Issue by rdasgupt** [eclipse-paho/paho.mqtt.c#483]
After successful build, tried to install the library on default location "/usr/local".
Install step is not creating required links. 

Contents of /usr/local/lib:
lrwxr-xr-x   1 root      admin         19 Jun 11 13:07 libpaho-mqtt3a.so -> libpaho-mqtt3a.so.1
-rw-r--r--   1 root      admin     132488 Jun 11 13:07 libpaho-mqtt3a.so.1.0
lrwxr-xr-x   1 root      admin         20 Jun 11 13:07 libpaho-mqtt3as.so -> libpaho-mqtt3as.so.1
-rw-r--r--   1 root      admin     148544 Jun 11 13:07 libpaho-mqtt3as.so.1.0
lrwxr-xr-x   1 root      admin         19 Jun 11 13:07 libpaho-mqtt3c.so -> libpaho-mqtt3c.so.1
-rw-r--r--   1 root      admin     117944 Jun 11 13:07 libpaho-mqtt3c.so.1.0
lrwxr-xr-x   1 root      admin         20 Jun 11 13:07 libpaho-mqtt3cs.so -> libpaho-mqtt3cs.so.1
-rw-r--r--   1 root      admin     138080 Jun 11 13:07 libpaho-mqtt3cs.so.1.0

Following links are missing:

 libpaho-mqtt3a.so.1 -> libpaho-mqtt3a.so.1.0
 libpaho-mqtt3as.so.1 -> libpaho-mqtt3as.so.1.0
 libpaho-mqtt3c.so.1 -> libpaho-mqtt3c.so.1.0
 libpaho-mqtt3cs.so.1 -> libpaho-mqtt3cs.so.1.0

**Comment by icraggs** [comment]
Hi Ranjan.  Do you have a fix for it?

**Comment by rdasgupt** [comment]
Updated install and uninstall rule that will work on all. Note that TABs may not show up in the GitHub comment.

install: build
        mkdir -p $(DESTDIR)$(PREFIX)${includedir}
        $(INSTALL_DATA) ${INSTALL_OPTS} ${MQTTLIB_C_TARGET} $(DESTDIR)${libdir}
        $(INSTALL_DATA) ${INSTALL_OPTS} ${MQTTLIB_CS_TARGET} $(DESTDIR)${libdir}
        $(INSTALL_DATA) ${INSTALL_OPTS} ${MQTTLIB_A_TARGET} $(DESTDIR)${libdir}
        $(INSTALL_DATA) ${INSTALL_OPTS} ${MQTTLIB_AS_TARGET} $(DESTDIR)${libdir}
        $(INSTALL_PROGRAM) ${INSTALL_OPTS} ${MQTTVERSION_TARGET} $(DESTDIR)${bindir}
        $(LDCONFIG) $(DESTDIR)${libdir}
        @if test ! -f $(DESTDIR)${blddir}/lib$(MQTTLIB_C).so; then ln -s lib$(MQTTLIB_C).so.${MAJOR_VERSION} $(DESTDIR)${libdir}/lib$(MQTTLIB_C).so; fi
        @if test ! -f $(DESTDIR)${libdir}/lib$(MQTTLIB_CS).so; then ln -s lib$(MQTTLIB_CS).so.${MAJOR_VERSION} $(DESTDIR)${libdir}/lib$(MQTTLIB_CS).so; fi
        @if test ! -f $(DESTDIR)${libdir}/lib$(MQTTLIB_A).so; then ln -s lib$(MQTTLIB_A).so.${MAJOR_VERSION} $(DESTDIR)${libdir}/lib$(MQTTLIB_A).so; fi
        @if test ! -f $(DESTDIR)${libdir}/lib$(MQTTLIB_AS).so; then ln -s lib$(MQTTLIB_AS).so.${MAJOR_VERSION} $(DESTDIR)${libdir}/lib$(MQTTLIB_AS).so; fi
        @if test ! -f $(DESTDIR)${blddir}/lib$(MQTTLIB_C).so.${MAJOR_VERSION}; then ln -s lib$(MQTTLIB_C).so.${VERSION} $(DESTDIR)${blddir}/lib$(MQTTLIB_C).so.${MAJOR_VERSION}; fi
        @if test ! -f $(DESTDIR)${libdir}/lib$(MQTTLIB_CS).so.${MAJOR_VERSION}; then ln -s lib$(MQTTLIB_CS).so.${VERSION} $(DESTDIR)${libdir}/lib$(MQTTLIB_CS).so.${MAJOR_VERSION}; fi
        @if test ! -f $(DESTDIR)${libdir}/lib$(MQTTLIB_A).so.${MAJOR_VERSION}; then ln -s lib$(MQTTLIB_A).so.${VERSION} $(DESTDIR)${libdir}/lib$(MQTTLIB_A).so.${MAJOR_VERSION}; fi
        @if test ! -f $(DESTDIR)${libdir}/lib$(MQTTLIB_AS).so.${MAJOR_VERSION}; then ln -s lib$(MQTTLIB_AS).so.${VERSION} $(DESTDIR)${libdir}/lib$(MQTTLIB_AS).so.${MAJOR_VERSION}; fi
        $(INSTALL_DATA) ${srcdir}/MQTTAsync.h $(DESTDIR)${includedir}
        $(INSTALL_DATA) ${srcdir}/MQTTClient.h $(DESTDIR)${includedir}
        $(INSTALL_DATA) ${srcdir}/MQTTClientPersistence.h $(DESTDIR)${includedir}

uninstall:
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_C).so.${VERSION}
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_CS).so.${VERSION}
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_A).so.${VERSION}
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_AS).so.${VERSION}
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_C).so.${MAJOR_VERSION}
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_CS).so.${MAJOR_VERSION}
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_A).so.${MAJOR_VERSION}
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_AS).so.${MAJOR_VERSION}
        rm $(DESTDIR)${bindir}/MQTTVersion
        $(LDCONFIG) $(DESTDIR)${libdir}
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_C).so
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_CS).so
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_A).so
        rm $(DESTDIR)${libdir}/lib$(MQTTLIB_AS).so
        rm $(DESTDIR)${includedir}/MQTTAsync.h
        rm $(DESTDIR)${includedir}/MQTTClient.h
        rm $(DESTDIR)${includedir}/MQTTClientPersistence.h

**Comment by icraggs** [comment]
Fix added to the develop branch.  Thanks!
