### ISSUE TITLE
CMake problem to generate static libraries

### ISSUE THREAD

**Issue by dominikheinz** [eclipse-paho/paho.mqtt.c#484]
I am trying to compile the static libraries (The *.a files).
Here is my build-script:

```
git clone https://github.com/eclipse/paho.mqtt.c.git
cd paho.mqtt.c
make
currentpath="$PWD"
echo "$currentpath"
cmake -DPAHO_BUILD_STATIC=TRUE -DPAHO_WITH_SSL=FALSE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=FALSE "$currentpath"
```

The script runs to the end without a problem but the static libraries are not being generated?
What am I missing?

**Comment by baldoalessandro** [comment]
After running `cmake` you should build the package, as reported in the README:

> To compile/link the binaries and to generate packages, simply invoke `ninja package` or `make -j <number-of-cores-to-use> package` after CMake.

I believe the `make` command in your script is not necessary.

**Comment by icraggs** [comment]
Also there are examples of build scripts, travis-build.sh for Linux/MacOS, and cbuild.bat for Windows.
