### ISSUE TITLE
pselect/external event loop in C

### ISSUE THREAD

**Issue by RobertBerger** [eclipse-paho/paho.mqtt.c#485]
Hi,

I would like to use paho.mqtt.c with my own external event loop.

something like:

pselect()
unblock if new mqtt message arrives
some logic
publish mqtt message

Is this possible at all?

If yes, can you please give me a hint on how this could work?

**Comment by icraggs** [comment]
Hi.  If you want to do this, I suggest you take a look at the embedded C client.  It's structured in layers so you can pick and choose the pieces you want, and the code is much simpler.

https://github.com/eclipse/paho.mqtt.embedded-c

**Comment by icraggs** [comment]
I'm going to close this now, thanks.
