### ISSUE TITLE
Logic Error at line 746 of MQTTClient.c

### ISSUE THREAD

**Issue by GitSzuKai** [eclipse-paho/paho.mqtt.c#489]
I was building an async publish program. In my program, it only publish message so I don't think MQTTClient_messageArrived is necessary. I called MQTTClient_setCallbacks as follow. 
MQTTClient_setCallbacks(client, NULL, connlost, NULL, delivered);
I found that I must provide MQTTClient_messageArrived* ma to MQTTClient_setCallbacks otherwise MQTTCLIENT_FAILURE failure will be returned. 
I checked MQTTClient_setCallbacks in MQTTClient.c, it checks if ma is present if not return MQTTCLIENT_FAILURE.

**Comment by icraggs** [comment]
This was a deliberate decision I made at the time.  It seems reasonable to require the setting of the messageArrived callback, just to know if a message does arrive, otherwise the client library just has to throw it away.  

I don't think it's a big overhead.
