### ISSUE TITLE
add curl in test2

### ISSUE THREAD

**Issue by sw-tt-chandershekharsuthar** [eclipse-paho/paho.mqtt.c#490]
hello everyone,
I have to add curl in that paho projects (like with test2) I want to get some data from webpage so how can add the curl with that eclipse/paho.mqtt.c I'm working in visual studio 2017 IDE on windows 7 (64bit) OS

**Comment by icraggs** [comment]
I find your question difficult to follow.  curl is a Unix-like utility - I think on Windows only available with Cygwin or similar environment.

**Comment by icraggs** [comment]
Now dealt with in #493
