### ISSUE TITLE
About the reconnect interval

### ISSUE THREAD

**Issue by DavidDong33** [eclipse-paho/paho.mqtt.c#492]
When it disconnect.
(1) I want it do re-connect never stop.
How to do? Maybe some flag or parameter cand set?!

(2)
maxRetryInterval = 60;
what it mean? max re-connect interval?
when re-connect interval = 120 stop?

**Comment by icraggs** [comment]
Auto reconnect is only available in the MQTTAsync client at the moment.   It is switched on by using the automaticReconnect flag in the connect options.

The first reconnect attempt is made after minRetryInterval seconds.  On each failed attempt the interval is doubled, but no more than maxRetryInterval.

**Comment by DavidDong33** [comment]
Hi,  
Thank you for repay.

I can into "re-connect" processing, but i want to know, when it stop? (if it's always connect failed.)
or it do "re-connect" ~"re-connect" ~"re-connect"....never stop?

**Comment by icraggs** [comment]
It won't stop.  It'll keep retrying at the maximum reconnect interval.
