### ISSUE TITLE
compile under OS400 

### ISSUE THREAD

**Issue by gbaracchino** [eclipse-paho/paho.mqtt.c#494]
Hi 
I've succesfully run cmake with

cmake -DCMAKE_CXX_COMPILER=/QOpenSys/opt/freeware/bin/g++  -DCMAKE_C_COMPILER=/QOpenSys/opt/freeware/bin/gcc . 

but when it arrives at 51% I receive this error:

[ 45%] Built target common_obj                                            
[ 48%] Building C object src/CMakeFiles/paho-mqtt3a.dir/MQTTAsync.c.obj   
[ 51%] Linking C shared library libpaho-mqtt3a.so                         
**ld: 0711-317 ERRORE: Simbolo non definito : .pthread_attr_init            
[..omissis,,.]
ld: 0711-317 ERRORE: Simbolo non definito : .pthread_mutexattr_settype**          
**ld: 0711-317 ERRORE: Simbolo non definito : .timersub**                           
ld: 0711-345 Usare l'opzione -bloadmap o -bnoquiet per ulteriori informazioni.  
collect2: ld returned 8 exit status                                             
make: 1254-004 Il codice errore per l'ultimo comando è 1.                         

I've manually patched the file including the -pthread 
src\CMakeFiles\paho-mqtt3a.dir\link.txt
src\CMakeFiles\paho-mqtt3c.dir\link.txt

I've modified as attached the OsWrapper.h

I've put on top of the tests (test1, test2, etc) the include "OsWrapper.h" in order to avoid the timersub error.

Please find attached the patched files and my CMakeCCompiler  CMakeSystem files in order to patch the build process accordingly

[PatchPahoMqtt_OS400.zip](https://github.com/eclipse/paho.mqtt.c/files/2141369/PatchPahoMqtt_OS400.zip)

**Comment by gbaracchino** [comment]
Even if the compile is successfull the test program and fails on this instruction in Thread.c:
Thread_create_sem -> rc = sem_init(sem, 0, 0)
The system, when it reaches the "sem_init" do a core dump and exits anomally.

I think there is a problem in the resource/libraries linking during the compile phase. 
My previous post is not enough..
Can someone help me?

Moreove I think that I should enable the AIX define in order to use the native ntimersub instead of the one included into the oswrapper.h.

**Comment by gbaracchino** [comment]
I think in OS400 is not implementing sem_init and sem_open.
Does it works on OS390  or AIX ??

**Comment by icraggs** [comment]
I built for AIX a long time ago, but not for several years, so I don't know if it still works there or not.

Linux, Windows and MacOS are the only OSes I test with.

The embedded C client is much simpler (and less featured) but it is much easier to port, if you want to consider that as an option.

**Comment by icraggs** [comment]
If a PR is submitted to allow this to work at some point, I'll look at it.
