### ISSUE TITLE
Reconnect race condition

### ISSUE THREAD

**Issue by altenmueller** [eclipse-paho/paho.mqtt.c#496]
Hi, it seems like I'm experiencing a race condition in the reconnection logic in paho.mqtt.c. My code is actually using paho.mqtt.cpp, but given that it's a wrapper, I'm assuming it's okay to post here (let me know if that's not the case).

Steps to reproduce:

1. Use the `async_subscriber.cpp` sample code to connect to an MQTT broker from here: https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/samples/async_subscribe.cpp . In my case, I removed the "sleep 2500ms" in the reconnect function, which seemed to make the below race condition occur more often.
2. Start it up, and start publishing on the topic with a frequency of about once per second. Observe the messages being printed by the async_subscriber.
3. Use the `tcpkill` utility (part of `dsniff` package on Linux) to continuously issue TCP reset messages:
```
sudo tcpkill -i eth1 -3 port 1883
```
4. Observe the async_subscriber continuously reconnecting.

If you wait long enough (in my case, several hours), it will eventually stop reconnecting and just hang there. This is the console output that I see:

```
Connection lost
Reconnecting.
Reconnection success
Subscription success (token: 1)
	token topic: 'rfidEvents', ...


Connection lost
Reconnecting.
Reconnection success
Subscription success (token: 1)
	token topic: 'rfidEvents', ...


Connection lost
Reconnecting.
Reconnection success
Subscription success (token: 1)
	token topic: 'rfidEvents', ...


Connection lost
Reconnecting.
```

It seems like the `connect()` function doesn't work at this point, doesn't issue any error or callback, and now we're just in a stuck state where we can't recover. It seems like adding a sleep() function before the connect() is issued reduces the likelihood that this occurs. However, even sleeping 100ms, I've still been able to reproduce this "hung" state, and I would prefer if we could be certain that this state will never occur.

I've tried to enable trace logging, but adding the environment variables `MQTT_C_CLIENT_TRACE=ON` and `MQTT_C_CLIENT_TRACE_LEVEL=MAXIMUM` didn't produce the Log() output that I would have expected when I look inside the MQTTAsync.c file. Let me know if I'm missing anything there, or if I can provide any additional details that might help. Thanks!

**Comment by icraggs** [comment]
Do you know which release of the C client you are using?  1.2.1 is the latest.

**Comment by icraggs** [comment]
I think this is probably fixed with new releases.  If not, we'll need some more information.
