### ISSUE TITLE
Update Makefile to build in Cygwin

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#5]
migrated from Bugzilla [#486095](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486095)
status UNCONFIRMED severity _enhancement_ in component _MQTT-C_ for _1.2_
Reported in version _1.0_ on platform _PC_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[0001-Update-Makefile-to-support-Cygwin.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=259254)_ (ID 259254)
- _[0001-Update-Makefile-to-support-Cygwin.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=259264)_ (ID 259264)

On 2016-01-19 06:28:14 -0500, Stavros Vagionitis wrote:

> Created attachment 259254
> Patch for updating the Makefile to build in Cygwin
> 
> Hi all,
> 
> Recently I needed to build the paho client library in Cygwin, but there was no support in the Makefile. So I made some changes in the Makefile and I was able to build it. I have attached a patch with the changes I made.
> ## Changes
> 
> Next following the major changes in order to build the libraries in Cygwin:
>     - In Cygwin the libraries need executable permissions in order to work,
>       currently during installation the libraries have only read/write
>       permissions (`-m 0644`). Removing the option `-m 0644` from the install
>       command, the libraries are installed with their default permissions.
>     - The filename format of the libraries in Cygwin is different from Linux and
>       also have different options to build shared libraries. More information can
>       be found in https://cygwin.com/cygwin-ug-net/dll.html
>     - The `ldconfig` utility does not exist in Cygwin, so the `install` and `uninstall`
>       targets needed to modified.
> ## Testing
> 
> I was able to run the test and sample files. The testing has been performed on a Ubuntu 14.04 64 bit and a Windows 7 Enterprise 64 bit machine. The Windows machine had installed Cygwin 2.4.0 64 bit.
> 
> Please review my changes.
> 
> Regards,
> 
> Stavros

On 2016-01-19 13:00:48 -0500, Stavros Vagionitis wrote:

> Created attachment 259264
> Latest Patch for updating the Makefile to build in Cygwin
> 
> Ignore the previous patch, I had added accidentally the CFLAGS of the Darwin to Cygwin. With this patch I removed them.

**Comment by icraggs** [comment]
Cygwin build can now be done with CMake.
