### ISSUE TITLE
cmake files not installing properly

### ISSUE THREAD

**Issue by eujean** [eclipse-paho/paho.mqtt.c#500]
It seems MQTTAsync.h depends on:

- MQTTProperties.h
- MQTTSubscribeOpts.h
- MQTTReasonCodes.h

which aren't included in the files to be installed according to CMakeLists.txt

Seems as if these files are relatively new and were simply forgotten to be added unless I am missing something?

Regards
E

**Comment by eujean** [comment]
It seems there is already a pull-request #499 for this issue however the author opted to modify only the base directory makefile.

**Comment by alexamirante** [comment]
I experienced the same issue and came up with #499. I'm not familiar with cmake so I don't know whether this should also be added to `CMakeLists.txt`. There's also #497 which only adds the new libraries in the `CMakeLists.txt` but not in the `Makefile`, which didn't seem to work for me.

**Comment by eujean** [comment]
Yes both methods should work depending on the method used to compile the libraries. Therefore both #499 and #497 should probably be combined for the best solution.

**Comment by icraggs** [comment]
I've merged the PR now.  While I'm finishing off the 1.3 release, even the master branch is likely to be a bit unstable.  If you need it, there is the 1.2.1 release.

**Comment by icraggs** [comment]
Actually I've merged both PRs, so this should be fixed.  Thanks.
