### ISSUE TITLE
Const or not const payload in MQTTClient_message struct ?

### ISSUE THREAD

**Issue by destroyedlolo** [eclipse-paho/paho.mqtt.c#505]
Hi all,

Is payload modified by **MQTTClient_publishMessage()** ?
If not, is it possible to change this field to const void * ?

Thanks

Laurent

**Comment by destroyedlolo** [comment]
Thanks for your reply.
I'm not sure that putting "const" for input parameter will change anything as it's only mean to the compiler that the function will not change the content. After passing a "void *" as a "const void *" will note raise any alert whereas passing a "const void *" as a "void *" will emit a warning : your function may change the content.

**Comment by icraggs** [comment]
Sometimes, the adding of a const modifier requires existing applications to have a cast or change the type of variables.  That's the type of change which I want to avoid, as that would require a move to version 2.x.x for a backward incompatible change.  

I changed it, seems ok.

**Comment by destroyedlolo** [comment]
ok, thanks a lot :)
