### ISSUE TITLE
Connection to MQTT broker using SLL error,

### ISSUE THREAD

**Issue by houdarh** [eclipse-paho/paho.mqtt.c#508]
I have the following error when I try to connect using a certificate (.PEM), 
but with the client mqtt.fx it's working well.

.....
27/07 16:07:07 654|MSG: TRACE_PROTOCOL : 20180727 160707.651 (4840)     (4)> MQTTStrncpy:773

27/07 16:07:07 654|MSG: TRACE_PROTOCOL : 20180727 160707.651 the src string is truncated

27/07 16:07:07 654|MSG: TRACE_PROTOCOL : 20180727 160707.651 (4840)     (4)< MQTTStrncpy:783

27/07 16:07:07 654|MSG: TRACE_PROTOCOL : 20180727 160707.651 (4840)    (3)< SSLSocket_setSocketForSSL:660 (1)

27/07 16:07:07 655|MSG: TRACE_PROTOCOL : 20180727 160707.651 (4840)    (3)> SSLSocket_connect:671

27/07 16:07:07 655|MSG: LOG_ERROR : 20180727 160707.651 SSL handshake started write:unknown:unknown

27/07 16:07:07 655|MSG: LOG_ERROR : 20180727 160707.651 SSL state connect:before/connect initialization:(NONE)

27/07 16:07:07 655|MSG: LOG_ERROR : 20180727 160707.651 sent 771 256 buflen 5

27/07 16:07:07 656|MSG: LOG_ERROR : 20180727 160707.651 sent 771 22 buflen 350

27/07 16:07:07 656|MSG: LOG_ERROR : 20180727 160707.656 SSL state connect:SSLv2/v3 write client hello A:(NONE)

27/07 16:07:07 657|MSG: LOG_ERROR : 20180727 160707.656 received 0 256 buflen 5

27/07 16:07:07 657|MSG: LOG_ERROR : 20180727 160707.656 received 771 22 buflen 74

27/07 16:07:07 657|MSG: LOG_ERROR : 20180727 160707.656 SSL state connect:SSLv3 read server hello A:(NONE)

27/07 16:07:07 657|MSG: LOG_ERROR : 20180727 160707.656 received 0 256 buflen 5

27/07 16:07:07 657|MSG: LOG_ERROR : 20180727 160707.656 received 771 22 buflen 5730

27/07 16:07:07 657|MSG: LOG_ERROR : 20180727 160707.656 sent 0 256 buflen 5

27/07 16:07:07 658|MSG: LOG_ERROR : 20180727 160707.656 sent 771 21 buflen 2

27/07 16:07:07 658|MSG: LOG_ERROR : 20180727 160707.656 SSL alert write:fatal:unknown CA

27/07 16:07:07 658|MSG: LOG_ERROR : 20180727 160707.656 SSL connect:error

27/07 16:07:07 658|MSG: LOG_ERROR : 20180727 160707.656 SSL connect:error

27/07 16:07:07 659|MSG: TRACE_PROTOCOL : 20180727 160707.656 (4840)     (4)> SSLSocket_error:94

27/07 16:07:07 659|MSG: TRACE_PROTOCOL : 20180727 160707.656 SSLSocket error (1) in SSL_connect for socket 540 rc -1 errno 0 No error

Is there someone who can explain me what this error means?

thank you in advance,

**Comment by icraggs** [comment]
The trace says, unknown CA:

27/07 16:07:07 658|MSG: LOG_ERROR : 20180727 160707.656 SSL alert write:fatal:unknown CA

If the certificate you have is used to validate the server certificate then you need to use the 'truststore' SSL option.

**Comment by houdarh** [comment]
Do you mean : {void set_trust_store(const string& trustStore);} ?? Because that's the function, that i use to passing my certificate PEM file.

**Comment by icraggs** [comment]
What options did you use with mqtt.fx?  Does the certificate file contain the server CA to trust?

**Comment by houdarh** [comment]
- With mqtt.fx I use **CA certificate file** :

![image](https://user-images.githubusercontent.com/39825469/43443703-ec9c8238-94a1-11e8-85e2-c2d9eb5df246.png)

- I have the following certificate architecture :
Root CA
Intermediate CA
Issuing CA
**Certificate**


In the certificate file I have only the **Certificate** chain, do I have to combine in the same PEM file the Root CA, Intermediate CA and Issuing CA??

**Comment by icraggs** [comment]
You need to allow OpenSSL to have access to the CA certificate, which sounds like the whole chain in your case.  I don't know how mqtt.fx works without that.

**Comment by houdarh** [comment]
OK, thank you.
