### ISSUE TITLE
MQTTClient_connect() returns error -8

### ISSUE THREAD

**Issue by destroyedlolo** [eclipse-paho/paho.mqtt.c#512]
Hello,

I just upgraded paho.mqtt.c but now MQTTClient_connect() is failing with error code -8.
What does it mean ?

The same code works perfectly before the update.
I reinstalled v1.2.1 from the tarball and the issue is gone.

Thanks

Laurent

**Comment by icraggs** [comment]
Seems like I erroneously updated the lower bound structure check.

**Comment by icraggs** [comment]
If you do try my fix out, it would be great if you let me know.  Thanks!

**Comment by icraggs** [comment]
I think this is fixed.
