### ISSUE TITLE
Cppcheck throws resource leak in Log.c

### ISSUE THREAD

**Issue by MilanVidic** [eclipse-paho/paho.mqtt.c#514]
Cppcheck throws resource leak in Log.c file at line 144:
`trace_destination = stdout;`
Did it falsely detect situation when `trace_destination` is not closed?

**Comment by icraggs** [comment]
Well stdout is a standard stream for every process, along with stdin and stderr, it's not opened by the library in this case, just referred to, so I wouldn't expect to have to close it explicitly either.
