### ISSUE TITLE
PAHO_WITH_SSL build option doesn't have sufficient preprocessor guards

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse-paho/paho.mqtt.c#516]
CMakeLists has a build option PAHO_WITH_SSL. But in _connect_options.h_, the header _mqtt/ssl_options.h_ is not preprocessor guarded. A `make install` doesn't install the _ssl_options.h_ when we turn off PAHO_WITH_SSL

**Comment by icraggs** [comment]
I don't think I recognise those header file names.  Where are they?

**Comment by kiranpradeep** [comment]
@icraggs Sorry. I raised in wrong repo. It was in paho.mqtt.cpp. Reraised at paho.mqtt.cpp[[1](https://github.com/eclipse/paho.mqtt.cpp/issues/156)]
