### ISSUE TITLE
Incomplete documentation for retryInterval

### ISSUE THREAD

**Issue by tbeu** [eclipse-paho/paho.mqtt.c#528]
The documentation comment for retryInterval is incomplete in both headers.
https://github.com/eclipse/paho.mqtt.c/blob/d54d56c77833b212ce3cd067442eccf8f46449d5/src/MQTTClient.h#L792-L795
https://github.com/eclipse/paho.mqtt.c/blob/d54d56c77833b212ce3cd067442eccf8f46449d5/src/MQTTAsync.h#L1028-L1031

**Comment by tbeu** [comment]
Can you please clarify why 0 is the recommended setting, but MQTTClient_connectOptions_initializer defaults to 20 for the retryInterval. Thanks.

**Comment by icraggs** [comment]
Historical accident.  We should change the default to 0, to match that in MQTTAsync.  In fact it isn't used at all in MQTTClient - equivalent to 0.  I'll fix that too.
