### ISSUE TITLE
reconnect after connection lost causes crashing the application

### ISSUE THREAD

**Issue by Aljumaili85** [eclipse-paho/paho.mqtt.c#532]
Hi there, 
Successfully I manged to build the project and I had every thing work well except the fact that, when I use the  MQTTAsync_subscribe application, its crashed after trying to reconnect to the broker (The Broker is stopped relaunched by me Intentionally  just for testing )
I even tried the Pre-built binaries for Windows and  (almost all ) old versions, but all they have the same issue.
The attached image is a screenshot of the problem debug result of Visual Studio

I appreciate your help .
![issue](https://user-images.githubusercontent.com/22834680/44918293-d353e800-ad3a-11e8-9409-89e447a82043.jpg)

**Comment by tbeu** [comment]
Did you build paho-mqtt3a.dll with debug symbols?

**Comment by tbeu** [comment]
Sure, it helps to locate the access violation. Do you use the current master or the latest release?

**Comment by icraggs** [comment]
I'm finishing off the MQTT V5 release at the moment.    The paho_c_sub application is one which I use and which should work reliably, and does pretty much the same thing.  The MQTTAsync_subscribe sample is a very simple example written a long time ago (and not by me).  I am thinking of removing it, in favour of paho_c_sub (and paho_cs_sub).   If anyone has thoughts on that, I'm interested to hear them.

**Comment by icraggs** [comment]
Actually, I'm not sure what's going on here.  I try the same scenario as you and I don't get an access violation.   I tried with the latest code, and with 1.2 downloaded.  Still, trying paho_c_sub.exe instead would be interesting.

**Comment by Aljumaili85** [comment]
thanks @icraggs,
I will try to re-compile it using the latest code and run the paho_c_sub.exe instead . I will Let you know soon . Thanks again.

**Comment by Aljumaili85** [comment]
Hi @icraggs , I compile the latest code using my personal computer  and I get rid of this error, I don't know how and why but its works, so we can close this issue . thanks for @tbeu also .
