### ISSUE TITLE
CPU spin @ 100%

### ISSUE THREAD

**Issue by jnicholls** [eclipse-paho/paho.mqtt.c#535]
I am utilizing the Rust bindings that wrap MQTTAsync. I've noticed that the I/O thread for the client is spinning at 100% CPU. I dug in just a little bit and saw that the client is using `select` (and not more performant albeit non-portable APIs such as epoll on Linux, kqueue on OS X, and IOCP/AsyncIO on Windows), but I do not think it is properly blocking. I am running on Debian Stretch Linux with a 4.9.0 kernel. I am using a `master` version of this library, i.e. newer than the latest 1.2.1 release, which contains some MQTT v5 stuff.

Has anyone seen similar behavior? I'm going to downgrade to v1.2.1 just to see if I notice the same behavior. ~Also, I would recommend using something like https://github.com/libuv/libuv over using `select`. However it is more of an IOCP callback-style paradigm and not at all like coding for kqueue and epoll (plus it requires more allocations which is bad); so I'd at least recommend using epoll directly on Linux for the high-performance server use cases that most Linux client applications will desire.~ I retract that, seeing as there will not be many sockets open at a time; I had to remind myself that this is a client not a server library :)

**Comment by jnicholls** [comment]
I've verified that v1.2.1 does *not* have this issue. It appears to be an issue with `HEAD`.

**Comment by milligan22963** [comment]
My app has been spinning at 60% or so and I it appears that in Thread.c there is something up with the call to clock_gettime(CLOCK_MONOTONIC, &cond_timeout);  (Line: 404)

Method: int Thread_wait_cond(cond_type condvar, int timeout)

I changed it to use CLOCK_REALTIME opposed to CLOCK_MONOTONIC and it appears to have addressed my issue - this is on Linux Mint 19 (Ubuntu) running 1.2.1 of the library.

Trace snippet:
20180906 214650.236 (1631164160)  (1)> MQTTAsync_checkTimeouts:1643
20180906 214650.236 (1631164160)  (1)< MQTTAsync_checkTimeouts:1717
20180906 214650.236 (1631164160)  (1)> Thread_wait_cond:397
20180906 214650.236 (1631164160)  (1)< Thread_wait_cond:412 (110)
20180906 214650.236 (1631164160)  (1)> MQTTAsync_checkTimeouts:1643
20180906 214650.236 (1631164160)  (1)< MQTTAsync_checkTimeouts:1717
20180906 214650.236 (1631164160)  (1)> Thread_wait_cond:397
20180906 214650.236 (1631164160)  (1)< Thread_wait_cond:412 (110)
20180906 214650.236 (1631164160)  (1)> MQTTAsync_checkTimeouts:1643
20180906 214650.236 (1631164160)  (1)< MQTTAsync_checkTimeouts:1717
20180906 214650.236 (1631164160)  (1)> Thread_wait_cond:397
20180906 214650.236 (1631164160)  (1)< Thread_wait_cond:412 (110)
20180906 214650.236 (1631164160)  (1)> MQTTAsync_checkTimeouts:1643
20180906 214650.236 (1631164160)  (1)< MQTTAsync_checkTimeouts:1717
20180906 214650.236 (1631164160)  (1)> Thread_wait_cond:397
20180906 214650.236 (1631164160)  (1)< Thread_wait_cond:412 (110)
20180906 214650.236 (1631164160)  (1)> MQTTAsync_checkTimeouts:1643
20180906 214650.236 (1631164160)  (1)< MQTTAsync_checkTimeouts:1717

**Comment by icraggs** [comment]
I reverted to CLOCK_REALTIME recently as 

pthread_condattr_setclock(&attr, CLOCK_MONOTONIC)

wasn't reporting an error on some systems if wasn't going to work in cond_timedwait.  The commit was added about 3 weeks ago: https://github.com/eclipse/paho.mqtt.c/commit/6c0a31e0992b1961527f7c451a0d35c1541a486d

**Comment by icraggs** [comment]
P.S.  I've used epoll for servers before.  But as you observe, this is a client library, and was intended to be easy to use above anything else.   I've shied away from changing the internals as I've plenty of other stuff to do :-)

Whether or not I've achieved ease of use is of course subjective and I don't really want to kick off that discussion here and now...

**Comment by jnicholls** [comment]
My copy of `master` was certainly more than 3 weeks old (but newer than 1.2.1) so I will close this ticket seeing as it is not an issue in either 1.2.1 or the latest on master.
