### ISSUE TITLE
ln: failed to create symbolic link '/usr/local/lib/libpaho-mqtt3c.so': File exists

### ISSUE THREAD

**Issue by ankitAMD** [eclipse-paho/paho.mqtt.c#536]
- [x] #root@d243f6716582:~ /paho.mqtt.c# sudo make install
mkdir -p build/output/samples
mkdir -p build/output/test
echo OSTYPE is Linux
OSTYPE is Linux
mkdir -p /usr/local/include
install -m 644  build/output/libpaho-mqtt3c.so.1.0 /usr/local/lib
install -m 644  build/output/libpaho-mqtt3cs.so.1.0 /usr/local/lib
install -m 644  build/output/libpaho-mqtt3a.so.1.0 /usr/local/lib
install -m 644  build/output/libpaho-mqtt3as.so.1.0 /usr/local/lib
install  build/output/paho_c_version /usr/local/bin
install  build/output/samples/paho_c_pub /usr/local/bin
install  build/output/samples/paho_c_sub /usr/local/bin
install  build/output/samples/paho_cs_pub /usr/local/bin
install  build/output/samples/paho_cs_sub /usr/local/bin
/sbin/ldconfig /usr/local/lib
ln -s libpaho-mqtt3c.so.1 /usr/local/lib/libpaho-mqtt3c.so
ln: failed to create symbolic link '/usr/local/lib/libpaho-mqtt3c.so':  File exists
Makefile:273: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by icraggs** [comment]
I always do a 'make uninstall' before a new install.  I don't know if there's a convention - I haven't found one.

**Comment by tkanoh** [comment]
How about using the -f option of the ln command?

**Comment by icraggs** [comment]
The -f option of ln looks like a good solution although it leaves the risk of old files being left around.

**Comment by Meghadoot** [comment]
@icraggs @tkanoh 
I did 'make uninstall' before running "sudo make install", but i'm facing the same issue.
Then i ran "ln -f -s libpaho-mqtt3c.so.1 /usr/local/lib/libpaho-mqtt3c.so" so as to forcefully create a symlink. 
and then if i run "sudo make install" then again facing the same error
Shown in figure:
![screenshot from 2019-01-30 02-00-33](https://user-images.githubusercontent.com/25079922/51950495-0953e000-2431-11e9-9401-bafd5f204934.png)

But with running "ldconfig -p | grep libpaho-mqtt3c" command, I can observe successful symlink creation.
Shown in snippet:
![screenshot from 2019-01-30 02-10-34](https://user-images.githubusercontent.com/25079922/51950826-62704380-2432-11e9-80b9-fe77afb52708.png)

Interestingly, if i compile any file (simple gcc compiler) with linking option -lpaho-mqtt3c. It is successful and also executable is working correctly. 
Shown in snippet: 
![screenshot from 2019-01-30 02-06-06](https://user-images.githubusercontent.com/25079922/51950685-c7776980-2431-11e9-8879-5c6a5116027b.png)

I'm new to software development. So, can you please elaborate this thing? Is it working correctly?

**Comment by raneeshgomez** [comment]
Does anyone have a solution for this? I'm running into the same error

**Comment by streamgao** [comment]
same here, would like to know the answer ...

**Comment by Mebus** [comment]
I get this:

```
[ 40%] Built target paho-cpp-objs
gmake[2]: *** No rule to make target '/usr/lib64/libpaho-mqtt3as.so', needed by 'src/libpaho-mqttpp3.so.1.0.1'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:95: src/CMakeFiles/paho-mqttpp3.dir/all] Error 2
gmake: *** [Makefile:152: all] Error 2
```
on Fedora 29 :disappointed: 

Mebus

**Comment by hanwin** [comment]
I did this and it worked:
`sudo make clean`
`sudo rm /usr/local/lib/libpaho-mqtt3*`
`make html`
`make && sudo make install`

**Comment by kYroL01** [comment]
@hanwin it works for me. Thanks
