### ISSUE TITLE
Missing Headers Files  in version 1.3.0  (eclipse-paho-mqtt-c-win32-1.3.0.zip)

### ISSUE THREAD

**Issue by rsaatpresys** [eclipse-paho/paho.mqtt.c#538]
I downloaded the latest release version 1.3.0  from eclipse site 

https://projects.eclipse.org/projects/technology.paho/downloads
https://www.eclipse.org/downloads/download.php?file=/paho/1.4/eclipse-paho-mqtt-c-win32-1.3.0.zip

and I think some headers files are missing in include directory like MQTTProperties.h  and MQTTReasonCodes.h. 

I can get these files from git , but I prefer to use in my project only the files from release package.

**Comment by icraggs** [comment]
This should be fixed now.
