### ISSUE TITLE
error codes for connect publish or subscribe failure

### ISSUE THREAD

**Issue by kushal4** [eclipse-paho/paho.mqtt.c#540]
hi,
Can you guys please elaborate to me about the meaning of each the error return codes for connect,publish,or subscribe failure.
thanks,
Kushal

**Comment by icraggs** [comment]
The return codes specific to the client library have descriptions in the header files, or the Doxygen documentation: 

https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/_m_q_t_t_client_8h.html#acba095704d79e5a1996389fa26203f73

Those specific to MQTT Version 3.1.1 are described in the standard: 

https://www.oasis-open.org/standards#mqttv3.1.1

There aren't many of those, mainly on connack, one on subscribe (0x80) a general failure.

I assume you're probably not using MQTT 5.0 yet, but the reason codes for that are named here: http://docs.oasis-open.org/mqtt/mqtt/v5.0/cs02/mqtt-v5.0-cs02.html#_Toc514345303

**Comment by kushal4** [comment]
I have one confusion regarding this , Specifically talking when there is subscribe failure from the client , i get a return code of 11 ,but corresponding to the 1st client doc link that you gave ,that doesnt match to it can you please elaborate regarding those failures :)

**Comment by kushal4** [comment]
No am not using mqtt version 5 yet

**Comment by icraggs** [comment]
I don't know how you are getting 11 (not -11?).  A client library trace (see the readme) might shed some light.

**Comment by kushal4** [comment]
okay seeing it :)

**Comment by kushal4** [comment]
when there is subscribe failure from the client end , the return code is -11 ,sorry positive value was a typo,in this case, how does it really match the scenario

**Comment by kushal4** [comment]
Sorry i didnt check the recent header files regarding this carefully.Now got it :) .Thanks
