### ISSUE TITLE
Proxy support for websocket

### ISSUE THREAD

**Issue by tkanoh** [eclipse-paho/paho.mqtt.c#541]
I wrote a patch that support to websoket via proxy. 

    https://github.com/tkanoh/paho.mqtt.c_proxy/blob/master/paho.mqtt.c_v1.3.0_proxy.diff

Processing for exceptional behavior such as connection timeout can not be described,
but I confirmd that It can connect to AWS IoT via Squid chache with synchronous connection.
Asynchronous and none SSL connection test is not done.           
It will be helpful if you can support proxy in future version.

**Comment by icraggs** [comment]
Hello.  Thank you for your work.  The best way to have this merged is to open a Pull Request.  This will take you through the Eclipse requirements for submitting contributions, like signing the contributor agreement.

**Comment by tkanoh** [comment]
Since we opened Pull Request # 542, I will close this issue.
Thanks.
