### ISSUE TITLE
[Win32] __stdcall vs __cdecl

### ISSUE THREAD

**Issue by holly7787** [eclipse-paho/paho.mqtt.c#543]
i have tryed to use this .dll in National Instruments Labwindows/CVI but get the undefined symbol when using .lib in the project.
if i call the .dll using GetProcAddress to the function, so explicit linking, doesn't give error and works correctly.

**Comment by holly7787** [comment]
i have created a new project and now works also with implicit.

**Comment by holly7787** [comment]
i have gone deeper in the problem, if the default calling convention (32-bit) is set to __stdcall give the problem described, if it's set to __cdecl works fine

**Comment by icraggs** [comment]
This document:

https://msdn.microsoft.com/en-us/library/zkwh89ks.aspx

says that __cdecl is the default calling convention for C/C+ programs, so I think this is what is expected.

**Comment by holly7787** [comment]
thank's for your reply.
i think it's good to know that __cdecl calling convention have to be used to compile the software implicitly.
it can be useful to other people.
