### ISSUE TITLE
Default port for websockets should be 80

### ISSUE THREAD

**Issue by windbender** [eclipse-paho/paho.mqtt.c#544]
When I compiled and ran the src/sample code I found that I had to include the port even when this should be implied.   For example, within src/samples/MQTTAsync_publish.c

#define ADDRESS     "ws://mybroker.mycompany.org"

did not work,  but

#define ADDRESS     "ws://mybroker.mycompany.org:80"

did.  Since. ws sort of implies HTTP and the default port for HTTP is port 80.  Why should we have to include port 80 on the address if we already have ws ?  

------

It appears that the problem here is in MQTTProtocolOut.c:73 where the code assume that the DEFAULT_PORT is 1883.  This is true in the case of tcp://.  but incorrect in the case of ws://

I would assume an equivalent problem would also exist in the case of a url starting with "wss://"

**Comment by icraggs** [comment]
I took the liberty of changing the issue description.  Thanks.
