### ISSUE TITLE
Using multiple clients MQTTAsync independently

### ISSUE THREAD

**Issue by SamZaitcev** [eclipse-paho/paho.mqtt.c#547]
I have a С++ program that needs several "MQTT" clients at the same time. The problem is that only the last client created is working.

I am using paho.mqtt.c async.

Does paho.mqtt.c support more than one client per program?

**Comment by icraggs** [comment]
Yes.  The tests directory contains several examples which are run on every build.  For instance, https://github.com/eclipse/paho.mqtt.c/blob/master/test/test8.c:

/*********************************************************************
Test3: More than one client object - simultaneous working.
*********************************************************************/
int test3(struct Options options)
{

**Comment by icraggs** [comment]
Take a trace at the normal level - that should give an idea of why the disconnect is being sent.

**Comment by SamZaitcev** [comment]
[Log with disconnect](https://github.com/eclipse/paho.mqtt.c/files/2410832/debug.txt) and [with sleep 1s](https://github.com/eclipse/paho.mqtt.c/files/2410853/good_log.txt)

**Comment by icraggs** [comment]
It looks like the MQTT server is deliberately closing the first connection in the first case.  Are you using different client ids for each connection?  Does the server have any other error message on its log?

**Comment by SamZaitcev** [comment]
Yes, I am using unique id for each MQTT client.

**Comment by SamZaitcev** [comment]
Really, 
`Client 670114029 already connected, closing old connection.`
std::rand() return the same value for second iteration ¯\_(ツ)_/¯

Thank you!

**Comment by icraggs** [comment]
Presumably, the one second wait caused the second client id to be correct.  I'm glad it's working.
