### ISSUE TITLE
Can't use SSL

### ISSUE THREAD

**Issue by Aterocana** [eclipse-paho/paho.mqtt.c#549]
I'm working with v1.3.0, this commit:
```
commit 9f715d0862a8e16099b5837c4e53a1bf6a6a0675 (HEAD -> master, tag: v1.3.0, origin/master, origin/develop, origin/HEAD)
Author: Ian Craggs <icraggs@uk.ibm.com>
Date:   Wed Sep 12 21:50:37 2018 +0100

    Stop Travis deploy which is not working
```

I'm trying to make the Async version work with SSL, so I started from `MQTTAsync_subscribe.c` example modifying it in this way:
```
/*******************************************************************************
 * Copyright (c) 2012, 2018 IBM Corp.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution. 
 *
 * The Eclipse Public License is available at 
 *   http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at 
 *   http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *    Ian Craggs - initial contribution
 *******************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "MQTTAsync.h"

#if !defined(WIN32)
#include <unistd.h>
#else
#include <windows.h>
#endif

#if defined(_WRS_KERNEL)
#include <OsWrapper.h>
#endif

#define SSL

#ifdef SSL
#define ADDRESS     "ssl://valid_address:8883"
#define CA_PATH		"/valid_path/ca.pem"
#define CERT_PATH		"/valid_path/cert.pem"
#else
#define ADDRESS     "tcp://valid_address:1883"
#endif
#define CLIENTID    "ExampleClientSub"
#define TOPIC       "valid/topic"
#define PAYLOAD     "Hello World!"
#define QOS         1
#define TIMEOUT     10000L
#define USERNAME 	"valid_username"
#define PASSWORD 	"valid_password"

volatile MQTTAsync_token deliveredtoken;

int disc_finished = 0;
int subscribed = 0;
int finished = 0;

void connlost(void *context, char *cause)
{
	MQTTAsync client = (MQTTAsync)context;
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	int rc;

	printf("\nConnection lost\n");
	if (cause)
		printf("     cause: %s\n", cause);

	printf("Reconnecting\n");
	conn_opts.keepAliveInterval = 20;
	conn_opts.cleansession = 1;
	if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start connect, return code %d\n", rc);
		finished = 1;
	}
}


int msgarrvd(void *context, char *topicName, int topicLen, MQTTAsync_message *message)
{
    int i;
    char* payloadptr;

    printf("Message arrived\n");
    printf("     topic: %s\n", topicName);
    printf("   message: ");

    payloadptr = message->payload;
    for(i=0; i<message->payloadlen; i++)
    {
        putchar(*payloadptr++);
    }
    putchar('\n');
    MQTTAsync_freeMessage(&message);
    MQTTAsync_free(topicName);
    return 1;
}


void onDisconnect(void* context, MQTTAsync_successData* response)
{
	printf("Successful disconnection\n");
	disc_finished = 1;
}


void onSubscribe(void* context, MQTTAsync_successData* response)
{
	printf("Subscribe succeeded\n");
	subscribed = 1;
}

void onSubscribeFailure(void* context, MQTTAsync_failureData* response)
{
	printf("Subscribe failed, rc %d\n", response ? response->code : 0);
	finished = 1;
}


void onConnectFailure(void* context, MQTTAsync_failureData* response)
{
	printf("Connect failed, rc %d\n", response ? response->code : 0);
	finished = 1;
}


void onConnect(void* context, MQTTAsync_successData* response)
{
	MQTTAsync client = (MQTTAsync)context;
	MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
	int rc;

	printf("Successful connection\n");

	printf("Subscribing to topic %s\nfor client %s using QoS%d\n\n"
           "Press Q<Enter> to quit\n\n", TOPIC, CLIENTID, QOS);
	opts.onSuccess = onSubscribe;
	opts.onFailure = onSubscribeFailure;
	opts.context = client;

	deliveredtoken = 0;

	if ((rc = MQTTAsync_subscribe(client, TOPIC, QOS, &opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start subscribe, return code %d\n", rc);
		exit(EXIT_FAILURE);
	}
}


int main(int argc, char* argv[])
{
	MQTTAsync client;
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	MQTTAsync_disconnectOptions disc_opts = MQTTAsync_disconnectOptions_initializer;
	int rc;
	int ch;

	MQTTAsync_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);

	MQTTAsync_setCallbacks(client, client, connlost, msgarrvd, NULL);

	conn_opts.keepAliveInterval = 20;
	conn_opts.cleansession = 1;
	conn_opts.onSuccess = onConnect;
	conn_opts.onFailure = onConnectFailure;
	conn_opts.context = client;
	conn_opts.username=USERNAME;
	conn_opts.password=PASSWORD;

	#ifdef SSL
	MQTTAsync_SSLOptions ssl_opts = MQTTAsync_SSLOptions_initializer;
	conn_opts.ssl = &ssl_opts;
    conn_opts.ssl->enableServerCertAuth = 1;
    // conn_opts.ssl->struct_version = 1;
    conn_opts.ssl->CApath = CA_PATH;
    conn_opts.ssl->trustStore = CERT_PATH;
    conn_opts.ssl->sslVersion = MQTT_SSL_VERSION_TLS_1_2;
	#endif
	
	if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start connect, return code %d\n", rc);
		exit(EXIT_FAILURE);
	}

	while	(!subscribed)
		#if defined(WIN32)
			Sleep(100);
		#else
			usleep(10000L);
		#endif

	if (finished)
		goto exit;

	do 
	{
		ch = getchar();
	} while (ch!='Q' && ch != 'q');

	disc_opts.onSuccess = onDisconnect;
	if ((rc = MQTTAsync_disconnect(client, &disc_opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start disconnect, return code %d\n", rc);
		exit(EXIT_FAILURE);
	}
 	while	(!disc_finished)
		#if defined(WIN32)
			Sleep(100);
		#else
			usleep(10000L);
		#endif

exit:
	MQTTAsync_destroy(&client);
 	return rc;
}
```
With `#define SSL` commented everything works fine, but with it decommented (as the code I reported here) I get:
```
> ./src/samples/MQTTAsync_subscribe                                             
[1]    29426 segmentation fault (core dumped)  ./src/samples/MQTTAsync_subscribe
```
the library is compiled in a Arch Linux system, exactly cloning it from repo, just changing `CMakeFileLists.txt` this way:
```
## build options
SET(PAHO_WITH_SSL TRUE CACHE BOOL "Flag that defines whether to build ssl-enabled binaries too. ")
SET(PAHO_BUILD_STATIC FALSE CACHE BOOL "Build static library")
SET(PAHO_BUILD_DOCUMENTATION FALSE CACHE BOOL "Create and install the HTML based API documentation (requires Doxygen)")
SET(PAHO_BUILD_SAMPLES TRUE CACHE BOOL "Build sample programs")
SET(PAHO_BUILD_DEB_PACKAGE FALSE CACHE BOOL "Build debian package")
SET(PAHO_ENABLE_TESTING TRUE CACHE BOOL "Build tests and run")
SET(PAHO_ENABLE_CPACK TRUE CACHE BOOL "Enable CPack")
```

Just to provide some more information:
```
> ls /usr/lib | grep ssl   
libevent_openssl-2.1.so.6
libevent_openssl-2.1.so.6.0.2
libevent_openssl.so
libssl3.so
libssl.so
libssl.so.1.0.0
libssl.so.1.1
libxmlsec1-openssl.so
libxmlsec1-openssl.so.1
libxmlsec1-openssl.so.1.2.26
openssl-1.0

> uname -a
Linux probook 4.18.8-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 15 20:34:48 UTC 2018 x86_64 GNU/Linux
```

Everything works fine with these same parameters with [paho.mqtt.go client ](https://github.com/eclipse/paho.mqtt.golang).
Am I missing something? I tried also with various combination of `MQTTAsync_SSLOptions` struct but I always get the segfault.

Thanks for the help.

**Comment by icraggs** [comment]
There are many tests in the repo, and the paho_c_pub and paho_c_sub utilities, which already use TLS.  You should be able to try out the utilities as they are built in the CMake build.  

If you are going to narrow down the cause of that particular error, then running under gdb and getting a backtrace and/or running a client trace (as described in the readme) are the places I would start.

**Comment by waltronix** [comment]
Hi @Aterocana,

I had a similar problem that took me quite a while to figure out.
You also have to set:
- conn_opts.serverURIcount 
- conn_opts.serverURIs
Because only then, inside the library a ssl connection will be established.

HTH
Andreas

**Comment by Aterocana** [comment]
By the way, if I compile it with `cmake .` I get:
```
> cmake ..
-- CMake version: 3.12.2
-- CMake system name: Linux
-- Timestamp is 2018-09-24T07:30:29Z
-- OpenSSL hints: 
-- OpenSSL headers found at /usr/include
-- OpenSSL library found at /lib/libssl.so
-- OpenSSL Crypto library found at /lib/libcrypto.so
-- OpenSSL hints: 
-- OpenSSL headers found at /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mauri/Documents/C/mqttlib
```
which make me think library should have SSL.

**Comment by icraggs** [comment]
This is a code snippet from paho_c_sub.c.  

    MQTTAsync_SSLOptions ssl_opts = MQTTAsync_SSLOptions_initializer;

    if (opts.connection && (strncmp(opts.connection, "ssl://", 6) == 0 ||
			strncmp(opts.connection, "wss://", 6) == 0))
	{
		if (opts.insecure)
			ssl_opts.verify = 0;
		ssl_opts.CApath = opts.capath;
		ssl_opts.keyStore = opts.cert;
		ssl_opts.trustStore = opts.cafile;
		ssl_opts.privateKey = opts.key;
		ssl_opts.privateKeyPassword = opts.keypass;
		ssl_opts.enabledCipherSuites = opts.ciphers;
		conn_opts.ssl = &ssl_opts;
	}

In fact, you should be able to use the paho_c_sub utility to subscribe using the TLS options you need, to see that everything works without having to build anything else (to start with).

**Comment by Aterocana** [comment]
It does actually include the SSL version now:
```
> ldd ./samples/MQTTAsync_subscribe
        linux-vdso.so.1 (0x00007ffd9390f000)
        libpaho-mqtt3as.so.1 => /PATH/src/libpaho-mqtt3as.so.1 (0x00007faf6d626000)                                                                      
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007faf6d566000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007faf6d294000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007faf6d0d0000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007faf6d0cb000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007faf6d0aa000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007faf6d6fe000)       
```
Still: I got `-1` (generic error) when connecting to the broker.
Weird enough, if I don't specify any `conn_opts.ssl->trustStore` it connects. Even with a fake CA.
I'm investigating further on it, for now thanks a lot for help.

**Comment by Aterocana** [comment]
It does actually include the SSL version now:
```
> ldd ./samples/MQTTAsync_subscribe
        linux-vdso.so.1 (0x00007ffd9390f000)
        libpaho-mqtt3as.so.1 => /PATH/src/libpaho-mqtt3as.so.1 (0x00007faf6d626000)                                                                      
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007faf6d566000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007faf6d294000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007faf6d0d0000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007faf6d0cb000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007faf6d0aa000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007faf6d6fe000)       
```
Still: I got `-1` (generic error) when connecting to the broker.
Weird enough, if I don't specify any `conn_opts.ssl->trustStore` it connects. Even with a fake CA.
I'm investigating further on it, for now thanks a lot for help.

**Comment by icraggs** [comment]
Configuring a truststore means that the certificate presented by the server will be checked.  Otherwise not.  You can get details of the TLS exchange by setting trace: MQTT_C_CLIENT_TRACE=ON, MQTT_C_CLIENT_TRACE_LEVEL=PROTOCOL (see readme for more details).

**Comment by VijayChandar-K** [comment]
hi,
i have generated ca.crt, server.crt, server.key, client.crt, client.key using openssl.
ca.crt, server.crt, server.key configured them to mosquitto (MQTT Broker)
ca.crt, client.crt, client.key to mqttfx and it is connecting to broker.

how can i use them in my paho-mqtt-c code to make ssl connection
mqtt-ssl connection is being established with out passing any certificates to ssl structure
can any one give information about certificate configuration to paho mqtt c client 

thanks in advance

**Comment by icraggs** [comment]
As I mentioned above, the easiest way to try out the TLS configuration is to use the paho_c_sub or paho_c_pub command line programs to connect to the Mosquitto broker.  They both have the full set of TLS options which you can use to pass the certificate and key files to them.  Then you can map those parameters to the TLS option structure from the source code of those example programs.

**Comment by VijayChandar-K** [comment]
while running what are the command line arguments that need to be passed.

**Comment by VijayChandar-K** [comment]
> while running what are the command line arguments that need to be passed.

at the same time which command argument is what certificate between ca.crt, client.crt, client.key

**Comment by VijayChandar-K** [comment]
hi i have created my client exactly as given in examples
**Client Hello**.  is sent from paho to mosquitto
**Server Hello, Certificate, Server Key Exchange, Server Hello Done** mosqitto sent above to paho
**Alert (Level: Fatal, Description: Unknown CA)** then paho is sending error

url = ssl://192.168.5.36:8883
conn_opts_ssl.CApath = MQTT_NonVolatileFlags.CApath;         _TLS/Certificates1024/_
conn_opts_ssl.keyStore = MQTT_NonVolatileFlags.Clcert;          _TLS/Certificates1024/client.crt_
conn_opts_ssl.trustStore = MQTT_NonVolatileFlags.CAcert;       _TLS/Certificates1024/ca.crt_
conn_opts_ssl.privateKey = MQTT_NonVolatileFlags.Clikey;       _TLS/Certificates1024/client.key_
conn_opts_ssl.ssl_error_cb = SSL_ErrorCallback;                //callback function
conn_opts_ssl.ssl_error_context = MQTT_NonVolatileFlags.LocalMQTTClient;
conn_opts.ssl = &conn_opts_ssl;                            //assigning ssl structure to connection options

paho is not connecting to mosquitto but mqttfx is connecting with same configuration

if i make
conn_opts_ssl.enableServerCertAuth=0;    //which is default enabled paho is connecting to broker with out any certificates

can some one help me in implementation of paho mqtt c client with proper TLS configuration

**Comment by VijayChandar-K** [comment]
hi can any on give some information of using TLS in paho-mqtt-c as  paho_c_sub or paho_c_pub are not helping
@icraggs waiting for some information to implement TLS for paho mqtt c

@Aterocana @waltronix  if you problem is solved can you help me solve this

**Comment by Aterocana** [comment]
@VijayChandar-K Sorry for that, we actually haven't solved.
