### ISSUE TITLE
malloc() without error check in MQTTPacket_publish

### ISSUE THREAD

**Issue by janschatz** [eclipse-paho/paho.mqtt.c#552]
In [MQTTPacket_publish](https://github.com/eclipse/paho.mqtt.c/blob/master/src/MQTTPacket.c#L526) there is a `malloc()` without an error check.

**Comment by janschatz** [comment]
I found another one in [readUTFlen](https://github.com/eclipse/paho.mqtt.c/blob/master/src/MQTTPacket.c#L367). Is this a general problem?

**Comment by janschatz** [comment]
Of course you cannot go on communicating if an out-of-memory condition occurs. So when trying to send a message an appropriate error message should be returned. If data received from the broker cannot be stored, the connection should be closed etc.
But not handling the condition at all may lead in accessing invalid memory locations, which will not only affect the MQTT communication, but the complete application. The application may have mission critical parts that may function perfectly without allocating any memory. So you should not tear them down by causing a segfault.

**Comment by icraggs** [comment]
I understand the consequences, and a check is made in Heap.c at line 162 in mymalloc().  The question is what is the appropriate action?  In my experience, through testing (a long time ago mind you!), I've not been able to recover from out of memory errors regardless of the approach I've tried.  

The other consideration is how frequently _recoverable_ out of memory errors are met in practice.  If hardly ever, then effort may be better expended elsewhere.

Do you regularly encounter _recoverable_ out of memory errors?  If so, what platform/environment?  If so, that could help test any changes made as they would have to leave the internal data structures in a consistent state to enable the library to continue operating.

**Comment by JuergenKosel** [comment]
Maybe this approach helps you:
For our application we increment a pending_message counter each time our application queues a message for publishing into the paho.mqtt.c library.
And we decrement this counter, inside the message send callbacks.
So if this counter reaches a certain limit (because we generate messages faster than the library could send over a bad connection), our application just stops to queue further messages.

**Comment by janschatz** [comment]
Thanks for your proposal. But I don't think that this will help, if the broker sends some large packets or any other component in the system will have high memory usage.

**Comment by icraggs** [comment]
@janschatz Do you regularly encounter recoverable out of memory errors? If so, what platform/environment and or scenario? If so, that could help test any changes made as they would have to leave the internal data structures in a consistent state to enable the library to continue operating.  Or is this a theoretical concern?

If you are on an embedded platform with restricted resources, the embedded C client which does not call malloc/free might be appropriate: https://github.com/eclipse/paho.mqtt.embedded-c

**Comment by janschatz** [comment]
No, I don't regularly encounter out-of-memory conditions. If I did, there would probably be some general problem with the software. It is more of theoretical problem, but I think not completely theoretical.

I am currently developing on an embedded Linux with some MiB of Ram (that's why I went for the 'normal' library with more commits). But I am coming from a 16-Bit platform with far less memory. That's why I am very cautious.

Concerning testing out-of-memory conditions: I once overwrote malloc() and added a call counter and a counter limit as global variables. When the counter would reach the limit, malloc() would return NULL.
I ran a test case once with a very high limit to count the number of allocations. Let's say there were 5. I then repeated the test case in a loop with counter limits from 1..5 - resetting the call counter each time. This way I was able to simulate an out-of-memory condition in every possible state.

**Comment by icraggs** [comment]
I've run similar out of memory tests before.  The question is the balance between the effort involved and the payback.  If out of memory conditions are infrequent, and when they do occur, unrecoverable by the application, then the payback is very low.

There are larger memory allocations which are more likely to encounter this situation - such as for payload and topics, so they would be the ones to prioritize. 

I'm happy to look at it in due course, and of course am open to PRs.

**Comment by ralight** [comment]
My thoughts on this are that you should never get into a situation where you could cause a segfault.

@icraggs I've written some tools to help testing this sort of thing. This is the simple but inflexible solution: https://github.com/ralight/mallocfail and I'm part way through writing a tool to do the same for valgrind: https://bugs.kde.org/show_bug.cgi?id=396290 The patch there is perfectly usable for allocation failure testing, it's another aspect that needs completing.

**Comment by icraggs** [comment]
Obviously I don't want to be in the position of causing a segfault, but as I mentioned before, in the out-of-memory testing I previously conducted, there was no way to recover.   The only way was to avoid getting into that situation in the first place, which was the idea behind the memory tracking.   And so this discussion is more theoretical than practical, so far.

Obviously, as I am overriding malloc/free then I can make them fail at will.  I'll check out your other options too.  The other question is what to do on an error.  Two basic approaches 1) terminate the library entirely (thinking about setjmp/longjmp for that) 2) try and retreat from the nested functions elegantly.  Also start with the most likely failure points (allocating large buffers for payloads and topic names).
