### ISSUE TITLE
Don't fail make install if API man pages aren't available

### ISSUE THREAD

**Issue by msaiducar** [eclipse-paho/paho.mqtt.c#555]
Hi all,

I just cloned the repository and tried to `make && make install`, however it failed. I compiled the repo successfully but `make install` fails due to lack of file.

I'm adding my console output : https://justpaste.it/7ani1

**Comment by icraggs** [comment]
It's looking for the API doc files, you should be able to generate those with the:

make html

command, assuming you have doxygen available.  I'll update the make file so the install doesn't fail if those files don't exist.

**Comment by msaiducar** [comment]
Hi Ian,

Actually I only executed `make` and `make install` commands.  The files were generated after I execute `make html` command as you said. However, I'm working on a DietPi OS with Raspberry Pi Zero, and it doesn't have `man` utility and I don't need documentations.

**Comment by miks** [comment]
Any news on this?
It's still failing when running `make && make install` as in this case no man page has been created.

**Comment by icraggs** [comment]
Fix merged into develop branch.  Thanks
