### ISSUE TITLE
Crashes when unsubscribing to a topic that is already unsubcribed

### ISSUE THREAD

**Issue by destroyedlolo** [eclipse-paho/paho.mqtt.c#558]
Hi,

This issue is happening on the today  (05/10/2018) snapshot as well as on older version.

My C application is dynamically subscribe/unsubscribe topics and, sometime, unsubscribes several time for the same topics without intermediate subscription.

In such situation, my application is crashing "Seg Fault" or, rarely, raise an internal connection error (it why I think it's a problem of memory corruption).
I forked you repo and added some traces : the segfault occurs while returning from MQTTClient_waitfor() called in MQTTClient_unsubscribeMany() as per my trace.

Putting a security in my code to avoid unsubscribe for a topic that is not anymore re-subscribed solved the issue, so the issue looks really in the library code.

Best regards,

Laurent

**Comment by icraggs** [comment]
Have you taken a client library trace, as described in the readme?  If so, can I see it?

I don't think that whether the topic still has a subscription or not should make any difference, as the server should respond the same in either case, and the client library does not keep a record of subscriptions.  So I think that the cause is something else.

**Comment by destroyedlolo** [comment]
This is the trace :

20181005 232628.689 Freeing 48 bytes in heap at file src/MQTTPacket.c line 652, heap use now 1072 bytes

20181005 232628.689 (3263148032)    (3)< MQTTPacket_freeSuback:653
20181005 232628.689 (3263148032)   (2)< MQTTProtocol_handleSubacks:218 (0)
20181005 232628.689 (3263148032)  (1)< MQTTClient_subscribeMany5:1900 (0)
20181005 232628.689 (3263148032) (0)< MQTTClient_subscribe5:1931 (0)
20181005 232628.689 (3263148032) (0)> MQTTClient_subscribe5:1927
20181005 232628.696 (3263148032)  (1)> MQTTClient_subscribeMany5:1795
20181005 232628.696 (3263148032)   (2)> UTF8_validateString:157
20181005 232628.696 (3263148032)    (3)> UTF8_validate:131
20181005 232628.696 (3263148032)    (3)< UTF8_validate:143 (1)
20181005 232628.696 (3263148032)   (2)< UTF8_validateString:159 (1)
20181005 232628.696 (3263148032)   (2)> MQTTProtocol_assignMsgId:83
20181005 232628.696 (3263148032)   (2)< MQTTProtocol_assignMsgId:96 (19)
20181005 232628.696 Allocating 48 bytes in heap at file src/LinkedList.c line 58 ptr 0x55fa3b0b3300

20181005 232628.696 Allocating 48 bytes in heap at file src/LinkedList.c line 58 ptr 0x55fa3b0c0aa0

20181005 232628.696 Allocating 32 bytes in heap at file src/LinkedList.c line 95 ptr 0x55fa3b0ad0c0

20181005 232628.696 Allocating 32 bytes in heap at file src/LinkedList.c line 95 ptr 0x55fa3b0b9d30

20181005 232628.696 (3263148032)   (2)> MQTTProtocol_subscribe:195
20181005 232628.696 (3263148032)    (3)> MQTTPacket_send_subscribe:226
20181005 232628.696 Allocating 48 bytes in heap at file src/MQTTPacketOut.c line 238 ptr 0x55fa3b08df70

20181005 232628.696 (3263148032)     (4)> MQTTPacket_send:187
20181005 232628.696 Allocating 16 bytes in heap at file src/MQTTPacket.c line 190 ptr 0x55fa3b0b2750

20181005 232628.696 (3263148032)      (5)> MQTTPacket_encode:281
20181005 232628.696 (3263148032)      (5)< MQTTPacket_encode:291 (1)
20181005 232628.696 (3263148032)      (5)> WebSocket_putdatas:681
20181005 232628.696 (3263148032)       (6)> Socket_putdatas:502
20181005 232628.697 (3263148032)        (7)> Socket_writev:426
20181005 232628.697 (3263148032)        (7)< Socket_writev:478 (41)
20181005 232628.697 (3263148032)       (6)< Socket_putdatas:550 (0)
20181005 232628.697 (3263148032)      (5)< WebSocket_putdatas:713 (0)
20181005 232628.697 Freeing 16 bytes in heap at file src/MQTTPacket.c line 214, heap use now 1248 bytes

20181005 232628.697 (3263148032)     (4)< MQTTPacket_send:216 (0)
20181005 232628.697 4 Majordome-PSet-12574 -> SUBSCRIBE msgid: 19 (0)
20181005 232628.697 Freeing 48 bytes in heap at file src/MQTTPacketOut.c line 264, heap use now 1232 bytes

20181005 232628.697 (3263148032)    (3)< MQTTPacket_send_subscribe:265 (0)
20181005 232628.697 (3263148032)   (2)< MQTTProtocol_subscribe:197 (0)
20181005 232628.697 Freeing 32 bytes in heap at file src/LinkedList.c line 396, heap use now 1184 bytes

20181005 232628.697 Freeing 48 bytes in heap at file src/LinkedList.c line 398, heap use now 1152 bytes

20181005 232628.697 Freeing 32 bytes in heap at file src/LinkedList.c line 396, heap use now 1104 bytes

20181005 232628.697 Freeing 48 bytes in heap at file src/LinkedList.c line 398, heap use now 1072 bytes

20181005 232628.697 (3263148032)   (2)> MQTTClient_waitfor:2368
20181005 232628.697 (3263148032)    (3)> Thread_wait_sem:244
20181005 232628.697 Return code 1 from read select
20181005 232628.697 (3235657472)    (3)> Socket_continueWrites:928
20181005 232628.697 (3235657472)    (3)< Socket_continueWrites:952 (0)
20181005 232628.697 Return code 1 from write select
20181005 232628.698 (3235657472)    (3)> isReady:213
20181005 232628.698 (3235657472)    (3)< isReady:218 (1)
20181005 232628.698 (3235657472)   (2)< Socket_getReadySocket:309 (4)
20181005 232628.698 (3235657472)   (2)> MQTTPacket_Factory:111
20181005 232628.698 (3235657472)    (3)> WebSocket_getch:469
20181005 232628.698 (3235657472)     (4)> Socket_getch:324
20181005 232628.698 (3235657472)      (5)> SocketBuffer_getQueuedChar:203
20181005 232628.698 (3235657472)      (5)< SocketBuffer_getQueuedChar:222 (-22)
20181005 232628.698 (3235657472)      (5)> SocketBuffer_queueChar:288
20181005 232628.698 queueChar: index is now 1, headerlen 1
20181005 232628.698 (3235657472)      (5)< SocketBuffer_queueChar:313
20181005 232628.698 (3235657472)     (4)< Socket_getch:345 (0)
20181005 232628.698 (3235657472)    (3)< WebSocket_getch:506 (0)
20181005 232628.698 (3235657472)    (3)> MQTTPacket_decode:310
20181005 232628.698 (3235657472)     (4)> WebSocket_getch:469
20181005 232628.698 (3235657472)      (5)> Socket_getch:324
20181005 232628.698 (3235657472)       (6)> SocketBuffer_getQueuedChar:203
20181005 232628.698 (3235657472)       (6)< SocketBuffer_getQueuedChar:222 (-22)
20181005 232628.698 (3235657472)       (6)> SocketBuffer_queueChar:288
20181005 232628.698 queueChar: index is now 2, headerlen 2
20181005 232628.698 (3235657472)       (6)< SocketBuffer_queueChar:313
20181005 232628.698 (3235657472)      (5)< Socket_getch:345 (0)
20181005 232628.698 (3235657472)     (4)< WebSocket_getch:506 (0)
20181005 232628.698 (3235657472)    (3)< MQTTPacket_decode:326 (0)
20181005 232628.698 (3235657472)    (3)> WebSocket_getdata:526
20181005 232628.698 (3235657472)     (4)> Socket_getdata:363
20181005 232628.698 (3235657472)      (5)> SocketBuffer_getQueuedData:163
20181005 232628.698 (3235657472)      (5)< SocketBuffer_getQueuedData:188
20181005 232628.698 (3235657472)      (5)> SocketBuffer_complete:263
20181005 232628.698 (3235657472)      (5)< SocketBuffer_complete:273
20181005 232628.698 (3235657472)     (4)< Socket_getdata:397
20181005 232628.698 (3235657472)    (3)< WebSocket_getdata:584 (1)
20181005 232628.698 Allocating 64 bytes in heap at file src/MQTTPacket.c line 526 ptr 0x7f32bc003420

20181005 232628.698 (3235657472)    (3)> MQTTPacket_publish:530
20181005 232628.698 (3235657472)     (4)> readUTFlen:361
20181005 232628.698 Allocating 32 bytes in heap at file src/MQTTPacket.c line 367 ptr 0x7f32bc000c70

20181005 232628.698 (3235657472)     (4)< readUTFlen:373
20181005 232628.698 (3235657472)    (3)< MQTTPacket_publish:558
20181005 232628.698 (3235657472)   (2)< MQTTPacket_Factory:164 (0)
20181005 232628.698 (3235657472)   (2)> MQTTProtocol_handlePublishes:278
20181005 232628.698 4 Majordome-PSet-12574 <- PUBLISH msgid: 0 qos: 0 retained: 1 payload: Intersaison
20181005 232628.698 (3235657472)    (3)> Protocol_processPublication:1038
20181005 232628.698 Allocating 32 bytes in heap at file src/MQTTClient.c line 1039 ptr 0x7f32bc00c270

20181005 232628.698 Allocating 64 bytes in heap at file src/MQTTClient.c line 1040 ptr 0x7f32bc000eb0

20181005 232628.698 Allocating 16 bytes in heap at file src/MQTTClient.c line 1056 ptr 0x7f32bc000d70

20181005 232628.698 Allocating 32 bytes in heap at file src/LinkedList.c line 95 ptr 0x7f32bc000f70

20181005 232628.698 (3235657472)    (3)< Protocol_processPublication:1077
20181005 232628.698 (3235657472)    (3)> MQTTPacket_freePublish:569
20181005 232628.698 Freeing 64 bytes in heap at file src/MQTTPacket.c line 574, heap use now 1264 bytes

20181005 232628.698 (3235657472)    (3)< MQTTPacket_freePublish:575
20181005 232628.698 (3235657472)   (2)< MQTTProtocol_handlePublishes:345 (0)
20181005 232628.698 (3235657472)   (2)> MQTTClient_retry:2251
20181005 232628.698 (3235657472)    (3)> MQTTProtocol_retry:727
20181005 232628.698 (3235657472)    (3)< MQTTProtocol_retry:746
20181005 232628.698 (3235657472)   (2)< MQTTClient_retry:2261
20181005 232628.698 (3235657472)  (1)< MQTTClient_cycle:2357 (0)
20181005 232628.698 Calling messageArrived for client Majordome-PSet-12574, queue depth 1
20181005 232628.698 (3040696064) (0)> MQTTClient_isConnected:1774
20181005 232628.698 (3040696064) (0)< MQTTClient_isConnected:1779 (1)
20181005 232628.698 (3040696064) (0)> MQTTClient_publishMessage5:2204
20181005 232628.698 (3040696064)  (1)> MQTTClient_publish5:2083
20181005 232628.698 (3040696064)   (2)> UTF8_validateString:157
20181005 232628.698 (3040696064)    (3)> UTF8_validate:131
20181005 232628.698 (3040696064)    (3)< UTF8_validate:143 (1)
20181005 232628.698 (3040696064)   (2)< UTF8_validateString:159 (1)
20181005 232628.698 Allocating 96 bytes in heap at file src/MQTTClient.c line 2122 ptr 0x7f32a8000be0

20181005 232628.698 Allocating 32 bytes in heap at file src/MQTTProtocolClient.c line 871 ptr 0x7f32a8000cf0

20181005 232628.698 (3040696064)   (2)> MQTTStrncpy:848
20181005 232628.698 (3040696064)   (2)< MQTTStrncpy:858
20181005 232628.698 (3040696064)   (2)> MQTTProtocol_startPublish:156
20181005 232628.698 (3040696064)    (3)> MQTTProtocol_startPublishCommon:133
20181005 232628.698 (3040696064)     (4)> MQTTPacket_send_publish:791
20181005 232628.698 Allocating 16 bytes in heap at file src/MQTTPacket.c line 792 ptr 0x7f32a8000db0

20181005 232628.698 (3040696064)      (5)> MQTTPacket_sends:239
20181005 232628.698 Allocating 16 bytes in heap at file src/MQTTPacket.c line 245 ptr 0x7f32a8000e60

20181005 232628.698 (3040696064)       (6)> MQTTPacket_encode:281
20181005 232628.698 (3040696064)       (6)< MQTTPacket_encode:291 (1)
20181005 232628.698 (3040696064)       (6)> WebSocket_putdatas:681
20181005 232628.698 (3040696064)        (7)> Socket_putdatas:502
20181005 232628.698 (3040696064)         (8)> Socket_writev:426
20181005 232628.698 (3040696064)         (8)< Socket_writev:478 (60)
20181005 232628.698 (3040696064)        (7)< Socket_putdatas:550 (0)
20181005 232628.698 (3040696064)       (6)< WebSocket_putdatas:713 (0)
20181005 232628.698 Freeing 16 bytes in heap at file src/MQTTPacket.c line 265, heap use now 1360 bytes

20181005 232628.698 (3040696064)      (5)< MQTTPacket_sends:266 (0)
20181005 232628.698 Freeing 16 bytes in heap at file src/MQTTPacket.c line 829, heap use now 1344 bytes

20181005 232628.698 4 Majordome-PSet-12574 -> PUBLISH qos: 0 retained: 0 (0)
20181005 232628.698 (3040696064)     (4)< MQTTPacket_send_publish:835 (0)
20181005 232628.698 (3040696064)    (3)< MQTTProtocol_startPublishCommon:137 (0)
20181005 232628.698 (3040696064)   (2)< MQTTProtocol_startPublish:169 (0)
20181005 232628.698 Freeing 32 bytes in heap at file src/MQTTClient.c line 2166, heap use now 1328 bytes

20181005 232628.698 Freeing 96 bytes in heap at file src/MQTTClient.c line 2167, heap use now 1296 bytes

20181005 232628.698 (3040696064)  (1)< MQTTClient_publish5:2179 (0)
20181005 232628.698 (3040696064) (0)< MQTTClient_publishMessage5:2224 (0)
20181005 232628.698 (3032303360) (0)> MQTTClient_isConnected:1774
20181005 232628.698 (3032303360) (0)< MQTTClient_isConnected:1779 (1)
20181005 232628.698 (3032303360) (0)> MQTTClient_publishMessage5:2204
20181005 232628.698 (3032303360)  (1)> MQTTClient_publish5:2083
20181005 232628.698 (3032303360)   (2)> UTF8_validateString:157
20181005 232628.698 (3032303360)    (3)> UTF8_validate:131
20181005 232628.699 (3032303360)    (3)< UTF8_validate:143 (1)
20181005 232628.699 (3032303360)   (2)< UTF8_validateString:159 (1)
20181005 232628.699 Allocating 144 bytes in heap at file src/MQTTClient.c line 2122 ptr 0x7f32a8000ec0

20181005 232628.699 Allocating 48 bytes in heap at file src/MQTTProtocolClient.c line 871 ptr 0x7f32a8000f60

20181005 232628.699 (3032303360)   (2)> MQTTStrncpy:848
20181005 232628.699 (3032303360)   (2)< MQTTStrncpy:858
20181005 232628.699 (3032303360)   (2)> MQTTProtocol_startPublish:156
20181005 232628.699 (3032303360)    (3)> MQTTProtocol_startPublishCommon:133
20181005 232628.699 (3032303360)     (4)> MQTTPacket_send_publish:791
20181005 232628.699 Allocating 16 bytes in heap at file src/MQTTPacket.c line 792 ptr 0x7f32a8000db0

20181005 232628.699 (3032303360)      (5)> MQTTPacket_sends:239
20181005 232628.699 Allocating 16 bytes in heap at file src/MQTTPacket.c line 245 ptr 0x7f32a8000e60

20181005 232628.699 (3032303360)       (6)> MQTTPacket_encode:281
20181005 232628.699 (3032303360)       (6)< MQTTPacket_encode:291 (1)
20181005 232628.699 (3032303360)       (6)> WebSocket_putdatas:681
20181005 232628.699 (3032303360)        (7)> Socket_putdatas:502
20181005 232628.699 (3032303360)         (8)> Socket_writev:426
20181005 232628.699 (3032303360)         (8)< Socket_writev:478 (111)
20181005 232628.699 (3032303360)        (7)< Socket_putdatas:550 (0)
20181005 232628.699 (3032303360)       (6)< WebSocket_putdatas:713 (0)
20181005 232628.699 Freeing 16 bytes in heap at file src/MQTTPacket.c line 265, heap use now 1424 bytes

20181005 232628.699 (3032303360)      (5)< MQTTPacket_sends:266 (0)
20181005 232628.699 Freeing 16 bytes in heap at file src/MQTTPacket.c line 829, heap use now 1408 bytes

20181005 232628.699 4 Majordome-PSet-12574 -> PUBLISH qos: 0 retained: 0 (0)
20181005 232628.699 (3235657472)  (1)> MQTTClient_freeMessage:550
20181005 232628.699 (3235657472)   (2)> MQTTProperties_free:366
20181005 232628.699 (3235657472)   (2)< MQTTProperties_free:389
20181005 232628.699 Freeing 16 bytes in heap at file src/MQTTClient.c line 552, heap use now 1392 bytes

20181005 232628.699 Freeing 64 bytes in heap at file src/MQTTClient.c line 553, heap use now 1376 bytes

20181005 232628.699 (3032303360)     (4)< MQTTPacket_send_publish:835 (0)
20181005 232628.699 (3032303360)    (3)< MQTTProtocol_startPublishCommon:137 (0)
20181005 232628.699 (3032303360)   (2)< MQTTProtocol_startPublish:169 (0)
20181005 232628.699 Freeing 48 bytes in heap at file src/MQTTClient.c line 2166, heap use now 1312 bytes

20181005 232628.699 Freeing 144 bytes in heap at file src/MQTTClient.c line 2167, heap use now 1264 bytes

20181005 232628.699 (3049088768) (0)> MQTTClient_isConnected:1774
20181005 232628.699 (3049088768) (0)< MQTTClient_isConnected:1779 (1)
20181005 232628.699 (3049088768) (0)> MQTTClient_publishMessage5:2204
20181005 232628.699 (3049088768)  (1)> MQTTClient_publish5:2083
20181005 232628.699 (3049088768)   (2)> UTF8_validateString:157
20181005 232628.699 (3049088768)    (3)> UTF8_validate:131
20181005 232628.699 (3049088768)    (3)< UTF8_validate:143 (1)
20181005 232628.699 (3049088768)   (2)< UTF8_validateString:159 (1)
20181005 232628.699 Allocating 96 bytes in heap at file src/MQTTClient.c line 2122 ptr 0x7f32b0001c30

20181005 232628.699 Allocating 48 bytes in heap at file src/MQTTProtocolClient.c line 871 ptr 0x7f32b0001d40

20181005 232628.699 (3049088768)   (2)> MQTTStrncpy:848
20181005 232628.699 (3049088768)   (2)< MQTTStrncpy:858
20181005 232628.699 (3049088768)   (2)> MQTTProtocol_startPublish:156
20181005 232628.699 (3049088768)    (3)> MQTTProtocol_startPublishCommon:133
20181005 232628.699 (3049088768)     (4)> MQTTPacket_send_publish:791
20181005 232628.699 Allocating 16 bytes in heap at file src/MQTTPacket.c line 792 ptr 0x7f32b0001e10

20181005 232628.699 (3235657472)  (1)< MQTTClient_freeMessage:555
20181005 232628.699 (3235657472)  (1)> MQTTClient_free:561
20181005 232628.699 Freeing 32 bytes in heap at file src/MQTTClient.c line 562, heap use now 1280 bytes

20181005 232628.699 (3235657472)  (1)< MQTTClient_free:563
20181005 232628.699 (3049088768)      (5)> MQTTPacket_sends:239
20181005 232628.699 Allocating 16 bytes in heap at file src/MQTTPacket.c line 245 ptr 0x7f32b0001ec0

20181005 232628.699 (3032303360)  (1)< MQTTClient_publish5:2179 (0)
20181005 232628.699 (3032303360) (0)< MQTTClient_publishMessage5:2224 (0)
20181005 232628.699 (3032303360) (0)> MQTTClient_unsubscribeMany5:1959
20181005 232628.699 (3049088768)       (6)> MQTTPacket_encode:281
20181005 232628.699 (3049088768)       (6)< MQTTPacket_encode:291 (1)
20181005 232628.699 (3049088768)       (6)> WebSocket_putdatas:681
20181005 232628.699 (3049088768)        (7)> Socket_putdatas:502
20181005 232628.699 (3049088768)         (8)> Socket_writev:426
20181005 232628.699 (3049088768)         (8)< Socket_writev:478 (71)
20181005 232628.699 (3049088768)        (7)< Socket_putdatas:550 (0)
20181005 232628.699 (3049088768)       (6)< WebSocket_putdatas:713 (0)
20181005 232628.699 Freeing 16 bytes in heap at file src/MQTTPacket.c line 265, heap use now 1264 bytes

20181005 232628.699 (3049088768)      (5)< MQTTPacket_sends:266 (0)
20181005 232628.699 Freeing 16 bytes in heap at file src/MQTTPacket.c line 829, heap use now 1248 bytes

20181005 232628.699 4 Majordome-PSet-12574 -> PUBLISH qos: 0 retained: 0 (0)
20181005 232628.699 (3049088768)     (4)< MQTTPacket_send_publish:835 (0)
20181005 232628.699 (3049088768)    (3)< MQTTProtocol_startPublishCommon:137 (0)
20181005 232628.699 (3049088768)   (2)< MQTTProtocol_startPublish:169 (0)
20181005 232628.699 Freeing 48 bytes in heap at file src/MQTTClient.c line 2166, heap use now 1232 bytes

20181005 232628.699 Freeing 96 bytes in heap at file src/MQTTClient.c line 2167, heap use now 1184 bytes

20181005 232628.699 (3049088768)  (1)< MQTTClient_publish5:2179 (0)
20181005 232628.699 (3049088768) (0)< MQTTClient_publishMessage5:2224 (0)
20181005 232628.699 Freeing 32 bytes in heap at file src/LinkedList.c line 222, heap use now 1088 bytes

20181005 232628.699 Freeing 32 bytes in heap at file src/LinkedList.c line 227, heap use now 1056 bytes

20181005 232628.699 (3235657472)  (1)> MQTTClient_cycle:2271
20181005 232628.699 (3235657472)   (2)> Socket_getReadySocket:237
20181005 232628.699 (3032303360)  (1)> UTF8_validateString:157
20181005 232628.699 (3032303360)   (2)> UTF8_validate:131
20181005 232628.699 (3032303360)   (2)< UTF8_validate:143 (1)
20181005 232628.699 (3032303360)  (1)< UTF8_validateString:159 (1)
20181005 232628.699 (3032303360)  (1)> MQTTProtocol_assignMsgId:83
20181005 232628.699 (3032303360)  (1)< MQTTProtocol_assignMsgId:96 (20)
20181005 232628.699 Allocating 48 bytes in heap at file src/LinkedList.c line 58 ptr 0x7f32a8001020

20181005 232628.699 Allocating 32 bytes in heap at file src/LinkedList.c line 95 ptr 0x7f32a8000cf0

20181005 232628.699 (3032303360)  (1)> MQTTProtocol_unsubscribe:233
20181005 232628.699 (3032303360)   (2)> MQTTPacket_send_unsubscribe:329
20181005 232628.699 Allocating 32 bytes in heap at file src/MQTTPacketOut.c line 340 ptr 0x7f32a8000cc0

20181005 232628.699 (3032303360)    (3)> MQTTPacket_send:187
20181005 232628.699 Allocating 16 bytes in heap at file src/MQTTPacket.c line 190 ptr 0x7f32a8000d90

20181005 232628.699 (3032303360)     (4)> MQTTPacket_encode:281
20181005 232628.699 (3032303360)     (4)< MQTTPacket_encode:291 (1)
20181005 232628.699 (3032303360)     (4)> WebSocket_putdatas:681
20181005 232628.699 (3032303360)      (5)> Socket_putdatas:502
20181005 232628.699 (3032303360)       (6)> Socket_writev:426
20181005 232628.700 Return code 1 from read select
20181005 232628.700 (3235657472)    (3)> Socket_continueWrites:928
20181005 232628.700 (3235657472)    (3)< Socket_continueWrites:952 (0)
20181005 232628.700 Return code 1 from write select
20181005 232628.700 (3032303360)       (6)< Socket_writev:478 (31)
20181005 232628.700 (3032303360)      (5)< Socket_putdatas:550 (0)
20181005 232628.700 (3032303360)     (4)< WebSocket_putdatas:713 (0)
20181005 232628.700 Freeing 16 bytes in heap at file src/MQTTPacket.c line 214, heap use now 1152 bytes

20181005 232628.700 (3235657472)    (3)> isReady:213
20181005 232628.700 (3235657472)    (3)< isReady:218 (1)
20181005 232628.700 (3235657472)   (2)< Socket_getReadySocket:309 (4)
20181005 232628.700 (3032303360)    (3)< MQTTPacket_send:216 (0)
20181005 232628.700 4 Majordome-PSet-12574 -> UNSUBSCRIBE msgid: 20 (0)
20181005 232628.700 Freeing 32 bytes in heap at file src/MQTTPacketOut.c line 353, heap use now 1136 bytes

20181005 232628.700 (3032303360)   (2)< MQTTPacket_send_unsubscribe:354 (0)
20181005 232628.700 (3032303360)  (1)< MQTTProtocol_unsubscribe:235 (0)
20181005 232628.700 Freeing 32 bytes in heap at file src/LinkedList.c line 396, heap use now 1104 bytes

20181005 232628.700 Freeing 48 bytes in heap at file src/LinkedList.c line 398, heap use now 1072 bytes

20181005 232628.700 (3032303360)  (1)> MQTTClient_waitfor:2368
20181005 232628.700 (3032303360)   (2)> Thread_wait_sem:244
20181005 232628.700 (3235657472)   (2)> MQTTPacket_Factory:111
20181005 232628.700 (3235657472)    (3)> WebSocket_getch:469
20181005 232628.700 (3235657472)     (4)> Socket_getch:324
20181005 232628.700 (3235657472)      (5)> SocketBuffer_getQueuedChar:203
20181005 232628.700 (3235657472)      (5)< SocketBuffer_getQueuedChar:222 (-22)
20181005 232628.700 (3235657472)      (5)> SocketBuffer_queueChar:288
20181005 232628.700 queueChar: index is now 1, headerlen 1
20181005 232628.700 (3235657472)      (5)< SocketBuffer_queueChar:313
20181005 232628.700 (3235657472)     (4)< Socket_getch:345 (0)
20181005 232628.700 (3235657472)    (3)< WebSocket_getch:506 (0)
20181005 232628.700 (3235657472)    (3)> MQTTPacket_decode:310
20181005 232628.700 (3235657472)     (4)> WebSocket_getch:469
20181005 232628.700 (3235657472)      (5)> Socket_getch:324
20181005 232628.700 (3235657472)       (6)> SocketBuffer_getQueuedChar:203
20181005 232628.700 (3235657472)       (6)< SocketBuffer_getQueuedChar:222 (-22)
20181005 232628.700 (3235657472)       (6)> SocketBuffer_queueChar:288
20181005 232628.700 queueChar: index is now 2, headerlen 2
20181005 232628.700 (3235657472)       (6)< SocketBuffer_queueChar:313
20181005 232628.700 (3235657472)      (5)< Socket_getch:345 (0)
20181005 232628.700 (3235657472)     (4)< WebSocket_getch:506 (0)
20181005 232628.700 (3235657472)    (3)< MQTTPacket_decode:326 (0)
20181005 232628.700 (3235657472)    (3)> WebSocket_getdata:526
20181005 232628.700 (3235657472)     (4)> Socket_getdata:363
20181005 232628.700 (3235657472)      (5)> SocketBuffer_getQueuedData:163
20181005 232628.700 (3235657472)      (5)< SocketBuffer_getQueuedData:188
20181005 232628.700 (3235657472)      (5)> SocketBuffer_complete:263
20181005 232628.700 (3235657472)      (5)< SocketBuffer_complete:273
20181005 232628.700 (3235657472)     (4)< Socket_getdata:397
20181005 232628.700 (3235657472)    (3)< WebSocket_getdata:584 (1)
20181005 232628.700 Allocating 48 bytes in heap at file src/MQTTPacketOut.c line 280 ptr 0x7f32bc001960

20181005 232628.700 (3235657472)    (3)> MQTTPacket_suback:284
20181005 232628.700 Allocating 48 bytes in heap at file src/LinkedList.c line 58 ptr 0x7f32a8000fa0

20181005 232628.700 Allocating 16 bytes in heap at file src/MQTTPacketOut.c line 303 ptr 0x7f32bc000f30

20181005 232628.700 Allocating 32 bytes in heap at file src/LinkedList.c line 95 ptr 0x7f32bc0034b0

20181005 232628.700 (3235657472)    (3)< MQTTPacket_suback:307
20181005 232628.700 (3235657472)   (2)< MQTTPacket_Factory:164 (0)
20181005 232628.700 (3235657472)   (2)> MQTTClient_retry:2251
20181005 232628.700 (3235657472)    (3)> MQTTProtocol_retry:727
20181005 232628.700 (3235657472)    (3)< MQTTProtocol_retry:746
20181005 232628.700 (3235657472)   (2)< MQTTClient_retry:2261
20181005 232628.700 (3235657472)  (1)< MQTTClient_cycle:2357 (0)
20181005 232628.700 Posting suback semaphore for client Majordome-PSet-12574
20181005 232628.700 (3235657472)  (1)> Thread_post_sem:314
20181005 232628.700 (3235657472)  (1)< Thread_post_sem:325 (0)
20181005 232628.700 (3235657472)  (1)> MQTTClient_cycle:2271
20181005 232628.700 (3235657472)   (2)> Socket_getReadySocket:237
20181005 232628.700 Return code 1 from read select
20181005 232628.700 (3235657472)    (3)> Socket_continueWrites:928
20181005 232628.700 (3235657472)    (3)< Socket_continueWrites:952 (0)
20181005 232628.700 Return code 1 from write select
20181005 232628.700 (3235657472)    (3)> isReady:213
20181005 232628.700 (3235657472)    (3)< isReady:218 (1)
20181005 232628.700 (3235657472)   (2)< Socket_getReadySocket:309 (4)
20181005 232628.700 (3235657472)   (2)> MQTTPacket_Factory:111
20181005 232628.700 (3235657472)    (3)> WebSocket_getch:469
20181005 232628.700 (3235657472)     (4)> Socket_getch:324
20181005 232628.700 (3235657472)      (5)> SocketBuffer_getQueuedChar:203
20181005 232628.700 (3235657472)      (5)< SocketBuffer_getQueuedChar:222 (-22)
20181005 232628.700 (3235657472)      (5)> SocketBuffer_queueChar:288
20181005 232628.700 queueChar: index is now 1, headerlen 1
20181005 232628.701 (3235657472)      (5)< SocketBuffer_queueChar:313
20181005 232628.701 (3235657472)     (4)< Socket_getch:345 (0)
20181005 232628.701 (3235657472)    (3)< WebSocket_getch:506 (0)
20181005 232628.701 (3235657472)    (3)> MQTTPacket_decode:310
20181005 232628.701 (3235657472)     (4)> WebSocket_getch:469
20181005 232628.701 (3235657472)      (5)> Socket_getch:324
20181005 232628.701 (3235657472)       (6)> SocketBuffer_getQueuedChar:203
20181005 232628.701 (3235657472)       (6)< SocketBuffer_getQueuedChar:222 (-22)
20181005 232628.701 (3235657472)       (6)> SocketBuffer_queueChar:288
20181005 232628.701 queueChar: index is now 2, headerlen 2
20181005 232628.701 (3235657472)       (6)< SocketBuffer_queueChar:313
20181005 232628.701 (3235657472)      (5)< Socket_getch:345 (0)
20181005 232628.701 (3235657472)     (4)< WebSocket_getch:506 (0)
20181005 232628.701 (3235657472)    (3)< MQTTPacket_decode:326 (0)
20181005 232628.701 (3235657472)    (3)> WebSocket_getdata:526
20181005 232628.701 (3235657472)     (4)> Socket_getdata:363
20181005 232628.701 (3235657472)      (5)> SocketBuffer_getQueuedData:163
20181005 232628.701 (3235657472)      (5)< SocketBuffer_getQueuedData:188
20181005 232628.701 (3235657472)      (5)> SocketBuffer_complete:263
20181005 232628.701 (3235657472)      (5)< SocketBuffer_complete:273
20181005 232628.701 (3235657472)     (4)< Socket_getdata:397
20181005 232628.701 (3235657472)    (3)< WebSocket_getdata:584 (1)
20181005 232628.701 Allocating 48 bytes in heap at file src/MQTTPacketOut.c line 369 ptr 0x7f32bc00fb20

20181005 232628.701 (3235657472)    (3)> MQTTPacket_unsuback:373
20181005 232628.701 (3235657472)    (3)< MQTTPacket_unsuback:397
20181005 232628.701 (3235657472)   (2)< MQTTPacket_Factory:164 (0)
20181005 232628.701 (3235657472)   (2)> MQTTClient_retry:2251
20181005 232628.701 (3235657472)    (3)> MQTTProtocol_retry:727
20181005 232628.701 (3235657472)    (3)< MQTTProtocol_retry:746
20181005 232628.701 (3235657472)   (2)< MQTTClient_retry:2261
20181005 232628.701 (3235657472)  (1)< MQTTClient_cycle:2357 (0)
20181005 232628.701 Posting unsuback semaphore for client Majordome-PSet-12574
20181005 232628.701 (3235657472)  (1)> Thread_post_sem:314
20181005 232628.701 (3235657472)  (1)< Thread_post_sem:325 (0)
20181005 232628.701 (3235657472)  (1)> MQTTClient_cycle:2271
20181005 232628.701 (3235657472)   (2)> Socket_getReadySocket:237
20181005 232628.701 (3263148032)    (3)< Thread_wait_sem:277 (0)
20181005 232628.701 (3263148032)   (2)< MQTTClient_waitfor:2460 (0)

I can do other test if you want.

**Comment by icraggs** [comment]
It would be better to attach a file with the trace in rather than a long paste.  Anyway, you seem to have three different threads simultaneously running a subscribe, unsubscribe and publishes potentially on the same client?  

The unsubscribe is started while the subscribe is still executing, if I'm reading that correctly.   This API is supposed to be pretty single threaded so that this simultaneous execution shouldn't happen.  The mutex locking should stop it.  What OS are you on?

**Comment by destroyedlolo** [comment]
Yes, my application is massively multi-threaded.

The strange part is this crash happening only when unsubscribing and always when there is a double unsubscription ... As soon as I add a code to about this double unsubscription, my appli will not crash anymore (tests ongoing but uptime is already more than a day).

I'm running Gentoo Linux on IA64 and ARM.

**Comment by icraggs** [comment]
If you can try running under gdb, and get a backtrace and/or attach some code (if possible) which shows the problem, then that might help.
