### ISSUE TITLE
Signed values in properties cause to wrong value calculation

### ISSUE THREAD

**Issue by troian** [eclipse-paho/paho.mqtt.c#559]
For example receive maximum per MQTT 5.0 is 65535 but it interpreted as -32767.
https://github.com/eclipse/paho.mqtt.c/blob/9f715d0862a8e16099b5837c4e53a1bf6a6a0675/src/MQTTProperties.h#L106

**Comment by icraggs** [comment]
Change integer property types to unsigned.
