### ISSUE TITLE
Segfault on bad SUBACK packet

### ISSUE THREAD

**Issue by ralight** [eclipse-paho/paho.mqtt.c#563]
If the server replies to an MQTT v5 SUBSCRIBE with a v3 SUBACK (i.e. no property length is defined) then paho_c_sub segfaults. Yes I know this situation shouldn't arise :)

```
[New Thread 0x7ffff6c21700 (LWP 16226)]
[New Thread 0x7ffff6420700 (LWP 16227)]
Trace : 4, 20181010 114350.630 Connecting to serverURI localhost:1883 with MQTT version 5
Trace : 4, 20181010 114350.730 3 paho-c-sub -> CONNECT cleansession: 0 (0)
Trace : 4, 20181010 114350.731 3 paho-c-sub <- CONNACK rc: 0
Subscribing to topic # with client paho-c-sub at QoS 0
Trace : 4, 20181010 114350.731 3 paho-c-sub -> SUBSCRIBE msgid: 1 (0)

Thread 3 "paho_c_sub" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6420700 (LWP 16227)]
MQTTAsync_receiveThread (n=<optimised out>) at src/MQTTAsync.c:2240
2240                                                                            data.reasonCode = *(int*)(sub->qoss->first->content);
(gdb) bt
#0  MQTTAsync_receiveThread (n=<optimised out>) at src/MQTTAsync.c:2240
#1  0x00007ffff79006db in start_thread (arg=0x7ffff6420700) at pthread_create.c:463
#2  0x00007ffff762988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by icraggs** [comment]
We should be able to cope, but no, it wasn't the first thing I tested!

**Comment by ralight** [comment]
It's not exclusive to SUBACKs by the way.

**Comment by icraggs** [comment]
I assumed not, as it's in the reason code processing.

**Comment by icraggs** [comment]
I think that some V3 suback packets can be indistinguishable from a well-formed V5 suback.  A suback with two granted QoS fields, the first one 0, will match a V5 suback packet with no properties (0 length) and one granted QoS, for instance.

**Comment by icraggs** [comment]
I put a fix in for what I assume is the suback problem.  It would be useful if you could try it out.

**Comment by icraggs** [comment]
I put a fix in for what I assume is the suback problem.  It would be useful if you could try it out.

**Comment by ralight** [comment]
Looks fine to me.

**Comment by icraggs** [comment]
Thanks Roger.

**Comment by icraggs** [comment]
Fix added for the other packets.
