### ISSUE TITLE
windows static build MQTTClient_subscribe Access violation reading

### ISSUE THREAD

**Issue by jumoog** [eclipse-paho/paho.mqtt.c#565]
If i use the static lib sometimes MQTTClient_subscribe throws a Unhandled exception..  Access violation reading.

Its random and doesn't happen with the none static lib. I guess its socket releated.

No idea how to debug this issue

OS: Windows

**Comment by icraggs** [comment]
I've never tested or used the static library.  It was added as an option by a contributor, but without tests.  It has seemed to work for people who have used it, but really there should be tests.

Options for debugging:
- set the client library trace environment variables (see readme) and let's see if the trace output helps
(- run under Visual Studio and get detailed execution info
- run on Linux or MacOS under gdb/lldb and get a backtrace)

**Comment by jumoog** [comment]
(-2)> MQTTClient_subscribe5:1945
(-1)> MQTTClient_subscribeMany5:1813

but i set MQTTVERSION_3_1_1

**Comment by icraggs** [comment]
Those calls are still used internally whichever version of MQTT you are using.  Do you have a snippet of the code where you call subscribe?

**Comment by jumoog** [comment]
here i made an example: 
sometimes it connects fine and sometimes it crashes
https://gist.github.com/jumoog/3cdaf968f622e7f7af63c8e9935171f8

if i use the none static libs i can connect every time

**Comment by icraggs** [comment]
That code look ok.  Does the trace show the same output each time?  Can you attach a fuller trace as a file?  If you don't subscribe does everything work?

**Comment by jumoog** [comment]
it took forever to find a crash without subscribe ~30 times

###with subscribe
[error.txt](https://github.com/eclipse/paho.mqtt.c/files/2496864/error.txt)
[error2.txt](https://github.com/eclipse/paho.mqtt.c/files/2496867/error2.txt)
###without subscribe
[crashWithOutSub.txt](https://github.com/eclipse/paho.mqtt.c/files/2496881/crashWithOutSub.txt)

**Comment by jumoog** [comment]
on my Server it works perfect!

the same binary keeps crashing on my home network. I guess its Socket related.

[Home.txt](https://github.com/eclipse/paho.mqtt.c/files/2498489/Home.txt)
[Server.txt](https://github.com/eclipse/paho.mqtt.c/files/2498493/Server.txt)

**Comment by icraggs** [comment]
What is the hardware/OS you are using at home?  That home.txt trace doesn't look right at all.  Can you try using dynamic library option there to see if it makes a difference?

**Comment by jumoog** [comment]
Home: Windows 10 Pro 1809 (Build 17763.55)
Server: Windows 10 Pro 1803 (Build 17134.345)

(Test VM) Static: 
Installed Windows 10 Pro 1803 and worked. 
Upgraded to Windows 10 Pro 1809 and it worked.

**Comment by Laro88** [comment]
I might have a similar issue trying to build paho.mqtt.cpp.
When I use the .dll + .lib then the sample options are ok, however when I use the -static.lib then it is breaking.
I run the samples against mosquitto.exe -v and I get the errorcode 6 whenever it fails. I am suspecting that something native is blowing up in the paho side of things (when I use the -static.lib)

Is this related to #341 and similar issues (I found at least one other that might be related)

**Comment by dataway** [comment]
The reason for this bug is that MQTTAsync.c defines the function DllMain() which in turn calls a bunch of CreateMutex() and CreateEvent(). Obviously if the library is used statically, DllMain is never executed and these mutexes and events are never initialized.

This initialization code is pretty obviously in the wrong place.

**Comment by icraggs** [comment]
Thanks @dataway .  I never used static builds, nor did I think that static builds would be used when I developed the library.  

The ability to build statically was a contribution, if I remember correctly.  I assume that static builds might work on Linux because the library initialization is different to that on Windows.  If anyone wants to contribute a PR to enable static builds on Windows then I'm very open to that.  If you rely on me to do it, it'll take a while.  Of course, to do the work properly we should include CI tests as well, which will probably be a bit complicated as it means adding the static builds of library + tests.

**Comment by dataway** [comment]
I can submit a PR if you like.

I moved the initialization code to MQTTAsync_createWithOptions, after "if (!global_initialized)" but I'm not convinced that it's the correct place. What if MQTTAsync_createWithOptions is called concurrently from two threads? That said the global_initialized block doesn't look thread-safe anyway at a cursory glance.

What is MQTTAsync_global_init() for? That might be a better place, but it is not called by the paho.mqtt.cpp.

**Comment by fpagliughi** [comment]
As a quick aside, I find myself using static builds more and more these days. Now that even some of my _embedded_ Linux devices have a 1TB SSD in them, disk space isn't at a premium as it was in the past. And it's often convenient to only rebuild, test, and deploy the components in a system that need an update, and leave the others alone (fully built to an old version of the library).

So, long and short, I'd love to see the static build working properly. If a PR is submitted, I would gladly dust off a Windows machine and test it out.
