### ISSUE TITLE
README directions for building with Make: Specify incorrect argument for OPENSSL_ROOT_DIR

### ISSUE THREAD

**Issue by jplflyer** [eclipse-paho/paho.mqtt.c#566]
The README.md says to use argument OPENSSL_SEARCH_PATH for the path to openssl. But at least on MacOS, that flag is wrong. Instead, the argument is OPENSSL_ROOT_DIR.

Specifically, this command:

`$ cmake -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SHARED=FALSE   -DPAHO_MQTT_C_PATH=~/paho.mqtt.c -DOPENSSL_SEARCH_PATH=/usr/local/opt/openssl ..`

Produces this error:

```
CMake Error at /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
```

This command is clean:

`$ cmake -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SHARED=FALSE   -DPAHO_MQTT_C_PATH=~/paho.mqtt.c -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..`

**Comment by icraggs** [comment]
Thanks.

**Comment by icraggs** [comment]
I think this is fixed.
