### ISSUE TITLE
Error during make on Cygwin

### ISSUE THREAD

**Issue by soulflyer13** [eclipse-paho/paho.mqtt.c#568]
Hello,
I'm trying to compile the project on Windows 10 with cygwin.

I have cloned the repo and when I execute the line "make". I'm getting the following errors;

> $ make
mkdir -p build/output/samples
mkdir -p build/output/test
echo OSTYPE is Windows_NT
OSTYPE is Windows_NT
cc -g -fPIC  -Os -Wall -fvisibility=hidden -Ibuild  -o build/output/libpaho-mqtt3c.so.1.0 src/Tree.c src/SocketBuffer.c src/utf-8.c src/MQTTReasonCodes.c src/LinkedList.c src/MQTTPersistence.c src/Log.c src/MQTTClient.c src/SHA1.c src/Thread.c src/OsWrapper.c src/Clients.c src/WebSocket.c src/MQTTPacketOut.c src/Messages.c src/MQTTPersistenceDefault.c src/MQTTProtocolClient.c src/MQTTProperties.c src/Base64.c src/StackTrace.c src/MQTTProtocolOut.c src/MQTTPacket.c src/Socket.c src/Heap.c  -shared -Wl,-init, -lpthread
src/SHA1.c: In function ‘SHA1_ProcessBlock’:
src/SHA1.c:109:10: warning: implicit declaration of function ‘be32toh’ [-Wimplicit-function-declaration]
   w[i] = be32toh(w[i]);
          ^~~~~~~
src/SHA1.c: In function ‘SHA1_Final’:
src/SHA1.c:156:15: warning: implicit declaration of function ‘htobe32’ [-Wimplicit-function-declaration]
  ctx->w[14] = htobe32((uint32_t)(total >> 32));
               ^~~~~~~
src/StackTrace.c: In function ‘StackTrace_entry’:
src/StackTrace.c:110:34: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   Log_stackTrace(trace_level, 9, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                  ^
src/StackTrace.c: In function ‘StackTrace_exit’:
src/StackTrace.c:134:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 10, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                    ^
src/StackTrace.c:136:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 11, (int)my_thread->id, my_thread->current_depth, name, line, (int*)rc);
                                    ^
/tmp/cceX9sG9.o: In function `SHA1_ProcessBlock':
/home/soulflyer/paho.mqtt.c/src/SHA1.c:109: undefined reference to `be32toh'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:109:(.text+0x48): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `be32toh'
/tmp/cceX9sG9.o: In function `SHA1_Final':
/home/soulflyer/paho.mqtt.c/src/SHA1.c:156: undefined reference to `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:156:(.text+0x256): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:157: undefined reference to `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:157:(.text+0x262): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:162: undefined reference to `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:162:(.text+0x275): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
collect2: error: ld returned 1 exit status
make: *** [Makefile:245: build/output/libpaho-mqtt3c.so.1.0] Error 

I'm guessing there is a problem with OpenSSL but I couldn't figure out how to make it work.

when I try " cmake -G "Unix Makefiles" /home/soulflyer/paho.mqtt.c -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_STATIC=TRUE -DOPENSSL_SEARCH_PATH=/usr/local"

> --CMake version: 3.6.2
-- CMake system name: CYGWIN
-- Timestamp is 2018-10-22T21:18:14Z
-- OpenSSL hints: /usr/local
-- OpenSSL headers found at /usr/local/include
-- OpenSSL library found at /lib/libssl.dll.a
-- OpenSSL Crypto library found at /lib/libcrypto.dll.a
-- OpenSSL hints: /usr/local
-- OpenSSL headers found at /usr/local/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/soulflyer/paho.mqtt.c/build

And then when I use "make" under build folder

> $ make
[ 22%] Built target common_obj
Scanning dependencies of target paho-mqtt3a
[ 23%] Building C object src/CMakeFiles/paho-mqtt3a.dir/MQTTAsync.c.o
[ 24%] Linking C shared library cygpaho-mqtt3a-1.dll
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0xd9): undefined reference to `be32toh'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0xd9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `be32toh'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3d1): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3d1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3e5): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3e5): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x417): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x417): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/paho-mqtt3a.dir/build.make:139: src/cygpaho-mqtt3a-1.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: src/CMakeFiles/paho-mqtt3a.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

Thanks for your help

**Comment by icraggs** [comment]
Some older versions of Visual Studio such as 2010 have trouble with some of those function definitions as in #561.   What Visual Studio version are you using?

**Comment by soulflyer13** [comment]
I have Visual Studio 2017, I can build using via Visual Studio successfully.
But when I try in cygwin I'm getting the error.

If i try make in source code, the output is;

> $ make
mkdir -p build/output/samples
mkdir -p build/output/test
echo OSTYPE is Windows_NT
OSTYPE is Windows_NT
sed -e "s/@CLIENT_VERSION@/1.3.0/g" -e "s/@BUILD_TIMESTAMP@//g" src/VersionInfo.h.in > build/VersionInfo.h
cc -g -fPIC  -Os -Wall -fvisibility=hidden -Ibuild  -o build/output/libpaho-mqtt3c.so.1.0 src/Tree.c src/SocketBuffer.c src/utf-8.c src/MQTTReasonCodes.c src/LinkedList.c src/MQTTPersistence.c src/Log.c src/MQTTClient.c src/SHA1.c src/Thread.c src/OsWrapper.c src/Clients.c src/WebSocket.c src/MQTTPacketOut.c src/Messages.c src/MQTTPersistenceDefault.c src/MQTTProtocolClient.c src/MQTTProperties.c src/Base64.c src/StackTrace.c src/MQTTProtocolOut.c src/MQTTPacket.c src/Socket.c src/Heap.c  -shared -Wl,-init, -lpthread
src/SHA1.c: In function ‘SHA1_ProcessBlock’:
src/SHA1.c:109:10: warning: implicit declaration of function ‘be32toh’ [-Wimplicit-function-declaration]
   w[i] = be32toh(w[i]);
          ^~~~~~~
src/SHA1.c: In function ‘SHA1_Final’:
src/SHA1.c:156:15: warning: implicit declaration of function ‘htobe32’ [-Wimplicit-function-declaration]
  ctx->w[14] = htobe32((uint32_t)(total >> 32));
               ^~~~~~~
src/StackTrace.c: In function ‘StackTrace_entry’:
src/StackTrace.c:110:34: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   Log_stackTrace(trace_level, 9, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                  ^
src/StackTrace.c: In function ‘StackTrace_exit’:
src/StackTrace.c:134:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 10, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                    ^
src/StackTrace.c:136:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 11, (int)my_thread->id, my_thread->current_depth, name, line, (int*)rc);
                                    ^
/tmp/ccfLJP7o.o: In function `SHA1_ProcessBlock':
/home/soulflyer/paho.mqtt.c/src/SHA1.c:109: undefined reference to `be32toh'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:109:(.text+0x48): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `be32toh'
/tmp/ccfLJP7o.o: In function `SHA1_Final':
/home/soulflyer/paho.mqtt.c/src/SHA1.c:156: undefined reference to `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:156:(.text+0x256): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:157: undefined reference to `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:157:(.text+0x262): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:162: undefined reference to `htobe32'
/home/soulflyer/paho.mqtt.c/src/SHA1.c:162:(.text+0x275): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
collect2: error: ld returned 1 exit status
make: *** [Makefile:245: build/output/libpaho-mqtt3c.so.1.0] Error 1

If i try with with cmake without SSL

>$ cmake -G "Unix Makefiles" /home/soulflyer/paho.mqtt.c/
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake version: 3.6.2
-- CMake system name: CYGWIN
-- Timestamp is 2018-10-24T20:24:10Z
-- Configuring done
-- Generating done
-- Build files have been written to: /home/soulflyer/paho.mqtt.c/build

>  $ make
Scanning dependencies of target common_obj
[  1%] Building C object src/CMakeFiles/common_obj.dir/MQTTProtocolClient.c.o
[  3%] Building C object src/CMakeFiles/common_obj.dir/Clients.c.o
[  5%] Building C object src/CMakeFiles/common_obj.dir/utf-8.c.o
[  7%] Building C object src/CMakeFiles/common_obj.dir/StackTrace.c.o
/home/soulflyer/paho.mqtt.c/src/StackTrace.c: In function ‘StackTrace_entry’:
/home/soulflyer/paho.mqtt.c/src/StackTrace.c:110:34: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   Log_stackTrace(trace_level, 9, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                  ^
/home/soulflyer/paho.mqtt.c/src/StackTrace.c: In function ‘StackTrace_exit’:
/home/soulflyer/paho.mqtt.c/src/StackTrace.c:134:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 10, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                    ^
/home/soulflyer/paho.mqtt.c/src/StackTrace.c:136:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 11, (int)my_thread->id, my_thread->current_depth, name, line, (int*)rc);
                                    ^
[  9%] Building C object src/CMakeFiles/common_obj.dir/MQTTPacket.c.o
[ 10%] Building C object src/CMakeFiles/common_obj.dir/MQTTPacketOut.c.o
[ 12%] Building C object src/CMakeFiles/common_obj.dir/Messages.c.o
[ 14%] Building C object src/CMakeFiles/common_obj.dir/Tree.c.o
[ 16%] Building C object src/CMakeFiles/common_obj.dir/Socket.c.o
[ 18%] Building C object src/CMakeFiles/common_obj.dir/Log.c.o
[ 20%] Building C object src/CMakeFiles/common_obj.dir/MQTTPersistence.c.o
[ 21%] Building C object src/CMakeFiles/common_obj.dir/Thread.c.o
[ 23%] Building C object src/CMakeFiles/common_obj.dir/MQTTProtocolOut.c.o
[ 25%] Building C object src/CMakeFiles/common_obj.dir/MQTTPersistenceDefault.c.o
[ 27%] Building C object src/CMakeFiles/common_obj.dir/SocketBuffer.c.o
[ 29%] Building C object src/CMakeFiles/common_obj.dir/Heap.c.o
[ 30%] Building C object src/CMakeFiles/common_obj.dir/LinkedList.c.o
[ 32%] Building C object src/CMakeFiles/common_obj.dir/MQTTProperties.c.o
[ 34%] Building C object src/CMakeFiles/common_obj.dir/MQTTReasonCodes.c.o
[ 36%] Building C object src/CMakeFiles/common_obj.dir/Base64.c.o
[ 38%] Building C object src/CMakeFiles/common_obj.dir/SHA1.c.o
/home/soulflyer/paho.mqtt.c/src/SHA1.c: In function ‘SHA1_ProcessBlock’:
/home/soulflyer/paho.mqtt.c/src/SHA1.c:109:10: warning: implicit declaration of function ‘be32toh’ [-Wimplicit-function-declaration]
   w[i] = be32toh(w[i]);
          ^~~~~~~
/home/soulflyer/paho.mqtt.c/src/SHA1.c: In function ‘SHA1_Final’:
/home/soulflyer/paho.mqtt.c/src/SHA1.c:156:15: warning: implicit declaration of function ‘htobe32’ [-Wimplicit-function-declaration]
  ctx->w[14] = htobe32((uint32_t)(total >> 32));
               ^~~~~~~
[ 40%] Building C object src/CMakeFiles/common_obj.dir/WebSocket.c.o
[ 40%] Built target common_obj
Scanning dependencies of target paho-mqtt3a
[ 41%] Building C object src/CMakeFiles/paho-mqtt3a.dir/MQTTAsync.c.o
[ 43%] Linking C shared library cygpaho-mqtt3a-1.dll
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0xd9): undefined reference to `be32toh'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0xd9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `be32toh'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3d1): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3d1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3e5): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3e5): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x417): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x417): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/paho-mqtt3a.dir/build.make:139: src/cygpaho-mqtt3a-1.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:206: src/CMakeFiles/paho-mqtt3a.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

If I try with SSL;

> $ cmake -G "Unix Makefiles" -DPAHO_WITH_SSL=TRUE /home/soulflyer/paho.mqtt.c/
-- CMake version: 3.6.2
-- CMake system name: CYGWIN
-- Timestamp is 2018-10-24T20:27:25Z
-- OpenSSL hints:
-- OpenSSL headers found at /usr/local/include
-- OpenSSL library found at /usr/local/lib/libssl.dll.a
-- OpenSSL Crypto library found at /usr/local/lib/libcrypto.dll.a
-- OpenSSL hints:
-- OpenSSL headers found at /usr/local/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/soulflyer/paho.mqtt.c/build

> $ make
Scanning dependencies of target common_ssl_obj
[  1%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTProtocolClient.c.o
[  2%] Building C object src/CMakeFiles/common_ssl_obj.dir/Clients.c.o
[  3%] Building C object src/CMakeFiles/common_ssl_obj.dir/utf-8.c.o
[  4%] Building C object src/CMakeFiles/common_ssl_obj.dir/StackTrace.c.o
/home/soulflyer/paho.mqtt.c/src/StackTrace.c: In function ‘StackTrace_entry’:
/home/soulflyer/paho.mqtt.c/src/StackTrace.c:110:34: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   Log_stackTrace(trace_level, 9, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                  ^
/home/soulflyer/paho.mqtt.c/src/StackTrace.c: In function ‘StackTrace_exit’:
/home/soulflyer/paho.mqtt.c/src/StackTrace.c:134:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 10, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                    ^
/home/soulflyer/paho.mqtt.c/src/StackTrace.c:136:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 11, (int)my_thread->id, my_thread->current_depth, name, line, (int*)rc);
                                    ^
[  5%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTPacket.c.o
[  6%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTPacketOut.c.o
[  8%] Building C object src/CMakeFiles/common_ssl_obj.dir/Messages.c.o
[  9%] Building C object src/CMakeFiles/common_ssl_obj.dir/Tree.c.o
[ 10%] Building C object src/CMakeFiles/common_ssl_obj.dir/Socket.c.o
[ 11%] Building C object src/CMakeFiles/common_ssl_obj.dir/Log.c.o
[ 12%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTPersistence.c.o
[ 13%] Building C object src/CMakeFiles/common_ssl_obj.dir/Thread.c.o
[ 14%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTProtocolOut.c.o
[ 16%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTPersistenceDefault.c.o
[ 17%] Building C object src/CMakeFiles/common_ssl_obj.dir/SocketBuffer.c.o
[ 18%] Building C object src/CMakeFiles/common_ssl_obj.dir/Heap.c.o
[ 19%] Building C object src/CMakeFiles/common_ssl_obj.dir/LinkedList.c.o
[ 20%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTProperties.c.o
[ 21%] Building C object src/CMakeFiles/common_ssl_obj.dir/MQTTReasonCodes.c.o
[ 22%] Building C object src/CMakeFiles/common_ssl_obj.dir/Base64.c.o
[ 24%] Building C object src/CMakeFiles/common_ssl_obj.dir/SHA1.c.o
[ 25%] Building C object src/CMakeFiles/common_ssl_obj.dir/WebSocket.c.o
[ 25%] Built target common_ssl_obj
Scanning dependencies of target paho-mqtt3cs
[ 26%] Building C object src/CMakeFiles/paho-mqtt3cs.dir/MQTTClient.c.o
[ 27%] Building C object src/CMakeFiles/paho-mqtt3cs.dir/SSLSocket.c.o
/home/soulflyer/paho.mqtt.c/src/SSLSocket.c: In function ‘SSLSocket_createContext’:
/home/soulflyer/paho.mqtt.c/src/SSLSocket.c:537:4: warning: ‘TLSv1_client_method’ is deprecated [-Wdeprecated-declarations]
    net->ctx = SSL_CTX_new(TLSv1_client_method());
    ^~~
In file included from /usr/local/include/openssl/e_os2.h:13:0,
                 from /usr/local/include/openssl/ssl.h:15,
                 from /home/soulflyer/paho.mqtt.c/src/SocketBuffer.h:28,
                 from /home/soulflyer/paho.mqtt.c/src/SSLSocket.c:31:
/usr/local/include/openssl/ssl.h:1854:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_client_method(void))
 ^
/home/soulflyer/paho.mqtt.c/src/SSLSocket.c:542:4: warning: ‘TLSv1_1_client_method’ is deprecated [-Wdeprecated-declarations]
    net->ctx = SSL_CTX_new(TLSv1_1_client_method());
    ^~~
In file included from /usr/local/include/openssl/e_os2.h:13:0,
                 from /usr/local/include/openssl/ssl.h:15,
                 from /home/soulflyer/paho.mqtt.c/src/SocketBuffer.h:28,
                 from /home/soulflyer/paho.mqtt.c/src/SSLSocket.c:31:
/usr/local/include/openssl/ssl.h:1860:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_client_method(void))
 ^
/home/soulflyer/paho.mqtt.c/src/SSLSocket.c:547:4: warning: ‘TLSv1_2_client_method’ is deprecated [-Wdeprecated-declarations]
    net->ctx = SSL_CTX_new(TLSv1_2_client_method());
    ^~~
In file included from /usr/local/include/openssl/e_os2.h:13:0,
                 from /usr/local/include/openssl/ssl.h:15,
                 from /home/soulflyer/paho.mqtt.c/src/SocketBuffer.h:28,
                 from /home/soulflyer/paho.mqtt.c/src/SSLSocket.c:31:
/usr/local/include/openssl/ssl.h:1866:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void))
 ^
[ 28%] Linking C shared library cygpaho-mqtt3cs-1.dll
[ 28%] Built target paho-mqtt3cs
Scanning dependencies of target common_obj
[ 29%] Building C object src/CMakeFiles/common_obj.dir/MQTTProtocolClient.c.o
[ 31%] Building C object src/CMakeFiles/common_obj.dir/Clients.c.o
[ 32%] Building C object src/CMakeFiles/common_obj.dir/utf-8.c.o
[ 33%] Building C object src/CMakeFiles/common_obj.dir/StackTrace.c.o
/home/soulflyer/paho.mqtt.c/src/StackTrace.c: In function ‘StackTrace_entry’:
/home/soulflyer/paho.mqtt.c/src/StackTrace.c:110:34: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   Log_stackTrace(trace_level, 9, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                  ^
/home/soulflyer/paho.mqtt.c/src/StackTrace.c: In function ‘StackTrace_exit’:
/home/soulflyer/paho.mqtt.c/src/StackTrace.c:134:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 10, (int)my_thread->id, my_thread->current_depth, name, line, NULL);
                                    ^
/home/soulflyer/paho.mqtt.c/src/StackTrace.c:136:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    Log_stackTrace(trace_level, 11, (int)my_thread->id, my_thread->current_depth, name, line, (int*)rc);
                                    ^
[ 34%] Building C object src/CMakeFiles/common_obj.dir/MQTTPacket.c.o
[ 35%] Building C object src/CMakeFiles/common_obj.dir/MQTTPacketOut.c.o
[ 36%] Building C object src/CMakeFiles/common_obj.dir/Messages.c.o
[ 37%] Building C object src/CMakeFiles/common_obj.dir/Tree.c.o
[ 39%] Building C object src/CMakeFiles/common_obj.dir/Socket.c.o
[ 40%] Building C object src/CMakeFiles/common_obj.dir/Log.c.o
[ 41%] Building C object src/CMakeFiles/common_obj.dir/MQTTPersistence.c.o
[ 42%] Building C object src/CMakeFiles/common_obj.dir/Thread.c.o
[ 43%] Building C object src/CMakeFiles/common_obj.dir/MQTTProtocolOut.c.o
[ 44%] Building C object src/CMakeFiles/common_obj.dir/MQTTPersistenceDefault.c.o
[ 45%] Building C object src/CMakeFiles/common_obj.dir/SocketBuffer.c.o
[ 47%] Building C object src/CMakeFiles/common_obj.dir/Heap.c.o
[ 48%] Building C object src/CMakeFiles/common_obj.dir/LinkedList.c.o
[ 49%] Building C object src/CMakeFiles/common_obj.dir/MQTTProperties.c.o
[ 50%] Building C object src/CMakeFiles/common_obj.dir/MQTTReasonCodes.c.o
[ 51%] Building C object src/CMakeFiles/common_obj.dir/Base64.c.o
[ 52%] Building C object src/CMakeFiles/common_obj.dir/SHA1.c.o
/home/soulflyer/paho.mqtt.c/src/SHA1.c: In function ‘SHA1_ProcessBlock’:
/home/soulflyer/paho.mqtt.c/src/SHA1.c:109:10: warning: implicit declaration of function ‘be32toh’ [-Wimplicit-function-declaration]
   w[i] = be32toh(w[i]);
          ^~~~~~~
/home/soulflyer/paho.mqtt.c/src/SHA1.c: In function ‘SHA1_Final’:
/home/soulflyer/paho.mqtt.c/src/SHA1.c:156:15: warning: implicit declaration of function ‘htobe32’ [-Wimplicit-function-declaration]
  ctx->w[14] = htobe32((uint32_t)(total >> 32));
               ^~~~~~~
[ 54%] Building C object src/CMakeFiles/common_obj.dir/WebSocket.c.o
[ 54%] Built target common_obj
Scanning dependencies of target paho-mqtt3a
[ 55%] Building C object src/CMakeFiles/paho-mqtt3a.dir/MQTTAsync.c.o
[ 56%] Linking C shared library cygpaho-mqtt3a-1.dll
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0xd9): undefined reference to `be32toh'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0xd9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `be32toh'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3d1): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3d1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3e5): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x3e5): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x417): undefined reference to `htobe32'
CMakeFiles/common_obj.dir/SHA1.c.o:SHA1.c:(.text+0x417): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `htobe32'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/paho-mqtt3a.dir/build.make:139: src/cygpaho-mqtt3a-1.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:139: src/CMakeFiles/paho-mqtt3a.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

**Comment by icraggs** [comment]
I don't use cygwin for building applications so I don't know how it works.  Is it looking for those functions in the Windows environment, or Cygwin?  If Cygwin, then you'll probably have to find an alternative implementation.  

You could build without SSL support which apparently omits this module.  The module is only needed for WebSocket support.
