### ISSUE TITLE
paho is not  enabling port 1883 8883 so i am not able subscribe or publish using mqtt

### ISSUE THREAD

**Issue by WilliamVJacob** [eclipse-paho/paho.mqtt.c#569]
Hi
I am implementing paho on a MIPS architecture chip using  buildroot  . I am able to build paho successfully . but when I  tried to implement a test subscribe code .I was not able to do it and when I did some digging I found out that paho is not enabling my port 1883  or 8883. please help

**Comment by icraggs** [comment]
I'm not sure what you mean by not opening port 1883 or 8883.  For the MQTTClient API the port you want to connect to is specified on the create:

rc = MQTTAsync_create(&client, url, opts.clientid, MQTTCLIENT_PERSISTENCE_NONE, NULL);

in the url parameter: tcp://localhost:1883 for instance.  The doc for the API call is here:

https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/_m_q_t_t_client_8h.html#a9a0518d9ca924d12c1329dbe3de5f2b6

The sample programs paho_c_pub and paho_c_sub show examples.

**Comment by icraggs** [comment]
I'm going to assume that's answered your question.
