### ISSUE TITLE
'MQTTClient_run' thread uses nearly all the CPU

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#57]
migrated from Bugzilla [#444884](https://bugs.eclipse.org/bugs/show_bug.cgi?id=444884)
status UNCONFIRMED severity _normal_ in component _MQTT-C_ for _1.1_
Reported in version _1.1_ on platform _Other_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[Paho_MQTT_C.log](https://bugs.eclipse.org/bugs//attachment.cgi?id=247322)_ (ID 247322)

On 2014-09-23 17:58:50 -0400, Franz Schnyder wrote:

> Created attachment 247322
> Log file with MQTT_C_CLIENT_TRACE_LEVEL=MINIMUM
> 
> I use multiple MQTT.C client instances each instance is accessed by its own thread.
> 
> When I have 3 or more clients that each sends 6 publish messages about all 30 seconds  the 'MQTTClient_run' thread starts to use nearly all the CPU after some time (between 1 hour or 2 days).
> 
> When the 'MQTTClient_run' uses all the CPU I do not see more network traffic than when it is working 'normal'.  
> 
> I attached a a log file recorded when the 'MQTTClient_run' uses all the CPU and with the level set to MQTT_C_CLIENT_TRACE_LEVEL=MINIMUM  
> 
> Environment:
> ---
> 
> Version: v1.0.1 tag form http://git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.c.git.
> HW: Raspberry Pi model B rev2 
> OS: RASPBIAN Debian Wheezy

On 2014-09-25 16:38:23 -0400, Franz Schnyder wrote:

> I tried to find out why the Socket_getReadySocket does not return 0 but always a socket even though there was no network traffic at that time. I found that my process had beside the 3 used sockets some "leaked" sockets:
> 
>    sudo lsof -a -p <pid>
>    ...
>    IPv4 TCP PiTwo:44388->MqttBroker:1883 (CLOSE_WAIT)
>    IPv4 TCP PiTwo:44666->MqttBroker:1883 (ESTABLISHED)
>    IPv4 TCP PiTwo:44403->MqttBroker:1883 (CLOSE_WAIT)
>    IPv4 TCP PiTwo:44667->MqttBroker:1883 (CLOSE_WAIT)
>    IPv4 TCP PiTwo:44669->MqttBroker:1883 (ESTABLISHED)
>    IPv4 TCP PiTwo:44674->MqttBroker:1883 (CLOSE_WAIT)
>    IPv4 TCP PiTwo:44676->MqttBroker:1883 (CLOSE_WAIT)
>    IPv4 TCP PiTwo:44680->MqttBroker:1883 (CLOSE_WAIT)
>    IPv4 TCP PiTwo:44682->MqttBroker:1883 (CLOSE_WAIT)
>    IPv4 TCP PiTwo:44686->MqttBroker:1883 (ESTABLISHED)
>    ...
> 
> I then found out that in some situation my code destroyed (MQTTClient_destroy) a connected client without a prior call to MQTTClient_disconnect which results in the 'leaked' sockets. I changed my code so it ensures it always disconnects the client prior to destroying them and the 'leaked' sockets are gone. The gateway now runs for more that one day and the CPU usage is still normal and the Socket_getReadySocket return 0 when there is no network traffic.
> 
> So I guess the problem I described above is probably the result of not disconnecting the client prior to destroying it. 
> 
> So i don't know if this is considered a bug of the library or if the library user must ensure that he disconnects a client before destroying the client.

On 2014-09-26 10:59:18 -0400, Ian Craggs wrote:

> (In reply to Franz Schnyder from comment # 1)
> 
> > I tried to find out why the Socket_getReadySocket does not return 0 but
> > always a socket even though there was no network traffic at that time. I
> > found that my process had beside the 3 used sockets some "leaked" sockets:
> > 
> >    sudo lsof -a -p <pid>
> >    ...
> >    IPv4 TCP PiTwo:44388->MqttBroker:1883 (CLOSE_WAIT)
> >    IPv4 TCP PiTwo:44666->MqttBroker:1883 (ESTABLISHED)
> >    IPv4 TCP PiTwo:44403->MqttBroker:1883 (CLOSE_WAIT)
> >    IPv4 TCP PiTwo:44667->MqttBroker:1883 (CLOSE_WAIT)
> >    IPv4 TCP PiTwo:44669->MqttBroker:1883 (ESTABLISHED)
> >    IPv4 TCP PiTwo:44674->MqttBroker:1883 (CLOSE_WAIT)
> >    IPv4 TCP PiTwo:44676->MqttBroker:1883 (CLOSE_WAIT)
> >    IPv4 TCP PiTwo:44680->MqttBroker:1883 (CLOSE_WAIT)
> >    IPv4 TCP PiTwo:44682->MqttBroker:1883 (CLOSE_WAIT)
> >    IPv4 TCP PiTwo:44686->MqttBroker:1883 (ESTABLISHED)
> >    ...
> > 
> > I then found out that in some situation my code destroyed
> > (MQTTClient_destroy) a connected client without a prior call to
> > MQTTClient_disconnect which results in the 'leaked' sockets. I changed my
> > code so it ensures it always disconnects the client prior to destroying them
> > and the 'leaked' sockets are gone. The gateway now runs for more that one
> > day and the CPU usage is still normal and the Socket_getReadySocket return 0
> > when there is no network traffic.
> > 
> > So I guess the problem I described above is probably the result of not
> > disconnecting the client prior to destroying it. 
> > 
> > So i don't know if this is considered a bug of the library or if the library
> > user must ensure that he disconnects a client before destroying the client.
> 
> In one sense I don't consider it a bug as destroy was intended to be called only once the client object was finished with.
> 
> However, the resulting behaviour is very unhelpful, so I am all in favour of improving the situation.

**Comment by icraggs** [comment]
Remaining question replaced by https://github.com/eclipse/paho.mqtt.c/issues/137
