### ISSUE TITLE
Premature "PINGRESP not received" in a one-way connection

### ISSUE THREAD

**Issue by rthrippleton** [eclipse-paho/paho.mqtt.c#570]
We're using Paho 1.2.1 , the async API, and using the default connect options (keepAliveInterval=60).

In a particular test of our product, we have two QoS 0 connections to a broker. The connections are only used for publishing, not receiving. On rare occasions, Paho decides that the connection has been lost. Looking at a packet trace, we get:

20181017 141349.376 received 0 256 buflen 5
20181017 141349.376 6 apme476721304cac6db <- PINGRESP
20181017 141349.662 received 0 256 buflen 5
20181017 141349.662 7 apmfe9110f2e635cddb <- PINGRESP
<lots and lots of PUBLISH>
20181017 141451.916 sent 0 256 buflen 5
20181017 141451.916 7 apmfe9110f2e635cddb -> PINGREQ (0)
20181017 141451.916 sent 0 256 buflen 5
20181017 141451.916 6 apme476721304cac6db -> PINGREQ (0)
20181017 141451.916 sent 0 256 buflen 5
20181017 141451.916 7 apmfe9110f2e635cddb -> PUBLISH qos: 0 retained: 0 (0)
20181017 141451.916 sent 0 256 buflen 5
20181017 141451.955 6 apme476721304cac6db -> PUBLISH qos: 0 retained: 0 (0)
<lots and lots of PUBLISH>
20181017 141457.321 PINGRESP not received in keepalive interval for client apmfe9110f2e635cddb on socket 7, disconnecting
20181017 141457.321 PINGRESP not received in keepalive interval for client apme476721304cac6db on socket 6, disconnecting

So it looks like a premature disconnection; the gap between PINGREQ and PINGRESP is a lot less than 60 seconds.

On code-inspection, I think the problem is in the outermost "if" statement in MQTTProtocol_keepalive, combined with the fact that our connection is only ever publishing. If a packet hasn't been sent for 60 seconds, *or* a packet hasn't been received for 60 seconds, disconnect. The last packet received was PINGRESP over 60 seconds ago, hence the second condition was true, despite the connection and broker being quite healthy, albeit a little slow at times.

I think the only reason this happens rarely is because it requires the retryLoopInterval and keepAliveInterval to get in a certain kind of 'phase' with each other.

Naively I'd suggest replacing the || with a &&, but I'm not 100% sure that's correct in all use-cases.

**Comment by icraggs** [comment]
Hi.  Thanks.  I think that the logic in the embedded C client is correct.  See the keepalive() member function in:

https://github.com/eclipse/paho.mqtt.embedded-c/blob/master/MQTTClient/src/MQTTClient.h

I'm trying out a fix which looks like that.

**Comment by icraggs** [comment]
I've put it into the develop branch.  The changes should work for 1.2.1 as well if you want to try them out.
