### ISSUE TITLE
Compile Win32 version with MinGW 5.3.0 under Win32

### ISSUE THREAD

**Issue by CapitanFuture** [eclipse-paho/paho.mqtt.c#577]
I try to compile the package with MinGW 5.3.0 / Ninja  under Win10 Environment 

During Linking I get the following 

```
src/CMakeFiles/common_obj.dir/Base64.c.obj:Base64.c:(.text+0x44): undefined reference to `_imp__CryptStringToBinaryA@28'
src/CMakeFiles/common_obj.dir/Base64.c.obj:Base64.c:(.text+0x94): undefined reference to `_imp__CryptBinaryToStringA@20'
src/CMakeFiles/common_obj.dir/WebSocket.c.obj:WebSocket.c:(.text+0xe1): undefined reference to `_imp__UuidCreate@4'
src/CMakeFiles/common_obj.dir/WebSocket.c.obj:WebSocket.c:(.text+0x575): undefined reference to `htonll'
src/CMakeFiles/common_obj.dir/WebSocket.c.obj:WebSocket.c:(.text+0x894): undefined reference to `ntohll'
src/CMakeFiles/common_obj.dir/WebSocket.c.obj:WebSocket.c:(.text+0xfba): undefined reference to `htonll'
collect2.exe: error: ld returned 1 exit status
```

Environment 
```
-- The C compiler identification is GNU 5.3.0
-- Check for working C compiler: C:/tools/mingw32/bin/gcc.exe
-- Check for working C compiler: C:/tools/mingw32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake version: 3.12.2
-- CMake system name: Windows
-- Timestamp is 2018-11-03T11:07:28Z
-- Configuring done
-- Generating done
```

It seem's to me that I need **crypt32** and **rocRT4** libs ?

**Comment by icraggs** [comment]
I don't really know enough about MinGW to say.  The main environments supported are Linux (with make and CMake), Windows (with CMake and Visual Studio) and MacOS (with make and CMake).

Some of those functions are Windows APIs (Crypt...) - I don't know how those are supposed to be accessible from a MinGW build.  As it happens, all of those functions are within the WebSocket support.

**Comment by JanWillemPxC** [comment]
I'm not sure if it completely works but it compiles nicely ;)

in the src/cmakelist i added some win32 libraries.

`IF (WIN32)`
`SET(LIBS_SYSTEM ws2_32 Crypt32 Rpcrt4)`

For some reason i cannot get de HTONLL to work with the winsock library stackoverflow helped out
[stackoverflow](https://stackoverflow.com/questions/16375340/c-htonll-and-back)

`#define HTONLL(x) ((1==htonl(1)) ? (x) : (((uint64_t)htonl((x) & 0xFFFFFFFFUL)) << 32) | htonl((uint32_t)((x) >> 32)))`
`#define NTOHLL(x) ((1==ntohl(1)) ? (x) : (((uint64_t)ntohl((x) & 0xFFFFFFFFUL)) << 32) | ntohl((uint32_t)((x) >> 32)))`

The above defines i added to the websocket.h.
It is not the most desired beautifull multiplatform solution .. 
If someone has a good improvement for that feel free to comment.

**Comment by icraggs** [comment]
If someone wants to submit a PR with changes that make this work, that would be great.  Of course, all the existing builds would still have to work.
