### ISSUE TITLE
MQTTAsync_destroy does not return

### ISSUE THREAD

**Issue by JGrossholtz** [eclipse-paho/paho.mqtt.c#578]
Hi,

I use libpaho 1.2.0 (seems similar on 1.2.1 and 1.3.0) on a Linux platform. I have a small issue regarding MQTTAsync_destroy, it does not return and my thread remains blocked there.

Here is how I obtain this behaviour:
- My program connects to a Mosquitto broker, data is exchanged with the broker
- For tests purposes I stop the broker
- The connection_lost_handler is called, so my program tries to reconnect with MQTTAsync_connect
- Soon after the onFailure callback is called by paho (from MQTTAsync_connect connect options).

After this, I call MQTTAsync_disconnect and then MQTTAsync_destroy, but it does not return and my thread remains blocked there.

I am able to reproduce this each time.

Any idea? What could produce this behaviour and how can I avoid it in your opinion?

Best regards,

**Comment by FrankPagliughi-DM** [comment]
One thing that may be helpful in these situations is to turn on logging using environment variables, as described at the bottom of the [README.md](https://github.com/eclipse/paho.mqtt.c/blob/master/README.md)

Like:
```
export MQTT_C_CLIENT_TRACE=ON
export MQTT_C_CLIENT_TRACE_LEVEL=MEDIUM
```

**Comment by icraggs** [comment]
As Frank says, a trace would help a lot.  The destroy call tries to clean up all the library's data structures if it is the last client to go, but this apparently runs into some timing issues.  It is quite likely waiting for some connect/disconnect process to finish in this case.

There is a proposal to separate out this cleanup process into (whatever the opposite of initialize is) another function, but I haven't done that yet.

**Comment by icraggs** [comment]
I need to see what happens after the call to connect failure.  The checkTimeouts function requests a mutex lock, so some other thread must be holding on to it.

**Comment by JGrossholtz** [comment]
Thank you for your answers, is this what you need ? Or you need some code ?

20181106 121326.985 Calling connect failure for client mqtt_client_1541506406
20181106 121326.985 (1199564544)    (3)> MQTTAsync_destroy:1603
20181106 121327.887 (1207957248)  (1)< Thread_wait_cond:381 (110)
20181106 121327.887 (1207957248)  (1)> MQTTAsync_checkTimeouts:1400
20181106 121327.887 (1207957248)  (1)< MQTTAsync_checkTimeouts:1468
20181106 121327.887 (1207957248)  (1)> Thread_wait_cond:367
20181106 121327.887 (1207957248)  (1)< Thread_wait_cond:381 (110)
20181106 121327.887 (1207957248)  (1)> MQTTAsync_checkTimeouts:1400
20181106 121327.887 (1207957248)  (1)< MQTTAsync_checkTimeouts:1468
20181106 121327.887 (1207957248)  (1)> Thread_wait_cond:367
20181106 121327.887 (1207957248)  (1)< Thread_wait_cond:381 (110)
20181106 121327.887 (1207957248)  (1)> MQTTAsync_checkTimeouts:1400

**Comment by JGrossholtz** [comment]
If I avoid to call MQTTAsync_destroy and try to call MQTTAsync_create again it also does not return.

What I observe each time in all situations is MQTTAsync_checkTimeouts being the last called function but does never reach its exit. So I guess mqttasync_mutex remains locked and may never get a chance to do its work ( we do not see logs coming from MQTTAsync_removeResponsesAndCommands).

**Comment by JGrossholtz** [comment]
Thanks a lot for your help. I am using 1.2.0 for dependency reasons but I could change that. Anyway, the problem remains the same.
Here is a trace with 1.3.0:
20181108 171030.067 Calling connect failure for client mqtt_client_1541697008
2018-11-08|17:10:30.068|+00:00|   22.105|core    |90:133| src/remote.c:210:_on_connect_failure |Connect failed, rc -1
20181108 171030.067 (956274432)     (4)> MQTTAsync_disconnect1:3050
20181108 171030.067 (956274432)     (4)< MQTTAsync_disconnect1:3087 (-3)
20181108 171030.067 (956274432)     (4)> MQTTAsync_destroy:1937
20181108 171030.067 (964667136)  (1)< Thread_wait_cond:419 (110)
20181108 171030.067 (964667136)  (1)> MQTTAsync_checkTimeouts:1730
20181108 171030.067 (964667136)  (1)< MQTTAsync_checkTimeouts:1778
20181108 171030.067 (964667136)  (1)> Thread_wait_cond:411
20181108 171031.966 (964667136)  (1)< Thread_wait_cond:419 (110)
20181108 171031.966 (964667136)  (1)> MQTTAsync_checkTimeouts:1730
20181108 171031.966 (964667136)  (1)< MQTTAsync_checkTimeouts:1778
20181108 171031.966 (964667136)  (1)> Thread_wait_cond:411
20181108 171031.966 (964667136)  (1)< Thread_wait_cond:419 (110)
20181108 171031.966 (964667136)  (1)> MQTTAsync_checkTimeouts:1730

And a bigger log is here:
[deadlock_paho-c-mqtt-1.3.0.txt](https://github.com/eclipse/paho.mqtt.c/files/2562782/deadlock_paho-c-mqtt-1.3.0.txt)

**Comment by icraggs** [comment]
Are you calling destroy() in the connect failure callback?  You shouldn't do that - you'll be trying to destroy the object in which the callback is operating.

**Comment by JGrossholtz** [comment]
You are right, that was my problem. Thank you very much. I though I was calling destroy in a separate thread but I was not. I have some complexity on the application side too.

I believe most users will either try to reconnect or destroy the paho handler after the failure callback. It is easy to make this mistake. I suggest to mention it in the documentation. If you agree I could submit a patch to complete "It should be called when the client is no longer required".

**Comment by icraggs** [comment]
Please do submit a PR to update the documentation.  Neither create nor destroy should be called within a callback.  Thanks!
