### ISSUE TITLE
MQTT on ESP8266 with RTOS

### ISSUE THREAD

**Issue by i17brn** [eclipse-paho/paho.mqtt.c#579]
I would like to use MQTT Paho library on my project, I'm using ESP8266 with FreeRTOS, and it has its own Mqtt library by Paho but when I try to use doesnt work, I use ur code and its the same, could you help me?

**Comment by icraggs** [comment]
I suggest you use the supplied FreeRTOS MQTT client, and ask for support from whatever resources they supply.  

If you do add more details here, I might possibly be able to give some simple pointers.
