### ISSUE TITLE
connection lost, if keepalive timeout is 20 minutes

### ISSUE THREAD

**Issue by Jainsaksham** [eclipse-paho/paho.mqtt.c#581]
I implemented basic MQTT async functionality with keepalive interval 20 minutes . After getting connection lost, we start from the MQTTAsync_connect function again with cleansession = 1.
But every connection set up with success callback, connection lost callback message come within 30 minutes.

**Comment by icraggs** [comment]
You could get a trace (see the README for how).  What happens if you set the keep alive to say 1 minute instead?  20 minutes is quite a long time for the keepalive.  What server are you using?  What does the server log say about the disconnect - anything?

**Comment by Jainsaksham** [comment]
Due to power consumption, we set keepalive 20 minutes. We checked keepalive with 1 minutes, it is working fine. We are using AWS server.

**Comment by icraggs** [comment]
So you'll need to get a trace - at the PROTOCOL level might be enough.  Or does the AWS server have any log messages?  I think 20 minutes is long enough that some other timeout might kick in, like TCP maybe.  Depends how much MQTT traffic you have.

There is also this issue, with a fix I've added to the development branch: https://github.com/eclipse/paho.mqtt.c/issues/570

**Comment by InventoryTech** [comment]
I'm seeing something similar; connection drops out after ~30 mins of inactivity (keepalive 0), however in my case MQTT itself doesn't seem to think connection has been lost - no disconnect callback and no 'connection lost' type messages in the logs on the broker or client. 

Looking at Wireshark traces I can see TCP retransmissions on our MQTT publish - and therefore there is no PUBACK coming back. Using the async_client, we just wait on a publish token forever. (Yes, we could use wait_for() and timeout, but that doesn't solve the root problem).

Setting keepalive to once every 15 mins also did not solve the problem. A successful keepalive occurred and then 4 minutes later a publish message failed again. The attached screenshot shows the successful keepalive at 16:54:53, followed by our own ping check (ICMP) at 16:59:40 before attempting to publish an MQTT message at 16:59:41 - the TCP retransmission occurs on the MQTT message packet and does not recover. 
![image](https://user-images.githubusercontent.com/49542518/76268665-a12e2980-62d3-11ea-9118-738936956dd8.png)

Note: this also _only_ seems to happen with a cellular modem. Over Wi-fi I'm not seeing this problem. Any suggestions for what else I can try to work out what is going on?

I should also mention we're also using the C++ wrapper.

**Comment by icraggs** [comment]
@InventoryTech the loss of connection will only be detected if some action is taken on the socket and there is a bad return code from TCP, or there is no response from a PING.   If the network stack does not return an error from the write to the socket (with a publish for instance), you'll need the lack of ping response to indicate connection lost.  TCP stacks can behave differently, especially cellular vs wifi vs wired.

**Comment by icraggs** [comment]
I think these are behaving correctly - the connection will only be detected as lost if some operation is attempted, which is the purpose of the keepalive - sending a ping.
