### ISSUE TITLE
memory statistics

### ISSUE THREAD

**Issue by ustccw** [eclipse-paho/paho.mqtt.c#585]
Hi, 
Here are two questions for you:
1. Is there a memory statistics? 
how much memory a Simple MQTT connecting cost, and how much memory a Two-Way Authentication cost with default configuration?

2. compare with [eclipse embedded mqtt](https://github.com/eclipse/paho.mqtt.embedded-c), what about memory compare?

**Comment by ustccw** [comment]
@icraggs Hi, is there any response?

**Comment by icraggs** [comment]
I have not done such a comparison.  But the answer will be, it depends on lots of factors.  When using the embedded client, there are three different options at this point: MQTTPacket, MQTTClient and MQTTClient-C, each of which come with their own capabilities and restrictions.  MQTTPacket is the most lightweight but the least capable.   Unless you are on a severely restricted device, or on a platform which this client library does not support, I would probably advise against using the embedded client library.

**Comment by ustccw** [comment]
@icraggs thanks for your response!
For excellent eclipse MQTTs, it's best to have a memory usage statistics for user. It will help embedded device to decide which is best choice. 

emmm, thanks any way.
