### ISSUE TITLE
MQTTClient_create() return error(MQTTCLIENT_BAD_PROTOCOL:-14)

### ISSUE THREAD

**Issue by luoluowang** [eclipse-paho/paho.mqtt.c#587]
I'm trying to make the MQTT client work with SSL,
but,MQTTClient_create() return error(MQTTCLIENT_BAD_PROTOCOL:-14)
#define ADDRESS     "ssl://valid_address:8883".

Dose anyone else have this problem?

**Comment by icraggs** [comment]
This error code is returned if you don't link with the TLS enabled version of the library (paho-mqtt3cs not paho-mqtt3c).  I've updated the doc for the BAD_PROTOCOL return code to explain this.

**Comment by luoluowang** [comment]
Thanks,the problem has been solved.
