### ISSUE TITLE
Client times out with keep alive interval of 1s

### ISSUE THREAD

**Issue by blues-breaker** [eclipse-paho/paho.mqtt.c#590]
When connecting a client with a keep alive interval of one second the client does not seem to send PINGREQs at the required rate.

This results in the broker disconnecting the client.

Mosquitto in verbose mode prints: `Client <client name> has exceeded timeout, disconnecting`.

The Python Paho library can connect a client with 1s keep alive interval without issue, so I think the broker can be ruled out initially.

I first encountered this problem using the paho C++ library, I then modified the MQTTClient_publish.c example program to see if the issue also existed in the C library.

Applying the fix mentioned in #570 did not solve the issue either.

Please find attached test program to reproduce the issue along with a trace file. 
[C_keep_alive_test.zip](https://github.com/eclipse/paho.mqtt.c/files/2648625/C_keep_alive_test.zip)

**Comment by icraggs** [comment]
I didn't intend that the keep alive interval should be as low as one second, so I'm not surprised.  The normal range for applications, in my experience, is 30 to 60 seconds.

It's controlled by the call to MQTTProtocol_keepalive(), and is rate limited to 1 per second due to the cost of calling time().  The rate could be increased at the expense of making more system calls.

**Comment by blues-breaker** [comment]
Thanks for the reply.

In my application MQTT is being used for pub/sub communication between several programs (some of which are running on limited hardware) on the same wired network. 

In this case the keep alive is being used to ensure a program hasn't gone down and so 1 second is a convenient value to use. 

As the library interface allows setting of the keep alive interval to 1 second, it seems like the behaviour I experienced would be classed as a bug?

Do you think a fix would be fairly straightforward to implement? 

Thanks again

**Comment by fpagliughi** [comment]
On a LAN, wouldn't severance of the TCP connection be enough to discover the lost client?

**Comment by blues-breaker** [comment]
@fpagliughi Yes, possibly - I'll need to think about all potential scenarios in my application before relying on that though.

I did some digging into the code and found that changing lines in: [src/MQTTClient.c](https://github.com/eclipse/paho.mqtt.c/blob/26c6c990363e7bffc96f31790a18604e4185ce15/src/MQTTClient.c#L2253) and [MQTTAsync.c](https://github.com/eclipse/paho.mqtt.c/blob/26c6c990363e7bffc96f31790a18604e4185ce15/src/MQTTAsync.c#L3497) to 

` if (difftime(now, last) >= retryLoopInterval) ` i.e replacing `>` with `>=` seems to fix the issue.

@icraggs I am not familiar enough with this code base to determine if the above is just a quick hack or a viable solution to this problem - maybe you can advise?

EDIT: After conducting longer tests with my changes - the client still times out it just takes longer to do so. I.e a series of PINGREQs and PINGRESPs are exchanged before time out, rather than timing out immediately.

**Comment by icraggs** [comment]
difftime() returns a result in seconds, and the lowest retryLoopInterval can go is 1, so changing > to >= seems like the right thing to do, and of course is simple :-).   It can be added to the next release.

**Comment by fpagliughi** [comment]
Remember that the keepAlive does not determine how long it will take for a severed connection to be noticed. That is normally the job of the underlying transport. The keepAlive is merely a failsafe in case the transport gets jammed up.

A low keepAlive puts a burden on both the client and the server, so there's a trade-off to be made. I wouldn't be terribly worried if the C client couldn't dial it all the way down to 1sec, but if not, the lower limit (2?, 3?, 5sec?) should be documented, and call to connect() should fail gracefully if it's a value that isn't supported.

That all said, I'm guessing that the MQTT spec implies that the value can be 1sec. So it would be good if the library conformed to the spec. But I wouldn't rush to do something right away that puts a drag on the performance of the 99.9% of apps that don't need a value that low.
