### ISSUE TITLE
Non-valid protocol in the host address leads to segmentation fault

### ISSUE THREAD

**Issue by AntoniFC** [eclipse-paho/paho.mqtt.c#593]
If the host address has a non-valid protocol name, e.g. tpc instead of tcp, a segmentation fault appears and the program stops. It would be desirable to indicate a wrong protocol name with an error code instead of a segmentation fault. 

Some simple code that exemplifies the issue. 

`#include "MQTTClient.h"
#include <stdlib.h>
#define ADDRESS     "abc://localhost:1883"   // Deliberately wrong protocol name
#define CLIENTID    "ExampleClientPub"

int main()
{
    MQTTClient client;
    MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
    int rc;

    MQTTClient_create(&client, ADDRESS, CLIENTID,MQTTCLIENT_PERSISTENCE_NONE, NULL);
    conn_opts.keepAliveInterval = 20;
    conn_opts.cleansession = 1;

    if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to connect, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }
    return 0;
}`

**Comment by icraggs** [comment]
Hi.  Did you check the return code from the create() call?  If you are using version 1.3 then you should get the BAD_PROTOCOL return code.

**Comment by AntoniFC** [comment]
Thank you very much. The create() does return the BAD_PROTOCOL exception. 
For the paho.mqtt.cpp client though the verification of the return code was not implemented in v.1.0.0, which was addressed in the following issue: 
https://github.com/eclipse/paho.mqtt.cpp/pull/149

and has been corrected in the recent v.1.0.1.
