### ISSUE TITLE
Compilation on OSX

### ISSUE THREAD

**Issue by zhoub** [eclipse-paho/paho.mqtt.c#595]
Hi !

I'm using OSX and would like to compile it, but seems that the latest build is not happy with the OSX's C API.

```
/Users/zb/Development/paho-mqtt-c-repo/src/Thread.c:412:2: warning: implicit declaration of function 'clock_gettime' is
      invalid in C99 [-Wimplicit-function-declaration]
        clock_gettime(CLOCK_REALTIME, &cond_timeout);
        ^
/Users/zb/Development/paho-mqtt-c-repo/src/Thread.c:412:16: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, &cond_timeout);
```

Thanks.

**Comment by icraggs** [comment]
I don't know how you are trying to build the library, or which version you are using, but that part of the code is not applicable to OS/X.   The Makefile and CMake builds work on OS/X for me.  The CMake builds are used on Travis all the time.

**Comment by zhoub** [comment]
The error comes from the CMake generated project, not Makefile.

This could be reproduced both from master branch and tag v1.3.0.

Thanks.

**Comment by icraggs** [comment]
Running these commands:

. travis_macos_vars (sets a couple of environment variables which to mimic Travis environment)
./travis-build.sh (will try to run tests too, but you can stop it then, with the binaries already built).

works for me.
