### ISSUE TITLE
Hardcoded OPENSSL_SEARCH_PATH on macOS

### ISSUE THREAD

**Issue by piotrwach** [eclipse-paho/paho.mqtt.c#602]
`cmake -DOPENSSL_SEARCH_PATH ...` is a way to tell the build system where to look for OpenSSL library, however on macOS this variable is always hardcoded to `/usr/local/opt/openssl`. 

To solve this, CMake should first check if this variable is not set, and only then set a default value.

**Comment by icraggs** [comment]
Fixed in the develop branch.
