### ISSUE TITLE
Connect fails - semaphore posted too many times

### ISSUE THREAD

**Issue by tucic** [eclipse-paho/paho.mqtt.c#604]
Hello Ian,

I am running some tests on v1.3.0 and it seems that there is an issue with reconnection.

It is reproduced on a test setup where both client and broker are running on the same host.
Once the broker is stopped, first reconnection increased connect semaphore to very hight number (in my case to 116). Next N/2 (58) retires failed, but N/2 +1 succeeded. In all of them broker reported: "ssl handshake failure".

I could not reproduce the same on v1.2.0.
Is it possible that this issue is introduced in: https://github.com/eclipse/paho.mqtt.c/commit/3b23859ef56f15a4dcc65c87f39fea00135824d1?

You can find output summary below.
Full logs are also attached: [paho.log](https://github.com/eclipse/paho.mqtt.c/files/2764734/paho.log), [mosquitto.log](https://github.com/eclipse/paho.mqtt.c/files/2764735/mosquitto.log).

Client: Paho C 1.3.0
Broker: Mosquitto 1.5.3.

Test output summary:
1. Mosquitto is up and running,
2. Paho SSL client connects:
> 16.01.19 14:55:21.078 I [Paho] 0: SSL connect:SSL negotiation finished successfully
> 16.01.19 14:55:21.078 D [Paho] 0: Posting connect semaphore for SSL client g-150000000015 rc 1
> 16.01.19 14:55:21.078 I [Paho] 0: sent 0 256 buflen 5
> 16.01.19 14:55:21.078 I [Paho] 0: 5 g-150000000015 -> CONNECT cleansession: 1 (0)
> 16.01.19 14:55:21.079 I [Paho] 0: received 0 256 buflen 5
> 16.01.19 14:55:21.079 D [Paho] 0: Posting connack semaphore for client g-150000000015
> 16.01.19 14:55:21.088 I [Paho] 0: 5 g-150000000015 <- CONNACK rc: 0

3. Mosquitto process terminates and client reports connection lost:
> 16.01.19 14:55:24.239 D [Paho] 0: Calling connectionLost for client g-150000000015

4. External reconnection mechanism is triggered, and first connect resulted in multiple semaphore posts:
> 16.01.19 14:56:23.805 D [Paho] 8: Connecting to serverURI 192.168.1.109:8885 with MQTT version 4
> 16.01.19 14:56:23.805 D [Paho] 8: New socket 5 for 192.168.1.109:8885, port 8885
> 16.01.19 14:56:23.805 D [Paho] 8: Connect pending
> 16.01.19 14:56:23.805 D [Paho] 0: Posting connect semaphore for client g-150000000015 rc 111
> 16.01.19 14:56:23.806 D [Paho] 0: Posting connect semaphore for client g-150000000015 rc 0
> 16.01.19 14:56:23.806 D [Paho] 0: Posting connect semaphore for client g-150000000015 rc 0
> 16.01.19 14:56:23.806 D [Paho] 0: Posting connect semaphore for client g-150000000015 rc 0
> ...
> 16.01.19 14:56:23.817 D [Paho] 8: SSLSocket error (5) in SSL_connect for socket 5 rc -1 errno 32 Broken pipe

5. Mosquitto is started again,
6. Following reconnections fail:
16.01.19 14:56:29.400 D [Paho] 8: Connecting to serverURI 192.168.1.109:8885 with MQTT version 4
16.01.19 14:56:29.400 D [Paho] 8: New socket 5 for 192.168.1.109:8885, port 8885
16.01.19 14:56:29.400 D [Paho] 8: Connect pending
...
16.01.19 14:56:29.403 D [Paho] 8: Removed socket 5
...
...
16.01.19 15:03:50.204 D [Paho] 8: Connecting to serverURI 192.168.1.109:8885 with MQTT version 4
16.01.19 15:03:50.204 D [Paho] 8: New socket 5 for 192.168.1.109:8885, port 8885
16.01.19 15:03:50.204 D [Paho] 8: Connect pending
...
16.01.19 15:03:50.206 D [Paho] 8: Removed socket 5

7. Until counter on connection semaphore dropped to 0:
> 16.01.19 15:03:56.298 D [Paho] 0: Posting connect semaphore for SSL client g-150000000015 rc 1
> 16.01.19 15:03:56.306 I [Paho] 8: sent 0 256 buflen 5
> 16.01.19 15:03:56.306 I [Paho] 8: 5 g-150000000015 -> CONNECT cleansession: 1 (0)
> 16.01.19 15:03:56.306 I [Paho] 0: received 0 256 buflen 5
> 16.01.19 15:03:56.306 D [Paho] 0: Posting connack semaphore for client g-150000000015
> 16.01.19 15:03:56.316 I [Paho] 8: 5 g-150000000015 <- CONNACK rc: 0

**Comment by icraggs** [comment]
How did you stop the broker?   A normal shutdown or kill?   Does it happen every time (so it would be easy to reproduce in a test)?

**Comment by tucic** [comment]
Broker is stopped gracefully, but stopping broker is not what caused the problem.
It is reproduced with broker being down on client's start. I don't have logs, but output was the same (without first part, starting from step 4). If needed, I will repeat this.
Notice that host is available on the network, while broker is down.
Yes, it is easy to reproduce. Issue is permanent.

Would conditional variable be a better choice, instead of connect semaphore?

**Comment by icraggs** [comment]
So far, I've not been able to reproduce this, on MacOS and Ubuntu.  Do you have a test program which shows the problem?

A full Paho client trace might provide more information.

**Comment by tucic** [comment]
And this is output from version 1.2.0 (working):

```
tucic@rtrkn356-lin ~/p/b/test> ./test_issue604 --test-no 1 --connection ssl://192.168.1.109:8885 --client_id "cli/test" --username "cli/test" --password "test" --trust_store ssl/cloud/stratus_ca.crt

Setting connection to ssl://192.168.1.109:8885
20190306 152219.902 Starting test 1 - reconnect on connectionLost
=========================================================
                   Trace Output
Product name: Paho Synchronous MQTT C Client Library
Version: 1.2.0
Build level: 2019-03-06T14:21:59Z
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
OpenSSL flags: compiler: cc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHAS
OpenSSL build timestamp: built on: reproducible build, date unspecified
OpenSSL platform: platform: debian-amd64
OpenSSL directory: OPENSSLDIR: "/usr/lib/ssl"
/proc/version: Linux version 4.15.0-45-generic (buildd@lcy01-amd64-027) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019

=========================================================
20190306 152220.046 Waiting connection lost (shutdown broker)
Callback: connection lost
20190306 152226.047 Sleeping 10 s ...
20190306 152236.047 Trying first re-connect (broker should be down) ...
20190306 152236.158 Connect failed, rc=-1
20190306 152237.158 Sleeping 10 s ...
20190306 152247.158 Trying to connect (restart broker) (2) ...
20190306 152248.186 Connected.
20190306 152249.188 passed: test test1. 6 tests run, 0 failures.

20190306 152249.188 verdict pass
```

**Comment by icraggs** [comment]
Ok, thanks.  That does it.  The part I was missing was the failed connect before attempting to reconnect with the broker up.  Also, seems to work on MacOS.

**Comment by icraggs** [comment]
So, after a bit of experimentation, for me, commenting out the line 

#define USE_TRYWAIT 

in Thread.c will resolve this issue.  You could try that, if you have the means.  I have a fix that I'm testing at the moment.

**Comment by icraggs** [comment]
Removing #define USE_TRYWAIT is the best solution - I only added the alternative because sem_timedwait() didn't work on one embedded platform.

**Comment by tucic** [comment]
I can confirm that it resolves the issue. Test passes.
Thank you!

**Comment by tucic** [comment]
Even when _#define USE_TRYWAIT_ is  removed from Thread.c:234, I can reproduce the issue. It reconnects much faster (after 1-2-3 retries), but still fails on connect after broker is up.

Can you submit a change, just to be sure that we are on the same trace?

**Comment by icraggs** [comment]
I will, once I have access to my Linux machine again, which will be later today or tomorrow.

**Comment by icraggs** [comment]
I think the second commit is the *real* fix here, but the first commit does no harm either.

**Comment by tucic** [comment]
I agree, state change resolves the issue. Thank you!
