### ISSUE TITLE
How to perform an MQTT Async Subscribe with topic that isn't a global variable?

### ISSUE THREAD

**Issue by jamie-chapman** [eclipse-paho/paho.mqtt.c#605]
See example: [https://github.com/eclipse/paho.mqtt.c/blob/master/src/samples/MQTTAsync_subscribe.c] where a topic is supplied to OnConnect by referencing a global variable, is there a way to provide a topic by passing an argument?

**Comment by icraggs** [comment]
There are various calls to subscribe in the test suites, which might give you an idea.  For example:

https://github.com/eclipse/paho.mqtt.c/blob/master/test/test4.c

**Comment by jamie-chapman** [comment]
Looking into them at the moment, we will post a nice solution here if we find one.
