### ISSUE TITLE
MQTTAsync speed with QoS1

### ISSUE THREAD

**Issue by Mohren** [eclipse-paho/paho.mqtt.c#606]
In my application I want to publish MQTT messages with QoS 1 with a frequency of a few kHz. Therefore I used the functions from MQTTAsync.h. 

Mainly I just run "MQTTAsync_sendMessage" and change the payload all the time (timestamp & data) in my main loop.
I don't really do something actively with the callbacks (MQTTAsync_setCallbacks(client, NULL, connlost, NULL,NULL) ).

Do you have some general advises regarding MQTTAsync.h to improve speed? I haven't found anything helpful in the other issues and as I have seen questions have been asked here before so I hope I am not completely at the wrong place to ask questions. Otherwise please inform me so.

**Comment by icraggs** [comment]
QoS 1 waits for an ack from the server, and there is a maximum of 64k slots for messages.  You could try turning off message persistence to see what difference that makes, and using QoS 0, to see what effect that has, even if you don't want to use it.
