### ISSUE TITLE
MQTT Client 1.3.0 is getting crashed after throtling the network on wifi interface using tc command.

### ISSUE THREAD

**Issue by NSSubrahmanyam** [eclipse-paho/paho.mqtt.c#607]
I my IOT Gateway, i am using paho 1.3.0 version. I throttled the GW network bandwidth on wifi interface with below command.  Application got crashed, gdb backtrace  below.
sudo tc qdisc add dev wlan0 root tbf rate 10kbit burst 2kb latency 470ms peakrate 20kbit minburst 1540.

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `/home/clf/ble_cloudleaf_app_xxaa_s120_xxaa.out'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xb6dd9a0e in MQTTProtocol_checkPendingWrites () at src/MQTTClient.c:2742
2742	src/MQTTClient.c: No such file or directory.
(gdb) bt
#0  0xb6dd9a0e in MQTTProtocol_checkPendingWrites () at src/MQTTClient.c:2742
#1  MQTTClient_writeComplete (socket=24, rc=<optimized out>) at src/MQTTClient.c:2764
#2  0xb6de2eac in Socket_continueWrites (pwset=pwset@entry=0xaf8fed00) at src/Socket.c:947
#3  0xb6de2fd2 in Socket_getReadySocket (more_work=more_work@entry=0, tp=tp@entry=0xaf8fedb0, mutex=0xb6df37ac <socket_mutex_store>) at src/Socket.c:272
#4  0xb6dd9b38 in MQTTClient_cycle (sock=sock@entry=0xaf8fedfc, timeout=timeout@entry=1000, rc=rc@entry=0xaf8fedf8) at src/MQTTClient.c:2284
#5  0xb6ddbee6 in MQTTClient_run (n=<optimized out>) at src/MQTTClient.c:753
#6  0xb6f33fa0 in start_thread (arg=0xaf8ff430) at pthread_create.c:314
#7  0xb6bfcd9c in ?? () at ../ports/sysdeps/unix/sysv/linux/arm/nptl/../clone.S:92 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

**Comment by icraggs** [comment]
A client library trace, as outlined in the readme, would be useful in this case.

**Comment by icraggs** [comment]
There are also several fixes in the later releases of the library, now 1.3.2.  You can try that.
