### ISSUE TITLE
Incoming persisted messages delivery attempted before messageArrived callback set

### ISSUE THREAD

**Issue by rbaez1** [eclipse-paho/paho.mqtt.c#610]
I noticed that if the persistence folder has messages stored and I create the client (MQTTClient_create) and set MQTTCLIENT_PERSISTENCE_DEFAULT, it tries to process the messages(using MQTTClient_run) before the callbacks are set(MQTTClient_setCallbacks). At that point it tries to invoke the callbacks (onMessageArrived using a null context) and its are null. This produces the library to crash and my whole application.
I am using Windows 10, paho-mqtt3cs.lib(with TLS), VS2015(C++) and mosquitto broker.

**Comment by icraggs** [comment]
Interesting, yes I can see this is a problem.  Not attempting to deliver messages until the message arrived callback is set, is the obvious solution.
