### ISSUE TITLE
Cannot connect to Amaton AWS IoT

### ISSUE THREAD

**Issue by janschatz** [eclipse-paho/paho.mqtt.c#615]
I want to connect to Amazon AWS IoT, but I have problems with the client certificate.
Amazon provides a client certificate file, a private key file and a CA certificate file (all in PEM format). There seems to exist an intermediate certificate. But they don't provide it.
I put the client certificate file's path in `MQTTClient_SSLOptions::keyStore` and the private key file's path in `MQTTClient_SSLOptions::privateKey`. I also tried adding the CA cerificate file's path in `MQTTClient_SSLOptions::trustStore`.
The result is that Paho sends an empty client certificate to the server.
What could be the reason for this? The MQTTClient_SSLOptions::ssl_error_cb is not being called.

**Comment by icraggs** [comment]
That sounds like the right approach.

How do you know that the Paho client sends an empty certificate?  You have a message from AWS?

A protocol level trace of the client will show the OpenSSL exchange.  It might shed some light, although it tends to be a bit cryptic.

**Comment by janschatz** [comment]
Thanks for the quick reply.

I saw the empty certificate on Wireshark. See packet no. 8 in the following capture file: [aws.pcap.gz](https://github.com/eclipse/paho.mqtt.c/files/2870064/aws.pcap.gz)

The certificate length is 0.

![aws pcap](https://user-images.githubusercontent.com/13834416/52872005-b0cc5480-314b-11e9-8d6c-872da894699d.png)

This looks different when I connect using another client.

**Comment by jumoog** [comment]
that should work:

```
sslOpts_.keyStore = "pem.crt";
sslOpts_.privateKey = "private.pem.key";
sslOpts_.privateKeyPassword = "";
```

**Comment by janschatz** [comment]
Has anone tried that with certificates from AWS? Could it be a problem that they don't contain a complete certificate chain? Does Paho or OpenSSL try to verify the certificate?

**Comment by janschatz** [comment]
I played around a bit more and am now getting a message via `ssl_error_cb`:

> 20055456:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:ssl/record/rec_layer_s3.c:1528:SSL alert number 42

**Comment by icraggs** [comment]
A quick search on StackOverflow suggests that alert number 42 means that the server expects client authentication by certificate and that failed, which ties in with the other information you have given.

From the information you have given, the problem is not with the AWS server certificates, but with the certificate for the device.

**Comment by janschatz** [comment]
Yes, the client sends an empty certificate list. So OpenSSL thinks that the client certificate I provided doesn't match the certificate request from the server.

I can successfully connect from my target using openssl's s_client functionality like this:
`openssl s_client -connect a309nkyxj0c15f-ats.iot.us-west-2.amazonaws.com:8883 -cert client.pem -key key.pem`

So it must be something in my configuration or in the way Paho uses OpenSSL.

**Comment by JuergenKosel** [comment]
Hello,

the AWS broker demands some special settings. For example the clean session flag must be set on connection establishment.
For one of our products, which uses paho.mqtt.c library, we have a howto which describes how to connect to AWS: https://data-intelligence.softing.com/fileadmin/media/products/applications/dataFEED_AWS_C_EN_181201_101_L.pdf

**Comment by icraggs** [comment]
Thank you @JuergenKosel !

@janschatz A full listing of the OpenSSL trace might shed some more light.

**Comment by janschatz** [comment]
Thank you @JuergenKosel. Unfortunately I am still far away from any MQTT-sepcific stuff. But I think AWS IoT support [persistent connections](https://docs.aws.amazon.com/iot/latest/developerguide/mqtt-persistent-sessions.html) now.

@icraggs, how can I get this OpenSSL trace? You don't mean a Wireshark capture, do you?

**Comment by icraggs** [comment]
@janschatz take a Paho client trace (described in the readme), with the level set to TRACE_PROTOCOL.  That includes MQTT exchanges and the OpenSSL trace.

**Comment by janschatz** [comment]
After spending two days debugging the internals of OpenSSL, I found out that in fact I didn't set `sslOpts_.keyStore` corretctly. My code looks like this:

    sslOpts_.keyStore = doSomeCheck(PATH) ? PATH : NULL;

And `doSomeCheck` didn't behave as expected. 

Sorry for bothering you!

**Comment by icraggs** [comment]
Good news! - I'm just happy it's working for you.  Thanks for letting us know.
