### ISSUE TITLE
cannot stat 'build/output/doc/MQTTClient/man/man3/MQTTClient.h.3': No such file or directory

### ISSUE THREAD

**Issue by ngoc233** [eclipse-paho/paho.mqtt.c#616]
**I have an error when i run " sudo make install ". Could someone help me with the solution?. Please.**

install -m 644 doc/man/man1/paho_cs_sub.1 /usr/local/share/man/man1
install -m 644 build/output/doc/MQTTClient/man/man3/MQTTClient.h.3 /usr/local/share/man/man3
install: cannot stat 'build/output/doc/MQTTClient/man/man3/MQTTClient.h.3': No such file or directory
Makefile:273: recipe for target 'install' failed
make: [install] Error 1 (ignored)
install -m 644 build/output/doc/MQTTAsync/man/man3/MQTTAsync.h.3 /usr/local/share/man/man3
install: cannot stat 'build/output/doc/MQTTAsync/man/man3/MQTTAsync.h.3': No such file or directory
Makefile:273: recipe for target 'install' failed
make: [install] Error 1 (ignored)

**Comment by edanla** [comment]
I have the same problem

**Comment by edanla** [comment]
I don't know what the problem is, but a different version is ok

**Comment by ibrainventures** [comment]
following steps helped with my installatio (also had the same issue): (ubuntu 18.04.2 / ARM64)
sudo apt install doxygen
sudo make html
make && sudo make install

**Comment by miracoli** [comment]
Same problem here. Solution from @ibrainventures worked.

**Comment by hanwin** [comment]
I had to add:
```
sudo make clean
sudo rm /usr/local/lib/libpaho-mqtt3*
make && sudo make install
```

**Comment by icraggs** [comment]
A fix has been added to not try to install the man pages if they have not been built.

**Comment by saadmajid95** [comment]
I downloaded the latest git and still facing the same problem. Now going with @ibrainventures's solution
