### ISSUE TITLE
“make install” failed on man pages

### ISSUE THREAD

**Issue by edanla** [eclipse-paho/paho.mqtt.c#617]
install -m 644 src/MQTTAsync.h /usr/local/include
install -m 644 src/MQTTClient.h /usr/local/include
install -m 644 src/MQTTClientPersistence.h /usr/local/include
install -m 644 src/MQTTProperties.h /usr/local/include
install -m 644 src/MQTTReasonCodes.h /usr/local/include
install -m 644 src/MQTTSubscribeOpts.h /usr/local/include	
install -m 644 doc/man/man1/paho_c_pub.1 /usr/local/share/man/man1
install -m 644 doc/man/man1/paho_c_sub.1 /usr/local/share/man/man1
install -m 644 doc/man/man1/paho_cs_pub.1 /usr/local/share/man/man1
install -m 644 doc/man/man1/paho_cs_sub.1 /usr/local/share/man/man1
install -m 644 build/output/doc/MQTTClient/man/man3/MQTTClient.h.3 /usr/local/share/man/man3
install: 无法获取"build/output/doc/MQTTClient/man/man3/MQTTClient.h.3" 的文件状态(stat): 没有那个文件或目录
make: [install] 错误 1 (忽略)
install -m 644 build/output/doc/MQTTAsync/man/man3/MQTTAsync.h.3 /usr/local/share/man/man3
install: 无法获取"build/output/doc/MQTTAsync/man/man3/MQTTAsync.h.3" 的文件状态(stat): 没有那个文件或目录
make: [install] 错误 1 (忽略)

**Comment by mgtaboada** [comment]
I think I had the same issue as you did. I found a workaround by commenting these two lines in the `Makefile`:
```bash
	- $(INSTALL_DATA) ${blddir}/doc/MQTTClient/man/man3/MQTTClient.h.3 $(DESTDIR)${man3dir}
	- $(INSTALL_DATA) ${blddir}/doc/MQTTAsync/man/man3/MQTTAsync.h.3 $(DESTDIR)${man3dir}
```

**Comment by ibrainventures** [comment]
following steps helped with my installatio (also had the same issue): (ubuntu 18.04.2 / ARM64)
sudo apt install doxygen
sudo make html
make && sudo make install

**Comment by edanla** [comment]
Thank you

**Comment by icraggs** [comment]
Any help with what the error messages say, in English?  Thanks.

**Comment by icraggs** [comment]
This has now been fixed in the develop branch.
