### ISSUE TITLE
Access violation during reconnect (lib 1.3.0)

### ISSUE THREAD

**Issue by andnig** [eclipse-paho/paho.mqtt.c#620]
Hi dear MQTT friends,
I'm using your (amazing) library with a .NET C# project. Basically, I did a wrapper around your MqttAsync-methods. I did not experience any problems for ~1year until commit fcef9b5dd5b3f5c2eb137dfe57193d296415f0cf

**Problem**: Access Violation after any reconnect attempt (automaticReconnect enabled).
The trace output is as follows: 
`20190303 093304.234 1700 sf/thing/62a7c2ae-5d08-49b7-89ff-64a9cdff1e07 -> CONNECT cleansession: 1 (0)
20190303 093304.351 received 0 256 buflen 5
20190303 093304.383 1700 sf/thing/62a7c2ae-5d08-49b7-89ff-64a9cdff1e07 <- CONNACK rc: 0`

after these lines, my application crashes with Visual Studio telling "Access violation". 

I'm aware, that this kind of behavior might also be related to my .net wrapper, however I would be glad, if someone could have a look at my issue. Maybe you can provide me with some insights, what I'm doing wrong.
Some more details here: 
- OS: Windows 10 x64
- Async
- connectOptions: StructVersion=5, Mqtt 3.1.1, CleanSession = 0, Ssl (StructVersion = 2, EnableServerCertAuth = 1, TLS12, Verify = 0), automaticReconnect = 1
- createOptions: SendWhileDisconnected = 1, StructVersion=0

**Comment by icraggs** [comment]
Can you run under Visual Studio debug and get it to tell you where the access violation occurs?  Taking a MQTT client library trace as described in the readme might also help.

**Comment by andnig** [comment]
Ok, thanks for your reply. I was able to locate the crash location more or less. 
If we compare the Trace output of the library which causes the crash (6b4227d4be30b5c14552eb6b9d5df387e9ac5fb9)

`20190313 191901.864 m->c->connect_state = 4
20190313 191901.864 CONNECT sent, *rc is 0
20190313 191901.864 (9944)   (2)> MQTTAsync_retry:3495
20190313 191901.864 (9944)    (3)> MQTTProtocol_retry:727
20190313 191901.864 (9944)    (3)< MQTTProtocol_retry:746
20190313 191901.864 (9944)   (2)< MQTTAsync_retry:3505
20190313 191901.864 (9944)  (1)< MQTTAsync_cycle:3810 (0)
20190313 191901.864 (9944)  (1)> MQTTAsync_completeConnection:2016
20190313 191901.864 2376 hallo/thing/db250287-9106-486f-87d9-39555f8d23dd <- CONNACK rc: 0
20190313 191901.864 (9944)   (2)> Thread_post_sem:314
20190313 191901.864 (9944)   (2)< Thread_post_sem:325 (0)
20190313 191901.864 (23476)  (1)< Thread_wait_sem:277 (0)
20190313 191901.864 (9944)  (1)< MQTTAsync_completeConnection:2054 (0)
20190313 191901.864 Calling connect success for client hallo/thing/db250287-9106-486f-87d9-39555f8d23dd`
(It crashes directly after "Calling connect success for"..., please see https://github.com/eclipse/paho.mqtt.c/blob/6b4227d4be30b5c14552eb6b9d5df387e9ac5fb9/src/MQTTAsync.c#L2155 line 2155 or line 2168). 

with the Trace output of the library which does not crash (0ca079abdeb90d51d8534c1c7b9b32365bd016d0) 

`20190313 195655.315 m->c->connect_state = 4
20190313 195655.315 CONNECT sent, *rc is 0
20190313 195655.315 (21340)   (2)> MQTTAsync_retry:2923
20190313 195655.315 (21340)    (3)> MQTTProtocol_retry:644
20190313 195655.315 (21340)    (3)< MQTTProtocol_retry:663
20190313 195655.315 (21340)   (2)< MQTTAsync_retry:2933
20190313 195655.315 (21340)  (1)< MQTTAsync_cycle:3189 (0)
20190313 195655.315 (21340)  (1)> MQTTAsync_completeConnection:1789
20190313 195655.315 2768 hallo/thing/db250287-9106-486f-87d9-39555f8d23dd <- CONNACK rc: 0
20190313 195655.315 (21340)   (2)> Thread_post_sem:294
20190313 195655.315 (21340)   (2)< Thread_post_sem:305 (0)
20190313 195655.315 (13364)  (1)< Thread_wait_sem:261 (0)
20190313 195655.315 (21340)  (1)< MQTTAsync_completeConnection:1825 (0)
20190313 195655.315 (13364)  (1)> MQTTAsync_checkTimeouts:1520
20190313 195655.315 (21340)  (1)> MQTTAsync_cycle:3080
20190313 195655.315 (13364)  (1)< MQTTAsync_checkTimeouts:1588
20190313 195655.315 (21340)   (2)> Socket_getReadySocket:239
20190313 195655.366 (13364)  (1)> Thread_wait_sem:235
`

we see, that the crash happens directly after logging "Calling connect success for" in MqttAsync.c Line 2155 or line 2168. Furthermore, the version which does not crash, does not even reach this logging call. I was not fully able to figure out, what the problem is, but is it possible, that the if-statement "else if (m->connect.onSuccess5)" is entered accidentially? I'm not initializing the Mqtt5-structs, as I don't use them for now. Maybe I can ask you to investigate a little bit further, as I'm stuck here? Thanks a lot!

**Comment by icraggs** [comment]
It sounds like the problem might actually be in your callback or .Net code.  Running the app under visual studio should enable the exact line of the problem to be shown.
