### ISSUE TITLE
Compiler throws warning for [Wmissing-field-initializer] for MQTTAsync_connectOptions_initializer

### ISSUE THREAD

**Issue by psalvi** [eclipse-paho/paho.mqtt.c#621]
In function ‘MQTTInit’:
 warning: missing initializer for field ‘serverURIcount’ of ‘MQTTAsync_connectOptions {aka struct <anonymous>}’ [-Wmissing-field-initializers]
MQTTAsync_connectOptions opts = MQTTAsync_connectOptions_initializer;
^~~~~~~~~~~~~~~~~~~~~~~~

/usr/include/MQTTAsync.h:646:6: note: ‘serverURIcount’ declared here
int serverURIcount;
     ^~~~~~~~~~~~~~
I am trying to use the the initializer provided in the MQTTAsync.h

**Comment by icraggs** [comment]
This was fixed in the develop branch by PR #601
