### ISSUE TITLE
mqtt test url is not connected？

### ISSUE THREAD

**Issue by Lawlieta** [eclipse-paho/paho.mqtt.c#622]
Hi

I found the mqtt test url "tcp://iot.eclipse.org:1883" not connected in China. 
Has anyone encountered the same problem, can you connect to this url now?

**Comment by icraggs** [comment]
There is some discussion about moving the service, but I don't know what state it's in.  The following bug has the discussion.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=541419
