### ISSUE TITLE
TRACE_MINIMUM log level env val not handled

### ISSUE THREAD

**Issue by tucic** [eclipse-paho/paho.mqtt.c#628]
Condition in Log.c:165 checks for TRACE_MEDIUM, instead of TRACE_MINIMUM. In this way, MQTT_C_CLIENT_TRACE_LEVEL environment variable with value TRACE_MINIMUM will be ignored.

**Comment by tucic** [comment]
Fix available in pull request https://github.com/eclipse/paho.mqtt.c/pull/629.

**Comment by icraggs** [comment]
The PR was merged last year.  Thanks.
