### ISSUE TITLE
Debian 7.9 make failed (needs rt lib)

### ISSUE THREAD

**Issue by dontsovcmc** [eclipse-paho/paho.mqtt.c#631]
Debian 7.9 make with custom openssl & options:
```
PAHO_WITH_SSL=TRUE
PAHO_BUILD_STATIC=TRUE
PAHO_ENABLE_TESTING=FALSE
PAHO_ENABLE_CPACK=FALSE
CMAKE_BUILD_TYPE=Release
CMAKE_VERBOSE_MAKEFILE=TRUE
```
failed with error:

`libpaho-mqtt3a.so.1.3.0: undefined reference to `clock_gettime'`

Solved by adding rt library to 'src/CMakeLists.txt':
```
IF(CMAKE_SYSTEM_NAME MATCHES "Linux")
        SET(LIBS_SYSTEM c dl pthread rt)
ELSEIF (CMAKE_SYSTEM_NAME MATCHES "FreeBSD")
... 
```

**Comment by pukguy** [comment]
Hi @dontsovcmc ! I tried your solution but still can't solve it.
```
[ 97%] Linking C executable thread
CMakeFiles/thread.dir/__/src/Thread.c.o: In function `Thread_wait_cond':
Thread.c:(.text+0x354): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make[2]: *** [test/thread] Error 1
make[1]: *** [test/CMakeFiles/thread.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by icraggs** [comment]
I note that the Debian man page says _Link with -lrt (only for glibc versions before 2.17)_  I hope that naively linking with the rt library doesn't cause any regressions.

**Comment by jgladen** [comment]
> Hi @dontsovcmc ! I tried your solution but still can't solve it.
> 
> ```
> [ 97%] Linking C executable thread
> CMakeFiles/thread.dir/__/src/Thread.c.o: In function `Thread_wait_cond':
> Thread.c:(.text+0x354): undefined reference to `clock_gettime'
> collect2: error: ld returned 1 exit status
> make[2]: *** [test/thread] Error 1
> make[1]: *** [test/CMakeFiles/thread.dir/all] Error 2
> make: *** [all] Error 2
> ```

I had the same issue the looks like the same change needs to be applied to the ```test/CMakeLists.txt``` file as well

```patch
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
 index 0e4c6a8..9018785 100644
 --- a/test/CMakeLists.txt
 +++ b/test/CMakeLists.txt
 @@ -13,7 +13,7 @@ IF (WIN32)
         SET(LIBS_SYSTEM ws2_32)
  ELSEIF (UNIX)
         IF(CMAKE_SYSTEM_NAME MATCHES "Linux")
 -           SET(LIBS_SYSTEM c dl pthread)
 +         SET(LIBS_SYSTEM c dl pthread rt)
         ELSEIF (CMAKE_SYSTEM_NAME MATCHES "FreeBSD")
                 SET(LIBS_SYSTEM compat pthread)
         ELSE()
```
