### ISSUE TITLE
how to set two root.cer files when connect mosquito server?

### ISSUE THREAD

**Issue by Peter756729890** [eclipse-paho/paho.mqtt.c#632]
As I could connect and commucate with the mosquito server with three files ca file, cert file, key file, or only ca file. but how to used the root.cer files? actually i could connect the server with call the api: SSL_CTX_load_verify_locations

**Comment by icraggs** [comment]
Multiple certificate files can be put into one .pem file, or put into the directory pointed to by the CApath option.
