### ISSUE TITLE
Not able to establish MQTT Connection, Gives return code == 150,  EINPROGRESS || EWOULDBLOCK

### ISSUE THREAD

**Issue by ashishsbn** [eclipse-paho/paho.mqtt.c#634]
Hi,

I am trying to establish a MQTT Connection for data transfer from my End device. i have used some printf for function calls.

**Logs on End Device**

MQTT Client Init
MQTT Client ID = MyGW90FD9FFFFE323F4A
MQTT BROKER = tcp://192.168.1.198:1883
MQTTAsync_create Enter ..
Inside MQTTAsync_createWithOptions.. 
Server URI == tcp://192.168.1.198:1883, clientId == MyGW90FD9FFFFE323F4A
SocketBuffer_initialize Enter ... 
SocketBuffer_newDefQ ENter ... 
Socket_outInitialize .. 
Socket_setWriteCompleteCallback Enter ... 
Socket_setWriteCompleteCallback ..MQTTPersistence_create success..
MQTTAsync_createWithOptions Exiting ..
HA Gateweay EUI64 = 90FD9FFFFE323F4A
Found 0 files

EMBER_NETWORK_UP 0x0000
Bootload state: Random Delay before start
Delaying 194 seconds before starting OTA client
144 2
MQTT not connected, message not sent: gw/90FD9FFFFE323F4A/settings - {"ncpStackVersion":"6.2.3-204","networkUp":true,"networkPanId":"0xD16C","radioTxPower":32,"radioChannel":11}
MQTT not connected, message not sent: gw/90FD9FFFFE323F4A/relays - {"relays":[]}
MQTT not connected, message not sent: gw/90FD9FFFFE323F4A/devices - {"devices":[]}
Attempting to reconnect to broker
MQTTAsync_addCommand Enter ... 
MQTTAsync_processCommand Enter ... 
current command == (null)
serverURI ONE== 192.168.1.198:1883
MQTTProtocol_connect Enter ... ip Address = 192.168.1.198:1883 
MQTTProtocol_addressPort Enter, uri = 192.168.1.198:1883, port = 2008182348
Socket_new Enter, addr = 192.168.1.198, port = 1883, sock = 7947644Socket_addSocket Enter ... 
Socket_setnonblocking Enter  ... 
Socket_error Enter ...
 Socket_new == 150
 EINPROGRESS || EWOULDBLOCK
MQTTProtocol_connect Exit 
Socket_getReadySocket Enter ... 
Inside MQTTAsync_checkConn..
Socket_close Enter ... 
Socket_close_only Enter ... 
Socket_error Enter ...
 MQTTAsync_addCommand Enter ... 
Socket_getReadySocket Enter ... 
MQTTAsync_processCommand Enter ... 
current command == (null)
serverURI ONE== 192.168.1.198:1883
MQTTProtocol_connect Enter ... ip Address = 192.168.1.198:1883 
MQTTProtocol_addressPort Enter, uri = 192.168.1.198:1883, port = 2008182348
Socket_new Enter, addr = 192.168.1.198, port = 1883, sock = 7947644Socket_addSocket Enter ... 
Socket_setnonblocking Enter  ... 
Socket_error Enter ...
 Socket_new == 150
 EINPROGRESS || EWOULDBLOCK
MQTTProtocol_connect Exit 
Socket_getReadySocket Enter ... 
Inside MQTTAsync_checkConn..
Socket_close Enter ... 
Socket_close_only Enter ... 
Socket_error Enter ...
 MQTTAsync_connect failed, returned response = -1
MQTTAsync_startConnectRetry Enter.. 
Socket_getReadySocket Enter ... 
Socket_getReadySocket Enter ... 
Attempting to reconnect to broker
MQTTAsync_addCommand Enter ... 
MQTTAsync_processCommand Enter ... 
current command == (null)
serverURI ONE== 192.168.1.198:1883
MQTTProtocol_connect Enter ... ip Address = 192.168.1.198:1883 
MQTTProtocol_addressPort Enter, uri = 192.168.1.198:1883, port = 2008182348
Socket_new Enter, addr = 192.168.1.198, port = 1883, sock = 7947644Socket_addSocket Enter ... 
Socket_setnonblocking Enter  ... 
Socket_error Enter ...
 Socket_new == 150
 EINPROGRESS || EWOULDBLOCK
MQTTProtocol_connect Exit 
Socket_getReadySocket Enter ... 
Socket_getReadySocket Enter ... 
Socket_getch Enter ... 
Socket_error Enter ...
 Inside MQTTAsync_checkConn..
Socket_close Enter ... 
Socket_close_only Enter ... 
Socket_error Enter ...
 MQTTAsync_addCommand Enter ... 
MQTTAsync_processCommand Enter ... 
current command == (null)
serverURI ONE== 192.168.1.198:1883
MQTTProtocol_connect Enter ... ip Address = 192.168.1.198:1883 
MQTTProtocol_addressPort Enter, uri = 192.168.1.198:1883, port = 2008182348
Socket_new Enter, addr = 192.168.1.198, port = 1883, sock = 7947644Socket_addSocket Enter ... 
Socket_setnonblocking Enter  ... 
Socket_error Enter ...
 Socket_new == 150
 EINPROGRESS || EWOULDBLOCK
MQTTProtocol_connect Exit 
Socket_close Enter ... 
Socket_close_only Enter ... 
Socket_error Enter ...
Socket_getReadySocket Enter ... 
Socket_getReadySocket Enter ... 

**Logs on Broker Machine**

ashish@Gladiator:~$ mosquitto -v
1553776595: mosquitto version 1.4.8 (build date Wed, 13 Feb 2019 00:27:01 +0000) starting
1553776595: Using default config.
1553776595: Opening ipv4 listen socket on port 1883.
1553776595: Opening ipv6 listen socket on port 1883.
1553776603: New connection from 192.168.1.199 on port 1883.
1553776603: Socket error on client <unknown>, disconnecting.
1553776603: New connection from 192.168.1.199 on port 1883.
1553776603: Socket error on client <unknown>, disconnecting.
1553776604: New connection from 192.168.1.199 on port 1883.
1553776604: Socket error on client <unknown>, disconnecting.
1553776604: New connection from 192.168.1.199 on port 1883.
1553776604: Socket error on client <unknown>, disconnecting.
1553776605: New connection from 192.168.1.199 on port 1883.
1553776605: Socket error on client <unknown>, disconnecting.
1553776605: New connection from 192.168.1.199 on port 1883.
1553776605: Socket error on client <unknown>, disconnecting.

Any help with this would be highly useful

Thanks
Ashish S

**Comment by icraggs** [comment]
Taking a debug trace, as described in the readme, might give more information.

**Comment by ashishsbn** [comment]
Hi icraggs,

I was able to establish a connection but still it is taking time to connect.
Sometimes 20 seconds and sometimes more than 1.5 minutes.

**Comment by icraggs** [comment]
Would need a trace to see what might be up.
