### ISSUE TITLE
Fails to connect with OpenSSL 1.1.1b

### ISSUE THREAD

**Issue by Kemp-J** [eclipse-paho/paho.mqtt.c#635]
**Summary**

I did a build against 1.1.1b of OpenSSL (your documentation doesn't seem to list supported versions, so I went for latest). It doesn't seem to work though, having an error during the connect. It works if I patch Paho to force a specific TLS version (any supported version).  I subsequently built against 1.0.2r and that does work out-of-the-box.

I have been testing with a Mosquitto broker. No special configuration other than providing certificates.

**Detail**

I have attached several logs showing a relevant portion of the connect. These are taken after the "SSL cipher available" lines. Note that the "SSL certificate verification: X509_V_OK" line is present in all three, including the one that subsequently fails.

Of note is this block of lines in the failed (unpatched 1.1.1b) case:

> 135217.600 SSL state connect:SSL negotiation finished successfully:TLS_AES_256_GCM_SHA384
> 135217.600 SSL state connect:SSL negotiation finished successfully:TLS_AES_256_GCM_SHA384
> 135217.600 received 772 22 buflen 233
> 135217.600 SSL state connect:SSLv3/TLS read server session ticket:TLS_AES_256_GCM_SHA384
> 135217.601 SSL connect:SSL negotiation finished successfully
> 135217.601 received 0 256 buflen 5
> 135217.601 received 772 257 buflen 1
> 135217.601 SSL state connect:SSL negotiation finished successfully:TLS_AES_256_GCM_SHA384
> 135217.601 SSL state connect:SSL negotiation finished successfully:TLS_AES_256_GCM_SHA384
> 135217.601 received 772 22 buflen 233
> 135217.601 SSL state connect:SSLv3/TLS read server session ticket:TLS_AES_256_GCM_SHA384
> 135217.601 SSL connect:SSL negotiation finished successfully

I found it interesting that several of the lines are repeated (up to four times), and these don't appear in the success cases.

Additionally, the following log lines while attempting to read the CONNACK response show a problem:

> 132751.112 (31152)    (3)> WebSocket_getch:469
> 132751.112 (31152)     (4)> SSLSocket_getch:751
> 132751.112 (31152)      (5)> SocketBuffer_getQueuedChar:203
> 132751.312 index is now 1, headerlen -572662307
> 132751.312 (31152)      (5)< SocketBuffer_getQueuedChar:222 (0)
> 132751.312 (31152)     (4)< SSLSocket_getch:772 (0)

headerlen is reoprted as -572662307, which is 0xFFFFDDDD. The character returned is 0xDD.

As a note, headerlen is unsigned but is being cast to a signed type for printing.

I have found that if I use OpenSSL 1.1.1b and force a specific TLS version with a Paho patch such as the following then the connection succeeds with a log output effectively identical to that when using 1.0.2r. In this case I have set it to TLS 1.2, but 1.1 and 1.0 also work.

```diff
--- paho.mqtt.c-master\src\SSLSocket.c	Wed Sep 12 20:50:37 2018
+++ patches\SSLSocket.c	Thu Mar 28 11:15:58 2019
@@ -521,7 +521,7 @@
 	FUNC_ENTRY;
 	if (net->ctx == NULL)
 	{
-		int sslVersion = MQTT_SSL_VERSION_DEFAULT;
-		if (opts->struct_version >= 1) sslVersion = opts->sslVersion;
+		int sslVersion = MQTT_SSL_VERSION_TLS_1_2;
+		//if (opts->struct_version >= 1) sslVersion = opts->sslVersion;
 /* SSL_OP_NO_TLSv1_1 is defined in ssl.h if the library version supports TLSv1.1.
  * OPENSSL_NO_TLS1 is defined in opensslconf.h or on the compiler command line
```

If I don't force a specific TLS version then the connect fails even though it negotiates a version that works when forced (e.g. TLS 1.2).

**Questions**

- Is this a known issue?
- Is 1.1.1b intended to be a supported OpenSSL version currently?
- If not, are there plans to support it in the next Paho release?

**Logs**

[1.1.0_success.txt](https://github.com/eclipse/paho.mqtt.c/files/3029362/1.1.0_success.txt)
[1.1.1_failure.txt](https://github.com/eclipse/paho.mqtt.c/files/3029363/1.1.1_failure.txt)
[1.1.1_success_(patched).txt](https://github.com/eclipse/paho.mqtt.c/files/3029364/1.1.1_success_.patched.txt)

**Comment by Kemp-J** [comment]
I have now tried with that patch applied and I get the same failure. I confirmed in the debugger that it is executing the new line.

**Comment by icraggs** [comment]
A review is needed of TLS and OpenSSL versions supported, but I haven't had time yet, and I'm now going to be on vacation until the end of April.  I'm open to any suggestions or PRs in the meantime of course.

**Comment by banjaxedben** [comment]
As another data point, we tried Paho with OpenSSL 1.1.1c and we had intermittent problems,
Reverted to 1.0.2q and the problems went away.

Please be aware: OpenSSL 1.0.2 will only be supported until the end of 2019.

**Comment by tbeu** [comment]
See also #718 for the issue with uninitialized `headerlen`.

**Comment by icraggs** [comment]
I've run the CI tests on Ubuntu 18.04 with OpenSSL 1.1.1 and they passed.  It seems basic support for OpenSSL >= 1.1 works.

**Comment by icraggs** [comment]
So I haven't found any issues with using OpenSSL 1.1.1.  Windows and MacOS CI tests use 1.1.1.  I run Linux CI tests locally with 1.1.1 frequently.  I don't get any issue. 

Now when I do this, the broker I use will also be using OpenSSL 1.1.1.  I don't know if there will be any difference if other versions of OpenSSL or other TLS implementations are used on the broker side.  It shouldn't be the case.

**Comment by Kemp-J** [comment]
Apologies for not coming back to this sooner. I've now had a chance to retest with 1.3.2 against OpenSSL 1.1.1g and I can confirm that it is working for me. Thank you for the fix.
