### ISSUE TITLE
Don't remove queued messages when cleaning state

### ISSUE THREAD

**Issue by nlhien** [eclipse-paho/paho.mqtt.c#640]
Hello,

This is more of a question than a bug report.
I am trying to implement the following behavior in Mobile Application: (Paho & Google IOT core)
1. Create a MQTT_Async client with the options: 
`{ PERSISTENCE_DEFAULT, sendWhileDisconnected=true }`
2. Connect with options:
`{cleansession = false, automaticReconnect = true}`
3. When the connection is established, turn off the Wifi & Mobile network.
4. Pubish a message and terminate the mobile application. (the message is stored in local disk)
5. Re-open the application, initiate a new connection and got some logs below:
> [4]: 20190415 210511.061 sent 0 256 buflen 5
> [4]: 20190415 210511.061 5 projects/.../device-1 -> CONNECT cleansession: 0 (0)
> [4]: 20190415 210511.286 received 0 256 buflen 5
> [4]: 20190415 210511.286 5 projects/.../device-1 <- CONNACK rc: 0
> [4]: 20190415 210511.286 **Cleaning session state on connect because sessionPresent is 0**

The cached message is never send to the broker. MsgId is reseted to 0.
When I remove the code MQTTAsync_cleanSession if sessionPresent is 0, then the cached message is successful send to the broker.
Why we need to clean the cached session when sessionPresent is Zero? 

Thanks,

**Comment by icraggs** [comment]
It's reasonable that the client library should do it.

**Comment by icraggs** [comment]
Actually, reading this again.  If there are inflight messages (ones for which an ack has not been received) then these should be removed if session_present = 0, as there is a session state mismatch.  There is a difference with queued up messages that have never been sent, though.  These should not be removed.

**Comment by nlhien** [comment]
Thanks @icraggs
