### ISSUE TITLE
Missing MQTTAsync_disconnectOptions_initializer5 leads to "missing initializer for field" warning

### ISSUE THREAD

**Issue by JGrossholtz** [eclipse-paho/paho.mqtt.c#641]
Using paho-c-mqtt v1.3. I compile my MQTT client application with gcc "-Wmissing-field-initializers" option.

When I want to disconnect my client, I initialize the disconnect options:
`MQTTAsync_disconnectOptions disc_opts = MQTTAsync_disconnectOptions_initializer;`

Unfortunately it leads to a warning:
```
warning: missing initializer for field ‘onSuccess5’ of ‘MQTTAsync_disconnectOptions {aka struct <anonymous>}’ [-Wmissing-field-initializers]
     MQTTAsync_disconnectOptions disc_opts = MQTTAsync_disconnectOptions_initializer;
```

The connect options initializer have a mqttv5 initializer, I don't see why the disconnect option initializer does not have one. 

I will submit a patch for this.

**Comment by icraggs** [comment]
Thanks.  It does have one, but it's missing two fields from the end.

**Comment by JGrossholtz** [comment]
I made a pull request to fix this:
https://github.com/eclipse/paho.mqtt.c/pull/643

**Comment by icraggs** [comment]
PR #643 has been merged.  Thanks.
