### ISSUE TITLE
MQTTAsync periodically errors on sendMessage with MQTTASYNC_OPERATION_INCOMPLETE 

### ISSUE THREAD

**Issue by truedat101** [eclipse-paho/paho.mqtt.c#642]
My first foray into using MQTTAsync, and I have am sending a message out every second with a small amount of data to the same topic.  I periodically get MQTTASYNC_OPERATION_INCOMPLETE .  Aside from the short description in the error message which don't completely enumerate the reasons why an operation would be incomplete, under what circumstances should I expect to see this error?  And how can this be avoided?  I've used the example app for Async as the basis, and just loop every second to send.

**Comment by icraggs** [comment]
This normally means that the connection has been broken, and you connected with cleansession=true, which means that the state of any QoS 1 or 2 messages that are incomplete will be discarded.

I think it's true to say that sending QoS 1 or 2 messages with cleansession=true is pointless.

**Comment by truedat101** [comment]
Thanks for the fast response.  Lots of little dials and knobs in the api I am discovering. 

So in my case, at least, qos = 0 (default), I am scratching my head why I'd be losing a connection with the Async send, as I'm still receiving messages I am subscribed to.  I'll take a look at this cleansession=true setting, if this is or is not my default, and experiment further.  I had not problem using publishMessage (sync) interface as an alternative to the Async send.
