### ISSUE TITLE
Fast transmission error

### ISSUE THREAD

**Issue by tx2rx** [eclipse-paho/paho.mqtt.c#645]
I try to do some fast transmission test, the server pub 100 messages/second. The client recv one message,then pub another message immediately.So the client will recv 100 messages and send 100 messages in one second.  But in my hardware environment ( MT7628 ) ，one minutes later with this transmission, the client will trigger error.

Here is the LOG:
__________
Trace : 5, 20190426 030105.584 Failed to remove heap item at file mqtt/MQTTClient.c line 552
Trace : 5, 20190426 030105.584 Failed to remove heap item at file mqtt/MQTTClient.c line 553
Trace : 5, 20190426 030105.584 Failed to remove heap item at file mqtt/MQTTClient.c line 562

Connection lost
     cause: (null)

**Comment by icraggs** [comment]
Taking a trace, as outlined in the readme, could help.

**Comment by icraggs** [comment]
Need a client lib trace as outlined in the readme.
