### ISSUE TITLE
Time jump into the past WHILE connection is lost, no automatic reconnect

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [eclipse-paho/paho.mqtt.c#647]
If a time jump into the past occures while the connection to the broker was interrupted, reconnect is not attempted.
When connection is lost paho.mqtt.c tries to automatically reconnect periodically. If the time is set to a past point in time, the reconnect attempts stop.
As soon as time is reset to the old time point (present) reconnect attempts resume.
I tested this connecting to a Mosquitto broker and then shutting Mosquitto down.

**Comment by D-r-P-3-p-p-3-r** [comment]
It seems the problem stems from this:
https://github.com/eclipse/paho.mqtt.c/issues/284#issuecomment-414721523

> I had to remove the use of CLOCK_MONOTONIC from Thread_wait_cond() as well, as it didn't work on some platforms. Same logic as for Thread_wait_sem(): the waits are not long, and repeated frequently, so not really affected by system clock changes.

The behavior should be changed on platforms that _do_ support CLOCK_MONOTONIC to make the library as robust as possible.
E.g. this is possible under Linux which probably accounts for quite some embedded platform use cases.

See also
https://stackoverflow.com/questions/14248033/clock-monotonic-and-pthread-mutex-timedlock-pthread-cond-timedwait

I'd assume that'd fix other time switch related problems on those platforms as well.

**Comment by D-r-P-3-p-p-3-r** [comment]
Just simply switching to CLOCK_MONOTONIC

and

```
	pthread_condattr_t condattr;
	pthread_condattr_init(&condattr);
	pthread_condattr_setclock(&condattr, CLOCK_MONOTONIC);
	pthread_cond_init(&send_cond->cond, &condattr);
```

 does seem to fix the problem.

BUT it causes 100% CPU load because the condition variable does not seem to sleep anymore.

At least on my i.MX6 Platform...

**Comment by icraggs** [comment]
Is this issue in addition to #646 or instead of?  Either way, it's better to discuss the issue in one place.  I think the changes in #646 are the ones likely to fix the problem.

**Comment by D-r-P-3-p-p-3-r** [comment]
It's in addition of. The fixes in #646 don't fix this problem.
#646 fixes time jumps in the past by retriggering actions. Cause: code didn't do the right thing.
This fix takes care of missing wake ups (correctly: wake ups in the - possibly - far future). Cause: code doesn't get executed as the thread sleeps due to a condition variable.

**Comment by D-r-P-3-p-p-3-r** [comment]
My condition variable doesn't sleep anymore, because setting of CLOCK_MONOTONIC fails. Exactly the problem mentioned in #284.
Still there should be a switch to activate this, _if_ pthread_condattr_setclock() works correctly on a plattform.
Alternatively, there could be a switch to turn it off on plattforms where it is broken. As this is only obvious (and not very obvious neither) at run time, it's most likely best to have an opt-in and not an opt-out switch.

**Comment by D-r-P-3-p-p-3-r** [comment]
I figured my problem out:
My code to set the condition variable to use the monotonic clock was placed in MQTTAsync_init.
But MQTTAsync_init is _not_ called at all, when using the CMake build.
If I call MQTTAsync_init manually everything works just fine! No more unnecessary CPU usage.
See also #655

**Comment by icraggs** [comment]
MQTTAsync_init is now called by the CMake build.

**Comment by D-r-P-3-p-p-3-r** [comment]
Verified with 1.3.4.: This is still broken.
