### ISSUE TITLE
CMake: Windows-Build enforces hard-coded OPENSSL_SEARCH_PATH

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [eclipse-paho/paho.mqtt.c#648]
Current src/CMakeLists.txt requires OpenSSL to reside in a fixed directory
x64
`SET(OPENSSL_SEARCH_PATH "C:/OpenSSL-Win64")`
x86
`SET(OPENSSL_SEARCH_PATH "C:/OpenSSL-Win32")`
We're pulling our third parties in from somewhere else, so this behavior breaks the build.

OPENSSL_SEARCH_PATH passed to CMake should be able to override this hard-coded default. Then everything works fine.

**Comment by icraggs** [comment]
Are you saying that you can't override the default?

**Comment by D-r-P-3-p-p-3-r** [comment]
Yes, that's my point.

**Comment by icraggs** [comment]
So changing it to a CACHE variable should do the trick.

**Comment by D-r-P-3-p-p-3-r** [comment]
Yes. That should be the way to go.

I just checked. There is another related problem. In my OpenSSL (32-bit) build (1.1.0f), the library folder is just called lib and not lib32 (or lib64 in case of a x64 build).
So the OPENSSL_SEARCH_LIB_PATH value calculation should take some different naming conventions into consideration as well.
Maybe some sort of "if lib32 exists else try lib" approach.

**Comment by waltronix** [comment]
I had the problem with the always overwritten OPENSSL_SEARCH_PATH and solved it by checking if the variable has a value before giving it a default value.
See the linked pull request #780 

@icraggs: If you would prefer the CACHE solution, I could try that and prepare another pull request.

**Comment by icraggs** [comment]
I think this is now fixed in the develop branch.
