### ISSUE TITLE
When assigning message id to command, restored persisted outgoing messages not checked for conflict

### ISSUE THREAD

**Issue by jens-f** [eclipse-paho/paho.mqtt.c#649]
I'm using message persistence for mission critical data and it looks like after restoring an unacknowledged QoS2 published message, a newly generated publish message might get assigned the same message id, hence overwriting the other message in the persistence store.

From looking at the code, this issue could be resolved by including checking  the msgids of `outboundMsgs` messages inside `MQTTAsync_assignMsgId` when performing step 7 below

I'm using paho.c version 1.3

Detailed steps to reproduce:
1. Run a Mqtt server
2. Start and connect a paho client with persistence enabled (`MQTTCLIENT_PERSISTENCE_DEFAULT`)
3. After connection was established, send a QoS2 message using `MQTTAsync_send`. It will have `msgid=1` and is persisted with persistence key `s-1`
4. In the Mqtt server, simulate a connection loss that prevents responding with an ACK (e.g. kill server before sending the ACK, in a way that doesn't immediately close the connection)
5. Exit paho client. We now have 1 persisted QoS2 message that needs to be resent.
6. Keep server killed and restart paho client. The client is not connected and has restored the unsent QoS2 message into the outbound messages list (`outboundMsgs`). 
7. While still disconnected, trigger sending a second QoS2 message inside the paho client using `MQTTAsync_send`. This will lead to a `command` with `token=1` and a persistence key `c-1`
8. Start Mqtt server and wait until paho client has re-connected
9. Once the connection is established, the paho client will retry sending message `s-1` from step 3.
10. On server side, simulate another connectivity issue that and prevents server from sending the ACK response
11. Observe that meanwhile inside the paho client, command `c-1` with `token=1` will be converted into a message with `msgid=1`. This is the same message id given to `s-1` from step 3, which is still in the outbound messages list (`outboundMsgs`). The new message is persisted with the already taken persistence key `s-1` and hence overwrites that message in the persistence store. At that point, if the client was restarted, we would have lost the first QoS2 message.

**Comment by ruantu** [comment]
This issue is caused by #588, check the MQTAsync.c line 944
