### ISSUE TITLE
Option to not persist QoS 0 commands

### ISSUE THREAD

**Issue by jens-f** [eclipse-paho/paho.mqtt.c#650]
I'm using message persistence in paho 1.3 using default persistence (MQTTCLIENT_PERSISTENCE_DEFAULT). When sending QoS 0 messages using `MQTTAsync_send`, the `command` for that message is persisted, even when the client is currently connected to a Mqtt server. Right after, the `command` is turned into the actual `message` and the persisted `command` is removed again from storage. Then the created QoS 0 `message` is NOT persisted (only QoS 1 and 2 are) and then sent out.

Would it be possible to turn off persistence of QoS 0 `commands`? We are sending lots of QoS messages from an embedded device with flash storage and would like to limit wear and tear caused by writing the QoS0 commands to the persistence store.  

(There's a related issue in https://github.com/eclipse/paho.mqtt.c/pull/520, which affects cases where the client is not connected to the server)

**Comment by icraggs** [comment]
Seems reasonable.

**Comment by icraggs** [comment]
Added to the develop branch.
