### ISSUE TITLE
getaddrinfo occasionally returns -3 and a connect will fail with -1

### ISSUE THREAD

**Issue by ThePursuer** [eclipse-paho/paho.mqtt.c#652]
The function Socket_new calls getaddrinfo which occasionally returns -3. While it can easily reconnect on retry, the calling chain translates the error to a generic -1 which makes the issue difficult to debug and the logs somewhat cryptic since the address is in fact valid but the resolution failed. 

20190502 092836.215 (1937634320)   (2)> MQTTClient_connectURIVersion:796
20190502 092836.215 Connecting to XXXX with MQTT version 4
20190502 092836.242 (1937634320)    (3)> MQTTProtocol_connect:94
20190502 092836.242 (1937634320)     (4)> MQTTProtocol_addressPort:51
20190502 092836.242 (1937634320)      (5)> MQTTStrncpy:736
20190502 092836.242 the src string is truncated
20190502 092836.242 (1937634320)      (5)< MQTTStrncpy:746
20190502 092836.242 (1937634320)     (4)< MQTTProtocol_addressPort:72
20190502 092836.242 (1937634320)     (4)> Socket_new:603
**20190502 092836.242 getaddrinfo failed for addr XXXX  with rc -3
20190502 092836.242 XXXX is not a valid IP address**

I admit it may be specific to my hardware but it is difficult to handle programatically since the actual error is unknowable at runtime. Can we get a more specific error code at the connect call? -1 implies the client is failing when it is in fact the underlying linux call. I can write the fix myself too.

**Comment by ThePursuer** [comment]
Oh hang on I think the port number isn't being passed to getaddrinfo in Socket_new(...). I have provided a port number but NULL is passed into getaddrinfo by Socket_new, is this a problem?

**Comment by icraggs** [comment]
If this is still a concern, then you could reopen.  Thanks.
