### ISSUE TITLE
The topicName passed to the messageArrived callback function is not set

### ISSUE THREAD

**Issue by jzhang666** [eclipse-paho/paho.mqtt.c#653]
I am using the paho.mqtt.c 1.3.0 and find that the topicName string my callback function gets is not correct (likely not set as the data seems random if I print out in hex), though the topicLen is correct. I am using the TLS connection. Not sure why is like this:

DEBUG (../mqtt/CMqttTransport.cpp at line 53): Callback: 3 message received on topic V. len=24.
DEBUG (../mqtt/CMqttTransport.cpp at line 54): Print topic string in HEX:
HEX_DUMP (../mqtt/CMqttTransport.cpp at line 55):

0x1 0x56 00 00 0x61 0x44 0x73 0x38 0x56 0x63 0x2d 0x61 0x76 0x5f 0x75 0x73
0x5f 0x30 0x30 0x31 0x2d 0x67 0x65 0x74 

DEBUG (../mqtt/CMqttTransport.cpp at line 53): Callback: 4 message received on topic . len=24.
DEBUG (../mqtt/CMqttTransport.cpp at line 54): Print topic string in HEX:
HEX_DUMP (../mqtt/CMqttTransport.cpp at line 55):

00 00 00 00 0xf0 0x80 0xdf 0x23 0x1 0x56 00 00 00 00 00 00
00 00 00 00 0x4 00 00 00

**Comment by icraggs** [comment]
The topic strings you are printing out have null characters in them which will truncate the topic printout.  I'm not sure what data you are expecting.

**Comment by jzhang666** [comment]
The only topic that is subscribed is "1xk7aDs8Vc-av_us_001-get" and MQTTClient_subscribe() returned MQTTCLIENT_SUCCESS:  

LOG (agent_data_publisher.cxx at line 181): Subscribing topic 1xk7aDs8Vc-av_us_001-get returned 0

I am not sure why the NULL characters are at the beginning. You mean the Server may not set the topic name correctly?

**Comment by jzhang666** [comment]
> The topic strings you are printing out have null characters in them which will truncate the topic printout. I'm not sure what data you are expecting.

The only topic that is subscribed is "1xk7aDs8Vc-av_us_001-get" and MQTTClient_subscribe() returned MQTTCLIENT_SUCCESS:

LOG (agent_data_publisher.cxx at line 181): Subscribing topic 1xk7aDs8Vc-av_us_001-get returned 0

I am not sure why the NULL characters are at the beginning. You mean the Server may not set the topic name correctly?

**Comment by icraggs** [comment]
If you still have this problem, a trace (as described in the README), or program which exhibits it could be helpful.

**Comment by fpagliughi** [comment]
Also, a packet sniffer like WireShark could really be helpful to see what is being passed around.
