### ISSUE TITLE
CMake build: MQTTAsync_init is not called

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [eclipse-paho/paho.mqtt.c#655]
In the original Makefile (eclipse/paho.mqtt.c/Makefile) an init function is set:
`LDFLAGS_AS = $(LDFLAGS) -shared $(START_GROUP) -lpthread $(EXTRA_LIB) -lssl -lcrypto $(END_GROUP) -Wl,-init,$(MQTTASYNC_INIT)`
A build via CMake does not do this! Thus MQTTAsync_init is never called!

Same is probably true for MQTTClient_init.

**Comment by icraggs** [comment]
It looks like it.  If this is true, I'm not sure how the Travis tests, which use CMake, work.

**Comment by D-r-P-3-p-p-3-r** [comment]
I think it works because
```
static pthread_mutex_t mqttasync_mutex_store = PTHREAD_MUTEX_INITIALIZER;
static mutex_type mqttasync_mutex = &mqttasync_mutex_store;

static pthread_mutex_t socket_mutex_store = PTHREAD_MUTEX_INITIALIZER;
static mutex_type socket_mutex = &socket_mutex_store;

static pthread_mutex_t mqttcommand_mutex_store = PTHREAD_MUTEX_INITIALIZER;
static mutex_type mqttcommand_mutex = &mqttcommand_mutex_store;

static cond_type_struct send_cond_store = { PTHREAD_COND_INITIALIZER, PTHREAD_MUTEX_INITIALIZER };
static cond_type send_cond = &send_cond_store;
```
does the very same already, so the initialization in MQTTAsync_init() is kinda superfluous.

I only noticed that the call is missing, because I tried to set CLOCK_MONOTONIC for a condition variable in this function and it didn't work.

**Comment by icraggs** [comment]
Ah, now I remember.  The init() function sets the attributes on the mutexes to PTHREAD_MUTEX_ERRORCHECK for better error checking.  So calling it is not essential, but would be useful.  The Linux manual excerpt is:

_PTHREAD_MUTEX_NORMAL
This type of mutex does not detect deadlock. A thread attempting to relock this mutex without first unlocking it shall deadlock. Attempting to unlock a mutex locked by a different thread results in undefined behavior. Attempting to unlock an unlocked mutex results in undefined behavior._

_PTHREAD_MUTEX_ERRORCHECK
This type of mutex provides error checking. A thread attempting to relock this mutex without first unlocking it shall return with an error. A thread attempting to unlock a mutex which another thread has locked shall return with an error. A thread attempting to unlock an unlocked mutex shall return with an error._

**Comment by D-r-P-3-p-p-3-r** [comment]
#284 
> I had to remove the use of CLOCK_MONOTONIC from Thread_wait_cond() as well, as it didn't work on some platforms. Same logic as for Thread_wait_sem(): the waits are not long, and repeated frequently, so not really affected by system clock changes.

Is this related?

**Comment by fpagliughi** [comment]
Two quick points:

1. I believe that the linker init only works for shared libraries, where it runs the function when it loads the library. I think we need a solution that works equally well for static and shared libs across all platforms. It seems like the static library is somewhat problematic at the moment.

2. I wonder if PTHREAD_MUTEX_ERRORCHECK comes with a performance penalty. If so I would vote to include it in a debug build, but not a release build.

**Comment by icraggs** [comment]
@fpagliughi there does appear to be a performance penalty from a quick search, but how significant, I don't know.
