### ISSUE TITLE
Crash on ARM: Possible miss of lock acquisition during MQTTAsync_assignMsgId?

### ISSUE THREAD

**Issue by ramanawithu** [eclipse-paho/paho.mqtt.c#656]
Here is test code and stack trace of crash on ARM (Raspberry) Linux platform. We are trying to subscribe/unsubscribe in parallel. This resulted in crash inside LinkedList, especially custom command compare function as it tried compare invalid node. Attached code for reproduce, along with stack trace. It appeared on 1.3.0, you can reproduce this on 1.2.1 also. We need to run it few times to reproduce. It wasn't easy to reproduce on high end machines (more cores).

[bug.zip](https://github.com/eclipse/paho.mqtt.c/files/3191240/bug.zip)

**Comment by ramanawithu** [comment]
Could someone respond? If you need any other information, do lemme know.

**Comment by icraggs** [comment]
You could take a client library trace as described in the readme.  That might help until I have a Linux machine to try it out.

As a matter of interest, why are you exercising subscribe/unsubscribe a lot?  Usually publish is the call which is used most - is this to show a problem you've met elsewhere?

**Comment by icraggs** [comment]
Thanks for the test program.  I've tried it out on a desktop Linux machine and a Raspberry Pi, but not reproduced the issue so far.  I realise it could be timing sensitive.

The lock should be taken at:

	if (thread_id != sendThread_id && thread_id != receiveThread_id)
	{
		MQTTAsync_lock_mutex(mqttasync_mutex);
		locked = 1;
	}

in assignMsgid.  You could add some debug to see if that code is actually being called when you get the problem, and if not, why the if statement is not correct.

**Comment by ramanawithu** [comment]
Ian, I too tried enabling MQTT debugging env variables. I couldn't able to reproduce with these. As mentioned, it seems a time sensitive issue as it is not appearing when lot of logs are printed or on high end machines. I have seen this only on Raspberry Pi ARM machine so far, and the stack trace for same is provided.

We are testing the a scenario in which we do continuous subscribe/unsubscribe on paho-c API, during which we have observed the crash. As a workaround I have introduced application level lock to let only one subscribe/unsubscribe call to go through.

Perhaps we could increase the chances of reproduction by increasing more parallelism.

**Comment by icraggs** [comment]
You could add debug print statement(s) to the assignMsgid function to see if the call to MQTTAsync_lock_mutex is actually made when the problem occurs, or how frequently it's made.

**Comment by ramanawithu** [comment]
Ian, I have added application level lock in the application prior to MQTT call. That solved the problem for now. If I remove the lock, it was appearing in our application quite frequently. But very difficult to reproduce outside our application, seems some timing issue causing deterministic reproduction of the crash. I will try to provide logs in few days (occupied for now).

**Comment by icraggs** [comment]
Thanks.
