### ISSUE TITLE
GLIBC Version Error

### ISSUE THREAD

**Issue by cp26** [eclipse-paho/paho.mqtt.c#658]
I just recompiled my project using the latest libraries from Paho 1.4.  I followed the same procedure as before using CMAKE to cross compile the Paho libraries for arm.

I am now receiving a GLIBC version error: "/lib/libc.so.6: version `GLIBC_2.17' not found (required by /usr/lib/libpaho-mqtt3as.so.1)"

Paho 1.3 does not produce this error.  Can anyone point me to where the GLIBC version is set in the new Paho 1.4?

**Comment by cp26** [comment]
I have found that the issue is linked to the clock_gettime. 
This function ran in the terminal: `objdump -T libpaho-mqtt3c.so.1 | grep 2.17
`
results in: `00000000      DF *UND*	00000000  GLIBC_2.17  clock_gettime`

I still can not find what change between Paho 1.3 and Paho 1.4 causes this GLIBC error.  The symbol clock_gettime is not even generated when running an objdump on Paho 1.3.

**Comment by icraggs** [comment]
What platform/OS are you using?  This stackoverflow entry has some ideas for an embedded device:  https://stackoverflow.com/questions/19471683/lib-libc-so-6-version-glibc-2-17-not-found

**Comment by cp26** [comment]
I am compiling on Ubuntu using arm-linux-gnueabi-gcc-5.  This is the same compiler I used on Paho 1.3 that interestingly does not add clock_gettime to the symbol table. 

Maybe I am heading in the wrong direction but I think there must be a difference between the cmake build instructions between 1.3 and 1.4 that causes this. 
 
Just for full disclosure here are the 1.3 commands: 
` cmake -GNinja -DPAHO_WITH_SSL=TRUE -DOPENSSL_SEARCH_PATH=~/Desktop/opensslArm3 -DCMAKE_TOOLCHAIN_FILE=~/paho.mqtt.c-1.2.0/cmake/toolchain.linux-arm_5.cmake  ~/paho.mqtt.c-1.2.0`

Here are the 1.4 commands: 
`cmake -GNinja -DPAHO_WITH_SSL=TRUE -DOPENSSL_SEARCH_PATH=~/Desktop/opensslArm3 -DCMAKE_TOOLCHAIN_FILE=~/paho.mqtt.c-1.3.0/cmake/toolchain.linux-arm_5.cmake ~/paho.mqtt.c-1.3.0`

The toolchain contains:
`SET(CMAKE_C_COMPILER arm-linux-gnueabi-gcc-5)`
`SET(CMAKE_SYSTEM_NAME Linux)`
`SET(CMAKE_SYSTEM_PROCESSOR arm)`
`SET(CMAKE_SYSTEM_VERSION 1)`

Objdump from 1.3:
`objdump -T libpaho-mqtt3as.so.1 | grep GLIBC_2.17`
nothing found

Objdump from 1.4:
`objdump -T libpaho-mqtt3as.so.1 | grep GLIBC_2.17`
`00000000      DF *UND*	00000000  GLIBC_2.17  clock_gettime`









`

**Comment by icraggs** [comment]
I did make some changes in the calls to time functions to try to cope with system clock changes, so this seems a likely cause.

This stackoverflow entry discusses the need to link with -lrt to get to clock_gettime, but says that this is not necessary from glibc 2.17: https://stackoverflow.com/questions/2418157/c-error-undefined-reference-to-clock-gettime-and-clock-settime
