### ISSUE TITLE
Link MQTT C Library to Mac OS

### ISSUE THREAD

**Issue by anyonepaw** [eclipse-paho/paho.mqtt.c#659]
I don't know how you are trying to build the library, or which version you are using, but that part of the code is not applicable to OS/X.   The Makefile and CMake builds work on OS/X for me.  The CMake builds are used on Travis all the time.

_Originally posted by @icraggs in https://github.com/eclipse/paho.mqtt.c/issues/595#issuecomment-449725632_

Hello, Ian @icraggs!
You said that Makefile and CMake builds works on OS/X for you - but as for me it builds both .dylib and .a, but I tried everything already - I can't link these libraries in any ways with CMake (I try to use them in CLion project) and other ways. Could you help me writing steps on how you link them? I surfed all the internet vainly for a month already..please, help!

**Comment by icraggs** [comment]
So, straight make works like this (from the repo main directory):

make

and the CMake build, outside of Travis:

. travis_macos_vars (sets a couple of environment variables which to mimic Travis environment)
./travis-build.sh (will try to run tests too, but you can stop it then, with the binaries already built).

Both methods build both samples and tests as applications.  So the Make method builds a test with this command, for instance:

cc -g -o build/output/test/test5 src/../test/test5.c -lpaho-mqtt3as  -I src  -lpthread -lssl -lcrypto  -L build/output -L /usr/local/opt/openssl/lib

**Comment by anyonepaw** [comment]
@icraggs, thank you very much for so quick answering!!! and your answer really works!
But it wasn't the whole question (I just so sorry not to explain all at once): I want it to work not only in its native project repo but from any project I work:)

For example, it is simply built and works in its native repo: 
<img width="1280" alt="Screenshot 2019-05-25 at 10 53 07" src="https://user-images.githubusercontent.com/32063879/58366465-51fd4080-7edb-11e9-8fcc-03e7cc9f9952.png">

But how about my own project?:)
<img width="1279" alt="Screenshot 2019-05-25 at 10 54 33" src="https://user-images.githubusercontent.com/32063879/58366480-8113b200-7edb-11e9-99dc-2dd266c554f6.png">

So, I wasn't able to find a way to link .dylibs and .a to make it work in every place
Like a `#include <pahomqtt>` and all works:)

But I find a way to hardcode it in CMakeList.txt (builds downloaded from here: https://www.eclipse.org/downloads/download.php?file=/paho/1.4/Eclipse-Paho-MQTT-C-1.3.0-Darwin.tar.gz):
<img width="1054" alt="Screenshot 2019-05-25 at 10 59 34" src="https://user-images.githubusercontent.com/32063879/58366521-32b2e300-7edc-11e9-974a-6f177e3a1bbb.png">

And now the same code seems to work:
<img width="916" alt="Screenshot 2019-05-25 at 11 21 34" src="https://user-images.githubusercontent.com/32063879/58366725-51ff3f80-7edf-11e9-99ce-fecded2cf305.png">

So, my question is:) : maybe there is another more competent way to link it (for example, to move it to a project /lib and take it from there (but, in CMakeList.txt with target_link...() not working - only hardcode from computer directories)) or another simple 3 strings of code in CMakeList.txt.

So, like this:) It is not urgent! but I'm curious😅
