### ISSUE TITLE
How to choose static runtime linkage "/MT(d)" for paho-mqtt3a/c(-static)?

### ISSUE THREAD

**Issue by aholzinger** [eclipse-paho/paho.mqtt.c#660]
When cmaking for Visual Studio the C runtime settings for paho-mqtt3a/c(-static) are always set to "/MD" which is problematic in wo ways:

- for debug builds the "d" counterpart should be selected: "/MDd"
- projects depending on using the static runtime "/MT" resp. "/MTd" can't use the paho mqtt libs

What are the correct paho.mqgtt.c cmake parameters to select the desired C runtime switch for Visual Studio builds?

**Comment by aholzinger** [comment]
Proposing this fix.
[0001-Introduce-cmake-variable-PAHO_STATIC_RUNTIME-to-sele.zip](https://github.com/eclipse/paho.mqtt.c/files/3219432/0001-Introduce-cmake-variable-PAHO_STATIC_RUNTIME-to-sele.zip)

**Comment by icraggs** [comment]
Going to be looked at under #792

**Comment by gbronner** [comment]
For those who run into this problem:
In the top level: `
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)
CMAKE_POLICY(SET CMP0091 NEW)`

Kill the automatic override  This absolutely confused me.  I also got rid of the multibyte char set.
`
IF(WIN32)
  /*ADD_DEFINITIONS(-D_CRT_SECURE_NO_DEPRECATE -DWIN32_LEAN_AND_MEAN -MD)
  ADD_DEFINITIONS(-D_CRT_SECURE_NO_DEPRECATE -DWIN32_LEAN_AND_MEAN -D_SBCS)

`
in the src file:
`
IF(PAHO_BUILD_STATIC)
SET(CMAKE_MSVC_RUNTIME_LIBRARY_DEFAULT "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()`

There are better ways of doing this --e.g. if you are trying to build static and shared at the same time, you'll have issues.
