### ISSUE TITLE
MQTT V5 : MQTTClient_Disconnect5 doesn't send DISCONNECT packet , resulting in 'Socket Error' on mosquitto server.

### ISSUE THREAD

**Issue by BinduRao2018** [eclipse-paho/paho.mqtt.c#661]
Paho client version - v1.3.0

I am trying a simple example that connects to Mosquitto on localhost, publish a message and then disconnects.

Here is a code snippet:

int main (int argc, char* argv[])
{
  MQTTClient client;
  MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer5;
  MQTTClient_createOptions createOpts = MQTTClient_createOptions_initializer;  
  createOpts.MQTTVersion = MQTTVERSION_5;
  MQTTClient_message pubmsg = MQTTClient_message_initializer;
  int rc = 0;
  conn_opts.keepAliveInterval = 10;

  rc = MQTTClient_createWithOptions(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE,NULL, &createOpts);

 MQTTProperties props = MQTTProperties_initializer;
 MQTTProperties willProps = MQTTProperties_initializer;
 MQTTResponse response = MQTTResponse_initializer;
 MQTTClient_deliveryToken token;

   conn_opts.cleanstart = 1;
   response = MQTTClient_connect5(client, &conn_opts, &props, &willProps);
   rc = response.reasonCode;

   pubmsg.payload = PAYLOAD;
   pubmsg.payloadlen = (int)strlen(PAYLOAD);
   pubmsg.qos = QOS;
   pubmsg.retained = 0;
   response = MQTTClient_publish5(client, TOPIC, pubmsg.payloadlen, pubmsg.payload, 0, 0, &props, &token);

   rc = MQTTClient_waitForCompletion(client, token, TIMEOUT);
   rc = MQTTClient_disconnect5(client, 10000, MQTTREASONCODE_SUCCESS, NULL);
   
 MQTTClient_destroy(&client);

   return EXIT_SUCCESS;
}

- Connect is successful and the message is published. Mosquitto logs "Socket error on client <name>, disconnecting when MQTTClient_Disconnect5 is called. 
Using wireshark, I see that Disconnect Req packet is not sent to the server.

**Comment by icraggs** [comment]
Can you take a client library trace, as described in the readme, please.  Thanks.

**Comment by BinduRao2018** [comment]
Here is a trace file attached, with the MQTT_C_CLIENT_TRACE_LEVEL=MAXIMUM.

[mqtt_trace.txt](https://github.com/eclipse/paho.mqtt.c/files/3232387/mqtt_trace.txt)

**Comment by icraggs** [comment]
Thanks.  I've added a fix to the develop branch.  The disconnect packet was being sent if there were properties or a non-zero reason code, which is why the tests didn't pick it up - if there was something interesting to be sent, it was.

**Comment by BinduRao2018** [comment]
I tried the same test with develop branch. Unfortunately, I still see the same problem.
Please find attached a trace file with the new version of paho mqtt.

[paho_v1.3.1.txt](https://github.com/eclipse/paho.mqtt.c/files/3236067/paho_v1.3.1.txt)

**Comment by icraggs** [comment]
That trace looks like the old one without the change having been picked up.  The trace between the disconnect send start and return should look like this:

20190530 100729.668 (297670080)   (2)> MQTTPacket_send_disconnect:488
20190530 100729.668 (297670080)    (3)> MQTTPacket_send:187
20190530 100729.668 (297670080)     (4)> MQTTPacket_encode:281
20190530 100729.668 (297670080)     (4)< MQTTPacket_encode:291 (1)
20190530 100729.668 (297670080)     (4)> WebSocket_putdatas:782
20190530 100729.668 (297670080)      (5)> Socket_putdatas:502
20190530 100729.668 (297670080)       (6)> Socket_writev:426
20190530 100729.668 (297670080)       (6)< Socket_writev:478 (2)
20190530 100729.668 (297670080)      (5)< Socket_putdatas:550 (0)
20190530 100729.668 (297670080)     (4)< WebSocket_putdatas:814 (0)
20190530 100729.668 (297670080)    (3)< MQTTPacket_send:216 (0)
20190530 100729.668 5 CLIENTID -> DISCONNECT (0)
20190530 100729.668 (297670080)   (2)< MQTTPacket_send_disconnect:508 (0)

You'll see that the change is in the develop branch: https://github.com/eclipse/paho.mqtt.c/commit/08a153e0e8281159d146a9bc65b73e1e4cab9255

**Comment by BinduRao2018** [comment]
Apologies.  I was linking against the old libraries !
Yes, the problem is fixed with the new version and thanks for addressing it quickly.
May i know by when v1.3.1 release would be available please ?

**Comment by icraggs** [comment]
There are a few fixes I should put out.  I'll try to do it soon.  I tentatively scheduled 1.3.1 before the end of June.

**Comment by BinduRao2018** [comment]
Thanks for the update @icraggs .
