### ISSUE TITLE
Question: MQTT 5.0 Will delay

### ISSUE THREAD

**Issue by mramsey96** [eclipse-paho/paho.mqtt.c#662]
Is the 5.0 feature "will delay" currently supported?

**Comment by icraggs** [comment]
Yes.  From the client library point of view it's one of the will properties on the connect packet.

**Comment by ghost** [comment]
Hello, 
I'm curious on which property of MQTTAsync_connectOptions you are referring to.

**Comment by fpagliughi** [comment]
The connect options struct contains a field for the MQTT v5 properties for the will (lwt) message:
https://github.com/eclipse/paho.mqtt.c/blob/3b7ae6348bc917d42c04efa962e4868c09bbde9f/src/MQTTAsync.h#L1327-L1330

The properties that you can set, including the "will delay interval" are described in the v5 spec:
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901060
