### ISSUE TITLE
Receiving pending messages in synchronous mode

### ISSUE THREAD

**Issue by martinezcp** [eclipse-paho/paho.mqtt.c#666]
I am trying to implement an application with a synchronous mode. I connect to me broker and then I wait for pending messages for about 5 seconds but nothing is received.

If I try with a command line client, I always get the pending messages. I think I am doing something wrong with the paho library.

`MQTTClient 					client;
	MQTTClient_connectOptions 	conn_opts 	= MQTTClient_connectOptions_initializer;
	MQTTClient_createOptions 	createOpts 	= MQTTClient_createOptions_initializer;
	MQTTClient_message 			*message 	= NULL;
	MQTTClient_message pubmsg = MQTTClient_message_initializer;
	MQTTClient_deliveryToken token;

	int rc;

	printf("    - MQTT: Connecting...");

	rc = MQTTClient_createWithOptions(&client, SELCAN_MQTT_config->url, CLIENT_ID, MQTTCLIENT_PERSISTENCE_NONE, NULL, &createOpts);
	if (rc != MQTTCLIENT_SUCCESS) {
		printf("FAIL");
	}
	conn_opts.keepAliveInterval = 10000L;
	conn_opts.cleansession 		= 0;
	conn_opts.username 		= USER;
	conn_opts.password 		= PASSWORD;
	conn_opts.retryInterval		= 1;
	conn_opts.reliable			= 1;

	 if ((rc = MQTTClient_connect(client, &conn_opts)) == MQTTCLIENT_SUCCESS) {
		printf("CONNECTED\r\n");
	}

	 pubmsg.payload = PAYLOAD;
	 pubmsg.payloadlen = strlen(PAYLOAD);
	 pubmsg.qos = QOS;
	 pubmsg.retained = 0;
	 MQTTClient_publishMessage(client, TOPIC, &pubmsg, &token);

	nb = strlen(TOPIC_SUBS);
	MQTTClient_receive(client, &TOPIC_SUB, &nb, &message, 5000);`

In case I send the message while application is waiting, it gets the message without problems.

Do I need to configure something different?

**Comment by icraggs** [comment]
The command line programs always set callbacks which means that a background thread is started.  That could explain a difference in behaviour.
