### ISSUE TITLE
OpenSSL Error - Connect failed

### ISSUE THREAD

**Issue by joshsavage** [eclipse-paho/paho.mqtt.c#668]
On mac I'm unable to connect over a secure port using the paho_c_sub or paho_cs_sub samples. It says "Connect failed, rc Failure". Using "mosquitto_sub" works perfectly using the same parameters. 

Here's the paho_c_sub command I'm using :
```
paho_c_sub mytopic -h mqtt.mydomain.com -p 8883 --cafile /usr/local/etc/openssl/cert.pem -u "myuser" -P "mypass"
```

On the server it says:
```
1560519266: OpenSSL Error: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
1560519266: Socket error on client <unknown>, disconnecting.
```

I have set up a standard mosquitto MQTT broker following this tutorial : https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-the-mosquitto-mqtt-messaging-broker-on-ubuntu-18-04-quickstart

Any suggestions on how to fix?

**Comment by thedevilfish** [comment]
What version of OpenSSL are you using? Did you build mosquitto and paho-c with OpenSSL support?

**Comment by icraggs** [comment]
If you use the --trace protocol option, it will print out the OpenSSL exchange diagnostics - these may explain more.  Also the Mosquitto log might have some information.

**Comment by joshsavage** [comment]
I fixed the issue. I found that with paho_c_sub I don't need to supply a cafile and it works fines.
