### ISSUE TITLE
crashed at LinkedList.c:157 on centos6.7 x64

### ISSUE THREAD

**Issue by Taygetus** [eclipse-paho/paho.mqtt.c#671]
![image](https://user-images.githubusercontent.com/33971057/60311753-3c23e500-998b-11e9-8d80-36086d64ca28.png)

**Comment by icraggs** [comment]
If you can take a trace as outlined in the README then this might help.  Also a description of how frequently and under what circumstances this occurs.  A test program to reproduce would be ideal.
