### ISSUE TITLE
MQTTClient: Add configurable command timeout for subscribe, unsubscribe

### ISSUE THREAD

**Issue by giovani-milanez** [eclipse-paho/paho.mqtt.c#673]
Hi guys,

My client was connecting fine but was disconnecting itself after a subscribe failure.
I've noticed that the subscribe was failing after 10 seconds.
So I had a look at the paho mqtt c code.

`MQTTClient_subscribe` ends up calling `MQTTClient_subscribeMany5` and in [this line](https://github.com/eclipse/paho.mqtt.c/blob/master/src/MQTTClient.c#L1847) there is a call to `MQTTClient_waitfor(handle, SUBACK, &rc, 10000L);`

When the broker is too busy it can take more than 10 seconds to reply.

Can we make this timeout configurable  ?

**Comment by icraggs** [comment]
Yes, of course it's possible.  That seems a very long time to wait.  Another option to consider would be to use the asynchronous API.

**Comment by icraggs** [comment]
Fix added to develop branch.
