### ISSUE TITLE
OPENSSL | CMake Error: The following variables are used in this project, but they are set to NOTFOUND. 

### ISSUE THREAD

**Issue by ghost** [eclipse-paho/paho.mqtt.c#677]
OpenSSL Library error.

installed version is :
         OpenSSL 1.1.0g  2 Nov 2017 (Library: OpenSSL 1.1.1  11 Sep 2018)

Run Command is:
         sudo cmake -GNinja -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_SAMPLES=TRUE -DPAHO_BUILD_DOCUMENTATION=TRUE -DOPENSSL_LIB_SEARCH_PATH=/tmp/libssl-dev/usr/lib/arm-linux-gnueabihf -DOPENSSL_INC_SEARCH_PATH="/tmp/libssl-dev/usr/include/openssl;/tmp/libssl-dev/usr/include/arm-linux-gnueabihf" -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.linux-arm11.cmake ~/mqtt_lib/paho.mqtt.c

Error i got is:

-- CMake version: 3.10.2
-- CMake system name: Linux
-- Timestamp is 2019-07-15T02:36:21Z
-- OpenSSL hints: 
-- OpenSSL headers found at /usr/include
-- OpenSSL library found at OPENSSL_LIB-NOTFOUND
-- OpenSSL Crypto library found at OPENSSLCRYPTO_LIB-NOTFOUND
-- OpenSSL hints: 
-- OpenSSL headers found at /usr/include
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENSSLCRYPTO_LIB
    linked by target "paho-mqtt3cs" in directory /home/toor/mqtt_lib/paho.mqtt.c/src
    linked by target "paho-mqtt3as" in directory /home/toor/mqtt_lib/paho.mqtt.c/src
    linked by target "Base64TestOpenSSL" in directory /home/toor/mqtt_lib/paho.mqtt.c/src
    linked by target "Sha1TestOpenSSL" in directory /home/toor/mqtt_lib/paho.mqtt.c/src
OPENSSL_LIB
    linked by target "paho-mqtt3cs" in directory /home/toor/mqtt_lib/paho.mqtt.c/src
    linked by target "paho-mqtt3as" in directory /home/toor/mqtt_lib/paho.mqtt.c/src
    linked by target "Base64TestOpenSSL" in directory /home/toor/mqtt_lib/paho.mqtt.c/src
    linked by target "Sha1TestOpenSSL" in directory /home/toor/mqtt_lib/paho.mqtt.c/src

-- Configuring incomplete, errors occurred!

++++++++++++++++++++++++++++++++++++++++++
it's been a week i'm stucked at this point please suggest me how to handle it.

Thanks In Advance  :) :)

**Comment by burnedfire** [comment]
hello, I meet same problem. Have you completed it?

**Comment by ghost** [comment]
yes, I figured it out. just version problem. you have to check which openssl version is compatible.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by burnedfire** [comment]
thanks for your reply. I have solve this problem with the way I add two parameters “-DOPENSSL_LIB=my OpenSSL lib path” and “-DOPENSSSLCRYPTO_LIB=my openssl lib path” when I cmake the pahoc/cmake/toolchain.linux-arm11.cmake&nbsp;,bucause my OpenSSL compile by myself.







------------------ Original ------------------
