### ISSUE TITLE
PAHO and Telit LE910C1

### ISSUE THREAD

**Issue by GAnto85** [eclipse-paho/paho.mqtt.c#684]
Hi,
I have to use the MQTT protocol in a system composed of a STM32F7 mcu and a Telit LE910C1 4g module, which communicate via UART. What is the best way for implementing it? I am checking the AT commands reference manual and it seems that the LE910C1 doesn't include any MQTT protocol. Can i use PAHO to create MQTT packets and send them to Telit device through UART? 
Every suggestion is well accepted, since this is the first time that i am doing this. 
Thank you

**Comment by icraggs** [comment]
Sorry for not responding sooner - I was very busy at the time.  From what you say, I think the embedded C client might be a better fit - it is a library for helping to put together MQTT packets and send/receive them.  https://github.com/eclipse/paho.mqtt.embedded-c/
