### ISSUE TITLE
Memory synchronization in pubasync example is broken

### ISSUE THREAD

**Issue by sfindeisen** [eclipse-paho/paho.mqtt.c#687]
I think the use of `volatile` in [this example](https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/pubasync.html) does not do what you think it does. This is not Java. This does not synchronize the `deliveredtoken` variable between the 2 threads. It is not guaranteed that the publishing thread sees the new value within any particular period of time. You might want to use locking (with the side effect of memory synchronization - see [here](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_12)) or C++'s `atomic` var.

[Here](https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/subasync.html) `deliveredtoken` variable is never read.

**Comment by icraggs** [comment]
Examples are now refactored.
