### ISSUE TITLE
Segmentation Fault - Async API - Multithreaded

### ISSUE THREAD

**Issue by prateek-khatri** [eclipse-paho/paho.mqtt.c#697]
Hello,

I have more than 1 threads creating separate client objects publishing data to the same topic. 
After a while (seems non-deterministic) I get the following SIGSEGV :
`Thread 5 "mqtt-test" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 962]
0x0000ffffbe6e8394 in ?? () from /usr/lib/libpaho-mqtt3as.so.1
(gdb) 
`
Things to note as per my implementation is that I am not registering any callbacks for data being published i.e. I don't have a callback for onSend() as per the example given on the website. I am simply creating the client, if the it is connected to the broker, I start calling the MQTTAsync_sendMessage() in a while loop. If I initialize my program with one thread it works just fine, anything more than that eventually produces segmentation fault.

Just to confirm, the Async API was meant to be thread-safe, correct?

Please advise.

Thanks,
Prateek

**Comment by icraggs** [comment]
Yes it is intended to be thread safe.  There are examples of multi-threaded use in the test suites.

**Comment by aggresss** [comment]
This PR may be fix it  https://github.com/eclipse/paho.mqtt.c/pull/707
https://github.com/eclipse/paho.mqtt.c/blob/7a31c2d9e2d578d6a46ef30c1d63d759a7c9847a/src/Socket.c#L929
```c
while (curpending && curpending->content)
```
