### ISSUE TITLE
Deadlock when subscribe

### ISSUE THREAD

**Issue by REBAUD** [eclipse-paho/paho.mqtt.c#698]
Hello,

I work on Linux 18.04 with the release 1.3.0.
the compilation is done with the parameters : 
"cmake -GNinja -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_SAMPLES=TRUE --config Release .."

During the use of the lib, i detect a deadlock when using the fonction MQTTAsync_subscribeMany

The function is call inside the connect cbk, you can find the implementation right below.

```
void onConnectionSuccess(void* context, char* cause)
{
    // Check if context not NULL
    if(NULL != context)
    {
        // Set good context type
        MQTT_Manager* MQTTManager = (MQTT_Manager*)context;

        // Get internal value
        // !!! Take Mutex !!!
        bool verbose            = MQTTManager->getVerbose();
        bool firstTime          = MQTTManager->getFirstTime();
        bool needSubscription   = MQTTManager->getNeedSubscribtion();

        // On first time, force disconneciton to connect well
        if(firstTime)
        {
            if(verbose)
            {
                printf("[MQTT_Manager::onConnectionSuccess::%s] First connexion done => launch deconnexion\n", MQTTManager->getClientId().c_str());
            }
            //Force disconnection
            MQTTManager->disconnect();
        }
        else
        {
            // Set state as connected
            // !!! Take Mutex !!!
            MQTTManager->setState(COMMUNICATION_MQTT_MANAGER_STATE_CONNECTED);
            if(verbose)
            {
                printf("[MQTT_Manager::onConnectionSuccess::%s] Connection succesful (%s)\n", MQTTManager->getClientId().c_str(), cause);
                fflush(stdout);
            }

            if(needSubscription)
            {
                MQTTManager->subscribe(verbose);
            }
        }
    }
    else
    {
        printf("[MQTT_Manager::onConnect] context can't be NULL");
    }
}


void MQTT_Manager::subscribe(bool verbose)
{

    // Get number of topics
    uint16_t nbOfTopics = (uint16_t)m_options.topicsList.size();

    // Init list of topics to subscribe
    char** topicsPath  = (char**)calloc(nbOfTopics, sizeof(char*));
    int* topicsQoS     = (int*)calloc(nbOfTopics, sizeof(int));
    for(uint16_t i = 0; i < nbOfTopics; i++)
    {
        topicsPath[i]   = const_cast<char*>(m_options.topicsList.at(i).path.c_str());
        topicsQoS[i]    = m_options.topicsList.at(i).qos;
    }

    if(verbose)
    {
        for(int i = 0; i < nbOfTopics; i++)
        {
            printf("test %d %s %d\n ", i, topicsPath[i], topicsQoS[i]);
        }
        printf("[MQTT_Manager::subscribe::%s] Manager subsciption started...\n", m_options.clientId.c_str());
    }

    // Create subcribe parameters
    MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
    opts.onSuccess = onSubscribtionSuccess;
    opts.onFailure = onSubscribtionFailure;
    opts.context = this;

    // Subscribe and disconnect if error
    int subscribeResult = MQTTAsync_subscribeMany(m_client, (int)(nbOfTopics), topicsPath, topicsQoS, &opts);
    if(MQTTASYNC_SUCCESS != subscribeResult)
    {
        printf("[MQTT_Manager::subscribe::%s] Manager subsciption error %d\n", m_options.clientId.c_str(), subscribeResult);
        disconnect();
    }
    else
    {
        printf("[MQTT_Manager::subscribe::%s] Manager subsciption success\n", m_options.clientId.c_str());
    }
    
    free((void*)topicsPath);
    free(topicsQoS);
}
```

After activate Trace, and adding print it seems that the issue is iside the funciton MQTTAsync_assignMsgId. The function block with the mutex.lock (deadLock?)
The issue is only reproductible with the lib in release and not in debug.
I add 2 files of trace, one ok, and the other with the bug:
[MQTTOkPrint.txt](https://github.com/eclipse/paho.mqtt.c/files/3464080/MQTTOkPrint.txt)
[MQTTBugPrint.txt](https://github.com/eclipse/paho.mqtt.c/files/3464081/MQTTBugPrint.txt)

If you need more information, or other tests i stay available.

Thank you in advance for your help.

**Comment by REBAUD** [comment]
Hello,

After adding more debug informations, it seems that when the bug occured, the current thread_id is neither the sender or the receiver one. 
When it's working, the thread_id is the same than the receiver.

it seems like 2 threads are created as receiver one : 
'''
20190804 100333.464 (1365214976) (0)< MQTTAsync_connect:3039 (0)
20190804 100333.464 (1255352064) (0)> MQTTAsync_receiveThread:2064
20190804 100333.464 (1263744768) (0)> MQTTAsync_receiveThread:2064
'''

In my application, i create only 2 client each one in a  threads (one for the sender and one for the publisher), but only 1 receiver in these exemples.
In the final one, i want to implement multiples clients sender or receiver, each one in a thread.

I add the Trace with and whithout the bug:
[MQTTBugPrintEnhanced.txt](https://github.com/eclipse/paho.mqtt.c/files/3464674/MQTTBugPrintEnhanced.txt)
[MQTTOkPrintEnhanced.txt](https://github.com/eclipse/paho.mqtt.c/files/3464675/MQTTOkPrintEnhanced.txt)


Thank you

**Comment by REBAUD** [comment]
Hi,

To avoid the bug, i created a new mutex : mqttThreadCreation_mutex

and modify the function MQTTAsync_connect this way :
```
	MQTTAsync_lock_mutex(mqttThreadCreation_mutex);
	if (sendThread_state != STARTING && sendThread_state != RUNNING)
	{
		MQTTAsync_lock_mutex(mqttasync_mutex);
		sendThread_state = STARTING;
		Thread_start(MQTTAsync_sendThread, NULL);
		MQTTAsync_unlock_mutex(mqttasync_mutex);
	}
	if (receiveThread_state != STARTING && receiveThread_state != RUNNING)
	{
		MQTTAsync_lock_mutex(mqttasync_mutex);
		receiveThread_state = STARTING;
		Thread_start(MQTTAsync_receiveThread, handle);
		MQTTAsync_unlock_mutex(mqttasync_mutex);
	}
	MQTTAsync_unlock_mutex(mqttThreadCreation_mutex);
```

i first tried to used mqttasync_mutex instead of creating a new one, but in this case the deadlock happen everytime:
```
	MQTTAsync_lock_mutex(mqttasync_mutex);
	if (sendThread_state != STARTING && sendThread_state != RUNNING)
	{
		sendThread_state = STARTING;
		Thread_start(MQTTAsync_sendThread, NULL);
	}
	if (receiveThread_state != STARTING && receiveThread_state != RUNNING)
	{
		receiveThread_state = STARTING;
		Thread_start(MQTTAsync_receiveThread, handle);
	}
	MQTTAsync_unlock_mutex(mqttasync_mutex);
```

What do you think of the solution proposed?
Do you have a better idea ?

Thank you

**Comment by icraggs** [comment]
Hi.  It seems that the problem is that the test

if (sendThread_state != STARTING && sendThread_state != RUNNING)

being outside of the(a) mutex.   I'm not sure why using the mqttasync_mutex does not work.  Is the deadlock in the same place, or somewhere else?

**Comment by REBAUD** [comment]
I didn't keep Trace with the mutex outside but it was very reproductable (100%) in my implementation.
I supposed it was because of the thread...

Maybe this implementaiton is easier to implement: 

```
bool StartSendThread = false;
bool StartReceiveThread = false;

 MQTTAsync_lock_mutex(mqttasync_mutex);
if (sendThread_state != STARTING && sendThread_state != RUNNING)
{
    sendThread_state = STARTING;
    StartSendThread = true;
}
if (receiveThread_state != STARTING && receiveThread_state != RUNNING)
{
    receiveThread_state = STARTING;
    StartReceiveThread = true;
}
MQTTAsync_unlock_mutex(mqttasync_mutex);

if (StartSendThread)
    Thread_start(MQTTAsync_sendThread, NULL);
if (StartReceiveThread)
    Thread_start(MQTTAsync_receiveThread, handle);
```

The lib is thread safe, true?
Because we add another issue on windows (crash) with the same implementation (but not yet enough information to open a ticket.

Thank you

**Comment by REBAUD** [comment]
Hi,

Just wanted to update the last solution proposed : 
```
    // Define if the thread need to be launch
    bool startSendThread    = 0;
    bool startReceiveThread = 0;
    MQTTAsync_lock_mutex(mqttasync_mutex);
    if (sendThread_state != STARTING && sendThread_state != RUNNING)
    {
        sendThread_state    = STARTING;
        startSendThread     = 1;
    }
    if (receiveThread_state != STARTING && receiveThread_state != RUNNING)
    {
        receiveThread_state = STARTING;
        startReceiveThread  = 1;
    }
    MQTTAsync_unlock_mutex(mqttasync_mutex);
    
    // Launch really the thread
    if (startSendThread)
    {
        Thread_start(MQTTAsync_sendThread, NULL);
    }
    if (startReceiveThread)
    {
        Thread_start(MQTTAsync_receiveThread, handle);
    }
```

In my implementation, it deadlock each time.
I don't know why or where but i get the Trace.
[correctifBloquant.txt](https://github.com/eclipse/paho.mqtt.c/files/3476395/correctifBloquant.txt)

No data sent or receiced, and when calling the death, MQTTAsync_destroy stay blocked.
It seems that calling mqttasync_mutex in the connect could lead to deadlock when the thread are already strated.

Have a very good day

Vincent REBAUD

**Comment by icraggs** [comment]
The first solution, with the creation mutex, is the best one so far if it works.  The second one using the mqttasync_mutex I would like to know where the actual deadlock is.  A trace of that would be useful.

The library is intended to be thread safe, but currently each client object must be disconnected properly for destroy() to be run safely, otherwise data structures which are still being used can be removed.  You can see examples of multi-threaded use in the test suites.

I have a change in mind to optionally have the calls to initialize and terminate the library do the starting and stopping of the background threads to avoid these timing issues entirely.

**Comment by REBAUD** [comment]
In the previous comment ,you will find the Trace when it happen.
I'm also quite confused with the Trace because i don't see exactly where it deadlock.
If you need more information, you can tell me where a print is needed and i can provide it to you.

i'm sure that each of my client is well destroy, each one in it's thread (because of my middleware)
i call MQTTAsync_destroy(&m_client); for each

I made the change on my side with the new mutex, and it seems good for my implementation.

Have a very good day

Vincent

**Comment by icraggs** [comment]
I tried the solution of moving the mqttasync mutex locks/unlocks:

MQTTAsync_lock_mutex(mqttasync_mutex);
	if (sendThread_state != STARTING && sendThread_state != RUNNING)
	{
		sendThread_state = STARTING;
		Thread_start(MQTTAsync_sendThread, NULL);
	}
	if (receiveThread_state != STARTING && receiveThread_state != RUNNING)
	{
		receiveThread_state = STARTING;
		Thread_start(MQTTAsync_receiveThread, handle);
	}
	MQTTAsync_unlock_mutex(mqttasync_mutex);

Ran the CI tests, and they worked.  You said when you did this, "the deadlock happens every time".   But what deadlock?  

I think this is the simplest solution, and should work as far as I can see.  I'd like to prove it doesn't work, if it doesn't.

**Comment by REBAUD** [comment]
In my stack, each time i tried to used mqttasync_mutex here, the program blocks.
I'm not able to send/receive data anymore.
Here the trace: 

it's probably because of my implementation when i start my client the first time:
- First i launch a connection with a cleanSession (i don't care of old messages when i launch the app)
- In the connectionSuccess cbk, i launch a disconnection 
- In the disconnectionSuccess cbk, i launch the conneciton without cleanSession to be able to get message if my app lost connection during it's life
- In the connectionSuccess cbk, i launch the subscribe

here the Trace :
[simpleMQTT.txt](https://github.com/eclipse/paho.mqtt.c/files/3480515/simpleMQTT.txt)

It seems that when the connect is call a second time, the library deadlock.
disconnectSuccess -> connect => Deadlock
Probably because we did'nt test if we already are un sendThread or receiveThread like in MQTTAsync_assignMsgId.

Is it forbiddent to call connect/disconnect/subscribe inside one of the cbk?
I supposed no because of what i saw in the lib so i didn't implement a state machine inside my main thread but used the lib cbk to do it.

Do you think the use i do of the lib is wrong?

Thank you
Vincent

**Comment by REBAUD** [comment]
I confirmed that this modification seems to work in my stack:
```
if (thread_id != sendThread_id && thread_id != receiveThread_id)
	{
		MQTTAsync_lock_mutex(mqttasync_mutex);
		locked = 1;
	}
	if (sendThread_state != STARTING && sendThread_state != RUNNING)
	{
		sendThread_state = STARTING;
		Thread_start(MQTTAsync_sendThread, NULL);
	}
	if (receiveThread_state != STARTING && receiveThread_state != RUNNING)
	{
		receiveThread_state = STARTING;
		Thread_start(MQTTAsync_receiveThread, handle);
	}
	if (locked)
	{
		MQTTAsync_unlock_mutex(mqttasync_mutex);
	}
```

I will test it multiples times to be sure

Thank you

**Comment by icraggs** [comment]
In principle that sequence sounds ok, but yes, I do avoid calling connect in a callback generally.

I may change the logic of those checks (thread_id != sendThread_id && thread_id != receiveThread_id) to make it clearer that we're avoiding locking an already locked mutex.

**Comment by REBAUD** [comment]
Maybe a function to call which always do the test but it's quite clear in the code already because it allow me to understand the fisrt issue which was that i have 2 receiveThread created.

Doing the test in the connect works well for me (tested at least 30 times this day in my app)

Thanks a lot
