### ISSUE TITLE
Synchronous Client failed to connect

### ISSUE THREAD

**Issue by PTalekar** [eclipse-paho/paho.mqtt.c#699]
Hi,
I've tried following client code on windows with x64 eclipse-paho-mqtt-c-win64-1.3.0 (by referring https://www.hivemq.com/blog/mqtt-client-library-pahocclient/ ) But MQTTClient_connect( ) API returns MQTTCLIENT_FAILURE.
Note: firewall is Off.

Any clue ! Please suggest. Thanks.

//---------------------
// Sample client code 
//---------------------
#include "stdafx.h"
#include "MQTTClient.h"

void connectionLost(void *context, char *cause);
int messageArrived(void *context, char *topicName, int topicLen, MQTTClient_message *message);

	//const char* serverURI = "tcp://mqtt.server.com:1883";   
	const char* serverURI = "mqtt.server.com";
	const char* clientId = "clientId";
	const char* topic = "client/topic/#";
	int QoS = 0;

int _tmain(int argc, _TCHAR* argv[])
{
	MQTTClient client = NULL;
	int rc = MQTTCLIENT_FAILURE;
	int ch = 0;
	
	MQTTClient_nameValue* infos = MQTTClient_getVersionInfo();
	
	if( MQTTCLIENT_SUCCESS == (rc = MQTTClient_create(&client, serverURI, clientId, MQTTCLIENT_PERSISTENCE_NONE, NULL)))
	{
		if( MQTTCLIENT_SUCCESS == (rc = MQTTClient_setCallbacks(client, NULL, connectionLost, messageArrived, NULL)))
		{
			MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
			conn_opts.keepAliveInterval = 10;
			conn_opts.cleansession = 1;
			conn_opts.connectTimeout = 20;
			conn_opts.username = "user";
			conn_opts.password = "passwd";
			
			
			if( MQTTCLIENT_SUCCESS == (rc = MQTTClient_connect(client, &conn_opts)))
			{
			  rc = MQTTClient_subscribe(client, topic, QoS);
			}
			else
			{
				// rc returns MQTTCLIENT_FAILURE 
			}
		}
	}
	
	return 0;
}
//-------------------

**Comment by icraggs** [comment]
A trace, as described in the README, might shed some light.  Also any server messages.

**Comment by PTalekar** [comment]
Hi, After doing following changes in client code MQTTClient_connect() and MQTTClient_subscribe() retruns MQTTCLIENT_SUCCESS. But soon after that connection drops as indiacted by attached log entry for connection lost callback. 
Surprisingly log indicates that disconnect request was sent from client (refer log Client-ID -> DISCONNECT) though MQTTClient_disconnect() was not explicitly called after subscribe().

Any guess for what went wrong and clue to move ahead please ! 
Thanks.

 I've added trace as per README, plus followed issue #594 as follows; ( _MQTTClient_connect returns -1 with SSL enabled_ )

**1.** Copied OpenSSL shared libs libeay32.dll and ssleay32.dll (32 bit Ver 1.0.2.16) into folder of paho-mqtt3cs.dll (64 bit)

**2.** Added following code for SSL support;
   MQTTClient_SSLOptions ssl_opts = MQTTClient_SSLOptions_initializer;
   ssl_opts.verify = 0;
   ssl_opts.ssl_error_cb = &ssl_error_cb;
   ssl_opts.enableServerCertAuth = 0;
   
   conn_opts.ssl = &ssl_opts;  // MQTTClient_connectOptions conn_opts
   
**3.** Replaced serverURI = "ssl://mqtt.server.com:8883";

**//-- Log snippet** 
20190807 205757.367 SSL certificate verification: X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY
20190807 205757.367 SSL connect:SSL negotiation finished successfully
20190807 205757.367 sent 0 256 buflen 5
20190807 205757.369 652 **Client-ID -> CONNECT** cleansession: 1 (0)
20190807 205757.369 received 0 256 buflen 5
20190807 205757.568 652 **Client-ID <- CONNACK** rc: 0
** MQTTClient_connect() Connected **
20190807 205757.573 sent 0 256 buflen 5
20190807 205757.573 652 **Client-ID -> SUBSCRIBE** msgid: 1 (0)
20190807 205757.774 received 0 256 buflen 5
20190807 205757.774 652 **Client-ID <- SUBACK** msgid: 1
** MQTTClient_subscribe() Subscribed to topic : MyTopic/datagrams/# **
20190807 205757.774 received 0 256 buflen 5
20190807 205757.812 received 771 21 buflen 2
20190807 205757.812 SSL alert read:warning:close notify
20190807 205757.812 sent 0 256 buflen 5
20190807 205757.817 652 **Client-ID -> DISCONNECT** (0)
20190807 205757.817 sent 0 256 buflen 5
20190807 205757.817 sent 771 21 buflen 2
20190807 205757.817 SSL alert write:warning:close notify
Inside method Connection lost()
//----

**Comment by icraggs** [comment]
Disconnect was probably sent because there was an error on the TLS connection.  A fuller trace would show that.   If you have access to the server logs, you should check those.

It's a (very) bad idea to use a obvious client id of "clientId".  If this is a shared server, you will clash with any other applications that also use the same client id and could get disconnected.  You should use something likely to be unique.

**Comment by PTalekar** [comment]
Clarification on Client-ID : is replacement of actual client id in log and is used here only for illustration purpose.
