### ISSUE TITLE
ServerURI with IPv6 not supported for Windows

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#7]
migrated from Bugzilla [#484496](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484496)
status UNCONFIRMED severity _normal_ in component _MQTT-C_ for _1.2_
Reported in version _1.2_ on platform _PC_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[persistance.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=258731)_ (ID 258731)
- _[IPv6.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=258751)_ (ID 258751)

On 2015-12-16 10:32:52 -0500, Juergen Kosel wrote:

> If the server URI contains an IPv6 address, e.g.
> "tcp://[2002:3e92:dead:beef:250:56ff:fe28:1234]:1883" (invalidated address in example)
> then MQTTAsync_create fails with return value -2 on Windows machines.
> 
> If you use the same valid serverURI on a Linux machine, for example within test/test4.c, then the test passes.

On 2015-12-16 11:06:39 -0500, Juergen Kosel wrote:

> Created attachment 258731
> Partial fix for bug 484496
> 
> With this fix MQTTAsync_Create does not fail with -2 any more.
> But there are other issues, which prevent MQTT and IPv6 from working on Windows.

On 2015-12-17 05:51:58 -0500, Juergen Kosel wrote:

> Created attachment 258751
> Patch to remove the leading '[' from IPv6 addresses
> 
> With this 2nd patch the socket could be created.
> But connecting to a broker with IPv6 address still fails.

**Comment by icraggs** [comment]
I've added a fix to the fixes branch.  As well as the persistence directory name, the socket initialization for IPv6 was not correct.

**Comment by icraggs** [comment]
Merged to develop.
