### ISSUE TITLE
Specifying Physical Interface

### ISSUE THREAD

**Issue by prateek-khatri** [eclipse-paho/paho.mqtt.c#705]
We are planning to have different interfaces on our board and one of the interface would have internet connectivity. 
Is it possible to specify what physical interface to use while creating the client and/or connecting? I couldn't explicitly find this in the documentation.

**Comment by icraggs** [comment]
This isn't possible at the moment.  There is an issue requesting this: #39

**Comment by prateek-khatri** [comment]
Hi @icraggs Thanks for pointing this out.

However, is there a plan to have this feature?

**Comment by icraggs** [comment]
It hadn't risen to the top of the requirements list yet, I thought I might had a contribution to implement it by now!
