### ISSUE TITLE
Abuse break in Socket_continueWrite()

### ISSUE THREAD

**Issue by aggresss** [eclipse-paho/paho.mqtt.c#706]
if add 'break' the remain buffer in pw is not send

https://github.com/eclipse/paho.mqtt.c/blob/7a31c2d9e2d578d6a46ef30c1d63d759a7c9847a/src/Socket.c#L804

```c
for (i = 0; i < pw->count; ++i)
	{
		if (pw->bytes <= curbuflen)
		{ /* if previously written length is less than the buffer we are currently looking at,
				add the whole buffer */
			iovecs1[++curbuf].iov_len = pw->iovecs[i].iov_len;
			iovecs1[curbuf].iov_base = pw->iovecs[i].iov_base;
		}
		else if (pw->bytes < curbuflen + pw->iovecs[i].iov_len)
		{ /* if previously written length is in the middle of the buffer we are currently looking at,
				add some of the buffer */
			size_t offset = pw->bytes - curbuflen;
			iovecs1[++curbuf].iov_len = pw->iovecs[i].iov_len - (ULONG)offset;
			iovecs1[curbuf].iov_base = (char*)pw->iovecs[i].iov_base + offset;
			break;    <======= why break ???
		}
		curbuflen += pw->iovecs[i].iov_len;
	}
```

If have a pw iovec[5] , every iovec.iov_len equ 10. when bytes equ 4, in for loop the iovec[0] `s 5-10 bytes has been copyed, the remain iovec 1-4 not copyed .

**Comment by icraggs** [comment]
It's not going to make any difference in practice because the last buffer is always the one going to cause a partial write because it's the payload.  Having said that it's probably cleaner to remove it - it's been there forever so I don't remember the logic.  It could have been for testing maybe.
