### ISSUE TITLE
Free invalid pointer when pending write run free()

### ISSUE THREAD

**Issue by aggresss** [eclipse-paho/paho.mqtt.c#709]
In function Socket_continueWrite() , when pw is write complete, will free pw->iovecs
https://github.com/eclipse/paho.mqtt.c/blob/7a31c2d9e2d578d6a46ef30c1d63d759a7c9847a/src/Socket.c#L909

But in function WebSocket_putdatas() 
https://github.com/eclipse/paho.mqtt.c/blob/7a31c2d9e2d578d6a46ef30c1d63d759a7c9847a/src/WebSocket.c#L809
the argment 'buf0' is not freeable , in function Socket_putdatas(), 'buf0' as a freeable argments been input,  when pw is write complete, will case "free() invalid pointer"

**Comment by aggresss** [comment]
https://github.com/eclipse/paho.mqtt.c/pull/712 may be fix it

**Comment by icraggs** [comment]
Do you have a test which shows the problem?

**Comment by icraggs** [comment]
I think this has been fixed in the WebSocket refactoring.
