### ISSUE TITLE
Four clients, segment error

### ISSUE THREAD

**Issue by guoyanzhang0817** [eclipse-paho/paho.mqtt.c#714]
hi ,
In a main function, I define four clients, three clients, I use callback function, the fourth client, I use receive (). When I run the first three clients alone, there are no errors. When I run the fourth client alone, there is no problem. But I use the four clients together. When the fourth client subscribes to the topic, that is, when the subscribe () function is called, there is a segment error. What is the reason? Because the code is not allowed to upload, it can only be described.

**Comment by guoyanzhang0817** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "MQTTClient.h"
#define ADDRESS     "tcp://localhost:1883"
#define CLIENTID1    "ExampleClientSub1"
#define CLIENTID2    "ExampleClientSub2"
#define CLIENTID3    "ExampleClientSub3"
#define CLIENTID4    "ExampleClientSub4"
#define TOPIC1       "aaa"
#define TOPIC2       "bbb"
#define TOPIC3       "ccc"
#define TOPIC4       "ddd"
#define PAYLOAD     "Hello World!"
#define QOS         1
#define TIMEOUT     10000L
volatile MQTTClient_deliveryToken deliveredtoken;



void delivered(void *context, MQTTClient_deliveryToken dt)
{
    printf("Message with token value %d delivery confirmed\n", dt);
    deliveredtoken = dt;
}
int msgarrvd(void *context, char *topicName, int topicLen, MQTTClient_message *message)
{
    int i;
    char* payloadptr;
    printf("Message arrived\n");
    printf("     topic: %s\n", topicName);
    printf("   message: ");
    payloadptr = message->payload;
    for(i=0; i<message->payloadlen; i++)
    {
        putchar(*payloadptr++);
    }
    putchar('\n');
    MQTTClient_freeMessage(&message);
    MQTTClient_free(topicName);
    return 1;
}
void connlost(void *context, char *cause)
{
    printf("\nConnection lost\n");
    printf("     cause: %s\n", cause);
}

int main(int argc, char* argv[])
{
    MQTTClient client1;
    MQTTClient client2;
    MQTTClient client3;
    MQTTClient client4;
    MQTTClient_connectOptions conn_opts1 = MQTTClient_connectOptions_initializer;
    MQTTClient_connectOptions conn_opts2 = MQTTClient_connectOptions_initializer;
    MQTTClient_connectOptions conn_opts3 = MQTTClient_connectOptions_initializer;
    MQTTClient_connectOptions conn_opts4 = MQTTClient_connectOptions_initializer;
    int rc;
    int ch;
    MQTTClient_create(&client1, ADDRESS, CLIENTID1, MQTTCLIENT_PERSISTENCE_NONE, NULL);
    MQTTClient_create(&client2, ADDRESS, CLIENTID2, MQTTCLIENT_PERSISTENCE_NONE, NULL);
    MQTTClient_create(&client3, ADDRESS, CLIENTID3, MQTTCLIENT_PERSISTENCE_NONE, NULL);
    MQTTClient_create(&client4, ADDRESS, CLIENTID4, MQTTCLIENT_PERSISTENCE_NONE, NULL);
    conn_opts1.keepAliveInterval = 20;
    conn_opts1.cleansession = 1;
    conn_opts2.keepAliveInterval = 20;
    conn_opts2.cleansession = 1;
    conn_opts3.keepAliveInterval = 20;
    conn_opts3.cleansession = 1;
    conn_opts4.keepAliveInterval = 20;
    conn_opts4.cleansession = 1;
//    MQTTClient_setCallbacks(client1, NULL, connlost, msgarrvd, delivered);
    MQTTClient_setCallbacks(client2, NULL, connlost, msgarrvd, delivered);
    MQTTClient_setCallbacks(client3, NULL, connlost, msgarrvd, delivered);
    MQTTClient_setCallbacks(client4, NULL, connlost, msgarrvd, delivered);

    MQTTClient_connect(client1, &conn_opts1);
    MQTTClient_connect(client2, &conn_opts2);
    MQTTClient_connect(client3, &conn_opts3);
    MQTTClient_connect(client4, &conn_opts4);

    MQTTClient_subscribe(client1, TOPIC1, QOS);
    MQTTClient_subscribe(client2, TOPIC2, QOS);
    MQTTClient_subscribe(client3, TOPIC3, QOS);
    MQTTClient_subscribe(client4, TOPIC4, QOS);
    do
    {
        ch = getchar();
    } while(ch!='Q' && ch != 'q');
    MQTTClient_disconnect(client1, 10000);
    MQTTClient_disconnect(client2, 10000);
    MQTTClient_disconnect(client3, 10000);
    MQTTClient_disconnect(client4, 10000);
    MQTTClient_destroy(&client1);
    MQTTClient_destroy(&client2);
    MQTTClient_destroy(&client3);
    MQTTClient_destroy(&client4);
    return rc;
}
-----------------------
like this code, If I don't set the callback function of the client1, as long as I publish the topic, there will be a paragraph error. why?

**Comment by icraggs** [comment]
That code doesn't compile cleanly, did you mis-type it?  You can attach a source file containing the code to the issue if you want to do that.

To help identify the problem you could take a client library trace as described in the readme.

**Comment by guoyanzhang0817** [comment]
ok, I have solved this problem，in function  'msgarrvd'.

**Comment by guoyanzhang0817** [comment]
i return 0,but it must return 1.
