### ISSUE TITLE
If synchronous and asynchronous functions are used together, how can they be compiled? Using GCC test.c-lpaho-mqtt3c-lpaho-mqtt3a-o test?

### ISSUE THREAD

**Issue by guoyanzhang0817** [eclipse-paho/paho.mqtt.c#716]
If synchronous and asynchronous functions are used together, how can they be compiled?
Using gcc test.c-lpaho-mqtt3c-lpaho-mqtt3a -o test?

**Comment by tbeu** [comment]
Did you try it?

**Comment by icraggs** [comment]
That looks about right.  I didn't intend that they should be used together, I haven't tried it, so I don't know if there are any issues.  Did you find any?

**Comment by guoyanzhang0817** [comment]
I can't remember, it seems that I can't compile.
