### ISSUE TITLE
Uninitialized memory causes connection failure

### ISSUE THREAD

**Issue by sasq64** [eclipse-paho/paho.mqtt.c#718]
`SocketBuffer.c:207`
headerlen can be uninitialized and very large at this point.
Discovered by _valgrind_;
```
==8165== Conditional jump or move depends on uninitialised value(s)
==8165==    at 0x290C39: SocketBuffer_getQueuedChar (SocketBuffer.c:207)
==8165==    by 0x28D4CE: SSLSocket_getch (SSLSocket.c:810)
```
This causes the connect to fail initially, but it eventually succeeds after a 30 second delay (which I think happens on the broker).

I did this ugly hack to confirm the problem:
`if(queue->headerlen) > 123456789) queue->headerlen = 0;`
which makes the issue go away.

**Comment by tbeu** [comment]
headerlen should be initialized in SocketBuffer_newDefQ.
