### ISSUE TITLE
Large Payloads over WSS either disconnects or fails PUBACK

### ISSUE THREAD

**Issue by keysight-daryl** [eclipse-paho/paho.mqtt.c#721]
Using paho c++/c 1.3.1 (windows) via async client over WSS to erlio/docker-vernemq:1.9.1 broker we publish messages with payloads > 4000 bytes and subscribe to the same topic.  In a loop on the client we validate arrival of published messages and that the payload of what is received matches what was sent. This works fine for payloads under 4000 bytes however for payloads above this size we have noticed consistent failure of the client to PUBACK and at times being disconnected from the broker.  We do not publish the next message until we have validated receipt of the previous published message subscription and so in theory there should only ever be one message in flight.  Switching to a connection over TCP does not have this issue.  Point of failure is somewhat random in nature but easy to reproduce and will occur within the first few messages for payloads over 4050 bytes and never for payloads under 4000 bytes. Between 4000-4050 bytes it occurs somewhat randomly.  Attached is a broker log of one such failure where the client appears to not have performed the PUBACK.

![mqttIssue](https://user-images.githubusercontent.com/40178586/64202435-20433080-ce5f-11e9-8c7a-e9d37edb0789.PNG)

**Comment by icraggs** [comment]
Do you know, or can you try whether you get the same results against Mosquitto, or the test server in https://github.com/eclipse/paho.mqtt.testing?

**Comment by keysight-daryl** [comment]
our application uses WSS and some custom auth so it might not port so easily around.  We have noticed the issue is less pronounced using WS without SSL requiring larger payloads (around 8500 bytes) to cause trouble.  We have tried to duplicate the issue using the paho.js client without success so it points to this being a bug within paho.c/cpp.  I will see if I can target the test server you mentioned.

**Comment by icraggs** [comment]
Alternatively, if it's easy to reproduce, taking a client library trace of the problem at the default level, as described in the readme, could help.

**Comment by keysight-daryl** [comment]
So same issue occurs against wss://test.mosquitto.org:8081/mqtt.  It works fine for small payloads like 1k bytes but hangs on the ack and never receives the subscribed message for larger (5k) payload sizes.  Attached a screen grab of it failing on that broker...  Which readme describes grabbing a debug trace?  I'll try that next.

![mqttIssueMosquitto](https://user-images.githubusercontent.com/40178586/64292405-56081800-cf38-11e9-996e-2ebf43d9fbea.PNG)

**Comment by keysight-daryl** [comment]
We found that the WS issue was resolved by increasing our maxBufferedMessages to the default 100 but WSS doesn't seem encouraged by bigger buffers.  Using QOS=2 does alter the failure sometimes letting it get 10 messages or so through before disconnecting.  With QOS=1 it usually fails on the first large payload under WSS.

**Comment by keysight-daryl** [comment]
... we are using paho via conan packaging paho.mqtt.cpp -> paho.mqtt.c -> OpenSSL/1.0.2q

one other thing I noticed for windows builds is paho.mqtt.c cannot be built as a static library due to it having some critical initialization logic within DllMain (MQTTAsync.c lines 122-138) where it creates mutexes.  It would be really nice if that logic were moved out of DllMain so it could be used statically on windows.

**Comment by keysight-daryl** [comment]
Think I figured out the trace logging... here is a session where it successfully sent a number of messages before getting the disconnect... 

[paho.0.log](https://github.com/eclipse/paho.mqtt.c/files/3576639/paho.0.log)
[paho.log](https://github.com/eclipse/paho.mqtt.c/files/3576636/paho.log)

**Comment by keysight-daryl** [comment]
any insight on the cause of this? we need to decide internally how to proceed with our large payload project and wss is a requirement.

**Comment by jumoog** [comment]
true i had the same problem

> one other thing I noticed for windows builds is paho.mqtt.c cannot be built as a static library due to it having some critical initialization logic within DllMain (MQTTAsync.c lines 122-138) where it creates mutexes. It would be really nice if that logic were moved out of DllMain so it could be used statically on windows.

paho.js works because Chrome buffers around 128KB per WebSocket connection.

**Comment by keysight-daryl** [comment]
Reading the websocket source code I see it isn't at all thread-safe.  We are using what is supposedly the async client.  Am I missing something here?

**Comment by icraggs** [comment]
Thread safety is at the MQTTAsync.c module level.    The trace error point seems to be:

20190904 174917.644 SSL_read: 2 bytes expected but 0 bytes now received

where an SSL read failed.  I will try a test soon.

**Comment by icraggs** [comment]
I've added some websocket TLS tests to the Travis suite, using some updates to test5.c, in the develop branch.  Test 10 (by index) is the large message test, which can be run individually with this command:

test5 --ws --hostname localhost --client_key test/ssl/client.pem --server_key test/ssl/test-root-ca.crt --test_no 10 --size 10000000 --verbose --count 5

I have not seen any errors so far, when using the Paho test broker as the server on the same machine as the test.  The --size and --count parameters can be used to vary the size of the message used and the number of messages sent and received in the test.

Using WebSockets with this library is noticeably slower than straight TCP, so that could be a factor between them.  Also QoS as you mentioned might need varying.

**Comment by keysight-daryl** [comment]
A colleague of mine also ran some tests of paho.c using the async client directly instead of through the paho.cpp wrapper and he couldn't reproduce the issue either.  Incidentally he is in the same state as the broker.  Is there a similar test using paho.cpp?  is that something you can test? wondering what other conditions could lead to the SSL_read error you found in the logs?

Additionally this isn't running on the same machine as the broker, it is across a proper network with real latency... ie Atlanta <-> California.  Could it be a premature latency timeout somewhere deep in the stack?  It doesn't happen every message but is somewhat random.  Pretty much a guarantee before say 200 large messages have been sent. The larger the payload seems to increase the likelihood.

**Comment by icraggs** [comment]
Does the broker have any administrative messages about the disconnection?  What keepalive value are you using and how long does each message transmission take?  

I'm not sure what using the C++ client layer is going to show - it would just add another layer of complexity.  I was hoping you might be able to use the test program to see if you get the same problem that way.

**Comment by keysight-daryl** [comment]
The test case is it is subscribing to topic 'test/topic' and then publishing messages in a loop to 'test/topic' and expecting to then receive the published message back as subscribed and verifying the received payload matches what was published.  Previously we had a too long keepAlive which also caused disconnects but have fixed that since and are now failing the case of receiving the message back as published.  It doesn't disconnect now but just never receives it back regardless of qos level.  higher qos (2 vs 1) seems to run longer before having this issue.

The broker message is that it sent the message back to the client but never received the PUBACK you can see from the first post in this issue.

I can try your test program and see if the result differ from what my colleague tested.  In his case he was not able to reproduce the issue using purely paho.c but our end app is using paho.cpp and an additional thin layer on top but all through registered callbacks.

**Comment by keysight-daryl** [comment]
cloned develop but am unable to run conanfile as written.  Performing a 'conan install .' followed by 'conan build .' results in this error...

conanfile.py (paho.mqtt.c/1.3.1@None/None): Running build()
ERROR: conanfile.py (paho.mqtt.c/1.3.1@None/None): Error in build() method, line 25
        conan_basic_setup()''')
        ConanException: replace_in_file didn't find pattern 'PROJECT("paho" C)' in 'CMakeLists.txt' file.

it is a bit difficult to setup to run tests since our build environment depends on conan and we have had to fork quite a few packaging changes and a few code changes to paho.c and .cpp to build properly and with our version of OpenSSL etc..  it never seems to work right out of the box for us.  dekstop dev environment is conan on windows and targeting windows, linux, and mac.

**Comment by icraggs** [comment]
I don't suppose this is a broker I could point my tests at myself is it?  I'm trying to see if I can reproduce.  Looking at the logs again, there is a TLS read that fails.  Two thoughts:

1) the broker is timing the session out and closing it due to message transmission taking a longer time than it allows

2) an edge case in the websockets code when a read fails.

I could add some more debug for you to run the tests again if you were able to build (with make for instance).  I haven't used conan myself, the build for conan was contributed.

**Comment by keysight-daryl** [comment]
The make requires a bunch of apt-stuff which I don't have on my windows machine.  Yeah we had to make some significant packaging changes to get it to work within our CI environment that uses conan.  Since most of the packaging is forked for us and even some small bits of code (but nothing that would cause these issues) it does make keeping in sync with latest or to be able to perform testing on paho itself a challenge.  Apples and oranges from here.  Would love it if the included conan recipe 'just worked'.  I could probably send you the changes we had to make to get it to build with conan across all targets.

I think the issue has something to do with a timing/timeout somewhere near the lowest levels of packet transmission within the websocket code.  It doesn't happen with tcp and it happens with both ws and wss with wss being much more sensitive probably due to the larger packets it produces or the additional time it takes to perform the encryptions.  

I experienced the exact same issues using the public mosquitto broker (wss://test.mosquitto.org:8081/mqtt) to be clear it wasn't specific to our broker.

**Comment by keysight-daryl** [comment]
I forked this repo and committed our conan/cmake packaging changes here in case they help...

https://github.com/keysight-daryl/paho.mqtt.c

Internally we consume our internally forked dependencies like OpenSSL but you should be able to just use any public version of those in the recipe the same.

**Comment by icraggs** [comment]
So I've been running tests against test.mosquitto.org, port 8081, secure websockets.   I couldn't even get connected successfully - the websocket upgrade did not work.  (It did work without TLS).  This was because the first socket read failed when attempting the upgrade.  

I've put a fix in for this in the develop branch so now I can connect successfully. Now, when larger messages are sent and received, I see similar issues.   I expect there is another read with the same situation, which is likely to be your problem too.  I will be looking into that.

**Comment by icraggs** [comment]
FYI, the websocket code was a contribution, for which I'm very grateful of course.  I just don't know that part of the code as well as my own.

**Comment by keysight-daryl** [comment]
very glad to hear you have successfully reproduced the issue.  looking forward to a fix and glad to be able to contribute to this great project helping to make it better.

**Comment by keysight-daryl** [comment]
from my quick inspection of the websocket code it does appear to be a likely culprit.  there are just too many places where static global state and thread safety are concerning.  to be honest it looks like it might be ripe for a re-write.

**Comment by icraggs** [comment]
It may take a while for me to fix this depending on the time I have available.  I don't work for IBM any more, so this is a personal project now.

**Comment by keysight-daryl** [comment]
understood... i really appreciate you continuing to support it and i'm absolutely sure the community does as well.

**Comment by stelfrag** [comment]
hi @icraggs thanks for looking into this!! 
if you have any suggestions / tips on how one can approach this maybe I or someone else can jump in and help with a fix

**Comment by keysight-daryl** [comment]
think I might have found at least one bug that could be responsible for this issue...  

WebSocket.c - line 613 - WebSocket_getRawSocketData(...)

1. line 630 - bytes is reassigned from caller bytes requested to bytes actually needed to complete the frame buffer
2. line 639 - attempt to actually read the additional bytes needed from the socket
3. line 693 - BUG - tries to fulfill the number of bytes needed to complete the frame buffer instead of the number of bytes actually requested 

The fix...

1. ++line 617 - size_t bytesRequested = bytes;
2. ++line 689 - bytes = bytesRequested;

**Comment by keysight-daryl** [comment]
Testing with this fix does not appear to resolve this issue entirely but it does seem to get a bit further on average and with larger payloads.

**Comment by keysight-daryl** [comment]
Finally found a fix!  In addition to the above change also change...

WebSocket.c - line 863 - WebSocket_receiveFrame(...)

3. line 863 - rc = TCPSOCKET_INTERRUPTED;

It was flagging the non immediate receipt of the first 2 bytes of a websocket frame as a socket error when this is actually an expected condition when the underlying OpenSSL::SSL_read(...) will return SSL_ERROR_WANT_READ during a websocket renegotiation with its peer.

**Comment by frbouvi** [comment]
I have a maybe similar problem with incoming publish with WSS. It seems that when a frame is already received and is in the 'in_frames' list but with not enough bytes in it, in Websocket_getdata, there is no way to fetch the missing bytes, and there is a huge desync after that.

**Comment by keysight-daryl** [comment]
yeah, the web socket code is super fragile... i wouldn't doubt there are a dozen edge case issues.

**Comment by frbouvi** [comment]
I am hacking the WebSocket_getdata function with some success. It needs to loop but for the moment, one retry is enough for my current test case

**Comment by keysight-daryl** [comment]
doesn't surprise me, that seems the most vulnerable chunk of code that really needs much stronger error handling and retry logic. my fix was just the tip of the iceberg

**Comment by icraggs** [comment]
@frbouvi yes, the case that doesn't work is if the MQTT packet being received is spread across more than one websocket frame.  And if the data isn't all available from the socket to complete the MQTT packet, then the data needs to be stored across TCP reads.

So there's two levels of buffering: one for the websocket frame, and one for the MQTT packet.   Perhaps there won't be case of multiple MQTT packets being contained in one websocket frame, I don't know.

**Comment by frbouvi** [comment]
@icraggs I created pull request #800 that address this issue

**Comment by frbouvi** [comment]
@icraggs your last commit doesn't work for me and create segfault. You missed the fact that realloc can move the data and the value of pointers after calling WebSocket_receiveFrame are not the same than before. rv and the content at the top of the list are not valid anymore.

**Comment by frbouvi** [comment]
@icraggs please consider PR #801

**Comment by icraggs** [comment]
@frbouvi I also have been looking at it.  I've added a proposed fix to the develop branch, which doesn't work in all cases yet.  I'll continue looking at along with your fix too.  Thanks for the PR.

**Comment by frbouvi** [comment]
disregard PR #800, yours is better, but only with #801 ;)

**Comment by icraggs** [comment]
With the help of @frbouvi, I think this is now fixed in the develop branch.  All the commits up to and including https://github.com/eclipse/paho.mqtt.c/commit/7687fae27c42e673a15867c9f8b74a46378f13ec are needed.  If anyone would like to try this out and confirm (or not) that would be really useful.

**Comment by keysight-daryl** [comment]
Would love to try it... should i take the entire branch or just cherry pick those commits or is it possible I just pull the websockets.c/h files and swap those into my local copy?  If possible i'd like to isolate whatever is needed to fix websockets from everything else since our branch has other changes elsewhere.

**Comment by icraggs** [comment]
Just take the latest develop branch - all the fixes are cumulative.  I just mentioned the specific commit to make sure that you included that one which is the latest currently on the develop branch anyway.

The websocket fixes were restricted to WebSocket.c in any case.  If you take that it should work for you.
