### ISSUE TITLE
Receives messages from a non subscribed topic

### ISSUE THREAD

**Issue by ovwagle** [eclipse-paho/paho.mqtt.c#723]
I have an application that is subscribed to topic abc/test/1/1/# but while publishing multiple messages, I figured that my application also receives messages having topic abc/test/1/2/xyz.

**Comment by icraggs** [comment]
Without any further information, I would say that this is likely something to do with the MQTT server rather than the client library.  You could take a client library trace, at the protocol level, as described in the readme.  This might give some useful information.

**Comment by keysight-daryl** [comment]
here is what I learned about mqtt while seeing the same thing happen in my client... so you connected to the broker and subscribed at some point to the other topic and those messages are either qos > 0 and retained meaning when you later reconnect to that broker as the same 'user' it still thinks your subscriptions to those old topics are still required.  Even using cleanSession doesn't always fix it.  You need to also publish the topic with an empty payload to flush it from the broker's retain.  the more and more I use it I am learning how hackish mqtt really is.  the protocol was almost designed to cause these issues.  ultimately it seems the broker retains your client's subscription states between connections and will deliver previously subscribed topics even if you never re-subscribe in the new connections.

**Comment by icraggs** [comment]
The clean session flag, when set to true, deletes the client session state which includes subscriptions. 

Retained messages are not part of the client state, they are meant to supply information that other clients can use too, if allowed or needed.  As such they are not affected by the clean session flag but need to be explicitly or administratively removed.

The server documentation and the MQTT specification describes this behaviour.

**Comment by keysight-daryl** [comment]
right, it is really tricky is what he's trying to say knowing how to actually use it to get the results you actually expect vs the canonical results the broker gives you.  I have seen it where cleanSession however does not actually purge previous client session subscriptions from the broker and it sends them to you anyway usually as soon as you connect, at least once.

**Comment by icraggs** [comment]
If that is really the case, I think the broker is not behaving correctly.

**Comment by icraggs** [comment]
The MQTT server in paho.mqtt.testing behaves as I would expect if you want to compare to that.  I think this is answered by the MQTT specification, but individual servers can have extra behaviour or bugs.
