### ISSUE TITLE
Default keepAlive of 60 fails since most websockets disconnect after 60 sec

### ISSUE THREAD

**Issue by keysight-daryl** [eclipse-paho/paho.mqtt.c#724]
Recommend reducing the default keepAlive to 45sec or less so as not to be marginalized by most webservers that are default configured with a websocket termination after 60 seconds of inactivity. (NGINX, ELB, ...)

**Comment by windbender** [comment]
last paragraph on this page:   http://nginx.org/en/docs/http/websocket.html.   "the connection will be closed if the proxied server does not transmit any data within 60 seconds. "

first paragraph here : https://aws.amazon.com/blogs/aws/elb-idle-timeout-control/
"This time period is known as the idle timeout for the Load Balancer and is set to 60 seconds." 

Lowering the default timeout to a reasonable bit below 60 seconds will improve the "out of the box" experience.  I would suggest 45 seconds, leaving 15 second for packet round trips even on the worst dialup line. :-)

**Comment by icraggs** [comment]
The tricky part of this is not changing the default behaviour for non websockets connections.  This would be a limited change, but it would nevertheless affect existing applications.

**Comment by icraggs** [comment]
We can have another connect options initializer specifically for websockets with a keepalive default of less than 60.

**Comment by wowtah** [comment]
+1 for this suggestion. My client (connecting over websockets to an NGINX instance) kept disconnecting and I had no idea why. Lowering the keepalive to 45s solved my issue.

**Comment by icraggs** [comment]
There are some alternative ws initializers for the connect options structure - I've added some more doc to highlight them:

Suitable default values are set in the following initializers:
 - MQTTAsync_connectOptions_initializer: for MQTT 3.1.1 non-WebSockets
 - MQTTAsync_connectOptions_initializer5: for MQTT 5.0 non-WebSockets
 - MQTTAsync_connectOptions_initializer_ws: for MQTT 3.1.1 WebSockets
 - MQTTAsync_connectOptions_initializer5_ws: for MQTT 5.0 WebSockets
