### ISSUE TITLE
return -1

### ISSUE THREAD

**Issue by guoyanzhang0817** [eclipse-paho/paho.mqtt.c#725]
conn_opts.onSuccess = onConnect;
    conn_opts.onFailure = onConnectFailure;
    conn_opts.keepAliveInterval = 20;
    conn_opts.cleansession = 1;
    conn_opts.automaticReconnect = 4;
    conn_opts.context = client;
    rc = MQTTAsync_connect(client, &conn_opts);
-----------------------
the function 'MQTTAsync_connect' return 0, but 'conn_opts.onFailure' still be run. why?

**Comment by icraggs** [comment]
The completion status in the async API is given by the success/failure callbacks.  The return code only indicates that the request has been successfully started.  This 'asynchronous' behaviour is the reason for the name of the API.

**Comment by guoyanzhang0817** [comment]
MQTTAsync_connect() return 0 indicates that the client has been successfully connected, so onConnect function should be called, but now onConnectFailure function be called. why?

**Comment by guoyanzhang0817** [comment]
> The completion status in the async API is given by the success/failure callbacks. The return code only indicates that the request has been successfully started. This 'asynchronous' behaviour is the reason for the name of the API.

MQTTAsync_connect() return 0 indicates that the client has been successfully connected, so onConnect function should be called, but now onConnectFailure function be called. why?

**Comment by icraggs** [comment]
The MQTTAsync_connect() return of 0 does not indicate that the client has been successfully connected.  It just means that the request has been started.  The asynchronous API is designed not to block.

**Comment by guoyanzhang0817** [comment]
ok，i got it. thanks.
