### ISSUE TITLE
about 'automaticReconnect' issue

### ISSUE THREAD

**Issue by guoyanzhang0817** [eclipse-paho/paho.mqtt.c#727]
I set conn_opts.automaticReconnect is 20.  When I kill the broker process, the subscription client tries to connect, I restart the broker, and see that the client is connected to the broker again, but I post the message, but the client does not receive it. Why?

**There are a lot of problems lately, I am sorry, sorry.**

**Comment by guoyanzhang0817** [comment]
I canceled the 'automaticReconnect' setting and reconnected in the MQTTAsync_connectionLost function, but there was a segmentation error.
---------------------------------------------
void connlost(void *context, char *cause)
{
        printf("connection lost\n");
        MQTTAsync client = (MQTTAsync)context;
        printf("connlost %p\n", client);
        MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
        int rc;
        printf("\nConnection lost\n");
        printf("     cause: %s\n", cause);
        printf("Reconnecting\n");
        conn_opts.keepAliveInterval = 20;
        conn_opts.cleansession = 0;
        if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
        {
                printf("Failed to start connect, return code %d\n", rc);
                finished = 1;
        }
}
-------------------------------------------------------

**Comment by icraggs** [comment]
Reconnecting using the automatic reconnect or in connectionLost will not affect existing subscriptions.  Whether the subscriptions exist after the broker restart depend on the behaviour of the specific broker, if Mosquitto it may not have stored them for instance.  Also the applications need to connect and reconnect non-cleansession otherwise the subscriptions could have been cleaned up.

**Comment by guoyanzhang0817** [comment]
What do you mean not only need to configure the specified broker, but also the client settings do not clean up the callback?

**Comment by yuiopt** [comment]
@guoyanzhang0817 Hi, have you solved this "autoReconnect" problem yet? recently I am using paho.mqtt.c in my project, I found that if the mosquitto was stopped and was restarted several seconds later, the subscribed topics would not work , and when the client reconnected, no one callback is called

**Comment by guoyanzhang0817** [comment]
> @guoyanzhang0817 Hi, have you solved this "autoReconnect" problem yet? recently I am using paho.mqtt.c in my project, I found that if the mosquitto was stopped and was restarted several seconds later, the subscribed topics would not work , and when the client reconnected, no one callback is called

Did you use **MQTTAsync_setConnected**？ The callback of this function is called when the client reconnected.
