### ISSUE TITLE
What is true?

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#728]
I recently noticed that the SSL connect code is testing the int / boolean `verify` flag for the exact value of one(1) to indicate "true":
https://github.com/eclipse/paho.mqtt.c/blob/9f7f45c76c02abee18766ca64c482ba036d0cb2c/src/SSLSocket.c#L749

The documentation for the flag just says:
```
     * Whether to carry out post-connect checks, including that a certificate
     * matches the given host name.
```

So it doesn't indicate that it requires an exact value of 1. I had been assuming the C convention of zero is false, and non-zero indicating 'true'.

Is this used throughout the library? Requiring a 1 for 'true'?

I did just notice, this morning, the definition:
https://github.com/eclipse/paho.mqtt.c/blob/9f7f45c76c02abee18766ca64c482ba036d0cb2c/src/MQTTAsync.h#L1425

**Comment by fpagliughi** [comment]
Ha! Maybe I just got lucky...  For all these years, I've been using an inline conversion function to go from C++ bool to a C int:
```
inline int to_int(bool b) { return b ? (!0) : 0; }
```

https://github.com/eclipse/paho.mqtt.cpp/blob/7fe0c260665d6b51557acdd1dc8f9a1386f1f8f4/src/mqtt/types.h#L167

Turns out, (!0) evaluates to exactly 1. (At least for gcc and clang).

**Comment by icraggs** [comment]
Philosophical question, man!

I should think we should stick to the normal C convention, although as you point out !0 tends to be evaluated to 1, which is why it's often used.

I'd like to see what other instances there before making a final decision.

**Comment by fpagliughi** [comment]
Certainly anything that might expand out to more than two choices in the future can stay as a choice between 0 and 1 for now, but the documentation should state that explicitly.

Things that are straight boolean should probably follow the C convention of allowing anything non-zero being considered true. In that case:
```
else if (verify)
```
or
```
else if (verify != 0)
```
That's my vote. But either way, let me know and I will update the C++ and Rust libraries.

**Comment by icraggs** [comment]
That's the only instance I could find.  I changed it to (verify), so we match the C conventions.
