### ISSUE TITLE
How to apply this project to an embedded system?

### ISSUE THREAD

**Issue by codemaner** [eclipse-paho/paho.mqtt.c#732]
Can this project be used in an embedded system? For example, other 32-bit arm chips.

**Comment by jumoog** [comment]
there is a special version for embedded systems https://github.com/eclipse/paho.mqtt.embedded-c

**Comment by codemaner** [comment]
Thank you------------------ 原始邮件 ------------------
发件人: "Kilian von Pflugk"<notifications@github.com>
发送时间: 2019年9月17日(星期二) 晚上9:59
收件人: "eclipse/paho.mqtt.c"<paho.mqtt.c@noreply.github.com>;
抄送: "codemaner"<1620123313@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [eclipse/paho.mqtt.c] How to apply this project to an embeddedsystem? (#732)



there is a special version for embedded systems https://github.com/eclipse/paho.mqtt.embedded-c
 
&mdash;

**Comment by icraggs** [comment]
Thanks @jumoog
