### ISSUE TITLE
Build fails in MacOS with error: Implicit declaration of function 'RAND_bytes' is invalid in C99

### ISSUE THREAD

**Issue by nlhien** [eclipse-paho/paho.mqtt.c#733]
When I enabled the Macro "**LIBUUID**", the Xcode got failed due to the error "**mqtt.c/src/WebSocket.c:201:3: Implicit declaration of function 'RAND_bytes**' is invalid in C99". After reviewing the source code, I think the root cause is because of the "**<openssl/rand.h>**" only include when the "**LIBUUID**" is not defined.

```
#if defined(LIBUUID)
#include <uuid/uuid.h>
#else /* if defined(USE_LIBUUID) */
#include <limits.h>
#include <stdlib.h>
#include <time.h>

#if defined(OPENSSL)
#include <openssl/rand.h>
#endif /* if defined(OPENSSL) */
... ... ... 
#endif
```

Should we consider to move **#include <openssl/rand.h>** to outside?

**Comment by icraggs** [comment]
I think this has been fixed in the develop branch.

**Comment by nlhien** [comment]
Thanks @icraggs
