### ISSUE TITLE
Building static libraries on linux failes

### ISSUE THREAD

**Issue by kedvsk** [eclipse-paho/paho.mqtt.c#738]
I'm using this:
```
#!/bin/bash
set -e
rm -rf build.paho
mkdir build.paho
cd build.paho
echo "travis build dir $TRAVIS_BUILD_DIR pwd $PWD"
#cmake -DCMAKE_BUILD_TYPE=Debug -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=TRUE ..
cmake -DCMAKE_BUILD_TYPE=Debug -DPAHO_BUILD_STATIC=TRUE -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=TRUE ..
make
...

```
failes with:

CMake Error at src/CMakeLists.txt:95 (ADD_LIBRARY):
  add_library cannot create target "paho-mqtt3c" because another target with
  the same name already exists.  The existing target is a shared library
  created in source directory "/10_data/55_git/paho.mqtt.c/src".  See
  documentation for policy CMP0002 for more details.

CMake Error at src/CMakeLists.txt:96 (ADD_LIBRARY):
  add_library cannot create target "paho-mqtt3a" because another target with
  the same name already exists.  The existing target is a shared library
  created in source directory "/10_data/55_git/paho.mqtt.c/src".  See
  documentation for policy CMP0002 for more details.

CMake Error at src/CMakeLists.txt:101 (INSTALL):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "paho-mqtt3c".
...

**Comment by tbeu** [comment]
Have a look at #730.

**Comment by kedvsk** [comment]
Fixed.

**Comment by tbeu** [comment]
> 
> 
> Fixed.

Hm, which branch?

**Comment by kedvsk** [comment]
I cloned lates version containing the error and changed the two files afterwards by myself.

**Comment by tbeu** [comment]
Which means, it is not yet fixed upstream. I'd rather would leave it open until #730 gets merged and closes this issue automatically.
