### ISSUE TITLE
ConnectionLost not being called when a PINGRESP not received

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#74]
migrated from Bugzilla [#413429](https://bugs.eclipse.org/bugs/show_bug.cgi?id=413429)
status VERIFIED severity _normal_ in component _MQTT-C_ for _---_
Reported in version _v0.5_ on platform _PC_
Assigned to: Ian Craggs

On 2013-07-22 05:56:14 -0400, Ian Craggs wrote:

> When an error condition is caught in the MQTTProtocolClient module, and MQTTProtocol_closeSession is called, the connectionLost callback should be called to tell the application that the connection has been lost.

On 2013-07-22 06:23:18 -0400, Ian Craggs wrote:

> Fix applied.  Now, MQTTProtocol_closeSession calls disconnectInternal which calls connectionLost if necessary.

**Comment by icraggs** [comment]
Closing.  This was verified on bugzilla.
