### ISSUE TITLE
ssl connection error, probably because def_queue->headerlen is uninitialized memory

### ISSUE THREAD

**Issue by imi0** [eclipse-paho/paho.mqtt.c#740]
I got strange issues when trying to connect to some servers via SSL. It seems to work in release mode, but fails when compiling with cl.exe under Debug.

After some hours of investigation, I think I nailed the issue:

The function SocketBuffer_newDefQ does not initialize the def_queue->headerlen field (it zeroes all the other fields, but not this one..)
Later, the def_queue is inserted into queues with the bogus headerlen and later again, the SocketBuffer_getQueuedChar checks for "if (queue->index < queue->headerlen)"

Since the MS compiler reliably initializes all memory returned by malloc with 0xCDCDCDCD, this headerlen was bigger than the index and it jumped into the if-clause.

Fix for me: Just change line in SocketBuffer_newDefQ from

`def_queue->buflen = def_queue->datalen = 0;`

into 

`def_queue->buflen = def_queue->datalen = def_queue->headerlen = 0;`

**Comment by jumoog** [comment]
#739
