### ISSUE TITLE
Persistence directory naming with no Client ID

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#746]
When I don't need a persistent session on the broker, I typically use a blank/empty Client ID string, and let the broker assign a temporary ID.

In that case, the C lib uses the empty string to come up with the name of the directory for the default file persistence, and will assign it something like "-localhost-1883".

Having a name that starts with a dash is problematic in that CLI tools will interpret it as a command switch, like:
```
$ cd -localhost-1883/
bash: cd: -l: invalid option
```

The other problem is that multiple different clients might try to share the same persistence file(s). That could be leading to #745.

I really should not be using file persistence when I don't need it, but as a default, it often slips in. Some of this can/should be dealt with at the app/system level, but maybe the library can figure out some naming to help?

**Comment by icraggs** [comment]
So this and #745 could be the same thing?

**Comment by fpagliughi** [comment]
Yes, I believe that they’re related. I think this issue can cause #745, but I don’t know if it’s the only thing that can cause it. Plus I thought this was distinct enough to warrant a separate discussion as to the best path to take. Apologies for the confusion.

**Comment by fpagliughi** [comment]
For this issue, I was wondering if there’s ever a case where a client that is using a blank Client ID could ever want or need persistence? Doesn’t the lack of a Client ID indicate a transient client that wouldn’t use persistent session. That would clearly be the case if clean session/ start is true, but what if not?

That would be weird in MQTT 3.x, but now that the client can retrieve its assigned ID from the broker in MQTT v5, can it reconnect using that “temporary” ID and use a persistent session with that name?

**Comment by keysight-daryl** [comment]
Our client would like a sort of 'single-session' behavior where no matter the broker url or client id all persistence is always going to and coming from a single folder on disk.  In other words no matter the broker the same persistence messages are in the session.

**Comment by icraggs** [comment]
@fpagliughi I think the answer to your MQTT 5.0 question is yes, the client can reconnect using the server assigned client id.  The standard says that the server must treat the client as if it had sent the server-assigned client id.  So there should be no difference in behaviour between clients with server assigned clientids and those with self-assigned.

**Comment by icraggs** [comment]
@keysight-daryl I'm going to open another issue for that.

**Comment by keysight-daryl** [comment]
Great idea

**Comment by icraggs** [comment]
I've been thinking about this some more.  The only time persistence is useful is when the application is destroyed completely, and then recreated.  You don't need disk persistence to cope with network failures - the in memory cache will take care of that.

So for MQTT 5.0 assigned client ids, the application would need to remember the clientid it had been assigned when it next started up.  

1. If using MQTT 3.1.1, the assigned id is not returned to the application.  So I think the client create should fail if a 0-length clientid is used with persistence.  

2. For MQTT 5.0 we could by default go the same route.  That sounds like the safest.

3. For MQTT 5.0, optionally (you have to switch it on) for the persistence, we could assign a 'clientid' something like 'paho-mqtt-50-0-length-uuid' and then store the real assigned clientid in the directory.  Calling create with the assigned clientid would cause the directories to be searched for the matching one.  The directory _could_ then be renamed to use the real clientid for further use.

We could implement 1 and 2 for 1.3.3, leaving 3 or a variant of it, for a later release.

**Comment by keysight-daryl** [comment]
The issue with the in memory cache is it can quickly deplete the process heap and crash.  I think persisting to the persistence layer when enabled is the best canonical approach and unloading those entries from the in memory cache until they are able to be safely sent.  This also supports better runtime memory management leveraging the persistence layer to offload these messages and providing a better guarantee of them persisting in the event the client crashes.

**Comment by fpagliughi** [comment]
Well, certainly the application should be able to decide the best persistence strategy for its use (in-memory vs file-based vs user strategy).

This GitHub issue is for a more subtle, specific problem. How to handle the situation when the application doesn't specify a Client ID (i.e. a blank ID). 

At the moment, for file-based persistence, the application generates a directory named "ClientID-host-port". If, say, a publisher doesn't care about a persistent session, it may be more common to omit the client ID. I've done this a lot in the past, but now that MQTT v5 allows you to get the server-generated ID, then this will likely become more common in general.

At the moment, for file-based persistence, a blank ID causes the library to create a subdirectory named "-host-port". That creates two problems:
1. This is difficult to deal with at the OS layer, since the leading dash makes most CLI tools think you're specifying a command-line option.
2. If two clients start with the same CWD, they clash, both attempting to access the same persistence directory.

But the thing to consider is that a client that does not use a persistent sever session (clean_start=false) probably does not need out-of-process client persistence. I should have made this more obvious in my initial post.

But for the three solutions posted by @icraggs, maybe we consider a fourth?

4. Maybe if the client doesn't specify a client ID or persistent session, then they don't get file persistence?  

I've been trying to think of reasons why that might not be a viable solution for that specific case.

**Comment by icraggs** [comment]
@fpagliughi 4. is like 1 and 2 but carrying on rather than throwing an error.  In that case, the developer could naturally expect that there is persistence, because they called for it, and it is working, so we would be 'failing' silently.  They might only realize when the application restarts and there are no messages to restore.

I would have thought it would be better to let the developer know what is going on.  Then they would then have to change the program to specify no persistence at create time.

**Comment by icraggs** [comment]
P.S.  Also, having persistence in this case is a valid use case (but not necessarily straightforward to implement) for MQTT 5.0, so if we went the 4 route but added the persistence option in some later release, we would silently be changing the behaviour.

**Comment by keysight-daryl** [comment]
In our use case we don't have the clientId or the mqtt broker url (both used to determine the persistence folder name) during the create call yet we still need the messages after that to persist.  But in our use case the 'single-session' concept also applies to which you don't really need a unique name for your persistence folder as all clients all brokers all runtimes regardless should pull from the same persist store.

**Comment by icraggs** [comment]
@keysight-daryl as Frank says, this issue is specifically for the case where the application is sending a 0-length clientid to the MQTT broker in the connect packet, as allowed by the MQTT protocol.  In your scenario, you don't know the clientid at create time necessarily, but you do at connect time as a result of a separate HTTP auth exchange.  Your scenario is covered in issue #869

**Comment by keysight-daryl** [comment]
Right...

**Comment by icraggs** [comment]
I've added a fix for cases 1 and 2.  I'm a bit nervous that some applications will meet an error - but it's better that it's known about, I guess.

**Comment by icraggs** [comment]
I've opened another issue #964, specifically for the MQTT 5.0 enhanced behaviour.
