### ISSUE TITLE
load certificate with ssl

### ISSUE THREAD

**Issue by Peney** [eclipse-paho/paho.mqtt.c#747]
how to use MQTTClient_SSLOptions? i donot know which param are needed ,i used keyStore to load server-certificate,trustStore to load root-certificate,privateKey to load server-key,and set enableServerCertAuth to 1,but always return General SSlengine problem,and also how to set the client?

**Comment by icraggs** [comment]
There are SSL tests in the test suite which show how these parameters can be used, and you can also try them out with the sample command line programs, paho_cs_sub and paho_cs_pub.
