### ISSUE TITLE
multiple simultaneously running mqtt clients occasionally losing connection (except with MAXIMUM trace level)

### ISSUE THREAD

**Issue by jkhsjdhjs** [eclipse-paho/paho.mqtt.c#749]
I have a C application that runs five MQTTAsync clients simultaneously.
Occasionally (once every few minutes) at least one of those clients loses connection (cause: `null`).
And sometimes the deliveryComplete callback is called with a random number (seems to be in the range `0..65535`) before the client loses the connection.

A trace log where one can see the clients `mqtt2` and `mqtt3` disconnecting can be found here: https://gist.github.com/jkhsjdhjs/45cfe52f52f32b900b69e91dc4bb4d23

In line 313 and 465 client `mqtt3` calls the deliveryComplete callback with very high message ids.
In line 559 the message `Bad MQTT packet` is shown for `mqtt3`.
In line 580 `mqtt3` sends the disconnect message.

In line 679 `mqtt2` receives a PUBREL for a very high message id, the matching PUBCOMP for this message id is send in line 691.
In line 734 the message `Bad MQTT packet` is shown for `mqtt2`.
In line 767 `mqtt2` sends the disconnect message.

The interesting thing is that none of this happens when I set the trace level to `MAXIMUM`. No bad packets, no high message ids and no disconnects. On all lower trace levels and when not tracing at all it does occur.

So what is the difference between the `MAXIMUM` trace level and all others? And what could be causing these disconnects?

**Comment by icraggs** [comment]
I think it will be a matter of timing - maximum trace level altering the timing of events sufficiently that the problem is not exposed.

Are you using websockets?

**Comment by jkhsjdhjs** [comment]
I'm using SSL/TLS with TCP.

**Comment by icraggs** [comment]
I'm interested in looking at this if you still are.  If you have an application I can run that might be the easiest way.  What OS are you using?  

There are changes that have gone in to the develop branch since the last release which could have some effect, although I don't propose that any in particular would fix this.

**Comment by jkhsjdhjs** [comment]
I was running it on Ubuntu 14.04 LTS.
I used this library to implement a specification at work. A few months after I first experienced this issue I had to update my implementation to support a new version of the specification.
After changing parts of my code I no longer experienced the issue I described here.
Since I'm the only one who ever experienced an issue like this with this library the issue was probably caused by my code or maybe a library on my system (since ubuntu 14.04 is pretty outdated).
Anyways, I can't reproduce it anymore, so you can close this issue if you want.

**Comment by icraggs** [comment]
Ok, thanks for letting me know.
