### ISSUE TITLE
Can we safely use LinkedList as a standalone list implementation?

### ISSUE THREAD

**Issue by abforce** [eclipse-paho/paho.mqtt.c#752]
Since it depends on a custom heap-tracking malloc, I'm curious whether it's safe to use it somewhere else?

**Comment by tbeu** [comment]
You might give [utlist](https://troydhanson.github.io/uthash/utlist.html) a try.

**Comment by icraggs** [comment]
Is it safe?  It depends on your use.  I wrote it because I wanted to minimize the external dependencies of this library - it was not meant to be used separately.  You are free to use it, but there would be no support except when used as part of the Paho C client.
