### ISSUE TITLE
crash when one thread socketbuffer_getWrite and another thread socket_getReadySocket

### ISSUE THREAD

**Issue by look2019** [eclipse-paho/paho.mqtt.c#754]
when I publish message to broke,network is disconnected at this time.using v1.3.0
the program crash,use gdb to debug core file,
one thread In function socketbuffer_getWrite(),another thread in function socket_getReadySocket(),like this:
![image](https://user-images.githubusercontent.com/52964124/68016385-70a80480-fccf-11e9-9070-4bbbdb03a9d0.png)

**Comment by look2019** [comment]
I find that Socket_getReadySocket() use socket_mutex,but socketbuffer_getWrite() use mqttclient_mutex.Not sure if that's the reason.

**Comment by icraggs** [comment]
We'll need more information than that.  A trace at normal level as described in the README could help.

**Comment by keysight-daryl** [comment]
it does look like the reason, nice work finding this

**Comment by rbiggers** [comment]
I was having a very similar issue. I would try to publish a message and it would immediately return disconnected. Turns out it was a dumb mistake on my part. I was using the async client and trying to publish directly after calling connect, so therefore I had not finished connecting before trying to publish hence the reason code of disconnected. So please make sure you are connected to the broker before you try to publish.

**Comment by zwnich** [comment]
@icraggs When using a persistence, isn't it expected that we should be able to publish messages without being connected to the broker? The docs state pretty unequivocally that this should be the case:
https://www.eclipse.org/paho/files/mqttdoc/MQTTAsync/html/offline_publish.html

We've been using Paho for about a year and a half now for an edge application that relies on cellular connectivity, which can be erratic at best, and it works most of the time. I have seen strange issues regarding persistence recently, but I'll write my own issue so as not to derail this one.

**Comment by icraggs** [comment]
I added a fix to lock the socket_mutex too.  On my previous comment I was thinking about the MQTTAsync API.
