### ISSUE TITLE
Modifying the system time causes PINGREQ packet to stop being sent.

### ISSUE THREAD

**Issue by Liu2Mao** [eclipse-paho/paho.mqtt.c#758]
Modifying the system time causes PINGREQ packet to stop being sent.

**Comment by icraggs** [comment]
What OS are you working with?  And which version of the library?  Thanks.

**Comment by Liu2Mao** [comment]
> What OS are you working with?  And which version of the library?  Thanks.

Thanks for your response.
The OS is ubuntu18.04 and the version of library is 13.04.

I know why this happened:
when the system time is adjusted, all calls to the function 'double difftime(time_t time1, time_t time2)' may return a negative number for a long while. So the program judges that it is not time to send the PINGREQ packet. For some reason, my system time is frequently modified actively, so I found this problem. I'm not quite sure if this is a problem. After all, usually the system time is not adjusted frequently.

change 'difftime(time1, time2) to 'fabs(difftime(time1, time2))' can solve the problem.  Of course, You should have a better way.

**Comment by icraggs** [comment]
Thanks.  It should work.  It sounds like difftime should be replaced with the functions in MQTTAsync_elapsed() which are intended to avoid this problem.

**Comment by icraggs** [comment]
I've put a fix into the develop branch.
