### ISSUE TITLE
Question - How to refresh client command queue after custom persistence layer purges oldest messages

### ISSUE THREAD

**Issue by keysight-daryl** [eclipse-paho/paho.mqtt.c#759]
We had to implement our own disk persistence layer that does two things a little differently.
 1. AES encryption on all persisted payloads
 2. Rotating message store (purging oldest messages once it reaches maxBufferedMessages)

So #1 works fine, no issues.  Problem now is in #2 right before we perform a publish we call our persistence purge function which identifies the oldest messages and removes them from disk and the list of keys it maintains for the client. Once it finishes purging the oldest messages it needs a way to tell the client to refresh it's command queue with the new set of keys, ideally via the abstraction of async_client.cpp.  What is the recommended approach here?  The best I can come up with is in the event it actually needs to purge some of these messages to first fully disconnect and shutdown the existing client, destroy the instance, then do it's disk cleanup of keys, then fire up a new async client and try to reconnect, and continue to perform the original publish.

I'd hate to go through all that if there is an easier way to handle this sort of message store cleanup and continue without having to reinstance the client.

**Comment by icraggs** [comment]
The best way to achieve this, I think, would be to add an option to the C client API to purge oldest rather than newest messages when the limit is reached.   I think that would be a common use case.  Then your persistence layer would have to do less work.  What do you think?

**Comment by windbender** [comment]
I'll just jump in here with some comments.

Different uses cases my have different criteria by which they decide which messages they want to keep and which messages must be dropped.  SO far we basically have "drop oldest" and "drop newest".  

Another might be if one were collecting messages in a sampling fashion and then the persistence store became "full",  the ideal system would be to decimate the messages in the store such that one still has a reasonably evenly distribution of messages over time once a connection reoccurs.

I could imagine a system by which messages are ranked via importance(priority) and the least important messages are dropped.  Priority could be monotonically increasing to achieve "drop oldest".  Monotonically decreasing to achieve "drop newest".  And one could assign a random number to achieve a decimation system.  I could also imagine systems which some particularly important messages get a very high range (but still random) while less important messages get a much lower, but still random range.   In this way all the low importance messages would get deleted prior to the high importance messages.

The hard part here is that MQTT doesn't really allow us to publish messages with an attached "persistence priority".  It might be interesting to evaluate an overloaded "packet identifier" as a means to achieve this in V3.1.1.   In version 5 it might be possible to use a Property to indicate priority.

**Comment by keysight-daryl** [comment]
So is there currently a paho client api to do this or would I have to write one?  Currently I have written our own persistence behavior by overriding the paho c++ persistence class.  We properly delete the oldest files from the persist folder on disk however we are not sure the right way to update the instantiated client so that it refreshes it's internal command queue to account for the new set of keys.

**Comment by keysight-daryl** [comment]
i agree it would be very valuable in general for the paho client api itself to support some form of persistence purge with options of either purging the oldest messages to assure it never hits the current maxMessages setting.  I think the easiest way to expose this is to just add a boolean option to persistRotation default to true which automatically calls the persistence layer remove functions whenever it hits the maxMessages limit.

**Comment by icraggs** [comment]
Yes, I could imagine use cases for more than drop oldest/first scenarios.   In version 5 you certainly could use a property to indicate priority or other values.

At the moment, it comes down to time available (for me).  The 'drop oldest' scenario would I think cover most use cases and be less work.  Adding a persistence management API would be substantially more work - documentation and tests too.  It's a question of best bang for the buck.

If someone wants to contribute a persistence API (along with doc and tests) then great! Otherwise there will be a few higher priorities for me.

**Comment by icraggs** [comment]
Added a deleteOldestMessages switch to the createOptions #441

**Comment by keysight-daryl** [comment]
Woot!
