### ISSUE TITLE
Using MQTT directly on Eclipse

### ISSUE THREAD

**Issue by saahilshroff** [eclipse-paho/paho.mqtt.c#760]
Hi.
I am unable to find any resources that suggests that I can directly run a MQTT code on Eclipse, not through other applications(eg: PAHO)
If there are any, it would be of great help if I can get the link/documentation for it.
TIA!

**Comment by icraggs** [comment]
If you mean the Eclipse IDE, then the Paho Java client is probably the best option. https://github.com/eclipse/paho.mqtt.java
