### ISSUE TITLE
Problem in compiling MQTTClient

### ISSUE THREAD

**Issue by fatimahkj** [eclipse-paho/paho.mqtt.c#762]
Hi, 

I got a problem when I compile MQTTClient.c  which says(.text+0x5a71): undefined reference to" 
 ". How to avoid such errors. 

Also, Which c code has the main function?

P.S. I'm using Ubuntu 18.04.2 LTS

![Screenshot from 2019-11-21 18-04-27](https://user-images.githubusercontent.com/47563480/69365060-6e601700-0c8b-11ea-990b-ae0c1db5bf66.png)

Thanks for your help

**Comment by keysight-daryl** [comment]
paho.mqtt.c is a library not an application.  it appears you are trying to compile just one file alone of the many required for this library to function as an application.  to build this library properly you will need to compile the entire project with all necessary options and dependencies using cmake.

**Comment by fatimahkj** [comment]
Hi, 

I manage to compile using make. However, I tried to connect with a simple example to subscribe as the attached picture. 
However, It says failed to connect

![Screenshot from 2019-11-25 16-41-22](https://user-images.githubusercontent.com/47563480/69559820-90ff7200-0fa2-11ea-8c6b-d1e5aa35419f.png)



this is the address I used

![Screenshot from 2019-11-25 16-37-47](https://user-images.githubusercontent.com/47563480/69559841-9bba0700-0fa2-11ea-9157-0f1589bda1ef.png)


Thanks for your reply.

**Comment by icraggs** [comment]
m2m.eclipse.org is an old address.  It is now mqtt.eclipse.org.  I believe the latest source has removed all references to m2m.eclipse.org.

**Comment by fatimahkj** [comment]
Thanks, Ian this example works. I tried to compile another example put I got the same problem as undefined function.

![Screenshot from 2019-11-26 11-00-43](https://user-images.githubusercontent.com/47563480/69624279-4f230a00-103c-11ea-8e8a-e060cc76849d.png)

also, can I compile sample encrypted messages using TLS?


Many thanks for your help and support

**Comment by styfstr** [comment]
You should add the path of libpaho-mqtt3c

**Comment by fatimahkj** [comment]
> You should add the path of libpaho-mqtt3c

Unfortunately, it didn't solve the problem 

![Screenshot from 2019-11-27 16-42-21](https://user-images.githubusercontent.com/47563480/69742782-3c403080-1135-11ea-8228-4f90b86c8e28.png)

**Comment by styfstr** [comment]
You also need to include the header path. just as
cc -I/home/include 
cc -L/home/lib -lname

-I is the head patch
-L is the lib patch

You may have got the parameters wrong

**Comment by icraggs** [comment]
The Makefile supplied builds the sample applications as well as the libraries, so you can use those as examples of command line parameters.

**Comment by icraggs** [comment]
I'm going to close this for now.
