### ISSUE TITLE
MQTTAsync_connectionLost sometimes doesn't callback after connected and then network broken

### ISSUE THREAD

**Issue by gyh007** [eclipse-paho/paho.mqtt.c#763]
Hi, thank you for your great work to develop this mqtt client.

i use client version 1.3.1 and async mode.

i call `MQTTAsync_setCallbacks` to set `MQTTAsync_connectionLost` callback at first, and then call `MQTTAsync_connect` connect to broker. it works normally.
i did some network broken test, i always connected to mqtt broker and then shutdown the network, at most time `MQTTAsync_connectionLost`callback first and then callback `connect onFailure`. but sometimes the `MQTTAsync_connectionLost` callback didsn't callback, `connect onFailure` callback normally.is there a bug?

**Comment by icraggs** [comment]
The connectionLost callback will only be called if the connection was previously connected.  The onFailure callback will always be called if the connect API call fails.  This could be the difference.

**Comment by icraggs** [comment]
A library trace would be needed for further investigation.
