### ISSUE TITLE
WebSocket connection fails when WebSocket Upgrade response is large

### ISSUE THREAD

**Issue by zod** [eclipse-paho/paho.mqtt.c#770]
If using MQTT-over-WebSocket paho fails to keep a connection to the server if the WebSocket upgrade response is larger than 500 bytes.

WebSocket_upgrade reads up to 500 bytes, if the header is larger than this size the remaining bytes are kept in the socket buffer and are interpreted as WebSocket packets (which usually fails) and paho decides to close the connection.

This can be reproduced by launching a local broker and forwarding the connection with `websocat --server-header='X: XXX' ws-l:127.0.0.1:8080 tcp:localhost:1883` (replace XXX with a large string of ~500 bytes) and then connecting using `paho_cs_sub --connection ws://localhost:8081 --topic test`

**Comment by keysight-daryl** [comment]
Good catch... sounds like another edge case of the problems we are having with large packets over websockets.

**Comment by icraggs** [comment]
Is this an actual use case, or a test?

**Comment by keysight-daryl** [comment]
In my case it is an actual use case as we have message payloads over 5k being pushed around and we need secure web sockets.

**Comment by zod** [comment]
I think it isn't releated to large payloads because the WebSocket_upgrade function is only used when establishing the connection.

For me it's an actual use case because the HTTP server which replies to the upgrade request sends a large response.

**Comment by icraggs** [comment]
ok, I'll look at this after the general payload issues.

**Comment by icraggs** [comment]
So one straightforward change, increasing the 500 amount in the line:

read_buf = WebSocket_getRawSocketData( net, 500u, &rcv );

in WebSocket.c allows the upgrade to work.   I don't remember how the upgrade request is supposed to terminate properly so I'll look into that.

**Comment by keysight-daryl** [comment]
i'm thinking to just swap out our websocket.c with the latest dev version probably next monday to give these changes a moment to cool.  Is WebSocket.c the only file that was changed through all the work done to improve websockets or am I missing something else?

**Comment by icraggs** [comment]
@zod Is there a larger maximum size that would be appropriate? 1024 for instance?  It seems unlikely the response would be arbitrarily long.  It could be of course, I'm just not seeing the usefulness of that.

**Comment by zod** [comment]
I think it's okay to increase it to 1024, but it should be ensured that the entire http header is read and fail if it's not the case. Otherwise it causes this hard do debug problem because the connections seems to be established but fails to transmit data.

**Comment by icraggs** [comment]
I've increased the max size to 1024, and a check that the complete response is read.
