### ISSUE TITLE
Error compile

### ISSUE THREAD

**Issue by ardiantovn** [eclipse-paho/paho.mqtt.c#772]
I downloaded mqtt-paho-source code v 1.3.1 [https://github.com/eclipse/paho.mqtt.c/archive/v1.3.1.zip].

I get an error like the following picture when compiling.
![errormqtt](https://user-images.githubusercontent.com/16162415/70206840-5e503900-175b-11ea-8e2a-aa99c9f86b69.PNG)

How to resolve this error?

**Comment by icraggs** [comment]
Did you try with the CMake option list that is in the Appveyor configuration?

What operating system version are you using?

**Comment by ardiantovn** [comment]
I am sorry, what is Appveyor configuration?

I am using Windows 10.

**Comment by icraggs** [comment]
The appveyor configuration is in the appveyor.yml file.  I use the cbuild.bat file on Windows as an easy way to build.  According to the source file WebSocket.c line 51, if WIN32 or WIN64 are defined, this function will also be defined.

**Comment by icraggs** [comment]
This looks like an environment issue - the correct Windows settings need to be made, such as _WIN32
