### ISSUE TITLE
Segmentation Fault after updating to 1.3.1 from 1.0

### ISSUE THREAD

**Issue by FerozeMohamed** [eclipse-paho/paho.mqtt.c#773]
Hi we have been using the PAHO MQTT C for about 2+ years and never updated the PAHO from the initial 1.0 release. We were facing some Socket Errors and hence upgraded the PAHO to the latest version 1.3.1.

Immediately after updating the PAHHO libraries to 1.3.1 on our Yocto Linux, we are have the Segmentation Fault on all our processes that use PAHO.

the GDB trace is as below:

```
Thread 2 "MyModule" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 2501]
0x4d54514c in ?? ()
(gdb) bt
#0  0x4d54514c in ?? ()
#1  0x76f1ae94 in MQTTAsync_processCommand () from /usr/lib/libpaho-mqtt3a.so.1
#2  0x76f1bad4 in MQTTAsync_sendThread () from /usr/lib/libpaho-mqtt3a.so.1
#3  0x76ed7388 in ?? () from /lib/libpthread.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

```
1.3.1 : seg fault
1.3.0 : seg fault
1.2.1 : no seg fault
1.2.0 : no seg fault
```

Please Help.

**Comment by icraggs** [comment]
If you take a client library trace as described in the readme, this could help.

**Comment by icraggs** [comment]
Or provide a simple test program if you can.  1.3.0 contained support for MQTT V5, so some substantial changes going on.

**Comment by icraggs** [comment]
No response.

**Comment by fpagliughi** [comment]
Oops, sorry. Just saw this one as it was closed. But I wonder if it isn't related to #745.

**Comment by icraggs** [comment]
As Frank suggests, perhaps removing the persistence directory might help?
