### ISSUE TITLE
Blocked call MQTTClient_publishMessage when publish large Data

### ISSUE THREAD

**Issue by choujayyl** [eclipse-paho/paho.mqtt.c#774]
paho.mqtt.c version:1.3.0

```
/* If the packet was partially written to the socket, wait for it to complete.
* However, if the client is disconnected during this time and qos is not 0, still return success, as
* the packet has already been written to persistence and assigned a message id so will
* be sent when the client next connects.
*/
if (rc == TCPSOCKET_INTERRUPTED)
{
while (m->c->connected == 1 && SocketBuffer_getWrite(m->c->net.socket))
{
printf("DEBUG7:rc:,%d \n",rc);
Thread_unlock_mutex(mqttclient_mutex);
MQTTClient_yield();
Thread_lock_mutex(mqttclient_mutex);
printf("DEBUG8:rc:,%d \n",rc);
}
rc = (qos > 0 || m->c->connected == 1) ? MQTTCLIENT_SUCCESS : MQTTCLIENT_FAILURE;
}
```

keeping blocked here

**Comment by icraggs** [comment]
Yes - the MQTTClient API is blocking.  It will wait until the publish is complete.  The MQTTAsync API is non-blocking.

**Comment by choujayyl** [comment]
No，It keeping blocked.I use wireshark grap tcp packages,It publish not complete,the broker receive incomplete message.

**Comment by icraggs** [comment]
Do you have a test which shows the problem?  What broker are you using?  Is it local or remote - does it behave differently if the broker is local or remote?  Are you using TLS or WebSockets?  Can you get a trace as described in the README?

**Comment by icraggs** [comment]
Need more information.

**Comment by svermigo** [comment]
Hello, I have observed similar issue on our devices. 
We are connected to microsoft iothub platform. It seems we have stucked MQTTClient_publishMessage() as well .. can you please have a look on the debug logs?
Thank you!

[084821.log](https://github.com/eclipse/paho.mqtt.c/files/4573464/084821.log)
[092735.log](https://github.com/eclipse/paho.mqtt.c/files/4573465/092735.log)
