### ISSUE TITLE
MQTTAsync_connect in second thread fails with  code : -1 : TCP connect completion failure

### ISSUE THREAD

**Issue by vortex314** [eclipse-paho/paho.mqtt.c#775]
**Describe the bug**
I'm trying to develop an UDP to MQTT gateway on Linux.
Each UDP connection should create a new Paho MQTT client in a different thread of the gateway.
The first UDP connection establishes succesfully a connection to the broker ( mosquitto on raspberry pi), the second thread for another UDP origin fails with error message => TCP connect completion failure 

20191217 230740.925 CONNECT sent but MQTTPacket_Factory has returned SOCKET_ERROR

**To Reproduce**
logging at maximum level : 
https://github.com/vortex314/udp2mqtt/blob/master/pahomaximum.log
**Expected behavior**
I would expect that the second connect  can also be established and that the paho.mqtt.c is fully multi-threaded

** Environment (please complete the following information):**
 - OS: Linux
 - Version Linux pcpav2 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by icraggs** [comment]
There are tests which are multi-threaded and work - I don't see a particular difference here.  Does the broker have any log messages?

**Comment by vortex314** [comment]
Hi Ian, I expected as much that it would be multi-threading. So far my own investigatiosn didn't result in much. Hereby the mosquitto server logs. Feel free to suggest tests I can do. 
There are 2 clientId's : 192.168.0.237@pcpav2 and  192.168.0.195@pcpav2.
It looks like the second MQTT CONNECT never arrives at the broker. 
============================== failing part in logs ===========
1576693291: Socket error on client <unknown>, disconnecting.
1576693291: New connection from 127.0.0.1 on port 1883.
1576693291: Received SUBSCRIBE from 192.168.0.237@pcpav2
1576693291: 	dst/ESP82-10027/# (QoS 0)
1576693291: 192.168.0.237@pcpav2 0 dst/ESP82-10027/#
1576693291: Sending SUBACK to 192.168.0.237@pcpav2
1576693291: Socket error on client <unknown>, disconnecting.
================== rest of logs =============


1576693181: mosquitto version 1.4.15 terminating
1576693266: mosquitto version 1.4.15 (build date Tue, 18 Jun 2019 11:42:22 -0300) starting
1576693266: Config loaded from /etc/mosquitto/mosquitto.conf.
1576693266: Opening ipv4 listen socket on port 1883.
1576693266: Opening ipv6 listen socket on port 1883.
1576693290: New connection from 127.0.0.1 on port 1883.
1576693290: New client connected from 127.0.0.1 as 192.168.0.237@pcpav2 (c1, k20).
1576693290: Sending CONNACK to 192.168.0.237@pcpav2 (0, 0)
1576693290: Received SUBSCRIBE from 192.168.0.237@pcpav2
1576693290: 	dst/192.168.0.237@pcpav2/# (QoS 0)
1576693290: 192.168.0.237@pcpav2 0 dst/192.168.0.237@pcpav2/#
1576693290: Sending SUBACK to 192.168.0.237@pcpav2
1576693291: New connection from 127.0.0.1 on port 1883.
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m2, 'src/192.168.0.237@pcpav2/udp2mqtt/alive', ... (4 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 2)
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m3, 'src/192.168.0.237@pcpav2/udp2mqtt/upTime', ... (1 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 3)
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m4, 'src/192.168.0.237@pcpav2/udp2mqtt/device', ... (20 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 4)
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m5, 'dst/ESP82-10027/system/loopback', ... (4 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 5)
1576693291: Socket error on client <unknown>, disconnecting.
1576693291: New connection from 127.0.0.1 on port 1883.
1576693291: Received SUBSCRIBE from 192.168.0.237@pcpav2
1576693291: 	dst/ESP82-10027/# (QoS 0)
1576693291: 192.168.0.237@pcpav2 0 dst/ESP82-10027/#
1576693291: Sending SUBACK to 192.168.0.237@pcpav2
1576693291: Socket error on client <unknown>, disconnecting.
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m7, 'dst/ESP82-10027/system/loopback', ... (4 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 7)
1576693291: Sending PUBLISH to 192.168.0.237@pcpav2 (d0, q0, r0, m0, 'dst/ESP82-10027/system/loopback', ... (4 bytes))
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m8, 'src/ESP82-10027/system/alive', ... (4 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 8)
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m9, 'src/ESP82-10027/system/alive', ... (4 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 9)
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m10, 'src/ESP82-10027/system/alive', ... (4 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 10)
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m11, 'src/ESP82-10027/system/alive', ... (4 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 11)
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m12, 'src/ESP82-10027/system/alive', ... (4 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 12)
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m13, 'src/ESP82-10027/system/alive', ... (4 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 13)
1576693291: Received PUBLISH from 192.168.0.237@pcpav2 (d0, q1, r0, m14, 'src/ESP82-10027/system/alive', ... (4 bytes))
1576693291: Sending PUBACK to 192.168.0.237@pcpav2 (Mid: 14)

**Comment by icraggs** [comment]
I have two experiments you could try:

1) use the develop branch - some fixes have gone in.
2) version 1.2.1 or older - websocket support and MQTT v5 may have affected the behaviour

I have my suspicions about 2).  I thought I had some multi-threaded tests in the test suite - I do, but not for the async API apparently.

**Comment by vortex314** [comment]
Hi Ian,
Thanks for the help you provide !
I tried both options, to no avail. Result remains the same. 
I'm using a static version of the library, don't know if this makes any difference. 
As I struggled with the CMake approach I rolled my first own build script. 
Script I used to build it with : 
cc -c -g -fPIC -Os -Wall -Ibuild src/Clients.c src/Heap.c  src/MQTTAsync.c \
src/LinkedList.c src/Log.c src/Messages.c src/MQTTClient.c \
src/MQTTPacket.c src/MQTTPacketOut.c src/MQTTPersistence.c \
src/MQTTPersistenceDefault.c src/MQTTProtocolClient.c \
src/MQTTProtocolOut.c src/SocketBuffer.c src/Socket.c src/StackTrace.c \
src/Thread.c src/Tree.c src/utf-8.c src/MQTTProperties.c src/WebSocket.c src/SHA1.c src/Base64.c 
ar -cru build/output/libpaho-mqtt3c.a Clients.o  Heap.o MQTTAsync.o \
LinkedList.o  Log.o  Messages.o  MQTTClient.o  MQTTPacket.o \
MQTTPacketOut.o  MQTTPersistence.o  MQTTPersistenceDefault.o \
MQTTProtocolClient.o  MQTTProtocolOut.o  SocketBuffer.o  Socket.o \
StackTrace.o  Thread.o  Tree.o MQTTProperties.o WebSocket.o SHA1.o Base64.o utf-8.o
I tried also the travis-build.sh with the static option.
What I noticed is that the thread for the callback is the same during the ConnectionFailure for both client Id's. Don't know if it is related or relevant. As I saw that the send &receive thread in the MqttAsync case are common across client connections ? 
The first column in the below logs is the thread name, the thread name assigned is the originating Ip address for the UDP part.

 168.0.237 I | 00:40:36.314  | pcpav2 |    Udp2Mqtt.cpp: 430 |  MQTT connection state MS_CONNECTING => MS_CONNECTED // this is from the OnConnectSuccess handler for client id 1
 168.0.237 I | 00:40:37.150  | pcpav2 |    Udp2Mqtt.cpp: 430 |  MQTT connection state MS_CONNECTING => MS_DISCONNECTED // this is from the onConnectFailure handler for client Id 2

First column indicating the thread is the same. 

  udp2mqtt I | 00:40:35.793  | pcpav2 |        main.cpp:  38 | build : Dec 19 2019 00:39:07
  udp2mqtt I | 00:40:35.793  | pcpav2 |        main.cpp:  43 |  load default config : /home/lieven/workspace/udp2mqtt/udp2mqtt.json
  udp2mqtt I | 00:40:35.794  | pcpav2 |      Config.cpp: 264 |  config loaded : {"mqtt":{"host":"test.mosquitto.org","port":1883,"keepAliveInterval":20},"udp":{"port":1883,"protocol":"jsonArray"}}
  udp2mqtt I | 00:40:36.005  | pcpav2 |    Udp2Mqtt.cpp:  74 |  Mqtt client id : 192.168.0.237@pcpav2 
 168.0.237 I | 00:40:36.005  | pcpav2 |        main.cpp:  80 |  starting thread for 192.168.0.237 
 168.0.237 I | 00:40:36.005  | pcpav2 |    Udp2Mqtt.cpp: 442 |  MQTT connecting tcp://test.mosquitto.org:1883 ... for 192.168.0.237@pcpav2 
 168.0.237 I | 00:40:36.005  | pcpav2 |    Udp2Mqtt.cpp: 430 |  MQTT connection state MS_DISCONNECTED => MS_CONNECTING 
 168.0.237 I | 00:40:36.314  | pcpav2 |    Udp2Mqtt.cpp: 430 |  MQTT connection state MS_CONNECTING => MS_CONNECTED 
 168.0.237 I | 00:40:36.314  | pcpav2 |    Udp2Mqtt.cpp: 140 | MQTT_CONNECT_SUCCESS 192.168.0.237 
 168.0.237 I | 00:40:36.314  | pcpav2 |    Udp2Mqtt.cpp: 430 |  MQTT connection state MS_CONNECTED => MS_CONNECTED 
 168.0.237 I | 00:40:36.314  | pcpav2 |    Udp2Mqtt.cpp: 483 | Subscribing to topic dst/192.168.0.237@pcpav2/# for client 192.168.0.237 using QoS0
 168.0.237 I | 00:40:36.314  | pcpav2 |    Udp2Mqtt.cpp: 493 |  subscribe send : dst/192.168.0.237@pcpav2/# 
 168.0.237 I | 00:40:36.347  | pcpav2 |    Udp2Mqtt.cpp: 156 | MQTT_SUBSCRIBE_SUCCESS 192.168.0.237 
  udp2mqtt I | 00:40:36.519  | pcpav2 |    Udp2Mqtt.cpp:  74 |  Mqtt client id : 192.168.0.195@pcpav2 
  udp2mqtt I | 00:40:36.519  | pcpav2 |        main.cpp:  80 |  starting thread for 192.168.0.195 
 168.0.195 I | 00:40:36.519  | pcpav2 |    Udp2Mqtt.cpp: 442 |  MQTT connecting tcp://test.mosquitto.org:1883 ... for 192.168.0.195@pcpav2 
 168.0.195 I | 00:40:36.519  | pcpav2 |    Udp2Mqtt.cpp: 430 |  MQTT connection state MS_DISCONNECTED => MS_CONNECTING 
 168.0.237 I | 00:40:37.016  | pcpav2 |    Udp2Mqtt.cpp: 483 | Subscribing to topic dst/ESP82-10027/# for client 192.168.0.237 using QoS0
 168.0.237 I | 00:40:37.016  | pcpav2 |    Udp2Mqtt.cpp: 493 |  subscribe send : dst/ESP82-10027/# 
 168.0.237 I | 00:40:37.100  | pcpav2 |    Udp2Mqtt.cpp: 156 | MQTT_SUBSCRIBE_SUCCESS 192.168.0.237 
 168.0.237 I | 00:40:37.123  | pcpav2 |    Udp2Mqtt.cpp: 503 |  MQTT RXD dst/ESP82-10027/system/loopback 
 168.0.237 I | 00:40:37.123  | pcpav2 |    Udp2Mqtt.cpp: 402 |  TXD 192.168.0.237 : [1,"dst/ESP82-10027/system/loopback","true"] 
  udp2mqtt I | 00:40:37.150  | pcpav2 |    Udp2Mqtt.cpp: 303 | [BF4A7510] messages messages queued : 3
 168.0.237 W | 00:40:37.150  | pcpav2 |    Udp2Mqtt.cpp: 527 |  onConnectFailure : response.code : -1 : TCP connect completion failure 
 168.0.237 I | 00:40:37.150  | pcpav2 |    Udp2Mqtt.cpp: 430 |  MQTT connection state MS_CONNECTING => MS_DISCONNECTED

**Comment by icraggs** [comment]
Well in one way that is good that the result is the same - that means the new versions haven't regressed.

Do you have any code I could see, and potentially use in a test?

**Comment by vortex314** [comment]
The code I am working on is located here : https://github.com/vortex314/udp2mqtt
I'm also trying to reproduce the issue with less dependencies.

**Comment by vortex314** [comment]
ok, looks I'm a bit closer to diagnose what's happening. It looks I gave a zero length string for LWT topic in the second thread. Need to dig further in my own code why this happens. But hard-coding the LWT topic fixed the issue at this time. So doesn't look to be a paho mqtt issue. 
btw : retired from IBM ?

**Comment by icraggs** [comment]
Yes I have retired from IBM.  It wasn't my idea to start with, now I'm finding out what to do next :-)  I did want to get the backlog on this project under control so I could feel good about it.  I've had a go at the PRs first.  Next, the issues.

If it's a zero length string for the LWT that's the cause - perhaps it's something we should be protecting ourselves against?

**Comment by vortex314** [comment]
Looks indeed you will have time available now to work on this open source project. ;-) Glad to have your swift feedback. 
yeah, I think it's a good idea to detect LWT error early and fail fast. As it is complex to diagnose otherwise. Don't know if the client or server should handle this.
I'm using this now on a Raspi 3 and sending about 300 msg/sec through it to the local mosquitto. generated by 3 x ESP8266 sending UDP.

**Comment by icraggs** [comment]
Interestingly it looks like Mosquitto is refusing the connect with a zero length LWT.  I tried the connect to the broker in paho.mqtt.testing and it worked.  I suppose it makes no sense to have a zero length LWT but the spec doesn't explicitly state it like that - just says 'present'.
