### ISSUE TITLE
Client caches all persistent messages data from init

### ISSUE THREAD

**Issue by keysight-daryl** [eclipse-paho/paho.mqtt.c#777]
This isn't a bug per-say as it appears intended but during init all persisted messages appear to be fully malloc() allocated into the command queue including all message attributes and payload data.  Aside from the clear performance issues associated with these early allocations this carries the potential to crash the client on init due to running out of heap memory with a persistent store of any significant size.

A simple fix might be to continue adding the command entries into the queue but without the overhead of pget() and mallocs on the message data/metadata. Instead leave these pointers as null and only perform the pget() call to populate this data in a lazy fashion when it is actually preparing to send it over the socket or act on it.  Ie. leave the data on disk or under persist until absolutely necessary and then immediately freeing and removing it once it is finished.

This is currently limiting the amount of messages we can persist over longer periods of the client being offline.

**Comment by icraggs** [comment]
I've added a change to the loading which shortens times for loading 64000 messages by a factor of 20 to 40 #835

**Comment by keysight-daryl** [comment]
Just wondering will this also unload the message data after an unsuccessful send until it it needed for the next retry?  Just concerned it kicks the can down the road in the event of an unexpected socket error or bad connection.

**Comment by icraggs** [comment]
I don't think that has changed.  Why do you think it has?  What part of the code?

**Comment by icraggs** [comment]
If you are referring to the unpersistCommand line - that has not changed.  At this point the command is processed and an MQTT publish is sent and it's added to the outbound inflight message list - called outboundMsgs which existed before the capability for 'offline' messaging was added.  The outboundMsgs list is also persisted.

**Comment by keysight-daryl** [comment]
talking about what happens to the message data in memory if the send fails.  hoping this lazy message data load gets immediately unloaded again so it doesn't continue consuming ram until it is again needed to be sent. in other words that message payload of the messages persisted in 'outboundMsgs' is freed from ram until it needs to be again loaded for a re-send attempt.

**Comment by icraggs** [comment]
@keysight-daryl no.  I did exactly what you suggested at the top of this issue.  The outbound message queue will be much smaller than the command queue.  For instance, you might have several thousand messages stored on the command queue, but the outbound message queue should, I expect, have no more than 10 or 20 at the most, often fewer.  There is a maxInflight message connect option which could limit the number of inflight messages further, to 1 if wanted, but that currently only operates for MQTT 5.0 (it would be straightforward to apply it to MQTT 3.1.1 though).

**Comment by icraggs** [comment]
There is something missing I realized though.  That not on startup, when adding a new message to the command queue from a normal sendMessage, the data is allocated and persisted but not freed at that point.  As the code for refreshing the data from persistence is already there, this should be straightforward to add.

**Comment by icraggs** [comment]
And I've added the commit for that.  As well as the change that should allow you to control the number of simultaneous inflight messages with maxInflightMessages in MQTT 3.1.1.  

Most servers in any case will probably limit the number of inflight messages per client.  I think the Mosquitto default is 20 for instance.  Rarely would you want it to be above 100.  There used to be a recommendation for max reliability of 1, but I didn't subscribe to that.  

In any case, if your command queue has 10000 messages and your max inflight window is 10 for example, you have 1000 times the memory allocated to the command queue vs the inflight message queue.

**Comment by keysight-daryl** [comment]
Yeah this was what I was talking about, the sendMessage persistence not being freed.  Now we just need the c++ wrapper updated in conan-index around all of these latest release changes
