### ISSUE TITLE
Error Compile

### ISSUE THREAD

**Issue by yixuan0719** [eclipse-paho/paho.mqtt.c#778]
**Describe the bug**
Breaks when i try to compile the code:
C:\Windows\system32>cmake -DPAHO_BUILD_STATIC=TRUE -DCMAKE_TOOLCHAIN_FILE=D:\opensource\paho.mqtt.c\cmake\toolchain.win64.cmake D:\opensource\paho.mqtt.c
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 1.
CMake Error at CMakeLists.txt:21 (PROJECT):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.4.0+e901037fe
    版权所有(C) Microsoft Corporation。保留所有权利。

    MSBUILD : error MSB1009: 项目文件不存在。
    开关:VCTargetsPath.vcxproj

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/Windows/System32/CMakeFiles/CMakeOutput.log".

** Environment (please complete the following information):**
 - OS: win10

**Additional context**
I have installed the visual studio 2019

**Comment by waltronix** [comment]
Have you tried to run cmake from the Developer Command prompt?
You have to take the right one (x86/x64).
Have a look here:
https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs

**Comment by icraggs** [comment]
The file cbuild.bat demonstrates how to build on Windows.  The static build is being worked on under other issues.
