### ISSUE TITLE
Supported URI

### ISSUE THREAD

**Issue by aimproxy** [eclipse-paho/paho.mqtt.c#782]
**Is your feature request related to a problem? Please describe.**
Kinda, I received a segmentation fault, when I used this uri: `tls://addr_host:port_n`.
Is this uri suported by the library? If is not can I use the `ssl://addr_host:porn` instead? it have the same purpose?

Thx in advance

**Comment by jumoog** [comment]
use `ssl://` you compiled with ssl support?

**Comment by aimproxy** [comment]
yes, I compiled with ssl support, connection is ok!
```
Message arrived
     topic: wifistat
   message: {"state":{"reported":{"netinfo":{"dhcp":true,"addr":3232235870,"mask":4294967040,"gw":3232235777,"dns1":3232235777,"dns2":0,"bssid":"cc:bb:fe:0a:4a:68","sec":4}}}}
```
