### ISSUE TITLE
No connection Lost detected if sendMessage still called

### ISSUE THREAD

**Issue by REBAUD** [eclipse-paho/paho.mqtt.c#784]
Hello,

Our configuration is the following: 
At least 2 computers:
-	Computer 1 : 
 o	Win7
o	Ip 192.168.67.81
o	Broker host, port 1885
o	Paho release 1.3.0
-	Computer 2 : 
o	Linux 18.04
o	Ip 192.168.67.82
o	No broker
o	Paho release 1.3.0 (compilation with the parameters :
"cmake -GNinja -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_SAMPLES=TRUE --config Release .." )

The second computer starts first, waits for computer 1. One application is launched and starts 4 clients (1 receiver and 3 publishers)
Then computer 1 boots and starts the broker and launches multiples applications which start each multiple clients.

The bug is present on computer 2. 
Log files : 
[mos_Bug.log](https://github.com/eclipse/paho.mqtt.c/files/4019359/mos_Bug.log)  : log broker mosquitto all when bug
[Paho_Bug.txt](https://github.com/eclipse/paho.mqtt.c/files/4019360/Paho_Bug.txt) : Log trace paho Maximum level when bug

Sequence:
-	Computer 2 starts
-	Computer 1 starts and starts broker
-	Computer 2 client connects and starts emission
o	Datas published in QOS0 or 1, and received on the broker mosquitto:
```
1578043497: New client connected from 192.168.67.82 as 20_PCLog_HMIPublisher (c0, k20, u'20').
1578043497: Received PUBLISH from 20_PCLog_HMIPublisher (d0, q0, r0, m0, '/HMI/LogManager/LogStates', ... (990 bytes))
```
-	Computer 2 client publish but no more data received on broker side after few second
o	MQTTAsync_sendMessage() return MQTT_ASYNC_SUCCESS
o	On Mosquito broker side, no more data received after : 
`1578043500: Received PUBLISH from 20_PCLog_HMIPublisher (d0, q0, r0, m0, '/HMI/LogManager/LogStates', ... (990 bytes))`

If we continue to emit message like this no connection lost is detected by the library
Mosquitto:
```
1578043530: Client 20_PCLog_HMIPublisher has exceeded timeout, disconnecting.
1578043530: Socket error on client 20_PCLog_HMIPublisher, disconnecting.
```
Paho:
`20200103 102619.467 105 20_PCLog_HMIPublisher -> PUBLISH qos: 0 retained: 0 (-22)`
=> Nothing call after for client 20_PCLog_HMIPublisher

**Strategy applied temporarily:** 

Log files : 
[mos_Fix.log](https://github.com/eclipse/paho.mqtt.c/files/4019361/mos_Fix.log) : log broker mosquitto all with workaround strategy
[Paho_Fix.txt](https://github.com/eclipse/paho.mqtt.c/files/4019362/Paho_Fix.txt) : Log trace paho Maximum level with workaround strategy

Sequence:
-	Publish periodically a QOS1 PING message ("PING" each 1s on topic /PublisherName/PING)
-	Check during a new publish that the old message was received (onDeliveryComplete cbk)
-	If not received, stop all emission, and wait for the keepalive period that forces a Paho pingReq and reconnect auto.

Paho:
```
20200103 102041.437 PINGRESP not received in keepalive interval for client 20_PCLog_HMIPublisher on socket 12, disconnecting
20200103 102041.438 Calling connectionLost for client 20_PCLog_HMIPublisher
```

**Comment by icraggs** [comment]
The application disconnects in the trace:

20200103 102637.791 PINGRESP not received in keepalive interval for client 20_HAL_SystemMonitor_MQTT_Publisher_1 on socket 104, disconnecting

20200103 102637.791 PINGRESP not received in keepalive interval for client 20_PCLog_Receiver on socket 103, disconnecting

From the trace, it looks like messages are being sent as fast as you can send them.  If so, this could cause a backlog of messages leaving no time for the ping responses to be received.   That's the first reason I can think of for the ping response not being received.

**Comment by REBAUD** [comment]
Hello,

Thank you for the answer.
As we use multiple clients, the one you have to focus on is 20_PCLog_HMIPublisher.

In fact the issue appears when : 
`20200103 102619.467 105 20_PCLog_HMIPublisher -> PUBLISH qos: 0 retained: 0 (-22)`

the -22 seems to be a tcp issue, but no impact on the lib behavior seems to appear, no cbk is called.

**Comment by icraggs** [comment]
-22 is communication interrupted - a partial packet sent.  The packet data will be continue to be sent later.  This won't cause a connectionLost().

I'm not clear what your issue is.  That connectionLost() isn't called when you expect it to be?  To detect a lost connection, an operation has to be attempted on the socket - like sending a packet for instance.  That's what the MQTT ping is for.

**Comment by REBAUD** [comment]
The issue is : 
Once our client get à -22 error during the publish, no more messages are never transmitted again to the broker.
You can see it in the mosquitto log and paho trace given above.

We have to stop calling the send function, and wait for the keepalive period that forces a Paho pingReq. At that time, a connection lost is detected and we can launch a reconection.

If we continue to call the send function, the library return that everything is ok, but no more messages will be receive on the broker side, and the library will never call the pingReq because it thinks that everythings works.

**Comment by icraggs** [comment]
From the trace I infer that you are sending about 40 QoS 0 messages per second for about 90 seconds, until I presume the TCP buffer fills up which causes the interrupted transmission on the send.  If that's the case, how would you intend to keep the sending rate at a level which can be maintained?

**Comment by icraggs** [comment]
No response to last question.

**Comment by REBAUD** [comment]
Sorry, i didn't saw your last answer.

It's true that i'm using MQTT as protocol for data exchange and so emit a lot of messages in QOS0 periodically. 
Do you think it's too much for MQTT protocol and broker?
I supposed that MQTT was good for exchanging a lot of small messages very often ( and the stress tests i had done was good), what is your opinion on the subject.

Have a good day

**Comment by icraggs** [comment]
No, I don't think it's too much.  

I've just tried sending QoS 0 messages continuously to a broker in various configurations, to mqtt.eclipse.org, to a broker on the same machine and to a broker on another machine.  In each case it worked.  There is a pause when the publish gets a -22 return code, which is the TCP buffer filling up, and then the publishing resumes when the buffer has some free space.

You should try using the latest 1.3.2 version, which is what I used.  And if you do take a trace, use the PROTOCOL level which makes it easier to see what is happening in this case.

**Comment by icraggs** [comment]
Here is my test program.

[MQTTAsync_publish.zip](https://github.com/eclipse/paho.mqtt.c/files/4515743/MQTTAsync_publish.zip)

**Comment by icraggs** [comment]
More info needed.  I added a test program.
