### ISSUE TITLE
No disconnection function effect 

### ISSUE THREAD

**Issue by REBAUD** [eclipse-paho/paho.mqtt.c#785]
Hello,

Our configuration is the same as in the bug #784, in the bug case
It’s a bug detected during the investigation on the other subject.

We tried to force a disconnection when no more QOS1 message is received by the broker by calling function MQTTAsync_disconnect.
In logTrace [PahoLog_neverDisconnect.txt](https://github.com/eclipse/paho.mqtt.c/files/4019377/PahoLog_neverDisconnect.txt)  : Line 22526
```
20200102 142324.839 (1863042816)  (1)> MQTTAsync_processCommand:1324
20200102 142324.839 (1863042816)   (2)> MQTTAsync_checkDisconnect:1084
20200102 142324.839 (1863042816)   (2)< MQTTAsync_checkDisconnect:1116
```
It’s seems that the function is called but ends immediately.
Probably because m->c->outboundMsgs->count is never equal to 0 (because never received on broker side) in MQTTAsync_checkDisconnect.

The part with MQTTAsync_elapsed in the ‘if’ seems to be never applied because the command is saved in “command->client->disconnect” line MQTTAsync.c ::1586, but does not seem to be reused after.

The result is, we ask for a disconnection but even after multiple call the lib doesn’t want to disconnect (does not use any callbacks).

Have a good day

**Comment by icraggs** [comment]
How do you know the client never disconnects? If disconnect ends immediately with a -3 return code, that is because the client is already disconnected.

The log is showing:

    20200102 142342.766 PINGRESP not received in keepalive interval for client 20_HAL_SystemMonitor_MQTT_Publisher_1 on socket 104, disconnecting
    20200102 142342.767 PINGRESP not received in keepalive interval for client 20_PCLog_Receiver on socket 103, disconnecting
    20200102 142345.760 PINGRESP not received in keepalive interval for client 20_ ComManagerWithVSM_Publisher on socket 106, disconnecting
    20200102 142346.074 PINGRESP not received in keepalive interval for client 20_PCLog_HMIPublisher on socket 105, disconnecting

All these four clients are getting disconnected because they are not receiving ping responses in time.  This could be because something, broker or network, is overloaded.  You can turn off keepalive processing by setting the keepalive interval to 0, although I would suggest that's more for testing than running for real to see if there is a difference.

**Comment by REBAUD** [comment]
I assume that the lib didn't disconnect because no cbk is call when I ask for a disconnection.
So instead of asking for a disconnection, I stop emission which will trigger a latter disconnection with ping request (linked to issue #784 for this case)

I detect that the print are not the sames when the disconnect succeed or not.

have a good day

**Comment by icraggs** [comment]
If the return code from the disconnect (or any other) call is not SUCCESS, then there will be no callback, success or failure, because the call to start the disconnect processing was not successful.

**Comment by icraggs** [comment]
I think this one is answered.
