### ISSUE TITLE
SSLSocket_error errno 11 Resource temporarily unavailable

### ISSUE THREAD

**Issue by weimianlong** [eclipse-paho/paho.mqtt.c#788]
app running after a few days, when MQTTAsync_sendMessage with big payload (about 40KB), connection broken.MQTTAsync_sendMessage with small payload is ok. log trace is here.  use v1.3.0 .

114219.542 (3070782272) (0)> MQTTAsync_sendMessage:3466.
114219.542 (3070782272)  (1)> MQTTAsync_send:3397.
114219.542 (3070782272)   (2)> UTF8_validateString:157.
114219.542 (3070782272)    (3)> UTF8_validate:131.
114219.542 (3070782272)    (3)< UTF8_validate:143 (1).
114219.542 (3070782272)   (2)< UTF8_validateString:159 (1).
114219.542 (3070782272)   (2)> MQTTStrncpy:848.
114219.542 (3070782272)   (2)< MQTTStrncpy:858.
114219.542 (3070782272)   (2)> MQTTAsync_addCommand:984.
114219.542 (3070782272)    (3)> Thread_signal_cond:393.
114219.542 (3060792128)  (1)< Thread_wait_cond:419 (0).
114219.542 (3060792128)  (1)> MQTTAsync_checkTimeouts:1730.
114219.826 (3060792128)  (1)< MQTTAsync_checkTimeouts:1778.
114219.826 (3060792128)  (1)> MQTTAsync_processCommand:1324.
114219.826 (3060792128)   (2)> MQTTProtocol_startPublish:156.
114219.826 (3060792128)    (3)> MQTTProtocol_startPublishCommon:133.
114219.826 (3060792128)     (4)> MQTTPacket_send_publish:791.
114219.826 (3060792128)      (5)> MQTTPacket_sends:239.
114219.826 (3060792128)       (6)> MQTTPacket_encode:281.
114219.826 (3060792128)       (6)< MQTTPacket_encode:291 (3).
114219.826 (3060792128)       (6)> WebSocket_putdatas:681.
114219.826 (3060792128)        (7)> SSLSocket_putdatas:878.
114219.826 (3060792128)         (8)> SSLSocket_error:97.
114219.826 SSLSocket error (1) in SSL_write for socket 40 rc -1 errno 11 Resource temporarily unavailable
114219.826 (3060792128)         (8)< SSLSocket_error:117 (-3).
114219.826 (3060792128)        (7)< SSLSocket_putdatas:932 (-1).
114219.826 (3060792128)       (6)< WebSocket_putdatas:713 (-1).
114219.826 (3060792128)      (5)< MQTTPacket_sends:266 (-1).
114219.826 40 CCU_00162 -> PUBLISH qos: 0 retained: 0 (-1).
114219.826 (3060792128)     (4)< MQTTPacket_send_publish:835 (-1).
114219.826 (3060792128)    (3)< MQTTProtocol_startPublishCommon:137 (-1).
114219.826 (3060792128)   (2)< MQTTProtocol_startPublish:169 (-1).
114219.830 (3060792128)   (2)> MQTTAsync_disconnect1:3050.
114219.830 (3060792128)    (3)> MQTTAsync_addCommand:984.
114219.830 (3060792128)     (4)> Thread_signal_cond:393.
114219.830 (3060792128)     (4)< Thread_signal_cond:398 (0).
114219.830 (3060792128)    (3)< MQTTAsync_addCommand:1018 (0).
114219.830 (3060792128)   (2)< MQTTAsync_disconnect1:3087 (0).
114219.830 Calling command failure for client CCU_00162.

**Comment by icraggs** [comment]
The SSL error from the above trace is -1 which according to the OpenSSL documentation is SSL_ERROR_SSL

    A non-recoverable, fatal error in the SSL library occurred, usually a protocol error.

I think the errno value is misleading and isn't related to the SSL error.  This looks like the TCP comms or broker failed in some way and the application needs to reconnect.

**Comment by weimianlong** [comment]
yes. when send fail ,always automatic recon . but MQTTAsync_sendMessage fail again as above when public msg with big payload. Kill the app proccess will solve the problem.

**Comment by icraggs** [comment]
Does sendMessage with >40k work when the app hasn't been running for a few days?
