### ISSUE TITLE
Async Publish Example : Token Question

### ISSUE THREAD

**Issue by prateek-khatri** [eclipse-paho/paho.mqtt.c#790]
Hello,

This is more of a question for my understanding rather than an issue. I am referring to the following example:
https://www.eclipse.org/paho/files/mqttdoc/MQTTAsync/html/publish.html

There is a global variable: `volatile MQTTAsync_token deliveredtoken;`
The only place this is used is the following:
```
void onConnect(void* context, MQTTAsync_successData* response)
{
        MQTTAsync client = (MQTTAsync)context;
        MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
        MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
        int rc;
        printf("Successful connection\n");
        opts.onSuccess = onSend;
        opts.context = client;
        pubmsg.payload = PAYLOAD;
        pubmsg.payloadlen = strlen(PAYLOAD);
        pubmsg.qos = QOS;
        pubmsg.retained = 0;
        deliveredtoken = 0;
        if ((rc = MQTTAsync_sendMessage(client, TOPIC, &pubmsg, &opts)) != MQTTASYNC_SUCCESS)
        {
                printf("Failed to start sendMessage, return code %d\n", rc);
                exit(EXIT_FAILURE);
        }
}
```
`deliveredtoken` is simply set to 0 without being used anywhere. What exactly is the use of this token in this example? If it's not being used, what's the proper way of using the Token to confirm delivery of a message with QOS >= 1.

What I understand is that `MQTTAsync_responseOptions` has the token field. When we send a message should the user be setting the token value and checking in 'MQTTAsync_deliveryComplete` callback?

Just want some insight into what the proper way of checking if a message was received by the broker.

**Comment by icraggs** [comment]
The token is set by the call to sendMessage when successful.  It's actually the MQTT message id.  It's always 0 if the QoS is 0, as those messages don't have message ids.  For QoS 0 messages, deliveryComplete is called when the message is written to the TCP socket - you can't tell whether the broker has received it.  For QoS 1 and 2 messages, deliveryComplete is called when the ack is received from the broker, which shows that the message has been received by the broker.

**Comment by prateek-khatri** [comment]
If we were to send multiple messages in succession with QoS of 1 or higher, after calling `MQTTAsync_sendMessage() ` we could store the token ID and compare when delivery complete is called to verify each message is acknowledged?
Is that correct?

**Comment by icraggs** [comment]
Correct.  The message sending and acknowledgement receiving would overlap, happening in parallel.

**Comment by Thomseeen** [comment]
Hello,

I hope this will be seen even through in a closed issue, but I didn't feel like opening a new one for this "simple" question :)

I find it hard to understand how to obtain the token for a sent message. If I call `MQTTAsync_sendMessage()` how can I obtain the token for this exact message so I can later check it versus `response->token` in the callback for `onSuccess`?

I tried 
```C
deliveredtoken = 0; // Globally defined as volatile MQTTAsync_token deliveredtoken;

if ((rc = MQTTAsync_sendMessage(mqtt_client, MQTT_DEFAULT_TOPIC_PREFIX, &mqtt_pubmsg, &mqtt_conn_opts)) != MQTTASYNC_SUCCESS) {
  log_error("Failed to start sendMessage, return code %d", rc);
  exit(EXIT_FAILURE);
}

while (deliveredtoken == 0) {
  usleep(10000);
}

log_trace("Sent measurement from pin %hhu with seq_no %llu and %d bytes with token %d", adc_reading->pin_no, adc_reading->seq_no, sizeof(*adc_reading), deliveredtoken);
```
and also tried to put `mqtt_conn_opts.token = deliveredtoken;` in there. Both never leave the while loop; QOS is 1.
