### ISSUE TITLE
Asynchronous MQTT C Client gets crash by giving MQTT error code 6.

### ISSUE THREAD

**Issue by jadhavshital** [eclipse-paho/paho.mqtt.c#791]
I am using Paho Asynchronous MQTT C Client to connect aws MQTT broker using SSL(client certificate, private key file and public key file).
My application gets crash at line no 42 -
`int conn_res = MQTTAsync_connect(pc->client, &conn_opts);`

In log I am getting MQTT error code 6. 
`20200106 112741.238 (7924)  (1)> MQTTAsync_processCommand:1398`
`20200106 112741.238 (7924)  (1)< MQTTAsync_addCommand:1084 (6)`
`20200106 112741.238 Error Unknown error locking mutex`
`20200106 112741.238 (9296) (0)< MQTTAsync_connect:3119 (6)`
`20200106 112741.238 Error Unknown error locking mutex`
`Attempt to initiate connection failed with error code: 6`

Kindly refer below attached client code and log file -
[code.txt](https://github.com/eclipse/paho.mqtt.c/files/4025832/code.txt)
[output.txt](https://github.com/eclipse/paho.mqtt.c/files/4025771/output.txt)

Your suggestion and help is highly appreciable.

**Comment by icraggs** [comment]
The -6 return code, as described in the header docs, means there is a null parameter.  From your code, it looks like you haven't called create() to create the client object.

**Comment by jadhavshital** [comment]
Thank you @icraggs for replying and it helped me a lot.
Now I am using SSL library and passing client certificate file and client private key file by using folloing lines of code in C. Here, i don't have CA file.
`ssl_opts.keyStore = cert_path;`
`ssl_opts.privateKey = private_key_path;`

Getting an error "Connect failed rc=-1", attaching screenshot of error
![connect_failed](https://user-images.githubusercontent.com/17235485/71877861-35530780-3150-11ea-9ee8-70256ea42fab.PNG)

Kindly help.

**Comment by icraggs** [comment]
The original question was answered.
