### ISSUE TITLE
Static Linkage

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#792]
I'd like to get static linking as a first-class citizen for this project. Over the last few years, I've had several customers requesting static linking for their embedded Linux projects. I suppose now that flash space is so cheap, dynamic libraries are not as important as they used to be.

Plus, the Paho Rust client uses static linking by default, and thus is completely broken on Windows. It doesn't give any warnings; it builds fine, but then all the apps crash hard due to problems with mutexes. So this is holding up the next (MQTT v5) Rust release.

In the long run, I'd like to accomplish two things:
- Make sure the static library works on all supported platforms
- [Less important] Update CMake so that it can build just the static library and not the dynamic one, on request.

This issue appears to be scattered across a number of open issues: #261, #263, #398, #519, #655, #660, etc...

If any work has started in this area, let me know, otherwise I can start working on it right away.

**Comment by jumoog** [comment]
maybe its better to write it completely in rust add we can use it via FFI?

**Comment by icraggs** [comment]
@fpagliughi The develop branch has some changes which I think should allow static linking to now work on Windows.  It would be good if you could try that out.

**Comment by fpagliughi** [comment]
@jumoog I thought of that. Perhaps as the async/await stuff in Rust stabilizes a bit more, it would be worth considering a 100% Rust library. 

Then, again, I thought v2 of the C++ library would be 100% stand-alone C++. And that was +6yrs ago...  So, we'll see.

@icraggs Cool! I'll try it out this week.

**Comment by fpagliughi** [comment]
The static build seems broken even on Linux at the moment. I get this:
```
...
[ 51%] Building C object src/CMakeFiles/common_obj.dir/Base64.c.o
[ 52%] Building C object src/CMakeFiles/common_obj.dir/SHA1.c.o
[ 53%] Building C object src/CMakeFiles/common_obj.dir/WebSocket.c.o
[ 53%] Built target common_obj
Scanning dependencies of target paho-mqtt3c-static
[ 54%] Building C object src/CMakeFiles/paho-mqtt3c-static.dir/MQTTClient.c.o
/home/fmp/mqtt/paho.mqtt.c/src/MQTTClient.c:77:10: fatal error: VersionInfo.h: No such file or directory
 #include "VersionInfo.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/paho-mqtt3c-static.dir/build.make:62: recipe for target 'src/CMakeFiles/paho-mqtt3c-static.dir/MQTTClient.c.o' failed
make[2]: *** [src/CMakeFiles/paho-mqtt3c-static.dir/MQTTClient.c.o] Error 1
CMakeFiles/Makefile2:242: recipe for target 'src/CMakeFiles/paho-mqtt3c-static.dir/all' failed
make[1]: *** [src/CMakeFiles/paho-mqtt3c-static.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by fpagliughi** [comment]
On Windows, I get the same "VersionInfo.h" fatal error, but I also get a lot of warnings. I tried it with MSVS 2017 & 2019, same results.

```
...
     Creating library K:/mqtt/paho.mqtt.c/build/src/Debug/paho-mqtt3as.lib and object K:/mqtt/paho.mqtt.c/build/src/Debug/paho-mqtt3as.exp
MQTTAsync.obj : warning LNK4217: locally defined symbol Thread_start imported in function MQTTAsync_connect [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
Heap.obj : warning LNK4049: locally defined symbol Thread_lock_mutex imported [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
MQTTAsync.obj : warning LNK4217: locally defined symbol Thread_lock_mutex imported in function MQTTAsync_lock_mutex [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
StackTrace.obj : warning LNK4049: locally defined symbol Thread_lock_mutex imported [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
Socket.obj : warning LNK4049: locally defined symbol Thread_lock_mutex imported [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
Log.obj : warning LNK4049: locally defined symbol Thread_lock_mutex imported [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
Heap.obj : warning LNK4049: locally defined symbol Thread_unlock_mutex imported [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
MQTTAsync.obj : warning LNK4217: locally defined symbol Thread_unlock_mutex imported in function MQTTAsync_unlock_mutex [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
StackTrace.obj : warning LNK4049: locally defined symbol Thread_unlock_mutex imported [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
Socket.obj : warning LNK4049: locally defined symbol Thread_unlock_mutex imported [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
Log.obj : warning LNK4049: locally defined symbol Thread_unlock_mutex imported [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
MQTTAsync.obj : warning LNK4217: locally defined symbol Thread_getid imported in function MQTTAsync_sendThread [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
StackTrace.obj : warning LNK4049: locally defined symbol Thread_getid imported [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as.vcxproj]
  paho-mqtt3as.vcxproj -> K:\mqtt\paho.mqtt.c\build\src\Debug\paho-mqtt3as.dll
  Building Custom Rule K:/mqtt/paho.mqtt.c/src/CMakeLists.txt
  MQTTAsync.c
K:\mqtt\paho.mqtt.c\src\MQTTAsync.c(80): warning C4273: 'MQTTAsync_global_init': inconsistent dll linkage [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as-static.vcxproj]
  k:\mqtt\paho.mqtt.c\src\MQTTAsync.h(245): note: see previous definition of 'MQTTAsync_global_init'
K:\mqtt\paho.mqtt.c\src\MQTTAsync.c(560): warning C4273: 'MQTTAsync_createWithOptions': inconsistent dll linkage [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as-static.vcxproj]
  k:\mqtt\paho.mqtt.c\src\MQTTAsync.h(886): note: see previous definition of 'MQTTAsync_createWithOptions'
K:\mqtt\paho.mqtt.c\src\MQTTAsync.c(685): warning C4273: 'MQTTAsync_create': inconsistent dll linkage [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as-static.vcxproj]
  k:\mqtt\paho.mqtt.c\src\MQTTAsync.h(858): note: see previous definition of 'MQTTAsync_create'
K:\mqtt\paho.mqtt.c\src\MQTTAsync.c(1133): warning C4273: 'MQTTAsync_reconnect': inconsistent dll linkage [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as-static.vcxproj]
  k:\mqtt\paho.mqtt.c\src\MQTTAsync.h(814): note: see previous definition of 'MQTTAsync_reconnect'
K:\mqtt\paho.mqtt.c\src\MQTTAsync.c(2046): warning C4273: 'MQTTAsync_destroy': inconsistent dll linkage [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as-static.vcxproj]
  k:\mqtt\paho.mqtt.c\src\MQTTAsync.h(1521): note: see previous definition of 'MQTTAsync_destroy'
K:\mqtt\paho.mqtt.c\src\MQTTAsync.c(2106): warning C4273: 'MQTTAsync_freeMessage': inconsistent dll linkage [K:\mqtt\paho.mqtt.c\build\src\paho-mqtt3as-static.vcxproj]
...
```

**Comment by icraggs** [comment]
I guess it's time for me to take a look...

**Comment by fpagliughi** [comment]
Apologies @icraggs, I meant to look in a little closer at this, but I've got busy week with work picking up after the holidays. If you don't get to it, I can have a look over the weekend.

**Comment by icraggs** [comment]
@fpagliughi that's ok.  I'd want to update the build/test process to run the tests statically too, so there's some effort involved.

**Comment by icraggs** [comment]
The VersionInfo.h problem should now be fixed, in the develop branch, at least on Linux.  I hope to look at the whole issue soon.

**Comment by icraggs** [comment]
Ok. So I've run the static build on Linux, Mac and Windows, with the new test CMake config.

@fpagliughi On Windows, when running statically, at the moment you have to call MQTTClient_global_init() or MQTTASync_global_init() before any other call, to initialize the mutexes.  

The initialization could be done implicitly in Create(), but I'm not sure that's a good idea - possible clash if called from multiple threads.

**Comment by fpagliughi** [comment]
Is it safe to call when using the shared library? Or do client apps need to figure out the linkage and only call for the static lib?

Either way, this is workable.

**Comment by icraggs** [comment]
It's safe to call when using the shared library.  In fact I had been thinking of making the MQTTAsync_terminate() call optionally explicit, because the implicit cleaning up of library resources has caused some issues in the past.

Having init() and terminate() calls explicit would allow the application to control more directly the allocation and freeing of the library resources, data structures and use of OpenSSL.

**Comment by fpagliughi** [comment]
For Paho C++ and Rust clients, I can probably wrap that up behind some thread-safe, run-once, functionality so that the application wouldn't need to worry about it.

But either way, this isn't a big problem. Quite a few networking libraries that I use (and one that I wrote) require this sort of static initialization.

**Comment by icraggs** [comment]
Because the init function creates the mutexes on which synchronization is done, it needs to be called in a non-synchronized way.  It could rely on the application creating a mutex, but that would just be more complicated.  I don't think there is a static initialization option in Windows.

**Comment by fpagliughi** [comment]
Oh, Windows.

That's interesting. Modern C++ has `call_once` functionality in the std library which is supposed to be thread-safe. It depends on a static `once_flag` used like:
```
std::once_flag init_flag;
 
void my_init()
{
    std::call_once(init_flag, [](){ MQTTAsync_global_init(); });
}
```
This would let me call `my_init()` as many times as I want, from different threads, but `MQTTAsync_global_init()` would only be called once.

I wonder how it's implemented on Windows.

**Comment by icraggs** [comment]
I don't claim to be an expert on Windows, so if there is another way that I'm not aware of...

A quick search didn't show up any obvious answers (except for 'no') but I may have been asking the wrong question.

**Comment by fpagliughi** [comment]
OK. I think I found it...
https://docs.microsoft.com/en-us/windows/win32/sync/one-time-initialization

Seems to provide a thread-safe way to call a function once and only once. Similar to *pthread_once()*.

It, like a bunch of useful multi-threaded kernel features, came into Win32 with Windows Vista. So it's not in XP or prior, but Microsoft dropped support for them years ago, so I would have no problem using it.

On that note, condition variables also came into Win32 at that time (Vista). That could help clean up some of the low-level queuing code if we wanted to bother.

**Comment by icraggs** [comment]
@fpagliughi I've submitted changes for static builds on Windows using that one time initialization method.  It works locally for me, I'm waiting for the AppVeyor builds to run to see if it works there.   Fingers crossed...

**Comment by icraggs** [comment]
Static build AppVeyor CI tests now working.  See https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c/builds/31478964.

What is still left to do is to get CMake to build both shared and static libraries in the same build, using different #defines - any advice on getting that to work would be gratefully accepted!

**Comment by jumoog** [comment]
When I try to use the static lib I always get the following errors when building:

> LNK2019: unresolved external symbol
> "__imp_MQTTClient_setCallbacks" 
> "__imp_MQTTClient_create"		
> "__imp_MQTTClient_connect" 		
> "__imp_MQTTClient_disconnect" 	
> "__imp_MQTTClient_publishMessage"
> 

I build the lib and later use it in a new console application. As code I take the example client

**Comment by icraggs** [comment]
@jumoog On Windows?  You can see the Windows AppVeyor static build & tests are working?

**Comment by jumoog** [comment]
I can also build the static tests. But they directly use the sources

//Edit yes on windows

**Comment by icraggs** [comment]
@jumoog you have to add the compile definition -DMQTT_DIRECT so the ExportDeclarations.h header has the correct attribute for the entry points.  I think that should probably be something like MQTT_STATIC, maybe.

**Comment by jumoog** [comment]
@icraggs thx!

**Comment by fpagliughi** [comment]
I just hit this, too. It's a little confusing, but probably workable. Do Windows users always have to put up with this sort of nonsense?

I agree, @icraggs, MQTT_STATIC would probably be a bit more descriptive. I also thinks all the compilation macros in `ExportDeclarations.h` should begin with PAHO_ to be more consistent and remove any chance of clashing with other MQTT code that people are using, so...
PAHO_MQTT_EXPORTS, PAHO_MQTT_STATIC

**Comment by icraggs** [comment]
I never used to use any attribute when importing the symbols but it was added by a contributor.  This page: 

https://docs.microsoft.com/en-us/cpp/build/importing-into-an-application-using-declspec-dllimport?view=vs-2019

says:

> Using __declspec(dllimport) is optional on function declarations, but the compiler produces more efficient code if you use this keyword.

But that more efficient linking doesn't apparently work if you're linking statically.  So we have 3 cases:

1. exporting from a shared lib
2. importing from a shared lib
3. importing/exporting from a static lib

**Comment by icraggs** [comment]
Thinking about it, I have a plan for the export declarations.

PAHO_MQTT_EXPORTS for building the shared lib.
PAHO_MQTT_IMPORTS for importing the shared lib.  Not necessary but more efficient, according to the MS doc.
No definition will add no attribute to the function calls.  This will work if you are building an application using the shared or static libraries.  Optionally you can use the PAHO_MQTT_IMPORTS definition for efficiency when using the shared library.

This combination will intuitively match the header file, and will work simply when linking applications.

**Comment by fpagliughi** [comment]
That sounds workable.

**Comment by icraggs** [comment]
Ok, I've done that.  Also some refactoring so the static and shared libraries can be built together.

**Comment by fpagliughi** [comment]
I've been testing with the Paho Rust client the last few days. So far, looks great with Linux.

Windows is crashing on the call into the C code. My guess at this moment is that it is something I'll need to fix on the Rust side, but I need to get a debugger working. I'll keep you informed.

**Comment by icraggs** [comment]
When it crashed on Windows it was always that MQTTAsync_init hadn't been called implicitly.  There seemed to be something intermittent going on with that Windows one-time initialization.  It works on the AppVeyor builds now - one of the three is a static build.

To prove that it is or isn't related to MQTTAsync_init not being called, you can call it explicitly to test it.  Given the unreliability of the implicit calling so far, I would still prefer to go with the explicit call to MQTTAsync_init for static use.  Unless we can fix it for sure.

**Comment by fpagliughi** [comment]
Yeah, it's starting to look like that's it. 

The Rust code appears to be calling into `MQTTAsync_createWithOptions()` fine, but then crashing somewhere in or near a call to `__impl_InitOnceExecuteOnce`.  It's a little tough to see exactly what's happening as I can't seem to get the debug symbols loaded for the C lib.

I can certainly try calling `MQTTAsync_init` manually as a quick test.

**Comment by fpagliughi** [comment]
Yeah. That's it. If I comment out the call to `OpenEventHandleSync()` in the client create function, and call `MQTTAsync_init()` manually, it seems to work fine.

Note that I have to get rid of the call to `InitOnceExecuteOnce()` because it always seems to crash. I should mention, I'm currently testing on Windows 7, as these things can behave totally differently on various versions of Windows.

I also double checked the implementation of the one-time initialization. It seems to match the Microsoft example exactly. No mistake there.

Either way, I'm coming around to agreeing with you. If this is flaky, let's forget about it. Calling `MQTTAsync_init()` explicitly wouldn't be the worse thing in the world.

**Comment by fpagliughi** [comment]
I suppose we'd need to:

- Rip out the one-time initialization code. (And apologies for sending you down this path to begin with).
- Add `MQTTAsync_init()` to the header file.
- Make sure the function is public and exported. And that it's safe to call even when not needed (DLL)?
- Update the samples to add the explicit call (possibly with conditional compilation for static builds)?

Does that make sense?

**Comment by icraggs** [comment]
Yes.  But this is irritating me.  I was getting a crash consistently in some tests due to this initialization, and I changed something in the tests and perhaps elsewhere, in how the API was used and it went away.  Now I can't get it back, on AppVeyor or my desktop.

Can I try out your use with Rust somehow?

**Comment by fpagliughi** [comment]
Sure. I may just take me a little while to get what I have patched together and pushed into a branch.

**Comment by fpagliughi** [comment]
Well this _is_ annoying...

I've been testing a hand-cobbled setup where the Rust project automatically builds and links the C lib, since that's my assumption on how most Rust users would operate. When doing this, I don't specify the C compiler to use. The Rust CMake wrapper just finds a compiler. And I have a few.

But you can also just tell Rust to use a pre-built C lib. I thought that would be easier for us at the moment, but when I tested it that way, it worked fine with the run-once initialization!

I specified MSVS 2019 (Community Edition) when I did the hand build. Now I'm wondering if the compiler version is a variable in this.

**Comment by icraggs** [comment]
I told you it was annoying :-)

**Comment by icraggs** [comment]
Actually that init code is over complicated.  I have a simpler version which is like that in MQTTClient.c.  Whether it will make any difference to your setup though I don't know.

**Comment by icraggs** [comment]
Any news? I'd like to tag this release if I can.  This function definitely works better than it did at any time previously, so things have not regressed.  If we need a follow on fix I can add another release quickly afterwards.

**Comment by fpagliughi** [comment]
If it's working on your end, push forward with the release. I can probably fix the Rust issue in that project. If not at least there seems to be a work-around.
