### ISSUE TITLE
Update cmake build system

### ISSUE THREAD

**Issue by waltronix** [eclipse-paho/paho.mqtt.c#799]
As discussed in #794 we should update the cmake build system to support all features of the Makefiles with the goal to replace the Makefiles.

Suggested is an update of the required cmake version to 3.5 to support builds on ubuntu 16.04 LTS.
This would also be beneficial for usage of OpenSSL on windows.

In context, I also suggest to update the CI build environments to use VS2019 with cmake (and maybe clang).

**Comment by waltronix** [comment]
@icrags a general question, would you prefer a series of smaller pull requests or a bigger one with small commits?

**Comment by jumoog** [comment]
but i need VS2013 / VS2015 support 🤕

**Comment by waltronix** [comment]
According to cmake docs, it should be available.

https://cmake.org/cmake/help/v3.5/generator/Visual%20Studio%2012%202013.html

**Comment by jumoog** [comment]
my bad i thought your idea was dropping support for older versions

**Comment by icraggs** [comment]
@waltronix smaller PRs are always good - easier to review and test.

The CI tests should use both recent and old versions of Visual Studio, IMO.  Ideally all of them that are supported, but that's probably too expensive in running time and CI resources.

**Comment by icraggs** [comment]
Visual Studio 2013 and 2015 are used in the AppVeyor CI tests, so we shouldn't have any problem supporting those.  At some point we might need a newer version too.

**Comment by icraggs** [comment]
@waltronix 

> Suggested is an update of the required cmake version to 3.5 to support builds on ubuntu 16.04 LTS. This would also be beneficial for usage of OpenSSL on windows.

We don't need to update the required version of CMake to allow building on 16.04 LTS do we?  I'm building on 18.04 with CMake 3.10.2 just fine.

**Comment by waltronix** [comment]
@icraggs  No, we do not need in update to be able to build on Ubuntu. But the more recent versions of cmake add additional features that might be helpful.
But I can try to keep the minimum version low until we encounter restrictions. Then we can decide by case.

**Comment by icraggs** [comment]
So, is this done now?  Or is there more?

**Comment by waltronix** [comment]
I'd like to pick this topic up again. But I didn't want to get into conflicts with the shared library topic.

**Comment by icraggs** [comment]
I've finished with the CMake changes for static and shared library building in the develop branch now.

**Comment by icraggs** [comment]
I've also added the definitions for calling the init functions for the shared libraries on Linux/MacOS.  And the testing of static builds.

The static build on Windows is using VS2019.  I've submitted it, but the AppVeyor builds haven't run yet.  When I get that working, is there anything left?

**Comment by icraggs** [comment]
To be clear, there are now 3 Windows CI builds.  One each for VS 2013, 2015 and 2019.

**Comment by icraggs** [comment]
I think this is all done now.

**Comment by fpagliughi** [comment]
Thanks for all the work on this! I will start testing today.

A large number of the issues on the Paho C++ site have to do with building the C and C++ libraries, having them work together with versioning issues and such, and having applications find and link proper versions of both libraries.

I would like to make this a much simpler process. So I'm going to start experimenting with having the C++ library automatically build and link to a specific version of the C lib unless explicitly told not to through a build option. I'm thinking to use a Git submodule (generally pointing to the latest C release), building it as a private, static lib using a subproject/subdirectory.

The C lib shouldn't need to do anything special to support this, but I will make sure that the static build works across platforms, and that it is properly configured to be built as a subproject. Both of these would be good to have regardless of the work on the C++ project.

**Comment by icraggs** [comment]
As it stands, building both the static and shared libraries _in the same build_ doesn't work (I think) for Windows, because there is conditional code depending on a static or shared build in MQTTClient.c and MQTTAsync.c.  I'm thinking what the best option might be...

**Comment by fpagliughi** [comment]
Ah. OK. That's probably fine for now, but we can look to fix it in a future release. I assume that would be done through the build, leaving the sources with the conditional compilation.

I think we could do it by defining separate targets for the shared and static libraries, and have them each compile the sources independently. Meaning we wouldn't use a common "object" library to compile the sources just once.
