### ISSUE TITLE
Null pointer access if the server URI does not contain a ':'

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.c#8]
migrated from Bugzilla [#484386](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484386)
status UNCONFIRMED severity _normal_ in component _MQTT-C_ for _1.2_
Reported in version _1.2_ on platform _PC_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[commit-ff8cd5b](https://bugs.eclipse.org/bugs//attachment.cgi?id=258686)_ (ID 258686)

On 2015-12-15 07:43:27 -0500, Juergen Kosel wrote:

> Created attachment 258686
> Patch to fix this issue
> 
> If the user accidentally provided a bad server URI without port and without ':'
> the paho-mqtt library crashes due to null pointer access.
> The fix is simple, please look at the attached patch.

**Comment by icraggs** [comment]
For this bug, I think we should be ensuring that the port is specified.  There is no default port assignment in the API, so not specifying the port in the serverURI is going to fail anyway.   With this approach, creating a client without specifying the port will fail with, perhaps with a new -10 return code (BAD_SERVERURI).

**Comment by JuergenKosel** [comment]
A default port is assigned in file MQTTProtocollOut.c function  MQTTProtocol_addressPort().
So it should be okay to not especially specify a port.

**Comment by icraggs** [comment]
This was fixed in the fix for issue #7 and works in the develop branch.
