### ISSUE TITLE
API Documentation issue in MQTTAsync_successData/MQTTAsync_subscribeMany when using MQTTAsync_subscribeMany() with a collection of 1 item could lead to bad usages and seg faults

### ISSUE THREAD

**Issue by Pascal-Fremaux** [eclipse-paho/paho.mqtt.c#804]
**Describe the bug**
MQTT 3.1.1 (did not check for v5):
The SUBACK of a subscribeMany with 1 element returns a value in alt.qos, not in alt.qosList as described by the documentation in MQTTAsync_successData
MQTTAsync_subscribeMany() documentation does not speak of special case of count==1 (value used by MQTTAsync_subscribe() internally, but could be used by external clients).
MQTTAsync_successData documentation says 

```
		/** For subscribe, the granted QoS of the subscription returned by the server. */
		int qos;
		/** For subscribeMany, the list of granted QoSs of the subscriptions returned by the server. */
		int* qosList;
```
In fact, the usage of qos or qosList do not depends on the API used (subscribe/subscribeMany), but on the number of topic items (1=>read qos, more=> read qosList)

**To Reproduce**
calls subscribeMany with an array of one qos element.

**Expected behavior**
The MQTTAsync_successData should says to read qos when expecting one topic response (count==1, could be calling subscribe or subscribeMany with one element) .
And qosList when expecting more than one element (count>1, obviously only with subscribeMany)
The MQTTAsync_subscribeMany API documentation should warn about that behavior to avoid bad implementation errors.

I suggest also to set qosList to NULL when not using it to avoid using the wrong returned data.
Because the SUBACK method that fills the struct MQTTAsync_successData do not set qosList to NULL when using qos, which prevent testing the qosList value and cause seg fault craches for errors that could be easily prevented with a NULL value.

**Screenshots**

** Environment (please complete the following information):**
 - OS: [e.g. Linux]

**Additional context**
Problem seen on using the Paho CPP v1.1, with an implementation that was not updated to the internal behavior of Paho C v1.3.1, with array of 1 to n topics elements usage in a collection subscribe API.

**Comment by icraggs** [comment]
Thanks
