### ISSUE TITLE
Add ability to update password before connection attempt - enables JWT support

### ISSUE THREAD

**Issue by jens-f** [eclipse-paho/paho.mqtt.c#808]
Some MQTT servers such as in Google Cloud IoT require the password of the `CONNECT` message to contain a JWT (Json Web Token). For security reasons, this token has an expiration date embedded which could be short (e.g. 10 minutes). 

Once a device is connected for e.g. more than 10 minutes and then gets disconnected, the re-connection attempt will fail since the password contains now an expired JWT. 

Is there a way of providing a new password before a new connection attempt? If not, would it be possible to add this kind of feature, e.g. through a callback mechanism?

More info:
https://cloud.google.com/iot/docs/how-tos/credentials/jwts

**Comment by jumoog** [comment]
if you look at the examples from google, you can see that the client logs off and then logs on again

Javascript example

```javascript
const secsFromIssue = parseInt(Date.now() / 1000) - iatTime;
if (secsFromIssue > argv.tokenExpMins * 60) {
  iatTime = parseInt(Date.now() / 1000);
  console.log(`\tRefreshing token after ${secsFromIssue} seconds.`);

  client.end();
  connectionArgs.password = createJwt(
    argv.projectId,
    argv.privateKeyFile,
    argv.algorithm
  );
  connectionArgs.protocolId = 'MQTT';
  connectionArgs.protocolVersion = 4;
  connectionArgs.clean = true;
  client = mqtt.connect(connectionArgs);
```

**Comment by icraggs** [comment]
Originally there was no auto reconnect (in the async client).  Reconnection was handled by getting notified in the connectionLost() callback, then calling connect with whatever parameters needed.  This method still works, and would work in this case.

**Comment by jens-f** [comment]
Thanks @icraggs . In that case the client would have to manually handle the re-connection logic that is currently done by paho. Certainly doable but also potentially error prone. I was hoping for something where paho is still handling that part and we can somehow hook into the re-connection logic that decides when to re-connect or how long to wait between attempts. Do you see options for that (e.g. being able to call that logic from outside of paho)?

**Comment by icraggs** [comment]
That assumes my coding is more reliable than yours!

**Comment by keysight-daryl** [comment]
We also have to handle this situation in our code and yes it does open a can of worms in the client app logic.  Would be nice to see this sort of internal reconnect re-auth but for now we have the freedom to just make our jwt expiry much longer and so near-term is not critical for us.

**Comment by icraggs** [comment]
The obvious solution to me is to be able to set a callback which is made just before a reconnection attempt which allows the application to change some set of the connect options.  Not SSL options probably because that would mess up any TLS session resumption optimization.

**Comment by keysight-daryl** [comment]
Totally makes sense

**Comment by jens-f** [comment]
I was able to come with a workaround that worked for me: I'm now setting a timer for the token expiration. When the timer is up, I'm issuing a new `MQTTAsync_connect` call with my updated password, keeping all the other values the same. If the connection is live, it will just keep it open and not disconnect (that's what we'd prefer anyway) and if it's currently not connected it will attempt a new connection immediately (and then falling back to the current retry interval if the connection attempt failed)

From what I could see walking through the source code, this method should just update the password without having two or multiple concurrent `connect` messages now sticking around in paho - it seems like the code base is already checking for this and removing duplicate `connect` messages.

@icraggs Is there any drawbacks you could think of doing this?

**Comment by icraggs** [comment]
@jens-totemic Interesting, I can see that could work, even though I hadn't intended that behaviour.  There's no immediate drawback I can think of.

**Comment by jens-f** [comment]
Great, thanks for confirming Ian!

**Comment by icraggs** [comment]
Fix added to the develop branch.
