### ISSUE TITLE
Persistance->context not freed in MQTTPersistence_close() when using directory

### ISSUE THREAD

**Issue by dadidag** [eclipse-paho/paho.mqtt.c#809]
**Describe the bug**
when using MQTTCLIENT_PERSISTENCE_DEFAULT in MQTTAsync_create() with a directory, e.g.
MQTTAsync_create(&client, url, clid, MQTTCLIENT_PERSISTENCE_DEFAULT, "C:\\MqttPrsistence");
the Paho lib allocates memory to store the directory name.

MQTTAsync_destroy(&client); calls MQTTPersistence_close(Clients *c), but 
MQTTPersistence_close() does NOT free directory name in persistance struct thus leading to memory leak:

Heap element size 48, line 65, file C:\projects\paho-mqtt-c\src\MQTTPersistence.c, ptr 00E079D0

**To Reproduce**
Use directory as persistant storage.

**Expected behavior**
Free directory name in MQTTPersistence_close()

**Screenshots**

** Environment (please complete the following information):**
 - OS: [Win 10]

**Comment by icraggs** [comment]
Fix added to develop branch.
