### ISSUE TITLE
MQTTClient_connectURIVersion is using two different serverURI internally

### ISSUE THREAD

**Issue by LorenzoBe** [eclipse-paho/paho.mqtt.c#813]
MQTTClient_connectURIVersion is internally using two different serverURI variables. One (m->serverURI) is coming from the handle created by MQTTClient_create, the other (serverURI) come as function parameter.

This creates confusion in my use case: I have to init the client with an empty serverURI and subsequently override it calling the MQTTClient_connectURIVersion with the proper serverURI to be used. I had some exceptions and discovered the inconsistency.

In my opinion only the function parameter should be used inside the MQTTClient_connectURIVersion.
Am I loosing some piece?
Thanks

**Comment by icraggs** [comment]
It's not ideal but as it is because of history.

Originally the only option was to have a single serverURI on the connect.  Then a request was made for the ability to switch between several URIs when reconnecting, so that load balancing could be achieved.  That ability was added to the connect options, but the original behaviour couldn't be changed because that would require existing applications to be changed as well.

Does that answer your question?

**Comment by LorenzoBe** [comment]
Thanks, it answers and it is a very useful feature.
However we had a crash when trying to use it because we usually init with empty URI and then we populate the alternative URIs to be used for the connection. But the current code of MQTTClient_connectURIVersion still uses the URI in the client handle to identify the port number and establish the SSL socket, crashing in the SSLSocket_setSocketForSSL.
Maybe these operations should be done on the serverURI passed as a function parameter, that is always populated with the latest selected URI?

See our change in our Paho version to avoid the issue:
```
@@ -885,9 +885,9 @@ static int MQTTClient_connectURIVersion(MQTTClient handle, MQTTClient_connectOpt
 			char* hostname;
 			int setSocketForSSLrc = 0;
 
-			hostname = MQTTProtocol_addressPort(m->serverURI, &port);
+			hostname = MQTTProtocol_addressPort(serverURI, &port);
 			setSocketForSSLrc = SSLSocket_setSocketForSSL(&m->c->net, m->c->sslopts, hostname);
-			if (hostname != m->serverURI)
+			if (hostname != serverURI)
 				free(hostname);
```

Don't know if this is applicable to all use cases.

**Comment by icraggs** [comment]
There is a CI test for the multiple serverURIs behaviour, but it doesn't use TLS.  So I'm pretty sure the non-TLS case works properly.  There is another issue on its use with TLS (#814), so thanks for your suggested code changes.  Having tests for every combination of features is time consuming - it appears this is one area that fell through the cracks.
