### ISSUE TITLE
SSLSocket_setSocketForSSL with serverURIs is not handled correctly

### ISSUE THREAD

**Issue by miks** [eclipse-paho/paho.mqtt.c#814]
When multiple server URIs are used, `SSLSocket_setSocketForSSL` is called for a host that has been set while initialising client. In case when there are empty `serverURI` passed and `serverURIs` used afterward, `SSLSocket_setSocketForSSL` call is created with an empty string and therefore no connection can't be made at all.
Is this intentional?

**Comment by miks** [comment]
I'm not sure whether this is valid approach at all, but adding line to update actual `serverURI` like this https://github.com/miks/paho.mqtt.c/commit/daeb39ad6559e7599917b073a2ebefe3b7650628 finally got serverURIs with wss:// working for me.

**Comment by icraggs** [comment]
Hmm, ok.  Ideally, we should add a test for the use of TLS and websockets for multiple serverURIs.
