### ISSUE TITLE
Websocket connection close packet unmasked

### ISSUE THREAD

**Issue by fraschbi** [eclipse-paho/paho.mqtt.c#821]
**Describe the bug**
When the Paho C client closes a connection over websockets gracefully by sending a DISCONNECT packet. The following Websocket Connection Close [FIN] packet is sent with `Mask: False`. 
This is a protocol violation.

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1.  Connect to any external MQTT broker via websockets
2. Start a packet capture using wireshark on the used port for the connection 
3. Filter for (websocket.mask == false) && (ip.src == your-ip)
4. Disconnect and observe the unmasked packet appearing.

**Expected behavior**
Every Websocket frame sent by the client is masked.

**Screenshots**

<img width="981" alt="screen-github" src="https://user-images.githubusercontent.com/16594392/76116508-1f2ebf80-5fb8-11ea-9523-e1085380db37.png">

** Environment (please complete the following information):**
 - OS: MacOS
 - Version 1.3.1

**Comment by icraggs** [comment]
So @lt-holman, in the code, it appears that you made a deliberate choice to send websocket close and pong frames unmasked.  Do you remember why?

**Comment by lt-holman** [comment]
Probably just to save the mask being sent in the packet.  Simply changing
the has_mask value to  "true" in the web socket create function will
generate a mask.  At least it should.  I've seen a lot of fixes around
large packets in the web socket code.  Admittedly, my original code only
used small packets so good to see those fixes going in now.

**Comment by icraggs** [comment]
Thanks Keith.

**Comment by icraggs** [comment]
Fix added to the develop branch.

**Comment by icraggs** [comment]
@fraschbi if it's possible to confirm the fix works for you, that would be very helpful.  Thanks.

**Comment by fraschbi** [comment]
@icraggs sorry about the delay.
I can confirm that the fix works. Best, Florian

**Comment by icraggs** [comment]
@fraschbi Thanks!
