### ISSUE TITLE
Can not complie on centos5

### ISSUE THREAD

**Issue by ugenehan** [eclipse-paho/paho.mqtt.c#822]
CentOS release 5 (Final)

libpaho-mqtt3a.so.1.3.1: undefined reference to `be64toh'
libpaho-mqtt3a.so.1.3.1: undefined reference to `be32toh'
libpaho-mqtt3a.so.1.3.1: undefined reference to `htobe32'
libpaho-mqtt3a.so.1.3.1: undefined reference to `htobe64'
libpaho-mqtt3a.so.1.3.1: undefined reference to `be16toh'
libpaho-mqtt3a.so.1.3.1: undefined reference to `htobe16'

**Comment by icraggs** [comment]
I note that CentOS 5 went out of support in 2017, having been released in 2007.

Having said that, these functions are used in the WebSockets support, WebSockets.c.  And there are probably equivalents available, as shown by the definition section for Windows:

#define htonll(x) _byteswap_uint64(x)
#define ntohll(x) _byteswap_uint64(x)

#if BYTE_ORDER == LITTLE_ENDIAN
#define htobe16(x)   htons(x)
#define htobe32(x)   htonl(x)
#define htobe64(x)   htonll(x)
#define be16toh(x)   ntohs(x)
#define be32toh(x)   ntohl(x)
#define be64toh(x)   ntohll(x)
#elif BYTE_ORDER == BIG_ENDIAN
#define htobe16(x)   (x)
#define htobe32(x)   (x)
#define htobe64(x)   (x)
#define be16toh(x)   (x)
#define be32toh(x)   (x)
#define be64toh(x)   (x)

At this point I don't know what those equivalents are.

**Comment by icraggs** [comment]
More info needed.
