### ISSUE TITLE
Debug always crash in Visual Studio 2019

### ISSUE THREAD

**Issue by forstef** [eclipse-paho/paho.mqtt.c#833]
It always crash when debug with this library in Visual Studio 2019, whether using the official build or build the mqtt library by myself.
![微信图片_20200326085359](https://user-images.githubusercontent.com/75085/77599495-cd86ae80-6f3f-11ea-96b4-05ac58b3b262.png)
![微信图片_20200326085508](https://user-images.githubusercontent.com/75085/77599496-ceb7db80-6f3f-11ea-81c0-d7e5436e4365.png)
![微信图片_20200326085515](https://user-images.githubusercontent.com/75085/77599497-d0819f00-6f3f-11ea-9477-e017b3fac583.png)

But it runs normally when you directly runing it.
![微信图片_20200326090039](https://user-images.githubusercontent.com/75085/77599623-4b4aba00-6f40-11ea-88df-342cd437c1a5.png)

Confusing, Is this library unfriendly to windows platform?

**Comment by icraggs** [comment]
I don't think there is any issue with Windows per se.  I used to use Visual Studio for building in Windows all the time but supporting different versions of Visual Studio projects became too time consuming when CMake was an alternative.

**Comment by icraggs** [comment]
If you have any suggestions for changes needed, you could let us know or submit a PR.
