### ISSUE TITLE
gcc-cross issue:aarch64-linux-gnu/bin/ld: cannot find -lpaho-mqtt3a

### ISSUE THREAD

**Issue by guoyanzhang0817** [eclipse-paho/paho.mqtt.c#836]
mv  main.o ec_uart_232.o ec_manage_plce.o ec_socket_video.o ec_mqtt_android.o ./output/
aarch64-linux-gnu-gcc -o ./output/ecSmartFire ./output/*  -O2 -Wall -Wcomment -Wformat -Wmissing-braces -Wswitch -Wuninitialized -Wbad-function-cast -Waggregate-return -Wmultichar -Wsign-compare -Wshadow -lpthread  -gdwarf-2 -g -lpaho-mqtt3a -ljson-c
/usr/lib/gcc-cross/aarch64-linux-gnu/8/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible //usr/local/lib/libpaho-mqtt3a.so when searching for -lpaho-mqtt3a
/usr/lib/gcc-cross/aarch64-linux-gnu/8/../../../../aarch64-linux-gnu/bin/ld: cannot find -lpaho-mqtt3a
/usr/lib/gcc-cross/aarch64-linux-gnu/8/../../../../aarch64-linux-gnu/bin/ld: cannot find -ljson-c
collect2: error: ld returned 1 exit status
make: *** [Makefile:32: ecSmartFire] Error 1

=========================

**Comment by guoyanzhang0817** [comment]
i have solved it.   Because i used the old version  MQTT*.h

**Comment by anudeep010291** [comment]
@guoyanzhang0817 Can you please let us know how to sort this. I am facing the same issue. This is the error i have been getting.
/home/mindlogic/octane_etk-6.0.0.240/arm-toolchain/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.1/../../../../arm-none-linux-gnueabi/bin/ld: 
cannot find -lpaho-mqtt3c

**Comment by guoyanzhang0817** [comment]
> @guoyanzhang0817 Can you please let us know how to sort this. I am facing the same issue. This is the error i have been getting.
> /home/mindlogic/octane_etk-6.0.0.240/arm-toolchain/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.1/../../../../arm-none-linux-gnueabi/bin/ld:
> cannot find -lpaho-mqtt3c
@anudeep010291  anudeep010291  about my question, i just change the new header files that just compiled.
