### ISSUE TITLE
why i modify the Makefile, CC=aarch64-linux-gnu-gcc，it is useless, i must run the command 'make cc=aarch64-linux-gnu-gcc'?

### ISSUE THREAD

**Issue by guoyanzhang0817** [eclipse-paho/paho.mqtt.c#837]
why i modify the Makefile, CC=aarch64-linux-gnu-gcc，it is useless, i must run the command 'make cc=aarch64-linux-gnu-gcc'?

thanks.

**Comment by icraggs** [comment]
I'm not sure what you're asking here.  If you want to override the compiler in the Makefile you can use the command template:

make CC=your-compiler

**Comment by icraggs** [comment]
So I tried this and it works.
