### ISSUE TITLE
 with debug_info, it mean lib has open debug, i want to close it.

### ISSUE THREAD

**Issue by guoyanzhang0817** [eclipse-paho/paho.mqtt.c#838]
with debug_info, it mean lib has open debug, i want to close it.

**Comment by guoyanzhang0817** [comment]
/usr/local/lib/libpaho-mqtt3a.so.1.0: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2958df2eda81db1b6a9477ab05e029c5264fb42f, with debug_info, not stripped

**Comment by guoyanzhang0817** [comment]
What's the impact on the code when open debug？

**Comment by icraggs** [comment]
Linux binaries are normally shipped with debug info, to aid debugging if there is crash or other problem.

**Comment by guoyanzhang0817** [comment]
Previous versions didn't seem to add debug

**Comment by icraggs** [comment]
You can strip the debug info from libraries on Linux with the strip command.

**Comment by icraggs** [comment]
I think I've answered this one.
