### ISSUE TITLE
Message lose in default persistent mode

### ISSUE THREAD

**Issue by mqueack** [eclipse-paho/paho.mqtt.c#839]
**Describe the bug**
Starting the publish client without network connection. And publishing messages, seems not to send the message after connection is established.
The messages seems to be stored on the filesystem, but never reach my broker if the connection is established.

**To Reproduce**
- I use the paho.mqtt.cpp library which uses the paho.mqtt.c library.
- For testing i used this example:
https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/samples/data_publish.cpp
- Only changes if done:
 1. Change the address to my vernemq-Broker
 2. Add ssl connection options
 3. Set send period to 1
 4. remove the connection wait
change from `cli.connect(connOpts)->wait();`
to `cli.connect(connOpts);`
 5. Change QOS to `2`

I removed the blocking wait, because on startup at most time there is no connection to the internet possible.
To simulate an non existing connection in my office i added
`route add -host <brokerip> reject `
and remove it to make an connection possible
`route del -host <brokerip> reject`

After the connection is established all new published messages arrived on my broker, but not the messages stored before connection established.

**Environment:**
 - OS: Linux (arm)
 - phao.mqtt.c: 1.3.1
 - paho.mqtt.cpp: 1.1
 - Broker: vernemq(docker)

**Additional context**
Is there an misconfiguration of my client or a bug in the default persistence mode?

**Comment by keysight-daryl** [comment]
We had this same issue.  Very glad to see it slated for 1.3.3

**Comment by icraggs** [comment]
Currently the behaviour is not to accept messages when disconnected before connect has been called (which is going to change).  So I'm unsure what's happening here.

Taking a trace, as described in the readme, should give a better idea of what is going on.

**Comment by icraggs** [comment]
I tried this, and it worked for me.  On these conditions:

1. a successful return from send().  This needs a) to have successfully previously connected or b) in the current develop branch set the create option allowDisconnectedSendAtAnyTime to 1.
2. the cleansession connect option set to 0.  Otherwise the messages will be cleaned up on a successful connect.

**Comment by icraggs** [comment]
Actually, this is also affected by #640.  The session state cleanup removes queued up messages.  As a result of the change for #640, condition 2) above, won't be needed.
