### ISSUE TITLE
MQTTCLIENT_PERSISTENCE_DEFAULT - Limiting disk usage

### ISSUE THREAD

**Issue by prateek-khatri** [eclipse-paho/paho.mqtt.c#842]
While configuring the client for `MQTTCLIENT_PERSISTENCE_DEFAULT` is there any way to control how much disk usage the library can use? 
Is it possible to have a circular buffer based storage that would overwrite the oldest message if the specified size is reached?

If not, what would be the ideal way to use `MQTTCLIENT_PERSISTENCE_USER` for achieving that?
We have disk space constraints on our system and the software is to run for days/weeks at a time, this could cause the disk to run out of space.

Also, if we are to use `MQTTAsync_createWithOptions()` will it buffer the messages sent while being disconnected in memory or the directory path provided by the persistence options?

**Comment by icraggs** [comment]
No, currently there isn't.  But I'm planning to look at persistence in the next release.

**Comment by keysight-daryl** [comment]
We have the exact same requirement and have currently implemented custom persistence with a purge oldest type circular buffer however other issues within persistence have prevented us from actually using persistence at all.  Really looking forward to this capability being added to the default behaviors.  A second persistence feature we require is that all persisted data be encrypted/decrypted into and out of persistent storage.  Currently our custom layer uses tiny-aes and a configurable key but it would be really nice for this to also be an internal option.

**Comment by icraggs** [comment]
#441 There is now the option to discard oldest queued messages when the max number of queued messages is reached.  (In soon to be released 1.3.5).
