### ISSUE TITLE
Mqtt 5 usage desciption

### ISSUE THREAD

**Issue by forstef** [eclipse-paho/paho.mqtt.c#845]
**Is your feature request related to a problem? Please describe.**
How to use mqtt 5 features, it should provide some demos, such as user properties, .etc

I encountered a problem when I was using the MQTTProperties:

`
typedef struct
{
  enum MQTTPropertyCodes identifier; /**<  The MQTT V5 property id. A multi-byte integer. */
  /** The value of the property, as a union of the different possible types. */
  union {
    unsigned char byte;       /**< holds the value of a byte property type */
    unsigned short integer2;  /**< holds the value of a 2 byte integer property type */
    unsigned int integer4;    /**< holds the value of a 4 byte integer property type */
    struct {
      MQTTLenString data;  /**< The value of a string property, or the name of a user property. */
      MQTTLenString value; /**< The value of a user property. */
    };
  } value;
} MQTTProperty;
`

There is no demo about this.

**Comment by icraggs** [comment]
There are examples of use of MQTT 5.0 properties in the samples paho_c_pub, paho_cs_pub, paho_c_sub and paho_cs_sub.

**Comment by forstef** [comment]
I see the code about user property with name and value:

property.identifier = MQTTPROPERTY_CODE_USER_PROPERTY;
			property.value.data.data = opts.user_property.name;
			property.value.data.len = (int)strlen(opts.user_property.name);
			property.value.value.data = opts.user_property.value;
			property.value.value.len = (int)strlen(opts.user_property.value);
			MQTTProperties_add(&props, &property);

but how about request/response pattern setting, where to put the response topic?

**Comment by fpagliughi** [comment]
I created compatible MQTT v5 RPC samples for the C++, Rust, and Python libraries. It's a simple service for basic math functions using JSON as the exchange format. I'm also going to post a blog about it in the next week or two. The C++ samples are here:

https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/samples/rpc_math_cli.cpp
https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/samples/rpc_math_srvr.cpp

I'll get samples for the C library shortly as well.

**Comment by icraggs** [comment]
There are also articles on my blog about MQTT 5.0 and its features: https://modelbasedtesting.co.uk/?s=MQTT+5

and various other information around the web for instance: https://www.hivemq.com/mqtt-5/

**Comment by forstef** [comment]
@fpagliughi Thanks for your examples, they are excellent demos.
@icraggs very detailed articles about MQTT 5.0.

I just have a little confusing about the MQTTProperty struct, when I am about to put the response topic to it, because the topic itself doesn't have key-value struct, so I think I can put it ether in data or value is ok. I just think it is not perfect match the field pattern for storage, the "data" field is not necessary in this situation.
![微信图片_20200420095520](https://user-images.githubusercontent.com/75085/79706873-41bd3380-82ed-11ea-838a-78549189ef68.png)

**Comment by fpagliughi** [comment]
Yes, I admit this is a little confusing (sorry, @icraggs!).

The Response Topic is a (single) string property. So you would set the `data` field to the value that you want to send (i.e. the response topic string). You leave the `value` field Zero/NULL.

And, of course, you set the identifier to `MQTTPROPERTY_CODE_RESPONSE_TOPIC` (0x08).

If you want to send a property that requires a string pair (like a user property), then you set `data` to the key and `value` to the value.

**Comment by icraggs** [comment]
Well, the comments do explain!

**Comment by forstef** [comment]
@fpagliughi Thanks for your explanation !
