### ISSUE TITLE
MQTTClient_strerror misses MQTTCLIENT_BAD_MQTT_VERSION

### ISSUE THREAD

**Issue by tbeu** [eclipse-paho/paho.mqtt.c#847]
MQTTClient_strerror of v1.3.2 reports "Unknown error code -11" for MQTTCLIENT_BAD_MQTT_VERSION, thus MQTTCLIENT_BAD_MQTT_VERSION is not handled in MQTTClient_strerror with a proper error message.

**Comment by icraggs** [comment]
Would you like to open a PR with the missing definitions? :-)
