### ISSUE TITLE
Linking issue with static library and cmake

### ISSUE THREAD

**Issue by atomcraft-th** [eclipse-paho/paho.mqtt.c#848]
**Describe the bug**
When I build with cmake and enable the PAHO_BUILD_STATIC option I get a linker error as it is missing libdl.
[ 49%] Linking C executable MQTTVersion-static
/usr/bin/ld: CMakeFiles/MQTTVersion-static.dir/MQTTVersion.c.o: in function `loadandcall':
MQTTVersion.c:(.text+0x264): undefined reference to `dlopen'
/usr/bin/ld: MQTTVersion.c:(.text+0x278): undefined reference to `dlerror'
/usr/bin/ld: MQTTVersion.c:(.text+0x2a0): undefined reference to `dlsym'
/usr/bin/ld: MQTTVersion.c:(.text+0x2c0): undefined reference to `dlsym'
/usr/bin/ld: MQTTVersion.c:(.text+0x2f4): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status

**To Reproduce**
cmake /path/to/src -DPAHO_BUILD_STATIC=ON
make

** Environment (please complete the following information):**
 - OS: linux (tried on raspbian and ubuntu)
 - library version 1.3.2

Can be fixed by inserting:
TARGET_LINK_LIBRARIES(MQTTVersion-static ${LIBS_SYSTEM})
after line 91 of src/CMakelists.txt

** FYI does the new dependency on uthash-dev need adding to the REAME?

**Comment by icraggs** [comment]
It works if you turn off the shared build, which is on by default, at the same time.  -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SHARED=FALSE.  Not sure why.

Also, that MQTTVersion doesn't really make sense in a static form, so we could just remove the static version.

**Comment by bryant-ferguson** [comment]
@icraggs Can you elaborate on why version 1.3.2 does not make sense as a static library and for how many versions that has been the case?

**Comment by fpagliughi** [comment]
In this case, `MQTTVersion` is referring to a sample application which can give you information about the shared Paho C libraries installed on the system. Like:
```
$ ./MQTTVersion 
MQTTVersion: print the version strings of an MQTT client library
Copyright (c) 2012, 2018 IBM Corp.
Specify a particular library name if it is not in the current directory, or not executable on this platform
--- Trying library paho-mqtt3c ---
Product name: Eclipse Paho Synchronous MQTT C Client Library
Version: 1.3.2
Build level: 2020-05-28T18:03:15Z
--- Trying library paho-mqtt3cs ---
Product name: Eclipse Paho Synchronous MQTT C Client Library
Version: 1.3.2
Build level: 2020-05-28T18:03:15Z
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
OpenSSL flags: compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-kxN_24/openssl-1.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OpenSSL build timestamp: built on: Tue Nov 12 16:58:35 2019 UTC
OpenSSL platform: platform: debian-amd64
OpenSSL directory: OPENSSLDIR: "/usr/lib/ssl"
...
```
This is useful because new versions of the library can be installed on your system without recompiling the apps (they're shared libraries after all).

This wouldn't be necessary with static linking since the library your app is linked to can't change. The version that was linked in remains constant for the life of the app.
