### ISSUE TITLE
struct timeval is an incomplete type in MQTTTime.h

### ISSUE THREAD

**Issue by ppaul1989** [eclipse-paho/paho.mqtt.c#851]
**Target Platform** 
Android

**Issue:**
While building paho.c for Linux struct timeval fails with error :
In file included from paho.mqtt.c/src/MQTTPersistence.c:29:
In file included from paho.mqtt.c/src/MQTTPersistence.h:27:
paho.mqtt.c/src/Clients.h:59:18: error: field has incomplete type 'struct timeval'
        START_TIME_TYPE lastTouch;                  /**> used for retry and expiry */
                        ^
paho.mqtt.c/src/MQTTTime.h:33:1: note: forward declaration of 'struct timeval'
START_TIME_TYPE MQTTTime_start_clock(void);
^
paho.mqtt.c/src/MQTTTime.h:28:32: note: expanded from macro 'START_TIME_TYPE'
#define START_TIME_TYPE struct timeval

**Possible fix**
Add #include <sys/time.h> do define timeval in MQTTTime.h when timeval is used.

**Comment by icraggs** [comment]
Evidently not all Linux distros, otherwise the Travis build wouldn't work.

Thanks.
