### ISSUE TITLE
About MQTTAsync_messageArrived

### ISSUE THREAD

**Issue by forstef** [eclipse-paho/paho.mqtt.c#852]
![image](https://user-images.githubusercontent.com/75085/79818598-c629b800-83ba-11ea-839f-abc5c87512ba.png)

Well, according to MQTT Version 5.0 OASIS Standard 07 March 2019:
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901241
![image](https://user-images.githubusercontent.com/75085/79819685-13a72480-83bd-11ea-80ab-8e646e7fcef7.png)

We do no need to worry about topic would have null charactors, so I think the topicLen is unnecessary.

**Comment by icraggs** [comment]
This client library was written in the age of MQTT 3.1, and still supports that specification, although its use is probably minimal now and decreasing.  It also supports the MQTT 3.1.1 and 5.0 standards.  MQTT 3.1 did not restrict the content of topic names.

**Comment by forstef** [comment]
OK.
