### ISSUE TITLE
Build fails for windows: Calling convention missing for InitOnceFunction in MQTTClient.c

### ISSUE THREAD

**Issue by mkfix** [eclipse-paho/paho.mqtt.c#856]
**Bug Description**
Building Paho C 1.3.0 in Windows 10 and as STATIC library fails with `MQTTClient.c(376): error C2440: 'function': cannot convert from 'BOOL (__cdecl *)(PINIT_ONCE,PVOID,PVOID *)' to 'PINIT_ONCE_FN'`

**Reproduce**
CMake build definitions: Build with STATIC - ON and SHARED - OFF
```
SET(PAHO_WITH_SSL FALSE CACHE BOOL "Flag that defines whether to build ssl-enabled binaries too. ")
SET(PAHO_BUILD_SHARED FALSE CACHE BOOL "Build shared library")
SET(PAHO_BUILD_STATIC TRUE CACHE BOOL "Build static library")
SET(PAHO_BUILD_DOCUMENTATION FALSE CACHE BOOL "Create and install the HTML based API documentation (requires Doxygen)")
SET(PAHO_BUILD_SAMPLES FALSE CACHE BOOL "Build sample programs")
SET(PAHO_BUILD_DEB_PACKAGE FALSE CACHE BOOL "Build debian package")
SET(PAHO_ENABLE_TESTING FALSE CACHE BOOL "Build tests and run")
SET(PAHO_ENABLE_CPACK TRUE CACHE BOOL "Enable CPack")
```
Build paho.mqtt.c
```
mkdir build.paho
cd build
cmake ..
cmake --build .
```

Build fails with following warning and error
`\MQTTClient.c(376): warning C4024: 'InitOnceExecuteOnce': different types for formal and actual parameter 2`
`MQTTClient.c(376): error C2440: 'function': cannot convert from 'BOOL (__cdecl *)(PINIT_ONCE,PVOID,PVOID *)' to 'PINIT_ONCE_FN' `
[cmake.log](https://github.com/eclipse/paho.mqtt.c/files/4521647/cmake.log)
[build_fail.log](https://github.com/eclipse/paho.mqtt.c/files/4521648/build_fail.log)

**Expected behavior**
Build success

**Environment**
- OS: Windows
- Version: 10
-  Visual Studio 15 2017

**Root cause**
`InitOnceExecuteOnce `expects 2nd argument (`InitOnceFunction`) with calling function `__stdcall`. But function `InitOnceFunction `is missing the calling convention `__stdcall`.

**Fix**
Add calling convention using `WINAPI `to `InitOnceFunction` function.
`BOOL WINAPI InitOnceFunction`
Pull request: #855
[build_pass.log](https://github.com/eclipse/paho.mqtt.c/files/4521661/build_pass.log)

**Comment by icraggs** [comment]
Interesting, the AppVeyor build doesn't fail: https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c/builds/32327995/job/0b0v30ddti80axp8

I can see that the definition is not quite right.  In MQTTAsync.c, it's defined with CALLBACK rather than WINAPI and the documentation shows that: https://docs.microsoft.com/en-us/windows/win32/sync/using-one-time-initialization.

So I think it ought to be CALLBACK.

**Comment by icraggs** [comment]
Thanks.
