### ISSUE TITLE
Can MQTTLenString hold binary bytes?

### ISSUE THREAD

**Issue by forstef** [eclipse-paho/paho.mqtt.c#862]
can MQTTLenString hold non ascii characters?
for example :  MQTTLenString in MQTTProperty.

MQTTLenString has length field, hence I think it can hold binary bytes, am I right?

**Comment by fpagliughi** [comment]
Usually in the library, if the struct has a 'len' field, it's a pretty good indicator that it can be used for arbitrary binary data. In the case of the MQTT v5 Properties, however, the protocol has very specific types that can be used with each different property. Look at the spec for which ones are designated "Binary Data" as opposed to "UTF-8 Encoded String"
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901027

**Comment by icraggs** [comment]
The general answer is yes.  These are strings in the traditional C sense - an array of char types which are bytes that can hold any value from -127 to 128.  They are length delimited to distinguish them from traditional C strings which are length delimited.

As Frank says, the MQTT V5 spec defines the contents of each property.  Also the MQTTProperties.c file in the nameToType structure describes the data type of each MQTT 5.0 property type.

**Comment by forstef** [comment]
OK.
