### ISSUE TITLE
Calling the function MQTTClient_setCallbacks results in very slow publish

### ISSUE THREAD

**Issue by Zhuzhongwei** [eclipse-paho/paho.mqtt.c#863]
**Describe the bug**
I want to publish a message (128K byte) all the time , as the same time, I subscribe a topic "start",  so before MQTTClient_connect to connect the server, call MQTTClient_setCallbacks to set callback function.  test code:

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "MQTTClient.h"

#define ADDRESS     "tcp://192.168.16.12:5883"
#define CLIENTID    "40000001_sub"
#define TOPIC       "start"
#define PAYLOAD     "Hello World!"
#define QOS         0
#define TIMEOUT     10000L

MQTTClient_deliveryToken deliveredtoken;

void delivered(void *context, MQTTClient_deliveryToken dt)
{
    printf("Message with token value %d delivery confirmed\n", dt);
    deliveredtoken = dt;
}

int msgarrvd(void *context, char *topicName, int topicLen, MQTTClient_message *message)
{
    printf("Message arrived\n");
    printf("     topic: %s\n", topicName);
    printf("   message: %.*s\n", message->payloadlen, (char*)message->payload);
    MQTTClient_freeMessage(&message);
    MQTTClient_free(topicName);
    return 1;
}

void connlost(void *context, char *cause)
{
    printf("\nConnection lost\n");
    printf("     cause: %s\n", cause);
}

void test_publish(MQTTClient client, char *wave, int len)
{
    MQTTClient_message pubmsg = MQTTClient_message_initializer;
    MQTTClient_deliveryToken token;
    int rc;

    pubmsg.payload = wave;
    pubmsg.payloadlen = len;
    pubmsg.qos = QOS;
    pubmsg.retained = 0;
    MQTTClient_publishMessage(client, "wave", &pubmsg, &token);

    rc = MQTTClient_waitForCompletion(client, token, 10000L);
    printf("Message with delivery token %d delivered, rc = %d\n", token, rc);

}

int main(int argc, char* argv[])
{
    MQTTClient client;
    MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
    int rc;
	
	
	unsigned short tmp[128 * 1024];
	for (int kk = 0;kk < 128 * 1024;kk++)
		tmp[kk] = kk;

	int haha = 10;

    if ((rc = MQTTClient_create(&client, ADDRESS, CLIENTID,
        MQTTCLIENT_PERSISTENCE_NONE, NULL)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to create client, return code %d\n", rc);
        rc = EXIT_FAILURE;
        goto exit;
    }
#if 1
    if ((rc = MQTTClient_setCallbacks(client, NULL, connlost, msgarrvd, delivered)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to set callbacks, return code %d\n", rc);
        rc = EXIT_FAILURE;
        goto destroy_exit;
    }
#endif
    conn_opts.keepAliveInterval = 20;
    conn_opts.cleansession = 1;
    if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to connect, return code %d\n", rc);
        rc = EXIT_FAILURE;
        goto destroy_exit;
    }
	printf("connect ok.....\n");
	
	#if 1
	while (haha--) {

		printf("send....\n");

		test_publish(client, (char*)&tmp[0], 128 * 1024);

	}
	#endif

    printf("Subscribing to topic %s\nfor client %s using QoS%d\n\n"
           "Press Q<Enter> to quit\n\n", TOPIC, CLIENTID, QOS);
    if ((rc = MQTTClient_subscribe(client, TOPIC, QOS)) != MQTTCLIENT_SUCCESS)
    {
    	printf("Failed to subscribe, return code %d\n", rc);
    	rc = EXIT_FAILURE;
    }
    else
    {
		
		while(1) {
			//todo
			sleep(10);
		}
	
    	int ch;
    	do
    	{
        	ch = getchar();
    	} while (ch!='Q' && ch != 'q');

        if ((rc = MQTTClient_unsubscribe(client, TOPIC)) != MQTTCLIENT_SUCCESS)
        {
        	printf("Failed to unsubscribe, return code %d\n", rc);
        	rc = EXIT_FAILURE;
        }
    }

    if ((rc = MQTTClient_disconnect(client, 10000)) != MQTTCLIENT_SUCCESS)
    {
    	printf("Failed to disconnect, return code %d\n", rc);
    	rc = EXIT_FAILURE;
    }
destroy_exit:
    MQTTClient_destroy(&client);
exit:
    return rc;
}

As above， after compiling and running,  The published message takes a long time(1s) to reach the server.  However,when I remove calling function MQTTClient_setCallbacks, the publish  will become very fast(10ms)

** Environment **
 - OS:  ubuntu 14.04
 - Version:  paho mqtt 1.3.2

**Comment by icraggs** [comment]
It's because of the timeout setting of 1000 ms in run().  Changing it to 100 ms to match the other timeout value seems to remedy well enough.

**Comment by icraggs** [comment]
(It's actually the connect that takes the long time rather than the publish)
