### ISSUE TITLE
Add persistence tests for websockets

### ISSUE THREAD

**Issue by icraggs** [eclipse-paho/paho.mqtt.c#865]
Ensure there are tests for websockets and persistence (including using a persistence store created with a tcp connection and then read with websockets, and vice versa).

**Comment by keysight-daryl** [comment]
not sure how to make this happen but also these tests should exercise lost broker connections and reconnects when the dropped connection is either client or broker side (broker upgrades/disconnects etc.)

**Comment by icraggs** [comment]
There is already a network proxy used within the tests to break connections.  It might need some work to support websockets, but that shouldn't be a problem.  There's also the test broker which can have behaviour added specifically for testing.

**Comment by icraggs** [comment]
First set: https://github.com/eclipse/paho.mqtt.c/commit/f8a111b5cdf7f438ebd7c70a6946c180e8ddbbc6
