### ISSUE TITLE
Option for persistence encryption via application callback

### ISSUE THREAD

**Issue by keysight-daryl** [eclipse-paho/paho.mqtt.c#866]
Our product requires all data at rest to be encrypted using AES encryption (for military customers, etc).  Currently we implement this within Paho to use tiny-aes within custom persistence pget/put to encrypt/decrypt all data in and out of the persistent storage using a configuration key.  If no (empty) key is specified it just doesn't perform encryption.  In combination with also requiring rolling message store for disk space limitations it has forced us to customize the persistence however other issues have prevented us from having success in this venture.  It would be great if Paho's default persistence also supported optional encryption in addition to message rolling limitations so that we may rely solely on the default behavior and avoiding the common mistakes and pitfalls of persistence customization.

**Comment by icraggs** [comment]
Perhaps separate callbacks to allow encryption/decryption of the data regardless of the persistence mechanism used?

**Comment by keysight-daryl** [comment]
That would be even better, nice idea!
