### ISSUE TITLE
'Single-session' behavior 

### ISSUE THREAD

**Issue by icraggs** [eclipse-paho/paho.mqtt.c#869]
Our client would like a sort of 'single-session' behavior where no matter the broker url or client id all persistence is always going to and coming from a single folder on disk. In other words no matter the broker the same persistence messages are in the session.

**Comment by icraggs** [comment]
@keysight-daryl I'm not sure what this actually entails.  it can't work for messages that are in-flight (partially sent), but I assume this is for messages that have been queued for later sending.  

What's the purpose?  To allow any queued message to be sent to the next MQTT connection?  Why are there multiple MQTT connections (high availability)?

**Comment by keysight-daryl** [comment]
Right, persisted messages really because when a client goes offline for a long time and later reconnects it may auth against a different broker url or get redirected.  What we don't want is to manage multiple persist folders (sessions) and lose any of those messages regardless of where it reconnects to.  Additionally we don't want to have to periodically garbage collect dead sessions that would forever fill up the disk.

**Comment by icraggs** [comment]
There is already a "high-availability" mechanism in the connect options.  Rather than specifying one URL, you specify a set of alternatives which are cycled between in case one or more are down.  It sounds like this, or an extension of it.

Who decides upon the different URL, and when?  How would redirection work?

**Comment by keysight-daryl** [comment]
It is configured server side by the customer so wouldn't really be known ahead of time either.  The list of urls is only known after auth.  we also will be using zeroconf to find local network auth servers.  I think the use case needs to be simpler then what the high-availability offers since we want any broker it connects to regardless of url to always persist into and out of the same folder.

**Comment by keysight-daryl** [comment]
the web response to our auth calls are expected to return a web redirect to whichever auth server is online to handle the request and in a multi-tenant sort of way dynamically based on the clientId, deviceId, etc. this redirect sends us to the auth server who also based on whatever customer configurations will return us the broker url in the jwt token.  these urls can't be predicted ahead of time and may change from one connect to the next. we can afford to lose the in-transit messages that are not persisted between different brokers but ultimately all brokers forward these messages on to the back-end which could care less where they came from or how they got there.

**Comment by fpagliughi** [comment]
Can't this be done pretty easily with the user-defined persistence hooks?

**Comment by keysight-daryl** [comment]
Right but with these persistence improvements the goal is to not need to stray from the default persistence behavior to prevent the untested waters and other gotchas that are hard to predict.  These are the 3 things needed by the default persistence to satisfy all the needs...

- Rotating where the oldest messages are dropped
- Encryption at rest
- Single Session

Currently our project does these 3 things in a custom persistence around the cpp library however it isn't easy to get this right and additional hooks into paho.c would really improve the stability of an end to end solid solution that is well considered in light of the intricacies of the underlying library architecture.

**Comment by keysight-daryl** [comment]
Also, I think in terms of Single Session in particular the majority of embedded systems or agents expect to be dealing with a single back-end server in terms of state mgmt and fault tolerance despite the url of the broker in the middle. A callback to assign the session identifier with the default being the current broker url markup might be the most flexible solution.

**Comment by icraggs** [comment]
This still sounds like the "high availability" scenario to me.   Is it essentially changing the URI of the server to connect to, while using the same store of messages for that particular client?  That's what the high availability function does.

If the proposed auto reconnect callback allows the URI to be changed as well as other connect options maybe that will work.

How is the URI decided upon - who does that determination and when?  Is that done by the application before any MQTT reconnect, or as part of the TCP/MQTT connection process somehow?  Can you give a more specific example - the steps involved?

**Comment by keysight-daryl** [comment]
1. Client performs mDNS resolution of auth url
2. Client makes https auth call to get jwt token
3. Client gets http redirect to some other auth server configured by the admin of the server farm
4. Client finally gets jwt auth token with specific broker url depending on what's online and available at the moment
5. Client connects to broker which is expecting all messages persisted regardless of previous broker connection

**Comment by icraggs** [comment]
Thanks. So yes, step 5 is pretty much what the "high availability" feature does.

The question is how to direct it.  How long is the information gathered in step 4 valid for?

**Comment by keysight-daryl** [comment]
No guarantees.  Currently out jwt tokens are set to expire at a huge interval because of the reconnect issues and not having the re-auth callback.  The broker url is valid until it gets pulled offline.  We don't have exact answers here as our system will be installed into customer sites and managed by them.

**Comment by keysight-daryl** [comment]
I was reviewing the code in search of this "high availability" feature with no luck.  Are you referring to the list of URIs in connect options?  If so we do not receive a list of URIs during our auth call we only receive one, the one we are to connect to with the corresponding jwt (this jwt would be invalid connecting to any other broker URI).  The persistence issue occurs when connecting to some other URI to the one it connected to in a previous runtime where there were persisted messages on disk in a folder named according to the default URI markup.  These messages thus never get sent and are essentially tied to that URI that no longer exists.  I might have mis-stated the concept of what I meant by 'single session'.  I was taking that URI markup folder name as being the 'session'.  What I really meant was single message store (persist folder) across all runtimes no matter the broker URI.

**Comment by icraggs** [comment]
Yes, the serverURI list.  There need only be one entry in the list.  

The key used for the persistence store (folder) is the URI given in the create call, but the URI used for connecting is the one in the serverURI list.  The latter can change (or we can add the facility for updating if needs be - I'll test it) but the stored messages are keyed off that main URI which doesn't have to be valid.

You can consider the create() URI a pointer to the store, which has to stay the same, but the 'real' URI to be used is that in the serverURI list, which can change.  (Of course only one MQTT client instance should access the same message persistence folder at the same time).

**Comment by keysight-daryl** [comment]
Ah ok then that wasn't clear to me at all, was it described in this way somewhere I must have missed? Will have to take a deeper look I guess.   So the create call URI isn't really a URI at all is it or is it actually used as a traditional URI somewhere in the library? It might make sense to rename that create URI to better reflect what it is used for.  Our application only ever uses a single client instance.

**Comment by keysight-daryl** [comment]
In any case yeah the later does and will change every runtime and possibly every auth expiry reconnect during a single runtime while the persistence folder name should never change at least not in our use case.

**Comment by icraggs** [comment]
@keysight-daryl the create URI is used if you don't specify anything in the serverURIs list.  This is the sort of thing that happens when new function is added later on, and you have to support the existing behaviour too, unless you want to change the major version number of the API (2.x.x).  So originally there was only the URI on the create, then later came the request for "high availability", or the ability to switch between a set of alternative URIs dynamically.  To support this, the serverURI list was added to the connect options, but if there's nothing in the list, we default back to the original behaviour of using the create URI.

If you use the serverURI list, then the create URI is not used for anything - apart from one of the components of the persistence directory name.  But this can work for us in this scenario too.  Use the serverURI list to dynamically update the URI to use for connect.  It's pretty close to that behaviour already.  Allowing updating of connect options when retrying (#808) will mean that the serverURI can be changed and used on the next connect.

**Comment by icraggs** [comment]
@keysight-daryl I think that with the change in #808 in the develop branch (or with the workaround described therein) and the use of the serverURIs, this will work now.
