### ISSUE TITLE
1.3.2 fails to build with openssl 1.0.2

### ISSUE THREAD

**Issue by nullr0ute** [eclipse-paho/paho.mqtt.c#871]
**Describe the bug**
When building the 1.3.2 release for Fedora and EL7 it built fine with Fedora (openssl 1.1.1.g) but fails when building for el8 with openssl 1.0.2. Output below.

**To Reproduce**
<pre>
Building C object test/CMakeFiles/test10.dir/test10.c.o
cd /builddir/build/BUILD/paho.mqtt.c-1.3.2/build.paho/test && /usr/bin/cc   -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -I/builddir/build/BUILD/paho.mqtt.c-1.3.2/test -I/builddir/build/BUILD/paho.mqtt.c-1.3.2/src    -o CMakeFiles/test10.dir/test10.c.o   -c /builddir/build/BUILD/paho.mqtt.c-1.3.2/test/test10.c
/usr/bin/cc  -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -Wl,-init,MQTTClient_init  -Wl,-z,relro  -shared -Wl,-soname,libpaho-mqtt3cs.so.1 -o libpaho-mqtt3cs.so.1.3.2 CMakeFiles/paho-mqtt3cs.dir/MQTTClient.c.o CMakeFiles/paho-mqtt3cs.dir/SSLSocket.c.o CMakeFiles/common_ssl_obj.dir/MQTTTime.c.o CMakeFiles/common_ssl_obj.dir/MQTTProtocolClient.c.o CMakeFiles/common_ssl_obj.dir/Clients.c.o CMakeFiles/common_ssl_obj.dir/utf-8.c.o CMakeFiles/common_ssl_obj.dir/MQTTPacket.c.o CMakeFiles/common_ssl_obj.dir/MQTTPacketOut.c.o CMakeFiles/common_ssl_obj.dir/Messages.c.o CMakeFiles/common_ssl_obj.dir/Tree.c.o CMakeFiles/common_ssl_obj.dir/Socket.c.o CMakeFiles/common_ssl_obj.dir/Log.c.o CMakeFiles/common_ssl_obj.dir/MQTTPersistence.c.o CMakeFiles/common_ssl_obj.dir/Thread.c.o CMakeFiles/common_ssl_obj.dir/MQTTProtocolOut.c.o CMakeFiles/common_ssl_obj.dir/MQTTPersistenceDefault.c.o CMakeFiles/common_ssl_obj.dir/SocketBuffer.c.o CMakeFiles/common_ssl_obj.dir/LinkedList.c.o CMakeFiles/common_ssl_obj.dir/MQTTProperties.c.o CMakeFiles/common_ssl_obj.dir/MQTTReasonCodes.c.o CMakeFiles/common_ssl_obj.dir/Base64.c.o CMakeFiles/common_ssl_obj.dir/SHA1.c.o CMakeFiles/common_ssl_obj.dir/WebSocket.c.o CMakeFiles/common_ssl_obj.dir/StackTrace.c.o CMakeFiles/common_ssl_obj.dir/Heap.c.o -lOpenSSL::SSL -lOpenSSL::Crypto -lc -ldl -lpthread -lrt /usr/lib64/libanl.so 
Building C object test/CMakeFiles/test2.dir/test2.c.o
cd /builddir/build/BUILD/paho.mqtt.c-1.3.2/build.paho/test && /usr/bin/cc   -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -I/builddir/build/BUILD/paho.mqtt.c-1.3.2/test -I/builddir/build/BUILD/paho.mqtt.c-1.3.2/src    -o CMakeFiles/test2.dir/test2.c.o   -c /builddir/build/BUILD/paho.mqtt.c-1.3.2/test/test2.c
/usr/bin/ld: cannot find -lOpenSSL::SSL
/usr/bin/ld: cannot find -lOpenSSL::Crypto
collect2: error: ld returned 1 exit status
make[2]: *** [src/libpaho-mqtt3cs.so.1.3.2] Error 1
make[2]: Leaving directory `/builddir/build/BUILD/paho.mqtt.c-1.3.2/build.paho'
make[1]: *** [src/CMakeFiles/paho-mqtt3cs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
</pre>

**Expected behavior**

**Screenshots**

** Environment (please complete the following information):**
RHEL 7 with openssl 1.0.2 when building paho.mqtt.c 1.3.2.

**Additional context**

**Comment by icraggs** [comment]
I don't think there's a problem with linking with OpenSSL 1.0.2 per se, as demonstrated by the Travis job: https://travis-ci.org/github/eclipse/paho.mqtt.c/jobs/681030917

**Comment by icraggs** [comment]
Does the supplied Makefile work?

**Comment by icraggs** [comment]
I added some more Travis builds, including Ubuntu 14.04, OpenSSL 1.0.1f and gcc 4.8.4, which still worked: https://travis-ci.org/github/eclipse/paho.mqtt.c/jobs/681897739

**Comment by icraggs** [comment]
Can't reproduce.

**Comment by zxcv8553172** [comment]
I use i386 Centos6 and openssl is 1.0.1.e  and cmake and mqtt1.3.2 has this problem，too.who can help me

**Comment by zxcv8553172** [comment]
gcc is 4.4.7

**Comment by zxcv8553172** [comment]
if I cd paho.mqtt.c,then make,has problem:build/output/libpaho-mqtt3a.so: undefined reference to `clock_gettime'

**Comment by icraggs** [comment]
@zxcv8553172 I googled it for you: https://github.com/libfuse/libfuse/issues/207 
The rt library is linked to in the Linux CMake build, so I'm not sure why you should get this.
