### ISSUE TITLE
I'm here to thank...

### ISSUE THREAD

**Issue by jiejieTop** [eclipse-paho/paho.mqtt.c#873]
Thank you very much for this library. I referenced and used it to make an [mqtt client](https://github.com/jiejieTop/mqttclient) with excellent stability, thanks.

**Comment by icraggs** [comment]
@jiejieTop Thanks very much.  However I think you are using a client library from another repo of mine: https://github.com/eclipse/paho.mqtt.embedded-c :-)

**Comment by jiejieTop** [comment]
> @jiejieTop Thanks very much. However I think you are using a client library from another repo of mine: https://github.com/eclipse/paho.mqtt.embedded-c :-)

Yes, I have referenced~

**Comment by icraggs** [comment]
Thanks.  

For anyone relying on this library or any of the others I maintain, you could consider showing your support through the Github sponsors scheme: https://github.com/sponsors/icraggs
