### ISSUE TITLE
Websockets double masking after reconnection

### ISSUE THREAD

**Issue by choka85** [eclipse-paho/paho.mqtt.c#877]
**Describe the bug**
When using wss, if client is disconnected while outboundMsgs list remains with some messages not sent to server, after successful reconnection (disconnect + connect), in MQTTProtocol_retries() client retries to send all messages that are in outboundMsgs list.

When using wss, messages in outboundMsgs are already encrypted. When paho tries to publish (MQTTPacket_send_publish()) those messages from MQTTProtocol_retries() those messages are encrypted again. As both topic and payload are "double encrypted" when sent to broker, broker possibly disconnects client due to "unknown topic" reason.

One possible solution would be to extend outboundMsgs with raw message data or add some new list which contains raw data and is used from MQTTProtocol_retries() after disconnect/connect.

**Expected behavior**
Expected to sent regular, once encrypted, data.

**Environment (please complete the following information):**
Debian Buster, Ubuntu 16.04... It is not platform related issue.

**Comment by icraggs** [comment]
By encrypted do you mean the masking of the websocket frames, as opposed to TLS encryption?  

Does it occur if you use websockets without TLS (SSL)?

What version of the library are you using?

**Comment by icraggs** [comment]
I can answer my own questions.  Yes, yes and latest.

**Comment by choka85** [comment]
As much as I noticed now you are unmasking frames after sending them to server. Is this ok approach in every situation (e.g. when sending frames in more than one chunk or some similar situation).

**Comment by icraggs** [comment]
No it isn't.  One step at a time - I was seeing if the changes would work in all build environments first.  Other solutions could be:

- copy payload and topic memory before masking.  If the payload is large, this seems inefficient.
- tag the payload data with a flag to indicate that it has been masked.  Unmask if/when needed.

Remaining work:

1. Cleanup after write interrupted write has completed
2. Ensure the approach works for messages that have been restored from persistence
3. Adding tests for websockets, reconnection and resending both with and without client object deletion and recreation, to make sure the persistence storage 

You weren't working on a PR, were you?

**Comment by choka85** [comment]
Ok. It seemed to me that there is some more work to be done, but I wasn't 100% sure if that was supposed to be final patch or not. Thanks for clarification.

I just worked on finding root cause why and how this issue occurred.

**Comment by keysight-daryl** [comment]
Sounds like a direct hit for our 'scrambled topics' issue following websocket reconnect.
