### ISSUE TITLE
Seg fault after connect reconnect cycle

### ISSUE THREAD

**Issue by stanzlavos** [eclipse-paho/paho.mqtt.c#879]
**Describe the bug**
My implementation tries to setup the connection at my process startup. When connection with broker is lost at run-time, from "conn lost" callback, I trigger a timer (spawn a new thread on timer expiry) to retry the connection. This seems to work at least one time. Usually ends up in a seg fault.
I have a messaging framework in place and so I tried to do the re-connection by sending a message and setup the connection from the main thread (instead of the thread created for timer expiry). This had the seg fault as well.

Backtrace :

#0  0xb6efa0e0 in ListNextElement (aList=0x0, pos=0xb62a5e3c, pos@entry=0xb62a5e34) at src/LinkedList.c:413
#1  0xb6f043a4 in MQTTAsync_checkTimeouts () at src/MQTTAsync.c:1964
#2  MQTTAsync_sendThread (n=<optimized out>) at src/MQTTAsync.c:2035
#3  0xb6d6d494 in start_thread (arg=0xb62a6460) at pthread_create.c:486
#4  0xb6e68578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

I saw something similar online. I followed that thread and it was fixed it seems. Is this something new ?  

**To Reproduce**

**Expected behavior**

**Screenshots**

** Environment (please complete the following information):**
Raspbian Buster

**Additional context**

**Comment by icraggs** [comment]
We would need more information than that.  Such as a trace (described in the readme).  

What version are you using?  Can't you use the automatic reconnect?

**Comment by stanzlavos** [comment]
Looks like the problem is resolved. I just did a code cleanup, and it went away. Not at all sure, how the seg fault went away though.

I did not see the "automatic reconnect" option. :) Just checked the conn options now. Will give that a try as well. Closing the issue for the time being.

Anyhow, thank you for the quick response.
