### ISSUE TITLE
Race condition while connect and receive in synchronous api

### ISSUE THREAD

**Issue by xvyvx** [eclipse-paho/paho.mqtt.c#881]
**Describe the bug**
When using `MQTTClient_connect` and `MQTTClient_receive` in a multi-thread application(one MQTTClient per thread), `MQTTClient_connect` will wait until timeout even if connection established.

**To Reproduce**
1. Create a thread(named thread `A`) to call `MQTTClient_receive` repeatedly(in a `while` statement).
1. Create a thread(named thread `B`) to call `MQTTClient_connect` After step 1.

In thread `B`, `MQTTClient_connect` will call `Socket_getReadySocket` to get connectted socket(`MQTTProtocol_connect`->`MQTTClient_waitfor`->`MQTTClient_cycle`->`Socket_getReadySocket`->`isReady`), and in the same time, thread `A` will also call `Socket_getReadySocket` to poll ready socket(`MQTTClient_receive`->`MQTTClient_cycle`->`Socket_getReadySocket`->`isReady`). If thread `A` exec `isReady` before thread `B`'s `isReady`(thread `B`'s connection is established before thread `A` exec `isReady`), thead `A` will remove thread `B`'s connection socket in [isReady](https://github.com/eclipse/paho.mqtt.c/blob/d5b2101da77d763ed2f709a66478be914c9eafd0/src/Socket.c#L226-L227) and thread `B` can't find it anymore(thread `B` will wait until timeout in [MQTTClient_waitfor](https://github.com/eclipse/paho.mqtt.c/blob/d5b2101da77d763ed2f709a66478be914c9eafd0/src/MQTTClient.c#L2588-L2592)).

**Expected behavior**
thread `B`'s `MQTTClient_connect` should establish connection successful.

**Environment**
Both client applicaton and broker are deployed on the same host.
- OS: Ubuntu 18.04.3 LTS (GNU/Linux 3.10.108 armv7l)
- paho.mqtt.c version: 1.3.1
- mosquitto version: 1.6.7

**Comment by icraggs** [comment]
Hi.  The single threaded mode in MQTTClient, using MQTTClient_receive instead of message arrived callbacks, should only be used from single threaded applications.  For multi-threaded applications use callbacks in either MQTTClient or MQTTAsync.

**Comment by xvyvx** [comment]
Oh, it's seems that i misunderstand `MQTTClient`, you means `MQTTClient_receive` and `MQTTClient_waitForCompletion` can only used in single thread app, in synchronous api, callbacks should be used to achieve same purpose when app is multi-threaded, is it right?

**Comment by icraggs** [comment]
Yes, correct.  MQTTClient_receive() should be used when the whole application is single threaded.  This blog post might give some extra information:

https://modelbasedtesting.co.uk/2013/10/13/which-paho-mqtt-c-api-to-use-and-some-history/

**Comment by xvyvx** [comment]
Great! This is really useful article for beginners, thank you your answers.
