### ISSUE TITLE
Risk of memory leak of MQTTAsync_send function

### ISSUE THREAD

**Issue by michaelpan129** [eclipse-paho/paho.mqtt.c#882]
Version 1.3.2.
In the implementation of `MQTTAsync_send`, if the malloc of payload failed, `pub` and `pub->command.details.pub.destinationName` would not be freed. It would introduce memory leakage.
My suggestion is to free the malloced memory before going to exit, i.e., as follows:
```
if ((pub->command.details.pub.destinationName = MQTTStrdup(destinationName)) == NULL)
{
	free(pub);
	rc = PAHO_MEMORY_ERROR;
	goto exit;
}
pub->command.details.pub.payloadlen = payloadlen;
if ((pub->command.details.pub.payload = malloc(payloadlen)) == NULL)
{
	free(pub->command.details.pub.destinationName);
	free(pub);
	rc = PAHO_MEMORY_ERROR;
	goto exit;
}
```

**Comment by icraggs** [comment]
Fix added to the develop branch.  Thanks.

**Comment by michaelpan129** [comment]
Looks good!
