### ISSUE TITLE
Pointer to docs, other helpful information and blog posts

### ISSUE THREAD

**Issue by icraggs** [eclipse-paho/paho.mqtt.c#883]
[Online API documentation](https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/index.html)

Some potentially useful blog posts:
- [Which Paho C API to use, with some history, for context](https://modelbasedtesting.co.uk/2013/10/13/which-paho-mqtt-c-api-to-use-and-some-history/)
- [Paho client MQTT 5.0 support and command line utilities](https://modelbasedtesting.co.uk/2018/08/08/paho-c-client-mqtt-5-0-and-command-line-utilities/)
- [MQTT, QoS and persistence](https://modelbasedtesting.co.uk/2013/11/24/mqtt-qos-and-persistence/)
- [A story of MQTT 5.0](https://modelbasedtesting.co.uk/2018/04/09/a-story-of-mqtt-5-0/)

[Various MQTT and MQTT-SN talks I've given.](https://modelbasedtesting.co.uk/talks-ive-given/)

**Comment by libin-n-g** [comment]
I had issue while trying out the example code at https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/pubasync.html 
I am receving the following error. 
`Failed to connect, return code -15`

**Comment by libin-n-g** [comment]
> I had an issue while trying out the example code at https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/pubasync.html
> I am receiving the following error.
> `Failed to connect, return code -15`

I had tried the same code during the last December and it was working fine. I belive the latest update ro master created some issue.

**Comment by icraggs** [comment]
> > I had an issue while trying out the example code at https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/pubasync.html
> > I am receiving the following error.
> > `Failed to connect, return code -15`
> 
> I had tried the same code during the last December and it was working fine. I belive the latest update to master created some issue.

It works for me.  

It fails with that error if using cleansession with MQTT 5.0 or cleanstart with MQTT 3.1.1.

**Comment by icraggs** [comment]
The information here has now been folded into the readme.
