### ISSUE TITLE
Error with the library paho-mqtt3c

### ISSUE THREAD

**Issue by Audrey-45** [eclipse-paho/paho.mqtt.c#884]
**Describe the bug**

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

** Environment (please complete the following information):**
 - OS: [e.g. Linux]

**Additional context**

**Comment by Audrey-45** [comment]
Hello, I code on JetBrains Clion on Windows, I follow the ReadMe but I've got this error : "CMakeFiles\untitled4.dir/objects.a(main.c.obj): In function `msgarrvd': C:/Users/DAVID/untitled4/untitled4/main.c:49: undefined reference to `MQTTClient_freeMessage' C:/Users/DAVID/untitled4/untitled4/main.c:50: undefined reference to `MQTTClient_free' CMakeFiles\untitled4.dir/objects.a(main.c.obj): In function `main': C:/Users/DAVID/untitled4/untitled4/main.c:68: undefined reference to `MQTTClient_create' C:/Users/DAVID/untitled4/untitled4/main.c:76: undefined reference to `MQTTClient_setCallbacks' C:/Users/DAVID/untitled4/untitled4/main.c:85: undefined reference to `MQTTClient_connect' C:/Users/DAVID/untitled4/untitled4/main.c:97: undefined reference to `MQTTClient_publishMessage' C:/Users/DAVID/untitled4/untitled4/main.c:117: undefined reference to `MQTTClient_disconnect' C:/Users/DAVID/untitled4/untitled4/main.c:124: undefined reference to `MQTTClient_destroy'"

**Comment by icraggs** [comment]
That means the build can't find the generated library.  The file cbuild.bat contains an outline (will need to be changed to your particular installation) of the commands needed to build.  

You might also get some help from the AppVeyor build output: https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c/history

**Comment by Audrey-45** [comment]
Thanks a lot for your answer. The cbuild.bat created a build.xml, but I don't understand where I can put this build in my project.

**Comment by icraggs** [comment]
I think you'll find the build.xml existed before and wasn't created by the build.  That's for building by the Eclipse Hudson setup.

cbuild.bat contains the instructions to build using CMake.  Perhaps there is some documentation which describes how to import a CMake project into JetBrains (which I don't use, so I can't help you there).
