### ISSUE TITLE
How should I handle a url startwith scheme "tls"???

### ISSUE THREAD

**Issue by wlj644920158** [eclipse-paho/paho.mqtt.c#885]
Now,In my project,firstly,I post a http,then server responses a url that my mqtt client should connect to,but the url scheme is not any type in TCP,WS,SSL,WSS,it is just like "tls:xxx.xx.cn",How should i connect to my Server?

**Comment by icraggs** [comment]
TLS is the newer name/method for SSL.  So replace TLS with SSL.

**Comment by wlj644920158** [comment]
The  Server developer tell me I can connect  without cert ,now I replace the scheme "tls" with "ssl",and set MQTTAsync_connectOptions's field ssl default,just like this:

MQTTAsync_SSLOptions ssl_opts = MQTTAsync_SSLOptions_initializer;
conn_opts.ssl = &ssl_opts;

but it does not work,the failure callback returns a error: TLS/SSL connect failure

**Comment by icraggs** [comment]
I assume that has answered the question.
