### ISSUE TITLE
[Question] Graceful shutdown using Paho

### ISSUE THREAD

**Issue by danewalton-msft** [eclipse-paho/paho.mqtt.c#886]
Hi all,
I have a question about graceful shutdown using Paho.

In the sample [here](https://github.com/eclipse/paho.mqtt.c/blob/master/src/samples/MQTTClient_publish.c), any function which returns an error results in a call to `exit()`, including the call to `MQTTClient_connect()`. I'm curious if that kind of behavior is intended to be followed for user applications using Paho as well.

So hopefully with this rough example/pseudo code I can better explain. I have copied most of the linked sample code into `send_data()`.
Lets say we have a device collecting data every minute and every day on every hour, it sends some kind of data to a server
```c

void send_data(void)
{
    //Insert structs and setup
    if ((rc = MQTTClient_create(&client, ADDRESS, CLIENTID,
        MQTTCLIENT_PERSISTENCE_NONE, NULL)) != MQTTCLIENT_SUCCESS)
    {
         printf("Failed to create client, return code %d\n", rc);
         exit(EXIT_FAILURE);
    }

    //Insert options setup
    if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
    {
        printf("Failed to connect, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }

    //Insert message setup
    if ((rc = MQTTClient_publishMessage(client, TOPIC, &pubmsg, &token)) != MQTTCLIENT_SUCCESS)
    {
         printf("Failed to publish message, return code %d\n", rc);
         exit(EXIT_FAILURE);
    }

    rc = MQTTClient_waitForCompletion(client, token, TIMEOUT);

    if ((rc = MQTTClient_disconnect(client, 10000)) != MQTTCLIENT_SUCCESS)
    	printf("Failed to disconnect, return code %d\n", rc);
    MQTTClient_destroy(&client);
}

int main()
{
    
    application_setup();

    while(1)
    {
        get_sensor_data();

        if(time == ON_THE_HOUR)
        {
            send_data();
        }
        sleep(ONE_MINUTE);
    }
}
```

Now in this case, if `MQTTClient_connect()` fails, my program exits which I don't think I would want. In this case, I would more likely want to clean up the resources allocated by `MQTTClient_create()` which would be a call to `MQTTClient_destroy()`. Furthermore, if my call to `MQTTClient_publishMessage()` fails, I would likely want to gracefully exit by attempting to disconnect from the server (`MQTTClient_disconnect()`) and then cleaning up the resources (`MQTTClient_destroy()`) to prevent leaking.

Is this something safe to do? Would it risk further corruption of memory if something like `MQTTCLIENT_BAD_STRUCTURE ` were returned from `_connect()` or `_publishMessage()`? Are there only certain conditions/returned values where this would be appropriate?

Pardon me if this is documented somewhere...I tried looking through past issues and the doxygen docs and couldn't find much guidance.

Thanks!
Dane

**Comment by icraggs** [comment]
That sample is meant to be very basic, but it could disconnect after a successful connect.

On cleanup, if the process ends, then all its resources will be discarded anyway, so whether you call destroy() is really rather up to you.  I would try to make sure that disconnect() is called if the connect was successful, to promptly close the TCP socket.  Those can hang around for a while on some systems before being cleaned up if they aren't closed.

**Comment by danewalton-msft** [comment]
Thanks for the help Ian! I probably should have been a little more specific about that example. I was thinking for a bare metal device or something using an RTOS without an MMU in which case those calls to `exit()` would be early returns. In that case, can I safely assume that a failed call to `MQTTClient_connect()` should result in a call to `MQTTClient_destroy()`?

And in the case that the device is connected with `MQTTClient_connect()`, a failed call to `MQTTClient_publishMessage()` should result in a graceful `MQTTClient_disconnect()` and then `MQTTClient_destroy()`?

**Comment by icraggs** [comment]
I'm not sure how this library would work on an RTOS as it's using system calls for Linux, Windows or MacOS.  The embedded C client is more suitable for an RTOS, I would have thought.

Anyway, there is no implicit destroy() anywhere.  If you don't call it, you don't get it!

**Comment by danewalton-msft** [comment]
Good point I think I was conflating the two. This helps thanks for the help!
