### ISSUE TITLE
Commit 7ed1672f1b2218fcfc0c6dedfa4c233954588060 broke ABI compatibility

### ISSUE THREAD

**Issue by jhlancer** [eclipse-paho/paho.mqtt.c#887]
**Describe the bug**
httpHeaders was added in the middle of MQTTClient_connectOptions and MQTTAsync_connectOptions, changing the meaning of all members from that point

**To Reproduce**
1. Build a program against paho-mqtt-c v1.3.0
1a. At some point call MQTTAsync_connect using MQTT version 3.1.1 and with v5 parameters properly zeroed
2. Run in a system with paho-mqtt-c v1.3.2
3. Get return code -15(MQTTASYNC_BAD_MQTT_OPTION)

**Expected behavior**
Call does not fail with code -15(MQTTASYNC_BAD_MQTT_OPTION)

** Environment (please complete the following information):**
 - OS: linux-arm-gnueabihf
 - Version 1.3.2

**Comment by icraggs** [comment]
Well I've made the change that should fix that in the develop branch.  Not looking closely enough at the PRs.  I could update the 1.3.2 tag but I don't know whether that would be frowned upon.

**Comment by tbeu** [comment]
Please do not retag 1.3.2 again, but instead provide a bug-fix version 1.3.3. Thank you.
