### ISSUE TITLE
Possible Memory Leak on Connection Loss and High Rate Message Publish

### ISSUE THREAD

**Issue by aflteam** [eclipse-paho/paho.mqtt.c#892]
**Describe the bug**
I am using version Paho 1.3.2 and tested 1.2.1 as well, i got same results. Both Async and Client versions act as same.

My testing setup contains one embedded linux device (128 MB Ram) and one PC with broker. They are connected via ethernet cable (100mbit).
In my test senario, embed device publishes 100 messages (qos 1) with 40 byte payload over 1 sec. Keep Alive 60 sec. and Connection Timeout 30 sec.

**To Reproduce**
1. Start the test messaging
2. Controlling it packages from PC Mosquito Broker and MQTTFx Client
3. When testing is ongoing, i unplug the ethernet cable.
4. Then Linux Device Memory runs out and kernel OOM killer is triggered.

**Expected behavior**
I expect normal connection lost callback and close connection, but my app fails. Normal RAM usage of Linux device is 20 MB and it has free 100 MB at least.

Log is added below. When I investigate the problem, after ethnernet link is down and library PUBLISH action is interuppted. My application does not use MQTTClient_waitForCompletion etc. I only use delivered callback to check messages are being sent. So I suspect that my last message is sent with MQTTCLIENT_SUCCESS retVal. Then interrpution occurs. Library waits for timeout. My applation did not receive Connection Loss callback and tries another publish message then crush occurs.

What do you suggest? Should i call waitFor after each send? How do i understand library still trying to send in background before i sent another package? Waiting is costy because networks can be slow. If i wait, message delivery callback becomes meaningless.
 
**LOG**

May 19 15:03:01 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150301.915 8 MQTT_CLIENT <- PUBACK msgid: 2626 
May 19 15:03:01 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150301.930 8 MQTT_CLIENT -> PUBLISH msgid: 2627 qos: 1 retained: 0 rc 0 payload len(39): 
May 19 15:03:01 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150301.936 8 MQTT_CLIENT <- PUBACK msgid: 2627 
May 19 15:03:01 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150301.948 8 MQTT_CLIENT -> PUBLISH msgid: 2628 qos: 1 retained: 0 rc 0 payload len(39):
May 19 15:03:01 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150301.954 8 MQTT_CLIENT <- PUBACK msgid: 2628 
May 19 15:03:01 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150301.967 8 MQTT_CLIENT -> PUBLISH msgid: 2629 qos: 1 retained: 0 rc 0 payload len(39):
May 19 15:03:01 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150301.971 8 MQTT_CLIENT <- PUBACK msgid: 2629 
May 19 15:03:01 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150301.984 8 MQTT_CLIENT -> PUBLISH msgid: 2630 qos: 1 retained: 0 rc 0 payload len(39):
May 19 15:03:01 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150301.990 8 MQTT_CLIENT <- PUBACK msgid: 2630 
May 19 15:03:02 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150302.002 8 MQTT_CLIENT -> PUBLISH msgid: 2631 qos: 1 retained: 0 rc 0 payload len(39):
May 19 15:03:02 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150302.005 8 MQTT_CLIENT <- PUBACK msgid: 2631 
**May 19 15:03:02 fcd kernel: [ 1948.624990] macb f8008000.ethernet eth0: link down
May 19 15:03:02 fcd mqtt_client: PAHO Lib( 4 ): 20200519 150302.108 8 MQTT_CLIENT -> PUBLISH msgid: 2632 qos: 1 retained: 0 rc 0 payload len(39):
May 19 15:03:02 fcd mqtt_client: publishTimeout EventList Cnt 0 Event Map Cnt: 0 Periodic Cnt 860 Periodic Map Cnt: 808** (MY APP Tries to send another package but it has not receive retVal)
May 19 15:03:06 fcd kernel: [ 1952.161387] slave invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=0
May 19 15:03:06 fcd kernel: [ 1952.172793] CPU: 0 PID: 256 Comm: slave Not tainted 4.19.78-linux4sam-6.2-00008-gdbab1bf-dirty 15
May 19 15:03:06 fcd kernel: [ 1952.182242] Hardware name: Atmel SAMA5
May 19 15:03:06 fcd kernel: [ 1952.185909] Function entered at [<c010db0c>] from [<c010ae34>]
May 19 15:03:06 fcd kernel: [ 1952.191879] Function entered at [<c010ae34>] from [<c01845cc>]
May 19 15:03:06 fcd kernel: [ 1952.197681] Function entered at [<c01845cc>] from [<c0183c94>]
May 19 15:03:06 fcd kernel: [ 1952.203384] Function entered at [<c0183c94>] from [<c01842bc>]
May 19 15:03:06 fcd kernel: [ 1952.209180] Function entered at [<c01842bc>] from [<c01891bc>]
May 19 15:03:06 fcd kernel: [ 1952.214890] Function entered at [<c01891bc>] from [<c0181584>]
May 19 15:03:06 fcd kernel: [ 1952.220674] Function entered at [<c0181584>] from [<c01a727c>]
May 19 15:03:06 fcd kernel: [ 1952.226396] Function entered at [<c01a727c>] from [<c01aa71c>]
May 19 15:03:06 fcd kernel: [ 1952.232181] Function entered at [<c01aa71c>] from [<c010e31c>]
May 19 15:03:06 fcd kernel: [ 1952.237928] Function entered at [<c010e31c>] from [<c010e714>]
May 19 15:03:06 fcd kernel: [ 1952.243649] Function entered at [<c010e714>] from [<c0102008>]
May 19 15:03:06 fcd kernel: [ 1952.249432] Exception stack(0xc3471fb0 to 0xc3471ff8)
May 19 15:03:06 fcd kernel: [ 1952.254387] 1fa0:                                     00002710 0000000b 00000000 000003e8
May 19 15:03:06 fcd kernel: [ 1952.262495] 1fc0: 0003a018 00039828 00000000 00000172 b6f67fd5 b6f6e17c 00038640 0003b8f0
May 19 15:03:06 fcd kernel: [ 1952.270566] 1fe0: b6f80164 b5efedf8 b6f667e7 b6f5ac18 20010030 ffffffff
May 19 15:03:06 fcd kernel: [ 1952.277093] Mem-Info:
May 19 15:03:06 fcd kernel: [ 1952.279303] active_anon:9989 inactive_anon:40 isolated_anon:0
May 19 15:03:06 fcd kernel: [ 1952.279303]  active_file:4 inactive_file:5 isolated_file:0
May 19 15:03:06 fcd kernel: [ 1952.279303]  unevictable:0 dirty:0 writeback:0 unstable:0
May 19 15:03:06 fcd kernel: [ 1952.279303]  slab_reclaimable:315 slab_unreclaimable:1185
May 19 15:03:06 fcd kernel: [ 1952.279303]  mapped:6 shmem:409 pagetables:101 bounce:0
May 19 15:03:06 fcd kernel: [ 1952.279303]  free:16545 free_pcp:2 free_cma:16312
May 19 15:03:06 fcd kernel: [ 1952.310846] Node 0 active_anon:39956kB inactive_anon:160kB active_file:16kB inactive_file:20kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:24kB dirty:0kB writeback:0kB shmem:1636kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
May 19 15:03:06 fcd kernel: [ 1952.332749] Normal free:66180kB min:932kB low:1164kB high:1396kB active_anon:39956kB inactive_anon:160kB active_file:16kB inactive_file:20kB unevictable:0kB writepending:0kB present:131072kB managed:120860kB mlocked:0kB kernel_stack:440kB pagetables:404kB bounce:0kB free_pcp:8kB local_pcp:8kB free_cma:65248kB
May 19 15:03:06 fcd kernel: [ 1952.359769] lowmem_reserve[]: 0 0
May 19 15:03:06 fcd kernel: [ 1952.362998] Normal: 1*4kB (U) 0*8kB 0*16kB 2*32kB (UC) 1*64kB (C) 2*128kB (UC) 1*256kB (U) 2*512kB (UC) 1*1024kB (C) 1*2048kB (C) 1*4096kB (C) 1*8192kB (C) 1*16384kB (C) 1*32768kB (C) 0*65536kB = 66180kB
May 19 15:03:06 fcd kernel: [ 1952.380938] 418 total pagecache pages
May 19 15:03:06 fcd kernel: [ 1952.384506] 32768 pages RAM
May 19 15:03:06 fcd kernel: [ 1952.387282] 0 pages HighMem/MovableOnly
May 19 15:03:06 fcd kernel: [ 1952.391029] 2553 pages reserved
May 19 15:03:06 fcd kernel: [ 1952.394120] 16384 pages cma reserved
May 19 15:03:06 fcd kernel: [ 1952.397669] Tasks state (memory values in pages):
May 19 15:03:06 fcd kernel: [ 1952.402277] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
May 19 15:03:06 fcd kernel: [ 1952.410837] [    114]     0   114     1271       77    10240        0             0 syslog-ng
May 19 15:03:06 fcd kernel: [ 1952.419245] [    115]     0   115     6110      179    18432        0             0 syslog-ng
May 19 15:03:06 fcd kernel: [ 1952.427655] [    120]     0   120      638       83     8192        0         -1000 udevd
May 19 15:03:06 fcd kernel: [ 1952.435696] [    152]  1000   152      564       39     8192        0             0 dbus-daemon
May 19 15:03:06 fcd kernel: [ 1952.444311] [    184]    33   184      909      123     8192        0             0 lighttpd
May 19 15:03:06 fcd kernel: [ 1952.452634] [    188]     0   188      928       65     8192        0         -1000 sshd
May 19 15:03:06 fcd kernel: [ 1952.460623] [    196]     0   196      369       21     6144        0             0 crond
May 19 15:03:06 fcd kernel: [ 1952.468692] [    217]     0   217      360       20     6144        0             0 ifplugd
May 19 15:03:06 fcd kernel: [ 1952.476904] [    239]     0   239     6664      235    16384        0             0 center
May 19 15:03:06 fcd kernel: [ 1952.485092] [    241]     0   241      563       23     6144        0             0 getty
May 19 15:03:06 fcd kernel: [ 1952.493161] [    248]     0   248     4154       94    14336        0             0 master
May 19 15:03:06 fcd kernel: [ 1952.501924] [    249]     0   249     8566      116    16384        0             0 slave
May 19 15:03:06 fcd kernel: [ 1952.510592] [    304]     0   304      563       22     6144        0             0 udhcpd
May 19 15:03:06 fcd kernel: [ 1952.518746] [    305]     0   305      966      104     8192        0             0 sshd
May 19 15:03:06 fcd kernel: [ 1952.526699] [    411]     0   411    16981     8442    59392        0             0 mqtt_client
May 19 15:03:06 fcd kernel: [ 1952.535318] Out of memory: Kill process 411 (mqtt_client) score 279 or sacrifice child
May 19 15:03:06 fcd kernel: [ 1952.543163] Killed process 411 (mqtt_client) total-vm:67924kB, anon-rss:33764kB, file-rss:4kB, shmem-rss:0kB
May 19 15:03:06 fcd kernel: [ 1952.584720] oom_reaper: reaped process 411 (mqtt_client), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

**Comment by icraggs** [comment]
I'm not sure what is happening.  If you don't pull the ethernet plug out, how long can you keep sending 100 messages per second for?  Forever?  What does the memory use of the process look like until you run out of memory?

What time intervals are there between steps 2 and 3, and 3 and 4?  A normal level trace snippet around the time the network is interrupted might help.

The MQTTClient API is intended to be straightforward to use, rather than higher performance.  The MQTTAsync API allows more control over the sending of messages and no blocking.

**Comment by aflteam** [comment]
Hey @icraggs thanks for fast reply,

I am running my process for 5 hours after reporting the issue without pull it out, everything seems fine. For my test code, i add some delays between publish messages, and i called MQTTClient_waitForCompletion after each sent. It gives a little space between publishes.
According to **htop**, overall system including linux memory usage is 18 MB and the process has %2.7 memory and 26 kB virt value. Nothing seems suspicious. I tried Asyinc API too, it behaves same way on my test.

After i start the test, i wait until everything is fine and messages are seen from PC side. Let's say 3-5 minutes later, I unplug the cable. Whenever i unplug it, application is crashed in 2-3 sec. It feels almost immediate. Crash happens %50 of the time. 

I tested with Normal Trace Level, behavior is changed, because of delays of printing.
Now system could crash without pull-out the cable. 

Test1,2,3 is happened without my touch. Test is started, couple of hundreds messages are sent, then it crashes. Timing between publish messages are so minimal. I removed delays and wait calls to create faulty condition. Even if MQTTClient API holds until ques is empty, delays help a lot. I could not figure it out why tho.

Test4 is occur when i  add some delay between publsihes (10 ms) and i add controlling of rc value as MQTTCLIENT_FAILURE. After I unplug the cable, publish message returns MQTTCLIENT_FAILURE and program exits. How should i handle that case? or is it normal? 

[paho test1.txt](https://github.com/eclipse/paho.mqtt.c/files/4653106/paho.test1.txt)
[paho test2.txt](https://github.com/eclipse/paho.mqtt.c/files/4653105/paho.test2.txt)
[paho test3.txt](https://github.com/eclipse/paho.mqtt.c/files/4653107/paho.test3.txt)
[paho test4.txt](https://github.com/eclipse/paho.mqtt.c/files/4653108/paho.test4.txt)

**Comment by icraggs** [comment]
The logs from tests 1, 2 and 3 seem to show about 40 to 60 messages sent before out of memory.  Is that right?  Actually that's just the responses, not the publishes.   Anyway, that is not many and doesn't seem anywhere near enough to cause an out of memory, unless the machine is very small.

There is an inflight message window which you should not be able to exceed.  If you get a return code of anything other than MQTTCLIENT_SUCCESS it means the message is not sent, so you would need to retry.

Perhaps you could share your test program.  

What is your goal here?  What message throughput are you hoping for?

**Comment by icraggs** [comment]
More info needed.
