### ISSUE TITLE
mqtt property question

### ISSUE THREAD

**Issue by forstef** [eclipse-paho/paho.mqtt.c#900]
In MQTTProperties.h:

MQTTPROPERTY_CODE_SUBSCRIPTION_IDENTIFIERS_AVAILABLE = 41,/**< The value is 41 */

what is this mean, and how can I use it?

**Comment by icraggs** [comment]
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901092

It allows the server to tell the client that it doesn't support subscription ids.  

The MQTT 5.0 standard is the place to refer to for explanations of the properties.  I'll add a pointer in the documentation to that effect.

**Comment by forstef** [comment]
OK
