### ISSUE TITLE
return error code -8

### ISSUE THREAD

**Issue by guoyanzhang0817** [eclipse-paho/paho.mqtt.c#902]
MQTTAsync_responseOptions sendOptions = MQTTAsync_responseOptions_initializer;
    MQTTAsync_message pubMsg = MQTTAsync_message_initializer;
    INT32 rc = 0;
    CHAR msgSend[MSG_LEN_48] = {0};
    json_object *pValue = NULL;
    json_object *pObjectSerPro = NULL;
	INT32 waitCount = 0;
	
	if (pLoopCount == NULL)
	{
		printf("(%s) This is an empty data.\n", __FUNCTION__);
        return DEAL_ERROR;
	}

    while(!ConnectedFlag && ++waitCount<WAIT_COUNT);
    if (waitCount >= WAIT_COUNT)
    {
        printf("(%s) Failed to wait for the connection.\n", __FUNCTION__);
        return DEAL_ERROR;
    }

    /*
	{
		"loop1_count": 1,
		"loop2_count": 2
	}
    */

     pObjectSerPro = json_object_new_object();

    pValue = json_object_new_int(pLoopCount->loop1Count);
    json_object_object_add(pObjectSerPro, LOOP1_COUNT, pValue);
    pValue = json_object_new_int(pLoopCount->loop2Count);
    json_object_object_add(pObjectSerPro, LOOP2_COUNT, pValue);

 
    memset(msgSend, 0, MSG_LEN_48);
    sprintf(msgSend, "%s", json_object_to_json_string(pObjectSerPro));

    json_object_put(pObjectSerPro);
	
    sendOptions.onSuccess = onSend;
    sendOptions.context = GlobalClient;
    pubMsg.payload = msgSend;
    pubMsg.payloadlen = strlen(pubMsg.payload);
    pubMsg.qos = 1;
    pubMsg.retained = 1;

    if ((rc = MQTTAsync_sendMessage(GlobalClient, ORENA_SMARTFIRE_EC_RESPONSE_LOOP_REGISTER, &pubMsg, &sendOptions)) != MQTTASYNC_SUCCESS)
    {
        printf("(%s) Failed to start sendMessage, return code %d\n", __FUNCTION__, rc);
        return DEAL_ERROR;
    }
    return DEAL_OK;

**Comment by guoyanzhang0817** [comment]
I intend to encapsulate a JSON message for publication, where MSG_LEN_48 = 48, MSG_LEN_40 = 40, CHAR is char, INT32 is int.my question is :
When I changed this code from **CHAR msgSend[MSG_LEN_48] = {0};** to CHAR **msgSend[MSG_LEN_40] = {0};**， I encountered **a return error code -8** , but I looked at the data and said that the problem of returning -8 was due to the version problem, why?
(#define MQTTASYNC_BAD_STRUCTURE   -8
--Return code: A structure parameter does not have the correct eyecatcher and version number)

**Comment by icraggs** [comment]
Perhaps you forgot to change the value in memset(msgSend, 0, MSG_LEN_48); as well and caused a memory overwrite.

**Comment by guoyanzhang0817** [comment]
> Perhaps you forgot to change the value in memset(msgSend, 0, MSG_LEN_48); as well and caused a memory overwrite.
I am modifying synchronously. but how does memory overwrite relate to return - 8?

**Comment by icraggs** [comment]
If you changed one definition but not the other, then the call to memset could overwrite any area of memory, including the header for the data structure which could cause the BAD_STRUCTURE return code.

**Comment by guoyanzhang0817** [comment]
> If you changed one definition but not the other, then the call to memset could overwrite any area of memory, including the header for the data structure which could cause the BAD_STRUCTURE return code.

I agree with you. I have verified that the length of the string copied to the array (excluding \ 0) is equal to the length of the array. If I add \ 0, the structure will be overwritten and damaged.

Thank you for your reply.
