### ISSUE TITLE
Can't attach Callbacks, return code -1

### ISSUE THREAD

**Issue by Thomseeen** [eclipse-paho/paho.mqtt.c#904]
Hello,

I am currently trying to make my application a little more robust. Doing so I noticed the callbacks set by `MQTTAsync_setCallbacks` never trigger. Checking the return code I noticed it actually fails to attach the callbacks but I can't trace down why. Probably not exactly a bug with the library but I can't find a forum or anything similar to get help (there are more problems I stumbled across :/).

The snippet of the initialization I do (pretty similar to the async-publish example):
```C
/* Setup MQTT paho async C client structure */
  MQTTAsync mqtt_client;
  MQTTAsync_connectOptions mqtt_conn_opts = MQTTAsync_connectOptions_initializer;

  /* Initialize MQTT paho async C client incl. callbacks */
  int rc;
  if ((rc = MQTTAsync_create(&mqtt_client, MQTT_BROKER_ADDRESS, MQTT_CLIENTID,
                             MQTTCLIENT_PERSISTENCE_NONE, NULL)) != MQTTASYNC_SUCCESS) {
    mqtt_connection_flag = MQTT_CON_CONNECTION_FAILED;
    log_fatal("... Failed to create MQTT-client, return code %d", rc);
    log_info("MQTT Handler thread terminates");
    exit(EXIT_FAILURE);
  };

  if ((rc = MQTTAsync_setCallbacks(mqtt_client, NULL, mqtt_handler_connlost, NULL,
                                   mqtt_handler_delivered)) != MQTTASYNC_SUCCESS) {
    mqtt_connection_flag = MQTT_CON_CONNECTION_FAILED;
    log_fatal("... Failed to setup callbacks in MQTT-client, return code %d", rc);
    log_info("MQTT Handler thread terminates");
    exit(EXIT_FAILURE);
  };

  mqtt_conn_opts.keepAliveInterval = 20;
  mqtt_conn_opts.cleansession = 1;

  /* MQTT paho async C client callbacks for connection */
  mqtt_conn_opts.onSuccess = mqtt_handler_on_connect;
  mqtt_conn_opts.onFailure = mqtt_handler_on_connect_failure;
  mqtt_conn_opts.context = mqtt_client;

  /* Try to connect to MQTT-broker */
  log_info("Trying to connect...");
  mqtt_connection_flag = MQTT_CON_CONNECTING;
  if ((rc = MQTTAsync_connect(mqtt_client, &mqtt_conn_opts)) != MQTTASYNC_SUCCESS) {
    mqtt_connection_flag = MQTT_CON_CONNECTION_FAILED;
    log_fatal("... Failed to start connection, return code %d", rc);
    log_info("MQTT Handler thread terminates");
    exit(EXIT_FAILURE);
  }
```

I'm on a Beagle Bone Black using Debian 10 (armv7l) compiling with the `paho-mqtt3a` lib.
Any help is much appreciated :)

**Comment by icraggs** [comment]
Because you didn't set a message arrived callback.  Even if you aren't expecting to get a message, it seems a bad idea not to set one because there's no other way of knowing that you do once you set callbacks.  And what should the client library do - just throw them away?

**Comment by Thomseeen** [comment]
Thanks for the quick answer. This fixed it. Based of the docs and instinct I simply did not expect this behavior. If there is no callback defined, discarding any incoming messages probably isn't the best practice in bigger projects. In my project I know, that I will never subscribe to anything, so I didn't see why I would need one, even if it's just an empty function like in the examples.

**Comment by ghost** [comment]
This is a documentation bug. The docs say:
"If your client application doesn't use a particular callback, set the relevant parameter to NULL."
The actual behavior is that the call to `setCallbacks` will fail if you don't set the message arrived callback.

If this is the behavior, I don't get it because the call to `setCallbacks` is not mandatory in the first place, but we should update the docs.
