### ISSUE TITLE
How to know my mqtt password is wrong?

### ISSUE THREAD

**Issue by wlj644920158** [eclipse-paho/paho.mqtt.c#907]
if I use a wrong username or password connect to broker,the connection callback returns a code 5 with a message 'CONNACK return code',now I want to know is the code 5 means wrong username or password?

**Comment by icraggs** [comment]
The [MQTT 3.1.1 specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html), and the API docs for [connect](https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/_m_q_t_t_client_8h.html#aaa8ae61cd65c9dc0846df10122d7bd4e) both say that the connack return code 5 means "not authorized".

For more detailed information you'll have to refer to the docs or setup of the server you are trying to connect to.

**Comment by wlj644920158** [comment]
thank you very much
