### ISSUE TITLE
SSL session memory leak

### ISSUE THREAD

**Issue by IgorStefanovic** [eclipse-paho/paho.mqtt.c#909]
There is a memory leak on the MQTTClient_closeSession and probably on MQTTAsync_closeOnly when OpenSSL is enabled. According to the OpenSSL documentation when:
**SSL_get1_session** called, it returns a pointer to the OpenSSL session and the reference counter for the same is incremented. For the same pointer to be freed, **SSL_SESSION_free** MUST be called. Check the comment below.

OpenSSL documentation:
`"If the data is to be kept, SSL_get1_session() will increment the reference count, so that the session will not be implicitly removed by other operations but stays in memory. In order to remove the session, **SSL_SESSION_free(3) MUST be explicitly called** once to decrement the reference count again."`

**Environment (please complete the following information):**
 - OS: Linux
 - Version: Any

Please check the attached patch.
[sslSessionLeak.txt](https://github.com/eclipse/paho.mqtt.c/files/4770367/sslSessionLeak.txt)

**Comment by icraggs** [comment]
Thanks.

**Comment by IgorStefanovic** [comment]
Please verify that this fixes the issue on all platforms.  This was tested on Ubuntu 16.04.

Also, what happens if SSL_get1_session() is not called and we call SSL_SESSION_free(). Probably a double free or something like that.

Best regards.

**Comment by icraggs** [comment]
You can take a look at the CI tests to see what platforms it's run on.

**Comment by IgorStefanovic** [comment]
This should be checked:
> Also, what happens if SSL_get1_session() is not called and we call SSL_SESSION_free(). Probably a double free or something like that.

**Comment by icraggs** [comment]
FYI according to the OpenSSL documentation, calling SSL_SESSION_free on a null value has no effect.

**Comment by IgorStefanovic** [comment]
Okay, thank you for the support.
