### ISSUE TITLE
MQTTClient_publishMessage stuck after TCPSOCKET_INTERRUPTED error

### ISSUE THREAD

**Issue by ssuraci** [eclipse-paho/paho.mqtt.c#911]
**Describe the bug**
I've experienced same issue described here #875 (tested on v1.3.1): got error -22 (`TCPSOCKET_INTERRUPTED`) on `MQTTClient_publishMessage` and when  `MQTTClient_publishMessage` is called again, it gets stuck in `MQTTClient_yield()`. Context was send-only so no callback for incoming messages was called. Now trying to force a disconnect/reconnect in case of `MQTTClient_publishMessage` error.

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1. The bug seems to happen when `MQTTClient_publishMessage` returns with error `TCPSOCKET_INTERRUPTED` and then `MQTTClient_publishMessage` is called again. Behaviour is similar to that described in #875

**Expected behavior**
`MQTTClient_publishMessage`  should continue to work properly

** Environment (please complete the following information):**
 - OS: Ubuntu 16.04 
 - Version `1.3.1` with SSL

**Comment by icraggs** [comment]
Are you using threaded mode or not?  That is, have you set callbacks?  Why is it returning -22 - is there a network problem or a really big message? 

A trace would be good, as suggested in the template.  Also you should try 1.3.2 or 1.3.4 to see if it has been fixed already.

**Comment by ssuraci** [comment]
> Are you using threaded mode or not?

Yes, callback for connection lost (simply logs) and message arrived (even if as I said in that setup no message arrived to application)

> Why is it returning -22

It was during a server (RabbitMQ) restart.

> A trace would be good

OK I'll try to trace it, anyway a disconnect/reconnect after publish error seems to work around  the issue.

**Comment by icraggs** [comment]
I thought the title of the issue says it was stuck?  Implying some delay?  I would expect you would have to reconnect after a server restart.

**Comment by ssuraci** [comment]
Yes, library was stuck on `MQTTClient_yield()`: it happened that I launched application form gdb and when it got stuck I paused gdb and looked at stack trace, and library was looping around   `MQTTClient_yield()` while trying to publish a message (like in #875). 

So I think the sequence of events that lead to stuck state was:
1) `MQTTClient_publishMessage` got `TCPSOCKET_INTERRUPTED`
2) connection lost callback was **not** called (normally it is), so I did not reconnect
3) next call to `MQTTClient_publishMessage` got stuck

Maybe there's a race condition between connection lost detection and `MQTTClient_publishMessage` so if an application "quickly" publishes another message after an error, library has not yet detected the connection is lost and the gets stuck ?    

EDIT: forcing a disconnect after pubish error seems to work around the issue

**Comment by icraggs** [comment]
#875 was caused by keeping a callback active, blocking the processing thread.  Callbacks should not be held active for long, or processing will be blocked.   This is different.

The return from the publish operation will depend on the behaviour of the TCP stack.    Detection of a socket no longer connected to a broker sometimes depends on the keepalive (ping) processing.

You should also try the latest release - 1.3.4.  There's no point in debugging an issue if it's already been fixed.

**Comment by icraggs** [comment]
A client library trace as described in the readme, could help diagnose the problem.

**Comment by xxl3111** [comment]
May I ask how it was finally fixed?
