### ISSUE TITLE
Failing to connect to "wss://" unless MQTTClient_setCallbacks is used

### ISSUE THREAD

**Issue by facontidavide** [eclipse-paho/paho.mqtt.c#913]
I am not 100% sure if this is a bug, but it looks very weird to me and it took me many ours to find out.

Apparently I am not able to connect to a websocket (protocol wss) unless I set a **messageArrived** callback with **MQTTClient_setCallbacks**.

**To Reproduce**

Comment out these lines https://github.com/eclipse/paho.mqtt.c/blob/master/src/samples/paho_cs_pub.c#L198-L204

And try to connect to a wss:// address.

Connection will fail.

**Environment**
 - OS: Ubuntu 18.04
 - Version master

**Comment by facontidavide** [comment]
Extra info...

Trace : 4, 20200623 092311.781 SSL connect:SSL negotiation finished successfully
Trace : 4, 20200623 092311.781 WebSocket upgrade read not complete 0
Trace : 4, 20200623 092311.781 3 paho-cs-pub -> CONNECT version 3 clean: 1 (0)
Trace : 4, 20200623 092311.781 SSL handshake started write:unknown:unknown
Trace : 4, 20200623 092311.781 SSL state connect:SSL negotiation finished successfully:TLS_AES_256_GCM_SHA384
Trace : 4, 20200623 092311.781 SSL state connect:SSL negotiation finished successfully:TLS_AES_256_GCM_SHA384
Trace : 4, 20200623 092311.781 SSL state connect:SSLv3/TLS read server session ticket:TLS_AES_256_GCM_SHA384
Trace : 4, 20200623 092311.781 SSL handshake done write:unknown:unknown
Trace : 4, 20200623 092311.781 SSL certificate verification: X509_V_OK
Trace : 4, 20200623 092311.781 SSL connect:SSL negotiation finished successfully
Trace : 4, 20200623 092311.885 3 paho-cs-pub <- PUBACK msgid: 21584
Trace : 5, 20200623 092311.885 Bad MQTT packet, type 3

**Comment by icraggs** [comment]
I can see that's likely to be an issue.  Most people will be using the multi-threaded mode so it's likely not to be have been used before.

**Comment by icraggs** [comment]
I just tried this, on both current master and develop branches, and it worked for me.

**Comment by icraggs** [comment]
I'm going to close this pending more info.

**Comment by facontidavide** [comment]
If it worked for you and you can't reproduce it... I don't know why that was happening to me.
Fair enough to close this until I have more info (that I don't have right now).
