### ISSUE TITLE
I want to run this paho.mqtt client.c file in my linux?how to run that

### ISSUE THREAD

**Issue by ship23-95** [eclipse-paho/paho.mqtt.c#917]
**Describe the bug**

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

** Environment (please complete the following information):**
 - OS: [e.g. Linux]

**Additional context**

**Comment by icraggs** [comment]
Have you read the README?  I don't think there is a client.c in the repo so are you referring to another one? You need to look up some information on building C applications in Linux.  The supplied Makefile will build the libraries and applications and give an example of how to do that for your own (see how the samples and tests are built).

**Comment by icraggs** [comment]
I'm going to close this issue.  You'll need to look at the README and how to build and run applications on Linux.
