### ISSUE TITLE
MQTT client disconnects while publishing messages at high frequency

### ISSUE THREAD

**Issue by shaila123456789** [eclipse-paho/paho.mqtt.c#918]
Hello,

I am writing an application on ubuntu system which publishes messages on MQTT broker using 2 threads. Each thread has it's own mqtt async client and it publishes messages with a frequency of 1000 messages in 1 sec. The client and the MQTT broker run on the same machine. Client gets connected with MQTT broker using default URL tcp://localhost:1883.
 
While the setup works fine for almost 10 hours, after that it shows exception that MQTT connection is broken and the callback function gets called.

What could be the possible cause of this disconnect ?

-Thanks,
S

**Comment by shaila123456789** [comment]
Hello,

I used the sample application posted at below URL:
https://github.com/eclipse/paho.mqtt.c/issues/784

In this, I added a loop which publishes 10 messages. After around 2 hours the application freezes. What can be the issue here ?

-Thanks,
S

**Comment by icraggs** [comment]
Without more information, I would be just guessing - you left out all the fields from the issue template.  

Are there any error messages on the broker?  In the first comment the time interval is ten hours, in the second two hours.   If the QoS you are using is 1 or 2, then there is a fix in the develop branch which may help.

What OS are you using?  What exactly freezes?  A trace of the situation as described in the README could help.

**Comment by shaila123456789** [comment]
Hello icraggs,

Thanks for the reply. Sorry for not being precise about my earlier post. But here are the details of the test program: 

Environment:
Ubuntu 18.04.3 LTS 
Mosquitto broker 1.4.15
Paho.mqtt.c  - from "develop" branch

Code has been compiled using following options:
cmake -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_STATIC:BOOL=OFF -DPAHO_BUILD_SAMPLES:BOOL=OFF -DPAHO_BUILD_SHARED:BOOL=ON -DPAHO_HIGH_PERFORMANCE=FALSE -DBUILD_TESTS:BOOL=OFF ..

I have attached a test program. The program uses QOS=1 and aysnc client (Its the test program from issue #784). The program publishes 10 messages in a loop in onSend and onConnect.
The program exits if MQTTAsync_sendMessage fails with any other error than -10 which is MQTTASYNC_NO_MORE_MSGIDS.

The program publishes messages on broker for 9 minutes successfully.  After that, there are no more message ids the program can assign to messages, the application gives error "Failed to start sendMessage, return code -10". Then the application pauses for around 5 minutes and then again gives the same error "Failed to start sendMessage, return code -10". There are no messages getting published on broker during this time and no other error also. This continues until I don't stop the execution of the program.

Should not the program start publishing messages immediately after it could assign ids to messages ? Does this have any relation with message buffer full of messages ?
[MQTTAsync_publish.zip](https://github.com/eclipse/paho.mqtt.c/files/4922923/MQTTAsync_publish.zip)


-Thanks,
S

**Comment by icraggs** [comment]
I think your program will cause an ever expanding number of parallel messages to be sent, which is why you run out of message ids.

On connect, 10 sends will be started.  Each send will cause the onSend callback to be called on success.  Each of the 10 onSend callbacks will cause another 10 sends to be started (now 100).  And so on.

**Comment by icraggs** [comment]
I assume that answered your question.
