### ISSUE TITLE
The protocol is transplanted to UCOS system

### ISSUE THREAD

**Issue by yoyoyou666** [eclipse-paho/paho.mqtt.c#922]
Is this protocol convenient to transplant UCOS？It can be like this paho.mqtt.embedded -Is there a special port interface for C

**Comment by icraggs** [comment]
I don't follow the question.  The embedded library is probably the better option for a non-Linux OS.

**Comment by yoyoyou666** [comment]
Thank you very much for your answer! I want to transplant this protocol to my RTOS system, because it has more functions, such as websocket. But the agreement is not like : paho.mqtt.embedded-C, there is a special interface like transport.c. I just need to dock this file according to my system to complete the migration. therefore paho.mqtt . C he did not set aside such an interface, which made it difficult to transplant.

**Comment by yoyoyou666** [comment]
@icraggs 
For the above question, can you help me analyze it? Is this protocol RTOS not applicable? Is there any good method?

**Comment by icraggs** [comment]
This library has more functions than the embedded library but relies on Linux MacOS or Windows system calls.  It's less portable but is more capable.

The embedded library avoids using OS calls as much as possible because they are different across OSes.  Porting this library to a RTOS is likely to be difficult.  If what you really want is websocket support, then taking some of the code here and merging it into the embedded library is likely to be the best way.  But handling websockets is not very simple, so that is likely to be not straightforward.

**Comment by yoyoyou666** [comment]
非常感谢你的解答！针对该套协议，我主要是想使用服务器可以主动下发数据给客户端这样一个功能，例如，当我MQTT客户端登录之后，然而不需要订阅主题，MQTT服务器就可以主动下发数据给指定客户端，
所以，我可以针对我想要的这个功能，对该套协议做裁剪可以吗，并且容易裁剪吗？

**Comment by yoyoyou666** [comment]
Thank you very much for your answer! For this protocol, I mainly want to use the function that the server can actively distribute data to clients. For example, after my mqtt client logs in, but I do not need to subscribe to topics, the mqtt server can actively distribute data to the specified client,

Therefore, can I tailor the protocol according to the function I want, and is it easy to cut?

**Comment by icraggs** [comment]
The MQTT protocol uses the publish/subscribe model.  For any client application to receive messages it must subscribe to a topic.  A good place to learn about MQTT is here: https://www.hivemq.com/mqtt-essentials/

**Comment by icraggs** [comment]
And as you've opened another issue, I'm going to close this one.

**Comment by yoyoyou666** [comment]
Hello, as mentioned before, now I want to transplant the protocol to RTOS system, but during the process, I found that my system does not have the function of writev, and my system only has write. What good method can I do to solve this problem?
