### ISSUE TITLE
Print log under Linux

### ISSUE THREAD

**Issue by yoyoyou666** [eclipse-paho/paho.mqtt.c#926]
I have installed a client on Linux,
How can I set and print all the logs？

**Comment by jumoog** [comment]
just set env MQTT_C_CLIENT_TRACE & MQTT_C_CLIENT_TRACE_LEVEL
```
export MQTT_C_CLIENT_TRACE=ON
export MQTT_C_CLIENT_TRACE_LEVEL=PROTOCOL
```
https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/tracing.html

**Comment by yoyoyou666** [comment]
Hello, now I want to transplant the protocol to RTOS system, but during the process, I found that my system does not have the function of writev, and my system only has write. What good method do I have to solve this problem?

**Comment by icraggs** [comment]
1. Write a version of writev yourself using write underneath
2. Use the embedded client

are the two I would consider.

**Comment by yoyoyou666** [comment]
In the code, I don't understand what this macro represents(#if !defined(NO_PERSISTENCE)). If I define this macro, my project compilation will fail. Can I define this macro and then use mqtt normally?

**Comment by icraggs** [comment]
The NO_PERSISTENCE macro was intended to allow builds without including the persistence capability.  Persistence allows the message state to be preserved over invocations of the MQTT application.  It's only really useful if you want the smallest executable - but that can be achieved better with the embedded client.
