### ISSUE TITLE
Client doesn't send PINGREQ

### ISSUE THREAD

**Issue by jumoog** [eclipse-paho/paho.mqtt.c#927]
- OS: Windows Server 2012 R2
 - Version Pahoo 1.3.4

The Client should send PINGREQ but it never sends it. The function MQTTProtocol_keepalive is never called. Any Ideas whats wrong? eclipse mqtt-spy works fine

[log.txt](https://github.com/eclipse/paho.mqtt.c/files/4994514/log.txt)

**Comment by icraggs** [comment]
I just tried Windows 10 and it works fine for me (the develop branch).  I don't have any older versions of Windows to hand except those that are used in the CI tests.  

If MQTTProtocol_keepalive is not being called, it depends on the statement:

    if (MQTTTime_difftime(now, last) > (retryLoopInterval * 1000))

so probably the behaviour of MQTTTime_difftime().  That depends on the GetTickCount function -- hard to see what could go wrong there.

**Comment by jumoog** [comment]
it looks like MQTTAsync_retry gets called as well

**Comment by jumoog** [comment]
```
20200729 173456.971 MQTTAsync_retry
20200729 173457.663 now <3656204734>
20200729 173457.663 last <0>
20200729 173457.663 diff <3656204734>
20200729 173457.663 retryLoopInterval <5000>
```
for some reason the compare is not true and else always gets called

GetTickCount overflows every every 49 days. MS recommends to use GetTickCount64

**Comment by jumoog** [comment]
I switched to GetTickCount64 and now everything works

**Comment by icraggs** [comment]
I'd assumed it was just going to be a problem at the instant of rollover.

**Comment by jumoog** [comment]
yes 42 days

![grafik](https://user-images.githubusercontent.com/5268791/88828812-05428300-d1cc-11ea-80fe-9df55fcfffee.png)

**Comment by icraggs** [comment]
Does GetTickCount fail completely now then?  I had thought from the description that it might rollover and start from 0 again.  Or something like that.

**Comment by jumoog** [comment]
@icraggs  it was like this and went always into else branch
`if (MQTTTime_difftime(3656204734, 0) > (5* 1000))`

**Comment by jumoog** [comment]
Maybe the Type for `MQTTTime_difftime` and `MQTTTime_elapsed` is wrong? long (range: –2147483648 through 2147483647 decimal) but `GetTickCount()` returns a DWORD (range: 0 through 4294967295 decimal)

**Comment by jumoog** [comment]
yes! i added a Fix #930 ..  this would be a fix with that works with older Windows Versions. And newer Windows Version wouldn't have a rollover.

**Comment by icraggs** [comment]
Hi @jumoog .  Thanks for the PRs.  I started with those but I needed to unsderstand what was going on and it was a bit difficult to keep track of the changes for me.  That's my problem not yours I think.

So I've added my proposed fix to the develop branch (you can see the commits above).  There's also some code to (hopefully) work on Windows versions older than Vista to enable GetTickCount to work.  

Please do let me know what you think.

**Comment by jumoog** [comment]
looks good i'll test it soon.

**Comment by icraggs** [comment]
@jumoog Thanks.  If you are able to test out the code for GetTickCount(), that would be most appreciated.  It's a bit tricky to test without a Windows system which has been active for > 49 days.

**Comment by jumoog** [comment]
i found a server with 34 days uptime.. all other server are over 49 days.. i'll start a test until it will wrap around.

**Comment by jumoog** [comment]
40 days still running 🥳

**Comment by jumoog** [comment]
49 days 4241351562 of 4294967295

**Comment by jumoog** [comment]
Okay it works!
