### ISSUE TITLE
Failed to remove heap item at file ../protocol/MQTTClient.c line 2356 and 2358

### ISSUE THREAD

**Issue by Robert-Ilg** [eclipse-paho/paho.mqtt.c#929]
In case of an interrupted transfer the message is deleted twice - causing an improper heap error: 

Failed to remove heap item at file ../protocol/MQTTClient.c line 2421: 0xefef944!
Failed to remove heap item at file ../protocol/MQTTClient.c line 2425: 0xefef9c8!

Occurred in stack version v1.3.4 in synchronous mode with large messages being transferred (61.809 Byte)

Unfortunately I can only reproduce it with my special set up.

I traced down the problem. It is definitely due to the memory handling in case of an interrupted transfer.
I'm not quite sure, where the right point is to avoid the memory to be freed the second time. I would tend to skip the free of topic and payload in case of an interrupted message at the end of  function MQTTClient_publish5.

Here is part of the code in function MQTTClient_publish5
| if (rc == TCPSOCKET_INTERRUPTED)                                                <----  rc is set to TCPSOCKET_INTERRUPTED
|     {
|         while (m->c->connected == 1)                                               <----  wait endlessly for the message to be transmitted
|         {
|             pending_writes* writing = NULL;
| 
|             Thread_lock_mutex(socket_mutex);
|             writing = SocketBuffer_getWrite(m->c->net.socket);
|             Thread_unlock_mutex(socket_mutex);
| 
|             if (writing == NULL)                                                            <----  message is transmitted, stop waiting
|                 break;
| 
|             Thread_unlock_mutex(mqttclient_mutex);
|             MQTTClient_yield();                                                             <----- delete message if transfered. See trace below
|             Thread_lock_mutex(mqttclient_mutex);
|         }
|         rc = (qos > 0 || m->c->connected == 1) ? MQTTCLIENT_SUCCESS : MQTTCLIENT_FAILURE;
|     }
| 
|     if (deliveryToken && qos > 0)
|         *deliveryToken = msg->msgid;
| 
| exit_and_free:
|     if (p)
|     {
|         if (p->topic)
|             free(p->topic);                                                              <----- topic and payload are freed second time, causing error
|         if (p->payload)
|             free(p->payload);                                                          <----- topic and payload are freed second time, causing error
|         free(p);
|     }

The first time the memory is freed calling the following functions:
MQTTClient_publish5
--> MQTTClient_yield
-----> MQTTClient_cycle
---------> Socket_getReadySocket
--------------->Socket_continueWrites
--------------------> (*writecomplete)(socket, rc)  is callback function MQTTClient_writeComplete
-------------------------->MQTTProtocol_checkPendingWrites   
-------------------------------> MQTTProtocol_removePublication                               <----- topic and payload are freed first time

**Comment by icraggs** [comment]
Thanks.  I'm sure it'll be reproducible (famous last words).
