### ISSUE TITLE
License version typo in /LICENSE

### ISSUE THREAD

**Issue by wismann** [eclipse-paho/paho.mqtt.c#940]
In commit 1e91229cb6403e3a9b02dfdc11c71b04c0518cff the license has been changed from EPL v1.0 to EPL v2.0.
In the file https://github.com/eclipse/paho.mqtt.c/blob/1e91229cb6403e3a9b02dfdc11c71b04c0518cff/LICENSE, the EDL license version has also been changed from 1.0 to 2.0.

This has to be a typo, because
1. There IMHO is no version 2.0 of the EDL
2. In every other place, the version of the EDL license has not been changed.

**Comment by icraggs** [comment]
Thanks for pointing this out.

**Comment by icraggs** [comment]
Fixed.
