### ISSUE TITLE
Windows port: DllMain() Log/Init ordering

### ISSUE THREAD

**Issue by jspaith** [eclipse-paho/paho.mqtt.c#941]
**Describe the bug**
In `DllMain` implementation for Windows, there are ordering issues trying to call `Log`.

```c
case DLL_PROCESS_ATTACH:
   Log(TRACE_MAX, -1, "DLL process attach");
   MQTTClient_init();
   break;
```
* `Log` is grabbing `log_mutex` via a `WaitForSingleObject`.  However the `log_mutex` itself isn't itself initialized until the call to `MQTTClient_init` which is beneath `Log`.
With code implemented as-is, this isn't going to cause problems because the `WaitForSingleObject` will just fail but nothing is checking it.  But as a best practice we should init mutexes 1st.  

* The `Log` call in DLL_PROCESS_ATTACH and others depending on program won't do anything anyway.  It filters on `TRACE_MAX` but the app never sets this - even if env variable is set - until much later in `Log_initialize`.

**Recommended fix**
I'm very new to Paho but not to DllMain issues.  My 2 cents here would be to remove the `Log` call entirely throughout DllMain.  The `Log_initialize` - which is correctly NOT called in DllMain - inherently means there's not a great way to do this.  And Paho (correctly!) isn't do that much here anyway.  In my experience debugging loader issues [Loader snaps](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/show-loader-snaps) is the mechanism not logs from Dll itself.

**To Reproduce**
Code review or hook up a debugger.

**Expected behavior**
Log to respect mutexes and to potentially be called in all cases if env variable is set.

**Screenshots**
N/A

** Environment (please complete the following information):**
Windows when building as a DLL only

**Comment by icraggs** [comment]
i agree.  Thanks.
