### ISSUE TITLE
SSL Doesn't seem to work. (Read Access Violation)

### ISSUE THREAD

**Issue by Jethrootje** [eclipse-paho/paho.mqtt.c#942]
I'm using paho.mqtt on Windows, tried it with CMake and with VCPKG, currently using VCPKG because i kept getting Unresolved External Errors, i got those with the vcpkg version too if i'd use the files in the "mqtt" folder, now i'm using the files outside of these, currently "MQTTAsync.h"

This is my code currently: (Most of it is from a example)
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "paho-mqtt/MQTTAsync.h"
#include <Windows.h>

#define ADDRESS     "ssl://*****.nl:8883"
#define CLIENTID    "******"
#define TOPIC       "testTopic"
#define PAYLOAD     "addtext"
#define QOS         1
#define TIMEOUT     10000L

volatile MQTTAsync_token deliveredtoken;
int finished = 0;
void connlost(void* context, char* cause)
{
    MQTTAsync client = (MQTTAsync)context;
    MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
    int rc;
    printf("\nConnection lost\n");
    printf("     cause: %s\n", cause);
    printf("Reconnecting\n");
    conn_opts.keepAliveInterval = 20;
    conn_opts.cleansession = 1;
    if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
    {
        printf("Failed to start connect, return code %d\n", rc);
        finished = 1;
    }
}
void onDisconnect(void* context, MQTTAsync_successData* response)
{
    printf("Successful disconnection\n");
    finished = 1;
}
void onSend(void* context, MQTTAsync_successData* response)
{
    MQTTAsync client = (MQTTAsync)context;
    MQTTAsync_disconnectOptions opts = MQTTAsync_disconnectOptions_initializer;
    int rc;
    printf("Message with token value %d delivery confirmed\n", response->token);
    opts.onSuccess = onDisconnect;
    opts.context = client;
    if ((rc = MQTTAsync_disconnect(client, &opts)) != MQTTASYNC_SUCCESS)
    {
        printf("Failed to start sendMessage, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }
}
void onConnectFailure(void* context, MQTTAsync_failureData* response)
{
    printf("Connect failed, rc %d\n", response ? response->code : 0);
    finished = 1;
}
void onConnect(void* context, MQTTAsync_successData* response)
{
    MQTTAsync client = (MQTTAsync)context;
    MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
    MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
    int rc;
    printf("Successful connection\n");
    opts.onSuccess = onSend;
    opts.context = client;
    pubmsg.payload = (void*) PAYLOAD;
    pubmsg.payloadlen = strlen(PAYLOAD);
    pubmsg.qos = QOS;
    pubmsg.retained = 0;
    deliveredtoken = 0;
    if ((rc = MQTTAsync_sendMessage(client, TOPIC, &pubmsg, &opts)) != MQTTASYNC_SUCCESS)
    {
        printf("Failed to start sendMessage, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }
}
int main(int argc, char* argv[])
{
    MQTTAsync client;
    MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
    MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
    MQTTAsync_token token;
    int rc;
    MQTTAsync_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);
    MQTTAsync_setCallbacks(client, NULL, connlost, NULL, NULL);
    conn_opts.username = "*******";
    conn_opts.password = "*******";

    MQTTAsync_SSLOptions ssl_opts = MQTTAsync_SSLOptions_initializer;
    conn_opts.ssl = &ssl_opts;
    conn_opts.ssl->enableServerCertAuth = 1;
    conn_opts.ssl->sslVersion = MQTT_SSL_VERSION_TLS_1_2;

    conn_opts.keepAliveInterval = 20;
    conn_opts.cleansession = 1;
    conn_opts.onSuccess = onConnect;
    conn_opts.onFailure = onConnectFailure;
    conn_opts.context = client;
    if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
    {
        printf("Failed to start connect, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }
    printf("Waiting for publication of %s\n"
        "on topic %s for client with ClientID: %s\n",
        PAYLOAD, TOPIC, CLIENTID);
    while (!finished)
        Sleep(100);
    MQTTAsync_destroy(&client);
    return rc;
}
```

This is the error i'm stuck on:
![image](https://user-images.githubusercontent.com/36591615/91866057-5f72b000-ec72-11ea-92af-ea3700fa2afd.png)

These are the settings i want to have: (With user & password credentials)
![image](https://user-images.githubusercontent.com/36591615/91866106-6d283580-ec72-11ea-8186-583bfdf745d9.png)

But it's like the SSL is not supported or something, i've seen a few Githubs but none of them solved my issue, probably because most of these weren't for windows either.

**Comment by jumoog** [comment]
You use the wrong library. You need paho-mqtt3as not paho-mqtt3a only paho-mqtt3as has openssl support

**Comment by Jethrootje** [comment]
> You use the wrong library. You need paho-mqtt3as not paho-mqtt3a only paho-mqtt3as has openssl support

Yeah, i tried to fix that issue before but it didn't seem to work, i just deleted all the other files, Do you have any idea how i'd replace it or anything?

**Comment by Jethrootje** [comment]
So i tried building with CMake and the SSL option on "ON" but  when i use this:
```
cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=C:\mqtt\paho-cpp -DPAHO_BUILD_SAMPLES=ON -DPAHO_WITH_SSL=ON -DCMAKE_PREFIX_PATH=C:\mqtt\paho-c
```

I'm receiving a error:
```
-- Configuring incomplete, errors occurred!
See also "C:/Users/jethr/Downloads/paho.mqtt.cpp/build/CMakeFiles/CMakeOutput.log".
```

Now this is my CMakeOutput.log https://pastebin.com/raw/8BwZ78CD
I don't really get what's wrong.

**Comment by icraggs** [comment]
I'm not sure I see any errors in that log.

You might find it useful to look at the AppVeyor Windows builds which include the use of SSL and build the test programs and samples: https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c/history

Also the repo contains a helper batch file which I use to build and run the tests on Windows: https://github.com/eclipse/paho.mqtt.c/blob/master/cbuild.bat

**Comment by jumoog** [comment]
i think you miss the flags.

**Comment by Jethrootje** [comment]
> I'm not sure I see any errors in that log.
> 
> You might find it useful to look at the AppVeyor Windows builds which include the use of SSL and build the test programs and samples: https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c/history
> 
> Also the repo contains a helper batch file which I use to build and run the tests on Windows: https://github.com/eclipse/paho.mqtt.c/blob/master/cbuild.bat

Yeah i managed to build it with CMake now with a classmate, currently i'm trying to find out how to connect to the server with the current options, may i ask.. in MQTT.fx you have a option "CA signed server certificate"

Should it be like this to enable that:
```
    MQTTAsync_SSLOptions ssl_opts = MQTTAsync_SSLOptions_initializer;
    ssl_opts.enableServerCertAuth = 1;
    ssl_opts.sslVersion = MQTT_SSL_VERSION_TLS_1_2;
    conn_opts.ssl = &ssl_opts;
```
Or should it be different?
And right now i have this..
```
    if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
    {
        printf("Failed to start connect, return code %d\n", rc);
        exit(EXIT_FAILURE);
    }
```
But it returns the code `-8` now i looked at the docs and i don't see anything for negative numbers only for positives, are these the right documents? https://docs.rs/paho-mqtt-sys/0.2.0/paho_mqtt_sys/fn.MQTTAsync_connect.html

**Comment by Jethrootje** [comment]
And if i use <mqtt/async_client.h> it gives 15 Unresolved External errors.
It doesn't with <MQTTAsync.h> though.

**Comment by Jethrootje** [comment]
![image](https://user-images.githubusercontent.com/36591615/91982411-8096d780-ed2a-11ea-9e37-90279e04f2b4.png)
this happens if i enable SHARED instead of STATIC

Therefor if i change the value to `1` for example, it gives the return code -8 again.
and if i test the `cbuild.bat` it says that `nmake` is not a recognized command.

**Comment by icraggs** [comment]
I don't know about those docs.  These are the ones I put up: https://www.eclipse.org/paho/files/mqttdoc/MQTTAsync/html/_m_q_t_t_async_8h.html

nmake is the Microsoft version of make.  You have to have some 'make' available.

**Comment by Jethrootje** [comment]
What do you mean with "You have to have some 'make' available" isn't CMake the same?
And those docs are basically the same about my problem, they only say this:
![image](https://user-images.githubusercontent.com/36591615/91988813-036e6100-ed30-11ea-9e5b-0eb44e6eb631.png)
They don't say negative number responses.

**Comment by Jethrootje** [comment]
Apparently there is a vcpkg SSL version too, but it doesn't seem to support SSL either because it still doesn't use the right .dll
Right now i'm talking about the `vcpkg install paho-mqttpp3[ssl]`

**Comment by icraggs** [comment]
> What do you mean with "You have to have some 'make' available" isn't CMake the same?
> And those docs are basically the same about my problem, they only say this:
> ![image](https://user-images.githubusercontent.com/36591615/91988813-036e6100-ed30-11ea-9e5b-0eb44e6eb631.png)
> They don't say negative number responses.

The page I linked to has the negative response codes on it.

I don't know anything about vcpkg I'm afraid.

**Comment by jumoog** [comment]
with Windows and OpenSSL you have no CA Root bundle. You can disable the validation. `enableServerCertAuth`

**Comment by icraggs** [comment]
I think this has been answered.
