### ISSUE TITLE
How to recover messages if they are failed to publish please?

### ISSUE THREAD

**Issue by rqg0717** [eclipse-paho/paho.mqtt.c#945]
OS: Ubutnu 14.04
Version libpaho-mqtt3as 1.3.5
log:
Connecting to wss://127.0.0.1:443 ...
Connect to MQTT broker, return code: Success.
Subscribing to topic /test with client CLIENTID_0_1598979517 at QoS 2
onConnectFailure: Connect failed, rc Failure reason code socket error
onConnectFailure: Connect failed, rc Failure reason code TCP connect completion failure
onPublishFailure: Publish failed, rc Operation discarded before completion.

if the message is failed to publish due to some network issues, what would be the best way to recover the message and republish the message please? Thank you.

**Comment by jumoog** [comment]
With QoS 2 thats no Problem. 
As long the sender doesn’t receive an acknowledgement (PUBREC) it will resend the message with the DUP flag set.

**Comment by rqg0717** [comment]
@jumoog  Thank you for your prompt reply. I am trying to send a 10MB file with QoS2 and MQTTCLIENT_PERSISTENCE_DEFAULT set.  automaticReconnect is also set. It seems the file never got resent for some reason after auto reconnect. Besides, sometimes it keeps trying to reconnect:
 test file size = 10485760. 
test_pubsub.c: Publish test file to MQTT broker. 
onConnectFailure5: Connect failed, rc Failure reason code SUCCESS
onConnectFailure5: Connect failed, rc Failure reason code SUCCESS
 onConnected: cause: automatic reconnect
Subscribing to topic /broadcast with client TCLIENTID_0_1599076378 at QoS 2
Subscribing to topic /test with client CLIENTID_0_1599076378 at QoS 2
onConnectFailure5: Connect failed, rc Failure reason code SUCCESS
 onConnected: cause: automatic reconnect
Subscribing to topic /broadcast with client TCLIENTID_0_1599076378 at QoS 2
Subscribing to topic /test with client CLIENTID_0_1599076378 at QoS 2
onConnectFailure5: Connect failed, rc Failure reason code SUCCESS
 onConnected: cause: automatic reconnect
Subscribing to topic /broadcast with client TCLIENTID_0_1599076378 at QoS 2
Subscribing to topic /test with client CLIENTID_0_1599076378 at QoS 2
onConnectFailure5: Connect failed, rc Failure reason code SUCCESS
 onConnected: cause: automatic reconnect
Subscribing to topic /broadcast with client TCLIENTID_0_1599076378 at QoS 2
Subscribing to topic /test with client CLIENTID_0_1599076378 at QoS 2
onConnectFailure5: Connect failed, rc Failure reason code SUCCESS
...
non-stop for some reason...

**Comment by icraggs** [comment]
Are you sure your attempt to subscribe is allowed?  From that it looks like the server might be denying it, or some other operation you are trying.  Maybe 10MB is bigger than is allowed by the server?

Also you need to ensure that cleansession = false in the connect options, for message retrying to work.

**Comment by rqg0717** [comment]
@icraggs 

> Are you sure your attempt to subscribe is allowed? 

Yes, 1MB big files were able to be republished without any issue.

>  Maybe 10MB is bigger than is allowed by the server? 

The maximum size is set to 100MB on the broker.

>Also you need to ensure that cleansession = false in the connect options, for message retrying to work. 

I am using MQTT V5 and cleanstart set to 0.


Update:
I was using VPN yesterday and the network was extremely unstable. It seems everything works fine today...
