### ISSUE TITLE
timeout do not works

### ISSUE THREAD

**Issue by SpaceZL** [eclipse-paho/paho.mqtt.c#949]
https://github.com/eclipse/paho.mqtt.c/blob/ed0706b1cb2b695ffe84ef93e0532f41afedd494/src/MQTTClient.c#L1211

I use QT with MSVC2017 32bit to bulid this code ,when run to this line , 'millisecsTimeout - MQTTTime_elapsed(start)' will return a  error value which is  very big. I find it looks like '(uint64_t) (unsign long long  -  (uint64_t)(int64_t)(unsign long long))' ,the error happen when to run '(int64_t)(unsign long long)'.

**Comment by icraggs** [comment]
You'll have to give some more information (like in the issue template you deleted).  Like: when does this happen?  How often (all the time, under some circumstances, etc)?  What is the external behaviour? 

In addition, taking a trace as described in the readme could help.

**Comment by icraggs** [comment]
More info needed.
