### ISSUE TITLE
the msgid of MQTTAsync_message doesn't seem to work 

### ISSUE THREAD

**Issue by louiscrazy** [eclipse-paho/paho.mqtt.c#952]
Hi there，
When I use the MQTTAsync_sendMessage function，the msgid of MQTTAsync_message doesn't seem to work, only the payloadlen, the  payload, the  QoS and the  retained work.  Please help to see if you can add an input parameter to MQTTAsync_send so that users can fill in msgid by themselves. Thanks.

**Comment by fpagliughi** [comment]
The library manages the msgid's in the outbound (send) messages automatically to insure that multiple inflight messages don't accidentally use the same value.
It will set an appropriate value for messages with QOS >= 1. 
For QOS 0 is uses a msgid of zero which is the proper behavior.

**Comment by louiscrazy** [comment]
@fpagliughi Hi，If users can't input msgid by themselves, they may not know which message was published successfully or failed.  Is there any way to let users know which message is published successfully or not.  Thanks

**Comment by icraggs** [comment]
The token in the response options is set to the assigned message id.  The message id in the MQTTAsync_message structure is not an input parameter.  The doc can be improved.
