### ISSUE TITLE
Publish frequency limited to 500 messages/s

### ISSUE THREAD

**Issue by dlebansais** [eclipse-paho/paho.mqtt.c#954]
Hello,

I have run the following setup:

+ All programs run on the same computer.
+ Program sender.exe is publishing at a given frequency on topic TEST0, with QoS 0, asynchronously, a short message (say, 1 byte).
+ Program loopback .exe is listening on TEST0, and sends back any received message on topic TEST1, with QoS 0, asynchronously.
+ Program receiver.exe is listening on topic TEST1 and measures the received throughput.

As I increase the frequency, the received throughput tops at exactly 500 messages per second even if the sender is publishing at a higher frequency.
If I increase the message size, the max received frequency stays 500 Hz.

I would expect the throughout to top eventually, but higher than 500 Hz and at a more random value.

Environment:
Windows 10, Intel i7, 2.8Ghz, 4 physical cores.

My take of this issue (could be completely off, but since I did some research I might as well tell you): in /src/MQTTAsync.c, line 1692 the code takes two mutexes. It does so once per command. If a context switch happens sometimes, this could explain the issue.
My suggestion, in situations like this, is to take the mutex once and copy all items from the queue to a local queue, release the mutex and then process each item.

**Comment by icraggs** [comment]
I think there is something more going on in your setup.  Using Mosquitto on Linux on my desktop I get a message send rate of 122000, 40000 and 26000 messages per second for QoS 0, 1 and 2 respectively.

Using Windows and Mosquitto, I get 16000, 6600 and 3750.

**Comment by dlebansais** [comment]
Thanks for checking. I'll investigate more deeply.

**Comment by dlebansais** [comment]
Apologies for the false alert, I narrowed down the issue to a problem in my code.
