### ISSUE TITLE
onDisconnect not called on SOCKET_ERROR

### ISSUE THREAD

**Issue by alekmag** [eclipse-paho/paho.mqtt.c#955]
"SOCKET_ERROR" in `MQTTAsync_receiveThread()` doesn't cause execution of `onDisconnect` callback as it was before. Previously there was `MQTTAsync_disconnect_internal(m, 0)` called, so I think it's result of this commit: [7465332](https://github.com/eclipse/paho.mqtt.c/commit/7465332c41d79d256637d4fa6689c133045a997c). This behaviour can be hard to recreate, because it's socket error between publishing message and getting any acknowledgment (as I understand).
Was it intentional change?

**Comment by icraggs** [comment]
Yes that seems like an unintended consequence of the fix.  Should be straightforward to address I hope.
