### ISSUE TITLE
`MQTTAsync_waitForCompletion` reports incorrectly that message was sent

### ISSUE THREAD

**Issue by Gamora35** [eclipse-paho/paho.mqtt.c#956]
If an mqtt disconnect happens while executing `MQTTAsync_waitForCompletion`, the function will incorrectly report that a message was sent. This functions checks in the begining if the for mqtt disconnect, but no longer does so in the while loop. The only function call in the while loop is `MQTTAsync_isComplete`, which reports complete when the future and current queues are empty, which is also the case on a disconnect (or so it seems). The fix would be to check for a disconnect also in the while loop

**Comment by icraggs** [comment]
Waitforcompletion isn't going to be as accurate as checking the success or failure callbacks for an operation.

I've added a check for disconnection.
