### ISSUE TITLE
MQTTASync - MQTTAsync_onFailure callback doesn't return ptr to MQTTAsync_message

### ISSUE THREAD

**Issue by HED-rhodson** [eclipse-paho/paho.mqtt.c#957]
In the MQTTAsync_onFailure callback, the parameters are a handle, and MQTTAsync_failureData* response
Neither structure contain a pointer to the original MQTTAsync_message passed to the MQTTAsync_sendMessage function. 

If the payload is a dynamically allocated string, in a multi-threaded application if is difficult to free the payload if the MQTTAsync_onFailure is called. 

If you have another suggestion on how to trace back to the data pointer I would be very interested in it.

I am using paho-mqtt-1.3.1, but I believe it is still true of the latest release

**Comment by icraggs** [comment]
The context pointer of the responseOptions can be used to point to a structure containing any information you need in the callback handler, such as the payload pointer.

The payload data along with all the other information is copied by the send function, so you shouldn't need to way until the success or failure callback to free it, if you don't want to.
