### ISSUE TITLE
My MQTT is showing some random Token Number . Why?

### ISSUE THREAD

**Issue by ship23-95** [eclipse-paho/paho.mqtt.c#958]
I want to publish 2 times with different payload then why it is showing me this:

Message ' 0 4 2 2 2 4 3 6 ' with delivery token 1 delivered (First Time)
publishing to FIRE with payload F  Message 'F' with delivery token 32552 delivered(Second Time)

this 32552 changes every time i run the code .please help.

**Comment by icraggs** [comment]
I'm not sure how you can expect a useful reply with so little information.  The issue template is there to guide you in providing enough.

**Comment by icraggs** [comment]
More info needed.  LIke a client library trace as described in the readme, or a test program.
