### ISSUE TITLE
Timeline for release of 1.3.6?

### ISSUE THREAD

**Issue by landersson** [eclipse-paho/paho.mqtt.c#960]
Hi, is there a timeline for the 1.3.6 release?

**Comment by icraggs** [comment]
This week.  Wrapping up remaining issues.

**Comment by landersson** [comment]
Fantastic, thanks!

**Comment by Pascal-Fremaux** [comment]
Hi @icraggs ,

Seems you have pushed the 1.3.6 patches to master 2 days ago (including the version update), but not creating the tag 1.3.6 to make the release official.
Am I wrong?

Example:
https://github.com/eclipse/paho.mqtt.c/commit/b3da4d6456550f3e48cf131e4f8017e964ad33fa
https://github.com/eclipse/paho.mqtt.c/commit/03715f5ad0fcb6cca5a03645f32b65f9add0f979

**Comment by icraggs** [comment]
No you're not wrong.  I didn't intend to push to the master branch but it did happen and I had other things to do yesterday.  There are a few more things to add.

**Comment by icraggs** [comment]
Released today.
