### ISSUE TITLE
Remove empty persistence directories on a clean disconnect

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#965]
Some Rust and C++ users have complained about the file persistence directories littering their machines. I agree that it can turn into clutter after a while.

I suggest that the client remove the persistence directory on a clean disconnect if there are no inflight messages still being tracked (i.e. remove it when shutting down if everything is "done").

**Comment by icraggs** [comment]
It does if the directory is empty, see:

    #if defined(_WIN32) || defined(_WIN64)
	if ( _rmdir(clientDir) != 0 )
	{
    #else
	if ( rmdir(clientDir) != 0 )
	{
    #endif
		if ( errno != ENOENT && errno != ENOTEMPTY )
			rc = MQTTCLIENT_PERSISTENCE_ERROR;
	}

in MQTTPersistence.c pstclose().  So is this a different condition?

**Comment by fpagliughi** [comment]
Oh, interesting, I will test and report back.

**Comment by icraggs** [comment]
Any update on this one?

**Comment by icraggs** [comment]
Closing in the absence of more info.  It does remove the directory if there are no persistence files left.
