### ISSUE TITLE
double free() after ssl connection goes away

### ISSUE THREAD

**Issue by tstock5886** [eclipse-paho/paho.mqtt.c#967]
WebSocket.c WebSocket_close() will try to free(fd.wsbuf0), but it has already been free if(net->ssl == NULL). So this worked for me:

#if defined(OPENSSL)
                if (!net->ssl)
#endif
                        free(fd.wsbuf0); /* free temporary ws header */

**Comment by icraggs** [comment]
Do you have a test, or a trace as described in the readme?  I'd like to make sure all the cases are covered.

**Comment by icraggs** [comment]
More information not forthcoming.  This free shouldn't be omitted all the time as it will leave the buffer unallocated.  And it obviously isn't a problem all the time as the CI tests would find it.
