### ISSUE TITLE
Non-blocking request to get informations - so to say "pop" / "dequeue" instead of subscribe

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse-paho/paho.mqtt.c#968]
Hi there

To enable non-blocking requests to get informations - so to say "pop" / "dequeue" instead of subscribe - that would be a nice idea for some (special) cases.

Or is there a "hack" / workaround (method override with inheritation or ananymous class or something like that) possible with current version to reach that goal?

Thank you for your feedbacks.

With best regards,
Jan

**Comment by icraggs** [comment]
The MQTTAsync API is all non-blocking except for waitForCompletion.  Even in the MQTTClient API, messages are delivered asynchronously through the messageArrived callback (except for single-threaded mode).

**Comment by jayjupdhig** [comment]
ok thx, will look about it

**Comment by jayjupdhig** [comment]
I also opened an issue on https://github.com/thomasnordquist/MQTT-Explorer/issues/452.

With kind regards,
Jan

**Comment by jayjupdhig** [comment]
`Problem of Mosquitto or MQTT Explorer thomasnordquist/MQTT-Explorer#452`

WTF... that's wrong... it's not mentioned anymore, it was a mistake on my side. But i changed the link. So there is a bug on GitHub...

**Comment by icraggs** [comment]
I think this has been answered.

**Comment by jayjupdhig** [comment]
yes, i think so. now i will test it in a practical way and i think i will reach the goal. Thanks!! :-)
