### ISSUE TITLE
sslOptions: trustStore overrides CApath

### ISSUE THREAD

**Issue by bryant-ferguson** [eclipse-paho/paho.mqtt.c#969]
**Describe the bug**
If the trustStore option is specified the CApath option is ignored.
If this is desired behavior, this is just a documentation bug as this behavior should probably be noted.

**To Reproduce**
Take a library trace as outlined in the README, and/or have a program or describe the steps to reproduce the behavior:
1. Specify both CApath and trustStore

**Expected behavior**
I expected the trustStore and CApath certificates to be combined.

** Environment (please complete the following information):**
- OS: Linux
- Paho version: 1.3.0

**Comment by icraggs** [comment]
Both the trust store and CAPath are passed to the OpenSSL SSL_CTX_load_verify_locations call so it looks right to me.  But changes have been made in this area since 1.3.0 (which is now two years old).

**Comment by bryant-ferguson** [comment]
Fair enough. I just took a look and indeed it's changed quite a bit so I'll close this and go get an updated version to test with.
