### ISSUE TITLE
[Not a bug] SSLSocket error (1) in SSL_connect for socket 6 rc -1 errno 0 Undefined error: 0

### ISSUE THREAD

**Issue by tchakabam** [eclipse-paho/paho.mqtt.c#971]
**Describe the bug**

This is less of a bug report more than an issue with SSL connectivity we found with lib Paho (or also NodeJS based, probably any clients using OpenSSL TLS sockets) versus browser based connectivity (i.e any underlying WebSocket impl using an own built-in SSL eventually).

1. Using the following `paho_cs_sub` command line:
```
paho_cs_sub -t "joep/test" -c "wss://mqtt.liveryvideo.com:8883" -i "user2" -u "user2" -P "$TOKEN" 
```

Outputs:
```
Connect failed return code: Failure
```

Here we also tried using `ssl` instead of `wss` URL scheme.

Trace log (`--trace "min"`) of `paho_cs_sub`:
```
Trace : 3, 20201007 233432.441 (416228800)     (4)> MQTTStrncpy:905
Trace : 3, 20201007 233432.441 the src string is truncated
Trace : 3, 20201007 233432.441 (416228800)     (4)< MQTTStrncpy:915
Trace : 3, 20201007 233432.441 (416228800)    (3)< SSLSocket_setSocketForSSL:746 (1)
Trace : 3, 20201007 233432.441 (416228800)    (3)> SSLSocket_connect:757
Trace : 4, 20201007 233432.441 SSL handshake started write:unknown:unknown
Trace : 4, 20201007 233432.441 SSL state connect:before SSL initialization:(NONE)
Trace : 3, 20201007 233432.441 sent 0 256 buflen 5
Trace : 3, 20201007 233432.441 sent 772 22 buflen 317
Trace : 4, 20201007 233432.441 SSL state connect:SSLv3/TLS write client hello:(NONE)
Trace : 4, 20201007 233432.441 SSL connect:SSLv3/TLS write client hello
Trace : 3, 20201007 233432.441 (416228800)     (4)> SSLSocket_error:100
Trace : 3, 20201007 233432.441 SSLSocket error WANT_READ/WANT_WRITE
Trace : 3, 20201007 233432.441 (416228800)     (4)< SSLSocket_error:120 (2)
Trace : 3, 20201007 233432.441 (416228800)    (3)< SSLSocket_connect:815 (-22)
Trace : 3, 20201007 233432.441 (416228800)    (3)> MQTTClient_waitfor:2571
Trace : 3, 20201007 233432.441 (416228800)     (4)> MQTTClient_cycle:2474
Trace : 3, 20201007 233432.441 (416228800)      (5)> Socket_getReadySocket:249
Trace : 3, 20201007 233432.441 (416228800)       (6)> Socket_continueWrites:988
Trace : 3, 20201007 233432.441 (416228800)       (6)< Socket_continueWrites:1012 (0)
Trace : 3, 20201007 233432.441 (416228800)       (6)> isReady:225
Trace : 3, 20201007 233432.441 (416228800)       (6)< isReady:230 (1)
Trace : 3, 20201007 233432.441 (416228800)      (5)< Socket_getReadySocket:321 (6)
Trace : 3, 20201007 233432.441 (416228800)      (5)> MQTTClient_retry:2454
Trace : 3, 20201007 233432.441 (416228800)       (6)> MQTTProtocol_retry:784
Trace : 3, 20201007 233432.441 (416228800)       (6)< MQTTProtocol_retry:803
Trace : 3, 20201007 233432.441 (416228800)      (5)< MQTTClient_retry:2464
Trace : 3, 20201007 233432.441 (416228800)     (4)< MQTTClient_cycle:2560 (0)
Trace : 3, 20201007 233432.441 (416228800)     (4)> SSLSocket_connect:757
Trace : 3, 20201007 233432.498 received 0 256 buflen 5
Trace : 3, 20201007 233432.498 received 772 21 buflen 2
Trace : 4, 20201007 233432.498 SSL alert read:fatal:internal error
Trace : 4, 20201007 233432.498 SSL connect:error
Trace : 3, 20201007 233432.498 (416228800)      (5)> SSLSocket_error:100
Trace : 3, 20201007 233432.498 SSLSocket error (1) in SSL_connect for socket 6 rc -1 errno 0 Undefined error: 0
```

Find complete logs here: https://pastebin.com/yLrxnGjA

2. Using the mqtt.js command-line tool `mqtt` which runs on NodeJS for the same operation here, will cause a failure such as:

```
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

3. Subscribing with the same credentials using mqtt.js via a browser page is *successful*.

----> Any ideas? :)

It seems there might have been a change of CA on the server side. Is my system out of data in terms of lists maintained locally? How could I fix that? Would that explain that the browser supported connection works, as it may ship a CA list built-in vs NodeJS and Paho using the system/user shared ones?

** Environment (please complete the following information):**
 - OS: macOS
 - Version 10.14.6

Using current lib Paho master

**Comment by icraggs** [comment]
I wonder if it's anything to do with security level that was introduced in OpenSSL 1.1: 

https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_get_security_level.html

However I would expect a more meaningful message than 'SSL alert read:fatal:internal error' which is not helpful.  Are there any error messages on the server?  Given the unhelpful error message, I would experiment with a few different settings to see if you can get some more clues.

**Comment by tchakabam** [comment]
Hi Ian! Thanks for having taken a look. You are right, we were also bewildered about the missing info on causes in the error. Seems something quite unexpected happened for the  client side SSL impl if the error is "undefined" ? :) 

We have very limited access to the server-side as this is a IaaS (in fact CDN) provided broker.

What we know is, the exact same command line would work to connect earlier (as well as our app integration of lib Paho would). 

Then came a change/update of certificate on the server side (unfortunately I have also only limited info on that side).

The result in short is, all clients using lib OpenSSL seem to fail, while browser based implementations still succeed. Interesting one? :)

**Comment by icraggs** [comment]
I would ask the provider if any requirements have changed for TLS connections as a result of the new certificate.  The OpenSSL internal error could be the result of the server side TLS implementation denying access to the client.

**Comment by icraggs** [comment]
I think this has been answered.

**Comment by tchakabam** [comment]
thanks! we have filed a support request with the SAAS provider of the MQTT broker side here, still awaiting replies :)

**Comment by tchakabam** [comment]
Update: The MQTT service provider confirmed there was an SSL setup issue on their side (unfortunately no details here on what that exactly was, and why it worked with WebSocket+SSL in browsers but not from Paho). They have fixed it anyway somehow, Paho now connects properly as well. @icraggs Thanks to you for backing the theory of a server-side config issue in the first place here.
