### ISSUE TITLE
The SO file does not contain functions such as MQTTClient Connect

### ISSUE THREAD

**Issue by Krehizi** [eclipse-paho/paho.mqtt.c#975]
### such as
![捕获111](https://user-images.githubusercontent.com/27603839/96117339-86ccc600-0f1c-11eb-936a-e89cc8d31549.PNG)

### cmake （ubuntu 14.04）
`cmake -DPAHO_WITH_SSL=TRUE -DOPENSSL_SEARCH_PATH=/usr/local/openssl -DCMAKE_INSTALL_PREFIX=/usr/local/mqtt -DCMAKE_C_COMPILER=arm-himix100-linux-gcc`

### execute the nm instruction
`nm -D libpaho-mqtt3as.so > function.txt`

**function.txt , there is only one function starting with MQTTClient**

![捕获11](https://user-images.githubusercontent.com/27603839/96117927-62bdb480-0f1d-11eb-99bb-0f4f8ebe8b2c.PNG)

**Comment by icraggs** [comment]
That's the .so for the MQTTAsync API.  You need the libpaho-mqtt3cs.so

**Comment by Krehizi** [comment]
> That's the .so for the MQTTAsync API. You need the libpaho-mqtt3cs.so

Thank you. I just found out.
