### ISSUE TITLE
MQTTClient_publishMessage keep blocked when send huge message (80k-100k Bytes) in msgarrvd CallBack func

### ISSUE THREAD

**Issue by choujayyl** [eclipse-paho/paho.mqtt.c#978]
**Describe the bug**
MQTTClient_publishMessage keep block when send huge message (80k-100k Bytes)

**To Reproduce**
use MQTTClient_publishMessage  send huge message (80k-100k Bytes)  in msgarrvd CallBack func

**Expected behavior**
no blocked

**Screenshots**
func MQTTClient_publishMessage   just blocked

** Environment (please complete the following information):**
 - OS:ubuntu 16.04
 - Version v 1.3.5

**Additional context**
no

**Comment by icraggs** [comment]
In the MQTTClient API, the only callback you can make an API call from is connectionLost(), and then only the connect call so that you can reconnect.

The MQTTAsync API allows you to do this.

**Comment by icraggs** [comment]
Add a callback section to the doc.
