### ISSUE TITLE
Raspberry Pi Hello World Test

### ISSUE THREAD

**Issue by baqwas** [eclipse-paho/paho.mqtt.c#982]
**Is your feature request related to a problem? Please describe.**
I'm reluctant to post this _newbie_ request here but have checked community sites (as suggested in this repository) and unable to receive a specific response for my inability to get off the ground, please pardon my misuse of an issues list.

I am seeking a detailed Hello World example with respect to linking with shared paho.mqtt.c libraries to build the executable on Raspberry Pi 3 computer running the August Buster Raspberry Pi OS.

**Describe the solution you'd like**
A sample g++ (or gcc for now) command line statement so that the paho.mqtt.c runtime libraries are linked properly. (I fully understand the specific folder names are dependent on how the paho.mqtt.c libraries were built from source but even after successfully completing the ccmake/make/sudo make install operations I do not have a clear understanding). Where are the libraries? (need only sync functions for now).

**Describe alternatives you've considered**
These are the steps I've performed:

- Build requirements
```
$ sudo apt install build-essential gcc make cmake cmake-gui cmake-curses-gui
$ sudo apt install fakeroot fakeroot devscripts dh-make lsb-release
$ sudo apt install libssl-dev
$ sudo apt install doxygen graphviz
```
- Source
`$ git clone https://github.com/eclipse/paho.mqtt.c`
- Compile
`$ ccmake ..`
- Build
```
$ make
$ sudo make install
```
- Test
I'm able to include the MQTTClient.h file with the following compiler directive:
`-I/home/pi/projects/paho.mqtt.c/src`

Unfortunately, the `-l/usr/lib/arm-linux-fnueabihf` directive for the library fails even though the file `libanl.so` is present in the folder.
Here is output from the link operation:
```
$ make
g++ -lm -lwiringPi  -o pubsync pubsync.o /usr/lib/arm-linux-gnueabihf/libanl.so
/usr/bin/ld: pubsync.o: in function `main':
/home/pi/projects/mqtt/pubsync.cpp:19: undefined reference to `MQTTClient_create'
/usr/bin/ld: /home/pi/projects/mqtt/pubsync.cpp:23: undefined reference to `MQTTClient_connect'
/usr/bin/ld: /home/pi/projects/mqtt/pubsync.cpp:32: undefined reference to `MQTTClient_publishMessage'
/usr/bin/ld: /home/pi/projects/mqtt/pubsync.cpp:36: undefined reference to `MQTTClient_waitForCompletion'
/usr/bin/ld: /home/pi/projects/mqtt/pubsync.cpp:38: undefined reference to `MQTTClient_disconnect'
/usr/bin/ld: /home/pi/projects/mqtt/pubsync.cpp:39: undefined reference to `MQTTClient_destroy'
collect2: error: ld returned 1 exit status
make: *** [Makefile:24: pubsync] Error 1
$ 
```
The Makefile to build the Hello World test sample is:

```
APP = pubsync
CC = g++
CFLAGS = -g -Wall
INCLUDES = -I/home/pi/projects/paho.mqtt.c/src
OBJS = ${APP}.o
LIBS = -lm -lwiringPi
${APP} : ${OBJS}
        ${CC} ${LIBS} -o ${APP} ${OBJS} /usr/lib/arm-linux-gnueabihf/libanl.so
%.o: %.cpp ${DEPS}
        ${CC} ${CFLAGS} ${INCLUDES} -c $^ -o $@
```

**Additional context**
To get off the ground for the first test, I tried to suppress async and SSL considerations and rely on the simple sync function. Here are the parameters for the build from source for the library using the ccmake operation:
![Screenshot from 2020-10-21 12-48-23](https://user-images.githubusercontent.com/7071255/96758136-01259c00-139c-11eb-8fa0-3be7eed7dab9.png)
![Screenshot from 2020-10-21 12-48-46](https://user-images.githubusercontent.com/7071255/96758142-04b92300-139c-11eb-8c5d-0b3c4b110f6f.png)

Also, FWIW, the computer runs the Python paho client (as installed from PyPi last week). Of course, off-topic!

Thanks for any advice.

Kind regards.

**Comment by icraggs** [comment]
I'm not sure what ccmake does - I've never used that.   Anyway, the supplied Makefile (if ccmake hasn't overwritten it), builds the libraries and samples so it's a good place to look for an example of building applications.

Your command line appears to lack the option to tell the linker to link with the Paho C library:

    -lpaho-mqtt3cs

For instance, here is a line of output from running make on the command line:

    cc -o build/output/samples/paho_cs_pub src/samples/paho_cs_pub.c -lpaho-mqtt3cs  -I src -Wl,--start-group -lpthread -lanl -lssl -lcrypto -Wl,--end-group -L build/output src/samples/pubsub_opts.c

**Comment by baqwas** [comment]
Thx for the quick feedback, @icraggs. You've given me sufficient details to resume my tests shortly.

Kind regards.

**Comment by baqwas** [comment]
Hello @icraggs,

I found my mistake! For some reason, the library filenames have a prefix - **lib**. The files (for one set) are along the following lines:

```
/usr/local/lib/libpaho-mqtt3c.so
/usr/local/lib/libpaho-mqtt3c.so.1
/usr/local/lib/libpaho-mqtt3c.so.1.3.6
```

Thanks again for helping me to plod along. I should be able to port some of my Python samples now.

Kind regards.
