### ISSUE TITLE
Run Ok in local virtualbox environment but can`t connect in cross compiler

### ISSUE THREAD

**Issue by mandy-yan** [eclipse-paho/paho.mqtt.c#987]
As the tile say, i have cross compile the paho successfully, and i use the .so， but same code, when i run it in cross environment, it can`t connect the broker(Actually, it can ping the broker), and the error code is -8

i don`t know what happened?  pls, give me some advice

![image](https://user-images.githubusercontent.com/17793782/97284287-d647b600-187b-11eb-8dad-f7ea59d9efd0.png)

**Comment by icraggs** [comment]
The issue template asks for a trace - that would have been nice.  And any information about the source and target platforms.  And what broker you were trying to connect to.  Etc. 

I suggest you try the compiler option REVERSED to change the order of the MQTT header bitfields.

**Comment by mandy-yan** [comment]
> The issue template asks for a trace - that would have been nice. And any information about the source and target platforms. And what broker you were trying to connect to. Etc.
> 
> I suggest you try the compiler option REVERSED to change the order of the MQTT header bitfields.

sorry for that,
the source platform is x86_64, like this:
![image](https://user-images.githubusercontent.com/17793782/97380171-74ca2a80-1901-11eb-9d06-8619b7306bac.png)

the target platfrom is mips(MT7621), like this:
![image](https://user-images.githubusercontent.com/17793782/97380651-7811e600-1902-11eb-8127-2e8f15c22b91.png)

 
my code is below:
void MQTT_InitAndConnect(char *clientid)                                                                                                                                     
{
     int ret;
     MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
 
     while (1)
     {
         ret = MQTTClient_create(&client, MQTT_ADDRESS, (const char *)clientid, MQTTCLIENT_PERSISTENCE_NONE, NULL);
         if(ret != MQTTCLIENT_SUCCESS)
         {
             logger_debug("->URL:%s\n", MQTT_ADDRESS);
             logger_fatal("MQTTClient create failed\n");
             return;
         }
         else
         {
             logger_debug("->URL:%s\n", MQTT_ADDRESS);
             logger_info("MQTTClient create success\n");     
         }
 
         if(MQTTClient_setCallbacks(client, NULL, connlost, msgarrvd, delivered) != MQTTCLIENT_SUCCESS)
         {
             logger_warn("MQTTClient setcallbacks failed\n\n");
             MQTTClient_destroy(&client);
             return ;
         }
 
         conn_opts.keepAliveInterval = 20;
         conn_opts.username = MQTT_USERNAME;
         conn_opts.password = MQTT_PASSWORD;
         conn_opts.cleansession = 1;
 
         if((ret = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
         {   
             MQTTClient_destroy(&client);
             logger_debug("[MQTTClient username:] %s\n", MQTT_USERNAME);
             logger_debug("[MQTTClient password:] %s\n", MQTT_PASSWORD);
 
             logger_warn("MQTTClient connect failed[%d], try..\n\n", ret);
             sleep(5);
         }
         else
        {
              logger_info("MQTTClient connect successed\n\n");
              break;
         }
    }
}

**Comment by icraggs** [comment]
OK.  Have you tried the REVERSED compile definition?   The -8 (look in the header file) implies the structure (connect options presumably) is not incorrectly filled out (the initializer should take care of this).  Take a client library trace (as described in the readme) to determine whether this is in fact the error or it's something else.

**Comment by mandy-yan** [comment]
i can’t understand what the word mean.&nbsp;REVERSED compile definition?


the conn_options i have been init at the begin in program. and i print the related value to trace how it can have the -8， but as the result, the related value is ok, &nbsp;i can’t understand why it has -8, i feel that’s impossible&nbsp;



------------------ Original ------------------

**Comment by mandy-yan** [comment]
is it possible the cross compile could be have something wrong?





------------------ Original ------------------

**Comment by icraggs** [comment]
If you take a trace, that could shed some light on what's happening.  -8 is invalid structure - it could be overwritten or filled out incorrectly.

**Comment by mandy-yan** [comment]
i printed some variables to trace, from the result. i can’t see any issues, the variables looked ok. so i puzzle where the problem be from?
and the local platfrom runs very well!&nbsp;





------------------ Original ------------------

**Comment by icraggs** [comment]
Taking a client library trace, as described in the readme might help pinpoint what's going on - at least confirm what the -8 return indicates.

You will see from the code that MQTTCLIENT_BAD_STRUCTURE (-8) can be returned from MQTTClient_connect if the checks on the connect options, will options or SSL options structures fail.  It's possible the connect options structure is being overwritten.

**Comment by mandy-yan** [comment]
if&nbsp;the connect options structure is being overwritten, why i print the values in conn options &nbsp;are all ok
head: MQTC&nbsp;
version: 7
will/ssl: NULL
these three values printed seem OK





------------------ Original ------------------

**Comment by mandy-yan** [comment]
i know where i am wrong, it is my mistake, So , i close my issues

**Comment by ZeeMoros** [comment]
@mandi-china 

Can you point to your mistake ? I think I may have done the same thing --'

**Comment by mandy-yan** [comment]
the so unmatch with the program





------------------ Original ------------------
From: ZeeMoros ***@***.***&gt;
Date: Thu,Mar 11,2021 6:34 PM
To: eclipse/paho.mqtt.c ***@***.***&gt;
Cc: Mandy.yan ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [eclipse/paho.mqtt.c] Run Ok in local virtualbox environment but can`t connect in cross compiler (#987)





 
@mandi-china
 
Can you point to your mistake ? I think I may have done the same thing --'
