### ISSUE TITLE
Can I use different threads to start different clients to connect to different servers?

### ISSUE THREAD

**Issue by leowoki** [eclipse-paho/paho.mqtt.c#992]
Can I use different threads to start different clients to connect to different servers?Both clients were offline when I tried to do this.

**Comment by icraggs** [comment]
yes

**Comment by nirmitdesai** [comment]
Let's say I've a client connected to particular endpoint and I want to now connect to a different endpoint, what's the right way to go about it? Disconnect old client, wait for its callback, destroy the client and then create a new client again (with same client ID as previous one)?

**Comment by leowoki** [comment]
> yes

When my second client successfully connects to another server, the first client is forced offline. Is there anything in the code that needs to be set?  Can you give me an example for my reference?

**Comment by icraggs** [comment]
If you connect two clients to the same server they must have different client ids, otherwise the first one to be connected will be thrown off.  This is a characteristic of MQTT.  

If you are really connecting to two different servers, then this will not be the case, but it sounds exactly like it.

**Comment by icraggs** [comment]
> Let's say I've a client connected to particular endpoint and I want to now connect to a different endpoint, what's the right way to go about it? Disconnect old client, wait for its callback, destroy the client and then create a new client again (with same client ID as previous one)?

That's one way.  But you don't have to.  There are tests, in the supplied test suite, that have more than one client connected simultaneously (to the same server, with different client ids).

**Comment by leowoki** [comment]
> If you connect two clients to the same server they must have different client ids, otherwise the first one to be connected will be thrown off. This is a characteristic of MQTT.
> 
> If you are really connecting to two different servers, then this will not be the case, but it sounds exactly like it.

Emm... When I change the connection order, they all connect, is this because the servers are different？？

**Comment by icraggs** [comment]
Without more information I'm just guessing.  Are there any error or warning messages on the server(s)?  How different are the servers?  What server software is being run?  

Providing a trace of a failing case (as described in the readme) might shed some light.  Using the protocol trace level first to get an overall idea of what's happening.  If the server supports MQTT 5.0 and you're not using it, then that might provide more information, if indeed it's a server error or decision.

**Comment by nirmitdesai** [comment]
> > Let's say I've a client connected to particular endpoint and I want to now connect to a different endpoint, what's the right way to go about it? Disconnect old client, wait for its callback, destroy the client and then create a new client again (with same client ID as previous one)?
> 
> That's one way. But you don't have to. There are tests, in the supplied test suite, that have more than one client connected simultaneously (to the same server, with different client ids).

I did see the tests. My scenario is a bit different. I use 1 client with say client ID = FOO and connect to a server. If I get SSL error, in the ssl error callback itself, I call MQTTAsync_Disconnect followed by MQTTAsync_Destroy and then a new thread will connect to another server using same client ID = FOO. I am currently debugging a crash in clientCompareSocket when I run above code. 
Is it safe to call the Disconnect and Destroy APIs from SSL error callback function?

**Comment by icraggs** [comment]
@nirmitdesai no, it's not safe to call destroy from an SSL error callback.  Disconnect might be ok, but you'd have to wait for the disconnect to complete before calling destroy (and not just by setting the disconnect timeout to 0), and waiting in a callback is a bad idea.

If you want to check a sequence of sever URIs in turn, you can use the serverURIs connect option.

**Comment by leowoki** [comment]
> Without more information I'm just guessing. Are there any error or warning messages on the server(s)? How different are the servers? What server software is being run?
> 
> Providing a trace of a failing case (as described in the readme) might shed some light. Using the protocol trace level first to get an overall idea of what's happening. If the server supports MQTT 5.0 and you're not using it, then that might provide more information, if indeed it's a server error or decision.

Thanks, I've found the cause of the problem, I go to synchronize the time with the server after connecting to it. But the time zones of the two servers don't match, which causes me to have a connection that times out.

**Comment by nirmitdesai** [comment]
> @nirmitdesai no, it's not safe to call destroy from an SSL error callback. Disconnect might be ok, but you'd have to wait for the disconnect to complete before calling destroy (and not just by setting the disconnect timeout to 0), and waiting in a callback is a bad idea.
> 
> If you want to check a sequence of sever URIs in turn, you can use the serverURIs connect option.

Okay thanks a lot. I did that and it fixed my crash. I've one final question since it's related to disconnect, I am posting it here only.

Is there a way to do a synchronous disconnect with MQTTAsync_Client? The reason is asynchronous disconnect adds some delay when shutting down app/service which causes app/service to shut down a bit late, after the disconnect callback comes in, all resources are freed etc

**Comment by icraggs** [comment]
@nirmitdesai it depends whether there are outstanding messages being processed in either direction, for QoS 1 or 2 especially, and whether you want them to complete.   There is a timeout setting on the disconnect so you could set that and take a trace (as described in the readme - minimum level).

**Comment by icraggs** [comment]
Questions answered, I think.
