### ISSUE TITLE
/usr/lib/x86_64-linux-gnu/libssl.so: file not recognized: File format not recognized

### ISSUE THREAD

**Issue by emeraldvii** [eclipse-paho/paho.mqtt.c#993]
I am trying to cross-compile on an arm device. I am currently on ubuntu18.04 x64. This was also using the toolchain provided. I ran `cmake -Bbuild -H. -DPAHO_WITH_SSL=TRUE -DPAHO_ENABLE_TESTING=OFF -DOPENSSL_LIB_SEARCH_PATH=/tmp/libssl-dev/usr/lib/arm-linux-gnueabihf -DOPENSSL_INC_SEARCH_PATH="/tmp/libssl-dev/usr/include/openssl;/tmp/libssl-dev/usr/include/arm-linux-gnueabihf" -DCMAKE_TOOLCHAIN_FILE=~/paho.mqtt.c/toolchain.linux-arm11.cmake` 

`sudo cmake --build build/ --target install`

I also followed this https://stackoverflow.com/questions/60821697/how-to-build-openssl-for-arm-linux and used symbolic link on /usr/lib/x86_64-linux-gnu/libssl.so to /usr/lib/aarch64-linux-gnu/libssl.so and still same error 

Is there are any resource I should look into before cross-compiling, I am relatively new to software engineering ty.

**Comment by icraggs** [comment]
I never cross compile if I can help it.  Install gcc and tools on the target platform and build there.  If you're using a platform which requires cross-compiling, presumably it comes with some instructions/help.

The 'file' command on Linux will tell you how an executable or shared library was built.  You need to make sure their properties are the same.

**Comment by icraggs** [comment]
I hope you have solved your issue.
